specs/distros.rst

This initial draft targets a proposed API for the new distro submodule,
which in turn is composed by other cohesive subnamespaces, that targets
one specialized are. A basic API is laid out, which describes how namespaces
interacts with objects from other namespaces and so on.
I propose to have a spec folder in the repo, where we could track our design decissions and all that, a la Python's PEPs. A location such as this helps when we are in doubt why something was added as is.
Anyway, this draft mostly targets a shallow description of the API. A more thorough document will follow it, if the proposed changes are accepted. I'll also have a pull request with the base classes and all the goodies, so that we could start putting actual code in the distros in the meanwhile.

Add a spec draft for the new distro namespace.

---

cloudinit/sources/__init__.py

If I run cloud-init with a config drive containing a metadata file which has
local-hostname set to null, I get the following traceback:
File "/usr/lib/python2.7/site-packages/cloudinit/sources/__init__.py", line 447, in find_source
if s.get_data():
File "/usr/lib/python2.7/site-packages/cloudinit/sources/__init__.py", line 132, in get_data
self._get_standardized_metadata())
File "/usr/lib/python2.7/site-packages/cloudinit/sources/__init__.py", line 110, in _get_standardized_metadata
'local-hostname': self.get_hostname(),
File "/usr/lib/python2.7/site-packages/cloudinit/sources/__init__.py", line 317, in get_hostname
if util.is_ipv4(lhost):
File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 544, in is_ipv4
toks = instr.split('.')
Tested on …

Fix metadata check when local-hostname is null

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/test_datasource/test_azure.py

Azure's Instance Metadata Service (IMDS) reports multiple IPv6
addresses, via the http://169.254.169.254/metadata/instance/network
route.
When the the list of ipAddresses under the 'ipv6' interface key is
greater than one, the first IP is obtained via a dhcp6 configurtion,
and additional ipAddress entries will be configured with a static IPv6
CIDR.

azure: support secondary ipv6 addresses

---

cloudinit/distros/freebsd.py

on FreeBSD our helpers live in /usr/local/lib/cloud-init/
lp: #1852491

correctly set usr_lib_exec path for FreeBSD distro

---

cloudinit/net/eni.py
cloudinit/net/netplan.py
cloudinit/net/network_state.py
cloudinit/net/sysconfig.py
cloudinit/sources/helpers/openstack.py
tests/unittests/test_datasource/test_configdrive.py
tests/unittests/test_net.py

Router advertisements are required for the default route
to be set up, thus accept_ra should be enabled for
dhcpv6-stateful.
sysconf: IPV6_FORCE_ACCEPT_RA controls accept_ra sysctl.
eni: mode static and mode dhcp 'accept_ra' controls sysctl.
Add 'accept-ra: true|false' parameter to config v1 and
v2. When True: accept_ra is set to '1'. When False:
accept_ra is set to '0'. When not defined in config the
value is left to the operating system default.
This change also extend the IPv6 support to distinguish
between slaac and dhcpv6-stateless. SLAAC is autoconfig
without any options from DHCP, while stateless auto-configures
the address and the uses DHCP for other options.
LP: #1806014
LP: #1808647

net: IPv6, accept_ra, slaac, stateless

---

tests/unittests/test_datasource/test_cloudsigma.py

The cloudsigma tests had few test cases that were not getting
all the "mocks" set up correctly.  Specifically is_running_in_cloudsigma
was not getting replaced and calls would leak through to
util.read_dmi_data.

tests: Fix cloudsigma tests when no dmidecode data is present.

---

cloudinit/ec2_utils.py
cloudinit/sources/DataSourceCloudStack.py
cloudinit/sources/DataSourceEc2.py
cloudinit/sources/DataSourceExoscale.py
cloudinit/sources/DataSourceMAAS.py
cloudinit/sources/DataSourceOpenStack.py
cloudinit/url_helper.py
tests/unittests/test_datasource/test_cloudstack.py
tests/unittests/test_datasource/test_ec2.py

AWS not supports a new version of fetching Instance Metadata[1].
Update cloud-init's ec2 utility functions and update ec2 derived
datasources accordingly.  For DataSourceEc2 (versus ec2-look-alikes)
cloud-init will issue the PUT request to obtain an API token for
the maximum lifetime and then all subsequent interactions with the
IMDS will include the token in the header.

ec2: Add support for AWS IMDS v2 (session-oriented)

---

cloudinit/tests/test_util.py
cloudinit/util.py
tests/unittests/test_net.py

a lot of our code assumes that we're on Linux, and all it needs to know
then is which exact distro it's on. We have structured our code such,
that FreeBSD *is* a distro, so before resorting to return nothing on
FreeBSD whenever get_linux_distro() is queried, we check if we're on
FreeBSD, and return distro_name = 'freebsd' and 'distro_version' with
the result of `uname -r`.
LP: #1815030
----
Since `is_FreeBSD()` is used a lot, which uses `system_info()`, which uses `get_linux_distro()` we add caching, by decorating the following functions with `@lru_cache`:
- get_architecture()
- _lsb_release()
- is_FreeBSD
- get_linux_distro
- system_info()
- _get_cmdline()
Since [functools](https://docs.python.org/3/library/functools.html) only exists in Python 3, only python 3 will benefit from this …

allow get_linux_distro() to return 'freebsd' for FreeBSD

---

cloudinit/config/cc_set_passwords.py
cloudinit/config/tests/test_set_passwords.py
cloudinit/distros/__init__.py
cloudinit/distros/freebsd.py
tests/unittests/test_distros/test_generic.py
tools/build-on-freebsd

Add FreeBSD support to `cc_set_passwords`.
FreeBSD does not come with chpasswd binary, a chpasswd port[1] exists
but it's not the same tool than the one from Linux[2].
Finally, NetBSD and OpenBSD don't have the chpasswd binary at all, so
an abstraction layer will be needed.
[1]: https://www.freshports.org/www/chpasswd/
[2]: https://github.com/shadow-maint/shadow/blob/master/src/chpasswd.c

set_passwords: support for FreeBSD

---

tools/.lp-to-git-user

Hi, I would like to start contributing to Cloud-init.  I've tried following the process on the following  [link](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html).  But seems that we need to fork on launchpad through ssh, which I can't do from my location.  I instead looked at how people where starting to contribute and matched my lp user myself to my github user.
Please let me know if I need to do something different.

lp-to-git-users: adding elafontaine

---

cloudinit/sources/helpers/azure.py
cloudinit/tests/test_url_helper.py
cloudinit/url_helper.py
cloudinit/user_data.py
cloudinit/util.py
tests/unittests/test_datasource/test_azure_helper.py

Headers param was accidentally omitted and no longer passed through to readurl due to
a previous commit. To avoid this omission in the future, drop positional param definitions
from read_file_or_url since all params are passed through to readurl when we are not
operating on a file.
In util:read_seeded, correct the once case where invalid positional param file_retries was
being passed into  read_file_or_url. Also drop duplicated file:// prefix addition from
read_seeded as read_file_or_url does that work anyway.
LP: #1854084

url_helper: read_file_or_url should pass headers param into readurl

---

setup.py

Amazon Linux requires USR_LIB_EXEC to be set to "usr/libexec". This PR introduces parsing of /etc/system-release-cpe to identify Amazon Linux set the proper value.

Amazon Linux sets libexec to /usr/libexec

---

.travis.yml

Until we have a clear issue with CI throughput, let's make sure that
we're testing master.
This reverts commit 21967a2dedc781e05cf62c80fb730d0ed5973c8b.

Revert "travis: only run CI on pull requests"

---

cloudinit/ssh_util.py
tests/unittests/test_sshutil.py

Currently cloud-init does not know how to handle multiple file
configuration on section AuthorizedKeysFile of ssh configuration.
cloud-init will mess up the home user directory by creating bogus
folders inside it.
This patch provides a fix for this erroneous behavior. It gathers all
keys from all the files listed on the section AuthorizedKeysFile of ssh
configuration and merge all of them inside home user
~/.ssh/authorized_keys of the vm deployed.
Resolves: rhbz#1642008

Multiple file fix for AuthorizedKeysFile config

---

SECURITY.md
doc-requirements.txt
doc/rtd/conf.py
doc/rtd/index.rst
doc/rtd/topics/security.rst
tox.ini

This enables the ability to show the security policy on both GitHub and
on the readthedocs site. To do this, enable the ability to import
Markdown based files and translate them to rst.

docs: Add security.md to readthedocs

---

doc/rtd/topics/tests.rst

doc8 does not know about the ephasize-lines portion of code-block and
throws an error. As this is the only place right now I am going to
remove it untill we can find a better solution. rstcheck and
restructuredtext-lint have issues with sphinx declaritives, so
doc8 is still the best to use for now.

docs: fix line length and remove highlighting

---

cloudinit/net/network_state.py
cloudinit/net/tests/test_network_state.py

Sending a valid but empty v1 network config resulted in a
stacktrace during execution.  Update the network_state
parse path to specific check if the 'config' key is None
(not present) versus being present but explicitly empty.
Also add some network_state unittests.
LP: #1852496

network_state: handle empty v1 config

---

cloudinit/net/dhcp.py
cloudinit/net/tests/test_dhcp.py

This is an attempt to fix the Centos bug with Cloud-init dhclient lease format.
Please see https://bugs.launchpad.net/cloud-init/+bug/1850642 for details

Lp 1850642

---

cloudinit/distros/__init__.py
cloudinit/distros/amazon.py

This is the 1st part of adding an Amazon distro definition to cloud-init.
From original work by: Andrew Jorgensen <ajorgens@amazon.com>
Reviewed-by: Matt Nierzwicki <nierzwic@amazon.com>
Reviewed-by: Ethan Faust <efaust@amazon.com>

Add an Amazon distro in the redhat OS family

---

tests/unittests/test_ds_identify.py
tools/ds-identify

On non-Linux systems, `/sys` won't be available.
In these cases, we can query `dmidecode(8)` directly.
To do this, we need a mapping function, since the names in
`/sys/class/dmi/id` do not match up with the ones dmidecode uses.
This pull request fixes LP#1852442

if /sys is not available, use dmidecode

---

packages/debian/manpages

Once the manpages are reviewed and added, this will add them to the debian directory. A package build will then pick up and deliver the pages.
Confirmed in a Bionic multipass instance.

debian: add reference to the manpages

---

debian/control

Drop alternate dependency on ifupdown as it is no longer supported in
Ubuntu.

d/control: drop alternate dependency on ifupdown

---

cloudinit/config/tests/test_users_groups.py
cloudinit/distros/freebsd.py

on FreeBSD, lock_passwd is implemented as `pw usermod <user> -h -`
This does not lock the account. It prompts for a password change on the console during cloud-init run.
To lock an account, we have to execute: `pw lock <name>`.
-----
Fixes LP # 1854594

fix unlocking method on FreeBSD

---

config/cloud.cfg.d/README

Update README to specify that only files with the '.cfg' extension are
read in this folder.
LP: #1855006

config/cloud.cfg.d: update README

---

doc/examples/cloud-config-add-apt-repos.txt
doc/rtd/topics/examples.rst

More clearly differentiate between the primary apt repo configuration
and any 3rd party apt configuration.
LP: #1832823

docs: clear up apt config sections

---

cloudinit/cmd/tests/test_query.py

The query command checks the user's uid when running and takes two
different code paths. As a normal user is returns fake data, that these
tests were expecting. As a root user, the actual user and vendor data
files are ready.
LP: #1856096

tests: mock uid when running as root

---

cloudinit/distros/freebsd.py

Specifically, revert the changes to logic which are incorrect.  The
testing introduced is for a separate part of the codebase, so is
retained.
This (partially) reverts commit
e2840f1771158748780a768f6bfbb117cd7610c6.

Partially revert "fix unlocking method on FreeBSD"

---

.travis.yml
tox.ini

This makes it easier to debug differences in test behaviour between
Travis and local developer environments.

ci: emit names of tests run in Travis

---

sysvinit/freebsd/cloudinit

Depends on devd to be sure the NIC device drivers are loaded in time.

freebsd: cloudinit service requires devd

---

HACKING.rst

The previous language suggested that only people who had signed the CLA
previously needed to prove their GH identity, which is not the case.

HACKING.rst: clarify that everyone needs to do the LP->GH dance

---

.travis.yml
tox.ini

Specifically, drop it from the default list of environments that tox will run, and from Travis.
Per https://lists.launchpad.net/cloud-init/msg00236.html, 19.4 was the last release with official Python 2.7 support.
(We retain the configuration in tox.ini for now, for any remaining Python 2.7 needs.)

ci: remove Python 2.7 from CI runs

---

doc/examples/cloud-config-update-apt.txt

Other options near it use the non-default value, so the inconsistency
has lead to confusion for readers.

doc: make apt_update example consistent

---

cloudinit/config/cc_disk_setup.py

The module cc_disk_setup.py fails when trying to initalize a swap partition with mkswap.
This is because 'lookup_force_flag' returns an empty string (''), which is taken as actual argument when launching mkswap , resulting in an error:
Unexpected error while running command.
Command: ['/usr/sbin/mkswap', '/dev/sdb', '']
Exit code: 1
Reason: -
Stdout:
Stderr: mkswap: invalid block count argument: ''
Preventing swap to work (this can be seen when using vmware hypervisor)
This patch simply remove the empty argument.

fixed minor bug with mkswap in cc_disk_setup.py

---

cloudinit/analyze/tests/test_boot.py
cloudinit/tests/test_util.py
cloudinit/util.py

Several tests depend on `platform.dist`, a.k.a. `platform.linux_distribution`. This function was removed in Python 3.8. To make the tests work, move some of them to mocking the internal `util.get_linux_distro` instead. For the tests for `util.get_linux_distro` itself, allow mock to create the function if it doesn't exist. The function's behavior in absence of `platform.dist` is already tested by `test_get_linux_distro_no_impl`.

Make tests work with Python 3.8

---

cloudinit/tests/test_util.py
cloudinit/util.py

and fix the bugs: pass binary instead of string to sysctlbyname(), and
unpack the "return value" in a struct, rather than in single integer.
lp:1853160

move uptime's else branch into its own function

---

tests/cloud_tests/testcases/modules/ssh_auth_key_fingerprints_disable.py

Adapt the test to the new capitalization introduced in
8116493950e7c47af0ce66fc1bb5d799ce5e477a.

ssh_auth_key_fingerprints_disable test: fix capitalization

---

cloudinit/distros/freebsd.py

We often map exception when is not necessary. This commit clean up
the FreeBSD distro file.

freebsd: remove superflu exception mapping

---

cloudinit/config/cc_growpart.py
tests/unittests/test_handler/test_handler_growpart.py

Currently, cloud-init will happily try to run `gpart` on Linux even
though on most distributions this a different tool [1]. Extend the
availability check to make sure the `gpart` present is really the BSD
variant, to avoid accidental execution.
Also add a pointer to the docs, so that people do not try to install
gpart on Linux in the expectation it will work with this module.
[1] https://github.com/baruch/gpart

Only use gpart if it is the BSD gpart

---

cloudinit/config/cc_apt_configure.py
cloudinit/distros/debian.py
cloudinit/util.py
tests/unittests/test_handler/test_handler_apt_source_v3.py

util.get_architecture() recently was wrapped using python3's lru_cache()
which will cache the result so we only invoke 'dpkg --print-architecture'
once.  In practice, cloud-init.log will show multiple invocations of the
command.  The source of this was that the debian Distro object implements
the get_primary_arch() with this command, but it was not calling it from
util, but issuing a util.subp() directly.  This branch also updates
cc_apt_configure methods to fetch the arch value from the distro class,
and then ensure that the methods apt_configure calls pass the arch value
around.
- drop lsb_release and get_architecture wrappers as lru_cache()
handles multiple values in its cache.

Ensure util.get_architecture() runs only once

---

cloudinit/config/cc_apt_configure.py
cloudinit/distros/debian.py
cloudinit/util.py
tests/cloud_tests/config.py
tests/cloud_tests/platforms/nocloudkvm/platform.py
tests/unittests/test_handler/test_handler_apt_configure_sources_list_v1.py
tests/unittests/test_handler/test_handler_apt_configure_sources_list_v3.py
tests/unittests/test_handler/test_handler_apt_source_v1.py
tests/unittests/test_handler/test_handler_apt_source_v3.py

This makes it clearer that we should only use this in code paths that
will definitely have dpkg available to them.

util: rename get_architecture to get_dpkg_architecture

---

cloudinit/cmd/query.py
cloudinit/handlers/__init__.py
cloudinit/log.py
cloudinit/mergers/__init__.py
cloudinit/mergers/m_dict.py
cloudinit/mergers/m_list.py
cloudinit/mergers/m_str.py
cloudinit/net/cmdline.py
cloudinit/reporting/handlers.py
cloudinit/sources/DataSourceOVF.py
cloudinit/sources/__init__.py
cloudinit/sources/helpers/openstack.py
cloudinit/type_utils.py
cloudinit/url_helper.py
cloudinit/user_data.py

cloud-init master no longer supports Python 2, so we no longer need to depend on the six library. This PR drops the usage of six in some parts of the codebase, to start us down that path.
(It also sorts imports where I was touching them anyway.)

Start removing dependency on six

---

.readthedocs.yaml

This should ensure that all its dependencies are installed during doc
generation.
LP: #1860450

.readthedocs.yaml: install cloud-init when building docs

---

cloudinit/config/cc_mounts.py
tests/unittests/test_handler/test_handler_mounts.py

When creating a swap file on an xfs filesystem, fallocate cannot be used.
Doing so results in failure of swapon and a message like:
swapon: swapfile has holes
The solution here is to maintain a list (currently containing only XFS)
of filesystems where fallocate cannot be used. The, on those fileystems
use the slower but functional 'dd' method.
Based on initial pull request:
https://code.launchpad.net/~adobrawy/cloud-init/+git/cloud-init/+merge/354680
And further comments from Scott Moser:
http://paste.ubuntu.com/p/8pVhczVqG3/

Do not use fallocate in swap file creation on xfs.

---

tests/unittests/test_data.py
tests/unittests/test_distros/test_generic.py
tests/unittests/test_distros/test_netconfig.py
tests/unittests/test_handler/test_handler_apt_configure_sources_list_v1.py
tests/unittests/test_handler/test_handler_apt_configure_sources_list_v3.py
tests/unittests/test_handler/test_handler_apt_source_v1.py
tests/unittests/test_handler/test_handler_apt_source_v3.py
tests/unittests/test_handler/test_handler_ca_certs.py
tests/unittests/test_handler/test_handler_growpart.py
tests/unittests/test_handler/test_handler_lxd.py
tests/unittests/test_handler/test_handler_mounts.py
tests/unittests/test_handler/test_handler_spacewalk.py
tests/unittests/test_util.py

We only run on Python 3 now, so we can unambiguously expect
unittest.mock to exist.

cloudinit: remove ImportError handling for mock imports

---

packages/brpm
packages/pkg-deps.json

The Python 2 deprecation broke the RPM build; the scripts have to be adapted
to use Python 3. Changes:
1. Make packages/brpm use python3 as its interpreter.
2. Satisfy the Py3 dependencies using python36-* packages instead of
python34-* packages.
Change (2) is not strictly necessary, but adapts the dependencies to CentOS 7,
our default CentOS test target.

Make the RPM build use Python 3

---

tools/run-container

Drop support for specifying an Python interpreter different from python3
from tools/run-container.

tools/run-container: drop support for python2

---

tools/run-container

Fixes shellcheck warning SC2236.

run-container: use 'test -n' instead of 'test ! -z'

---

doc/examples/cloud-config-disk-setup.txt

fixes typo at `doc/examples/cloud-config-disk-setup.txt`; Cavaut => Caveat

docs: fix typo

---

sysvinit/freebsd/cloudconfig
sysvinit/freebsd/cloudfinal
sysvinit/freebsd/cloudinit
sysvinit/freebsd/cloudinitlocal

bugzilla ref: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224361
svn rev: https://svnweb.freebsd.org/ports?view=revision&revision=457768

import sysvinit patches from freebsd-ports tree

---

cloudinit/config/tests/test_set_passwords.py

When running tox we see stderr output from one of the cc_set_password tests.
This patch mocks out the write to sys.stderr so we no longer see that message
while running unittests.

unittest: fix stderr leak in cc_set_password random unittest output.

---

debian/control

These just never got updated after cloud-init move it's upstream to
github.

debian/control: Update vcs fields after move to github.

---

tests/cloud_tests/__init__.py
tests/cloud_tests/platforms/azurecloud/image.py
tests/cloud_tests/platforms/azurecloud/instance.py
tests/cloud_tests/platforms/azurecloud/platform.py
tests/cloud_tests/setup_image.py

The azurecloud platform did not always start instances
during collect runs.  This was a result of two issues. First
the image class _instance method did not invoke the start()
method which then allowed collect stage to attempt to run
scripts without an endpoint.  Second, azurecloud used the
image_id as both an instance handle (which is typically
vmName in azure api) as well as an image handle (for image
capture).  Resolve this by adding a .vm_name property to
the AzureCloudInstance and reference this property in
AzureCloudImage.
Also in this branch
- Fix error encoding user-data when value is None
- Add additional logging in AzureCloud platform
- Update logging format to print pathname,funcName and line number
This greatly eases debugging.
LP: #1861921

azurecloud: fix issues with instances not starting

---

cloudinit/config/cc_mounts.py
doc/examples/cloud-config-mount-points.txt

Minor doc cleanup noticed when someone hit a swapfile device setup issue.

docs: mount_default_files is a list of 6 items, not 7

---

cloudinit/util.py

As noticed by Seth Arnold, non-deterministic SystemRandom should be
used when creating security-sensitive random strings.
LP: #1860795

utils: use SystemRandom when generating random password.

---

cloudinit/ec2_utils.py
cloudinit/sources/DataSourceEc2.py
cloudinit/url_helper.py
tests/unittests/test_datasource/test_ec2.py

Instead of logging the token values used log the headers and replace the actual
values with the string 'REDACTED'.  This allows users to examine cloud-init.log
and see that the IMDSv2 token header is being used but avoids leaving the value
used in the log file itself.
LP: #1863943

ec2: Do not log IMDSv2 token values, instead use REDACTED

---

packages/bddeb
tools/make-tarball
tools/read-version

Our [release process](https://github.com/CanonicalLtd/uss-tableflip/blob/master/doc/upstream_release_process.md) calls for a tag to be created locally (pointing at the "new release" commit) and pushed to the upstream repo so that CI can pass. The process then later calls for the "new release" commit to be pushed directly to upstream's master (instead of being merged by a CI system). This results in a correctly tagged commit in upstream's master, even though the tagging was performed before the commit landed in master.
As things stand, this doesn't work for us on GitHub. We have branch protection configured to stop us from pushing to master, so the only way to land new commits in master is via squash merge through the GitHub UI. This means that a _new_ commit is created in `master`, so the …

Update tooling for GitHub-based new releases

---

cloudinit/sources/helpers/openstack.py
cloudinit/sources/helpers/tests/test_openstack.py

OpenTelekom Cloud is based on cascading OpenStack.
The type of network interfaces used for KVM instances 
here is:'cascading'.
This commit adds 'cascading' to the list of KNOWN_PHYSICAL_TYPES.

Add physical network type: cascading to openstack helpers

---

doc/rtd/topics/datasources/openstack.rst

In cloud-init 19.2, we added the ability for cloud-init to detect
OpenStack platforms by checking for "OpenStack Compute" or "OpenStack
Nova" in the chassis asset tag.  However, this was never reflected
in the documentation.  This patch updates the datasources documentation
for OpenStack to reflect the possibility of using the chassis asset tag.
LP: #1669875

Fix docs for OpenStack DMI Asset Tag

---

cloudinit/tests/test_url_helper.py
cloudinit/url_helper.py

Our header redact logic was redacting both logged request headers and
the actual source request. This results in DataSourceEc2 sending the
invalid header "X-aws-ec2-metadata-token-ttl-seconds: REDACTED" which
gets an HTTP status response of 400.
Cloud-init retries this failed token request for 2 minutes before
falling back to IMDSv1.
LP: #1865882

ec2: only redact token request headers in logs, avoid altering request

---

cloudinit/net/cmdline.py
doc/rtd/topics/network-config.rst
tests/unittests/test_net.py

Allow disabling cloud-init's network configuration via an plain text
kernel cmdline
Cloud-init docs indicate that users can disable cloud-init networking
via kernel command line parameter 'network-config=<YAML>'.  This does
not work unless the <YAML> payload base64 encoded.  Document the base64
encoding requirement and add a plain-text value for disabling
cloud-init network config:
network-config=disabled
Also:
- Log an error and ignore any plain-text network-config payloads that
are not specifically 'network-config=disabled'.
- Log a warning if network-config kernel param is invalid yaml but do
not raise an exception, allowing boot to continue and use fallback
networking.
LP: #1862702

net: support network-config:disabled on the kernel commandline

---

cloudinit/sources/__init__.py
cloudinit/sources/tests/test_init.py

When cloud-init persisted instance metadata to instance-data.json
if failed to redact the sensitive value. Currently, the only sensitive key
'security-credentials' is omitted as cloud-init does not fetch this value
from IMDS.
Fix this by properly redacting the content from the public
instance-metadata.json file while retaining the value in the root-only
instance-data-sensitive.json file.
LP: #1865947

instance-data: write redacted cfg to instance-data.json

---

cloudinit/sources/DataSourceEc2.py
tests/unittests/test_datasource/test_ec2.py

The EC2 Data Source needs to handle 3 states of the Instance
Metadata Service configured for a given instance :
1. HttpTokens : optional & HttpEndpoint : enabled
Either IMDSv2 or IMDSv1 can be used.
2. HttpTokens : required & HttpEndpoint : enabled
Calls to IMDS without a valid token (IMDSv1 or IMDSv2 with expired token)
will return a 401 error.
3. HttpEndpoint : disabled
The IMDS http endpoint will return a 403 error.
Previous work to support IMDSv2 in cloud-init handled case 1 and case 2. This commits handles case 3 by bypassing the retry block. It shaves 2 minutes when rebooting an instance that has had its IMDS http endpoint disabled but creates some inconsistencies.  An instance that doesn't set "manual_cache_clean" to "True" will have its ```/var/lib/cloud/instance``` symlink …

ec2: Do not fallback to IMDSv1 on EC2

---

.travis.yml
Makefile
packages/pkg-deps.json
test-requirements.txt
tools/run-container
tools/tox-venv
tox.ini

As the nose docs[0] themselves note, it has been in maintenance mode for the past several years.  pytest is an actively developed, featureful and popular alternative that the nose docs themselves recommend. See [1] for more details about the thinking here.
(This PR also removes stale tox definitions, instead of modifying them.)
[0] https://nose.readthedocs.io/en/latest/
[1] https://lists.launchpad.net/cloud-init/msg00245.html

cloudinit: move to pytest for running tests

---

tox.ini

pyflakes versions older than 2.1.0 are incompatible with Python 3.8
(which is the Python version in the current Ubuntu development release).
See https://github.com/PyCQA/pyflakes/issues/367 for details.
2.1.1 is the latest version ATM, so bump to that.

tox.ini: bump pyflakes version to 2.1.1

---

.github/workflows/cla.yml

Github api doesn't allow each pull_request CI run to drive label
changes.
Thus, convert the job to a schedule and drive the labeling while
walking through all open pull requests.
For each PR, check if the author has signed CLA:
* If unsigned, add "CLA not signed" label and add a comment telling them about CLA
* If signed, add "CLA signed" label and remove "CLA not signed"
Note a working run triggers on pull_request from my local repo:
https://github.com/blackboxsw/cloud-init/commit/944e6ae1d90a0a606a9c3f170236831eb5d2bd00/checks?check_suite_id=393562692

workflows: adjust to status_check on pull_request as github actions can't label during CI

---

tox.ini

Now that we can distinguish between CI xenial dependencies and
needed-to-run-on-dev-machine xenial depedencies, we can return to
testing with the correct jsonpatch version.

tox.ini: use xenial version of jsonpatch in CI

---

.github/workflows/cla.yml

Instead of using the username that triggered the action (which, in the
case of a committer merging master into a PR branch will be the
committer), always use the username of the submitter of the pull
request.

workflows/cla.yml: use correct username for CLA check

---

cloudinit/config/cc_phone_home.py

Initial pass at adding the ed25519 host key to allowed `phone_home` payload keys.
LP: #1866671

Add pub_key_ed25519 to cc_phone_home

---

tox.ini

See the added comment for details.

tox.ini: avoid substition syntax that causes a traceback on xenial

---

README.md
doc/rtd/topics/availability.rst

Since 94838def772349387e16cc642b3642020e22deda, CloudInit supports NetBSD
too.

doc: CloudInit also support NetBSD

---

cloudinit/config/tests/test_resolv_conf.py
templates/resolv.conf.tmpl

This is a follow-up to #144 which fixed the rendering behaviour.
While writing the tests, CI failed due to dict iteration differences across Python versions, so this also sorts output so that we will produce the same output across Python versions.

cc_resolv_conf: introduce tests and stabilise output across Python versions

---

.github/workflows/stale.yml

This workflow will label pull requests with "stale-pr" if they haven't
seen activity for 14 days.  It will then close them out after a further
7 days of inactivity.

workflows: introduce stale pull request workflow

---

tests/cloud_tests/releases.yaml

Quote the Ubuntu version numbers in releases.yaml to make sure they're
treated as strings and not as floats.

releases.yaml: quote the Ubuntu version numbers

---

tests/cloud_tests/testcases/base.py

The 'merged_cfg' key introduced in 71af48d was incorrectly referenced
to as 'ci_cfg' in the json validation test for ec2.

ec2 json validation: fix the reference to the 'merged_cfg' key

---

cloudinit/net/network_state.py
cloudinit/sources/DataSourceEc2.py
doc/rtd/topics/datasources/ec2.rst
tests/unittests/test_datasource/test_ec2.py

On Ec2, cloud-init will configure networking on all attached NICs,
instead of just the primary NIC.
Also add support for rendering secondary static IPv4/IPv6 addresses on
any NIC attached to the machine.
For network config, cloud-init now reads Ec2 IMDS metadata API version
2018-09-24. Ec2-lookalike platforms which do not support this version
will not get secondary IP addresses configured.
Secondary IPs are listed in IMDS  API keys local-ipv4s, ipv6s,
subnet-ipv4-cidr-block and subnet-ipv6-cidr-block in order to set
proper static IP and CIDR prefix.
Also in this branch:
- Shift DataSourceEc2.network_config to emit v2 instead of v1.
- Add an `apply_network_config` Ec2 datasource config option which
allows images to disable network config for secondary NICs and
secondary IP addresses by …

ec2: render network on all NICs and add secondary IPs as static

---

cloudinit/cmd/tests/test_main.py
cloudinit/config/tests/test_disable_ec2_metadata.py
cloudinit/net/tests/test_init.py
cloudinit/sources/tests/test_oracle.py
tests/unittests/test_datasource/test_azure.py
tests/unittests/test_datasource/test_maas.py
tests/unittests/test_handler/test_handler_locale.py
tests/unittests/test_handler/test_handler_puppet.py
tests/unittests/test_util.py

These classes don't use `self.logs` anywhere in their body, so we can
remove the `with_logs = True` setting from them.
These instances were found using astpath[0], with the following
invocation:
```
astpath "//Name[@id='with_logs' and not(ancestor::ClassDef//Attribute[@attr='logs'])]"
```
[0] https://github.com/hchasestevens/astpath

cloudinit/tests: remove unneeded with_logs configuration

---

cloudinit/sources/DataSourceOracle.py

Bring it into line with the current state of the code (by dropping the
now-untrue caveat).

DataSourceOracle: update .network_config docstring

---

cloudinit/util.py

On NetBSD and OpenBSD, the libc soname and location are different. There
is no reason to be to specific. Python is able to propely open the share
library by itself.

bsd: boottime does not depend on the libc soname

---

cloudinit/config/cc_apt_configure.py
cloudinit/util.py
tests/unittests/test_handler/test_handler_apt_source_v3.py

These two implementations had drifted away from one another very
slightly.  Reconcile them and then remove the one in cc_apt_configure.

cc_apt_configure/util: combine search_for_mirror implementations

---

tools/ccfg-merge-debug
tools/make-mime.py
tools/mock-meta.py
tools/pipremove
tools/read-dependencies
tools/read-version
tools/validate-yaml.py

Switch tools/ to use python3 instead of python.  At minimum this
fixes building deb on python3 only releases like Focal. Applied
via shell commands:
$ grep 'usr/bin/.*python' tools/* 2>/dev/null | \
grep -v python3 | awk -F':' '{print $1}' | \
xargs -i sed -i -e '0,/python/s/python/python3/' {}

tools: use python3

---

cloudinit/distros/bsd.py
cloudinit/distros/freebsd.py

Currently, `cc_package_update_upgrade_install.py` fails because
`package_command()` does not know how to do an update on FreeBSD.
```
2020-03-23 20:01:53,995 - util.py[DEBUG]: Package update failed
File "/usr/local/lib/python3.7/site-packages/cloud_init-20.1-py3.7.egg/cloudinit/config/cc_package_update_upgrade_install.py", line 85, in handle
cloud.distro.update_package_sources()
File "/usr/local/lib/python3.7/site-packages/cloud_init-20.1-py3.7.egg/cloudinit/distros/freebsd.py", line 158, in update_package_sources
["update"], freq=PER_INSTANCE)
File "/usr/local/lib/python3.7/site-packages/cloud_init-20.1-py3.7.egg/cloudinit/helpers.py", line 185, in run
results = functor(*args)
File "/usr/local/lib/python3.7/site-packages/cloud_init-20.1-py3.7.egg/cloudin …
```

freebsd: ensure package update works

---

cloudinit/tests/test_util.py
cloudinit/util.py
doc/examples/kernel-cmdline.txt

Add support for additional escaping of formatting characters
in the YAML content between the 'cc:' and 'end_cc' tokens.  On
s390x legacy terminals the use of square brackets [] are not
available limiting the ability to indicate lists of values in
yaml content. Using #5B and #5D, [ and ] respectively enables
s390x users to pass list yaml content into cloud-init via
command line interface.
- Add unittests for read_conf_from_cmdline
- Fix typo in docstring for read_conf_from_cmdline
- Update cc: end_cc kernel command line example

util: read_cc_from_cmdline handle urlencoded yaml content

---

cloudinit/sources/DataSourceOVF.py
cloudinit/sources/helpers/vmware/imc/config.py
cloudinit/sources/helpers/vmware/imc/guestcust_util.py
tests/unittests/test_vmware/test_guestcust_util.py
tests/unittests/test_vmware_config_file.py

VMWare: support to update guest info gc status if gc status is enabled in configuration file.

VMWware: support to update guest info gc status if enabled

---

cloudinit/distros/bsd.py
cloudinit/distros/netbsd.py
cloudinit/distros/openbsd.py
cloudinit/net/__init__.py
cloudinit/net/openbsd.py
cloudinit/net/renderers.py
cloudinit/sources/DataSourceConfigDrive.py
cloudinit/sources/DataSourceNoCloud.py
cloudinit/util.py
config/cloud.cfg.tmpl
doc/rtd/topics/network-config.rst
setup.py
tests/unittests/test_util.py
tools/build-on-openbsd
tools/render-cloudcfg

Based on: https://github.com/canonical/cloud-init/pull/62

add Openbsd support

---

setup.py

We no longer need to support versions which don't have
subprocess.check_output, so we can rely on its presence in the stdlib.

setup.py: drop NIH check_output implementation

---

.travis.yml

We're seeing CI failures currently because a LXD image takes more than
10 minutes to download if the transatlantic link to Canonical's DC is
heavily contested.
This uses a helper provided by Travis[0] to avoid cancellation due to
lack of output for 30 minutes, which should be sufficient to download an
image even at the lowest speeds we've been seeing.
[0] https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

.travis.yml: allow 30 minutes of inactivity in cloud tests

---

cloudinit/tests/helpers.py
tests/unittests/test_handler/test_handler_yum_add_repo.py
tests/unittests/test_handler/test_handler_zypper_add_repo.py

(And sort some imports where I was changing them.)

CiTestCase: remove now-unneeded parse_and_read helper method

---

cloudinit/net/__init__.py
cloudinit/net/tests/test_init.py

This will be required for the mirror URL sanitisation work, but is a convenient unit to review separately hence the proposal with no callers.
(Also sort some imports.)

net: introduce is_ip_address function

---

cloudinit/net/__init__.py
cloudinit/net/tests/test_init.py
cloudinit/sources/__init__.py
cloudinit/util.py

This also simplifies the implementation to rely on the stdlib, instead
of our own NIH checking.

cloudinit: refactor util.is_ipv4 to net.is_ipv4_address

---

config/cloud.cfg.tmpl
tests/unittests/test_net.py
tests/unittests/test_render_cloudcfg.py

On Focal and later, Ubuntu will prioritize netplan renderer before eni, even if ifupdown
and netplan are both installed. ENI on Bionic and later is considered an unsupported
configuration and so cloud-init should generally prefer netplan to eni rendering because
/etc/network/interfaces config file on many cloud images disables including cloud-init's
/etc/network/interfaces.d/50-cloud-init.cfg file.
Ubuntu series-specific changes may be applied to Bionic and Eoan, but further
discussion is warranted about the best approach on released series.
LP: #1867029

net: ubuntu focal prioritize netplan over eni even if both present

---

cloudinit/user_data.py
tests/unittests/test_data.py

Don't pull just yet -- this is the testcase first, adding the fix as second step (TDD).
So this will fail the CI and the subsequent patch should fix it ...
Test case from Ryan Harper in discussion of PR#234
(https://github.com/canonical/cloud-init/pull/234).
This should demonstrate that cloud-init (without the subsequent
patches) will fail to accept multipart user-data documents
with the cloud-config piece (mis)declared as text/x-shellscript.
This happens on old heat on OpenTelekomCloud.
Let's watch this fail the CI and then add the fix ...
Signed-off-by: Kurt Garloff <kurt@garloff.de>

Test acceptance of x-shellscript as cloud-config.

---

cloudinit/sources/DataSourceRbxCloud.py
tests/unittests/test_datasource/test_rbx.py

I am co-worker of RbxCloud provider.
We have noticed that in the case of a specific network configuration, the current arping execution for IP addresses ended with .1, .2 and .3 fails, as it is not supported. In future network hardware of platform, .2 and .3 IP addresses will probably not be required and not supported at all.
Currently, no arping to all IP address does not mean no network communication, but degraded service until ARP lease. For this reason, this error should not stop the datasource, but only be logged in.
This behavior also allows us to gracefully discontinue use of .2 and .3 IP addresses in all future network configurations. It also means that the message should be logged in instead of stopping datasource completely.

rbxcloud: gracefully handle arping errors

---

cloudinit/distros/__init__.py
cloudinit/distros/tests/test_init.py

This modifies _get_package_mirror_info to convert the hostnames of generated mirror URLs to their IDNA form, and then iterate through them replacing any invalid characters (i.e. anything other than letters, digits or a hyphen) with a hyphen.
This commit introduces the following changes in behaviour:
* generated mirror URLs with Unicode characters in their hostnames will have their hostnames converted to their all-ASCII IDNA form
* generated mirror URLs with invalid-for-hostname characters in their hostname will have those characters converted to hyphens
* generated mirror URLs which cannot be parsed by `urllib.parse.urlsplit` will not be considered for use
* other configured patterns will still be considered
* if all configured patterns fail to produce a URL that parses then the fallback …

distros: replace invalid characters in mirror URLs with hyphens

---

cloudinit/cmd/tests/test_clean.py
cloudinit/cmd/tests/test_status.py
cloudinit/tests/helpers.py
tests/unittests/test_handler/test_schema.py

This shim was required to support Python 2.6, so we no longer need it.

CiTestCase: stop using and remove sys_exit helper

---

cloudinit/distros/__init__.py
cloudinit/distros/tests/test_init.py

This also cleans up some unnecessary indentation introduced in #291.

distros: drop leading/trailing hyphens from mirror URL labels

---

HACKING.rst

* Split the "existing contributors" information out to a separate
section
* Update the "Do these things once" CLA information for the current
process

HACKING.rst: reorganise/update CLA signature info

---

cloudinit/util.py

functools.lru_cache has been present since Python 3.2, so we no longer need to handle its absence.
(Also sort util's imports while we're modifying them.)

util: remove unnecessary lru_cache import fallback

---

cloudinit/distros/netbsd.py
cloudinit/distros/openbsd.py

`usermode -C no foo` does not work on OpenBSD. Unlike NetBSD, we don't
actually need to unlock the user.

openbsd: set_passwd should not unlock user

---

cloudinit/config/cc_mounts.py
tests/unittests/test_handler/test_handler_mounts.py

The cc_mounts module does not support NFS mounts in the form of `hostname:/` or `hostname:/path`.
This PR adds support for NFS-style paths in the fs_spec field.
LP: #1870370

Add support for NFS/EFS mounts

---

cloudinit/net/network_state.py
cloudinit/net/tests/test_network_state.py

Accept netplan config with 'renderer' keys.
LP: #1870421

net: ignore 'renderer' key in netplan config

---

HACKING.rst

And document that we can't yield in pytest.fixture functions due to the
age of xenial's pytest.

HACKING.rst: add pytest version gotchas section

---

cloudinit/config/cc_mounts.py

Swap file size variable was being used before checked if it's set to str
"auto". If set to "auto", it will break with:
failed to setup swap: unsupported operand type(s) for /: 'str' and 'int'
RHBZ: 1772505

swap file "size" being used before checked if str

---

cloudinit/config/cc_mounts.py
cloudinit/config/tests/test_mounts.py

cc_mounts: fix incorrect format specifiers

---

cloudinit/sources/tests/test_oracle.py
tests/unittests/test_datasource/test_opennebula.py

We currently have a test system where get_interfaces_by_mac raises an
exception, which is causing these tests to fail as they aren't mocking
get_interfaces_by_mac out.
LP: #1873910

tests: add missing mocks for get_interfaces_by_mac

---

doc/examples/cloud-config-apt.txt
doc/examples/cloud-config-boot-cmds.txt
doc/examples/cloud-config-chef-oneiric.txt
doc/examples/cloud-config-chef.txt
doc/examples/cloud-config-datasources.txt
doc/examples/cloud-config-disk-setup.txt
doc/examples/cloud-config-mcollective.txt
doc/examples/cloud-config-mount-points.txt
doc/examples/cloud-config-phone-home.txt
doc/examples/cloud-config-power-state.txt
doc/examples/cloud-config-puppet.txt
doc/examples/cloud-config-reporting.txt
doc/examples/cloud-config-rh_subscription.txt
doc/examples/cloud-config-rsyslog.txt
doc/examples/cloud-config-user-groups.txt
doc/examples/cloud-config-vendor-data.txt
doc/examples/cloud-config-write-files.txt
doc/examples/cloud-config-yum-repo.txt
doc/examples/cloud-config.txt
doc/examples/kernel-cmdline.txt
doc/rtd/topics/datasources/azure.rst
doc/rtd/topics/datasources/cloudstack.rst
doc/rtd/topics/datasources/ec2.rst
doc/rtd/topics/datasources/nocloud.rst
doc/rtd/topics/datasources/openstack.rst
doc/rtd/topics/tests.rst
tools/.github-cla-signers

This proposal has been aligned in a human readable.
- There are [no changes to this except for spac](https://github.com/canonical/cloud-init/pull/323/files?w=1)
- The indentation size is not specifically defined in the YAML RFC
- `$ make yaml` has passed on my-machine
I set the indentation size to the largest number of articles in the repository (dictionary: `2`)

YAML align indent sizes for docs readability 

---

cloudinit/conftest.py
cloudinit/tests/test_conftest.py

This mirrors the behaviour of CiTestCase.allowed_subp, by causing all calls to `util.subp` within pytest tests to raise an AssertionError. It also includes support for re-enabling `util.subp` on a per-test basis (which is not yet needed). It does not yet have support for selectively allowing calls, but that can be added once it is needed.

conftest: introduce disable_subp_usage autouse fixture

---

HACKING.rst

* Add a list of available pytest fixtures to the gotchas section
* Document the common mock naming pattern used in the codebase
* Typo/newlines fixes

More unit test documentation

---

.travis.yml

The integration test doesn't work against the ubuntu/* branches because
it uses the tooling designed to work against master.  This means that
ubuntu/* branches always report failures in Travis, which doesn't give
us any signal.

.travis.yml: don't run integration test on ubuntu/* branches

---

cloudinit/log.py

logging.NullHandler has been present since Python 3.1, we don't need to
handle its absence.

log: remove unnecessary import fallback logic

---

cloudinit/distros/__init__.py

As written, it's possible that the first transformation for a mirror
hostname could be passed None if the parsed mirror URL didn't have a
hostname component, when the defined interface is that the
transformations will be passed strings.
This isn't an error currently, because the first transformation happens
to gracefully handle being passed None.  It returns None, so the
pipeline processing ends there.
This was caught when testing out mypy on the cloud-init codebase.

distros: handle a potential mirror filtering error case

---

cloudinit/config/tests/test_users_groups.py
cloudinit/net/tests/test_dhcp.py
cloudinit/net/tests/test_init.py
cloudinit/sources/tests/test_init.py
cloudinit/tests/helpers.py
integration-requirements.txt
packages/pkg-deps.json
test-requirements.txt
tests/cloud_tests/testcases/__init__.py
tests/cloud_tests/testcases/base.py
tests/cloud_tests/testcases/modules/ntp_chrony.py
tests/cloud_tests/verify.py
tests/unittests/test_builtin_handlers.py
tests/unittests/test_datasource/test_azure.py
tests/unittests/test_datasource/test_azure_helper.py
tests/unittests/test_datasource/test_smartos.py
tests/unittests/test_handler/test_handler_ca_certs.py
tests/unittests/test_handler/test_handler_chef.py
tests/unittests/test_handler/test_handler_growpart.py
tests/unittests/test_handler/test_schema.py
tox.ini

These libraries provide backports of Python 3's stdlib components to Python 2. As we only support Python 3, we can simply use the stdlib now. This pull request does the following:
* removes some unneeded compatibility code for the old spelling of `assertRaisesRegex`
* replaces invocations of the Python 2-only `assertItemsEqual` with its new name, `assertCountEqual`
* replaces all usage of `unittest2` with `unittest`
* replaces all usage of `contextlib2` with `contextlib`
* drops `unittest2` and `contextlib2` from requirements files and tox.ini

cloudinit: drop dependencies on unittest2 and contextlib2

---

cloudinit/sources/DataSourceNoCloud.py

These two lines were a requirement for RHEL6, and they have been added 7
years ago:
- https://github.com/canonical/cloud-init/commit/984c72e522c585c6d3f6b3d3aec39fb21dd84028
- https://github.com/canonical/cloud-init/commit/48a3b4ca0ba55699825d6eabe75d843286c23545
RHEL6 comes with Python 2.6, since Python3 is now a strong requirement, I
think it's save to remove this hack.

nocloud: drop work around for Linux 2.6

---

cloudinit/sources/DataSourceNoCloud.py
cloudinit/util.py
tests/unittests/test_datasource/test_nocloud.py
tests/unittests/test_util.py

Refactoring of the `find_devs_with_xxx()` methods:
- centralize everything in `util.py`
- add test coverage

BSD: find_devs_with_ refactoring

---

cloudinit/config/cc_write_files.py
cloudinit/config/schema.py
tests/unittests/test_cli.py
tests/unittests/test_handler/test_handler_write_files.py
tests/unittests/test_handler/test_schema.py

* schema: extend Draft4 to validate binary strings fix list validation
* schema: add --module param to `cloud-init devel schema` to filter docs printed on CLI
* schema: docs now support list of object types

schema: add json schema for write_files module

---

cloudinit/config/schema.py

The line in question is in the code path handling older versions of
jsonschema.  In that context it _is_ correct, but when pylint analyses
it against the latest jsonschema it (incorrectly) detects an error.

schema: ignore spurious pylint error

---

cloudinit/config/cc_write_files.py

Clarify in documentation that `write_files` will create parent folders
for paths that do not already exist.
This obfuscates what the problem is when people erroneously create
files in `/tmp` despite the warnings in the documentation not to do so.
People naturally assume that their file is absent because the parent folder
did not exist for it to be created in, causing them to add a `runcmd` block
to create the folder, even though execution order means that this will not
occur until after `write_files` have all finished.
Might also consider adding an actual warning in log output if a `write_files`
block does this.

[Docs] Clarify that `write_files` creates parent folders

---

doc/rtd/topics/format.rst

`make-mime.py` is a more recent version of the inline script that this
link is replacing.

doc/format: reference make-mime.py instead of an inline script

---

ChangeLog
cloudinit/version.py

Bump the version in cloudinit/version.py to 20.2 and
LP: #1875951
Created with the following:
```
cd /tmp;
git clone git@github.com:canonical/cloud-init.git;
cd cloud-init;
upstream-release 20.2 20.1
Continue? <enter>
create release branch (y/n) ? 'y'
Enter the bug ID that was created for this upstream release 
1875951<enter>
```

Release 20.2

---

cloudinit/config/cc_yum_add_repo.py

Users of Centos who want to add yum repos, like they do on Fedora
or RHEL get this unfortunate message:
Skipping modules 'yum-add-repo' because they are not verified
on distro 'centos'.  To run anyway, add them to
'unverified_modules' in config
Centos certainly supports yum, add it to the supported distro
list in the module.

yum_add_repo: Add Centos to the supported distro list

---

.travis.yml

This introduces caching of pip dependencies by default, and caching of lxd images in the integration tests. (See the inline comment for more details.)

.travis.yml: introduce caching

---

cloudinit/sources/DataSourceEc2.py
tests/unittests/test_datasource/test_ec2.py

We want to set route-metrics such that NICs are configured with the priority that they are given in the network metadata that we receive from the IMDS.  (This switches away from using MAC ordering.)
This also required the following test changes:
* reverse the sort order of the MACs in test data (so that they would trigger the bug being fixed)
* fix up the key names in `NIC2_MD` (which were under_scored instead of dash-separated)
* use a full interface dict (rather than a minimal one) for `TestConvertEc2MetadataNetworkConfig`
LP: #1876312

DataSourceEc2: use metadata's NIC ordering to determine route-metrics

---

Makefile
packages/bddeb
packages/brpm
packages/debian/control.in
packages/debian/rules
packages/debian/rules.in
packages/pkg-deps.json
packages/redhat/cloud-init.spec.in
tools/read-dependencies
tools/run-container
tools/run-pyflakes
tools/run-pyflakes3

Changes:
- Do not template debian/rules as python3 is the only supported version
- Drop six from requirements.txt
- Makefile: drop everything related to Python 2
- run-container: install the CI deps only on ubuntu|debian
- read-version: update the shebang to use Python 3
- brpm: read_dependencies(): drop unused argument
- read-dependencies: switch to Py3 and drop the --python-version option
- pkg-deps.json: drop the Python version field and update the redhat deps
- Update RPM the spec file to use Python 3 when building the RPM
- bddeb: drop support for Python 2

Adapt the package building scripts to use Python 3

---

tools/.github-cla-signers

Add lucasmoura as contributor in the project

Add lucasmoura as contributor

---

cloudinit/distros/bsd.py
cloudinit/distros/freebsd.py
cloudinit/distros/netbsd.py
tests/unittests/test_distros/test_netbsd.py

Implement the upgrade support:
- FreeBSD: using `pkg upgrade`
- NetBSD: with `pkgin`

BSD: upgrade support

---

cloudinit/analyze/dump.py
cloudinit/analyze/tests/test_dump.py

Amazon Linux 2 is configured with a log format different to the one
shipped by upstream, which means analyze fails to parse any of the log
lines.  This updates the code to know how to parse such lines.
LP: #1876323

analyze/dump: add support for Amazon Linux 2 log lines

---

cloudinit/config/cc_snap.py
tests/unittests/test_handler/test_schema.py

Following this [launchpad bug](https://bugs.launchpad.net/cloud-init/+bug/1876412), we need to validate if the examples provided in the config module are conforming to the concatenated schema of all config modules. The rationale behind that is not only to verify if the examples are correctly written but to assert that no config schema is interfering with each other.
Also, but looking at the [validate_cloudconfig_schema](https://github.com/canonical/cloud-init/blob/master/cloudinit/config/schema.py#L76), I believe that will raise the `SchemaValidationError` by using `strict=True`, so I have only called the function pasisng the right schemas to compare.
LP: #1876412

Create tests to validate schema examples

---

doc/examples/cloud-config-apt.txt
doc/examples/cloud-config-datasources.txt
doc/examples/cloud-config-disk-setup.txt
doc/examples/cloud-config-landscape.txt
doc/examples/cloud-config-rsyslog.txt
tests/unittests/test_handler/test_schema.py

See https://bugs.launchpad.net/cloud-init/+bug/1876414

Add test to ensure docs examples are valid cloud-init configs

---

.travis.yml

As we only look at these logs when there's an error, and lintian
failures don't cause the package build to error out, we never examine
this lintian output.  Let's save ourselves some CI time by skipping it.
(We aren't lintian clean, otherwise a better change here would be to
make lintian warnings cause the package build to fail.)

.travis.yml: don't run lintian during integration test package builds

---

HACKING.rst

Specifically:
* include warning against general use of mock assert methods (and suggestions on how to replace them)
* add guidelines on test decorator/param ordering
* add test guideline for module-level mock variables

HACKING.rst: more unit testing documentation

---

HACKING.rst

This (a) gives people an easy way of getting a commit into the codebase,
and (b) saves us from having to explain this process (or do it
ourselves) for every new contributor.

HACKING.rst: guide people to add themselves to the CLA file

---

HACKING.rst

Change manager contact info from Josh Powers to Rick Harding in the HACKING doc

HACKING.rst: change contact info to Rick Harding

---

cloudinit/analyze/dump.py

This was a minor cleanup suggested by Ryan in #346.

analyze/dump: refactor shared string into variable

---

cloudinit/conftest.py
cloudinit/tests/helpers.py
cloudinit/tests/test_conftest.py

And fix up an inconsistency in `tests/helpers.py` too by raising a `TypeError` when subp is called with no arguments as it does under normal operation:
```py
>>> from cloudinit.util import subp
>>> subp()
File "<stdin>", line 1, in <module>
TypeError: subp() missing 1 required positional argument: 'args'
```

conftest: add docs and tests regarding CiTestCase's subp functionality

---

cloudinit/config/cc_apt_configure.py
cloudinit/config/cc_ntp.py
cloudinit/config/cc_write_files.py
cloudinit/config/schema.py
doc/examples/cloud-config-apt.txt
doc/examples/cloud-config-chef-oneiric.txt
doc/examples/cloud-config.txt
tests/cloud_tests/testcases/examples/install_run_chef_recipes.yaml
tests/unittests/test_handler/test_schema.py

This PR creates a schema object for the `apt_configure`  module and validate this schema in the `handle`  function of the module.
There are some considerations regarding this PR:
* The `primary` and `security` keys have the exact same properties. I tried to eliminate this redundancy by moving their properties to a common place and then just referencing it for both security and primary. Similar to what is documented [here](https://json-schema.org/understanding-json-schema/structuring.html) under the `Reuse` paragraph. However, this approach does not work, because the `#` pointer goes to the beginning of the file, which is a python module instead of a json file, not allowing the pointer to find the correct definition. What I did was to create a separate dict for the mirror config and reuse …

Add schema to apt configure config

---

.travis.yml
tests/cloud_tests/platforms/__init__.py
tests/cloud_tests/util.py
tox.ini

This ensures that Travis will not kill our tests if fetching images is
taking a long time.
In implementation turns, this introduces a context manager which will
spin up a multiprocessing.Process in the background and print a dot to
stdout every 10 seconds.  The process is terminated when the context
manager exits.

cloud_tests: emit dots on Travis while fetching images

---

cloudinit/config/schema.py
cloudinit/serial.py
cloudinit/sources/DataSourceMAAS.py
cloudinit/tests/helpers.py
tests/unittests/test_cs_util.py
tests/unittests/test_datasource/test_smartos.py
tests/unittests/test_templating.py
tests/unittests/test_util.py

cloudinit: remove unneeded __future__ imports

---

cloudinit/config/tests/test_snap.py
cloudinit/config/tests/test_ubuntu_drivers.py
cloudinit/sources/helpers/tests/test_netlink.py
cloudinit/tests/test_conftest.py

We recently discovered that pylint is failing to report some errors when
invoked across our entire codebase (see
https://github.com/PyCQA/pylint/issues/3611).  I've run pylint across
every Python file under cloudinit/[0], and this commit fixes the issues
so-discovered.
[0] find cloudinit/ -name "*.py" | xargs -n 1 -t .tox/pylint/bin/python -m pylint

cloudinit: minor pylint fixes

---

doc/rtd/topics/faq.rst
tools/.github-cla-signers

We are longer using lxd.readthedocs.io
Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>

doc/rtd/topics/faq: Updates LXD docs links to current site

---

cloudinit/util.py

and slower.
and since we're making it slower, let's cache it, in case boottime gets
called more than once.
this should fix `boottime()` (again).

(BSD) util.py:boottime: make finding libc platform independent

---

cloudinit/config/cc_snap.py
cloudinit/config/tests/test_snap.py

Specifically, ensure that given values are either strings, or arrays of strings.

cc_snap: apply validation to snap.commands properties

---

cloudinit/conftest.py
cloudinit/tests/test_conftest.py

This allows tests to be configured to permit some commands to be run via
util.subp, while still rejecting any unexpected calls.  See the
documentation for further details.

conftest: implement partial disable_subp_usage

---

cloudinit/config/cc_snap.py
cloudinit/config/tests/test_snap.py

And add an example of providing a list of assertions.

cc_snap: validate that assertions property values are strings

---

HACKING.rst

Hopefully this will save some ~pointless round trips on CLA PRs.

HACKING: mention that .github-cla-signers is alpha-sorted

---

HACKING.rst

As I was looking at the initial implementation for this refactor, I realised that we didn't actually have a concrete description of the proposed refactor (and process). To save people from having to Just Know (TM), this introduces a section to `HACKING.md` named `Ongoing Refactors` as well as its first entry, for this refactor.
I do not intend this to be merged before I have an initial implementation (hence "Draft"), but figured that I may as well push this up for review while I'm working on that.

HACKING.rst: introduce .net -> Networking refactor section

---

config/cloud.cfg.tmpl

these config management things work on BSD, they also claim to work on all distros, so enabling them!
ref: https://bugs.launchpad.net/cloud-init/+bug/1880279

enable Puppet, Chef mcollective in default config

---

.travis.yml
tox.ini

Instead of running pycodestyle and pyflakes seperately, use flake8 to
get the benefits of pyflakes and also stylistic checks as well as the
ability to configure the settings for the project.

testing: use flake8 again

---

cloudinit/config/cc_chef.py
doc/examples/cloud-config-chef.txt
templates/chef_client.rb.tmpl
tests/unittests/test_handler/test_handler_chef.py

**Enable chef_license support for chef infra client**
Latest versions of chef products needs us to accept the EULA license agreements.
Without accepting license cloud-init's chef module could not run chef-client.
This update enables cloud-init's chef  module to add chef_license setting in client.rb
LP: #1879403

Enable chef_license support for chef infra client

---

tests/cloud_tests/releases.yaml

now that we've turned on jenkins CI for cloud-init. let's add the groovy release so we can test it.
without this fix our jenkins runner will see:
```
cloud_tests run: error: argument -n/--os-name: invalid choice: 'groovy' (choose from 'artful', 'bionic', 'centos66', 'centos70', 'cosmic', 'disco', 'eoan', 'focal', 'jessie', 'stretch', 'trusty', 'xenial')
ERROR: InvocationError: '/var/lib/jenkins/servers/server/workspace/cloud-init-integration-ec2-g/cloud-init/.tox/citest/bin/python -m tests.cloud_tests run --os-name=groovy --platform=ec2 --preserve-data --data-dir=results --verbose --deb=/var/lib/jenkins/servers/server/workspace/cloud-init-integration-ec2-g/cloud-init_20.2-2462-g0919bd4-0ubuntu1+1837~trunk~ubuntu20.10.1_all.deb'
```
Failure case here: …

tests: add groovy integration tests for ubuntu

---

cloudinit/distros/__init__.py
cloudinit/net/__init__.py
cloudinit/sources/DataSourceOpenNebula.py
cloudinit/sources/helpers/openstack.py
cloudinit/ssh_util.py
tests/cloud_tests/platforms/instances.py
tests/cloud_tests/testcases/base.py
tests/unittests/test_datasource/test_ec2.py
tests/unittests/test_datasource/test_ovf.py
tests/unittests/test_ds_identify.py
tests/unittests/test_handler/test_handler_apt_source_v3.py
tests/unittests/test_sshutil.py
tox.ini

This removes the use of variables named ‘l’, ‘O’, or ‘I’. Generally
these are used in list comprehension to read the line of lines.

test: fix all flake8 E741 errors

---

cloudinit/config/cc_grub_dpkg.py
cloudinit/config/tests/test_grub_dpkg.py
tools/.github-cla-signers

Please read https://bugs.launchpad.net/cloud-init/+bug/1877491
Replace the hardcoded list of devices with a more robust way of determining
the device which grub is installed to.
We use grub-probe to fetch the underlying disk the /boot directory is located on, and attempt to match the disk with its /dev/disk/by-id value. If no such /dev/disk/by-id/ value exists, we fallback to the plain disk name.
The changes are robust to unstable kernel device names and ordering, and use
/dev/disk/by-id values to populate grub-pc/install_devices where possible.
LP: #1877491

cc_grub_dpkg: determine idevs in more robust manner with grub-mkdevicemap

---

tox.ini

This puts an ignore on the imports not at the top of the file errors
for the cmd/main.py file. The reason for the ignore instead of fix
is that the file is using imp to grab a lock and patch logging
before further imports are completed.

test: ignore flake8 E402 errors in cmd/main.py

---

cloudinit/cmd/tests/test_query.py
cloudinit/config/cc_apt_configure.py
cloudinit/net/tests/test_dhcp.py
cloudinit/sources/DataSourceGCE.py
cloudinit/tests/test_url_helper.py
tests/unittests/test_net.py
tox.ini

Remove extra spaces after a ','

test: fix all flake8 E241

---

cloudinit/net/network_state.py
cloudinit/reporting/handlers.py
cloudinit/sources/helpers/azure.py
tests/unittests/test_datasource/test_aliyun.py
tests/unittests/test_datasource/test_azure.py
tests/unittests/test_datasource/test_ec2.py
tests/unittests/test_datasource/test_scaleway.py
tests/unittests/test_distros/test_netconfig.py
tests/unittests/test_ds_identify.py
tests/unittests/test_handler/test_handler_puppet.py
tests/unittests/test_net.py
tox.ini

This fixes issues with closing brackets not matching the opening
bracket's line and continuation line under-idented for hanging indent.

test: fix all flake8 E121 and E123 errors

---

HACKING.rst
cloudinit/features.py
cloudinit/tests/test_features.py
cloudinit/user_data.py
tests/unittests/test_data.py

WIP PR is for discussion, not review.
If an `#include` line fails, we only get a warning in the stdout log, but no failure in the `result.json`. For more background, see https://bugs.launchpad.net/cloud-init/+bug/1734939
I replaced the possible log warnings with exceptions (including a similar warning for a failed decompression I saw in the same file). I now get this in the `result.json` (the URL intentionally has an extra character at the end):
```{
"v1": {
"datasource": "DataSourceNoCloud [seed=ds_config][dsmode=net]",
"errors": [
"404 Client Error: Not Found for url: https://raw.githubusercontent.com/canonical/cloud-init/master/doc/examples/cloud-config-run-cmds.txtd"
]
}
}
```
Is this too blunt an instrument? Previously, if one piece failed, we'd log the warning and continue. Raising …

Include fails silently and new feature flag functionality

---

cloudinit/config/cc_scripts_per_boot.py
cloudinit/config/cc_scripts_per_instance.py
cloudinit/config/cc_scripts_per_once.py
cloudinit/config/cc_scripts_user.py
cloudinit/config/cc_scripts_vendor.py
cloudinit/subp.py
cloudinit/util.py

runparts (run a directory of scripts) seems to fit well in subp
module.  The request to move it there was raised in #416.

Move runparts to subp.

---

cloudinit/config/cc_chef.py

This was brought up in review of #416.
Makes sense to remove the local copy of "is this executable file".

Replace cc_chef is_installed with use of subp.is_exe.

---

doc/rtd/topics/datasources/cloudstack.rst
tools/.github-cla-signers

Since 19.4, cloud-init supports a more reliable approach to obtain the CloudStack user-data server address than DHCP: Via the well-known `data-server.` hostname.
I think this deserves to be documented.
Commit when the feature was added: 9662a8791e53bac40a3a37aa3f5bee3076f7d447
I also submitted a documentation PR to the CloudStack project, so they are in line: https://github.com/apache/cloudstack-documentation/pull/132

Document CloudStack data-server well-known hostname

---

cloudinit/sources/helpers/vmware/imc/guestcust_util.py

During guest os customization based on cloud-init on Photon, in the cloud-init.log found the ProcessExecutionError raised. The reason is that for the default setting on photon, there is no /etc/vmware-tools/tools.conf. When tools.cfg does not exist, running cmd : "vmware-toolbox-cmd config get deployPkg enable-custom-scripts", the return code will be EX_UNAVAILABLE(69)
cloud-init only take 0 is the normal action, so raise a ProcessExecutionError, to fix this add 69 to the rcs.
Details of the log when the issue happened:
2020-05-08 04:07:51,689 - util.py[DEBUG]: Running command ['vmware-toolbox-cmd', 'config', 'get', 'deployPkg', 'enable-custom-scripts'] with allowed return codes [0] (shell=False, capture=True)
2020-05-08 04:07:51,725 - guestcust_util.py[ERROR]: Failed running …

Fix the ProcessExecutionError issue during running "vmware-toolbox-cmd config get deployPkg enable-custom-scripts"

---

cloudinit/net/network_state.py
tests/unittests/test_net.py
tools/.github-cla-signers

LP #1879673
Reason: commit ded1ec81 introduced a regression whereby a bridge with no "parameters:" setting caused a KeyError exception.

Fixes KeyError for bridge with no "parameters:" setting

---

.travis.yml

Prior to this change, we would debootstrap for every single integration
test run in Travis.  This changes that, so we will store the chroot
created by debootstrap in Travis' cache, and use it if available.  This
saves 3-4 minutes, or ~1/3rd of the integration test run time (which is
our longest run).

travis: cache the chroot we use for package builds

---

config/cloud.cfg.d/05_logging.cfg

On a system with a non-utf8 default locale, the logger will silently not log anything if the message contains an unsupported character.
Specifically on Xenial, in the cloud-init process
```
import locale
print(locale.getpreferredencoding())
```
returns `ANSI_X3.4-1968`. 
Interesting to note, running the same code on the CLI after cloud-init has completed returns `UTF-8`.
The StreamLogger (i.e., the stdout/stderr logger) suffers from the same problem, but there's no (non-hacky) way to alter its encoding.

Default to UTF-8 in /var/log/cloud-init.log

---

.travis.yml

This makes us more robust, as our caching won't start breaking if other
parts of the Travis build change directory for us.

.travis.yml: use $TRAVIS_BUILD_DIR for lxd_image caching

---

cloudinit/atomic_helper.py
cloudinit/ssh_util.py
cloudinit/util.py
tests/unittests/test_util.py

When updating the docstring to include it, I realised that the current
name is somewhat misleading; this makes it a little easier to
understand, I think.

util: rename write_file's copy_mode parameter to preserve_mode

---

tools/read-dependencies
tools/run-container

When using an http proxy make sure to disable all the dynamic mirror
URLs. In particular:
- Uncomment the baseurl in /etc/yum.repos.d/*.repo.
- Comment out the mirrorlist and metalink URLs in *.repo.
- Replace the dynamic download.fedoraproject.org host with
dl.fedoraproject.org, which is static.
- Run the above as part of the MAYBE_RELIABLE_YUM_INSTALL command,
as installing packages may add new repos (e.g. EPEL).
- Stop disabling fastestmirror, not needed when doing the above.

RPM build: disable the dynamic mirror URLs when using a proxy

---

cloudinit/net/dhcp.py
cloudinit/net/tests/test_dhcp.py
cloudinit/sources/DataSourceAzure.py
cloudinit/sources/helpers/azure.py
tests/unittests/test_datasource/test_azure.py
tests/unittests/test_datasource/test_ec2.py
tests/unittests/test_datasource/test_openstack.py

Logging the error stream of the dhclient process is very handy when debugging the dhclient issues since it shows different DHCP signals. Here's a sample from the cloud-init.log of how this could look like:
```
2020-05-15 22:18:04,599 - dhcp.py[DEBUG]: dhclient error stream: Internet Systems Consortium DHCP Client 4.3.5
Copyright 2004-2016 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Listening on LPF/eth0/00:0d:3a:6e:d4:52
Sending on   LPF/eth0/00:0d:3a:6e:d4:52
Sending on   Socket/fallback
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 3 (xid=0xc988334c)
DHCPREQUEST of 10.0.0.22 on eth0 to 255.255.255.255 port 67 (xid=0x4c3388c9)
DHCPOFFER of 10.0.0.22 from 168.63.129.16
DHCPACK of 10.0.0.22 from 168.63.129.16
bound …
```

printing the error stream of the dhclient process before killing it

---

cloudinit/util.py
tests/unittests/test_util.py

This allows us to disable the `ensure_dir` call when it isn't
appropriate.

util: add ensure_dir_exists parameter to write_file

---

.travis.yml

Prior to this change, the process of tarring up would mean that Travis
would always detect that the cache had changed, and we would incur ~30s
of packing/transferring at the end of every build.
Instead, we now check if there was any change to the installed contents
of the schroot, and only generate a new tarball if there were changes.

.travis.yml: only store new schroot if something has changed

---

cloudinit/config/cc_final_message.py
cloudinit/config/tests/test_final_message.py

If the instance symlink doesn't exist, then we shouldn't create a
directory in its place, because that breaks future boots.
LP: #1883903

cc_final_message: don't create directories when writing boot-finished

---

cloudinit/sources/DataSourceHetzner.py
cloudinit/sources/helpers/hetzner.py
tests/unittests/test_datasource/test_hetzner.py

Hetzner cloud only supports user-data as a string (presumabily utf-8).
In order to allow users on Hetzner to provide binary data to cloud-init,
we will attempt to base64decode the userdata.
The change here adds a 'maybe_b64decode' function that will decode data
if and only if is base64 encoded.
LP: #1884071

Hetzner: support reading user-data that is base64 encoded.

---

systemd/cloud-init-generator.tmpl

The name `redhat' is not used but rather `rhel' to identify the distro.

Change from redhat to rhel in systemd generator tmpl

---

systemd/cloud-init.service.tmpl

We use "rhel" consistently everywhere else.

cloud-init.service.tmpl: use "rhel" instead of "redhat"

---

HACKING.rst
cloudinit/distros/__init__.py
cloudinit/distros/bsd.py
cloudinit/distros/networking.py

This pull request introduces the initial structure for the "cloudinit.net -> cloudinit.distros.networking Hierarchy" refactor, as detailed in [0]. It also updates that section with some changes driven by this initial implementation, as well as adding a lot more specifics to it.
[0] https://cloudinit.readthedocs.io/en/latest/topics/hacking.html#cloudinit-net-cloudinit-distros-networking-hierarchy

distros.networking: initial implementation of layout

---

HACKING.rst
cloudinit/distros/networking.py
cloudinit/net/__init__.py
cloudinit/net/tests/test_init.py

Namely, is_connected, is_wireless and is_present.  None of these are
used in the cloud-init codebase, so remove the dead code (instead of
refactoring it).

net/networking: remove unused functions/methods

---

.travis.yml

We build in a schroot using sbuild, so we don't need Build-Depends
installed in the host; save some time (and manual maintenance when
Build-Depends change) by dropping their installation and skipping the
check for them when calling `bddeb`.  We _do_ require debhelper to be
installed to build the source package, so ensure it is installed.
Additionally, while I was here, replace ubuntu-dev-tools with
devscripts; we don't need everything that ubuntu-dev-tools pulls in.

.travis.yml: rationalise installation of dependencies in host

---

.travis.yml

My previous testing was insufficient: there is a branch of testing that
requires mk-sbuild, which is shipped in ubuntu-dev-tools itself.

.travis.yml: revert to installing ubuntu-dev-tools

---

cloudinit/config/cc_chef.py
tests/unittests/test_handler/test_schema.py

his PR creates a schema object for the chef module and validate this schema in the handle function of the module.
Some of the config keys description, so I tried looking at the code and chef documentation to provide an information to the user. However, I don't know if I have the best description for all fields. For example, for the key `show_time` I could not find an accurate description of what it did, so I used what was in our code base to infer what it should do.
LP: #1858888

Add schema for cc_chef module

---

cloudinit/sources/DataSourceRbxCloud.py
tests/unittests/test_ds_identify.py

Changes are made that simplify code and aim to properly support FreeBSD:
- use `util.find_devs_with` instead call directly `blkid`, because on FreeBSD is not supported well and `util.find_devs_with` have solution for FreeBSD for that
- introduction of an additional name on FAT file system, which is used in FreeBSD
- drop shell to use default value, because FreeBSD – by default – does not have `/bin/bash`

RbxCloud: Add support for FreeBSD

---

.travis.yml
HACKING.rst
cloudinit/config/tests/test_final_message.py
packages/bddeb
tox.ini

`caplog` is only available in `pytest` itself from 3.0 onwards. In xenial, we only have pytest 2.8.7. However, in xenial we do have `pytest-catchlog` available (as `python3-pytest-catchlog`), so we use that where appropriate.

Enable use of the caplog fixture in pytest tests, and add a cc_final_message test using it

---

tests/cloud_tests/bddeb.py

We dropped that parameter in https://github.com/canonical/cloud-init/commit/4d2684848722cb2d469ad4fa60999bf81cf7056e

cloud_tests: don't pass --python-version to read-dependencies

---

doc/rtd/topics/datasources/nocloud.rst
tools/.github-cla-signers

Add mention of ability to optionally provide a vendor-data file for no-cloud format.

Add mention of vendor-data to no-cloud format documentation

---

cloudinit/tests/test_conftest.py
conftest.py
tests/unittests/test_datasource/test_opennebula.py
tests/unittests/test_render_cloudcfg.py
tox.ini

This is an improvement over indirect parameterisation for a few reasons:
* The test code is much easier to read, the mark names are much more
intuitive than the indirect parameterisation invocation, and there's
less boilerplate to boot
* The fixture no longer has to overload the single parameter that
fixtures can take with multiple meanings

tests: use markers to configure disable_subp_usage

---

cloudinit/sources/helpers/openstack.py
cloudinit/util.py
tox.ini

Specifically:
* disable E1102 in `cloudinit/sources/helpers/openstack.py` for reasons
described in a comment, and
* refactor `util.abs_join` to require at least one positional argument; this
matches `os.path.join`'s signature, and that mismatch is what was
causing pylint to emit a warning
* bump to pylint 2.4.2

cloudinit: fix tip-pylint failures and bump pinned pylint version

---

config/cloud.cfg.tmpl
templates/hosts.freebsd.tmpl

If I understand correctly, Cloud-init adopts the default configuration to run all supported modules on a given distro. For unknown reasons, the update_etc_hosts module does not run on FreeBSD and NetBSD, although:
- module `update_etc_hosts` has sense and retains functionality,
- module `update_etc_hosts` is working on the platform, in accordance with its documentation and manual tests.
In our environment, we assume that all images should have  `/etc/hosts` file managed by default. FreeBSD is an exception due default Cloud-init config.
According Git history @goneri provided recently support for NetBSD and follow that configuration, so I ask him for review.
This distinction has been made to this configuration file in a change 41d46bfb85929c79dabcec3cf21c8d71401fd2b8 but that patch follow …

Add update_etc_hosts as default module on *BSD

---

tests/cloud_tests/platforms/lxd/image.py

LXD cloud_tests: support more lxd image formats

---

cloudinit/config/cc_mounts.py
tests/unittests/test_handler/test_handler_mounts.py

Do not fail if /etc/fstab is not present.  Some images, like container
rootfs may not include this file by default.
LP: #1886531

cc_mounts: handle missing fstab

---

tests/unittests/test_data.py

I've been seeing intermittent failures of this test, and I tracked it
down to something to do with`test_features.py`: running this test after
`test_features.py` causes the failure, but the inverse does not.
This fixed patch ensures that the test will pass regardless of ordering.

test_data: fix faulty patch

---

.pylintrc
cloudinit/analyze/show.py
cloudinit/config/cc_resizefs.py
cloudinit/distros/opensuse.py
cloudinit/net/eni.py
cloudinit/sources/DataSourceAzure.py
cloudinit/sources/DataSourceHetzner.py
tests/unittests/test_datasource/test_azure_helper.py
tests/unittests/test_reporting_hyperv.py

This includes a fix to a test that had a string concatenation issue, and
so was only testing a prefix of what was intended.

cloudinit: remove global disable of pylint W0105 and fix errors

---

.pylintrc
cloudinit/config/cc_set_hostname.py
cloudinit/distros/networking.py
cloudinit/distros/ubuntu.py
cloudinit/net/cmdline.py
cloudinit/net/dhcp.py
cloudinit/reporting/handlers.py
cloudinit/sources/DataSourceAzure.py
cloudinit/sources/__init__.py
cloudinit/sources/helpers/netlink.py
cloudinit/sources/helpers/vmware/imc/config_file.py
cloudinit/sources/helpers/vmware/imc/config_namespace.py
cloudinit/sources/helpers/vmware/imc/config_source.py
cloudinit/stages.py
tests/cloud_tests/platforms/azurecloud/instance.py
tests/cloud_tests/platforms/images.py
tests/cloud_tests/platforms/snapshots.py
tests/cloud_tests/testcases/base.py
tests/unittests/test_datasource/test_ibmcloud.py
tests/unittests/test_reporting.py

This includes removing a test class which contained no tests but wasn't
detected as empty because of an errant pass statement.
(Also update the comment in .pylintrc to match what we actually filter.)

cloudinit: remove global disable of pylint W0107 and fix errors

---

cloudinit/ssh_util.py
doc/examples/cloud-config.txt

It is confusing for scripts, where a disabled user has been specified,
that ssh exits with a zero status by default without indication anything
failed.
I think exitting with a non-zero status would make more clear in scripts
and automated setups where things failed, thus making noticing the issue
and debugging easier.
LP: #1170059
Signed-off-by: Aleksandar Kostadinov <akostadi@redhat.com>

ssh exit with non-zero status on disabled user

---

tools/build-on-freebsd

The package has been renamed.
See: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246546

freebsd: py37-serial is now py37-pyserial

---

cloudinit/sources/DataSourceAzure.py

JSONDecodeError is only available in Python 3.5+. When it isn't available (i.e. on Python 3.4, which cloud-init still supports) use the more generic ValueError.

DataSourceAzure: Use ValueError when JSONDecodeError is not available

---

cloudinit/sources/DataSourceOVF.py
cloudinit/sources/helpers/vmware/imc/config.py
doc/rtd/topics/datasources/ovf.rst
tests/unittests/test_datasource/test_ovf.py
tests/unittests/test_vmware_config_file.py

The flag "enable-custom-scripts" in VM Tools configuration is used to determine whether script is allowed to run. If this flag is not set in VM Tools configuration, we will take default value "false" for security purpose. vCloud product complain this break their regression behavior.   To resolve this, we introduce flag "DEFAULT-RUN-POST-CUST-SCRIPT" so that the default value of "enable-custom-scripts" is "yes" in case "enable-custom-scripts" is absent. If "enable-custom-scripts" is explicitly set, then we still follow its value to enable/disable the script.

VMware: Support parsing DEFAULT-RUN-POST-CUST-SCRIPT

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/test_datasource/test_azure.py

DataSourceAzure: Gracefully handle the case of set hostname failure during provisioning

Disable bouncing hostname when setting hostname fails

---

test-requirements.txt

pylint is emitting errors with pytest 6.x which are not observed on
pytest 5.x.  While that is resolved, pin to a lower pytest version.

test-requirements.txt: pin pytest to <6

---

test-requirements.txt

pytest 6.0.1 fixes the issue we had with pytest 6.0.0.
This reverts commit db5c1c81840638cfe6f08bbd40982b86dd3ecef7.

Revert "test-requirements.txt: pin pytest to <6 (#512)"

---

cloudinit/util.py

+ Identifies itself as "sle_hpc" in os-release. We need to recognize this
to set the proper variant.

- Handle additional identifier for SLES For HPC

---

cloudinit/sources/DataSourceNoCloud.py
cloudinit/util.py
tests/unittests/test_ds_identify.py
tests/unittests/test_util.py
tools/.github-cla-signers
tools/ds-identify

Continuation of #500.
Proposed squashed commit message:
```
Recognize LABEL_FATBOOT labels
Update DataSourceNoCloud and ds-identify to recognize LABEL_FATBOOT labels from blkid.
Also updated associated tests.
LP: #1841466
```

Fix label fatboot

---

cloudinit/config/cc_apt_pipelining.py
tools/.github-cla-signers

Fix a typo in apt pipelining module

---

.github/workflows/stale.yml

We missed this one when we updated all the docs for the Canonical team's
management change.

.github/workflows/stale.yml: s/Josh/Rick/

---

cloudinit/sources/DataSourceOracle.py
cloudinit/sources/tests/test_oracle.py
conftest.py
tox.ini

The /opc/v1/ metadata endpoints[0] are universally available in Oracle
Cloud Infrastructure and the OpenStack endpoints are considered
deprecated, so we can refactor the data source to use the OPC endpoints
exclusively.  This simplifies the datasource code substantially, and
enables use of OPC-specific attributes in future.
[0] https://docs.cloud.oracle.com/en-us/iaas/Content/Compute/Tasks/gettingmetadata.htm

DataSourceOracle: refactor to use only OPC v1 endpoint

---

doc/rtd/topics/network-config-format-v2.rst

Fix headers for device types in network v2 docs

---

cloudinit/distros/__init__.py

This aligns their docstrings more closely with their actual behaviour.

cloudinit.distros: update docstrings of add_user and create_user

---

cloudinit/config/cc_users_groups.py
doc/examples/cloud-config-user-groups.txt
tools/.github-cla-signers

Few of the 'User and Groups' configurations in cloud-config have no effect on
already existing users. This was not documented earlier.
This change set adds that information to documentation.

Fix 'Users and Groups' configuration documentation

---

.travis.yml

We have doc8 configured, so we should use it to gate documentation
changes.

.travis.yml: run a doc build during CI

---

cloudinit/sources/DataSourceOracle.py
cloudinit/sources/tests/test_oracle.py

* v2 of the API is now default with fallback to v1.
* Refactored the Oracle datasource to fetch version, instance, and vnic metadata simultaneously.

Support Oracle IMDSv2 API

---

tox.ini

The version was bumped in c7248059dd2faaaadfbcef5c83e8e8ea166d6767 to
support running on Python 3.7+ systems.  Now that we have separate
`xenial` and `xenial-dev` tox environments, we can restore the correct
pinning for `xenial` without breaking `xenial-dev` on developer
machines.
Also drop the `mock` dependency from `xenial-shared-deps`; its removal
was missed in 5f8f85bb38cc972d3d2c705a1ec73db3f690f323.

tox.ini: pin correct version of httpretty in xenial{,-dev} envs

---

cloudinit/user_data.py

Commit d00126c167fc06d913d99cfc184bf3402cb8cf53 regressed cloud-init
handling in multipart MIME user-data.  Specifically, cloud-init would
examine the payload of the MIME part to determine what the content
type and subsequently which handler to use.  This meant that user-data
which had shellscript payloads (starts with #!) were always handled
as shellscripts, rather than their declared MIME type and affected
when the payload was handled.
One failing scenario was a MIME part with text/cloud-boothook type
declared and a shellscript payload.  This was run at shellscript
processing time rather than boothook time resulting in an change in
behavior from previous cloud-init releases.
To continue to support known scenarios where clouds have specifed
a MIME type of text/x-shellscript but provided …

user-data: only verify mime-types for TYPE_NEEDED and x-shellscript

---

debian/changelog
debian/cloud-init.postinst

In [0] we landed a change to the determination of the grub install device
for new instance launches, specifically to fix the grub install device
determined for instances booting from NVMe drives.  However, for running
NVMe-root instances to successfully install grub updates which change
the ABI between the core and its modules, we also need to fix the grub
install device that the previous (incorrect) code determined.
This commit performs that fixing, on upgrade.
[0] https://github.com/canonical/cloud-init/commit/fc07d633f7cb694423349a2c4b10c91c4b4981a2
LP: #1889555

debian/cloud-init.postinst: fix NVMe grub install device on upgrade

---

debian/changelog
debian/cloud-init.postinst

Bionic version of #514 
============================================================================================
In [0] we landed a change to the determination of the grub install device
for new instance launches, specifically to fix the grub install device
determined for instances booting from NVMe drives.  However, for running
NVMe-root instances to successfully install grub updates which change
the ABI between the core and its modules, we also need to fix the grub
install device that the previous (incorrect) code determined.
This commit performs that fixing, on upgrade.
[0] https://github.com/canonical/cloud-init/commit/fc07d633f7cb694423349a2c4b10c91c4b4981a2
LP: #1889555

Bionic: debian/cloud-init.postinst: fix NVME grub install device on upgrade

---

debian/changelog
debian/cloud-init.postinst

Focal version of #514
============================================================================================
In [0] we landed a change to the determination of the grub install device
for new instance launches, specifically to fix the grub install device
determined for instances booting from NVMe drives.  However, for running
NVMe-root instances to successfully install grub updates which change
the ABI between the core and its modules, we also need to fix the grub
install device that the previous (incorrect) code determined.
This commit performs that fixing, on upgrade.
[0] https://github.com/canonical/cloud-init/commit/fc07d633f7cb694423349a2c4b10c91c4b4981a2
LP: #1889555

Focal: debian/cloud-init.postinst: fix NVME grub install device on upgrade

---

cloudinit/cmd/query.py
cloudinit/cmd/tests/test_query.py

cloud-init query tries to directly load and decode
raw user-data from /var/lib/cloud/instance/user-data.txt.
This results in UnicodeDecodeErrors on some platforms which
provide compressed content.
Avoid UnicodeDecoderErrors when parsing compressed user-data at
/var/lib/cloud/instance/user-data.txt.
LP: #1889938
To reproduce:
```
juju bootstrap aws/us-east-1.
juju deploy ubuntu
juju ssh ubuntu/0 
sudo cloud-init query --all
OR 
lxc launch ubuntu-daily:xenial my-test
lxc exec my-test bash
gzip /var/lib/cloud/instance/user-data.txt
mv /var/lib/cloud/instance/user-data.txt.gz /var/lib/cloud/instance/user-data.txt
cloud-init query --all

cmd: cloud-init query to handle compressed userdata

---

cloudinit/cmd/query.py
cloudinit/cmd/tests/test_query.py

Addressed review comments on https://github.com/canonical/cloud-init/pull/516
No need to handle binary file types that are not gzip'd or utf-8 decodable

query: do not handle non-decodable non-gzipped content

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/test_datasource/test_azure.py

Commit message:
```
Azure: Add netplan driver filter when using hv_netvsc driver
This fixes a long delay during boot of some instances. For Azure instance types using SR-IOV via the Hyper-V netvsc network driver, two network interfaces are created that share the same MAC, but only the virtual device should be configured and used. Updating the netplan configuration to filter on the hv_netvsc driver prevents netplan from trying to figure both devices.
LP: #1830740
```

Azure: Add netplan driver filter when using hv_netvsc driver

---

doc/examples/cloud-config-chef.txt

As stated in this launchpad [bug](https://bugs.launchpad.net/cloud-init/+bug/1892947), there is a mistake in the chef example regarding cloud config. This PR fixes that

Fix cloud config on chef example

---

packages/redhat/cloud-init.spec.in

456fb55744a1acc6bd2f464b7656a9c33d0b7ac5 made tools/read-dependencies
and package/brpm distinguish between build dependencies and runtime
dependencies, however packages/redhat/cloud-init.spec.in expects all
the dependencies to be in the 'requires' list, thus missing some build
dependencies.
This change makes cloud-init.spec use 'buildrequires' too.

redhat spec: add missing BuildRequires

---

cloudinit/config/cc_lxd.py
tests/unittests/test_handler/test_handler_lxd.py

When cleaning up the bridge network created by default by LXD as part
of the `lxd init` process detach the network its profile before deleting
it. LXD will otherwise refuse to delete it with error:
Error: The network is currently in use.
Discussion with LXD upstream: lxc/lxd#7804.
LP: #1776958

LXD: detach network from profile before deleting it

---

systemd/cloud-init.service.tmpl

Lintian spotted the following issue:
>   The specified systemd .service file contains both DefaultDependencies=no
>   and Conflicts=shutdown.target directives without Before=shutdown.target.
> 
>   This can lead to problems during shutdown because the service may linger
>   until the very end of shutdown sequence as nothing requests to stop it
>   before (due to DefaultDependencies=no).
> 
>   There is race condition between stopping units and systemd getting a
>   request to exit the main loop, so it may proceed with shutdown before
>   all pending stop jobs have been processed.
Please add Before=shutdown.target.
[1] https://lintian.debian.org/tags/systemd-service-file-shutdown-problems.html

systemd: add Before=shutdown.target when Conflicts=shutdown.target is used

---

cloudinit/sources/helpers/azure.py

This reverts commit [`8d25d5e6fac39ab3319ec5d37d23196429fb0c95`](https://github.com/canonical/cloud-init/pull/468/commits/8d25d5e6fac39ab3319ec5d37d23196429fb0c95).
PR #468 refactored the Azure helper for better breakdown of diagnostics and telemetry. However, in order to facilitate ease of backporting that PR to distros that only support `Python 2.x`, the decision was made to not include type hints in #468.
As discussed and agreed upon, type hints for the Azure helper will be introduced in this separate PR.

Add method type hints for Azure helper

---

integration-requirements.txt

During the ec2 integration test runs we occasionally see failures in
deleting test instances. Hopefully a newer boto3 will be more robust.
Also bump: paramiko, cryptography, pylxd (now pulling it from pypi).
Tested with a full Xenial EC2 cloud_tests run.

Bump the integration-requirements versioned dependencies

---

cloudinit/net/sysconfig.py
tests/unittests/test_distros/test_netconfig.py
tests/unittests/test_net.py

Prior to this change, vlans were rendered in sysconfig with
'TYPE=Ethernet', and incorrectly renders the PHYSDEV based on
the name of the vlan device rather than the 'link' provided
in the network config.
The change here fixes:
* rendering of TYPE=Ethernet for a vlan
* adds a warning if the configured device name is not supported
per the RHEL 7 docs "11.5. Naming Scheme for VLAN Interfaces"
Forward-ported to cloud-init-20.2: Minimal changes on the order of
things on cloudinit/net/sysconfig.py.
LP: #1788915
LP: #1826608
rhbz: #1861871
Signed-off-by: Scott Moser <smoser@brickies.net>

network: Fix type and respect name when rendering vlan in sysconfig.

---

cloudinit/config/cc_power_state_change.py
cloudinit/distros/__init__.py
cloudinit/distros/alpine.py
cloudinit/distros/bsd.py
tests/unittests/test_handler/test_handler_power_state.py
tools/.github-cla-signers

See https://www.freebsd.org/cgi/man.cgi?shutdown(8)

create a shutdown_command method in distro classes

---

doc/rtd/topics/datasources/opennebula.rst

- use `sh` as highlight language of the code block
- change order so that the confusing indentation is less confusing

clarify OpenNebula example

---

doc/rtd/topics/boot.rst

boot.rst: add First Boot Determination section

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/test_datasource/test_azure.py

Azure datasource's `parse_network_config` throws a fatal uncaught exception when an exception is raised during generation of network config from IMDS metadata. This happens when IMDS metadata is invalid/corrupted (such as when it is missing network or interface metadata). This causes the rest of provisioning to fail.
This changes `parse_network_config` to be a non-fatal implementation. Additionally, when generating network config from IMDS metadata fails, fall back on generating fallback network config (`_generate_network_config_from_fallback_config`).
This also changes fallback network config generation (`_generate_network_config_from_fallback_config`) to blacklist an additional driver: `mlx5_core`.

Azure parse_network_config uses fallback cfg when generate IMDS network cfg fails

---

cloudinit/config/cc_ntp.py

The service installed by the CentOS and RHEL 'ntp' package is
ntpd.service
not
ntp.service
Fix that for those two distros.
LP: #1897915

Fix name of ntp service to ntpd on CentOS and RHEL.

---

tests/integration_tests/bugs/test_lp1886531.py

> add integration test for LP: #1886531
1. `pytest -s tests/integration_tests/bugs`

add integration test for LP: #1886531

---

tox.ini

> tox.ini: add integration-tests testenv definition
With the test from #592 added to the branch (so we have something to run), the output (without package installation preamble) is:
```
integration-tests run-test-pre: PYTHONHASHSEED='3602795599'
integration-tests run-test: commands[0] | /home/daniel/dev/cloud-init/.tox/integration-tests/bin/python -m pytest --log-cli-level=INFO tests/integration_tests
=================================== test session starts ====================================
platform linux -- Python 3.8.6, pytest-6.1.0, py-1.9.0, pluggy-0.13.1
cachedir: .tox/integration-tests/.pytest_cache
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 1 item …
```

tox.ini: add integration-tests testenv definition

---

conftest.py
tox.ini

> conftest.py: remove top-level import of httpretty
> 
> This means that the integration tests do not need to install
> test-requirements.txt in order to successfully import `conftest.py`.
`tox -e integration-tests` still works.

conftest.py: remove top-level import of httpretty

---

tests/integration_tests/conftest.py

> integration_tests: improve cloud-init.log assertions
With https://github.com/canonical/cloud-init/pull/592 also in tree, `CLOUD_INIT_OS_IMAGE=ubuntu:09768724e1c1 pytest -s tests/integration_tests/bugs` will demonstrate the assertion output this modifies. Before this change:
```
>       assert "WARNING" not in log_content
E       AssertionError: assert 'WARNING' not in '2020-10-01 ...atasources\n'
E         'WARNING' is contained here:
E           2020-10-01 20:49:47,402 - util.py[DEBUG]: Cloud-init v. 20.1-10-g71af48df-0ubuntu5 running 'init-local' at Thu, 01 Oct 2020 20:49:47 +0000. Up 2.06 seconds.
E           2020-10-01 20:49:47,402 - main.py[DEBUG]: No kernel command line url found.
E           2020-10-01 20:49:47,402 - main.py[DEBUG]: Closing stdin.
E           2020-10-01 …
```

integration_tests: improve cloud-init.log assertions

---

tests/integration_tests/platforms.py

> integration_tests: don't error on cloud-init failure
>
> pycloudlib's default behaviour is to raise an exception if cloud-init
> fails to run in an instance being launched.  For cloud-init testing, we
> want our test assertions to flag up failures, so we disable this
> behaviour for instances we launch.
~~This must not land before https://github.com/canonical/pycloudlib/pull/37 lands; it is marked `wip` for now.~~ (Now landed.)
For both of these, apply #592 to your tree (so you have a test to run), then run `CLOUD_INIT_OS_IMAGE=ubuntu:09768724e1c1 pytest tests/integration_tests/bugs --log-cli-level=INFO` (that image causes the test in #592 to fail, so we can compare output).
Before this change, the failure happens during launch of the test instance (which is happening during test setup, …

integration_tests: don't error on cloud-init failure

---

cloudinit/sources/DataSourceAzure.py
cloudinit/sources/helpers/azure.py
tests/unittests/test_reporting_hyperv.py

Azure helper: Refactor report_diagnostic_event and logging
Across the cloud-init Azure datasource codebase, one of the `LOG` functions (`debug`, `warning`, and `error`) is always invoked whenever `report_diagnostic_event` is invoked. This changes `report_diagnostic_event` so that a logger function can be passed in, and then invoked within `report_diagnostic_event`.
* Deploy an Azure VM (from any cloud-init enabled Ubuntu LTS image)
* Apply this PR's patch
* Reboot
* Check for a common message that is both (1) reported to KVP diagnostics and (2) logged to `cloud-init.log`. A good candidate is the `found datasource in` diagnostic message.
* Observe within `cloud-init.log` the logged diagnostic messages.
* Observe within `/var/lib/hyperv/.kvp_pool_1` (KVP diagnostics file) the logged …

Azure: Clean up and refactor report_diagnostic_event

---

cloudinit/sources/DataSourceOpenStack.py
tests/unittests/test_datasource/test_openstack.py
tools/.github-cla-signers

Consider valid product names as valid chassis asset tags when detecting
OpenStack platform before crawling for OpenStack metadata.
As `ds-identify` tool uses product name as valid chassis asset tags,
let's replicate the behaviour in the OpenStack platform detection too.
This change should be backwards compatible and a temporary fix for the
current limitations on the OpenStack platform detection.
LP: #1895976

openstack: consider product_name as valid chassis tag

---

tests/integration_tests/modules/test_apt_configure_sources_list.py
tests/integration_tests/modules/test_ntp_servers.py
tests/integration_tests/modules/test_set_password.py
tests/integration_tests/modules/test_set_password_list.py
tests/integration_tests/modules/test_users_groups.py

> integration_tests: implement citest tests run in Travis
> 
> Specifically:
> * `apt_configure_sources_list`
> * `ntp_servers`
> * `set_password_list`
> * `users_groups`
>
> Although not currently run in Travis, `set_password_list_string` was
> ported over alongside `set_password_list` (as `test_set_password`).
V e r y   w i d e:
```
GLOB sdist-make: /home/daniel/dev/cloud-init/setup.py
integration-tests recreate: /home/daniel/dev/cloud-init/.tox/integration-tests
integration-tests installdeps: -r/home/daniel/dev/cloud-init/integration-requirements.txt
integration-tests inst: /home/daniel/dev/cloud-init/.tox/.tmp/package/52/cloud-init-20.3.zip
integration-tests installed: adal==1.2.4,applicationinsights==0.11.9,argcomplete==1.12.1,attrs==20.2.0,azure-cli-core==2.9.1,azure-cli-nspkg==3.0.4 …
```

integration_tests: implement citest tests run in Travis

---

tests/integration_tests/conftest.py
tests/integration_tests/platforms.py

> integration_tests: emit settings to log during setup
Log output now looks like this:
```
tests/integration_tests/bugs/test_lp1886531.py::TestLp1886531::test_lp1886531 
------------ live log setup ------------
INFO     integration_testing:conftest.py:50 Setting up environment for lxd_container
INFO     integration_testing:platforms.py:42 Settings:
CLOUD_INIT_SOURCE=NONE
EXISTING_INSTANCE_ID=None
GCE_PROJECT=None
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_INSTANCE=False
OCI_COMPARTMENT_ID=None
OS_IMAGE=focal
PLATFORM=lxd_container
INFO     integration_testing:conftest.py:73 Done with environment setup
```

integration_tests: emit settings to log during setup

---

tests/integration_tests/modules/test_package_update_upgrade_install.py
tests/integration_tests/modules/test_runcmd.py
tests/integration_tests/modules/test_seed_random_data.py
tests/integration_tests/modules/test_set_hostname.py
tests/integration_tests/modules/test_snap.py
tests/integration_tests/modules/test_ssh_auth_key_fingerprints.py
tests/integration_tests/modules/test_ssh_generate.py
tests/integration_tests/modules/test_ssh_import_id.py
tests/integration_tests/modules/test_ssh_keys_provided.py
tests/integration_tests/modules/test_timezone.py
tests/integration_tests/modules/test_write_files.py

Translate tests from `cloud_test`  to the new integration test framework.
We are translating the following tests:
* test_runcmd.py
* seed_random_data.py
* set_hostname.py
* set_hostname_fqdn.py
* snap.py
* ssh_auth_key_fingerprints_disable.py
* ssh_auth_key_fingerprints_enable.py
* ssh_import_id.py
* ssh_keys_generate.py
* ssh_keys_provided.py
* timezone.py
* write_files.py

Add more integration tests

---

cloudinit/subp.py
doc/rtd/topics/cloud_tests.rst
packages/bddeb

bddeb builds a .deb package using the template packaging files in
packages/debian/.
The new --packaging-branch flag allows to specify a git branch
where to pull the packaging (i.e. the debian/ directory) from.
This is useful to build a .deb package from master with the very
same packaging which is used for the uploads.

bddeb: new --packaging-branch argument to pull packaging from branch

---

cloudinit/ssh_util.py
tests/unittests/test_sshutil.py

The following commit merged all ssh keys into a default user file
`~/.ssh/authorized_keys` in sshd_config had multiple files configured for
AuthorizedKeysFile:
commit f1094b1a539044c0193165a41501480de0f8df14
Author: Eduardo Otubo <otubo@redhat.com>
Date:   Thu Dec 5 17:37:35 2019 +0100
Multiple file fix for AuthorizedKeysFile config (#60)
This commit ignored the case when sshd_config would have a single file for
AuthorizedKeysFile, but a non default configuration, for example
`~/.ssh/authorized_keys_foobar`. In this case cloud-init would grab all keys
from this file and write a new one, the default `~/.ssh/authorized_keys`
causing the bug.
rhbz: #1862967
None
1. Prepare a VM with cloud-init enabled
2. Modify `/etc/ssh/sshd_config` to remove …

Change default authorizedkeys file

---

.travis.yml

> .travis.yml: add integration-tests to Travis matrix
> 
> This is implemented as a copy/paste of the `citest` integration testing
> script: the two are not intended to co-exist long-term, so it isn't
> worth further complicating an already complex part of our Travis
> configuration for short-term code reuse.
> 
> The two changes from the `citest` definition: the test framework
> executed on the last line of `script`, and it is given a `name` so we
> can easily ignore failures.
A success in my branch can be seen at https://travis-ci.org/github/OddBloke/cloud-init/jobs/733071509; there should also be a run attached to this PR shortly, of course.

.travis.yml: add integration-tests to Travis matrix

---

cloudinit/config/cc_mounts.py
cloudinit/config/tests/test_mounts.py

`create_swap()` was previously catching and not re-raising the
`ProcessExecutionError` that indicated swap creation failure; this meant
that the fallback logic could never be triggered.
This commit adds the required re-raise (as well as removing a duplicated
log message).
LP: #1897099

cc_mounts: correctly fallback to dd if fallocate fails

---

cloudinit/distros/rhel_util.py
tests/unittests/test_distros/test_resolv.py

update_resolve_conf_file is no longer used.  The last reference
to it was removed in c3680475f9c970, which was itself a "remove dead
code" commit.

Drop vestigial update_resolve_conf_file function.

---

doc/rtd/topics/faq.rst

There is a complete lack of documentation on using cloud-localds with
cloud-init to boot an image locally.
Drive by, added some more whitepapers, blogs, and videos
docs: Add how to use cloud-localds to boot qemu
There is a complete lack of documentation on using cloud-localds with
cloud-init to boot an image locally.
This has come up a lot with the deprecation and removal of the mini.iso. Instead showing people how to use cloud-images properly was lacking the step about customization via cloud-localds.
Built the docs using `make doc`

docs: Add how to use cloud-localds to boot qemu

---

cloudinit/stages.py
cloudinit/tests/test_stages.py
cloudinit/tests/test_util.py
cloudinit/util.py

> stages: don't reset permissions of cloud-init.log every boot
>
> `ensure_file` needed modification to support doing this, so this commit
> also includes the following changes:
>
> * test_util: add tests for util.ensure_file
> * util: add preserve_mode parameter to ensure_file
> * util: add (partial) type annotations to ensure_file
> 
> LP: #1900837
First, change the permissions of the log file:
```sh
$ stat -c "%a" /var/log/cloud-init.log
644
$ chmod 600 /var/log/cloud-init.log
$ stat -c "%a" /var/log/cloud-init.log
600
```
Then reboot, and confirm that we see the bug with this reproducer:
```sh
$ stat -c "%a" /var/log/cloud-init.log
644
```
Having built a bionic package from this PR branch, following the same steps:
```sh
$ stat -c "%a" /var/log/cloud-init.log
644
$ chmod 600 …
```

stages: don't reset permissions of cloud-init.log every boot

---

doc/rtd/topics/network-config-format-v1.rst
doc/rtd/topics/network-config-format-v2.rst
tests/unittests/test_net.py

Update v1 and v2 network config docs to clarify when MAC addresses should be quoted.
Also update MAC addresses used in testcases to remove quotes where not
required and add single quotes where quotes are required.
MAC addresses consisting of only 0-9 digits may be misintepreted as YAML Base 60 numbers if not quoted.
See [YAML reference](https://yaml.org/type/int.html) for definition of a Base 60 number.
Existing testcases are adequate.

Update v1 and v2 network config docs to clarify MAC addresses

---

cloudinit/config/cc_refresh_rmc_and_interface.py
cloudinit/config/cc_reset_rmc.py
config/cloud.cfg.tmpl
tests/unittests/test_handler/test_handler_refresh_rmc_and_interface.py
tools/.github-cla-signers

IBM PowerVM specific RMC module
Reliable Scalable Cluster Technology (RSCT) is a set of software components that together provide a comprehensive clustering environment(RAS features) for IBM PowerVM based virtual machines. RSCT includes the Resource Monitoring and Control (RMC) subsystem. RMC is a generalized framework used for managing, monitoring, and manipulating resources. RMC runs as a daemon
process on individual machines and needs creation of unique node id and restarts during VM boot.
More details refer
https://www.ibm.com/support/knowledgecenter/en/SGVKBA_3.2/admin/bl503_ovrv.htm
To enable the healthy functioning of RMC services on ppcle Linux based VMs.
These modules  are used for creating new node_id for every new instance/ virtual machine and ensure that Network Manager is not …

IBM PowerVM specific RMC module

---

cloudinit/net/__init__.py
cloudinit/net/tests/test_init.py
tools/.github-cla-signers

If an OVS bridge was used as the only/primary interface, the 'init'
stage failed with the following error, leaving the system with a broken
SSH setup:
```
Cloud-init v. 20.3-2-g371b392c-0ubuntu1~20.04.1 running 'init' at Fri, 09 Oct 2020 11:00:25 +0000. Up 18.61 seconds.
ci-info: +++++++++++++++++++++++++++++++++++++++++Net device info++++++++++++++++++++++++++++++++++++++++++
ci-info: +------------+-------+------------------------------+---------------+--------+-------------------+
ci-info: |   Device   |   Up  |           Address            |      Mask     | Scope  |     Hw-Address    |
ci-info: +------------+-------+------------------------------+---------------+--------+-------------------+
ci-info: |    ens4    |  True |              .               |       .       |   .    | …
```

get_interfaces: don't exclude Open vSwitch bridge/bond members

---

cloudinit/net/network_state.py
cloudinit/net/sysconfig.py
cloudinit/sources/helpers/openstack.py
tests/unittests/test_distros/test_netconfig.py
tests/unittests/test_net.py

The static and static6 subnet types for network_data.json were
being ignored by the Openstack handler, this would cause the code to
break and not function properly.
As of today, if a static6 configuration is chosen, the interface will
still eventually be available to receive router advertisements or be set
from NetworkManager to wait for them and cycle the interface in negative
case.
It is safe to assume that if the interface is manually configured to use
static ipv6 address, there's no need to wait for router advertisements.
This patch will set automatically IPV6_AUTOCONF and IPV6_FORCE_ACCEPT_RA
both to "no" in this case.
This patch fixes the specific behavior only for RHEL flavor and
sysconfig renderer. It also introduces new unit tests for the specific
case as well as adjusts some …

Explicit set IPV6_AUTOCONF and IPV6_FORCE_ACCEPT_RA on static6

---

cloudinit/sources/DataSourceHetzner.py
tests/unittests/test_datasource/test_hetzner.py

Hetzner Cloud also provides the instance ID in SMBIOS information. Use it to locally check_instance_id and to compared with instance_id from metadata service.
This also prevents reconfiguring an instance in case metadata server is temporarily unavailable or cannot be reached due to broken networking or misconfigured firewall
* https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1885527
* Create an Ubuntu instance on Hetzner Cloud.
* Add changed DS
* Create snapshot from instance
* Create new instance from snapshot should run without errors. cloud-init.log should display instance_id/serial from SMBIOS

Hetzner: initialize instance_id from system-serial-number 

---

tools/build-on-freebsd

tools/build-on-freebsd: Fix top comment explaining the purpose of the script
since there *is* an official port for cloud-init in FreeBSD, this script has a different purpose.
It's an interface between cloud-init maintainers, and the FreeBSD port maintainers for quickly seeing which dependencies have changed.
This fixes LP# 1799674
This is a documentation bug.

fix comment in tools/build-on-freebsd

---

.travis.yml

> .travis.yml: use a known-working version of lxd
>
> The latest lxd 4.7 snap causes failures; while we're diagnosing those
> and addressing the issues (either upstream or in our code), pin at lxd
> 4.6 so we can continue to land PRs in cloud-init trunk.
https://travis-ci.com/github/canonical/cloud-init/jobs/421338811 is an example of one of these failures, the relevant log line:
```
2020-10-30 10:07:15,285 - /home/travis/build/canonical/cloud-init/tests/cloud_tests/stage.py:run_stage:102 [ERROR]: stage: collect test data for xenial encountered error: Create instance from copy: The container is already frozen
```
https://github.com/lxc/lxd/commit/1cb7475c22a02f5317641c746c87430b0d561551 recently landed in lxd master, which looks like it could be related.
We aren't seeing failures in the …

.travis.yml: use a known-working version of lxd

---

cloudinit/sources/DataSourceHetzner.py
tests/unittests/test_datasource/test_hetzner.py

Fixes erroneous string/int comparison introduced in 1431c8a
* Using the Hetzner DS from PR# 630 triggers a runtime error as the comparison fails due to int/str type mismatch
* Replace DS with updated DS and create a new snapshot
* Create new instance with updated DS

Hetzner: Fix instance_id / SMBIOS serial comparison

---

conftest.py

Specifically by fixing references to `util`, adding some missing
formatting, and adding information about a corner case of mock usage
that `disable_subp_usage` breaks.
> conftest: improve docstring for disable_subp_usage
>
> Specifically by fixing references to `util`, adding some missing
> formatting, and adding information about a corner case of mock usage
> that `disable_subp_usage` breaks.
This is a doc change.

conftest: improve docstring for disable_subp_usage

---

cloudinit/tests/test_util.py
cloudinit/util.py

Fix mounting of vfat filesystems by normalizing the different names for vfat to "msdos" which works across BSDS.
FreeBSD Bugzilla ref: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250496
LP# https://bugs.launchpad.net/cloud-init/+bug/1901958
This doesn't reproduce on Ubuntu.

Fix mounting of vfat on *BSD

---

tests/integration_tests/bugs/test_lp1886531.py

> test_lp1886531: don't assume /etc/fstab exists
>
> As the bug manifested because groovy doesn't ship /etc/fstab, we should
> not assume that /etc/fstab will be present for us to remove in our
> bootcmd.
```
$ CLOUD_INIT_OS_IMAGE=groovy tox -e integration-tests -- tests/integration_tests/bugs/test_lp1886531.py
GLOB sdist-make: /home/daniel/dev/cloud-init/setup.py
integration-tests inst-nodeps: /home/daniel/dev/cloud-init/.tox/.tmp/package/52/cloud-init-20.3.zip
integration-tests installed: adal==1.2.4,applicationinsights==0.11.9,argcomplete==1.12.1,attrs==20.2.0,azure-cli-core==2.9.1,azure-cli-nspkg==3.0.4,azure-cli-telemetry==1.0.6,azure-common==1.1.23,azure-core==1.8.2,azure-mgmt-compute==7.0.0,azure-mgmt-core==1.0.0,azure-mgmt-network==5.0.0,azure-mgmt-resource==4.0.0,azure-mgmt-storag …
```

test_lp1886531: don't assume /etc/fstab exists

---

tests/integration_tests/clouds.py
tests/integration_tests/conftest.py
tox.ini

> integration_tests: various launch improvements
>
> * fix passing launch_kwargs to session_cloud.launch
> * log the launch_kwargs before launching instances
> * add support for specifying instance name for tests
These commits are also part of my WIP PR for pickling (https://github.com/canonical/cloud-init/pull/609/), but they are useful improvements nonetheless (and it's preferable to review them separately). This does not include all the integration testing commits from that PR: I don't think that `mode` is the right parameter for `pull_from_file` (because there's no situation where you would want the temporary file opened as anything other than readable) so I'll modify https://github.com/canonical/cloud-init/pull/609/commits/8af1c4b52baba2a601e35a0a69ccfb7eba019f18 and submit it …

integration_tests: various launch improvements

---

.travis.yml

> Revert ".travis.yml: use a known-working version of lxd (#643)"
>
> This reverts commit f72d0cb7a03cc311700ea8795edf2454172c7414.
>
> A new release of lxd has been released to the stable channel, which
> includes a fix for the issue we were previously working around.
See https://github.com/canonical/cloud-init/pull/643 for background. Our issue should be fixed with https://github.com/lxc/lxd/commit/4d5751993136a31ede7196a831a5037d05f3217b which stgraber confirmed to me via IRC is now in the stable channel.
If Travis passes, we're good.

Revert ".travis.yml: use a known-working version of lxd (#643)"

---

tests/unittests/test_ds_identify.py
tools/ds-identify

previously, ds-identify would mostly just guess that the system in question is `maybe` OpenStack.
This patch makes it correctly recognize NoCloud.
>  Fix ds-identify's read_fs_info() to work on FreeBSD
>
> FreeBSD doesn't have blkid, so we want to use geom to list devices and their fstypes and labels.
>
>This PR also adds `jail` to the list of is_container()
>And we now also properly cache geom and blkid output!
>
> Finally, A test is added to verify the new behaviour by correctly identifying NoCloud on FreeBSD.
This fixes LP 1901174

Fix ds-identify's read_fs_info() to work on FreeBSD

---

tests/integration_tests/clouds.py

Fix launch_kwargs bug in integration tests
Integration test instance  launch would previously fail if provided
launch_kwargs is None
None
`pytest tests/integration_tests/`

Fix launch_kwargs bug in integration tests

---

.travis.yml

Prevent timeout on travis integration tests
Add a script in travis to output a dot every 10 minute during
and integration test run to prevent travis timeout.
If a task gives no output for 10 minutes, travis will assume it hung and kill it. Integration tests can go for 10 minutes without outputting anything. This change adds an additional script to the travis task to output a every 10-ish minutes while integration tests are running.
n/a

Prevent timeout on travis integration tests

---

cloudinit/dmi.py
cloudinit/tests/test_dmi.py
cloudinit/util.py
tests/unittests/test_ds_identify.py
tools/build-on-freebsd
tools/ds-identify

FreeBSD lets us read out kernel parameters with `kenv(1)`, a user-space utility that's shipped in "base"
We can use it in place of `dmidecode(8)`, thus removing the dependency on sysutils/dmidecode, and the restrictions to i386 and x86_64 architectures that this utility imposes on FreeBSD.
I added this code, and while it opened the doors for more BSD stuff to be added, I'd like to remedy this restriction.
I'd also like to remind that @goneri already pointed this path out a year ago: https://github.com/canonical/cloud-init/pull/42#discussion_r353283759
run `kenv | grep smbios` on your favourite FreeBSD machine, and notice that unlike `dmidecode` you can just run it without being root!

replace usage of dmidecode with kenv on FreeBSD

---

HACKING.rst

> Hacking doc: unify network-refactoring namespace
>
> We've had some inconsistencies between distro.net.<func> and
> distro.networking.<func>. This pr unifies all such instances to
> distro.networking.<func>
This is a docs patch.
This is still a docs patch.

Hacking doc: unify network-refactoring namespace

---

cloudinit/net/eni.py
cloudinit/net/network_state.py
cloudinit/net/sysconfig.py
tests/unittests/test_net.py

Add code so that specifying "wakeonlan: true" actually results in relevant
configuration entry appearing in /etc/network/interfaces, NetPlan, and
sysconfig for RHEL and OpenSuse.
Add testcases for the above.
In a Network Config v2 YAML file specify the following:
```
version: 2
ethernets:
eth0:
dhcp4: true
wakeonlan: true
```
Then check the resultant Netplan file to see if wakeonlan specified there.
Wakeonlan is not supported in a v1 config file.

Make wakeonlan Network Config v2 setting actually work

---

cloud-tests-requirements.txt
integration-requirements.txt
tox.ini

> split integration and cloud_tests requirements
>
> The cloud_tests and the integration_tests (via pycloudlib) have
> conflicting requirements. This commit splits up their requirements
> files, so we can accurately express the requirements for each.
Testing is being tracked in the corresponding `pycloudlib` PR: https://github.com/canonical/pycloudlib/pull/42

split integration and cloud_tests requirements

---

tests/cloud_tests/releases.yaml

> cloud_tests: add hirsute release definition
Spotted in our integration testing.
On master:
```
$ tox -e citest -- run --verbose --preserve-data --data-dir results --os-name hirsute --test modules/ntp.yaml
...
usage: cloud_tests run [-h] [-p PLATFORM] [-n NAME] [-t FILE] [--feature-override FEATURE_OVERRIDE] [-v] [-q] [-r FILE] [-d DIR] [--preserve-instance] [--preserve-data] [--deb FILE] [--rpm FILE] [--script DATA] [--repo NAME] [--ppa NAME] [-u] [--upgrade-full]
cloud_tests run: error: argument -n/--os-name: invalid choice: 'hirsute' (choose from 'artful', 'bionic', 'centos66', 'centos70', 'cosmic', 'disco', 'eoan', 'focal', 'groovy', 'jessie', 'stretch', 'trusty', 'xenial')
ERROR: InvocationError for command /home/daniel/dev/cloud-init/.tox/citest/bin/python -m tests.cloud_tests run …
```

cloud_tests: add hirsute release definition

---

cloudinit/sources/DataSourceOpenNebula.py

> DataSourceOpenNebula: exclude SRANDOM from context output
>
> This is a new builtin variable that appeared in Ubuntu in
> 5.1~rc2-1ubuntu1 and started causing daily build failures.
Build failure: https://launchpadlibrarian.net/506884236/buildlog_ubuntu-hirsute-amd64.cloud-init_20.3-2645-g38ba6b30-0ubuntu1+1861~trunk~ubuntu21.04.1_BUILDING.txt.gz
Tested a build with this commit locally (after confirming the failure reproduced in such a build from master):
```
+------------------------------------------------------------------------------+
| Summary                                                                      |
+------------------------------------------------------------------------------+
Build Architecture: amd64
Build Type: binary
Build-Space: 17236
Build-Time: 38 …
```

DataSourceOpenNebula: exclude SRANDOM from context output

---

integration-requirements.txt

Pin pycloudlib to a working commit
Pycloudlib is currently causing integration tests to fail. Until we get proper pycloudlib versioning, I think we should pin commits so that a change in pycloudlib doesn't break tests.
n/a

Pin pycloudlib to a working commit

---

cloudinit/gpg.py
cloudinit/tests/test_gpg.py
tools/.github-cla-signers

Make sure the gpg works even if VM provides no /dev/tty (e.g. debian cloud init)
LP:#1813396
fixes https://bugs.launchpad.net/cloud-init/+bug/1813396
on a VM without a terminal mounted as /dev/tty define an external keyserver such used for docker
```
apt:
sources:
docker:
source: 'deb [arch=amd64] https://download.docker.com/linux/debian stretch stable'
keyserver: keyserver.ubuntu.com
keyid: 0EBFCD88
```

add --no-tty option to gpg

---

cloudinit/tests/test_persistence.py

> test_persistence: add VersionIsPoppedFromState test
Filling the gap pointed out by @blackboxsw: https://github.com/canonical/cloud-init/pull/659#discussion_r525529152 (Thanks Chad!)
Unit testing change only; Travis is sufficient.

test_persistence: add VersionIsPoppedFromState test

---

cloudinit/tests/test_persistence.py

> test_persistence: simplify VersionIsPoppedFromState
This was still up on my screen from yesterday, and I noticed this simplification.
Travis is sufficient.

test_persistence: simplify VersionIsPoppedFromState

---

tox.ini

```
tox.ini: only select "ci" marked tests for CI runs
`-k` will select tests or marks whose names match.  `-m` selects only
tests which have the specified mark, so is more appropriate.
```
This currently makes no difference: the only test selected based on this substring is already marked with `ci`, but this will save pain in the future.
The Travis run should succeed and indicate that a subset of integration tests were selected.

tox.ini: only select "ci" marked tests for CI runs

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/test_datasource/test_azure.py

DataSourceAzure: update password for the default user if the user exists
cc_set_password will only update the password for the default user if
cfg['password'] is set. The existing code of datasource Azure will fail 
to update the default user's password because it does not set that 
metadata. If the default user doesn't exist in the image, the current 
code works fine because the password is set during user create and 
not in cc_set_password
+ Deploy the latest bionic image on Azure with password
+ Prepare an image but do not delete the user (waagent -deprovision)
+ Deploy a new VM from the prepared image with a new password
+ Observe that the password is not set appropriately (and that the
previous password continued to work)
+ Apply this patch and go through the steps again and verify …

DataSourceAzure: update password for the default user if the user exists

---

tests/integration_tests/clouds.py
tests/integration_tests/conftest.py
tests/integration_tests/instances.py

Make mount in place for tests work
IMAGE_SOURCE = 'IN_PLACE' wasn't working previously. Replaced
LXD launch with an init, then mount, then start.
n/a
At the beginning of the `main_init` function of `cloudinit/main.py`, raise an Exception. Save but do not commit. 
Run:
CLOUD_INIT_CLOUD_INIT_SOURCE=NONE pytest tests/integration_tests/modules/test_runcmd.py
Verify that test passes
Run:
CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE pytest tests/integration_tests/modules/test_runcmd.py
Verify that test fails

Make mount in place for tests work

---

tests/integration_tests/bugs/test_lp1900837.py
tox.ini

```
add integration test for LP: #1900837
As the first test of this SRU cycle, this also introduces the
sru_2020_11 mark to allow us to easily identify the set of tests
generated for this SRU.
```
I ran this test against every current Ubuntu release:
```sh
for release in xenial bionic focal groovy hirsute; do CLOUD_INIT_OS_IMAGE=$release pytest --log-cli-level=INFO tests/integration_tests/bugs/test_lp1900837.py; done
```
and it failed with:
```
FAILED tests/integration_tests/bugs/test_lp1900837.py::TestLp1900836::test_lp1900836 - AssertionError: assert '600' == '644'
```
in each case, as expected.
I then ran this test against every current Ubuntu release with cloud-init installed from the daily PPA (which includes the fix this is testing) and they all passed.

add integration test for LP: #1900837

---

cloudinit/config/cc_ssh.py
cloudinit/config/tests/test_ssh.py
tests/integration_tests/modules/test_ssh_keys_provided.py
tools/.github-cla-signers

Support configuring SSH host certificates.
Support configuring SSH host certificates.
Existing config writes keys to /etc/ssh after deleting files matching
a glob that includes certificate files. Since sshd looks for
certificates in the same directory as the keys, a host certificate
must be placed in this directory. This update enables the certificate's
contents to be specified along with the keys.
To test, specify a host certificate's contents using
KEYTYPE_certificate (e.g., `rsa_certificate`) next to the public and
private keys normally included in the `ssh_keys` section of the config
yaml file.

Support configuring SSH host certificates.

---

cloudinit/distros/networking.py
cloudinit/distros/tests/test_networking.py
cloudinit/sources/DataSourceAzure.py
cloudinit/sources/helpers/netlink.py
cloudinit/sources/helpers/tests/test_netlink.py
tests/unittests/test_datasource/test_azure.py
tools/.github-cla-signers

Adds the ability to run the Azure preprovisioned VMs as NIC-less and then hot-attach them when assigned for reprovision.
The NIC on the preprovisioned VM is hot-detached as soon as it reports ready and goes into wait for one or more interfaces to be hot-attached. Once they are attached, cloud-init gets the expected number of NICs (in case there are more than one) that will be attached from IMDS and waits until all of them are attached. After all the NICs are attached, reprovision proceeds as usual.
Ability to hot-attach NICs to Preprovisioned VMs before reprovision
- Deploy pre-provisioned VMs (Internal to Azure)
- Deploy a VM with the same OS and size to reprovision it

[Azure] Add ability to hot-attach NICs to Preprovisioned VMs before reprovision

---

.travis.yml

> .travis.yml: correctly integration test the built .deb
>
> `IMAGE_SOURCE` was renamed to `CLOUD_INIT_SOURCE` before the testing
> framework ever landed, but I did not mirror that change in .travis.yml
> before it landed.  This addresses that.
Travis output should be inspected to confirm the built `.deb` is being used, something like:
```dosini
CLOUD_INIT_SOURCE=cloud-init_20.3-103-gb07ec7d3-1~bddeb~16.04.1_all.deb
```

.travis.yml: correctly integration test the built .deb

---

integration-requirements.txt
tests/integration_tests/clouds.py
tests/integration_tests/conftest.py
tests/integration_tests/instances.py
tox.ini

LXD VM support in integration tests
n/a
In integration settings, set `PLATFORM = 'lxd_vm`. Run
pytest -s tests/integration_tests
and notice tests run in LXD VMs rather than LXD containers.

LXD VM support in integration tests

---

integration-requirements.txt
tests/integration_tests/instances.py
tests/integration_tests/modules/test_users_groups.py
tests/integration_tests/modules/test_write_files.py

Ensure proper root permissions in integration tests
Tests previously assumed that when executing commands and transferring
files that user will have root permissions. This change updated
integration testing infrastructure so that is true.
n/a
pytest tests/integration_tests/

Ensure proper root permissions in integration tests

---

tox.ini

> Commit cd752df added substvars in tip which causes tracesbacks
>  on Xenial because tox 2.3.1 still suffers from
>    https://github.com/tox-dev/tox/issues/208.
>
> As a result we cannot use testenv substvars if we want to support
> running tox on xenial systems.
> 
> Drop the {[testenv:integration-tests]*} substitutions to avoid
> tracebacks when running `tox -e xenial-dev` which has the signature:
>
>   "No support for the %s substitution type" % sub_type)
>    tox.ConfigError: ConfigError: No support for the posargs
>     substitution type
None
```
cat > doit.sh <<EOF
git clone https://github.com/canonical/cloud-init
apt-get update
apt-get install tox -y
cd cloud-init
tox -e xenial-dev
EOF
lxc launch ubuntu-dialy:xenial test-x
lxc file push doit.sh test-x/
lxc exec test-x -- bash …
```

tox: avoid tox testenv subsvars for xenial support

---

tests/integration_tests/conftest.py
tests/integration_tests/instances.py
tests/integration_tests/integration_settings.py

Collect logs from integration test runs
During teardown of every cloud instance, run 'cloud-init collect-logs',
then transfer and unpack locally. Two new integration settings have
been added to specify when to perform this action (ALWAYS, 
ON_ERROR, NEVER), and where to store these logs.
Note that it runs once per client, so if you're using the class client, you'll get one set of the logs for the entire class. Currently logs take about 5M of space locally. The entire tree of files created after a single test run can be seen here: https://paste.ubuntu.com/p/v4rF9m9tPF/ . It includes a couple `test_example` runs that don't exist in the repo because I was testing parameterized tests.
Without overriding `COLLECT_LOGS` or `LOCAL_LOG_PATH` in the integration test settings, run:
`pytest -s …

Collect logs from integration test runs

---

tests/integration_tests/instances.py

For us to support running commands through LXD as non-root, as described in this [PR](https://github.com/canonical/ubuntu-advantage-client/pull/1241), we need to update some our integration tests for this new scenario

Update tests to run commands on LXD as non root

---

tests/integration_tests/clouds.py
tests/integration_tests/conftest.py
tests/integration_tests/instances.py

Delete image snapshots created for integration tests
For integration testing, any time we use a PPA, proposed, or deb image as our cloud init source, we create a snapshot of setup instance to be the image source for the test run. I originally left deleting that snapshot image as a todo since we weren't using those methods much. With the upcoming SRU we'll be using them a ton, so I figured it was finally time to add it.
Run cloud-init integration tests with CLOUD_INIT_SOURCE = 'PROPOSED'. When the tests are done running, list the custom images for the particular cloud in use (e.g., `lxc image list` for lxd) and verify no snapshot image exists for that particular test run.

Delete image snapshots created for integration tests

---

cloudinit/net/sysconfig.py
tests/unittests/test_net.py

Adding BOOTPROTO = dhcp to render sysconfig dhcp6 stateful on RHEL
BOOTPROTO needs to be set to 'dhcp' on RHEL so NetworkManager can
properly acquire ipv6 address.
rhbz: #1859695
The original [bz 1859695](https://bugzilla.redhat.com/show_bug.cgi?id=1859695) is mostly marked as private but the bug as noticed while configuring an internal IPv6 network on Openstack between the instance and an NFS storage. No patch required or bug noticed if the instance was configured with a regular ipv6/dhcp interface.
(as described on the above mentioned BZ)
Steps to Reproduce:
1. Create StorageNFS network with IPv6 CIDR and address range defined
2. Create a Nova instance with 2 NICs, 2nd NIC connected to StorageNFS network
3. Login to VM and examin Eth1 IP …

Adding BOOTPROTO = dhcp to render sysconfig dhcp6 stateful on RHEL

---

debian/changelog

SRU review found a stray LP: # in a commit message that needs to be redacted to avoid triggering inclusion as SRU validation
I filed this against log2dch to ensure we don't hit this when using new-upstream-stapshot during SRUs https://github.com/canonical/uss-tableflip/issues/69

changelog: drop unredacted LP reference from changelog entry

---

doc/rtd/topics/integration_tests.rst
tests/integration_tests/clouds.py
tests/integration_tests/conftest.py
tests/integration_tests/integration_settings.py
tests/integration_tests/modules/test_apt_configure_sources_list.py
tests/integration_tests/modules/test_package_update_upgrade_install.py
tests/integration_tests/modules/test_snap.py
tests/integration_tests/modules/test_ssh_import_id.py
tests/integration_tests/modules/test_users_groups.py
tox.ini

```
integration_tests: introduce skipping of tests by OS
This introduces an optional, more complex OS_IMAGE format (`<image
id>::<os>::<release>`) which allows the specification of the OS/OS
release which the given image ID corresponds to.  This information is
used to skip tests which do not apply to the image.
This commit is comprised of the following discrete changes:
* introduce the IntegrationImage class, to handle parsing and storing
the new OS_IMAGE format
* support inferring the OS and OS release of Ubuntu series, so that we
can continue to set OS_IMAGE to just a series name and have test
skipping work
* add documentation on Image Selection to integration_tests.rst
* introduce the actual skipping behaviour based on OS marks
* apply the `ubuntu` mark to all tests that should be …
```

integration_tests: introduce skipping of tests by OS

---

tests/integration_tests/clouds.py
tests/integration_tests/integration_settings.py

Add ability to keep snapshotted images in integration tests
For SRU test development, every single time we start a new test run,
we need to first install the PROPOSED version and create an image
snapshot. Instead of automatically deleting a snapshot, add an
integration setting to allow us to keep the snapshot. The end of the
test run will log the image name which can then be used as the
OS_IMAGE in subsequent test runs.
n/a

Add ability to keep snapshotted images in integration tests

---

tests/integration_tests/bugs/test_gh570.py
tests/integration_tests/bugs/test_lp1900837.py
tests/integration_tests/instances.py

Integration test for #570
Test that we can add optional vendor-data to the seedfrom file in a
NoCloud environment.
Also added the option to pass `raise_on_cloudinit_failure` through
an instance restart so we get automatic failure checking when
we need to manually reboot.
#570
should fail:
pytest tests/integration_tests/bugs/test_gh570.py
should pass:
CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED pytest tests/integration_tests/bugs/test_gh570.py

Integration test for 570

---

tests/integration_tests/clouds.py
tests/integration_tests/conftest.py
tests/integration_tests/instances.py
tests/integration_tests/integration_settings.py
tests/integration_tests/log_utils.py
tests/integration_tests/modules/test_power_state_change.py
tox.ini

Add integration test for power_state_change module
Based on https://github.com/canonical/cloud-init/pull/567 , but not naming the test after it because the changes that affected Ubuntu were only a refactor.
In the test, I've included adding a timeout to the user_data, but I don't know of a way to actually test it because the power state module is the last module to run, so even with a timeout of 1, cloud-init finishes before the timeout is triggered.
pytest tests/integration_tests/modules/test_power_state_change.py

Add integration test for power_state_change module

---

integration-requirements.txt
tests/integration_tests/bugs/test_lp1898997.py
tests/integration_tests/conftest.py
tox.ini

```
integration_tests: add test for LP: #1898997
This introduces the `lxd_config_dict` mark, used to specify a
free-form configuration dict to LXD for tests which only run there; and
the `not_xenial` and `not_bionic` marks, used to skip tests on
xenial/bionic via a basic release skipping mechanism.
(The `lxd_config_dict` change further complicated `_client`, so a minor
refactoring is applied.)
```
This is WIP because it needs https://github.com/canonical/pycloudlib/pull/66 to land for network config to LXD VMs to work.
Run `CLOUD_INIT_PLATFORM=lxd_vm pytest --log-cli-level=INFO tests/integration_tests/bugs/test_lp1898997.py` to see a failure.
Run `CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED pytest --log-cli-level=INFO tests/integration_tests/bugs/test_lp1898997.py` to …

integration_tests: add test for LP: #1898997

---

tox.ini

> integration_tests: include timestamp in log output
Before:
```
INFO     integration_testing:clouds.py:73 Detected image: image_id=focal os=ubuntu release=focal
```
After:
```
2020-12-09 22:26:03 INFO      integration_testing:clouds.py:73 Detected image: image_id=focal os=ubuntu release=focal
```

integration_tests: include timestamp in log output

---

tests/integration_tests/bugs/test_lp1813396.py
tests/integration_tests/log_utils.py
tests/integration_tests/modules/test_power_state_change.py

Integration test for lp-1813396 and #669 
Ensure gpg is called with no tty flag.
Also, refactored the "ordered_items_in_text" to assert if the line
is missing and provide a more useful error message.
#669
fail:
CLOUD_INIT_CLOUD_INIT_SOURCE=NONE pytest tests/integration_tests/bugs/test_lp1813396.py
pass:
CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED pytest tests/integration_tests/bugs/test_lp1813396.py

Integration test for lp-1813396

---

cloudinit/cmd/main.py

Fedora build system's rpmlint is complaining ther's a file with a
shebang but no executable flag set. No need to have shebang on this
file.

rpmlint complains about Python shebang on 644 file

---

integration-requirements.txt
tests/integration_tests/bugs/test_gh671.py

Integration test for gh-671
Verify that on Azure that if a default user and password are specified
through the Azure API that a change in the default password overwrites
the old password
#671 
fail:
CLOUD_INIT_PLATFORM=azure CLOUD_INIT_CLOUD_INIT_SOURCE=NONE pytest tests/integration_tests/bugs/test_gh671.py
pass:
CLOUD_INIT_PLATFORM=azure CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED pytest tests/integration_tests/bugs/test_gh671.py

Integration test for gh-671

---

tests/integration_tests/bugs/test_gh632.py

Integration test for gh-632
Verify that if cloud-init is using DataSourceRbxCloud, there is
no traceback if the metadata disk cannot be found.
#632
fail:
CLOUD_INIT_CLOUD_INIT_SOURCE=NONE pytest tests/integration_tests/bugs/test_gh632.py
pass:
CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED pytest tests/integration_tests/bugs/test_gh632.py

Integration test for gh-632.

---

tests/integration_tests/modules/test_lxd_bridge.py

> integration_tests: port lxd_bridge test from cloud_tests
`pytest --log-cli-level=INFO tests/integration_tests/modules/test_lxd_bridge.py` fails:
```
>       assert "WARN" not in cloud_init_log
E       assert "WARN" not in cloud-init.log string; unexpectedly found on these lines:
E         2020-12-08 22:48:08,461 - util.py[WARNING]: Running module lxd (<module 'cloudinit.config.cc_lxd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_lxd.py'>) failed
tests/integration_tests/modules/test_lxd_bridge.py:39: AssertionError
```
`CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED pytest --log-cli-level=INFO tests/integration_tests/modules/test_lxd_bridge.py` passes.

integration_tests: port lxd_bridge test from cloud_tests

---

tests/integration_tests/integration_settings.py

Ensure overriding test vars with env vars works for booleans
n/a
CLOUD_INIT_KEEP_INSTANCE=False pytest <any_test>
Ensure the instance isn't kept around.

Ensure overriding test vars with env vars works for booleans

---

tests/integration_tests/test_upgrade.py

Some test_upgrade fixes
- workaround pad.lv/1890528 for restarting instances
- move wait param from launch_kwargs to launch call
- remove name param as it's not universally supported
- add platfrom to log names
n/a
pytest tests/integration_tests/test_upgrade.py

Some test_upgrade fixes

---

tests/integration_tests/bugs/test_gh626.py

Integration test for gh-626
Ensure if wakeonlan is specified in the network config that it is
rendered in the /etc/network/interfaces or netplan config.
See #626
pytest tests/integration_tests/bugs/test_gh626.py

Integration test for gh-626

---

tests/integration_tests/modules/test_cli.py

Add integration tests for CLI functionality
This currently covers functionality added in #575
#575
pytest -s tests/integration_tests/modules/test_cli.py

Integration test for #575

---

tests/integration_tests/modules/test_lxd_bridge.py

>  integration_tests: restrict test_lxd_bridge appropriately
>
> On xenial, the bridge test fails because xenial's LXD doesn't include
> the `network` subcommand.  On bionic, the bridge test fails within
> containers, because LXD isn't able to manipulate the host kernel as it
> expects.
> 
> (focal and later do run successfully in containers, but we don't have a
> good way of expressing that presently.)
`CLOUD_INIT_OS_IMAGE=xenial pytest tests/integration_tests/modules/test_lxd_bridge.py` and `CLOUD_INIT_OS_IMAGE=bionic pytest tests/integration_tests/modules/test_lxd_bridge.py` fail currently, and with this change instead passes (with all skips).
`CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_OS_IMAGE=xenial pytest tests/integration_tests/modules/test_lxd_bridge.py` fails currently, and with this …

integration_tests: restrict test_lxd_bridge appropriately

---

tests/integration_tests/conftest.py
tests/integration_tests/test_upgrade.py

> integration_tests: fix IN_PLACE CLOUD_INIT_SOURCE
>
> This fixes up an issue introduced in
> 54e202a6480e48dbb8a72004f7a5003f7c4edfae.
Run the tests using `CLOUD_INIT_SOURCE=IN_PLACE`: it fails in master, and passes with this PR.

integration_tests: fix IN_PLACE CLOUD_INIT_SOURCE

---

.travis.yml

> .travis.yml: add (most) supported Python versions to CI
>
> This excludes Python 3.4, as there are currently test failures there;
> that will be addressed separately.
Travis is sufficient.

.travis.yml: add (most) supported Python versions to CI

---

tests/integration_tests/conftest.py

> integration_tests: log the path we collect logs into
>
> This makes it easier to find the failure logs when you're running a
> bunch of similar tests in parallel.
Run a test that fails, observe that the path to its logs is emitted to the log.

integration_tests: log the path we collect logs into

---

.github/PULL_REQUEST_TEMPLATE.md

> PULL_REQUEST_TEMPLATE.md: use backticks around commit message
>
> This makes it easier to copy/paste commit messages prepared elsewhere
> into the GitHub UI (and also means that the formatting in the GH UI more
> closely matches how the commit message will be consumed elsewhere).

PULL_REQUEST_TEMPLATE.md: use backticks around commit message

---

tests/integration_tests/conftest.py

> integration_tests: set log-cli-level to INFO by default
>
> This gives us more detailed integration testing output by default.
> This will make debugging failures reported by users/developers easier to
> debug, as it removes the need for an initial round-trip to get the
> output we need for debugging.  It will also make debugging intermittent
> failures easier: there will definitely be log output from runs which
> exhibit the intermittent failure.
Run the integration tests without any CLI arguments and observe log output:
```
$ pytest tests/integration_tests/modules/test_ntp_servers.py
...
2020-12-18 15:20:52 INFO      integration_testing:clouds.py:73 Detected image: image_id=focal os=ubuntu release=focal
...
```
Run the unittests without any CLI arguments and observe no log output:
``` …
```

integration_tests: set log-cli-level to INFO by default

---

.github/workflows/stale.yml

```
stale: fix error in definition
This should fix the error, and also allows us to manually trigger the
workflow.
```

stale: fix error in definition

---

debian/changelog
debian/cloud-init.manpages

```
d/cloud-init.manpages: include upstream manpages in package.
```
I've built the package locally, installed it into a hirsute container and confirmed that `man cloud-init`, `man cloud-init-per` and `man cloud-id` work as expected.

d/cloud-init.manpages: include upstream manpages in package.

---

cloudinit/sources/DataSourceAzure.py

```
Azure: Add telemetry for poll IMDS
```
`_poll_imds` within `DataSourceAzure.py` currently doesn't have the Azure telemetry decorator `@azure_ds_telemetry_reporter`. This decorator enriches telemetry needed for diagnosing issues related to Azure polling of IMDS.
* Deployed a `Canonical:UbuntuServer:18.04-LTS:latest` VM on Azure.
* Built a `deb` package out of my branch's cloud-init.
* Installed the `deb` in the Azure VM.
* Cleaned the VM and captured it into a generalized custom image.
* Deployed and provisioned a VM from this generalized custom image containing custom cloud-init.
* Verified that everything works.

Azure: Add telemetry for poll IMDS

---

tests/integration_tests/modules/test_ca_certs.py

> integration_tests: port ca_certs tests from cloud_tests
Run `pytest --log-cli-level=INFO tests/integration_tests/modules/test_ca_certs.py` and observe success.

integration_tests: port ca_certs tests from cloud_tests

---

.github/workflows/stale.yml

```
stale: re-enable post holidays
This reverts commits fad919aa2c894abaa3af88aed1e064c1220937fe ("stale:
disable check for holiday break (#735)") and
e4f2d6139a802e659c571f581763eddeee715e2f ("stale: fix error in
definition (#740)").
```

stale: re-enable post holidays

---

doc/rtd/topics/network-config-format-v2.rst

```
network-config-format-v2.rst: add Netplan Passthrough section
We don't currently document our passthrough behaviour, which has lead to
some user confusion about what they can rely upon on Ubuntu systems.
This clarifies our support.
```
https://bugs.launchpad.net/cloud-init/+bug/1909138 is an example of a user not understanding our support.
Build the docs and see:

network-config-format-v2.rst: add Netplan Passthrough section

---

tests/integration_tests/clouds.py
tests/integration_tests/integration_settings.py

```
integration_tests: add SSH key selection settings
This introduces PUBLIC_SSH_KEY, to configure what public SSH key should
be passed to (and used to access) systems under test, and KEYPAIR_NAME,
to configure the name used in clouds for that SSH key (or the default
SSH key, in PUBLIC_SSH_KEY's absence).
```
To test both parts together, register a non-default SSH key in EC2 with a key name other than your username, then run:
```
CLOUD_INIT_KEYPAIR_NAME=<EC2 key name> CLOUD_INIT_PUBLIC_SSH_KEY=/path/to/your/created/public/key pytest tests/integration_tests/modules/test_ca_certs.py
```
Verify that the settings have been correctly picked up (by examining the logged output), and then confirm that the test passes.

integration_tests: add SSH key selection settings

---

doc/rtd/topics/datasources/aliyun.rst

```
Add example configuration for datasource `AliYun`
```

Add example configuration for datasource `AliYun`

---

doc/rtd/topics/network-config-format-v1.rst

```
Added some missing IPv6 subnet configuration types (ipv6_dhcpv6-stateful, ipv6_dhcpv6-stateless, ipv6_slaac) to Networking config v1 documentation.
```

doc: document missing IPv6 subnet types

---

cloudinit/net/sysconfig.py
tests/unittests/test_net.py

IPV6_AUTOCONF needs to be set to 'no' on RHEL so NetworkManager can
properly acquire ipv6 address.
rhbz: #1859695
According to additional tests from the reporter Tom Barron on the Original Bugzilla ([1859695](https://bugzilla.redhat.com/show_bug.cgi?id=1859695)) the option IPV6_AUTOCONF should also be set to `no` on this specific case. Most of the BZ is marked as private, though.
(as described on the above mentioned BZ)
Steps to Reproduce:
1. Create StorageNFS network with IPv6 CIDR and address range defined
1. Create a Nova instance with 2 NICs, 2nd NIC connected to StorageNFS network
1. Login to VM and examin Eth1 IP address
Actual results:
The Nova assigned IPv6 address was not assigned to device Eth1
Expected results:
Expected the Nova …

Missing IPV6_AUTOCONF=no to render sysconfig dhcp6 stateful on RHEL

---

cloudinit/cmd/devel/net_convert.py

```
net_convert: add some missing help text
```
You can run this in a local checkout; here's the output diff:
```diff
--- before	2021-01-06 16:23:47.951011650 -0500
+++ after	2021-01-06 16:23:51.771062044 -0500
@@ -7,7 +7,9 @@
optional arguments:
-h, --help            show this help message and exit
-p PATH, --network-data PATH
+                        The network configuration to read
-k {eni,network_data.json,yaml,azure-imds,vmware-imc}, --kind {eni,network_data.json,yaml,azure-imds,vmware-imc}
+                        The format of the given network config
-d PATH, --directory PATH
directory to place output in
-D {alpine,arch,debian,ubuntu,freebsd,gentoo,amazon,centos,fedora,rhel,opensuse,sles}, --distro {alpine,arch,debian,ubuntu,freebsd,gentoo,amazon,centos,fedora,rhel,opensuse,sles} …
```

net_convert: add some missing help text

---

tests/integration_tests/clouds.py

```
integration_tests: log cloud-init version in SUT
```
Run a test and see a log line like this:
```
2021-01-08 16:46:48 INFO      integration_testing:clouds.py:172 cloud-init version: /usr/bin/cloud-init 20.4-0ubuntu1~16.04.1
```

integration_tests: log cloud-init version in SUT

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/test_datasource/test_azure.py

Fix regression with handling of IMDS ssh keys.
```
With the changes for ssh public keys to be retrieved from IMDS as a first option, when a key is passed through not in the raw ssh public key format it causes an issue and the key is not added to the user's authorized_keys file.
This PR will temporarily disable this behavior until a permanent fix is put in place.
```

Fix regression by forcing no IMDS ssh keys

---

tests/integration_tests/bugs/test_lp1910835.py
tox.ini

```
integration_tests: add integration test for LP: #1910835
```
Currently, daily images fail but release images pass (having been rolled back). So you can observe this test fails on dailies (our default target, with cloud-init 20.4) by running:
```
CLOUD_INIT_PLATFORM=azure pytest -m sru_2021_01 tests/integration_tests
```
and you can see the test passes against release images (i.e. cloud-init 20.3, predating the breaking change) by running:
```
CLOUD_INIT_OS_IMAGE="Canonical:0001-com-ubuntu-server-focal:20_04-lts:20.04.202101081" CLOUD_INIT_PLATFORM=azure pytest -m sru_2021_01 tests/integration_tests
```

integration_tests: add integration test for LP: #1910835

---

cloudinit/distros/arch.py
tools/.github-cla-signers

```
archlinux: fix package upgrade command handling
pacman uses `-u` instead of `upgrade` to trigger a system upgrade, fix
the command handling so this is properly accounted for. as is, the
resulting command attempts to install a (non-existent) `upgrade` package
```
Pretty straightforward. Arch's pacman uses `-u` instead of `upgrade` (see [`man 8 pacman`](https://man.archlinux.org/man/core/pacman/pacman.8.en#SYNC_OPTIONS_(APPLY_TO_-S))). Without this change I get an error when `package_upgrade: true`:
```
Cloud-init v. 20.4 running 'single' at Tue, 12 Jan 2021 00:37:17 +0000. Up 3995.82 seconds.
:: Synchronizing package databases...
error: target not found: upgrade
core is up to date
extra is up to date
community is up to date
2021-01-12 00:37:17,927 - util.py[WARNING]: Package upgrade …
```

archlinux: fix package upgrade command handling

---

tests/integration_tests/bugs/test_gh632.py

Fix test gh-632 test to only run on NoCloud
This test was attempting to run and failing on Azure
pytest -s tests/integration_tests/bugs/test_gh632.py
will now skip on anything other than LXD.

Fix test gh-632 test to only run on NoCloud

---

cloudinit/config/cc_seed_random.py
tests/integration_tests/modules/test_seed_random_data.py

```
cc_seed_random: update documentation and fix integration test
The documentation did not mention that the given data may not be the
exact string written: the cloud's random data may be added to it.
Additionally, the documentation of the command key was incorrect.
test_seed_random_data was updated to check that the given data is a
prefix of the written data, to match cloud-init's expected (and, now,
documented) behaviour.
LP: #1911227
```
Run `CLOUD_INIT_PLATFORM=azure pytest tests/integration_tests/modules/test_seed_random_data.py` and observe a pass (vs. a fail previously).

cc_seed_random: update documentation and fix integration test

---

cloudinit/ssh_util.py
tests/unittests/test_sshutil.py

```
Revert "ssh_util: handle non-default AuthorizedKeysFile config (#586)"
This reverts commit b0e73814db4027dba0b7dc0282e295b7f653325c.
LP: #1911680
```
This is the same fix used in the 20.4.1 hotfix release, now being included upstream.
The following integration test can be used to validate this:
```py
ABSOLUTE_AUTH_KEYS_PATH = "/etc/ssh/authorized_keys"
BACKDOOR_KEYS = "/etc/backdoor_keys"
USER_DATA_TMPL = """\
#cloud-config
bootcmd:
- sed -i "s,#AuthorizedKeysFile.*,AuthorizedKeysFile {0} {1}," /etc/ssh/sshd_config
runcmd:
- |
cat << EOF > {1}
{{}}
EOF
""".format(ABSOLUTE_AUTH_KEYS_PATH, BACKDOOR_KEYS)
#
def test_test(session_cloud, setup_image):
user_data = USER_DATA_TMPL.format(
session_cloud.cloud_instance.key_pair.public_key_content
)
with session_cloud.launch(user_data=user_data) …
```

Revert "ssh_util: handle non-default AuthorizedKeysFile config (#586)"

---

tests/integration_tests/clouds.py

```
integration_tests: log image serial if available
Ubuntu cloud images ship /etc/cloud/build.info which includes a line
with the build serial used to identify the image:
serial: 20210108
This is valuable information when verifying Ubuntu issues (to confirm
that testing is happening against the expected image), but is also
useful when debugging test failures: manifests of all packages in (the
base) images can be found at http://cloud-images.ubuntu.com/
```
Run a test (against Ubuntu) and observe:
```
2021-01-13 17:52:03 INFO      integration_testing:clouds.py:178 image serial: 20210112
```

integration_tests: log image serial if available

---

ChangeLog
cloudinit/config/cc_resolv_conf.py
cloudinit/config/cc_rh_subscription.py
doc/rtd/topics/examples.rst
tests/cloud_tests/testcases/examples/TODO.md

The company name has two district words.
Signed-off-by: Dan Kenigsberg <danken@redhat.com>

Use proper spelling for Red Hat

---

doc/rtd/topics/format.rst
tools/.github-cla-signers

Two shell code blocks are not marked as such, confusing rst to consider
them as yaml. Be explicit about their syntax, and use $ prompt to match
elsewhere in the docs.
```
/home/travis/build/canonical/cloud-init/doc/rtd/topics/format.rst:28: WARNING: Could not lex literal_block as "yaml". Highlighting skipped.
/home/travis/build/canonical/cloud-init/doc/rtd/topics/format.rst:52: WARNING: Could not lex literal_block as "yaml". Highlighting skipped.
```
Signed-off-by: Dan Kenigsberg <danken@redhat.com>

doc: avoid two warnings

---

integration-requirements.txt
tests/integration_tests/clouds.py
tests/integration_tests/integration_settings.py

```
Use more cloud defaults in integration tests
Stop requiring compartment_id for OCI and project_id for GCE since they
can now be inferred in pycloudlib.
```
n/a
Remove: GCE_PROJECT, GCE_REGION, GCE_ZONE, and OCI_COMPARTMENT_ID from user_settings.py if they exist there.
Run any integration test using GCE or OCI and it should pass.

Use more cloud defaults in integration tests

---

integration-requirements.txt
tests/integration_tests/bugs/test_gh570.py
tests/integration_tests/bugs/test_lp1900837.py
tests/integration_tests/clouds.py
tests/integration_tests/instances.py
tests/integration_tests/modules/test_power_state_change.py
tests/integration_tests/test_upgrade.py

Pycloudlib no longer raises exceptions when cloud-init fails to start,
and the API has been updated accordingly. Changes have been made to
integration tests accordingly
```
Remove 'remove-raise-on-failure' calls from integration_tests
Pycloudlib no longer raises exceptions when cloud-init fails to start,
and the API has been updated accordingly. Changes have been made to
integration tests accordingly
```
https://github.com/canonical/pycloudlib/pull/93
> pytest tests/integration_tests
Tested on both lxd containers and lxd vms. Failures were unrelated.

Remove 'remove-raise-on-failure' calls from integration_tests

---

tox.ini

```
Stop linting cloud_tests
The tox pylint command was failing because of competing dependencies in
the multiple requirements files. Given that we plan on no longer
updating cloud_tests, we also no longer need to lint them.
```
n/a
`tox -e pylint` in a bionic container

Stop linting cloud_tests

---

HACKING.rst

```
HACKING.rst: add clarifying note to LP CLA process section
We've had some first time contributors still end up trying to submit via
Launchpad: this commit underlines that this is not necessary.
```
Build the docs and observe:

HACKING.rst: add clarifying note to LP CLA process section

---

tests/integration_tests/bugs/test_gh668.py

```
test_gh668: fix failure on LXD VMs
In LXD containers, the default interface is named eth0.  In VMs, it
isn't; it's renamed by systemd (likely to enp5s0, but we can't rely on
that).  This means that, on VMs, the network configuration we specify
for "eth0" doesn't match an interface in the system and so is not
applied.
This modifies the test to set a MAC address in a match clause in the
network configuration and on the eth0 interface (which is the LXD name
in both containers and VMs pre-rename): this ensures that the specified
configuration applies in both cases.
```
Run the test using a LXD VM.

test_gh668: fix failure on LXD VMs

---

tests/integration_tests/modules/test_power_state_change.py
tests/integration_tests/test_upgrade.py

During #788 , I forgot to update the calls to `session_cloud.launch(...)` to remove the `wait` argument.

Remove wait argument from tests with session_cloud calls

---

tests/integration_tests/modules/test_seed_random_data.py

Fix attempting to decode binary data in test_seed_random_data test
`test_seed_random_data.py` was failing on openstack as openstack
provides additional binary seed data to the end of the specified file.
The test has been changed to only read the ascii porition of
seed file.
n/a
Using openstack as the testing platform (requires branch #804 if branch isn't merged yet):
`pytest tests/integration_tests/modules/test_seed_random_data.py`

Fix attempting to decode binary data in test_seed_random_data test

---

tests/integration_tests/bugs/test_gh626.py

```
integration_tests: fix test_gh626 on LXD VMs via SSH
Without a MAC address match clause, the test network configuration is
not applied to the primary interface in LXD VMs (which is named enp*s*
rather than eth0). This means that networking does not come up, so
SSH access is not possible.
```
Run the test on a LXD VM (with either an SSH key configured, or with the new pycloudlib which uses SSH by default) and observe success.

integration_tests: fix test_gh626 on LXD VMs via SSH

---

tests/integration_tests/__init__.py
tests/integration_tests/bugs/test_gh626.py
tests/integration_tests/bugs/test_gh668.py
tests/integration_tests/bugs/test_lp1898997.py
tests/integration_tests/clouds.py
tests/integration_tests/integration_settings.py

```
integration_tests: use unique MAC addresses for tests
Using the same MAC address results in strange test behaviour if more
than one such instance is up: traffic gets routed to an arbitrary
interface with the given MAC address.  This can happen if running tests
in parallel, or on a system which retains test instances from previous
runs.
The introduction of tests/integration_tests/__init__.py means that
pylint now checks the integration tests: this commit also addresses
those failures.
```
This introduces `tests/integration_tests/__init__.py` as a holding place for the utility function this introduces; I didn't want to introduce a `util`, but it also didn't feel like it fit well in anything we currently had.
Run the affected tests in parallel a few times and observe a lack of …

integration_tests: use unique MAC addresses for tests

---

tests/integration_tests/conftest.py
tests/integration_tests/instances.py
tests/integration_tests/integration_settings.py

```
integration_tests: add UPGRADE CloudInitSource
This allows out-of-date images to be brought up-to-date with the
archive, so that tests written against the latest cloud-init release
will pass.
```
This is particularly handy for OpenStack, as deployments may not get fresh Ubuntu images on a regular cadence.
Run tests against a stale image with `CLOUD_INIT_CLOUD_INIT_SOURCE=UPGRADE` in your environment.

integration_tests: add UPGRADE CloudInitSource

---

tox.ini

```
integration_tests: fix use of SSH agent within tox
We need to allow the SSH_AUTH_SOCK environment variable through for
paramiko to be able to find the agent.
```
Run the tests in tox with an SSH key that requires a passphrase and observe that they pass.

integration_tests: fix use of SSH agent within tox

---

.github/workflows/stale.yml

```
stale.yml: don't ask submitters to reopen PRs
Because they don't have the permissions to do it.  Instead, reword the
message to ask people to ping mitechie, in line with the rest of the
message.
```
The lack of permissions was pointed out in https://github.com/canonical/cloud-init/pull/745.
No particularly good way of testing this; we'll have to observe it in action.

stale.yml: don't ask submitters to reopen PRs

---

cloudinit/sources/DataSourceAzure.py
tests/integration_tests/bugs/test_lp1835584.py
tests/integration_tests/instances.py
tests/unittests/test_datasource/test_azure.py
tox.ini

Kernel's newer than 4.15 present /sys/dmi/id/product_uuid as a
lowercase value. Previously UUID was uppercase.
Azure datasource reads the product_uuid directly as their platform's
instance-id. This presents a problem if a kernel is either
upgraded or downgraded across the 4.15 kernel version boundary because
the case of the UUID will change, resulting in cloud-init seeing a
"new" instance id and re-running all modules.
Re-running cc_ssh in cloud-init deletes and regenerates ssh_host keys
on a system which can cause concern on long-running instances that 
somethingnefarious has happened.
Also add:
- An integration test for this for Azure Bionic Ubuntu FIPS upgrading from
a FIPS kernel with uppercase UUID to a lowercase UUID in linux-azure
- A new pytest.mark.sru_next to collect all …

azure: case-insensitive UUID to avoid new IID during kernel upgrade

---

integration-requirements.txt
tests/integration_tests/bugs/test_gh668.py
tests/integration_tests/bugs/test_lp1898997.py
tests/integration_tests/conftest.py
tox.ini

```
integration_tests: introduce lxd_use_exec mark
pycloudlib has modified the way LXD executes tests
(https://github.com/canonical/pycloudlib/pull/114): it will always use
SSH to access them by default, instead of using `lxc exec`.  This
behaviour is transparent for the majority of cloud-init's integration
tests, but some currently depend on using `lxc exec` to access instances
with (intentionally) broken networking: obviously these are not
accessible via SSH.
pycloudlib retains support for switching an instance to use `lxc exec`.
This commit introduces the `lxd_use_exec` mark, which tests can use to
indicate to the integration testing framework that they should be so
switched, and applies it to all applicable tests.
```
See https://github.com/canonical/pycloudlib/pull/114
CI tests will …

integration_tests: introduce lxd_use_exec mark

---

cloudinit/sources/DataSourceAzure.py
integration-requirements.txt
tests/integration_tests/bugs/test_lp1901011.py
tests/unittests/test_datasource/test_azure.py

Azure: Support for VMs without ephemeral resource disks.
Changes:
* Only merge in default Azure cloud ephemeral disk configs
during `DataSourceAzure._get_data()` if the ephemeral disk
exists.
* `DataSourceAzure.address_ephemeral_resize()` (which is
invoked in `DataSourceAzure.activate()` should only set up
the ephemeral disk if the disk exists.
Azure VMs may or may not come with ephemeral resource disks
depending on the VM SKU. For VM SKUs that come with
ephemeral resource disks, the Azure platform guarantees that
the ephemeral resource disk is attached to the VM before
the VM is booted. For VM SKUs that do not come with
ephemeral resource disks, cloud-init currently attempts
to wait and set up a non-existent ephemeral resource
disk, which wastes boot time. It also causes disk setup …

Decrease azure ephemeral resource disk wait time

---

ChangeLog
cloudinit/version.py

```
Release 21.1
Bump the version in cloudinit/version.py to 21.1 and
LP: #1916540
```
Due to the 20.4.1 hotfix, a couple of manual modifications to our automated output were made. The merge commit was removed from the changelog, and the automatically incremented version was fixed up (from 21.1.1).

Release 21.1

---

cloudinit/config/cc_keys_to_console.py

PR #811 added a new config key, emit_keys_to_console, but didn't update the
documentation for mention it.

cc_keys_to_console.py: Add documentation for recently added config key

---

cloudinit/distros/arch.py
tools/.github-cla-signers

```
archlinux: Use hostnamectl to set the transient hostname
hostname (inetutils) isn't installed per default on arch, so switch
to hostnamectl which is installed per default (systemd).
```
This has been tested manually with the Arch Linux [cloud-init package](https://archlinux.org/packages/community/any/cloud-init/) (`arch.py` patched with the changes in this commit) and `inetutils` forcefully removed (`pacman -Rsddn inetutils`).

archlinux: Use hostnamectl to set the transient hostname

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/test_datasource/test_azure.py

Add flexibility to IMDS api-version by having both a desired IMDS api-version and a minimum api-version. The desired api-version will be used first, and if that fails it will fall back to the minimum api-version.
This PR will allow us to rollout features in cloud-init to take advantage of newer features in IMDS.
The following shell script was used to validate this end-to-end both using an existing desired IMDS api-version and then using an impossible (future) api-version, forcing a fallback to the minimum version. This script relies on [helper functions from my az-cli-helpers repo](https://github.com/trstringer/az-cli-helpers).
```bash
#!/bin/bash -i
RESOURCE_NAME=$(resource_name)
echo "$(date) - Using resource name $RESOURCE_NAME"
az_vm_create_default
az_vm_deb_install "$RESOURCE_NAME" …
```

Add flexibility to IMDS api-version

---

integration-requirements.txt
tests/integration_tests/clouds.py
tests/integration_tests/conftest.py
tests/integration_tests/integration_settings.py

```
Add openstack as a testing platform
```
set `OPENSTACK_NETWORK` appropriately in user_settings.py. Then
`CLOUD_INIT_PLATFORM=openstack CLOUD_INIT_OS_IMAGE=3709d596-ce0d-45ac-976a-9d2f3ce46474 pytest tests/integration_tests`

Add openstack as a testing platform

---

tox.ini

```
tox.ini: pass OS_* environment variables to integration tests
This allows source'd OpenStack credentials to be used for tox tests.
```
This fails without the change, and passes with it:
```
. /path/to/novarc
CLOUD_INIT_OS_IMAGE="..." CLOUD_INIT_PLATFORM=openstack tox -e integration-tests-ci
```

tox.ini: pass OS_* environment variables to integration tests

---

cloudinit/net/__init__.py
cloudinit/net/tests/test_init.py
cloudinit/sources/helpers/tests/test_openstack.py
cloudinit/sources/tests/test_oracle.py
tests/integration_tests/bugs/test_lp1912844.py
tests/unittests/test_datasource/test_configdrive.py
tests/unittests/test_net.py

```
net: exclude OVS internal interfaces in get_interfaces
`get_interfaces` is used to in two ways, broadly: firstly, to determine
the available interfaces when converting cloud network configuration
formats to cloud-init's network configuration formats; and, secondly, to
ensure that any interfaces which are specified in network configuration
are (a) available, and (b) named correctly.  The first of these is
unaffected by this commit, as no clouds support Open vSwitch
configuration in their network configuration formats.
For the second, we check that MAC addresses of physical devices are
unique.  In some OVS configurations, there are OVS-created devices which
have duplicate MAC addresses, either with each other or with physical
devices.  As these interfaces are created by OVS, we can be …
```

net: exclude OVS internal interfaces in get_interfaces

---

cloudinit/sources/DataSourceEc2.py
tests/unittests/test_datasource/test_aliyun.py

```
Fix requiring device-number on EC2 derivatives
#342 (70dbccbb) introduced the ability to determine route-metrics based on
the `device-number` provided by the EC2 IMDS. Not all datasources that
subclass EC2 will have this attribute, so allow the old behavior if
`device-number` is not present.
LP: #1917875
```
n/a
Run unit tests

Fix requiring device-number on EC2 derivatives

---

tests/integration_tests/clouds.py

```
integration_tests: mount more paths IN_PLACE
This mounts the full directories that we install into systems over their
corresponding paths within the system under test, getting us slightly
closer to testing what a package would install.
```
Make a change to the relevant files locally, run:
```sh
CLOUD_INIT_KEEP_INSTANCE=true CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE pytest tests/integration_tests/modules/test_runcmd.py
```
(or any other single test) and observe that your changes are present in the instance.

integration_tests: mount more paths IN_PLACE

---

tests/integration_tests/modules/test_users_groups.py

```
Integration test for #783
Newer verisons of /etc/sudoers prefer @includedir over
#includedir. Ensure we handle that properly and don't include an
additional #includedir when one isn't warranted.
```
#783
Run tests/integration_tests/modules/test_users_groups.py on Groovy or later. Pre-SRU, you'll also need an image including the relevant code.

Integration test for #783

---

tests/integration_tests/modules/test_apt.py
tox.ini

The apt default test wasn't ported over from cloud-tests correctly.
Fix it so it works as it did in the cloud tests.
Also add openstack specific test for apt configuration with no uri.
```
Fix apt default integration test
The apt default test wasn't ported over from cloud-tests correctly.
uri should be specified in the test, but it was not, so the test
failed on openstack (and likely other platforms) because without
a specified uri, the default uri will vary by platform. I separated
this uri test out into a separate test function.
Also add openstack specific test for apt configuration with no uri.
Other platform-specific tests should be added here over time.
```
n/a
Run integration tests on openstack

Fix apt default integration test

---

cloudinit/config/cc_set_passwords.py
cloudinit/config/tests/test_set_passwords.py
cloudinit/tests/test_util.py
cloudinit/util.py
tests/integration_tests/modules/test_set_password.py
tests/integration_tests/test_logging.py
tests/unittests/test_util.py

```
write passwords only to serial console, lock down cloud-init-output.log
Prior to this commit, when a user specified configuration which would
generate random passwords for users, cloud-init would cause those
passwords to be written to the serial console by emitting them on
stderr.  In the default configuration, any stdout or stderr emitted by
cloud-init is also written to `/var/log/cloud-init-output.log`.  This
file is world-readable, meaning that those randomly-generated passwords
were available to be read by any user with access to the system.  This
presents an obvious security issue.
This commit responds to this issue in two ways:
* We address the direct issue by moving from writing the passwords to
sys.stderr to writing them directly to /dev/console (via
util.multi_log); this …
```

write passwords only to serial console, lock down cloud-init-output.log

---

.travis.yml

```
.travis.yml: generate an SSH key before running tests
```
The Travis run should run successfully; note that we currently have a bug where it always goes green: the log will need to be examined.

.travis.yml: generate an SSH key before running tests

---

doc/examples/cloud-config-chef.txt
tools/.github-cla-signers

Fix chef apt source
```
summary: Fix chef apt source
key is a property of source1 and not sources
```
try to add a apt repository with the old docs
apt repository wont be added

Fix chef apt source

---

cloudinit/sources/helpers/azure.py
tests/unittests/test_datasource/test_azure_helper.py

```
Azure helper: sleep between retries for http handler
Ensure that the Azure helper's http
handler sleeps a fixed duration
between retry failure attempts.
The http handler will sleep a
fixed duration between failed
attempts regardless of whether
the attempt failed due to
(1) request timing out or
(2) instant failure (no timeout).
Due to certain platform issues,
the http request to the Azure
endpoint may instantly fail
without reaching the http
timeout duration.
Without sleeping a fixed duration
in between retry attempts, the
http handler will loop through
the max retry attempts quickly.
This causes the communication
between cloud-init and the
Azure platform to be less
resilient due to the
short total duration
if there is no sleep in
between retries.
```
* Created a cloud-init package …

Azure helper: sleep between retries for http handler

---

tests/integration_tests/modules/test_keys_to_console.py
tools/write-ssh-key-fingerprints

When console output of SSH info is disabled show no headers/footers.
Prevent risk of message text being interpreted as "logger" option by
appending "--" to logger options.
Correct syslog output that was tagged with "ec2" regardless of DataSource
in use. Now use "cloud-init" tag instead.
Various "shellcheck" corrections.
Add testcase for disabled output of SSH host keys.
LP: #1915460
Provides alternative solution to #811.
In user-data config add either, or both, of the following lines:
```
ssh_fp_console_blacklist: [ 'ssh-dsa', 'ssh-dss', 'ssh-rsa', 'ssh-ed25519' ]
ssh_key_console_blacklist: [ 'ssh-dsa', 'ssh-dss', 'ssh-rsa', 'ssh-ed25519' ]
```

tools/write-ssh-key-fingerprints: do not display empty header/footer

---

cloudinit/net/cmdline.py
tests/unittests/test_net.py

**Integration test still needs to be written**
```
Fix mis-detecting network configuration in initramfs cmdline
klibc initramfs in debian allows the 'iscsi_target_ip=' cmdline
parameter to specify an iscsi device attachment. This can
cause cloud-init to mis-detect the cmdline paramter as a
networking config.
LP: #1919188
```
https://bugs.launchpad.net/cloud-init/+bug/1919188
**Integration test still needs to be written**

Fix mis-detecting network configuration in initramfs cmdline

---

cloudinit/net/__init__.py
cloudinit/net/tests/test_dhcp.py
cloudinit/net/tests/test_init.py
tools/.github-cla-signers

```
Inside gateway field we has ip address not in CIDR notation. We must check it because of different ip route behavior for gatewayed and direct routes.
```
Try to run cloud-init with classless-static-routes with direct-connection of networks give me errors https://github.com/lf-edge/eve/pull/1982#issuecomment-802983262.

bringup_static_routes: fix gateway check

---

cloudinit/net/sysconfig.py
tests/unittests/test_net.py

Current documentation[1][2] recommends to use BONDING_MODULE_OPTS
instead of BONDING_OPTS. SLES/wicked even ignores BONDING_OPTS
except for the bonding mode and requires BONDING_MODULE_OPTS.
[1] https://wiki.linuxfoundation.org/networking/bonding
[2] https://www.kernel.org/doc/Documentation/networking/bonding.txt
I also changed the name of the render function so that there is no difference between function_name and what it does.
Currently bonding on SLES (I only tested 15sp2 but it's probably true for prior versions as well as even SLES9 docu only mentions BONDING_MODULE_OPTS) via Configdrive on OpenStack fails because cloud-init sets BONDING_OPTS but SLES ignores the BONDING_OPTS. SLES also requires that the miimon option is set. (SLES [config …

bonding sysconfig: use bonding_module_opts instead of bonding_opts

---

cloudinit/sources/DataSourceAzure.py
doc/rtd/topics/datasources/azure.rst
tests/unittests/test_datasource/test_azure.py

azure: removing ability to invoke walinuxagent from within cloud-init as this is no longer supported/necessary.

Removing ability to invoke walinuxagent from cloud-init

---

cloudinit/config/cc_rightscale_userdata.py
doc/rtd/topics/boot.rst
doc/rtd/topics/vendordata.rst

```
doc: Replace remaining references to user-scripts as a config module
git-grep showed a few more locations where we refer to a "user-scripts"
config module which is really cc_scripts_user module.  Replace these
references with slightly different language so as not to confuse
future me when looking for "user-scripts" vs. "scripts-user"
```
```
tox -e doc
```
that apply. -->

doc: Replace remaining references to user-scripts as a config module

---

cloudinit/config/cc_set_hostname.py
cloudinit/config/cc_update_hostname.py
cloudinit/distros/__init__.py
cloudinit/distros/freebsd.py
cloudinit/distros/rhel.py
tests/integration_tests/modules/test_set_hostname.py
tests/unittests/test_handler/test_handler_set_hostname.py

add prefer_fqdn_over_hostname config option
the above option allow the user to control the
behavior of a distro hostname selection
so if the user send hostname, FQDN Configs
if prefer_fqdn_over_hostname is true the
The FQDN will be selected as hostname
if false the hostname will be selected
LP: #859 
```
```

Add an option for rhel to force the use of hostname config

---

cloudinit/sources/__init__.py
cloudinit/tests/test_upgrade.py
tests/integration_tests/clouds.py
tests/integration_tests/test_upgrade.py

```
Fix error on upgrade caused by new vendordata2 attributes
In #777, we added 'vendordata2' and 'vendordata2_raw' attributes to
the DataSource class, but didn't use the upgrade framework to deal
with an unpickle after upgrade. This commit adds the necessary
upgrade code.
Additionally, added a smaller-scope upgrade test to our integration
tests that will be run on every CI run so we catch these issues
immediately in the future.
LP: #1922739
```
We haven't caught this is our current upgrade test because we haven't been checking for error status of `cloud-init status`. I added a check for that in the larger upgrade test as well.
Since the latest cloud-init version is already in LXD images, it's not as straightforward. You can launch a xenial instance and then upgrade to the latest PPA/deb. …

Fix error on upgrade caused by new vendordata2 attributes

---

cloudinit/sources/DataSourceAzure.py
cloudinit/sources/helpers/azure.py
tests/unittests/test_datasource/test_azure_helper.py

Azure: eject the provisioning iso before reporting ready
Due to hyper-v implementations, iso ejection is more efficient if performed 
from within the guest. The code will attempt to perform a best-effort ejection.
Failure during ejection will not prevent reporting ready from happening. If iso
ejection is successful, later iso ejection from the platform will be a no-op.
In the event the iso ejection from the guest fails, iso ejection will still happen at
the platform level.

Azure: eject the provisioning iso before reporting ready

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/test_datasource/test_azure.py

Azure: Retry getting network metadata during nic attach for all non-timeout errors.
When network interfaces are hot-attached to the VM, attempting to get network metadata might return 410 (or 500, 503 etc) because the info is not yet available. In those cases, we retry getting the metadata before giving up. The only case where we can move on to wait for more nic attach events is if the call times out despite retries, which means the interface is not likely a primary interface, and we should try for more nic attach events.
* Deploy Pre-provisioned VM in Azure of type "savable" (internal to Azure)
* Reuse the VM with one or more network interfaces
* When repeating this multiple times, some of them might fail if the platform is not ready to serve the network metadata

Azure: Retry getting network metadata during nic attach for all non-timeout errors

---

cloudinit/config/cc_chef.py
templates/chef_client.rb.tmpl
tools/.github-cla-signers

Move `chef_license` from TPL_PATH_KEYS to TPL_KEYS as the chef license setting is not a path but must be added to the client config template. Fixes file or folder not found exception raised from `ensure_dirs`.
Perform a cloud-init run with chef bootstrap configuration and chef_license set.

Fix chef module run failure when chef_license is set

---

cloudinit/config/cc_growpart.py
doc/examples/cloud-config-growpart.txt
tests/unittests/test_handler/test_handler_growpart.py

```
Revert "Add support to resize rootfs if using LVM (#721)"
This reverts commit 74fa008bfcd3263eb691cc0b3f7a055b17569f8b.
During pre-release testing, we discovered two issues with this commit.
Firstly, there's a typo in the udevadm command that causes a TypeError
for _all_ growpart executions.  Secondly, the LVM resizing does not
appear to successfully resize everything up to the LV, though some
things do get resized.
We certainly want this change, so we'll be happy to review and land it
alongside an integration test which confirms that it is working as
expected.
LP: #1922742
```
I'm working on an integration test to cover this LVM case, as it's a fairly complex use of our test framework. A rough draft can be seen in https://paste.ubuntu.com/p/y6zG3fdTZv/
LXD containers do not perform …

Revert "Add support to resize rootfs if using LVM (#721)"

---

cloudinit/tests/helpers.py
cloudinit/tests/test_url_helper.py

```
Fix unit tests breaking from new httpretty version
Httpretty now logs all requests by default which gets mixed up with our
logging tests. Also we were incorrectly setting a logging level to
'None', which now also causes issues with the new httpretty version.
See https://github.com/gabrielfalcao/HTTPretty/pull/419
```
Run pytest

Fix unit tests breaking from new httpretty version

---

cloudinit/net/bsd.py
cloudinit/net/freebsd.py
cloudinit/net/netbsd.py
cloudinit/net/openbsd.py

In the case of a static network, we now set the MTU according to the
meta-data.

BSD: static network, set the mtu

---

tests/integration_tests/bugs/test_gh868.py

```
Add integration test for #868
Ensure no Traceback when 'chef_license' is set
```
pytest tests/integration_tests/bugs/test_gh868.py

Add integration test for #868

---

cloudinit/net/openbsd.py

Ensure we've got a clean environment before we restart the network.
In some cases, the `sh /etc/netstart` is not enough to restart the
network. A previous default route remains in the route table and
as a result the network is broken.
Also `sh /netstart` does not kill `dhclient`.
The problen happens for instance with OVH OpenStack SBG3.

openbsd/net: flush the route table on net restart

---

HACKING.rst
README.md
doc/rtd/index.rst
doc/rtd/topics/code_review.rst
doc/rtd/topics/debugging.rst
doc/rtd/topics/faq.rst

Libera has no webchat, so removed one link, and replaced another with a link to the main website.

Docs: Replace all freenode references with libera (SC-68)

---

cloudinit/net/dhcp.py
cloudinit/net/tests/test_dhcp.py

Allow braces to appear in dhclient output
```
dhclient output that contains brackets for pxe variables will break the dhclient parsing regex line. This fix retains the current
functionality while fixing this particular issue.
```
Not sure if there are any cases I may be missing that the regex there was intended to resolve, but this line passes the tests and
fixes my particular issue with it. It seems to function exactly as it did before from what I can see.
This was the following output that broke this line,
```
lease {
interface "enp1s0f0";
fixed-address 45.63.17.162;
filename "http://100.100.100.1/getbootconfig.php?mac=${netX/mac}";
server-name "100.100.100.1";
option subnet-mask 255.255.254.0;
option routers 45.63.16.1;
option dhcp-lease-time 86400;
option dhcp-message-type 5;
option …
```

Allow braces to appear in dhclient output

---

cloudinit/stages.py
cloudinit/tests/test_stages.py

+ Security scanners are often simple minded and complain on arbitrary
settings such as file permissions. For /var/log/* having world read is
one of these cases.
Appease some simple minded "security" scanners
```
summary: Change log file to 640 permissions
Security scanners are often simple minded and complain on arbitrary
settings such as file permissions. For /var/log/* having world read is
one of these cases.
```
- [ x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)

- Create the log file with 640 permissions

---

tools/build-on-netbsd

Reuse the FreeBSD logic to be able to switch between Python3 versions
easily.

build-on-netbsd: don't pine a specific py3 version

---

cloudinit/handlers/jinja_template.py
doc/rtd/topics/instancedata.rst
tests/unittests/test_builtin_handlers.py

```
Use instance-data-sensitive.json in jinja templates
instance-data.json redacts sensitive data for non-root users. Since user
data is consumed as root, we should be consuming the non-redacted data
instead.
LP: #1931392
```
https://bugs.launchpad.net/cloud-init/+bug/1931392
Run unit tests

Use instance-data-sensitive.json in jinja templates (SC-117)

---

cloudinit/log.py

```
Replace deprecated collections.Iterable with abc replacement
LP: #1932048
```
> Deprecated since version 3.3, will be removed in version 3.10: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.9.
https://docs.python.org/3.9/library/collections.html
I did a quick search for any other references to something in `collections` that should be coming from `collections.abc` and didn't find anything.
n/a

Replace deprecated collections.Iterable with abc replacement (SC-127)

---

cloudinit/reporting/events.py
tests/unittests/test_reporting.py
tools/.github-cla-signers

- small document update for ReportEventStack explaining post_files
parameter
- small unit test for test_reporting demonstrating the close of an
event with optional post_files list
Hey there, this project is rad! Trying to wrap my head around bits of it here and there, very greenhorn still haha. Thought there might be a slight benefit to a little more documentation surrounding an optional list parameter.  Added an additional little test for small additional gain of test coverage and demonstration.

Small Doc Update for ReportEventStack and Test

---

tests/integration_tests/bugs/test_gh868.py
tox.ini

```
tests: Add 'adhoc' mark for integration tests
Also new jenkins tox definition
```
Not all integration tests should get run in jenkins.

tests: Add 'adhoc' mark for integration tests

---

cloudinit/net/network_state.py
cloudinit/net/tests/test_network_state.py
doc/rtd/topics/network-config-format-v1.rst

```
Fix DNS in NetworkState
v1 network config currently has no concept of interface-specific DNS,
which is required for certain renderers. To fix this, added an
optional 'interface' key on the v1 nameserver definition. If
specified, it makes the DNS settings specific to the interface.
Otherwise, it will be defined as global DNS as it always has.
Additionally, DNS for v2 wasn't being recognized correctly. For DNS
defined on a particular interface, these settings now also go into the
global DNS settings as they were intended.
```
These changes would help enable a systemd-networkd renderer.
Added new unit tests. This can't be integration tested yet as a renderer would need to pick up these changes.

Fix DNS in NetworkState (SC-133)

---

HACKING.rst
README.md
doc/rtd/topics/code_review.rst
doc/rtd/topics/datasources/ovf.rst
doc/rtd/topics/faq.rst
doc/rtd/topics/format.rst
doc/rtd/topics/testing.rst

```
Update doc references to 'main' default branch due to rename.
Also some links have eroded:
-  for doc links directly to a line num link to a
blob/<commit>/file/path#L10 instead of blob/<branch_name>.
- pytest.param link to a specific version doc as latest has dropped
the link
```
tox -e doc
open browser to doc/rtd_html/index,html

docs: fix stale links rename master branch to main

---

tests/cloud_tests/releases.yaml

```
cloud_tests: add impish release definition
```
Spotted in our integration testing.
On `main`:
```
$ python3 -m tests.cloud_tests run --os-name=impish --platform=nocloud-kvm --preserve-data --data-dir=results --verbose                                2021-06-18T16:06:28 CEST
usage: cloud_tests run [-h] [-p PLATFORM] [-n NAME] [-t FILE] [--feature-override FEATURE_OVERRIDE] [-v] [-q] [-r FILE] [-d DIR] [--preserve-instance] [--preserve-data] [--deb FILE] [--rpm FILE] [--script DATA]
[--repo NAME] [--ppa NAME] [-u] [--upgrade-full]
cloud_tests run: error: argument -n/--os-name: invalid choice: 'impish' (choose from 'artful', 'bionic', 'centos66', 'centos70', 'cosmic', 'disco', 'eoan', 'focal', 'groovy', 'hirsute', 'jessie', 'stretch', 'trusty', 'xenial')
```
With this PR:
```
$ python3 -m …
```

cloud_tests: add impish release definition

---

debian/changelog
debian/cloud-init.templates
debian/cloud-init.templates.README

- Revert "d/cloud-init.templates: comment about why Oracle DS is absent"
- Update d/changelog (UNRELEASED)
If it's OK not to squash PRs to packaging branches then maybe this can be merged non-squashed. Otherwise the commit message can be
```
d/cloud-init.templates: remove comment (unsupported by debconf)
```
Spotted by our CI.
When installing a deb package with the comment this happens:
```
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
Template parse error near `# Oracle DS absent to retain orig behavior: Oracle(Bionic) == OpenStack detected', in stanza #1 of /var/lib/dpkg/info/cloud-init.templates
dpkg: error processing …
```

d/cloud-init.templates: remove comment (unsupported by debconf)

---

tests/cloud_tests/releases.yaml

```
cloud_tests: fix the Impish release name
Commit f5a2449 introduced Impish but left the release name set to
'hirsute'.
```
Spotted by our CI. 
On `main`:
```
$ tox -e citest -- run "--os-name=impish" \
--platform=nocloud-kvm --preserve-data --data-dir=results \
--verbose "--deb=DAILY_DEB.deb"
AssertionError: 'impish' != 'hirsute'
- impish
+ hirsute
```

cloud_tests: fix the Impish release name

---

cloudinit/net/bsd.py
tests/unittests/test_net_freebsd.py

```
bsd/net_v1 format: read MTU from interface config
We read the MTU from the subnet entries. With the v1 format, the MTU can
be set at the root level of the interface entry in the `config` section.
Limitation, we won't set the MTU if the interface use DHCP. This
would require a bit of refactoring.
Also simplify/clarify how we pass the target variable in `cloudinit.net.bsd`.
See: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256309
Reported-by: Andrey Fesenko
```
- [ x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
- [ x] I have updated or added any unit tests accordingly
- [ x] I have updated or added any documentation accordingly

bsd/net_v1 format: read MTU from interface config

---

cloudinit/sources/DataSourceOVF.py
doc/rtd/topics/datasources/ovf.rst
tests/unittests/test_datasource/test_ovf.py

…update the documentation. Fix bugs about max_wait.
summary: Introduce a new switch allow_raw_data to control raw data feature, its default value is true. Also fix bugs about max_wait. Update the documentation accordingly.
Set allow_raw_data to True and False in datasource config, trigger the guest customization on VMware vsphere and verify cloud-init could get the execpted data source.
- [ X] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
- [ X] I have updated or added any unit tests accordingly
- [ X] I have updated or added any documentation accordingly

VMware: add a new switch allow_raw_data to control raw data feature

---

tools/read-dependencies
tools/run-container

```
run-container: fixup the centos repos baseurls when using http_proxy
The EPEL repo file used to have download.fedoraproject.org as its
baseurl. That has now been replaced by `download.example`, which we need
to replace with dl.fedoraproject.org, the actual mirror we want to
download from.
We can't use download.fedoraproject.org or the mirrorlist (which is the
default way for finding mirrors) because of our internal proxy rules.
This change only applies if http_proxy is set, otherwise the mirrors are
reached in the default way.
```
Should fix our `cloud-init-copr-build` job.
Follow what Jenkins does step by step:
https://github.com/canonical/server-jenkins-jobs/blob/main/jenkins-jobs/cloud-init/centos.yaml#L60

run-container: fixup the centos repos baseurls when using http_proxy

---

cloudinit/distros/photon.py
config/cloud.cfg.tmpl
doc/rtd/topics/availability.rst
doc/rtd/topics/network-config.rst
tests/unittests/test_distros/test_photon.py

Currently cloud-init generates fallback network config on various
scenarios.
For example:
1. When no DS found
2. There is no 'network' info given in DS metadata.
3. If a DS gives a network config once and upon reboot if DS doesn't
give any network info, previously set network data will be
overridden.
This newly introduced key can be used to control this behaviour.
Also, if OS comes with a set of default network files(configs), like in
PhotonOS, cloud-init should not overwrite them by default.
cloud.cfg.tmpl: add a key to manage fallback network config
```
Currently cloud-init generates fallback network config on various
scenarios.
For example:
1. When no DS found
2. There is no 'network' info given in DS metadata and so on.
3. If a DS …
```

cloud.cfg.tmpl: add a key to manage fallback network config

---

tests/integration_tests/modules/test_ssh_import_id.py
tests/integration_tests/util.py

```
testing: fix test_ssh_import_id.py
test_ssh_import_id.py occassionally fails because cloud-init finishes
before the keys have been fully imported. A retry has been added to the
test .
```
pytest tests/integration_tests/modules/test_ssh_import_id.py

testing: fix test_ssh_import_id.py (SC-272)

---

cloudinit/distros/photon.py
cloudinit/net/activators.py
cloudinit/net/networkd.py
tests/unittests/test_distros/test_photon.py
tests/unittests/test_handler/test_handler_set_hostname.py
tests/unittests/test_net_activators.py

distros/photon.py: refactor hostname handling

---

tools/.github-cla-signers

This change adds myself and two Puppet employees, @GabrielNagy and @ciprianbadescu, to the approved CLA signers list in support of #960.
```
tools: Add Puppet contributors to CLA signers
```

Add Puppet contributors to CLA signers

---

cloudinit/config/cc_puppet.py
doc/examples/cloud-config-puppet.txt
tests/cloud_tests/testcases/examples/setup_run_puppet.yaml
tests/unittests/test_handler/test_handler_puppet.py

```
cc_puppet: support AIO installations and more
- update the puppet module to support AIO installations by setting
`install_type` to `aio`
- make the install collection configurable through the `collection`
parameter; by default the rolling `puppet` collection will be used,
which installs the latest version)
- when `install_type` is `aio`, puppetlabs repos will be purged after
installation; set `cleanup` to `False` to prevent this
- AIO installations are performed by downloading and executing a shell
script; the URL for this script can be overridden using the
`aio_install_url` parameter
- make it possible to run puppet agent after installation/configuration
via the `exec` key
- by default, puppet agent will run with the `--test` argument; this can
be overridden via the `exec_args` key …
```

cc_puppet: support AIO installations and more

---

requirements.txt

```
Change netifaces dependency to 0.10.4
Currently versions Ubuntu <=20.10 use netifaces 0.10.4 By requiring
netifaces 0.10.9, the VMware datasource omitted itself from cloud-init
on Ubuntu <=20.10.
This patch changes the netifaces dependency to 0.10.4. While it is true
there are patches to netifaces post 0.10.4 that are desirable, testing
against the most common network configuration was performed to verify
the VMware datasource will still function with netifaces 0.10.4.
```
NA
To verify this patch, two Dockerfiles were created based on Ubuntu 20.04:
**netifaces 0.10.4**
```Dockerfile
FROM ubuntu:20.04
RUN apt-get -y update && \
apt-get -y --no-install-recommends install \
ca-certificates \
curl \
git \
python3 \
python3-configobj \
python3-distutils \
python3-requests \
python3-yaml …
```

Change netifaces dependency to 0.10.4

---

tools/ds-identify

Other minor tweaks.
Update dscheck_VMware's rpctool check
```
Update dscheck_VMware's rpctool check
This patch updates the dscheck_VMware function's use of "vmware-rpctool".
When checking to see if a "guestinfo" property is set.
Because a successful exit code can occur even if there is an empty
string returned, it is possible that the VMware datasource will be
loaded as a false-positive. This patch ensures that in addition to
validating the exit code, the emitted output is also examined to ensure
a non-empty value is returned by rpctool before returning "${DS_FOUND}"
from "dscheck_VMware()".
Other minor tweaks in ds-identify script.
```

 Update dscheck_VMware's rpctool check

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/test_datasource/test_azure.py

Azure: Check if interface is up after sleep when trying to bring it up
```
summary:
When bringing interface up by unbinding and then binding hv_netvsc driver, it might take a short delay after binding for the link to be up. So before trying unbind/bind again after sleep, check if the link is up. This is a corner case when a preprovisioned VM is reused and the NICs are hot-attached.
```
- Deploy savable Pre-provisioned VMs whose NICs get hot-attached when they get reprovisioned
- Reuse them for a multi-NIC VM. In some cases, this may show up as a delay for the VM to report ready because we aggressively unbind, bind and check of status immediately after the bind.

Check if nic is up after sleep when trying to bring it up

---

tests/unittests/test_handler/test_handler_puppet.py

```
Replace broken httpretty tests with mock
Certain versions of python/httpretty don't work correctly using https
URIs. #960 recently added httpretty tests using https. This commit
replaces the httpretty tests that were failing on https with mocks of
readurl instead.
```
This was found by running `packages/bddeb` on main.
The [root cause](https://github.com/gabrielfalcao/HTTPretty/issues/242) has been open for 6 years now (and has affected other parts of the code base), so we may want to migrate to [responses](https://github.com/getsentry/responses) at some point in the future.

Replace broken httpretty tests with mock (SC-324)

---

tools/ds-identify

```
Revert unnecesary lcase in ds-identify
This patch reverts an unnecessary lcase optimization in the
ds-identify script. SystemD documents the values produced by
the systemd-detect-virt command are lower case, and the mapping
table used by the FreeBSD check is also lower-case.
The optimization added two new forked processes, needlessly
causing overhead.
```
Please see https://github.com/canonical/cloud-init/pull/970#discussion_r688621314 for more information.
cc @smoser 
```bash
$ make clean_pyc && PYTHONPATH="$(pwd)" python3 -m pytest -v tests/unittests/test_ds_identify.py
```

Revert unnecesary lcase in ds-identify

---

cloudinit/cmd/devel/hotplug_hook.py
cloudinit/sources/__init__.py
tests/integration_tests/modules/test_hotplug.py
tools/hook-hotplug

```
Only invoke hotplug socket when functionality is enabled
Alter's hotplug hook to have a query mechanism checking if the
functionality is enabled. This allows us to avoid using the hotplug
socket and service when hotplug is disabled.
`cloud-init devel hotplug-hook -s net query` will return 'enabled' or
'disabled' depending on hotplug availability.
```
n/a
see integration test

Only invoke hotplug socket when functionality is enabled (SC-251)

---

tests/integration_tests/test_upgrade.py

```
testing: skip upgrade tests on LXD VMs
The issues we see on Bionic VMs don't appear anywhere else, including
when invoking kvm directly. It likely has to do with the extra
LXD agent setup happening on bionic. Given that we still have Bionic
covered on all other platforms, the risk of skipping bionic for LXD VM
tests seems low.
```

testing: skip upgrade tests on LXD VMs

---

tests/unittests/test_datasource/test_vmware.py

Running `test_vmware.py` in isolation (or on an rpm-based system) will cause errors due to some missing mocks.

testing: Add missing mock to test_vmware.py (SC-348)

---

cloudinit/cmd/devel/logs.py

```
Ignore hotplug socket when collecting logs
Update "cloud-init collect-logs" to ignore
/run/cloud-init/hook-hotplug-cmd as this will raise the error
"/run/cloud-init/hook-hotplug-cmd` is a named pipe" if included.
Also updated logs.py to continue writing the tarball if it fails
collecting a file rather than let the exception bubble up.
LP: #1940235
```
https://bugs.launchpad.net/cloud-init/+bug/1940235
Start an impish image (or `packages/bddeb`, upload to your instance, install deb and reboot).
Run `cloud-init collect-logs`
On main, fails as mentioned in the bug. On this branch, shows `Wrote /root/cloud-init.tar.gz` having `hook-hotplug-cmd` excluded from the tarball. From now on, if any other error is encountered, we should see something along the lines of:
```
Failed collecting …
```

Ignore hotplug socket when collecting logs (SC-345)

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/test_datasource/test_azure.py

Azure: During primary nic detection, check interface status with sleep before rebinding again
This is a follow up to #972. After A/B testing in Azure and getting inputs from networking experts, we realized the best way to detect if nic is up after netvsc unbind/bind is to check continuously for a while instead of rebinding immediately after 1 second. This change ensures that after a rebind, we check the link status every 500ms for 10s before trying rebind again. Validations in Azure confirm that this is the best way to bring the link up fast instead of continuously rebinding in a loop which could result in failures.
- Deploy a savable PPS VM in Azure (repro is internal to Azure)
- Reuse the VM with multiple NICs. Without this fix, a small number of the VMs could fail because cloudinit …

Azure: During primary nic detection, check interface status continuously before rebinding again

---

tests/integration_tests/modules/test_ssh_keysfile.py

```
testing: Fix ssh keys integration test
Home directory permissions changed in hirsute. The integration test
assumed permissions from earlier releases. Test was fixed to take both
permissions into account
```

testing: Fix ssh keys integration test

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/test_datasource/test_azure.py

Azure: Retry dhcp on timeouts when polling reprovisiondata in the nic attach path
```
In the nic attach path, we skip doing dhcp since we already did it when bringing the interface up.
However when polling for reprovisiondata, it is possible for the request to timeout due to platform issues.
In those cases we still need to do dhcp and try again since we tear down the context. We can only skip the first dhcp attempt.
```
- Create savable PPS VMs (internal to Azure)
- Reuse the PPS VM to exercise the nic hot attach path
- In rare cases, the first attempt to get reprovisiondata might timeout. Without this fix, cloud-init would tear down the dhcp and all retry attempts since then would fail with network unreachable error. With this fix, dhcp is retried and the polling continues.

Azure: Retry dhcp on timeouts when polling reprovisiondata in the nic attach path

---

cloudinit/config/cc_update_etc_hosts.py
tools/.github-cla-signers

```
cc_update_etc_hosts: Use the distribution-defined path for the hosts file
The distribution class has a property that specifies the location of
the system hosts file and this can be overridden in subclasses.
While the property is correctly used in distro.update_etc_hosts(), the
update_etc_hosts module does not use it and just assumes '/etc/hosts'
This fixes the module to use the distribution-specific property.
```
There are still places in the code where the path is assumed to be `/etc/hosts` but this
fixes the update_etc_hosts module.
I've been using this patch as part of my work to bring in support for the illumos family of operating systems, where the canonical hosts file is `/etc/inet/hosts`
```
2021-08-17 14:07:05,773 - util.py[DEBUG]: Cloud-init v. 21.2 running 'single' at Tue, …
```

cc_update_etc_hosts: Use the distribution-defined path for the hosts file

---

cloudinit/sources/DataSourceAzure.py

```
Set Azure to only update metadata on BOOT_NEW_INSTANCE
In #834, we refactored the handling of events for fetching new metadata.
Previously, in Azure's __init__, the BOOT event was added to the
update_events, so it was assumed that Azure required the standard BOOT
behavior, which is to apply metadata twice every boot: once during
local-init, then again during standard init phase.
https://github.com/canonical/cloud-init/blob/21.2/cloudinit/sources/DataSourceAzure.py#L356
However, this line was effectively meaningless. After the metadata was
fetched in local-init, it was then pickled out to disk. Because
"update_events" was a class variable, the EventType.BOOT was not
persisted into the pickle. When the pickle was then unpickled in the
init phase, metadata did not get re-fetched because …
```

Set Azure to only update metadata on BOOT_NEW_INSTANCE (SC-386)

---

cloudinit/ssh_util.py
tests/unittests/test_sshutil.py

As specified in #LP 1845552,
In cloudinit/ssh_util.py, in parse_ssh_config_lines(), we attempt to
parse each line of sshd_config. This function expects each line to
be one of the following forms:
key value
key=value
However, options like DenyGroups and DenyUsers are specified to
**optionally** accepts values in sshd_config.
Cloud-init should comply to this and skip the option if a value
is not provided.
Signed-off-by: Emanuele Giuseppe Esposito <eesposit@redhat.com>
LP: #1845552
RHBZ:#1862933
Add the following line(s) to sshd_config
```
DenyUsers
DenyGroups
```

ssh_utils.py: ignore when sshd_config options are not key/value pairs

---

templates/hosts.debian.tmpl
tools/.github-cla-signers

```
Update IPv6 entries in /etc/hosts
Add IPv6 localhost (::1) entry. See:
https://salsa.debian.org/installer-team/netcfg/-/blob/1767c9264e04652b9150ffc7b25568e4ea6b2bdd/netcfg.h#L42
https://salsa.debian.org/md/netbase/-/blob/9de8afcad482418cc4956dc09bbf6a2e8624d574/debian/netbase.postinst#L8
Also remove ip6-localnet, ip6-mcastprefix, and ip6-allhosts. See:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=499800
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=688090
LP: #1943798
```
`pytest-3`
cc @dseomn

Update IPv6 entries in /etc/hosts

---

cloudinit/config/cc_ssh.py
doc/rtd/topics/bugs.rst

Remove a duplicate "a" in the docs, and change the bug reporting documentation to tell users to run the commands with sudo.
LP: #1940236

docs: fix typo and include sudo for report bugs commands

---

cloudinit/net/__init__.py
cloudinit/net/dhcp.py
cloudinit/net/tests/test_dhcp.py
cloudinit/net/tests/test_init.py
cloudinit/sources/DataSourceOracle.py
cloudinit/sources/helpers/vultr.py
cloudinit/sources/tests/test_oracle.py

```
Add connectivity_url to Oracle's EphemeralDHCPv4
On bionic, when trying to bring up the EphemeralDHCPv4, it's possible
that we already have a route defined, which will result in an error when
trying to add the DHCP route. Use the connectivity_url to check if we
can reach the metadata service, and if so, skip the EphemeralDHCPv4.
The has_url_connectivity function has also been modified to take either
a url as string or the dict of kwargs to send to readurl.
LP: #1939603
```
According to Oracle, `the v2 endpoint will always be available, at least for the foreseeable future, anyway`, so we don't need to worry about the v1 fallback.
Launch a bionic instance on Oracle. For me this looked like:
```
oci compute instance launch --availability-domain="qIZq:PHX-AD-3" --shape="VM.Standard1.1" …
```

Add connectivity_url to Oracle's EphemeralDHCPv4 (SC-395)

---

cloudinit/sources/DataSourceAzure.py
tests/integration_tests/modules/test_user_events.py

```
Set Azure to apply networking config every BOOT
In #1006, we set Azure to apply networking config every
BOOT_NEW_INSTANCE because the BOOT_LEGACY option was causing problems
applying networking the second time per boot. However,
BOOT_NEW_INSTANCE is also wrong as Azure needs to apply networking
once per boot, during init-local phase.
```
Run integration test

Set Azure to apply networking config every BOOT

---

.pylintrc
cloudinit/reporting/handlers.py
cloudinit/safeyaml.py
cloudinit/sources/DataSourceNoCloud.py
cloudinit/templater.py
cloudinit/tests/test_subp.py
tests/unittests/test_datasource/test_azure.py
tests/unittests/test_datasource/test_configdrive.py
tests/unittests/test_datasource/test_openstack.py
tests/unittests/test_datasource/test_scaleway.py
tests/unittests/test_handler/test_handler_apt_source_v3.py
tests/unittests/test_handler/test_handler_debug.py
tests/unittests/test_util.py
tox.ini

```
tox: bump the pinned flake8 and pylint version
* pylint: fix W1406 (redundant-u-string-prefix)
The u prefix for strings is no longer necessary in Python >=3.0.
* pylint: disable W1514 (unspecified-encoding)
From https://www.python.org/dev/peps/pep-0597/ (Python 3.10):
The new warning stems form https://www.python.org/dev/peps/pep-0597,
which says:
Developers using macOS or Linux may forget that the default encoding
is not always UTF-8. [...] Even Python experts may assume that the
default encoding is UTF-8. This creates bugs that only happen on Windows.
The warning could be fixed by always specifying encoding='utf-8',
however we should be careful to not break environments which are not
utf-8 (or explicitly state that only utf-8 is supported). Let's silence
the warning for now.
* …
```

tox: bump the pinned flake8 and pylint version (SC-422)

---

cloudinit/config/cc_disk_setup.py

```
docs: update cc_disk_setup for fs to raw disk
```
See https://bugs.launchpad.net/cloud-init/+bug/1943156

docs: update cc_disk_setup for fs to raw disk (SC-413)

---

doc/examples/cloud-config-user-groups.txt
doc/rtd/topics/datasources/vmware.rst

```
Remove invalid ssh_import_id from examples
```
`None` could be taken to mean, "this is valid but do nothing", but actually specifying None will give an error in the logs.
@akutz requested I remove the VMWare references as well.
We use `<ssh pub key 1>` in the examples, so I figure using a non-real `<Launchpad/Github id>` is fine.

Remove invalid ssh_import_id from examples

---

tests/integration_tests/modules/test_version_change.py

```
testing: skip test_cache_purged_on_version_change on Azure
```
See comment in change

testing: skip test_cache_purged_on_version_change on Azure (SC-445)

---

cloudinit/config/cc_disable_ec2_metadata.py
cloudinit/config/cc_emit_upstart.py
cloudinit/config/cc_final_message.py
cloudinit/config/cc_growpart.py
cloudinit/config/cc_migrator.py
cloudinit/config/cc_refresh_rmc_and_interface.py
cloudinit/config/cc_scripts_per_boot.py
cloudinit/config/cc_set_hostname.py
cloudinit/config/cc_update_etc_hosts.py
cloudinit/config/cc_update_hostname.py
cloudinit/config/cc_yum_add_repo.py

```
Some modules' frequency are documented as `always` while others as
`per always`. The difference in wording can be confusing. This change
updates all such modules to use `always`.
Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>
```

Make wording for module frequency consistent

---

requirements.txt
test-requirements.txt
tox.ini

```
Pin jsonschema to 3.2.0
On unit tests, tox is attempting to install 4.0, which fails two of
the unit tests, and fails python 3.5 as it is not compatible.
```

Pin jsonschema to 3.2.0 (SC-466)

---

tests/unittests/test_datasource/test_ovf.py

We likely have a test somewhere not cleaning up its mocks causing tests to run after it to not have to mock things that should be mocked. When run in isolation, these tests will fail. We need to find this test and fix it, but for now, fix the lack of mocks.

Add necessary mocks to test_ovf unit tests

---

cloudinit/config/cc_install_hotplug.py
cloudinit/sources/__init__.py
packages/redhat/cloud-init.spec.in
tests/unittests/test_datasource/test_ovf.py
tests/unittests/test_handler/test_handler_install_hotplug.py

```
Allow libexec for hotplug
When we added the install hotplug module, we forgot to update the
redhet/cloud-init.spec.in file and allow for execution on /usr/libexec.
This PR adds that functionality
```
Verified rpm package builds, `/etc/udev/rules.d/10-cloud-init-hook-hotplug.rules` gets written and references `/usr/libexec/cloud-init/hoook-hotplug` and `/usr/libexec/cloud-init/hook-hotplug` exists. Also tested that integration test still passes on ubuntu.

Allow libexec for hotplug (SC-532)

---

cloudinit/config/cc_apt_configure.py
doc/examples/cloud-config-apt.txt

```
Fix schema and fix unhandled apt_configure case.
Don't throw an exception when mirror arch is unspecified.
```
Use the following [config](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#additional-apt-configuration-and-repositories).

Fix unhandled apt_configure case (SC-526)

---

tests/integration_tests/datasources/test_lxd_discovery.py
tests/integration_tests/datasources/test_network_dependency.py

```
testing: Remove calls to 'install_new_cloud_init'
In our integration tests, a few tests were modifying the environment and
then calling 'install_new_cloud_init'. This is problematic because it
updates the environment for all future tests.
Existing instances of 'install_new_cloud_init' aren't problematic because
they aren't modifying the underlying environment.
```
Since this involves one test affecting tests run after it, the whole suite of tests was run for lxd containers. I also verified the updated GCE test on GCE.

testing: Remove calls to 'install_new_cloud_init'

---

cloudinit/sources/DataSourceAzure.py

Azure: fallback nic needs to be reevaluated during reprovisioning
```
During reprovisioning, VM network will change. fallback nic
should be cleared after use so that it can be re-evaluated after
reprovisioning
```

clear fallback interface before reprovisioning

---

cloudinit/distros/alpine.py

```
alpine.py: add options to the apk upgrade command
Whenever "apk upgrade" is triggered also use the "--available" and
"--update-cache" options to ensure that an up-to-date packages list
is used.
```

alpine.py: add options to the apk upgrade command

---

cloudinit/distros/debian.py
tests/unittests/test_distros/test_debian.py
tests/unittests/test_handler/test_handler_landscape.py

```
Wait for apt lock
Currently any attempt to run an apt command while another process holds
an apt lock will fail. We should instead wait to acquire the apt lock.
LP: #1944611
```
See https://bugs.launchpad.net/cloud-init/+bug/1944611 . I have also seen this intermittently while testing.
Beyond the unit tests, start an instance with the following cloud-config
```
#cloud-config
bootcmd:
- python3 -c "import fcntl; from time import sleep; x = open('/var/lib/dpkg/lock', 'w'); fcntl.lockf(x, fcntl.LOCK_EX | fcntl.LOCK_NB); sleep(50000)" &
drivers:
nvidia:
license-accepted: true
```
Old behavior is to fail immediately. With this PR it will wait 30 seconds and then fail. Decrease the sleep an appropriate amount of time if you'd like to see it wait and then proceed when the lock is cleared.

Wait for apt lock

---

cloudinit/net/networkd.py
cloudinit/net/tests/test_networkd.py

```
Fix for set-name bug in networkd renderer
This patch address an issue where the use of the "set-name"
directive caused the networkd renderer to fail.
LP: #1949407
```
Please note this was root caused by @pradipd at https://github.com/pradipd/cloud-init/commit/756742a05dacbd812da5c10c0f3ae592156679ca, and this PR is merely an optimization on their existing fix as well as the addition of a unit test to validate the fix.
Fixes Kubernetes image builder bug described in this comment - https://github.com/kubernetes-sigs/image-builder/issues/712#issuecomment-954140935
CC @MaxRink @zawachte-msft @kkeshavamurthy @randomvariable @codenrhoden 
The following command and output demonstrates the patch works as intended:
```bash
$ make clean_pyc && PYTHONPATH="$(pwd)" python3 -m pytest -v …
```

Fix for set-name bug in networkd renderer

---

tests/integration_tests/conftest.py

Cloud-init allows automatic log collection from integration tests, however the UX isn't very friendly if tests are being ran repeatedly. Selecting "which directory" is not fun. Consider:
```
holmanb@arc:~ > ls /tmp/cloud_init_test_logs -l
total 36
drwxrwxr-x 3 holmanb holmanb 4096 Nov 10 10:52 211110105102
drwxrwxr-x 3 holmanb holmanb 4096 Nov 10 11:32 211110113108
drwxrwxr-x 3 holmanb holmanb 4096 Nov 10 11:38 211110113715
drwxrwxr-x 3 holmanb holmanb 4096 Nov 10 14:37 211110143557
drwxrwxr-x 3 holmanb holmanb 4096 Nov 10 14:39 211110143852
drwxrwxr-x 3 holmanb holmanb 4096 Nov 10 14:41 211110144125
drwxrwxr-x 3 holmanb holmanb 4096 Nov 10 14:47 211110144700
drwxrwxr-x 3 holmanb holmanb 4096 Nov 10 14:48 211110144823
drwxrwxr-x 3 holmanb holmanb 4096 Nov 10 15:22 211110152216
```
How to …

Add convenience symlink to integration test output

---

tests/integration_tests/datasources/test_lxd_discovery.py

```
On Bionic and Xenial, pycloudlib sets user.vendor-data config in lxd
to ensure that lxd-agent is setup on those images.
Adapt the lxd_discovery integration test to assert the appropriate
user.vendor-data config key exists if we are on xenial or bionic.
Also add assertions that /var/lib/cloud/nocloud-net/meta-data still
exists in the images because we want NoCloud to be a viable fallback
datasource if LXD config security.lxddev = false or LXD datasource
discovery encountered an unexpected error.
```
[pycloudlib has special vendor-data treatment on Xenial and Bionic](https://github.com/canonical/pycloudlib/blob/main/pycloudlib/lxd/defaults.py#L13-L27)
```bash
.tox/integration-tests/bin/pytest  tests/integration_tests/datasources/test_lxd_discovery.py
CLOUD_INIT_SOURCE=lxd_vm …
```

tests: specialize lxd_discovery test for lxd_vm vendordata

---

tests/integration_tests/modules/test_apt.py
tests/integration_tests/modules/test_combined.py
tests/integration_tests/modules/test_keys_to_console.py
tests/integration_tests/modules/test_puppet.py
tests/integration_tests/modules/test_ssh_auth_key_fingerprints.py
tests/integration_tests/util.py

```
Some miscellaneous integration test fixes
- Added to list of expected warnings on Oracle when opc user has
no ssh key
- Added retries to tests that read from syslog as that can sometimes
take time to reflect in the log
- Updated test_apt.py to remove proxy info into its own test as that
can cause failures in updating, which will immediately traceback
out of the module and prevent us from running further class tests
- Updated test_apt.py to use a more updated ppa in the test_keyserver
- Added basic rsyslog test to test_combined.py
- Added basic puppet test as test_puppet.py
```

Some miscellaneous integration test fixes (SC-606)

---

tests/integration_tests/conftest.py

```
integration_tests: Ensure log directory exists before symlinking to it
Also simplify a path and fix a spelling error while in the file
```

integration_tests: Ensure log directory exists before symlinking to it (SC-611)

---

cloudinit/sources/DataSourceLXD.py
cloudinit/sources/tests/test_lxd.py

```
lxd: add preference for LXD cloud-init.* config keys over user keys
LXD now adds cloud-init scoped configuration keys network-config,
user-data and vendor-data. The existing user.user-data,
user.vendor-data, user.network-config and meta-data will be
deprecated in newer LXD.
cloud-init will prefer LXD config keys cloud-init.* keys above
user.* keys even if both are present.
Expectation is that the configuration user.network-config,
user.meta-data, user.user-data and user.vendor-data* keys should
not be present at the same time as the comparable cloud-init.* keys.
Also drop awareness of user.network_mode as this was deprecated
from LXD 2.1.
```

lxd: add preference for LXD cloud-init.* config keys over user keys

---

cloudinit/sources/DataSourceVultr.py

Fix Vultr timeout and wait values
```
Some Vultr Datacenters can experience latency in the connection due to the location of one of the dependant api's. The timouts need to be adjusted so this isn't a failure in the future.
```
Deploy in Singapore, run curl command to API with various wait/timeouts
- [ X ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)

Fix Vultr timeout and wait values

---

cloudinit/analyze/tests/test_boot.py
cloudinit/config/tests/test_set_passwords.py
cloudinit/tests/test_util.py
cloudinit/util.py
conftest.py
tests/unittests/test_datasource/test_azure.py
tests/unittests/test_datasource/test_azure_helper.py
tests/unittests/test_datasource/test_configdrive.py
tests/unittests/test_distros/test_netconfig.py
tests/unittests/test_distros/test_user_data_normalize.py
tests/unittests/test_handler/test_handler_ntp.py
tests/unittests/test_net.py

```
testing: monkeypatch system_info call in unit tests
system_info can make calls that read or write from the filesystem, which
should require special mocking. It is also decorated with 'lru_cache',
which means test authors often don't realize they need to be mocking.
Also, we don't actually want the results from the user's local
machine, so monkeypatching it across all tests should be reasonable.
Additionally, moved some of 'system_info` into a helper function to
reduce the surface area of the monkeypatch, added tests for the new
function (and fixed a bug as a result), and removed related mocks that
should be no longer needed.
```

testing: monkeypatch system_info call in unit tests (SC-533)

---

CONTRIBUTING.rst
doc/rtd/index.rst
doc/rtd/topics/contributing.rst
doc/rtd/topics/hacking.rst

```
docs: Rename HACKING.rst to CONTRIBUTING.rst
This is more consistent with other github repositories, and will prompt
a first-time contributor to read the contributing guidelines before
submitting the pull request.
Additionally, added a summary section to the top, updated some outdated
language, and removed some outdated typing guidance.
```
The net refactor stuff seems a bit out of place here, but I didn't move it because there's not an immediately better place to put it, and I think it can be easily ignored for somebody not interested.

docs: Rename HACKING.rst to CONTRIBUTING.rst (SC-501)

---

.github/PULL_REQUEST_TEMPLATE.md

"HACKING" was renamed to "CONTRIBUTING", update the PR template
URL accordingly.

github: update PR template's contributing URL

---

cloudinit/sources/DataSourceAzure.py
doc/examples/cloud-config-datasources.txt
tests/unittests/test_datasource/test_azure.py

Some references were missed in the removal of the agent command
in PR #799.  This simply removes the remaining references.

sources/azure: remove unused remnants related to agent command

---

cloudinit/config/cc_ssh_authkey_fingerprints.py
tests/integration_tests/modules/test_keys_to_console.py

```
cc_ssh_authkey_fingerprints.py: prevent duplicate messages on console
When cloud-init is configured to show SSH user key fingerprints during
boot two of the same message appears for each user. This appears to be as
the util.multi_log call defaults to send to both console directly and to
stderr (which also goes to console).
This change sends them only to console directly.
```

cc_ssh_authkey_fingerprints.py: prevent duplicate messages on console

---

cloudinit/sources/helpers/vultr.py

Fix missing metadata routes for Vultr
```
Vultr uses 169.254.169.254 for the metadata server. Some distros are having trouble with this on IPv6 only servers because the route is not being assigned to the link-local interface by default as it is in other distros. This change sets that route before attempting to fetch the metadata avoiding the current issue.
```
Deploy Arch as IPv6 Only on Vultr.

Fix missing metadata routes for Vultr

---

cloudinit/sources/DataSourceGCE.py
tests/integration_tests/modules/test_combined.py
tests/unittests/test_datasource/test_common.py
tests/unittests/test_datasource/test_gce.py

```
Move GCE metadata fetch to init-local
GCE currently fetches metadata after network has come up. There's no
reason we can't fetch at init-local time, so update GCE to fetch at
init-local time to be more consistent with other datasources.
```
Upload dpkg to GCE instance and install
`cloud-init clean --logs --reboot`
Verify metadata is fetched at init-local time
Verify metadata is NOT fetched at init time
cloud-init.log can be seen at:
https://paste.ubuntu.com/p/tY3RkS9rKY/
Additionally, I ran integration tests on GCE

Move GCE metadata fetch to init-local (SC-502)

---

tests/integration_tests/modules/test_combined.py

```
testing: Remove date from final_message test
```
We've seen a number of failures due to timezones that it's silly to keep this check around, especially for this module.

testing: Remove date from final_message test (SC-638)

---

cloudinit/cmd/query.py
cloudinit/cmd/tests/test_query.py
cloudinit/handlers/jinja_template.py
cloudinit/sources/DataSourceLXD.py
cloudinit/sources/tests/test_lxd.py
doc/rtd/topics/instancedata.rst
tests/integration_tests/datasources/test_lxd_discovery.py
tests/integration_tests/modules/test_jinja_templating.py
tests/unittests/test_builtin_handlers.py

```
Allow #cloud-config and cloud-init query to use underscore-delimited
"jinja-safe" key aliases for any instance-data.json keys
containing jinja operator characters.
This provides a means to use Jinja's dot-notation instead of square brackets
and quoting to reference "unsafe" obtain attribute names.
Support for these aliased keys is available to both #cloud-config user-data and
`cloud-init query`.
For example #cloud-config alias access can look like:
{{ ds.config.user_network_config }}
- instead of -
- 
{{ ds.config["user.network-config"] }}
```
```bash
tox -e integration-tests tests/integration_tests/datasources/test_lxd_discovery.py
```

jinja: provide and document jinja-safe key aliases in instance-data (SC-622)

---

cloudinit/distros/__init__.py
cloudinit/net/activators.py
tests/unittests/test_net_activators.py

```
Fix exception when no activator found
Given that there are additional network management tools that we haven't
yet supported with activators, we should log a warning and continue
without network activation here, especially since this was a no-op for
years.
LP: #1948681
```

Fix exception when no activator found (SC-540)

---

cloudinit/net/__init__.py
tests/unittests/net/test_init.py

```
If we set a dhcp server side like this:
$ cat /var/tmp/cloud-init/cloud-init-dhcp-f0rie5tm/dhcp.leases
lease {
...
option classless-static-routes 31.169.254.169.254 0.0.0.0,31.169.254.169.254
10.112.143.127,22.10.112.140 0.0.0.0,0 10.112.140.1;
...
}
cloud-init fails to configure the routes via 'ip route add' because to there are
two different routes for 169.254.169.254:
$ ip -4 route add 192.168.1.1/32 via 0.0.0.0 dev eth0
$ ip -4 route add 192.168.1.1/32 via 10.112.140.248 dev eth0
But NetworkManager can handle such scenario successfully as it uses "ip route append".
So change cloud-init to also use "ip route append" to fix the issue:
$ ip -4 route append 192.168.1.1/32 via 0.0.0.0 dev eth0
$ ip -4 route append 192.168.1.1/32 via 10.112.140.248 dev eth0
Signed-off-by: Emanuele …
```

 cloudinit/net: handle two different routes for the same ip

---

cloudinit/cmd/clean.py
cloudinit/cmd/cloud_id.py
cloudinit/config/cc_apk_configure.py
cloudinit/config/cc_apt_configure.py
cloudinit/config/cc_bootcmd.py
cloudinit/config/cc_chef.py
cloudinit/config/cc_install_hotplug.py
cloudinit/config/cc_locale.py
cloudinit/config/cc_ntp.py
cloudinit/config/cc_resizefs.py
cloudinit/config/cc_runcmd.py
cloudinit/config/cc_snap.py
cloudinit/config/cc_ubuntu_advantage.py
cloudinit/config/cc_ubuntu_drivers.py
cloudinit/config/cc_write_files.py
cloudinit/config/cc_write_files_deferred.py
cloudinit/config/cc_zypper_add_repo.py
cloudinit/config/schema.py
cloudinit/importer.py
cloudinit/util.py
doc/rtd/conf.py
tests/unittests/cmd/test_clean.py
tests/unittests/cmd/test_cloud_id.py
tests/unittests/config/test_schema.py
tests/unittests/test_cli.py

```
Improve schema validation.
This adds strict validation of config module definitions at testing
time, with plumbing included for future runtime validation. This
eliminates a class of bugs resulting from schemas that have definitions
that are incorrect, but get interpreted by jsonschema as
"additionalProperties" that are therefore ignored.
- Add strict meta-schema for jsonschema unit test validation
- Separate schema from module metadata structure
- Improve type annotations for various functions and data types
Cleanup:
- Remove unused jsonschema "required" elements 
- Eliminate manual memoization in schema.py:get_schema(),
reference module.__doc__ directly
```
Many of the files were only touched for function name/arg/schema/meta updates, however schema.py, test_schema.py, test_cli.py …

Add Strict Metaschema Validation

---

doc/rtd/topics/network-config-format-v1.rst
doc/rtd/topics/network-config-format-v2.rst

```
docs: Make MACs lowercase in network config
LP: #1876941
```

docs: Make MACs lowercase in network config (SC-541)

---

tests/unittests/sources/test_azure.py

It looks like this is patched in other tests, this must have been missed.
```
mock sleep() in azure test
```
It looks like this is patched in other tests, this must have been missed.
```
arc~/cloud-init(:cd40789a|…) pytest --durations=1 tests/unittests/sources/test_azure.py
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.9.7, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /home/holmanb/cloud-init, configfile: tox.ini
plugins: cov-3.0.0, xdist-2.2.0, forked-1.3.0
collected 160 items …
```

mock sleep() in azure test

---

tests/unittests/test_util.py

```
Remove non-deterministic test parameter
Non-deterministic test parameters have multiple downsides:
- potentially non-deterministic tests results
- breaks parallel test execution via xdist.
```
There are other things in our unittests that cause intermittent failures during parallel test execution, but this one will cause failures every time. The random input here is frankly unnecessary. With this change I can (usually) run `pytest tests/unittests -n2` locally in ~25 seconds, rather than the normal >40s to complete.

Remove non deterministic test param

---

tests/unittests/config/test_cc_chef.py
tests/unittests/config/test_cc_resolv_conf.py
tests/unittests/config/test_cc_update_etc_hosts.py
tests/unittests/config/test_schema.py
tests/unittests/helpers.py
tests/unittests/sources/vmware/test_vmware_config_file.py
tests/unittests/test_ds_identify.py
tests/unittests/test_helpers.py
tests/unittests/test_render_cloudcfg.py
tests/unittests/test_subp.py
tox.ini

```
Add a test helper to get top level directory
Many tests need to get the location of files & dirs within the cloud-init
project directory.
Tests implement this in various different ways, and often those ways
depend on the current working directory of the pytest invocation.
Create helper functions (and tests) that gets the path of the top
directory or any sub directory under the top directory. This function
does not depend on the environment.
```
- This is not a very high value refactor, but not being able to run pytest wherever I please has been bugging me.
- It should also makes a common task less slightly less error prone and tedious.
- I'm sure that I missed tests.
- The tests I converted were unittests that fail when running pytest in a subdirectory.

factor out function for getting top level directory of cloudinit

---

.travis.yml
tests/unittests/test_fail.py

```
If building the *.deb fails, exit
Currently integration tests will run and fail with a non-obvious
message. This makes it so the last thing in the logs is whatever
caused the build to fail.
```
Consider the new output for a failed build:
https://app.travis-ci.com/github/canonical/cloud-init/jobs/551267972

travis - don't run integration tests if no deb (SC-699)

---

cloudinit/util.py

Improve error message in cloud-init.log for images without ntfs support.

Improve error message in cloud-init.log

---

cloudinit/util.py
tests/unittests/test_util.py

When the metadata is an ISO image and is exposed through a disk,
the device is called `/dev/sd?a` internally. For instance `/dev/sd1a`.
It can then be mounted with `mount_cd9660 /dev/sd1a /mnt`.
For comparison, metadata in the FAT32 format are exposed as `/dev/sd?i` because this time there is a partition table.
With this change, cloud-init ttries to mount `/dev/sd?a` in addition to `/dev/sd?i`.
Closes: https://github.com/ContainerCraft/kmi/issues/12

find_devs/openbsd: accept ISO on disk

---

cloudinit/util.py
tests/unittests/test_util.py

`sysctl -n hw.disknames` returns a trailing `\n`. We need to clean
this up. In addition, the criteria matching system is a source of
problem because:
- we don't have a way to look up the label of the partition
- we've got situation where an ISO image can be exposed through a virtio
block device.
So we just totally ignore the value of `criteria`. We end-up with a
slightly longer loop of mount-retry. But this way we're sure we don't
miss a configuration disk.
Tested on Kubvirt with the help of Brady Pratt @jbpratt.

find_devs_with_openbsd: ensure we return the last entry

---

packages/bddeb

```
Fix bddeb script for impish
```
dh_systemd is now included in the default helper, no need to specify it anymore for impish

Fix bddeb script for impish (SC-688)

---

cloudinit/config/schema.py
tests/unittests/config/test_schema.py

```
Schema processing changes
* Use proper logging
* Add parsing for patternProperties
* Add label to annotate patternProperties
* Log warning if schema parsing fails during metaschema processing
* Some schema test fixes
```

Schema processing changes (SC-676)

---

tests/unittests/cmd/test_query.py

test_handle_args_error_on_invalid_vaname_paths() would fail when run
as root due to invocation of load_userdata() on the default user/vendor
data locations under the instance link.
- Mock load_userdata() for this test case to avoid loads.
- Update _setup_paths() to configure cloud_dir in temporary location.
- Add new test case to verify that the default locations are loaded
when unspecified.

tests/cmd/query: fix test run as root and add coverage for defaults

---

cloudinit/distros/debian.py

https://github.com/canonical/cloud-init/pull/1034#issuecomment-986971376
https://github.com/canonical/cloud-init/pull/1034#issuecomment-987012207
I also included a link to the first comment in a code comment.

Include dpkg frontend lock in APT_LOCK_FILES (SC-650)

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/sources/test_azure.py

If get_imds_data_with_api_fallback() falls back to the minimum required
API version, it is effectively pinned to the old API version forever.
Remove the failed_desired_api_version property to prevent persistence of
the flag between calls and/or reboots.
The continued presence of this flag in obj.pkl should be harmless.

sources/azure: do not persist failed_desired_api_version flag

---

.travis.yml

```
Add 3.10 support to test matrix
Multiple supported distros (arch/fedora) have changed their default
python version to 3.10. We should include it in the test matrix.
```
Context: https://travis-ci.community/t/add-python-3-10/12220/12

3.10 Test Coverage (SC-719)

---

cloudinit/config/schema.py

```
pylint: silence errors on compat code for old jsonschema
Let's silence the errors which are emitted by pylint on
a code path that exists only for backwards compatibility
with older versions of jsonschema. Pylint can't be aware
of the library version check we're doing.
```
Spotted by Jenkins:
```
************* Module cloudinit.config.schema
cloudinit/config/schema.py:121: [E1101(no-member), get_jsonschema_validator] Class 'Validator' has no 'DEFAULT_TYPES' member
cloudinit/config/schema.py:126: [E1123(unexpected-keyword-arg), get_jsonschema_validator] Unexpected keyword argument 'default_types' in function call
```
Run `tox -e pylint` on a >= Focal system and verify that pylint emits no errors.

pylint: silence errors on compat code for old jsonschema

---

tests/unittests/test_ds_identify.py

```
On LXD containers /dev/lxd/sock will always exist.
Mock dscheck_LXD to return 1 (NOT_FOUND) to avoid leaking into
test environment and returning LXD as detected.
We have integration tests covering proper LXD datasource detection
so we don't need a Unit test validating the [ -S /dev/lxd/sock] that
is in ds-identify.
```
```bash
lxc launch ubuntu-daily:bionic dev-b
lxc config device add dev-b rohome disk source="/home/csmith/src/cloud-init" path="/root/cloud-init/"
lxc exec dev-b bash
tox -e py3 tests/unittests/test_ds_identify.py
```

tests: mock LXD datasource detection in ds-identify on LXD containers

---

.travis.yml
cloudinit/config/cc_apt_configure.py
cloudinit/distros/debian.py
conftest.py
doc/examples/cloud-config-apt.txt
doc/examples/cloud-config-chef.txt
doc/rtd/topics/debugging.rst
doc/rtd/topics/testing.rst
tests/integration_tests/bugs/test_gh626.py
tests/integration_tests/bugs/test_lp1898997.py
tests/integration_tests/conftest.py
tests/integration_tests/datasources/test_lxd_discovery.py
tests/integration_tests/modules/test_disk_setup.py
tests/integration_tests/modules/test_lxd_bridge.py
tests/integration_tests/modules/test_users_groups.py
tests/unittests/cmd/devel/test_hotplug_hook.py
tests/unittests/config/test_cc_install_hotplug.py
tests/unittests/distros/test_networking.py
tests/unittests/sources/test_lxd.py
tests/unittests/sources/test_oracle.py
tests/unittests/sources/test_vmware.py
tests/unittests/test_features.py
tests/unittests/test_net_activators.py
tests/unittests/test_stages.py
tests/unittests/test_util.py
tox.ini

```
Remove 3.5 and xenial support
Includes:
- Update tox.ini and .travis.yml accordingly
- Cleanup tox.ini with new tox syntax and cloud-init dependencies
- Update documentation accordingly
- Replace/remove xenial references where additional testing isn't required
- Remove xenial checks in integration tests
- Replace yield_fixture with fixture in pytest tests
Sections of code commented with lines like "Remove when Xenial is no
longer supported" still exist as they'll require additional testing.
```
I created a separate ticket for dealing with code that would need additional testing.

Remove 3.5 and xenial support (SC-711)

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/sources/test_azure.py

Format tweak to match naming conventions for classes & enums.
No functional changes.

sources/azure: rename metadata_type -> MetadataType

---

cloudinit/config/cc_keyboard.py
cloudinit/distros/__init__.py
cloudinit/distros/debian.py
config/cloud.cfg.tmpl
doc/rtd/topics/modules.rst
tests/integration_tests/modules/test_keyboard.py
tests/unittests/config/test_schema.py
tools/.github-cla-signers

```
Add new config module to set keyboard layout
Adds a new module to allow setting keyboard layout,
for use-cases in which cloud-init is used to configure
OS images meant for physical computers instead
of the cloud.
This initial release only implements support
for Linux distributions that allow layout to be
set through systemd's localectl.
LP: #1951593
```
Allow setting keyboard layout like this:
```
#cloud-config
keyboard:
layout: us
```
Or if you need more specific options:
```
#cloud-config
keyboard:
layout: de
model: pc105
variant: nodeadkeys
options: compose:rwin
```

Add new config module to set keyboard layout

---

cloudinit/sources/__init__.py

```
cloudinit/importer.py: print a meaningful message if import fails
Sometimes an import might fail for different reasons: the string
is wrongly typed, or the module has a dependency that is not
installed in python.
We should print that there is an import error, otherwise it might be
really difficult to understand what is the root cause of this
issue. Currently, cloud-init just ignores the error and continues.
This can have fatal consequences, especially when used to pick
the datasource to use.
For example, we can have a missing/misspelled datasource file:
$ ls cloudinit/sources/DataSourceInexistent.py
ls: cannot access 'cloudinit/sources/DataSourceInexistent.py': No such file or directory
$ python
>>> __import__("cloudinit.sources.DataSourceInexistent")
and in this case cloud-init …
```

cloudinit/importer.py: print a meaningful message if import fails

---

.gitignore

```
Add pyenv version file to .gitignore
This file is an artifact of the `pyenv local` command, which is helpful for
setting a project-specific python version for testing.
```

Add .python-version to gitignore

---

cloudinit/cmd/cloud_id.py
cloudinit/cmd/status.py
doc/man/cloud-id.1
tests/unittests/cmd/test_cloud_id.py
tests/unittests/cmd/test_status.py

*     cli: status avoid reporting disabled before generator runs
Once cloud-init's systemd generator runs it emits either:
/run/cloud-init/enabled  OR /run/cloud-init/disabled
If we have neither of those files, cloud-init status should
still report not-run.
*     cli: cloud-id report not-run or disabled state as cloud-id
Given that cloud-id could be run before cloud-init discovery has
run report when cloud-init is in a 'disabled' state or whether it
has 'not-run'.
Adopt new exit codes:
0: success
1: error
2: cloud-init is in disabled state
3: cloud-init generator has not run yet
```
cli: cloud-id report not-run or disabled state as cloud-id
This fix has two elements:
- cloud-init status will not correctly report 'not-run' prior to systemd
generator running. Only report "disabled" when …
```

cli: cloud-id report not-run or disabled state as cloud-id

---

cloudinit/templater.py
tests/unittests/test_render_cloudcfg.py
tools/render-cloudcfg

```
Reduce template rendering test runtime
```
Pytest consistently shows the parametrized template rendering tests as the most time-consuming in the unit test suite (0.5s per test). Profile analysis shows that nearly all of the time spent is in one-time setup tasks (importing modules). Currently each test invokes a subprocess to execute the test.
This change should be non-functional. It simply moves the rendering code into the `templater` module and uses function calls in place of spawning a new process per parametrized test (function calls share the setup cost of module import). A single test that calls the tool as a subprocess was added to maintain test coverage.
This saves ~7s on my machine (which is 13% of the total unittest runtime).

Test Optimization Proposal (SC-736)

---

cloudinit/sources/DataSourceOracle.py
tests/integration_tests/network/test_net_config_load.py
tests/unittests/sources/test_oracle.py

```
Ensure system_cfg read before ds net config on Oracle
In 2c52e6e88b19f5db8d55eb7280ee27703e05d75f, the order of
reading network config was changed for Oracle due to initramfs
needing to take lower precedence than the datasource. However,
this also bumped system_cfg to a lower precedence than ds, which
means that any network configuration specified in /etc/cloud will not
be applied. system_cfg should instead be moved above ds so network
configuration in /etc/cloud takes precedence.
LP: #1956788
```
https://github.com/canonical/cloud-init/commit/2c52e6e88b19f5db8d55eb7280ee27703e05d75f
Boot an Oracle instance using the Oracle datasource.
Create /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with contents `network: {config: disabled}`
rm /etc/netplan/50-cloud-init.yaml (or rename …

Ensure system_cfg read before ds net config on Oracle (SC-720)

---

doc/sources/ovf/example/ubuntu-server.ovf
tools/.github-cla-signers

Cloud-init includes the capability to take the network-config from a
separate key. This removes the need to merge the network config in
the user-data and make it more transparent in some cases.
Reference:
https://github.com/canonical/cloud-init/blob/42b938e8ff4c50833ff7b8f5acc1d9ab3f43ab18/cloudinit/sources/DataSourceOVF.py#L557
- Create a template using the OVF example
* Instantiate a VM from that template
- Set the property key network-config to
```
bmV0d29yazoKICB2ZXJzaW9uOiAyCiAgZXRoZXJuZXRzOgogICAgaW50ZXJmYWNlMDoKICAgICAgbWF0Y2g6CiAgICAgICAgbmFtZTogZW5zMTkyCiAgICAgIGFkZHJlc3NlczoKICAgICAgICAtIDE5Mi4xNjguMTAwLjEwMC8yNAogICAgICBnYXRld2F5NDogMTkyLjE2OC4xMDAuMQogICAgICBuYW1lc2VydmVyczoKICAgICAgICBzZWFyY2g6CiAgICAgICAgIC0gZm9vLmxvY2FsCiAgICAgICAgIC0gYmFyLmxvY2FsCiAgICAgICAgYWRkcmVzc2VzOgog …
```

Add DatasourceOVF network-config propery to Ubuntu OVF example

---

cloudinit/sources/DataSourceAzure.py
cloudinit/sources/helpers/azure.py
tests/unittests/sources/test_azure.py

- Update EphemeralDHCPv4WithReporting to subclass EphemeralDHCPv4 for
consistency (non-functional change).
- Replace all usage of EphemeralDHCPv4 with EphemeralDHCPv4WithReporting.
- Converging to one DHCP class exposed an issue with ExitStack patches
being mixed with decorators.  Specifically, it appeared that tests
that did not enable azure.EphemeralDHCPv4WithReporting mocks had it
applied anyways from previous tests.
Presumably ExitStack was overwriting the actual value with the
mock provided by the decorator?  For now, remove some mock patches
that trigger failures, but future work should move towards a
consistent approach to prevent undetected effects.

sources/azure: consolidate DHCP variants to EphemeralDHCPv4WithReporting

---

doc/sources/ovf/example/ubuntu-server.ovf

This enables the OVF enviroment transport via ISO variable as defined
in the Open Virtualization Format Specification Version: 2.1.1.
8.1 VirtualHardwareSection
11.1 Transport media
Reference:
https://www.dmtf.org/sites/default/files/standards/documents/DSP0243_2.1.1.pdf
* Create a template using the OVF example
* Instantiate a VM from that template
* Check if the content is available via ISO transport

Enable OVF environment transport via ISO in example

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/sources/test_azure.py

The if-statement set ovf_is_accessible to True if the OVF is read
from /dev/sr0, but not from other data sources.  It defaults to
True, but may get flipped to False while processing an invalid
source, and never get set back to True when reading from the data
directory.
Instead, default ovf_is_accessible to False, and only set it to
True once we've read an OVF successfully (and end the search).
This fixes an error when OVF is read from data_dir and IMDS
data is unavailable (failing with "No OVF or IMDS available").

sources/azure: set ovf_is_accessible when OVF is read successfully

---

tox.ini

tox: pass PYCLOUDLIB_* env vars into integration tests when present
Allow any PYCLOUDLIB_* environment variables in integration-tests and jenkins
environments to allow overriding default behavior.
This specifically helps jenkins which seeds PYCLOUDLIB_CONFIG env var for
secrets.
```bash
"No configuration file found! Copy pycloudlib.toml.template to "
"~/.config/pycloudlib.toml or /etc/pycloudlib.toml"
)
cat > /tmp/test.toml <<EOF
[lxd]
EOF
CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_OS_IMAGE=jammy CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily CLOUD_INIT_COLLECT_LOGS=ON_ERROR PYCLOUDLIB_CONFIG=/tmp/test.toml  tox -e  integration-tests tests/integration_tests/modules/test_cli.py
```

tox: pass PYCLOUDLIB_* env vars into integration tests when present

---

cloudinit/cmd/cloud_id.py
cloudinit/cmd/status.py
doc/man/cloud-id.1
tests/unittests/cmd/test_status.py

We don't want to break existing snapd. So, let's leave "not run" value untouched. Also note, if we decide to change cloud-init status exit codes, that also has the potential to break snapd too, so we'd need to float that by that team first and get buyin.
```
snapd currrently looks for 'not run' from cloud-init status[1].
Avoid changing this behavior and revert "not-run" value to
"not run".
This avoids having to get snapd to change implementation and
release updates as far back as Bionic to handle a hyphenated
not-run string.
[1]: https://github.com/snapcore/snapd/blob/master/sysconfig/\
cloudinit.go#L802
```

cmd: status and cloud-id avoid change in behavior for 'not run'

---

tests/integration_tests/clouds.py
tests/integration_tests/test_upgrade.py

```
integration: test against the Ubuntu daily images
Dailies are always available for stable releases and the devel release.
Moreover testing against dailies will warn us earlier about issues.
```
Spotted while working at the Jammy (= devel) Jenkins jobs.
Just start an integration testing run.

integration: test against the Ubuntu daily images (SC-743)

---

cloudinit/sources/DataSourceVultr.py
cloudinit/sources/helpers/vultr.py

Seek interfaces on Vultr opposed to using the first, fix region codes
```
We were seeing issues where if anything showed up before the expected first adapter, booting could fail. This switches to seeking for a working interface to handle edge cases.
Also fixes region code handling.
```

Seek interfaces, skip dummy, fix region codes

---

tests/unittests/config/test_schema.py

Avoid series-specific log formatting in tests by using
caplog.record_tuples.
Added benefit, we can easily check log-level WARNING too.
Fixes unit test failures from Focal Package builds at:
https://code.launchpad.net/~cloud-init-dev/+archive/ubuntu/daily/+build/23076508
```
Avoid series-specific log formatting in tests by using
caplog.record_tuples.
Added benefit, we can easily check log-level WARNING too.
Fixes unit test failures from Focal Package builds at:
https://code.launchpad.net/~cloud-init-dev/+archive/ubuntu/daily/\
+build/23076508
```
```bash
git checkout upstream/focal
get merge tests-focal-fix-log-whitespace
build-package
sbuild --resolve-alternatives --dist=focal --arch=amd64  --arch-all ../out/cloud-init_21.4-0ubuntu1~20.04.1.dsc
```

tests: focal caplog has whitespace indentation for multi-line logs

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/sources/test_azure.py

load_azure_ds_dir() always returns a tuple.  Instead of saving this
tuple as ret, expand it immediately as md, userdata_raw, cfg, files.
This allows for more fine-grained passing of data before getting
expanded later.
- Update _should_reprovision methods to use cfg instead of tuple.
- Update _should_reprovision methods to remove the ovf_md guard.
This should be a safe refactor as the OVF is not required, and the
config is initialized to an empty dict.  In practice, a mount failure
would have initalized ret anyways if the OVF was not found. If a
mount failure wasn't seen and ret was None, this guard could be
causing other failures by ignoring the PPS state that should be
available from IMDS metadata.

sources/azure: unpack ret tuple in crawl_metadata()

---

config/cloud.cfg.tmpl
templates/hosts.gentoo.tmpl
tests/unittests/test_render_cloudcfg.py
tools/render-cloudcfg

```
Add support for gentoo in cloud.cfg and templates.
This is an already existing patch in gentoo upstream https://gitweb.gentoo.org/repo/gentoo.git/tree/app-emulation/cloud-init/files/cloud-init-20.4-gentoo-support-upstream-templates.patch.
Cherry-picking the patch to the upstream cloud-init.
```

Add support for gentoo templates and cloud.cfg

---

cloudinit/sources/DataSourceAzure.py

Avoid requirement of getattr() and ensure _ephemeral_dhcp_ctx isn't
persisted in the cache.

sources/azure: always initialize _ephemeral_dhcp_ctx on unpickle

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/sources/test_azure.py

According to the documentation in the tests:
```
We expect 3 calls to report_failure_to_fabric,
because we try 3 different methods of calling report failure.
The different methods are attempted in the following order:
1. Using cached ephemeral dhcp context to report failure to Azure
2. Using new ephemeral dhcp to report failure to Azure
3. Using fallback lease to report failure to Azure
```
Case 1 and 2 make sense.  If networking is established, use it.
Should failure occur using current network configuration, retry
with fresh DHCP.
Case 3 suggests that we can fall back to a lease file and retry.
Given that:
1. The wireserver address has never changed to date.
2. The wireserver address should be in the DHCP lease.
3. Parsing the lease file does not improve connectivity over the
prior …

sources/azure: drop unused case in _report_failure()

---

cloudinit/netinfo.py
tests/data/netinfo/sample-ipaddrshow-json
tests/data/netinfo/sample-ipaddrshow-json-down
tests/data/netinfo/sample-ipaddrshow-output
tests/unittests/test_netinfo.py

```
Add json parsing of ip addr show
When obtaining information from "ip addr", default to using
"ip --json addr" rather than using regex to parse "ip addr show"
as json is machine readable as less prone to error.
Deprecate but leave fallback to use "ip addr" for older iproute2
tooling which does not support --json param. 
Fix regex parsing of "ip addr" to support peer addresses and
metrics.
```
https://github.com/canonical/cloud-init/pull/1183

Add json parsing of ip addr show (SC-723)

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/sources/test_azure.py

Consolidate _should_reprovision_after_nic_attach() with
_should_reprovision() into the following:
- _write_reprovision_marker() to write provisioning marker for
reboot-during-provisioning case.
- PPSType enum and _determine_pps_type() for determining which to
provisioning mode, if any, we're running under.
PPSType.UNKNOWN is when the reprovisioning marker is found and we
do not have the context to know what the original mode was. In this
scenario, we must resort to polling for reprovision data.
Tests:
- Introduce a simple data source fixture to for fine-grain
control of mocking with pytest without unittest.
- Migrate relevant _should_reprovision() tests into a combination of
TestDeterminePPSTypeScenarios cases.

sources/azure: refactor _should_reprovision[_after_nic_attach]() logic

---

cloudinit/sources/helpers/vultr.py

Fix lo being used for DHCP, try next on cmd fail
```
Arch didn't like the last fix and lo found its way into this list. Checking for this and skipping interfaces that generate subp failures.
```
Deployed Arch on Vultr

Fix lo being used for DHCP, try next on cmd fail

---

templates/sources.list.ubuntu.tmpl
tools/.github-cla-signers

The partner archive is now obsolete.  LP: #1959343.
```
```

Do not support setting up archive.canonical.com as a source

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/sources/test_azure.py

Refactor _report_ready_if_needed() to work for both Savable PPS
and Runnable PPS:
- rename _report_ready_if_needed() to _report_ready_for_pps()
- return interface name from lease to support _poll_imds() behavior
without changing it.
- fixes an issue where reporting ready return value was silently
ignored for Savable PPS.
- add explicit handling for failure to obtain DHCP lease to
result in sources.InvalidMetaDataException.
Refactor _poll_imds():
- use _report_ready_for_pps() for reporting ready, removing this logic
to simplify loop logic.
- move netlink and vnetswitch out of while loop to simplify loop logic,
leaving only reprovision polling in loop.
- add explicit handling for failure to obtain DHCP lease and
retry in the next iteration.
Signed-off-by: Chris Patterson …

sources/azure: refactor _report_ready_if_needed and _poll_imds

---

CONTRIBUTING.rst
tox.ini

```
fix parallel tox execution
```
Changes:
- tox -p fails due to a shared directory clobbering files - use unique env dirs to avoid this (this does cause a longer initial serial run due to deps getting installed multiple times)
- remove unneeded dependencies for black, flake8, and isort environments (saves some CI cycles by avoiding installing unused deps - since travis doesn't share a cache this should be a net gain)
- add a new environment (for convenience) just for "checking formatting" - this moves current "format" env to "do_format" and adds "check_format". I'm happy to adjust names if others would rather "format" doesn't change or think there is some better naming scheme.

RFC - tox changes (SC-763)

---

tools/ds-identify

```
Move LXD to end ds-identify DSLIST
LP: #1959118
```
See LP: #1959118

Move LXD to end ds-identify DSLIST

---

.travis.yml
Makefile
doc/examples/cloud-config-disk-setup.txt
doc/examples/cloud-config-install-packages.txt
doc/examples/cloud-config-landscape.txt
doc/examples/cloud-config-mount-points.txt
doc/examples/cloud-config-power-state.txt
doc/examples/cloud-config-user-groups.txt
doc/examples/cloud-config.txt
doc/examples/kernel-cmdline.txt
doc/examples/seed/README
doc/examples/seed/meta-data
doc/rtd/conf.py
doc/rtd/topics/datasources.rst
doc/rtd/topics/datasources/smartos.rst
doc/rtd/topics/datasources/vmware.rst
doc/rtd/topics/datasources/vultr.rst
doc/rtd/topics/faq.rst
doc/rtd/topics/instancedata.rst
doc/rtd/topics/network-config-format-v1.rst
doc/sources/kernel-cmdline.txt
doc/sources/ovf/README
doc/sources/ovf/make-iso
doc/userdata.txt

```
Fix spelling errors
- Add Makefile target that checks for spelling errors
- Add Makefile target that fixes spelling errors
- Add spelling check to travis doc tests
- Fix various spelling errors in the docs 
```
revert the bug fixes in the second commit to test the new makefile target functionality
```
git reset --hard HEAD^
make check_spelling
echo $?
make fix_spelling
make check_spelling # note the one error fix_spelling couldn't automagically fix
make fix_spelling
echo $?
```
Note that this [build](https://app.travis-ci.com/github/canonical/cloud-init/jobs/557796208) fails (before the spelling fixes) and this [build](https://app.travis-ci.com/github/canonical/cloud-init/jobs/557796695) succeeds (after the fixes).

spell check docs with spellintian (SC-770)

---

doc/rtd/topics/integration_tests.rst
tests/integration_tests/bugs/test_gh570.py
tests/integration_tests/bugs/test_gh671.py
tests/integration_tests/bugs/test_lp1813396.py
tests/integration_tests/bugs/test_lp1835584.py
tests/integration_tests/bugs/test_lp1897099.py
tests/integration_tests/bugs/test_lp1900837.py
tests/integration_tests/bugs/test_lp1910835.py
tests/integration_tests/clouds.py
tests/integration_tests/conftest.py
tests/integration_tests/instances.py
tests/integration_tests/modules/test_cli.py
tests/integration_tests/modules/test_power_state_change.py
tox.ini

```
Integration testing docs and refactor
* Include CI and Fixtures sections in integration test docs
* Incorporate additional variable annotations
* Remove unnecessary IntegrationInstance subclasses
* Move setup_image teardown into its fixture
```

Integration testing docs and refactor (SC-746)

---

integration-requirements.txt
tests/integration_tests/clouds.py
tests/integration_tests/instances.py

```
integration: do not LXD bind mount /etc/cloud/cloud.cfg.d
Since lxc bind mounts will be read-only as nobody:nogroup
we don't want to bind mount /etc/cloud/cloud.cfg.d into the
instance because some tests add artifacts to /etc/cloud/cloud.cfg.d.
Also make LXD push_file pull_file methods assert that the
file transfer was a success, otherwise we miss the root-cause
for test failures.
This resulted in failed Jenkins runs in test_lxd_discovery with a
symptom of NoCloud being detected instead of LXD datasource.
The root-case was that instance.file_push failed due to permission
errors for root on the bind mounted /etc/cloud/cloud.cfg.d.
Also bump pycloudlib commitish to get Azure Jammy image support.
```
```bash
cat >/tmp/pycloudlib-lxd.toml <<EOF
[lxd]
EOF
CLOUD_INIT_PLATFORM=lxd_container …
```

integration: do not LXD bind mount /etc/cloud/cloud.cfg.d

---

cloudinit/distros/gentoo.py

```
Fix Gentoo locales
```
Tracking down a stack trace in gentoo cloud LXD images pointed out an issue with localization on gentoo. It's possible that this code once "succeeded" with a different image build. Fix the trace and actually set a locale. 
https://wiki.gentoo.org/wiki/Localization/Guide/en
Stack Trace:
```
2022-01-24 20:04:10,553 - util.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) failed
File "/usr/lib/python3.9/site-packages/cloudinit/stages.py", line 884, in _run_modules
ran, _r = cc.run(run_name, mod.handle, func_args,
File "/usr/lib/python3.9/site-packages/cloudinit/cloud.py", line 54, in run
return self._runners.run(name, functor, args, freq, …
```

Fix Gentoo Locales (SC-748)

---

tests/integration_tests/conftest.py
tests/integration_tests/modules/test_combined.py

```
Integration test changes
* Wrap the log fetching code in a try/except in case file is missing
* Stop checking NoCloud seed dir when testing datasource detection
```

Integration test changes

---

tests/integration_tests/clouds.py

```
testing: stop universally overwriting /etc/cloud/cloud.cfg.d
As part of IN_PLACE testing, /etc/cloud/cloud.cfg.d get overwritten by
what's in the source tree. This can cause problems when the directory is
mounted in, because tests need the ability to modify files in
/etc/cloud. Attempting to 'lxc file push'  instead will fail on LXD VMs
because the LXD agent isn't available yet.
If such functionality is desired, one can temporarily use the
'lxd_setup' mark while writing a test and push the files manually.
```
#1234

testing: stop universally overwriting /etc/cloud/cloud.cfg.d

---

cloudinit/config/cc_mounts.py

The ephemeral disk depends on a functional network to be mounted. Even
though it depends on cloud-init.service, sometimes an ordering cycle is
noticed on the instance. If the option "_netdev" is added the problem is
gone.
rhbz: #1998445
Deploy a RHEL-9/cloud-init-21.1 instance on Azure and observe that sometimes there's an ordering cycle on the logs and there's no network connectivity.

Add _netdev option to mount Azure ephemeral disk

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/sources/test_azure.py

Currently it checks for imds_md is None, but imds_md is returned as
an empty dictionary on error fetching metdata.
Fix this check and the tests that are incorrectly vetting IMDS
polling code.
Additionally, use response.contents() instead of str(response) when
loding the JSON data returned from readurl.  This helps simplify the
mocking and avoids an unncessary conversion.

sources/azure: fix metadata check in _check_if_nic_is_primary()

---

cloudinit/config/cc_salt_minion.py

```
cc_salt_minion freebsd fix for rc.conf
This fixes a bug that prevents the salt module from enabling the salt minion in rc.conf.
For more details:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254339
```

cc_salt_minion freebsd fix for rc.conf (SC-782)

---

cloudinit/sources/DataSourceAzure.py
cloudinit/sources/helpers/azure.py
tests/unittests/sources/test_azure.py

Introduce:
-  _setup_ephemeral_networking() to bring up networking.
If no iface is specified, it will use net.find_fallback_nic()
which is consistent with the previous usage of fallback_interface.
This method now tracks the encoded address of the wireserver
with a new property `_wireserver_endpoint`.
- _teardown_ephemeral_networking() to bring down networking.
- _is_ephemeral_networking_up() to check status.
Ephemeral networking is now:
- Brought up prior to checking IMDS.
- Torn down following metadata crawl.
- For Savable PPS, torn down prior to waiting for NIC detach.
The link must be torn down in advance or we will see errors
from cleaning up network after the interface is unplugged.
- For Running PPS, torn down after waiting for media switch.
The link must be up for media switch to …

sources/azure: consolidate ephemeral DHCP configuration

---

tests/integration_tests/instances.py

Test pycloudlib's [BaseInstance.pull_file](https://github.com/canonical/pycloudlib/blob/main/pycloudlib/instance.py#L228) doesn't return a Result
object. So we can't call ok() on the None response in integration tests.
When an integration test failes, this error results in _collect_logs incorrectly reporting that a pull_file has failed 
leaving an uncompressed tarfile which was correctly downloaded.
Leave the try/except handling as pull_file will raise an
IOError if there is an error connecting via paramiko's sftp.get.
```
Test pycloudlib's BaseInstance.pull_file doesn't return a Result
object. So we can't call ok() on the response in integration tests.
Leave the try/except handling as pull_file will raise an
IOError if there is an error connecting via paramiko's sftp.get.
```
Run the …

tests: do not assert instance.pull_file().ok()

---

cloudinit/sources/helpers/azure.py

Remove debug print that snuck in on a previous fixup.

sources/azure: drop debug print

---

cloudinit/sources/__init__.py
tests/integration_tests/modules/test_combined.py
tests/unittests/sources/test_init.py

Once a valid datasource is detected, publish the following artifacts
to expedite cloud-identification without having to invoke cloud-id from
shell scripts or sheling out from python.
These files can also be relied on in systemd ConditionPathExists
directives to limit execution of services and units to specific
clouds.
/run/cloud-init/cloud-id:
- A symlink with content that is the canonical cloud-id of the                    datasource detected. This content is the same lower-case value
as the output of /usr/bin/cloud-id.
/run/cloud-init/cloud-id-\<**canonical-cloud-id**\>:
- A single file which will contain the canonical cloud-id encoded
in the filename
```
Once a valid datasource is detected, publish the following artifacts
to expedite cloud-identification without having to invoke …
```

cloud-id: publish /run/cloud-init/cloud-id-<cloud-type> files

---

cloudinit/config/cc_mounts.py
tests/integration_tests/modules/test_disk_setup.py

Fixes the spaces introduced in #1213

mounts: fix mount opts string for ephemeral disk

---

tests/integration_tests/modules/test_disk_setup.py

Ubuntu Jammy output from lsblk --json now contains
'mountpoints': [...] instead of 'mountpoint' for children devs.
Let our integration test handle either case.
```bash
CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_KEEP_INSTANCE=true CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE CLOUD_INIT_OS_IMAGE=bionic::ubuntu::bionic  .tox/integration-tests/bin/pytest tests/integration_tests/modules/test_disk_setup.py::TestDeviceAliases
-- or Jammy --
CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_KEEP_INSTANCE=true CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE CLOUD_INIT_OS_IMAGE=jammy::ubuntu::jammy .tox/integration-tests/bin/pytest tests/integration_tests/modules/test_disk_setup.py::TestDeviceAliases
```

tests: lsblk --json output changes mountpoint key to mountpoinst []

---

tests/integration_tests/modules/test_apt.py

Yet another integration test fix, Azure has custom/local APT security URLs instead of security.ubuntu.com
```
test_apt_security: azure platform has specific security URL overrides
Delivered in /etc/cloud/cloud.cfg.d/90-azure.cfg
```

test_apt_security: azure platform has specific security URL overrides

---

doc/rtd/topics/format.rst

Docs for x-shellscript* userdata (SC-795)

---

tests/integration_tests/modules/test_set_password.py

This resolves ` AssertionError: assert None == '$y$j9T$la3Xe...iM0xEOjQwtjxB'`  failures on our [bionic Jenkins test runner when exercising lxd_container jammy-daily jobs](https://jenkins.ubuntu.com/server/view/cloud-init/job/cloud-init-integration-lxd_container-jammy-daily-ppa/4/console)
```
There are inconsistencies for cryptographic libraries across
major distribution releases.
From a bionic host, attempting run run crypt.crypt locally using
salt and format info from a Jammmy /etc/shadow file will result in
a failure to produce an encrpted password.
To avoid inconsistencies of python cryptographic libs across Linux
releases, perform the password encryption on the system under test.
```
From a bionic host system
```PYCLOUDLIB_CONFIG=pycloudlib.toml CLOUD_INIT_PLATFORM=lxd_container …
```

tests: when generating crypted password, generate in target env

---

cloudinit/sources/helpers/vultr.py
tests/unittests/sources/test_vultr.py

Fix extra ipv6 issues, code reduction and simplification
```
I eliminated the duplicate code and now run the entire configuration routine against both public and private interfaces. I also addressed an inconsistency from our metadata api for ipv6 address configuration.
```
Start a Vultr vm with additional IPv6's added to the instance.

Fix extra ipv6 issues, code reduction and simplification

---

cloudinit/config/cc_runcmd.py

Multiple times I have seen confusion over runcmd and how to know what it's running. It'd help to know that runcmd isn't actually executing the script and what module is.

docs: Add more details to runcmd docs

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/sources/test_azure.py

Due to race conditions and caching, IMDS may return stale or incomplete
metadata.  Add some validation to detect these scenarios and report
appropriate telemetry.

sources/azure: validate IMDS network configuration metadata

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/sources/test_azure.py

If the VM is rebooted during provisioning, the PPS type will be
determined to be UNKNOWN and will poll for reprovision data.
Given that we will never enter _wait_for_all_nics_ready() in any
other condition than a fresh source instance in Savable PPS, we can
safely remove the now-unused code paths.

sources/azure: removed unused savable PPS paths

---

cloudinit/sources/DataSourceAzure.py
cloudinit/url_helper.py
tests/unittests/sources/test_azure.py

sources/azure: ensure retries on IMDS request failure
There are two issues with IMDS retries:
1. IMDS_VER_WANT will never be attempted if retries=0, such as
when fetching network metadata with infinite=True.
2. get_imds_data_with_api_fallback() will attempt one request with
IMDS_VER_WANT.  If the connection fails due to a timeout, connection
issue, or error code other than 400, an empty dictionary will be
returned without attempting the requested number of retries.
This PR:
- Updates get_imds_data_with_api_fallback() to invoke
get_metadata_from_imds() with the specified retries and infinite
parameters.
- Updates retry_on_url_exc to take a configurable set of HTTP error
codes and exception types to retry on.
- Add IMDS_RETRY_CODES set to retry with when fetching data from IMDS:
- 404 not …

sources/azure: ensure retries on IMDS request failure

---

debian/apport-launcher.py
debian/changelog

```
debian/apport-launcher.py: Fix string and whitespace formatting
```

Fix format for tests in ubuntu/devel

---

doc/man/cloud-init.1

```
Include missing subcommand in manpage
```
```
...
SYNOPSIS
cloud-init [-h] [-d] [-f FILES] [--force] [-v] {init,modules,single,query,dhclient-hook,features,analyze,de‐
vel,collect-logs,clean,status}"
...
clean  Remove logs and artifacts so cloud-init can re-run.
devel  Run development tools. See help output for subcommand details.
dhclient-hook
Run the dhclient hook to record network info.
...
```

Include missing subcommand in manpage

---

tests/integration_tests/modules/test_apt.py

software-properties 0.99.18 now adds PPAs with HTTPS URLs in
sources.list when using add-apt-repository. This change only
affects Jammy.
We could use a regexp to match both, but it's simpler to just remove
the protocol from the search string.
```
test_ppa_source: accept both http and https URLs
software-properties 0.99.18 (>= Jammy) adds PPAs with
HTTPS URLs in sources.list when using add-apt-repository.
Older versions still add plain HTTP URLs.
We could use a regexp to match both, but it's simpler to just
remove the protocol from the search string.
```
Spotted by Jenkins.
```
AssertionError: assert 'http://ppa.launchpad.net/simplestreams-dev/trunk/ubuntu' in 'deb https://ppa.launchpadcontent.net/simplestreams-dev/trunk/ubuntu/ jammy main\n# deb-src …
```

test_ppa_source: accept both http and https URLs (SC-825)

---

tests/integration_tests/modules/test_combined.py

```
tests: on AWS proper, cloud-id actually starts with aws not ec2
Other clouds such as aliyun, brightbox, e24cloud and zstack
which have EC2-like metadata services will not return "aws"
from cloud-id.
Example AWS instance data:
$ cloud-init query --format '{{platform}} {{cloud_id}}'
ec2 aws
```
```
CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily CLOUD_INIT_PLATFORM=ec2  tox -e integration-tests  tests/integration_tests/modules/test_combined.py::TestCombined::test_instance_json_ec2
```

tests: on AWS proper, cloud-id actually starts with aws not ec2

---

tests/integration_tests/modules/test_apt.py

```
Fix integration test ppa url
```
Per https://github.com/canonical/cloud-init/pull/1287/files/a677b2486f8a945d35c0f9a5d295063aa9b69209#r812973166, the url conditional is backwards.

Integration test fix ppa 

---

debian/changelog
debian/patches/retain-apt-partner-pocket.patch
debian/patches/series

We need to revert one minor PR to retain original behavior on impish/focal/bionic for default APT sources templates.
Steps to create this PR:
https://github.com/canonical/uss-tableflip/blob/main/doc/ubuntu_release_process.md#adding-a-quilt-patch-to-debianpatches
```
```

retain commented APT partner pocket in sources list

---

tests/integration_tests/clouds.py

```
tests: create a IPv4/IPv6 VPC in Ec2 integration tests
Integration tests should create their own VPC in EC2 because
an account's default VPC, subnets, security groups and ACLs
cloud be configured for for limited or unexpected connectivity.
```
```
CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily CLOUD_INIT_PLATFORM=ec2  tox -e integration-tests  tests/integration_tests/modules/test_combined.py::TestCombined::test_instance_json_ec2
```

tests: create a IPv4/IPv6 VPC in Ec2 integration tests

---

cloudinit/distros/__init__.py
tests/integration_tests/modules/test_users_groups.py

```
Do not silently ignore integer uid
The docs do not make it obvious that uid is supposed to be of type string.
Current behavior is to silently ignore integer uid.
LP: #1875772
```
Since the docs aren't clear about what type it should be, support both string and integer types. It is reasonable for the user to assume integer. Currently planned jsonschema work would have allowed a warning message when providing an "incorrect type", but in the absence of clear documentation for this key, supporting string and integer types here is more user friendly.
Drop the second commit and watch the new integration test fail
Alternatively:
Verify the following userdata produces users with the correct UID.
```
#cloud-config
groups:
- secret: [root]
- cloud-users
users:
- default
- name: foobar
gecos: …
```

Fix Silently Ignored UID (SC-817)

---

cloudinit/util.py
tests/unittests/test_util.py

If a dead symlink by the same name is present, os.path.exists returns
false.
Signed-off-by: Shreenidhi Shedi <yesshedi@vmware.com>
```
summary: Check for existing symlink while force creating symlink
If a dead symlink by the same name is present, os.path.exists returns
false.
```

Check for existing symlink while force creating symlink

---

.github/workflows/cla.yml

Fix link in CLA check to point to contribution guide
The CLA check should point users to the contribution guide, the hacking guide is a 404.
See CLA results from a recent PR and verify it points to the contribution guide
Verify that the URL mentioned is 200 OK

Fix link in CLA check to point to contribution guide.

---

packages/pkg-deps.json

The hostname command, that cloud-init uses to apply a hostname change,
is in a package that is typically around, but not guarranteed to be.
Include it in package dependencies.
---
My CLA signature: https://github.com/canonical/cloud-init/pull/1286

redhat: Depend on "hostname" package

---

cloudinit/analyze/show.py
cloudinit/config/cc_puppet.py
cloudinit/sources/helpers/azure.py
tests/unittests/config/test_cc_puppet.py

It is reasonable to expect that "systemctl" is found in one of the locations in the PATH
+ Using the '/bin' prefix is very distribution specific. A number of
distributions are moving all executables from '/' to '/usr'.
```
systemctl may bot be in `/bin`
```
cloud-init on a distribution where systmctl is in `/usr/bin` produces an error
Command: ['/bin/systemctl', 'show', '-p', 'UserspaceTimestampMonotonic']
[   37.366919] cloud-init[882]: Exit code: -
[   37.369468] cloud-init[882]: Reason: [Errno 2] No such file or directory:
- [ x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
- [x ] I have updated or added any unit tests accordingly

systemctl location

---

cloudinit/net/dhcp.py
tests/unittests/net/test_dhcp.py

When performing DHCP, it is useful for the caller to have context
on the type of failure.  This can be done with some new exceptions
types, subclassing NoDHCPLeaseError so the caller's current
contract remains.
- Add the following errors:
- NoDHCPLeaseInterfaceError if there are problems finding
the (possibly specified) interface.
- NoDHCPLeaseMissingDhclientError for missing dhclient.
- Update InvalidDHCPLeaseFileError to subclass NoDHCPLeaseError.
- Pass through these errors rather than catching it in obtain_lease().
Tests:
- Add missing mock for test_provided_nic_does_not_exist().
- Add new test coverage for EphemeralDHCPv4 errors.
- Update existing tests for maybe_perform_dhcp_discovery() to match
new behavior.

net/dhcp: surface type of DHCP lease failure to caller
