- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
With debug logging, tight loops may result in huge log file sizes, e.g.:
"Unable to find fallback nic"
1. Raise NoDHCPLeaseMissingDhclientError to caller if no dhclient found
instead of retrying DHCP, retrying will not fix a missing dhclient.
2. For other DHCP failures, retry after sleeping one second.
Depends on #1276 
Would be a good candidate for SRU, if possible.
> sources/azure: prevent tight loops for DHCP retries

- cloudinit/templater.py
- tests/unittests/test_templating.py
- tools/.github-cla-signers
Adding support for jinja do statements in template rendering.
```
summary: adding support for jinja 'do' statements in jinja templating
Support for jinja do statements will prevent having to workaround the following exception:
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'do'.
LP: #1962759
```
When processing the following example, the jinja exception is thrown.
{% set data_result = [] %}
{% set data_input = [1,2,3] %}
{% for i in data_input %}
{% do data_result.append(i) %}
{% endfor %}
{{data_result}}
> add support for jinja do statements, add unit test

- doc/rtd/topics/boot.rst
- doc/rtd/topics/docs.rst
- doc/rtd/topics/format.rst
```
Improve docs.
- remove unnecessary "First Boot Determination" from tox
- reorder user-data formats based on usage frequency
```
cloud-config at the top, upstart at the bottom
> docs improvements

- systemd/cloud-init-local.service.tmpl
```
Remove unused init local artifact
```
This isn't used in cloud-init and systemd provides commands to show that `cloud-init-local.service` has been reached. It seems like a debugging artifact that shouldn't be needed.
> Remove Unused Init Local Artifact

- cloudinit/sources/helpers/vultr.py
- tests/unittests/sources/test_vultr.py
Better interface handling for Vultr, expect unexpected DHCP servers
```
If a private interface is configured, has a DHCP server on it, and Cloud-Init runs, the Datasource fails to fail over to the next interface interrupting seeking. Configuring it as such can also lead to delays in deploy time if it did. This sorts the interface list to limit the potential of this occurring. Checks for the metadata route before trying, and now appropriately fails over if those contingencies fails by appropriately continuing to seek on metadata failure as was originally intended. Ideally the upcoming candidate_nic would of been used here to avoid the interface list function.
```
The complexity here is due to the wild inconsistency on the platform. An image may end up on a vm, or a baremetal server, or not …
> Better interface handling for Vultr, expect unexpected DHCP servers

- .travis.yml
```
Switch to python 3.10 in Travis CI
Travis 3.10 support previously required pinning to 3.10.1. This restriction
no longer exists.
```
> travis supports 3.10 now (SC-843)

- tests/integration_tests/modules/test_combined.py
```
Remove flaky test
This ssh-import-id test uses multiple remote key servers
that fail periodically.
```
Here is an example flaky failure:
https://github.com/canonical/cloud-init/pull/1302#issuecomment-1061763157
This same failure has happened to me as well.
> remove flaky test from ci (SC-850)

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/helpers/azure.py
- doc/rtd/topics/datasources/azure.rst
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_azure_helper.py
With reporting ready now happening in local phase, we have access
to ephemeral DHCP lease options and no longer need to parse DHCP
lease files.
- Switch from tracking wireserver endpoint in its encoded form to the
IP string, parsing it only when read from lease options.
- Drop fallback_lease_file and dhcp_options parameters in favor of
processed endpoint string.
- Add some minor type information for mypy.
> sources/azure: remove lease file parsing

- tests/unittests/sources/test_vmware.py
Make VMWare data source test host independent and expand testing
```
At present the test to get the host info is dependent on the network
of the host on which the test is run. If there is no network the test will
fail. Make the test host independent by applying appropriate mocks and
expand the test to cover ipv4, ipv6, and dual stack setups.
```
- [x ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
- [ x] I have updated or added any unit tests accordingly
> Make VMWare data source test host independent and expand testing

- doc/rtd/topics/datasources/configdrive.rst
- doc/rtd/topics/datasources/rbxcloud.rst
- tools/ds-identify
```
Make fs labels match for ds-identify and docs
- ConfigDrive datasource works with CONFIG-2, document it
- RbxCloud datasource works with cloudmd, document it
- OpenNebula datasource supports CDROM, but ds-identify doesn't check it
```
> Fix fs label documentation and ds-identify (SC-854)

- cloudinit/url_helper.py
- tests/unittests/test_url_helper.py
It may be useful to configure connection timeout and read timeout
separately.  Update readurl() to accept a tuple that is supported
by python requests to configure both.
> url_helper: add tuple support for readurl timeout

- systemd/cloud-init-generator.tmpl
- tests/integration_tests/clouds.py
- tests/integration_tests/cmd/test_status.py
```
Fix cloud-init status --wait when no datasource found
In 0de7acb1, we modified status checks to wait until we get an "enabled"
or "disabled" file from our generator. It never outputs a
"disabled" file, so "status --wait" will wait indefinitely if no
datasource is found.
LP: #1966085
```
See: https://github.com/canonical/cloud-init/pull/1162
Run tests/integration_tests/cmd/test_status.py
I also manually checked the generator script to verify that enabled and disabled files get created as expected and are mutually exclusive.
> Fix cloud-init status --wait when no datasource found

- cloudinit/sources/helpers/vultr.py
- tests/unittests/sources/test_vultr.py
Vultr code cleanup and missing dns
```
Use find_candidate_nics and add IPv6 DNS.
```
> Vultr code cleanup and missing dns

- doc-requirements.txt
CI docs is currently failing on main due to a new jinja2 release.
> docs: add jinja2 pin

- cloudinit/config/cc_ssh_authkey_fingerprints.py
- tests/integration_tests/modules/test_ssh_auth_key_fingerprints.py
prevent cc_ssh_authkey_fingerprints.py from inadvertently creating a home when "no_create_home: true", or "system: true"
```
summary: stop cc_ssh_authkey_fingerprints from ALWAYS creating home
cloudinit/config/cc_ssh_authkey_fingerprints.py unintentionally ends
up creating a home directory for a user even when `no_create_home:
true` or `system: true`. This prevents it.
`cc_ssh_authkey_fingerprints.py` calls `ssh_util.extract_authorized_keys`,
which ends up calling `check_create_path`, which creates the as yet
non-existent home while looking for an `authorized_keys` file to parse.
`cc_ssh_authkey_fingerprints.py` looks like the best place to stop this.
NOTE that I do not handle the situation where (`no_create_home: true`
or `system: true`) *and* yet `ssh_authorized_keys` is provided. In …
```
> prevent cloudinit/config/cc_ssh_authkey_fingerprints.py from creating home when "no_create_home: true", or "system: true"

- .readthedocs.yaml
```
docs: Re-order readthedocs install
Order building cloud-init before building doc-requirements.txt.
Building '.' invokes a 'pip install --upgrade .' which happens to also
re-install the latest versions of some previously pinned 
docs dependencies
Also updated the yaml to 2-space indents.
```
> docs: Re-order readthedocs install (SC-884)

- cloudinit/config/cc_apt_configure.py
- tests/unittests/config/test_apt_source_v1.py
- tests/unittests/config/test_apt_source_v3.py
```
Add --no-update to add-apt-repostory call
In cc_apt_configure, "add-apt-repository" is called a few lines before
we make a call to update packages, so the additional update that
happens in "add-apt-repository" is redundant and a waste of time.
Additionally, the update in add-apt-repository can fail on
obtaining apt lock and cause the module to raise an exception.
```
> Add --no-update to add-apt-repostory call (SC-880)

- tests/unittests/test_net_freebsd.py
Is failing for me locally (but not in CI)
> testing: Add missing mock to networking test

- doc-requirements.txt
- doc/examples/cloud-config-user-groups.txt
- doc/rtd/conf.py
- doc/rtd/topics/cli.rst
- doc/rtd/topics/datasources/configdrive.rst
- doc/rtd/topics/examples.rst
- doc/rtd/topics/logging.rst
- doc/rtd/topics/security.rst
```
Various doc fixes:
- fix rst to actually render the security page
- remove headers of missing examples
- m2r seems abandoned, switch to m2r2
- hide deprecated content in a drop-down panel
- bump sphinx to 4.3
- ping sphinx_rtd_theme (workaround for bullet list rendering issue)
- use inline literal rather than italics for code
- fix a broken link
```
Note: it looks like docutils 0.17 / sphinx_rtd_theme < 0.5.2 breaks things, context can be found [here](https://github.com/readthedocs/sphinx_rtd_theme/issues/1115) (link included as a comment in doc-requirements.txt)
Planned future work: resolve the 40+ warnings that sphinx spews (mostly harmless, I think?) and then make warnings fail CI (this would have prevented some of the errors I fixed in this PR).
> Doc fixes (SC-857)

- cloudinit/config/cc_mounts.py
- cloudinit/stages.py
- cloudinit/util.py
- tests/unittests/test_merging.py
- tox.ini
```
Black < 22.3.0 didn't handle a dropped internal attribute _unicodefun
from in more click package version 8.1.0. Due to issue
Issue: https://github.com/psf/black/issues/2964
This broke our CI and tox -e do_format targets with
cannot import name '_unicodefun' from 'click'.
Increment our pinned black to 22.3.0 and apply minor format
change rules.
```
> black: bump pinned version to 22.3.0 to avoid click dependency issues

- doc/rtd/topics/datasources/lxd.rst
- tests/integration_tests/datasources/test_lxd_discovery.py
- tests/unittests/test_ds_identify.py
- tools/ds-identify
```
ds-identify: also discover LXD by presence from DMI board_name = LXD
VMs will not start lxd-agent.service in systemd generator timeframe
which means /dev/lxd/sock will not exist yet on LXD VM.
For VM support, ds-identify will return DS_FOUND when
/sys/class/dmi/id/board_name == "LXD" which exists at
early boot regardless of LXD socket status.
Later, in cloud-init init-local boot stage, cloud-init's will only
discover the LXDDatasource if the /dev/lxd/sock is active.
This allows consumers to disable the LXD datasource
behavior by running:
lxc config set MACHINE_NAME security.devlxd=false
```
```
$ CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_KEEP_INSTANCE=true CLOUD_INIT_CLOUD_INIT_SOURCE=/home/csmith/src/cloud-init/cloud-init_22.1-25-g67b413dc-1~bddeb_all.deb CLOUD_INIT_OS_IMAGE=focal tox -e …
```
> ds-identify: also discover LXD by DMI board_name = LXD

- cloudinit/distros/rhel.py
- tests/unittests/distros/test_generic.py
- tools/.github-cla-signers
Make sure to use system locale as default on RHEL if locale is not
set in cloud-config.
>  Honor system locale for RHEL

- tests/unittests/test_net.py
Hello
I am executing the cloud-init test case and the testcase has occasionally failed.
The failure testcases are:
FAILED tests/unittests/test_net.py::TestGetInterfaces::test_gi_excludes_any_without_mac_address
FAILED tests/unittests/test_net.py::TestGetInterfaces::test_gi_excludes_stolen_macs
FAILED tests/unittests/test_net.py::TestGetInterfaces::test_gi_includes_duplicate_macs
The error log for each failed use case is similar as follows:
```
def test_gi_excludes_any_without_mac_address(self):
self._mock_setup()
>       ret = net.get_interfaces()
tests/unittests/test_net.py:5431:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cloudinit/net/__init__.py:941: in get_interfaces
if is_netfailover(name):
cloudinit/net/__init__.py:204: in is_netfailover
if …
```
> The devname referenced in your traceback should be the result of get_devicelist(), which should be mocked.

- tests/integration_tests/modules/test_combined.py
Fixes failures like:
```
>       assert re.match(r"3.\d\.\d", v1_data["python_version"])
E       AssertionError: assert None
E        +  where None = <function match at 0x7f1206b7bc80>('3.\\d\\.\\d', '3.10.3')
```
https://jenkins.ubuntu.com/server/view/cloud-init/job/cloud-init-integration-jammy-gce/2/testReport/tests.integration_tests.modules.test_combined/TestCombined/test_instance_json_gce/
> tests: python 3.10 is showing up in cloudimages

- tox.ini
```
tox: add types-* packages to check_format env
```
`tox -e check_format` 
Fails on mypy because the type stubs aren't installed.
> tox: add types-* packages to check_format env (SC-898)

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
Wait up to 10 seconds for link to come up before continuing. This
typically takes just a few seconds once the NIC is hotplugged.
If it takes longer than 10 seconds for whatever reason, dhclient
should eventually succeed on its next attempt after the link does
come online.
> sources/azure: remove bind/unbind logic for hot attached nic

- cloudinit/config/cc_ssh_import_id.py
- tools/.github-cla-signers
The import of ssh keys for users does not work in corporate networks
behind proxies.
The ssh-import-id command does not support cmd line arguments or other
configurations for specifying a proxy. The sudo command in the module
executes the ssh-import-id command directly, so any proxy settings of
shells will not work. The only option would be either to specify the
proxy setting on the command line, but this wouldn't be easily user
editable.
So the only solution is to selectively forward any already set
https_proxy variable to the executed command. Since only one env
variable is used and forwarded, the security impact should be
acceptable.
> Expose https_proxy env variable to ssh-import-id cmd

- cloudinit/sources/DataSourceEc2.py
- doc/rtd/topics/datasources/ec2.rst
- tests/unittests/sources/test_ec2.py
- tools/.github-cla-signers
```
Support EC2 tags in instance metadata
Add support for newer EC2 metadata versions (up to 2021-03-23), so that
tags can be retrieved from the `ds.meta_data.tags` field, as well as
with any new fields that might have been added since the 2018-09-24
version.
```
I'm not sure about:
* whether I should have used the latest available metadata version as of today (`2021-07-15`, that is one release after the one I wrote). I ended up using the minimum version that supported tags.
* Maybe the commit message should be modified to reflect other changes (beyond `tags`) that come with that upgrade?
* whether I chose a good testing strategy. My tests would actually pass without the changes I did, so I would appreciate some guidance on how to test something more useful.
* Enable tags on metadata for …
> Support EC2 tags in instance metadata

- tests/unittests/test_ds_identify.py
- tools/ds-identify
```
Launching KVM instances from a host system with > 5.10 kernel results
in LXC passing `hv_passthrough` to the kvm instance being launched.
Systemd < 251 will incorrectly detect the CPU in this case as
"qemu" instead of "kvm".
ds-identify needs to properly interpret systems with
sytemd-detect-virt="qemu"  and /sys/class/dmi/id/board_name="LXD"
This functionality can be dropped once systemd 251 support is
available on all supported distributions.
LP: #1968085
```
https://github.com/systemd/systemd/issues/22709
From a jammy host:
```
$ lxc profile show jammy-vm
config: {}
description: Default LXD profile for jammy VMs
devices:
eth0:
name: eth0
network: lxdbr0
type: nic
root:
path: /
pool: default
type: disk
name: jammy-vm
$ lxc launch ubuntu-daily:jammy --vm --profile jammy-vm test-jammy …
```
> ds-identify: detect LXD for VMs launched from host with > 5.10 kernel

- cloudinit/cmd/status.py
- cloudinit/util.py
- tests/unittests/test_util.py
The status file read here is a symlink which is not atomically
updated, since `get_status_details` already copes with not being able
to read the status file, we simply suppress the error reading it.
LP:1962150
TODO: Needs appropriate testing.
Passes unit tests locally
> Suppress FileNotFoundError when reading status

- cloudinit/config/cc_ubuntu_advantage.py
- cloudinit/config/cc_ubuntu_drivers.py
- cloudinit/config/cc_update_etc_hosts.py
- cloudinit/config/cc_update_hostname.py
- cloudinit/config/cc_write_files.py
- cloudinit/config/cc_write_files_deferred.py
- cloudinit/config/cc_yum_add_repo.py
- cloudinit/config/cc_zypper_add_repo.py
- cloudinit/config/cloud-init-schema.json
- doc/examples/cloud-config.txt
- doc/rtd/topics/modules.rst
- tests/unittests/config/test_cc_ubuntu_advantage.py
- tests/unittests/config/test_cc_ubuntu_drivers.py
- tests/unittests/config/test_cc_update_etc_hosts.py
- tests/unittests/config/test_cc_write_files.py
- tests/unittests/config/test_cc_write_files_deferred.py
- tests/unittests/config/test_cc_yum_add_repo.py
- tests/unittests/config/test_schema.py
```
Migrate legacy schema to cloud-init-schema.json:
- cc_ubuntu_advantage
- cc_ubuntu_drivers
- cc_write_files: added minItems: 1 to list to catch potential YAML typos
- cc_write_files_deferred
- cc_zypper_add_repo
Defined JSON schema for the following modules:
- cc_update_hostname
- cc_update_etc_hosts: Add DEPRECATED log for manage_etc_hosts: "template" as 
it is non-intuitive alias of True value
- cc_yum_add_repo:  docstring incorrectly status PER_ALWAYS, but no module
frequency attribute was defined, so cloud-init defaults to PER_INSTANCE.
Set it PER_INSTANCE explicitly to avoid change in behavior.
```
Does not contain cc_user_groups as that's a fairly big module schema to sort, so I'd like to keep that module separate for
ease of review.
```
tox -re doc; xdg-open …
```
> schema: add json defs for modules U-Z

- cloudinit/distros/gentoo.py
```
Pull in Gentoo patches.
These patches are issues/features that have been fixed downstream.
Grab the remaining patches.
```
See the 22.1 patches here:
https://github.com/gentoo/gentoo/tree/master/app-emulation/cloud-init/files
> Grab last remaining Gentoo patches (SC-919)

- tests/unittests/config/test_cc_ntp.py
- tests/unittests/test_sshutil.py
- tests/unittests/test_temp_utils.py
```
Distro compatibility fixes:
- Don't assume python's tempdir location
- Fix hostname jsonschema test 
```
- Gentoo's build system uses an environment variable[1] to specify Python's temporary directories. Our tempfiles tests assume `/tmp/` is the only possible location, which is not always true. Python uses `gettempdir()` to define tempfile locations, so should we.
[gentoo-tempfail.txt](https://github.com/canonical/cloud-init/files/8459928/gentoo-tempfail.txt) 
- jsonschema validation doesn't think that `valid` is a valid hostname on Gentoo. I don't know why this differs (see references in commit message), but the fix is straightforward. Need to investigate to ensure this test isn't getting skipped on Ubuntu.
[gentoo-hostnamefail.txt](https://github.com/canonical/cloud-init/files/845992 …
> Distro Compatibility Fixes (SC-921)

- setup.py
- tox.ini
```
Mypy stubs and other tox maintenance
- add type stubs for mypy: jinja, jsonschema, oauthlib
- specify mypy directories to avoid env/ false positive
- add conftest.py and setup.py
- make setup.py pass pylint:
- check ./tools/render-cloudcfg return code in setup.py
- find_sources() has no return code, don't check for one
```
find_sources has never had a return code: https://github.com/pypa/setuptools/commit/873ebe91a8de43df836c873d9106e5af31c302e4
> Mypy stubs and other tox maintenance (SC-920)

- cloudinit/gpg.py
- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/helpers/vmware/imc/guestcust_util.py
- cloudinit/subp.py
- cloudinit/util.py
- tests/unittests/config/test_apt_key.py
- tests/unittests/sources/vmware/test_guestcust_util.py
- tests/unittests/test_gpg.py
- tests/unittests/test_util.py
```
Return a namedtuple from subp()
This provides a minor readability improvement.
subp.subp(cmd)[0] -> subp.subp(cmd).stdout
subp.subp(cmd)[1] -> subp.subp(cmd).stderr
```
Named tuples are an "easy win" in terms of readability. I'm open to suggestions if someone would rather a different name than `PipeOutput`.
> cloudinit.sub.py: Return a namedtuple

- cloudinit/net/network_state.py
- cloudinit/net/renderer.py
- cloudinit/net/sysconfig.py
- tests/unittests/test_net.py
```
Fix KeyError when rendering sysconfig IPv6 routes
Route rendering code was expecting a netmask rather than using the
prefix. A prefix is provided to the renderer, but was being hidden
from the route rendering code. This commit exposes the prefix and
prefers it for IPv6, given how uncommon netmasks are for IPv6.
LP: #1958506
```
See https://bugs.launchpad.net/cloud-init/+bug/1958506
> Fix KeyError when rendering sysconfig IPv6 routes (SC-776)

- cloudinit/ec2_utils.py
- cloudinit/sources/DataSourceEc2.py
- cloudinit/url_helper.py
- integration-requirements.txt
- test-requirements.txt
- tests/integration_tests/clouds.py
- tests/integration_tests/datasources/test_ec2.py
- tests/unittests/sources/test_ec2.py
- tests/unittests/test_url_helper.py
- tox.ini
```
Add support for dual stack ipv6/ipv4 IMDS to Ec2
- add support for parallel http(s) requests to wait_for_url()
- implementation based loosely on RFC6555: "Happy Eyeballs" [1]
- update ec2 datasource to support dual-stack ipv6/ipv4
- only "nitro" instances have ipv6 IMDS, favor ipv4 initially
- replace httpretty with requests for ec2 tests
[1] https://datatracker.ietf.org/doc/html/rfc6555
```
In contrast to "happy eyeballs", this implementation supports parallel attempts to communicate with a small delay favoring ipv4. This is datasource-specific, and other datasources that wish favor ipv6 can do so trivially.
1.  use a threadpool executor to wrap synchronous calls in async scheduler (see `url_helper.py:dual_stack()`) that does 0.150s delay, cancels pending responses, etc (basically a …
> Add ec2 IPv6 IMDS Support (SC-336)

- cloudinit/config/cc_users_groups.py
- cloudinit/config/cloud-init-schema.json
- cloudinit/config/schema.py
- cloudinit/distros/ug_util.py
- doc/examples/cloud-config-user-groups.txt
- tests/unittests/config/test_cc_users_groups.py
- tests/unittests/config/test_schema.py
- tests/unittests/test_cli.py
```
schema: add json defs for module cc_users_groups
Additional support for markdown docs of nested $refs:
- Support types as list for doc rendering versus single {"type": "string"}
- Add _sort_property_order so 'array' and 'object' types are sorted last
when multiple types are listed via oneOf or type lists
- Decorate enum values with double back-ticks and replace "string" type
- Add _flatten_schema_refs support for extracting $defs into inline schema
definition
LP: #1858930
```
```bash
git checkout upstream/main
PYTHONPATH=. python3 -m cloudinit.cmd.main devel schema --docs all > orig-docs
git checkout <this_branch>
PYTHONPATH=. python3 -m cloudinit.cmd.main devel schema --docs all > new-docs
diff -urN orig-docs new-docs
Also review full rendered docs for typos, …
```
> Schema users

- cloudinit/net/__init__.py
- cloudinit/net/dhcp.py
- cloudinit/net/network_manager.py
- cloudinit/net/network_state.py
- cloudinit/net/sysconfig.py
- tests/unittests/net/test_init.py
- tests/unittests/test_net.py
```
Network functions refactor and bug fixes
- replace common functionality with standard library implementations
- add is_ip_network() for validating addresses in form: "192.168.1.1/24"
- add validation to _normalize_net_keys
- fix eni tests that formerly tested invalid ipv6 addresses (caught by
stricter validation)
- other refactorization and name standardization
```
Fixing is_ipv6_addr() broke a lot of tests, which demonstrated that it was implemented incorrectly _and_ used incorrectly.
> Network functions refactor and bugfixes

- cloudinit/config/cc_ntp.py
- cloudinit/config/cloud-init-schema.json
- tests/unittests/config/test_cc_ntp.py
- tests/unittests/config/test_schema.py
Fixes: SC-803
```
cc_ntp: migrated legacy schema to cloud-init-schema.json
Fixes: SC-803
```
```bash
PYTHONPATH=. python3 -m cloudinit.cmd.main devel schema --docs all > docs.main
hub pr checkout 1384
PYTHONPATH=. python3 -m cloudinit.cmd.main devel schema --docs all > docs.PR
diff -urN docs.main docs.PR
```
> cc_ntp: migrated legacy schema to cloud-init-schema.json

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
sources/azure: only wait for primary nic to be attached during restore
```
summary:
Currently DS Azure waits for all nics to be up and running during the 
restore phase of save-restore VMs. This change will alter the behavior
so that it will only wait for primary nic. This new behavior is consistent
with non-preprovisioning and running types.
```
> sources/azure: only wait for primary nic to be attached during restore

- cloudinit/config/cc_ssh_import_id.py
- packages/debian/control.in
```
cc_ssh_import_id: Warn and skip module if missing dep
Add ssh-import-id as a suggested package dependency for debs
```
Context:
We have a module that uses ssh-import-id. Users of ssh-import-id will want this package installed.
> declare dependency on ssh-import-id (SC-864)

- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/test_azure_helper.py
Remove unused functionality and general kwargs support in favor
of defined parameters.
As only headers and data kwargs are used, add those explicitly
to http_with_retries().
There should be no behavioral changes.
> sources/azure: refactor http_with_retries to remove **kwargs

- debian/changelog
- debian/control
[Daily builds are unable to build now that unittests have a dependency on responses.](https://launchpadlibrarian.net/596826434/buildlog_ubuntu-jammy-amd64.cloud-init_22.1-3180-g4af644ba-0ubuntu1+1954~trunk~ubuntu22.04.1_BUILDING.txt.gz)
Add it to d/control Build-depends.
Turns out my comment at standup about worrying about build-depends being pulled in as hard package `Depends` was bogus, we had already separated those dependencies years ago :/ Sorry for the "fake news".
```
d/control: add python3-responses for unittests
```
```
git checkout upstream/ubuntu/main
build-package
sbuild --resolve-alternatives --dist=jammy --arch=amd64 ../out/cloud-init*dsc
```
> Ubuntu/devel: d/control: add python3-responses for unittests

- cloudinit/config/cc_ubuntu_advantage.py
- cloudinit/config/cc_update_hostname.py
- cloudinit/config/cloud-init-schema.json
- tests/unittests/config/test_cc_seed_random.py
- tests/unittests/config/test_schema.py
```
tests: make module example tests very strict to specific schema
Followup to c2bfd5. Schema module examples should be strictly
validated against the specific schema. Given that
cloud-init-schema.json defines a permissive 'allOf' set of schemas
top-level additionalParoperties that are undefined in schema are
permitted.
This allowed for multiple typos to get through schema
unittest validation.
Also fix invalid schema definition in cc_seed_random which should define
`random_seed` property instead of `seed_random`.
```
Unit tests should now strictly validate and fail and specific example typos:
```
tox -e py3  tests/unittests/config/test_schema.py -vv
```
> Schema example doc fixes

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
While this was a previously intended change, the actual logic was
backwards.  Try for 20 minutes during provisioning, only 5 minutes
otherwise.
Add test coverage to verify the timeout for provisioning scenarios.
> sources/azure: fix provisioning dhcp timeout to 20 minutes

- debian/changelog
- debian/control
```
d/control: add python3-responses for unittests
```
ref: https://github.com/canonical/cloud-init/compare/ubuntu/bionic...holmanb:ubuntu/bionic?expand=1
```
git checkout upstream/ubuntu/impish
build-package
sbuild --resolve-alternatives --dist=impish --arch=amd64 ../out/cloud-init*dsc
```
> Impish: d/control: add python3-responses for unittests

- cloudinit/stages.py
- tests/unittests/test_ds_identify.py
- tools/ds-identify
```
Fix ds-identify not detecting NoCloud seed in config
NoCloud seed config can be defined in /etc/cloud/cloud.cfg[.d].
However, ds-identify had no means of detecting this config and reported
NOT FOUND. This commit allows ds-identify to detect and report it
properly.
LP: #1876375
```
LP: #1876375 notes that if you specify the datasource list in a cfg file, it works, but if you don't it doesn't. It has nothing to do with the reading of the config files. If the datasource list only contains one entry (or one + None), ds-identify skips datasource detection entirely and just uses the specified datasource. https://github.com/canonical/cloud-init/blob/main/tools/ds-identify#L1793-L1798 . The problem is that ds-identify just had no means of detecting this use case.
> Fix ds-identify not detecting NoCloud seed in config (SC-542)

- cloudinit/config/cc_ssh_import_id.py
- tests/integration_tests/bugs/test_gh570.py
- tests/integration_tests/bugs/test_gh632.py
- tests/integration_tests/datasources/test_lxd_discovery.py
- tests/integration_tests/modules/test_combined.py
- tests/integration_tests/modules/test_persistence.py
- tests/integration_tests/util.py
- tests/unittests/config/test_cc_ssh_import_id.py
```
cc_ssh_import_id: fix is_key_in_nested_dict avoid early return False
In 437cb0a we added recursive is_key_in_nested_dict.
This function should early returning only in the event of finding
an ssh_import_id directive.
Test updates:
- test_combined LXD datasource expectation for Jammy
- Jammy LXD no longer supplies /var/lib/cloud/seed/nocloud-net/
- Jammy has neither NoCloud nor /var/lib/cloud/seed/nocloud-net
- verify_ordered_items_in_text accept regex LXD|NoCloud
```
```
make deb
CLOUD_INIT_PLATFORM=lxd_container  CLOUD_INIT_OS_IMAGE=jammy::ubuntu::jammy CLOUD_INIT_CLOUD_INIT_SOURCE=/path/to/cloud-init*.deb tox -e integration-tests tests/integration_tests/modules/test_combined.py
```
> nested ssh import id and jammy lxd test fixes

- tests/unittests/sources/test_ec2.py
```
testing: Add responses workaround for focal/impish
The responses workaround relies on an internal variable, and the
internals changed between Bionic and Focal, so the workaround needs
to be updated as well.
```
This fixes tests failing on Focal/Impish
> testing: Add responses workaround for focal/impish (SC-954)

- cloudinit/distros/__init__.py
- cloudinit/distros/bsd.py
- cloudinit/distros/freebsd.py
- cloudinit/distros/netbsd.py
- cloudinit/distros/networking.py
- cloudinit/net/__init__.py
- cloudinit/stages.py
- tests/unittests/distros/test_networking.py
- tests/unittests/net/test_init.py
- tests/unittests/test_stages.py
- tests/unittests/util.py
```
cloudinit.net refactor: apply_network_config_names
- Remove `apply_network_config_names` from `cloudinit.net` and `Distro` classes so it is only accessible via the networking attribute.
LP: #1884602
```
> cloudinit.net refactor: apply_network_config_names

- cloudinit/config/cc_growpart.py
- cloudinit/subp.py
- test-requirements.txt
- tests/unittests/config/test_cc_growpart.py
- tox.ini
Take 2 of #1032
```
Allow growpart to resize encrypted partitions
Adds the ability for growpart to resize a LUKS formatted partition.
This involves resizing the underlying partition as well as the
filesystem. 'cryptsetup' is used for resizing.
This relies on a file present at /cc_growpart_keydata containing
json formatted 'key' and 'slot' keys, with the key being
base64 encoded. If resizing is successful, cloud-init will destroy
the luks slot used for resizing and remove the key file.
```
I tried to structure the unit tests such that they act more end-to-end, rather than testing individual functions at a time. This involved some additional mocking setup, but I think it's overall worth it.
As of right now, an in-tree integration test is impractical.
Following a [Canonical internal …
> Resize encrypted partitions (SC-353)

- cloudinit/config/cc_ssh_authkey_fingerprints.py
- cloudinit/config/cc_users_groups.py
- doc/examples/cloud-config-user-groups.txt
- tests/unittests/config/test_cc_users_groups.py
```
summary: raise error when home should not be created AND ssh keys are provided
An invalid user config would be if no_create_home or system is set to
True, AND (ssh_authorized_keys or ssh_import_id or ssh_redirect_user)
is also provided. Right now, cloud-init proceeds to create the keys
(which would obviously create home for the user).
This change will cause an error to be raised instead for this invalid
config.
```
sample user data:
```
#cloud-config
system_info:
default_user:
name: jf
users:
- default
- name: nch
no_create_home: true
ssh_authorized_keys:
- list
- of
- keys
- name: system
system: true
ssh_authorized_keys:
- list
- of
- keys
```
> raise ValueError when "no_create_home" or "system" is set and ssh_authorized_keys is also provided

- pyproject.toml
httpretty does not appear to support mypy stubs. Add configuration
to for mypy to ignore this import.
With this we can add checking for test_azure.py.
> mypy: disable missing imports warning for httpretty

- Makefile
- bash_completion/cloud-init
- cloudinit/cmd/devel/parser.py
- cloudinit/cmd/main.py
- doc/man/cloud-init.1
- doc/rtd/topics/cli.rst
- doc/rtd/topics/faq.rst
- doc/rtd/topics/tutorial.rst
- tests/integration_tests/modules/test_cli.py
- tests/unittests/test_cli.py
```
Promote schema command from devel to top level subcommand
```
> Promote cloud-init schema (SC-953)

- cloudinit/config/cc_rsyslog.py
- tests/unittests/config/test_cc_rsyslog.py
```
Fix cc_rsyslog.py initialization
Raises an error if some top level config value has an invalid type.
Previously, it replaced them with default values.
Fixes: SC-878
```
Execute `cloud-init` with this config:
```yaml
#cloud-config
rsyslog:
config_dir: True
```
Expected error:
```txt
"Invalid type for key `config_filename`. Expected type(s): <class 'str'>. Current type: <class 'bool'>"
```
> Fix cc_rsyslog.py initialization

- cloudinit/net/__init__.py
```
Don't fail if InfiniBand/Ethernet addresses collide
Current behavior for the collision of Ethernet mac 
address and the "openstack 6 byte IB format" is to fail[1].
This isn't a problem for the respective Ethernet and IB
networks, so don't force cloud-init to fail.
[1] https://bugs.launchpad.net/cloud-init/+bug/1871326
```
I was on the fence about whether to propose as-is, or to move forward with refactoring out the openstack-specific code. I proposed because this represents a failure path that I don't think we want and the "fix" is relatively small.
> Don't fail if IB and Ethernet devices 'collide'

- cloudinit/cmd/devel/hotplug_hook.py
- cloudinit/sources/DataSourceOracle.py
- cloudinit/sources/__init__.py
- cloudinit/stages.py
- tests/unittests/sources/test_common.py
- tests/unittests/sources/test_oracle.py
- tests/unittests/test_stages.py
From nametuple to enum.
```
Refactor cloudinit.sources.NetworkConfigSource to enum
It was implemented as a namedtuple, because it was written
when the codebase supported Python 2 (where using an enum would have
introduced a new dependency). As enum is in the stdlib in all our
supported Python releases, we can now use it without that constraint.
LP: #1874875
```
> Refactor cloudinit.sources.NetworkConfigSource to enum

- tests/integration_tests/util.py
Failures in Jenkins test runner indicate that the recent changes landed in 
02f213b539395be2f4b90b3b9e6bcd5fbc81c202 didn't account for some search items containing characters which need to be
re.escaped.  
```
tests: verify_ordered_items fallback to re.escape if needed
When re.search fails with an re.error, it is most likely due
to characters which need escape. Fallback to re.escape in
this case to try harder.
```
[Failing Jenkins job](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-lxd_container/15/testReport/tests.integration_tests.bugs/test_lp1813396/test_gpg_no_tty/)
```
.tox/integration-tests/bin/pytest tests/integration_tests/bugs/test_lp1813396.py::test_gpg_no_tty
```
> tests: verify_ordered_items fallback to re.escape if needed

- cloudinit/cmd/devel/hotplug_hook.py
- cloudinit/cmd/devel/make_mime.py
- cloudinit/cmd/main.py
- doc/man/cloud-init.1
- doc/rtd/topics/cli.rst
- doc/rtd/topics/faq.rst
```
Update cli docs and standardize grammar/spelling/punctuation
```
> Docs fixes

- doc/rtd/topics/datasources/nocloud.rst
```
- fix failing example command
- augment "alternative commands" with more common utilities
- drop reference to decade old release
```
qemu-img correctly identifies the format of the backing file, but fails anyways:
```
arc/tmp qemu-img create -f qcow2 -b disk.img boot-disk.img 
qemu-img: boot-disk.img: Backing file specified without backing format
Detected format of qcow2.%                                                                                            arc/tmp echo $?
1
```
Fix by adding `-F qcow2` to invocation.
Additionally, add some context to the `mcopy` command, as well as alternative option with mount/umount/cp
> Fix NoCloud docs:

- tools/run-container
```
run-container: add support for LXD VMs
Images of older releases (e.g. CentOS 7) can't run as containers on
newer Ubuntu releases because they need a CGroupV1 host system. They
can however run as VMs.
```
This change will be backported to the `stable-19.4` branch, which
is used in Jenkins to test builds of 19.4 on CentOS 7.
This will fail to launch the container:
```
./tools/run-container centos/7 --source-package --artifacts=.
```
This will not fail to launch the container
```
./tools/run-container centos/7 --source-package --artifacts=. --vm
```
It will however fail for other unrelated reasons.
Full test in VM mode:
```
./tools/run-container centos/8-Stream --source-package --artifacts=. --vm
```
> run-container: add support for LXD VMs (SC-981)

- tools/run-container
```
run-container: add support for LXD VMs
Backport of d1149988323bb88 to stable-19.4.
Images of older releases (e.g. CentOS 7) can't run as containers on
newer Ubuntu releases because they need a CGroupV1 host system. They
can however run as VMs.
```
Needed to keep the tests working on the stable-19.4 branch.
```
./tools/run-container centos/7 --source-package --artifacts=. --vm
```
> run-container: add support for LXD VMs (SC-985)

- cloudinit/cmd/devel/hotplug_hook.py
- setup.py
- tests/unittests/config/test_cc_growpart.py
- tests/unittests/sources/test_configdrive.py
- tests/unittests/test_ds_identify.py
- tox.ini
```
Update linters and adapt code for compatibility
Changes:
- pylint 2.13.8: fix E0601(used-before-assignment)
- pylint 2.13.8: fix E4702(modified-iterating-dict)
- pylint 2.13.8: silence W0402(deprecated-module) on distutils.errors
- tox: bump linters versions
```
This should make the `cloud-init-style-tip` green.
```
tox -e py3,black,flake8,isort,mypy,pylint,tip-flake8,tip-mypy,tip-pylint
```
> Update linters and adapt code for compatibility (SC-986)

- tests/integration_tests/modules/test_combined.py
```
testing: Fix LXD VM metadata test
Jammy additions changed the non-jammy subplatform check in a way that
caused failure.
```
> testing: Fix LXD VM metadata test (SC-990)

- cloudinit/net/network_state.py
- cloudinit/sources/DataSourceLXD.py
- cloudinit/sources/DataSourceNoCloud.py
- cloudinit/stages.py
- tests/unittests/net/test_network_state.py
- tests/unittests/sources/test_nocloud.py
- tests/unittests/test_stages.py
```
Consistently strip top-level network key
Our NetworkState parsing code expects no top level network key even
though it's part of our v1 and v2 standard. NoCloud and LXD datasources
had their own code to strip off the top-level network key, but it failed
for v2 configs. This commit simplifies and moves that code into the
parser so that it is consistent across all datasources.
LP: #1906187
```
See https://bugs.launchpad.net/cloud-init/+bug/1906187
> Consistently strip top-level network key (SC-963)

- tests/integration_tests/modules/test_disk_setup.py
```
testing: Ensure NoCloud detected in test
test_disk_setup_when_mounted changes userdata during the test run, so
ensure NoCloud datasource is used so new userdata is detected.
```
This one is simple enough I don't think we need to use the other NoCloud setup.
> testing: Ensure NoCloud detected in test

- debian/changelog
- debian/cloud-init.postinst
Support people who want to keep their modified /etc/cloud/cloud.cfg instead of package maintainer's version
by redacting deprecated emit_upstart config module from /etc/cloud/cloud.cfg if present.
In the event that a someone modified their /etc/cloud/cloud.cfg and opted to
keep their modified version instead of upstream maintainers version across up
cloud-init will remove the emit_upstart and upstart_dir references to avoid having a warning
in cloud-init logs about a missing emit_upstart config module.
Also in this branch is a sync of the released d/changelog entries from our devel-22.1-hotfix branch to prepare for a new-upstream-snapshot in ubuntu/devel which will follow after #1421 lands
```
-  changelog
-  d/postinst: remove deprecated emit_upstart from cloud.cfg on upgrade
- changelog …
```
> Ubuntu/devel (SC-984)

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
If we haven't reported ready for source PPS then we can treat
the recovery boot like any other.  The metadata on the OVF
and IMDS will indicate the PPS type correctly as the state
hasn't changed.
If we have reported ready for source PPS, we continue to fall
into _poll_imds() by way of setting pps_type to UNKNOWN if the
REPORTED_READY_MARKER is present and will not attempt to report
ready again.
This fixes a potential issue when recovering on Savable PPS.
If a recovery boot occurs after the recovery marker is created,
and without reporting ready, the subsequent boot will assume
pps type UNKNOWN and attempt to report ready in _poll_imds()
using the Running PPS netlink operations.
Add unit test coverage for complete recovery scenario.
> sources/azure: remove reprovisioning marker

- cloudinit/net/activators.py
- cloudinit/net/network_manager.py
- cloudinit/net/sysconfig.py
- tests/unittests/test_net_activators.py
```
Fix network-manager activator availability and order
The current network-manager activator availability check is too broad.
It triggers as available if chrony is installed. Its priority is also
higher than netplan, which means it can activate even if netplan config
has been rendered. This commit reverts the network-manager check to its
previous state and orders netplan above network-manager in priority.
```
Currently the check for network-manager only checks if '/usr/lib/NetworkManager' exists ([here](https://github.com/canonical/cloud-init/blob/main/cloudinit/net/network_manager.py#L372) and [here](https://github.com/canonical/cloud-init/blob/main/cloudinit/net/network_manager.py#L22))
On an Azure instance, after upgrade (tests/integration_tests/test_upgrade.py::test_clean_boot_of_upg …
> Fix network-manager activator availability and order (SC-991)

- cloudinit/config/cc_set_passwords.py
- cloudinit/distros/__init__.py
- packages/debian/control.in
- tests/unittests/config/test_cc_set_passwords.py
```
Add pre-fight check to verify if SSH is running
- In negative case then perform an early return with a warning and no 
modifications
- Handle an exception when user-data provides 'ssh_pwauth: True'
and the open-ssh service is not available
- Add openssh-server as suggested package for debian-based distros
SC-968
LP: #1969526
```
```sh
cat > ssh_needed.yaml << EOF
#cloud-config
ssh_pwauth: true
EOF
lxc launch ubuntu-daily:focal f1 -c user.user-data="$(cat ssh_needed.yaml)"
lxc exec f1 -- cloud-init status --wait
lxc exec f1 apt remove opensssh-server
lxc exec f1 -- sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
lxc exec f1 -- cloud-init clean --logs --reboot
lxc exec f1 -- cloud-init status --wait --long
```
Expect status Done and a warning in the …
> Handle error if SSH service no present.

- tests/integration_tests/datasources/test_lxd_discovery.py
- tests/integration_tests/modules/test_combined.py
```
testing: Make integration tests kinetic friendly
```
> testing: Make integration tests kinetic friendly

- cloudinit/config/schema.py
- cloudinit/safeyaml.py
- tests/unittests/config/test_schema.py
- tests/unittests/test_safeyaml.py
```
Use a custom yaml.SafeLoader to track SchemaMarks to define
start and end row/column values of each object within the
original cloud-config content.
Fixes KeyError from cloud-init devel schema --annotate when
encountering invalid nested list values under a dict key.
Drop _CustomSafeLoaderWithMarks replaces the need for
_schemapath_for_cloudconfig logic.
Fixes: SC-929
```
```bash
$ cat <baduser.txt  >>EOF
#cloud-config
users:
- default                                                                       
- name: ok
sudo: false
- name: user2
sudo: 2
EOF
PYTHONPATH=. python3 -m cloudinit.cmd.main devel schema -c baduser.txt --annotate
```
> schema: render schema paths from _CustomSafeLoaderWithMarks

- cloudinit/url_helper.py
- tests/unittests/test_url_helper.py
```
Log all exceptions in dual_stack()
```
While debugging something that uses the dual_stack() function, I noticed that exceptions are not being logged as originally intended.
All exceptions thrown from futures in dual_stack() should be logged for debugging purposes.
> Fix bug in url_helper/dual_stack() logging

- cloudinit/config/cc_set_passwords.py
- tests/unittests/config/test_cc_set_passwords.py
```
testing: mock uses_systemd in ssh password tests
Tests currently assume systemd, so add a mock such that uses_systemd
always returns True.
```
Dailies are failing. See
https://launchpadlibrarian.net/600835820/buildlog_ubuntu-jammy-amd64.cloud-init_22.1-3228-g3e5938c6-0ubuntu1+1959~trunk~ubuntu22.04.1_BUILDING.txt.gz
I haven't actually reproduced the errors on a local machine, but based on the failures I would be surprised if the new mock doesn't work.
> testing: mock uses_systemd in ssh password tests (SC-1040)

- integration-requirements.txt
- tests/integration_tests/decorators.py
- tests/integration_tests/instances.py
- tests/integration_tests/modules/test_combined.py
- tests/integration_tests/modules/test_keys_to_console.py
- tests/integration_tests/modules/test_set_password.py
- tests/integration_tests/modules/test_ssh_auth_key_fingerprints.py
- tests/integration_tests/util.py
```
testing: Fix console_log tests
Bring in the pycloudlib change effecting the console_log on ec2.
Additionally, provide a helper function for retrieving the console log
to reduce duplication.
Moved the retry decorator into a new file to avoid cyclic dependency
and had to update call sites accordingly.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-ec2/15/testReport/tests.integration_tests.modules.test_keys_to_console/TestKeysToConsoleEnabled/test_duplicate_messaging_console_log/
> testing: Fix console_log tests (SC-992)

- cloudinit/config/cc_ssh.py
- cloudinit/config/cloud-init-schema.json
- tests/unittests/config/test_cc_ssh.py
- Delete *-sk keys from cloud-init-schema.json under
cc_ssh.{ssh_keys,ssh_genkeytypes}
- Log a warning if some given key is unsupported or unknown.
- Port tests to Pytests, add some types and increase unittest
coverage.
```
Drop support of *-sk keys in cc_ssh.
- Delete *-sk keys from cloud-init-schema.json under
cc_ssh.{ssh_keys,ssh_genkeytypes}
- Log a warning if some given key is unsupported or unknown.
- Port tests to Pytests, add some types and increase unittest
coverage.
```
SC-908
After the discussions in #cloud-init we decided to drop the support
of *-sk key types because:
1) In the autogeneration case, user interaction with the device is needed,
which does not fit with a cloud-context.
2) This type of keys are user-based, not hostkeys.
About the integration tests, without the need …
> Drop support of *-sk keys in cc_ssh.

- cloudinit/config/cc_snap.py
- cloudinit/config/cloud-init-schema.json
- tests/integration_tests/modules/test_combined.py
- tests/unittests/config/test_cc_snap.py
cc_snap.maybe_install_squashfuse no longer needed in Bionic++.
squashfuse install no longer required as snapd feature was backported
and released (and Xenial support is no longer available for
cloud-init).
```
Drop cc_snap.maybe_install_squashfuse.
cc_snap.maybe_install_squashfuse no longer needed in Bionic++.
squashfuse install no longer required as snapd feature was backported
and released (and Xenial support is no longer available for
cloud-init).
```
SC-903
> Drop cc_snap.maybe_install_squashfuse.

- cloudinit/config/cc_set_passwords.py
- tests/unittests/config/test_cc_set_passwords.py
If the SSH status is checked in a non-systemd system, do not
distinguish between service statuses and log a generic warning
as we cannot expect status exit codes fulfilling any convention.
```
Log generic warning on non-systemd systems.
If the SSH status is checked in a non-systemd system, do not
distinguish between service statuses and log a generic warning
as we cannot expect status exit codes fulfilling any convention.
```
https://github.com/canonical/cloud-init/pull/1422#issuecomment-1124936382
> Log generic warning on non-systemd systems.

- cloudinit/config/modules.py
- tests/integration_tests/modules/test_combined.py
- tests/integration_tests/modules/test_frequency_override.py
- tests/integration_tests/modules/test_write_files.py
```
Each cloud-config module defines meta["frequency"] module attribute.
This frequency will be preferred unless overrides are given in
/etc/cloud/cloud.cfg module definitions.
```
> cc_modules: set default meta frequency value when no config available

- doc/examples/cloud-config-disk-setup.txt
```
Fix typos in disk names
The name `ephmeral0` appears in two places in this file, but based 
on the fact that `ephemeral0` is used elsewhere in the file, it is 
very likely that `ephmeral0` is actually a typo.
```
First spotted while reading the formatted docs at https://cloudinit.readthedocs.io/en/latest/topics/examples.html
This is a file of examples and (I think) not something that can be tested directly.
> Fix apparent typos in disk names

- cloudinit/sources/DataSourceScaleway.py
- tests/unittests/sources/test_scaleway.py
- tools/.github-cla-signers
```
summary: Scaleway: Fix network configuration for netplan 0.102 and later
Since version 0.102 netplan no longer supports the option `gateway6`.
This commit changes this option to the newer `routes` one.
```
Cloud init currently fails to run on Scaleway instances with OSes using recent Netplan versions. This PR fixes the issue by updating the generated netplan configuration to stop using deprecated options.
> Scaleway: Fix network configuration for netplan 0.102 and later

- cloudinit/config/cc_set_passwords.py
- tests/unittests/config/test_cc_set_passwords.py
- If the system doesn't use systemd and the status of the ssh
service is not 0, then apply the pw_auth config. As distros as
Alpine could start the ssh service later in the boot sequence.
- Change log level from warning to debug when ssh_pwauth is
written but the ssh service is not restarted.
```
Improve cc_set_passwords.
- If the system doesn't use systemd and the status of the ssh
service is not 0, then apply the pw_auth config. As distros as
Alpine could start the ssh service later in the boot sequence.
- Change log level from warning to debug when ssh_pwauth is
written but the ssh service is not restarted.
```
SC-968
https://github.com/canonical/cloud-init/pull/1450#issuecomment-1127138478
> Improve cc_set_passwords.

- cloudinit/config/cc_write_files.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_write_files.py
Allow `text/plain` in write_files.encoding.
```
cc_write_files: Improve schema.
Allow `text/plain` in write_files.encoding.
```
> cc_write_files: Improve schema.

- config/cloud.cfg.tmpl
- systemd/cloud-config.service.tmpl
- systemd/cloud-final.service.tmpl
- systemd/cloud-init-local.service.tmpl
- systemd/cloud-init.service.tmpl
- tests/unittests/test_render_cloudcfg.py
```
So far RHEL had its own custom .service and cloud.cfg files,
that diverged from upstream. We always replaced the generated files
with the ones we had.
This caused only confusion and made it harder to rebase and backport
patches targeting these files.
Hopefully this brings some alignment with upstream.
At the same time, we are going to delete our custom downstream-only files
and use the ones generated by .tmpl.
The mapping is
config/cloud.cfg.tmpl -> rhel/cloud.cfg
systemd/* -> rhel/systemd/*
Such rhel-specific files are open and available in the Centos repo:
https://gitlab.com/redhat/centos-stream/src/cloud-init
Signed-off-by: Emanuele Giuseppe Esposito <eesposit@redhat.com>
```
RHBZ 2082071
> Systemd and config: align rhel custom files with upstream

- config/cloud.cfg.tmpl
- doc/rtd/topics/network-config.rst
```
This is adapted from Neal Gompa's PR:
https://github.com/canonical/cloud-init/pull/1435
The only difference is that we are not modifying renderers.py (thus
modifying the priority of all distros), but just tweaking cloud.cfg to
apply this change to Fedora and RHEL. Other distros can optionally
add themselves afterwards.
net: Prefer Netplan and NetworkManager renderers by default
NetworkManager is used by default on a variety of Linux distributions,
and exists as a cross-distribution network management service.
Additionally, add information about the NetworkManager renderer to
the cloud-init documentation.
Because Netplan can be explicitly used to manage NetworkManager,
it needs to be preferred before NetworkManager.
As part of this	change, delete a duplicate test case for network …
```
> Use Network-Manager and Netplan as default renderers for RHEL and Fedora

- ChangeLog
```
Changelog: correct errant classification of LP issues as GH
```
log2dch incorrectly represented `Fixes: SC-###` as fixed github issues in changelogs.
https://github.com/canonical/uss-tableflip/pull/89
> Changelog: correct errant classification of LP issues as GH

- .github/workflows/check_format.yml
- cloudinit/subp.py
```
Move "formatting tests" to Github Actions
```
Start with formatting tests, we can always go back to travis.
- Github integration means users see test result on local branch by default, no setup
- Lower friction UI and UX due to to integration
- [free](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions) (I think?)
the bonus tests (failing) will obviously be dropped before merge
> Github Actions

- .travis.yml
- Makefile
- doc/rtd/topics/faq.rst
```
Docs additions:
- Add service completion blockers to FAQ
- Update LXD config option names from deprecated names
- Add neovim configuration blog post
- Make docs test fail early on spelling error
- Update spelling filter
```
Example early exit success:
https://app.travis-ci.com/github/canonical/cloud-init/jobs/570863456
> Docs additions:

- tests/integration_tests/instances.py
```
integration tests: Log ip when `KEEP_INSTANCE = True`
```
Typically when I use this setting I expect manual debugging. Showing the IP at teardown is a small convenience for this workflow.
Thoughts?
Example:
```
-------------------------------------------------------------------------------------------- live log teardown --------------------------------------------------------------------------------------------
2022-05-24 04:21:27 INFO      pycloudlib.instance:instance.py:183 executing: sudo -- sh -c 'cloud-init collect-logs -u -t /var/tmp/cloud-init.tar.gz'
2022-05-24 04:21:28 INFO      integration_testing:conftest.py:197 Writing logs to /tmp/cloud_init_test_logs/220523221536/tests/integration_tests/datasources/test_ec2_ipv6/test_dual_stack
2022-05-24 04:21:28 INFO …
```
> integration tests: If KEEP_INSTANCE = True, log IP (SC-1077)

- .vscode/extensions.json
- cloudinit/config/schemas/schema-cloud-config-v1.json
- cloudinit/config/schemas/versions.schema.cloud-config.json
```
schema: write_files defaults, versions $ref full URL and add vscode
* Set write_files.permissions and content defaults the correct "string"
data type. This aids in vscode auto-completion which injects default
values for defined cloud-config keys.
* Make the $ref URI a full URL to our schema-cloud-config-v1.json
JSON schema Draft-04 does not support relative $ref URLs which
prevents validators like https://www.jsonschemavalidator.net/
from parsing our versions schema with the error:
Error when resolving schema reference './schema-cloud...json'.
* Add vscode exstentions for validatating #cloud-config YAML
Developers using the cloud-init repo are likely to also
want to create #cloud-config YAML files for development. Provide
the suggested YAML extension in .vscode/extensions.json.
This …
```
> schema: write_files defaults, versions $ref full URL and add vscode

- cloudinit/config/cc_yum_add_repo.py
- tests/unittests/config/test_cc_yum_add_repo.py
Prefer "-" as repo id separator.
```
cc_yum_add_repo: Fix repo id canonicalization
Prefer "-" as repo id separator.
LP: #1975818
```
SC-1086
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/sec-setting_repository_options
```sh
cat <<EOT > /tmp/user-data.yaml
#cloud-config
yum_repos:
rhel-8.5-appstream-mycloud:
baseurl: <url>
name: "repo name"
enabled: True
EOT
lxc launch images:fedora/36/cloud fedora --config=user.user-data="$(cat /tmp/user-data.yaml)"
lxc exec fedora -- cloud-init status --wait
$ lxc exec fedora -- cat /etc/yum.repos.d/rhel-8.5-appstream-mycloud.repo
[rhel-8.5-appstream-mycloud]
baseurl = ...
```
> cc_yum_add_repo: Fix repo id canonicalization

- cloudinit/config/cc_ubuntu_advantage.py
Fix documentation about ubuntu_advantage.enable list.
```
cc_ubuntu_advantage: Fix doc
Fix documentation about ubuntu_advantage.enable list.
```
SC-1083
> cc_ubuntu_advantage: Fix doc

- tests/integration_tests/clouds.py
In the case of pre-launched instances, the IntegrationInstance
client creation did return a pycloudlib.BaseInstance instead of
an IntegrationInstance.
```
Fix integration test client creation
In the case of pre-launched instances, the IntegrationInstance
client creation did return a pycloudlib.BaseInstance instead of
an IntegrationInstance.
```
SC-1091
1. Create manually a cloud Instance.
2. Configure the instance_id in `tests/integration_tests/integration_settings.py::EXISTING_INSTANCE_ID`.
3. Execute an integration hitting the configured cloud.
> Fix integration test client creation

- .github/workflows/check_format.yml
Is there a reason we want it enabled for push and not just for PRs?
> Only run github actions on pull request (SC-1094)

- cloudinit/config/cc_runcmd.py
```bash
doc: Add runcmd str vs. list arg behavior to module docs
```
Per discussion [here](https://bugs.launchpad.net/cloud-init/+bug/1977780) I think we should document this better.
Note: The comment about rc.local isn't as relevant as it used to be, but I don't think it should be removed at this time.
The rendering:
> improve runcmd docs

- cloudinit/dmi.py
- cloudinit/net/__init__.py
- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/DataSourceOracle.py
- cloudinit/sources/__init__.py
- integration-requirements.txt
- pyproject.toml
- tests/integration_tests/datasources/test_lxd_discovery.py
- tests/integration_tests/datasources/test_network_dependency.py
- tests/integration_tests/datasources/test_oci_networking.py
- tests/integration_tests/integration_settings.py
- tests/unittests/distros/test_networking.py
- tests/unittests/helpers.py
- tests/unittests/sources/test_oracle.py
- tox.ini
iSCSI-based config is limited to older images in Oracle. 
cloud-init need to prefer network content from vNIC IMDS crawl.
1. Use /run/net-* files if they exist. Currently if /run/initramfs/open-iscsi.interface does not exist, we do not use them.
2. If we cannot obtain networking information from /run/net-* files, use IMDS to configure the primary interface. Currently IMDS is ONLY used for secondary interfaces, and if the iSCSI files don’t exist, we use the fallback “best guess” method as our primary interface.
```
DS Oracle network changes
For primary network config:
- Use `iSCSI` config if some `/run/net*` file exists, even if 
`/run/initramfs/open-iscsi.interface` does not.
- If the instance is not an `iSCSI` one, then crawl the network
config from `IMDS` instead of falling back to …
```
> Oracle ds changes

- cloudinit/config/cc_phone_home.py
- tests/unittests/config/test_cc_phone_home.py
```
Fix cc_phone_home requiring 'tries'
As part of dee8231, the code was updated to use a ValueError rather than
catching the top level Exception. This should have also included
catching TypeError. Also, calculate 'retries' correctly.
Additionally, add unit tests for module as it effectively had none.
LP: #1977952
```
I officially apologize for all of the younger-me rants about checked exceptions in other languages.
> Fix cc_phone_home requiring 'tries' (SC-1101)

- cloudinit/cmd/devel/net_convert.py
- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
- Replace parse_network_config() with _generate_network_config()
instance method and consolidate cache checks into network_config.
- Update _generate_network_config_from_imds_metadata() to take
just network metadata portion of instance metadata.
- Consolidate relevant unit tests and refactor to pytest.
> sources/azure: minor refactoring to network config generation

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
Azure does not populate ovf-env.xml with UserData, just CustomData.
Update tests accordingly.
> sources/azure: remove unused userdata property from ovf

- setup.py
```
RHEL must put cloudinit .rules files in /usr/lib/udev/rules.d
This place is a rhel standard and since it is used by all packages
cannot be modified.
Signed-off-by: Emanuele Giuseppe Esposito <eesposit@redhat.com>
```
> setup.py: adjust udev/rules default path

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
This property is not found in Azure's ovf-env.xml.
Remove relevant code merging it into datasource config
and unit tests.
> sources/azure: remove dscfg parsing from ovf-env.xml

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
- seedfrom is not used by Azure ovf-env.xml, remove it.
- azure_data is capturing arbitrary keys and we already
have a redacted ovf-env.xml if we need to inspect any
(unused) properties.
> sources/azure: remove unused metadata captured when parsing ovf

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
It is unused and unsupported in Azure's ovf-env.xml. Remove it.
> sources/azure: remove unused encoding support for customdata

- .travis.yml
```
CI: drop linters from Travis CI (moved to GH Actions)
```
Past PR that added a GH Actions workflow for the linters: https://github.com/canonical/cloud-init/pull/1496
Looks reliable.
Check the "checks" list in any recent PR.
> CI: drop linters from Travis CI (moved to GH Actions) (SC-1118)

- tox.ini
```
tox: integration-tests-jenkins: softfail if only some test failed
Prior to this change a single test failure when running the
integration-tests-jenkins tox environment caused Jenkins jobs to fully
fail (status FAILURE).
With this change the pytest's "some tests failed" return code [1] is
ignored, and the status of the Jenkins jobs is determined using the
junit report that pytest generates. Most of the time this will result
in UNSTABLE (yellow) jobs when some tests failed.
If the junit report is missing (or only reports failures) the job
will still be marked as FAILURE (red).
[1] https://docs.pytest.org/en/7.1.x/reference/exit-codes.html
```
See the internal Jenkins `cloud-init` view.
1. Sabotage a test and run the `integration-tests-jenkins` on a subset
of tests containing it. Verify …
> tox: integration-tests-jenkins: softfail if only some test failed (SC-1117)

- cloudinit/sources/DataSourceOVF.py
- tests/unittests/sources/test_ovf.py
```
summary: 
Change the second error code reporting for GUESTCUST_ERROR_SCRIPT_DISABLED from (4, 100) to (4, 6)
```
In GUESTCUST_ERROR_SCRIPT_DISABLED failure, cloud-init reports customization state (and error code) twice, which are used to be (4, 6) and (4, 100). The interval of the two reporting is short. 
Sometimes the first reporting (4, 6) can be inhibited, which may make users confused about the customization failure reason.
This update changes the second reporting from (4, 100) to (4, 6). 
And this change is compatible with the VMware traditional guest OS customization behavior. 
Run unit test
> Rongz609 pr2976717

- packages/redhat/cloud-init.spec.in
Update spec file per change landed in PR: #1513 
```
redhat spec: udev/rules.d lives under /usr/lib on rhel-based systems
Cloud-init now delivers udev rules to /usr/lib/udv/rules.d on
rhel-based systems as of commit 7071512.
Update spec template to unblock COPR builds of CentOS/8-Stream which
fail on RPM build errors like:
File not found: /build.../lib/udev/rules.d/66-azure-ephemeral.rules
Use spec macro %{_udevrulesdir} instead of hard-coding rules dir.
```
COPR build log failure on CentOS/8:
https://download.copr.fedorainfracloud.org/results/@cloud-init/cloud-init-dev/epel-8-x86_64/04547217-cloud-init/builder-live.log.gz
```
./tools/run-container centos/8-Stream --vm --name ci-c8 --source-package --package --artifacts=.
```
> Centos copr builds udev

- packages/debian/control.in
- packages/pkg-deps.json
```
d/control: add python3-debconf to Build-Depends
```
Added to be able to run python3-debconf unittests.
SC-1102
https://github.com/canonical/cloud-init/pull/1511/files#r899456743
`make deb`
> d/control: add python3-debconf to Build-Depends

- cloudinit/apport.py
- cloudinit/cmd/devel/logs.py
- cloudinit/cmd/main.py
- cloudinit/config/cc_snap.py
- cloudinit/distros/__init__.py
- cloudinit/helpers.py
- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/DataSourceBigstep.py
- cloudinit/util.py
- tests/integration_tests/bugs/test_lp1976564.py
- tests/integration_tests/test_paths.py
- tests/unittests/cmd/devel/test_logs.py
- tests/unittests/config/test_cc_snap.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_bigstep.py
- tests/unittests/test_apport.py
- tests/unittests/test_cli.py
- tests/unittests/test_util.py
```
cloud-config: honor cloud_dir setting
- Modules affected: cmd.main, apport, devel.logs (collect-logs),
cc_snap, sources.DataSourceAzure, sources.DataSourceBigstep,
util:fetch_ssl_details.
- testing: Extend and port to pytest unit tests, add integration test.
LP: #1976564
```
https://bugs.launchpad.net/cloud-init/+bug/1976564
https://warthogs.atlassian.net/browse/SC-1085
```sh
cat > /tmp/95-custom-cloud-dir.cfg <<EOF
system_info:
paths:
cloud_dir: /new-cloud-dir
EOF
CONTAINER_NAME=dev-k
lxc launch ubuntu-daily:kinetic $CONTAINER_NAME
lxc file push /tmp/95-custom-cloud-dir.cfg $CONTAINER_NAME/etc/cloud/cloud.cfg.d/
lxc exec $CONTAINER_NAME -- rm -rf /var/lib/cloud
lxc exec $CONTAINER_NAME -- cloud-init clean --logs --reboot
lxc exec $CONTAINER_NAME -- cloud-init status --wait --long
lxc …
```
> cloud-config: honor cloud_dir setting

- cloudinit/sources/DataSourceLXD.py
- tests/unittests/sources/test_lxd.py
```
Fix LXD datasource crawl when BOOT enabled
In 53a995e2, the network config code was updated to initialize
variables to None rather than using "_unset" in order to simplify the
typing. On subsequent boots with the BOOT event enabled, this resulted
in network config being set to "_unset", causing cloud-init to fail
with traceback.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-lxd_container/47/testReport/tests.integration_tests.modules/test_user_events/test_boot_event_enabled/
> Fix LXD datasource crawl when BOOT enabled

- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_users_groups.py
- tools/.github-cla-signers
```
Change groups within the users schema to support lists and strings.
The `groups` section of `users` has traditionally supported arrays.
This change returns support for groups as a list instead of comma
separated string, as found in the documentation.
```
Attempt to validate a cloud-config yaml file with a list of groups.
> Change groups within the users schema to support lists and strings

- .github/workflows/check_format.yml
- .pylintrc
- cloudinit/config/cc_ssh.py
- tests/unittests/test_url_helper.py
- tox.ini
```
CI: add non-blocking run against the linters tip versions
Changes:
* Tox: the tip-black and tip-isort environments.
* Tox: reuse the non-tip commands in the tip- environments.
* Add non-blocking (continue-on-error: true) step in the test
test matrix to run the tip- linters on ubuntu-latest.
* Code fixups to make tip-pylint pass.
* Bump the pinned pylint version to 2.13.9 (last version
supporting Python 3.6).
```
Spotted by Jenkins job `cloud-init-style-tip`.
> CI: add non-blocking run against the linters tip versions (SC-1119)

- cloudinit/cmd/main.py
- cloudinit/config/schema.py
- tests/integration_tests/modules/test_cli.py
- tests/unittests/config/test_schema.py
Remove schema errors from log
When schema errors are encountered, the section of userdata in question
gets printed to the cloud-init log. As this could contain sensitive
data, so log a generic warning instead and redirect user to run
`cloud-init schema --system` as root.
LP: #1978422
> Remove schema errors from log

- cloudinit/config/cc_ssh_import_id.py
```
cc_ssh_import_id: Substitute deprecated warn
```
Run `tox -e py3`. The following warning won't appear:
```
tests/unittests/config/test_cc_ssh_import_id.py::TestHandleSshImportIDs::test_skip_inapplicable_configs[cfg2-ssh-import-id is not installed]
/home/aciba/canonical/cloud-init/cloudinit/config/cc_ssh_import_id.py:61: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
"ssh-import-id is not installed, but module ssh_import_id is "
```
> cc_ssh_import_id: Substitute deprecated warn

- Makefile
- tox.ini
```
tox: add unpinned env for do_format and check_format
Add make helpers to do and check fmt
```
My typical pre-push check `tox -e do_format && tox -e check_format` no longer catches all format issues since the -tip checks were added to CI. This PR adds `*_tip` variants to these environments and, while I'm at it, additionally adds some `make` helpers for these checks.
> Add formating environments to tox for unpinned dependencies

- tests/unittests/sources/test_cloudstack.py
```
tests: mock dns resolution that may cause long timeouts
```
This PR turns this (inconsistent):
```
19.72s call     tests/unittests/sources/test_cloudstack.py::TestCloudStackPasswordFetching::test_saved_password_doesnt_create_config
19.14s call     tests/unittests/sources/test_cloudstack.py::TestCloudStackPasswordFetching::test_password_not_saved_if_bad_request
18.94s call     tests/unittests/sources/test_cloudstack.py::TestCloudStackPasswordFetching::test_empty_password_doesnt_create_config
14.21s call     tests/unittests/sources/test_cloudstack.py::TestCloudStackPasswordFetching::test_password_not_saved_if_empty
14.15s call     tests/unittests/sources/test_cloudstack.py::TestCloudStackPasswordFetching::test_valid_response_means_password_marked_as_saved
14.07s call …
```
> tests: mock dns lookup that causes long timeouts

- .github/workflows/check_format.yml
- cloudinit/apport.py
We can see that `Lint Tests / Check format (pinned)` jobs do not run: [runs/2595343023](https://github.com/canonical/cloud-init/actions/runs/2595343023)
Fixed here: [actions/runs/2595516299](https://github.com/canonical/cloud-init/actions/runs/2595516299)
I have also improved the job names.
```
CI: Fix GH pinned-format jobs
```
https://warthogs.atlassian.net/browse/SC-1150
It is expected that jobs with `continue-on-error: true` finish as green in the UI but they are shown as red in the Action summary. More context on this: https://github.com/github-community/community/discussions/15452
> CI: Fix GH pinned-format jobs

- tests/integration_tests/cmd/test_status.py
We occasionally get [jenkins failures](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-impish-lxd_container/47/testReport/tests.integration_tests.cmd/test_status/test_wait_when_no_datasource/) that I believe are caused by the post-reboot code running on an instance that hasn't even gone down yet.
> testing: Wait for changed boot-id in test_status.py (SC-1146)

- cloudinit/net/__init__.py
- cloudinit/net/network_state.py
```
net: fix interface matching support
- broken in bf94945fb855c40c5188cef5fb
- factor out a reusable helper function
- stylistic change for match keyword
LP: #1979877
```
TODO: Find a better name than `get_interface_from_mac()`
Adapted from the test proposed [here](https://bugs.launchpad.net/cloud-init/+bug/1979877)
```
diff --git a/tests/unittests/test_net.py b/tests/unittests/test_net.py
index bfc13734..3b185509 100644
--- a/tests/unittests/test_net.py
+++ b/tests/unittests/test_net.py
@@ -13,6 +13,7 @@ import pytest
from yaml.serializer import Serializer
from cloudinit import distros, net
+from cloudinit import safeyaml
from cloudinit import safeyaml as yaml
from cloudinit import subp, temp_utils, util
from cloudinit.net import (
@@ -8276,4 +8277,24 @@ class …
```
> net: fix interface matching support

- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_landscape.py
- tests/unittests/config/test_cc_lxd.py
- tests/unittests/config/test_cc_mcollective.py
- tests/unittests/config/test_cc_users_groups.py
- tests/unittests/config/test_cc_yum_add_repo.py
```
schema: add missing additionalProperties values to schema
Unless we want to disable schema validation under a specific key,
additionalProperties should be set to false in each object. When
we want to disable checking for subschemas, we should probably 
set additionalProprties to true, just to make it clear that it was
the initial intent (and not a forgotten key).
This PR adds:
- 8 tests that fail without the accompanying schema fixes
- multiple additionalProperties definitions to object definitions
- misc format modifications for ease of auditing schema
- a spelling fix to one key
```
This work is somewhat related to https://github.com/canonical/cloud-init/pull/1532.
```
git checkout HEAD^
tox -e py3  # observe 8 failures
git checkout -
tox -e py3  # observe no failures
```
> schema: Force stricter validation (SC-1166)

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/test_azure_helper.py
- Use ElementTree instead of minidom
- Use namespaces and case sensitive names
- Decouple parsing from usage in config/metadata dictionaries
- More clearly distinguish between NonAzureDataSource() and
BrokenAzureDataSource() exceptions.  Only raise NonAzureDataSource()
exception if the `ProvisioningSection` in the windowsazure namespace
is not found. Any other parsing failures will result in
BrokenAzureDataSource() being raised.
- Streamline log messages
- Move logic into Azure helper module
There should be no effective change in behavior unless some bad XML
is in the wild and being ignored or failing silently.
> sources/azure: refactor ovf-env.xml parsing

- tests/unittests/net/test_dns.py
- tools/.github-cla-signers
This patch adds a test case for the launchpad bug below. When parsing a network configuration where a device on the system has the same mac address as given in the `match` section of the config, but with the real device name not matching the config name, parsing of a static nameserver entry fails with a `KeyError`.
LP: #1979877
> Test case for parsing static dns when device is present on system

- tox.ini
```
tox: Remove entries from default envlist
lowest-supported-dev requires running with python 3.6, which few people
will be running locally.
hypothesis-slow is being removed because fuzz testing
shouldn't be a gate for new features.
LP: #1980854
```
> tox: Remove entries from default envlist (SC-1176)

- cloudinit/config/cc_mounts.py
- tests/unittests/config/test_cc_mounts.py
- tools/.github-cla-signers
```
mounts: fix suggested_swapsize for > 64GB hosts
```
If provisioning hosts with more than 64GB of memory, swap will not be created and the following error messages will be logged by cloud-init:
```
2022-07-07 23:45:13,257 - cc_mounts.py[DEBUG]: suggest None swap for 257675.54296875 MB memory with '958841.80859375 MB' disk given max=16384.0 MB [max=16384.0 MB]'
2022-07-07 23:45:13,257 - cc_mounts.py[WARNING]: failed to setup swap: unsupported operand type(s) for /: 'NoneType' and 'int'
```
Upon inspection, this appears to be a bug in `suggested_swapsize`; I could not see a case where the existing conditional would be correct behavior, but I would like to hear from upstream in case I missed something obvious.
Attempt to provision a system with more than 64GB of RAM with the following …
> mounts: fix suggested_swapsize for > 64GB hosts

- cloudinit/analyze/__main__.py
- cloudinit/cmd/cloud_id.py
- tests/unittests/analyze/test_boot.py
- tests/unittests/analyze/test_dump.py
- tests/unittests/test_util.py
- tox.ini
```
add tox target for tracing for resource leaks, fix some leaks
```
I cleaned up a few leaks, but I'm loosing steam on this and would like to merge it as is. My original intent was to clean up all leaks which would make this more useful as a ci / jenkins job, but I have spent too much time on this already and need to move on to other things.
[resource-leak.txt](https://github.com/canonical/cloud-init/files/9023208/resource-leak.txt)
run the added tox env
> Resource leak cleanup

- config/cloud.cfg.tmpl
```
User feedback on the initial OpenMandriva support patch was that
it works great, but it's too easy to mistype the overly long
username.
Shorten it to omv -- this is also consistent with what we do
on PinePhone.
Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>
```
Unit tests and documentation aren't affected - so no need to update them as per checklist
Install OpenMandriva with patched cloud-init, ssh in as user omv, try to ssh in as user openmandriva and make sure that fails.
> Rename the openmandriva user to omv

- doc/rtd/topics/datasources/vmware.rst
updated govc command in point 7 - previous method gave the following error for govc 0.27.5
govc vm.power -vm "${VM}" -on
govc: flag provided but not defined: -vm
```
```
> Update govc command in point 7 of walkthrough

- doc/examples/cloud-config-apt.txt
- doc/examples/cloud-config-install-packages.txt
- tools/.github-cla-signers
Fix comment typo regarding use of `packages:` and relationship to `package_update:`
```
Found a small typo in the online documentation.
```
N/A
N/A
> Fix comment typo regarding use of `packages:` and relationship to `package_update:`

- cloudinit/config/cc_write_files.py
- cloudinit/config/cc_write_files_deferred.py
- cloudinit/distros/__init__.py
- cloudinit/distros/bsd.py
- cloudinit/distros/freebsd.py
- tests/unittests/config/test_cc_write_files.py
```
Don't assume root user is in root group
BSD's root user has group name "wheel" for GID 0
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265177
```
Rather than assuming that "root:root" is default user:group everywhere, move this value into the distro definitions as the default, and override this to "root:wheel" for ~~freebsd~~ BSDs.
I also added some type annotations along the way, which help us catch/prevent bugs thanks to mypy and friends.
> freebsd: Don't assume that root user is in root group

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_azure_helper.py
In preparation of adding a new tag to support, move the
current DMI chassis asset tag into an enum.  No change
in behavior should be present other than reporting.
- Create ChassisAssetTag enum for containing all Azure
DMI chassis asset tags and logic to query system for it.
- Add current DMI asset tag to enum as AZURE_CLOUD.
- Reporting: drop event frame and report valid asset tag.
- Update tests for platform viability to pytest.
> sources/azure: refactor chassis asset tag handling

- cloudinit/cmd/clean.py
- cloudinit/settings.py
- config/clean.d/README
- setup.py
- tests/unittests/cmd/test_clean.py
cloud-init clean command provides a run-parts /etc/cloud/clean.d
directory to allow third party apps to deliver supplemental cleanup
scripts to aid in golden image creation.
Any executable scripts in /etc/cloud/clean.d will be run in
lexicographical order via subp.runparts.
This aids customers creating golden images, where the typical process
an image creator performs is to reset cloud-init on that system so
the next boot of this cloned image will be treated as first-boot and
perform all early system configuration.
This PR is part of a series of improvements in cloud-init and live-installer interaction:
```
clean: allow third party cleanup scripts in /etc/cloud/clean.d
cloud-init clean command provides a run-parts /etc/cloud/clean.d
directory to allow third party apps to deliver …
```
> UC015.U1.1 clean: allow third party cleanup scripts in /etc/cloud/clean.d

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/test_azure.py
The password is still set for the default (admin) user but isn't
immediately expired as a result of this change:
https://github.com/canonical/cloud-init/pull/1577
> sources/azure: don't set cfg["password"] for default user pw

- cloudinit/config/cc_growpart.py
- cloudinit/config/cc_grub_dpkg.py
- cloudinit/config/cc_install_hotplug.py
- cloudinit/config/cc_keyboard.py
- cloudinit/config/cc_keys_to_console.py
- cloudinit/config/cc_landscape.py
- cloudinit/config/cc_locale.py
- cloudinit/config/cc_lxd.py
- cloudinit/config/cc_mcollective.py
- cloudinit/config/cc_migrator.py
- cloudinit/config/cc_mounts.py
- cloudinit/config/cc_ntp.py
```
config: Def activate_by_schema_keys for g-n mods
```
SC-1133
Merge #1609
> config: Def activate_by_schema_keys for g-n mods

- tests/unittests/sources/test_azure.py
Split tests for parsing/converting network config from network_config.
> sources/azure: reorganize tests for network config

- cloudinit/config/cc_apk_configure.py
- cloudinit/config/cc_apt_configure.py
- cloudinit/config/cc_apt_pipelining.py
- cloudinit/config/cc_bootcmd.py
- cloudinit/config/cc_byobu.py
- cloudinit/config/cc_ca_certs.py
- cloudinit/config/cc_chef.py
- cloudinit/config/cc_debug.py
- cloudinit/config/cc_disable_ec2_metadata.py
- cloudinit/config/cc_disk_setup.py
- cloudinit/config/cc_fan.py
- cloudinit/config/cc_final_message.py
```
config: Def `activate_by_schema_keys` for a-f mods
```
SC-1133
Merge #1609
> config: Def `activate_by_schema_keys` for a-f mods

- cloudinit/cmd/clean.py
- doc/rtd/topics/cli.rst
- doc/rtd/topics/datasources/vmware.rst
- tests/unittests/cmd/test_clean.py
```
clean: add param to remove /etc/machine-id for golden image creation
Typically when a cloud-image boots /etc/machine-id should be
auto-generated if /etc/machine-id does not exist. Some cloud images
appropriately generate /etc/machine-id if the image is recognized
as a clone, in most other cases it is a best practice to remove
/etc/machine-id and let DBUS or systemd do the work of generating
a new UUID on next boot so the cloned VMs are represented
uniquely to any monitoring/management software.
```
US015.UC01.2: subiquity/cloud-init spec, golden image support: ability to clean machine-id from golden image
> cloud-init clean --machine-id

- cloudinit/config/cc_timezone.py
- cloudinit/config/cc_ubuntu_advantage.py
- cloudinit/config/cc_ubuntu_autoinstall.py
- cloudinit/config/cc_ubuntu_drivers.py
- cloudinit/config/cc_update_etc_hosts.py
- cloudinit/config/cc_update_hostname.py
- cloudinit/config/cc_users_groups.py
- cloudinit/config/cc_write_files.py
- cloudinit/config/cc_write_files_deferred.py
- cloudinit/config/cc_yum_add_repo.py
- cloudinit/config/cc_zypper_add_repo.py
```
config: Def activate_by_schema_keys for t-z mods
```
SC-1133
SC-1203
Merge #1609
> config: Def activate_by_schema_keys for t-z

- cloudinit/config/cc_lxd.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/integration_tests/modules/test_lxd_bridge.py
- tests/unittests/config/test_cc_lxd.py
```
lxd: enable MTU configuration in cloud-init
This option exists in LXD already. Plumb the options
without changing default behavior.
```
depends on https://github.com/canonical/cloud-init/pull/1621
> LXD Add MTU Support

- CONTRIBUTING.rst
```
docs: Align git remotes with uss-tableflip setup
`uss-tableflip/scripts/upstream-release` assumes Canonical remote is 
called `upstream` and your personal remote `origin`.
Fix upstream git URI.
```
https://github.com/canonical/uss-tableflip/blob/e8528bcfdc3fdb28cdf0c4f4b434c47f57aec6b6/doc/upstream_release_process.md?plain=1#L5
> docs: Align git remotes with uss-tableflip setup

- cloudinit/cmd/devel/hotplug_hook.py
- cloudinit/distros/__init__.py
- cloudinit/net/activators.py
- config/cloud.cfg.tmpl
- doc/rtd/topics/network-config.rst
- tests/unittests/cmd/devel/test_hotplug_hook.py
- tests/unittests/distros/test_netconfig.py
- tests/unittests/test_net_activators.py
```
Support overriding network activators in cloud.cfg system_info
on disk.
Default cloud-init activators are used either during hot-plug or
for datasources that are detected during init-network stage when
basic networking has already been setup by the OS.a
Activators are discovered in the following priority order and
determined based on the presence of related network tools:
system_info:
network:
activators: [eni, netplan, network-manager, networkd]
On some systems where multiple network config tools are installed
it is necessary to override the priority order of detection to ensure
one activator is chosen over the other. This is done by providing
the a custom cloud config snippet in a /etc/cloud/cloud.cfg.d/*cfg.
LP: #1958377
```
Also related to ubuntu-desktop-installer [LP …
> network: add system_info network activator cloud.cfg overrides

- integration-requirements.txt
- tests/integration_tests/bugs/test_lp1835584.py
- tests/integration_tests/clouds.py
- tests/integration_tests/conftest.py
- tox.ini
```
testing: add support for pycloudlib's pro images
Added new pytest marker to define IntegrationCloud customizations.
Migrate test_lp1835584 to use this functionality.
Bump pycloudlib version.
```
SC-1148
```sh
$ tox -e integration-tests -- tests/integration_test/bugs/test_lp1835584.py::test_azure_kernel_upgrade_case_insensitive_uuid
...
image_id=Canonical:0001-com-ubuntu-pro-bionic-fips:pro-fips-18_04
...
```
> testing: add support for pycloudlib's pro images

- debian/changelog
- debian/patches/renderer-do-not-prefer-netplan.patch
Daily recipe builds for bionic broke due to `quilt push -a` not being able to apply any more due drift in tip of main introduced by commit 6e498773bf153f7b2f5e995a2f2fe24774dd3cab
Performed steps documented here https://github.com/canonical/uss-tableflip/blob/main/doc/ubuntu_release_process.md#when-the-daily-recipe-build-fails
* update changelog
* d/patches/renderer-do-not-prefer-netplan refresh to activators change
```
git clone git@github.com:canonical/cloud-init.git -r upstream
cd cloud-init
git merge origin/ubuntu/bionic
quilt push -a # ensure no failure applying patches
tox -e py3   # ensure no failure in unit tests
quilt pop -a
```
> Ubuntu/bionic: refresh bionic patches to fix daily recipe build

- tests/integration_tests/modules/test_ca_certs.py
```
testing: Fix test_ca_certs integration test
```
After the inclusion of https://github.com/canonical/cloud-init/pull/1609, some Jenkins' jobs fail:
[cloud-init-integration-bionic-azure/68](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-azure/68/)
[cloud-init-integration-bionic-gce/65](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-gce/65/)
[cloud-init-integration-bionic-lxd_vm/67](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-lxd_vm/67/)
[cloud-init-integration-focal-azure/65](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-azure/65/)
[cloud-init-integration-focal-gce/70](https://jenkins.canonical.com/server-te …
> testing: Fix test_ca_certs integration test

- cloudinit/config/schema.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_power_state_change.py
- tests/unittests/config/test_schema.py
Order deprecated sub schema property descriptions after
any active descriptions.
Add trailing stop for descriptions in docs is absent.
For readability, preface any deprecated sub-schema properties with
DEPRECATED:
SC-1175
```
Order deprecated sub schema property descriptions after
any active descriptions.
Add trailing stop for descriptions in docs is absent.
For readability, preface any deprecated sub-schema properties with
DEPRECATED:
SC-1175
```
> schema: add aggregate descriptions in anyOf/oneOf

- cloudinit/distros/parsers/sys_conf.py
- tools/.github-cla-signers
```
Remove configobj _a_to_u() calls
configobj upstream removed it in
https://github.com/DiffSK/configobj/commit/7b07952dc599fb00d2dd2b5a1c1d1ec19d720132
In this case it should be a no-op on Python 3
Paving the way to resolve https://bugs.debian.org/1016467
```
> Remove configobj a_to_u calls

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
sources/azure: add experimental support for preprovisioned os disks
Some pre-provisioning scenarios require that the VM be started and
shut back down as part of preparing the VM for future use.
When the PPS type is PreprovisionedOSDisk, report ready and wait for
host to shut down the VM.
Provisioning will resume normally on next boot, so do not write
a reported ready marker file.
> sources/azure: add experimental support for preprovisioned os disks

- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_set_passwords.py
```
schema: Enable deprecations in cc_set_passwords
```
SC-1173
> schema: Enable deprecations in cc_set_passwords

- cloudinit/ssh_util.py
- packages/debian/cloud-init.postrm
- tests/integration_tests/modules/test_set_password.py
- tests/integration_tests/modules/test_ssh_keys_provided.py
- tests/unittests/config/test_cc_ssh.py
- tests/unittests/test_ssh_util.py
```
ssh_util: Handle sshd_config.d folder
Write sshd config to /etc/ssh/sshd_config.d/00-cloud-init.conf
if the sshd_config sources sshd_config.d
LP: #1968873
```
SC-1172
LP: #1968873
In order to ease upgrading `openssh-server`, write out sshd_config
into a separated `cloud-init` conf file with high priority under
`/etc/ssh/sshd_config.d/00-cloud-init.conf`.
This fixes #1968873 in `main` and will be SRUed to `focal`, `impish`
and `focal`.
```sh
cat <<EOF > /tmp/user-data
#cloud-config
ssh_pwauth: true
password: asdf
EOF
lxc launch ubuntu:focal ff --config=user.user-data="$(cat /tmp/user-data)"
lxc exec ff -- cloud-init status --wait
$ lxc exec ff -- grep -rn 'PasswordAuthentication ' /etc/ssh/sshd_config /etc/ssh/sshd_config.d
/etc/ssh/sshd_config:58:PasswordAuthentication no …
```
> ssh_util: Handle sshd_config.d folder

- cloudinit/sources/helpers/azure.py
- cloudinit/url_helper.py
```
typing: Type UrlResponse.contents
As requests.Response.contents returns always an instance of bytes,
type UrlResponse.contents accordingly.
This change undercovered an incorrect typing in
sources/helpers/azure, that was hidden because
ElementTree.fromstring accepts str and bytes.
```
https://github.com/canonical/cloud-init/pull/1606#discussion_r934791692
> typing: Type UrlResponse.contents

- integration-requirements.txt
- tests/integration_tests/modules/test_ca_certs.py
```
tests: can run without azure-cli, tests expect inactive ansible
Bump pycloud version to include fixes so Azure tests can run on VMs
without an azure-cli installed.
```
Related jenkins failure https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-kinetic-ec2/55/testReport/junit/tests.integration_tests.modules.test_ca_certs/TestCaCerts/test_clean_log/
```bash
CLOUD_INIT_PLATFORM=lxd_container CLOUD_INIT_OS_IMAGE=kinetic CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily tox -e integration-tests ./tests/integration_tests/modules/test_ca_certs.py::TestCaCerts::test_clean_log
```
> tests: fix integrate test to expect ansible inactive without user-data

- tests/unittests/config/test_apt_configure_sources_list_v1.py
- tox.ini
```
tox: Fix tip-flake8 and tip-mypy
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-style-tip/113/
```bash
tox -e tip-flake8,tip-mypy
```
> tox: Fix tip-flake8 and tip-mypy

- tests/unittests/config/test_cc_ssh.py
- tests/unittests/conftest.py
```
test: use fake filesystem to avoid file removal
```
https://github.com/canonical/cloud-init/pull/1646
```
sudo touch /etc/ssh/ssh_host_a_key_b
sudo chown root:root /etc/ssh/ssh_host_a_key_b
sudo chmod 700 /etc/ssh/ssh_host_a_key_b
tox -e py3
./package/bddeb -d
```
> test: use fake filesystem to avoid file removal

- cloudinit/config/schema.py
- tests/unittests/config/test_apt_source_v1.py
- tests/unittests/config/test_apt_source_v3.py
- tests/unittests/config/test_schema.py
- tests/unittests/test_data.py
- tests/unittests/test_stages.py
- tests/unittests/util.py
```
schema: Resolve user-data if --system given
Validated the processed/rendered userdata instead of "userdata_raw"
so that `sudo cloud-init schema --system` provides a concise
error about what the procesed invalid user-data is.
LP: #1983306
```
SC-1215
```bash
mkdir -p /tmp/instance-data
cat > /tmp/instance-data/user-data <<EOF
#cloud-config
runcmd:
- touch /root/hello.txt
EOF
cat > /tmp/instance-data/script.sh <<EOF
#!/bin/sh
touch /root/bye.txt
EOF
python -m cloudinit.cmd.main devel make-mime -a /tmp/instance-data/user-data:cloud-config -a /tmp/instance-data/script.sh:x-shellscript > /tmp/instance-data/userdata
gzip -f /tmp/instance-data/userdata
cd /tmp/instance-data && python3 -m http.server &
cat > /tmp/include.yaml <<EOF
#include http://0.0.0.0:8000/userdata.gz
EOF
lxc init …
```
> schema: Resolve user-data if --system given

- cloudinit/config/cc_set_hostname.py
```
Return cc_set_hostname to PER_INSTANCE frequency
In 96eb95a the frequency was inadvertently changed to ALWAYS due to
the documentation being incorrect. The code and documentation should
now align to be PER_INSTANCE.
LP: #1983811
```
> Return cc_set_hostname to PER_INSTANCE frequency (SC-1222)

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_azure_helper.py
Upon reporting ready for Savable PPS, the VM may be suspended before
we see the http request complete.  When the VM resumes,
http_with_retries will keep retrying even though it sees
"Network is unreachable" errors due to the unplugged NIC (and
perhaps a new unconfigured one) or "Read timed out" raised.
- Do not retry when "Network is unreachable", this will not
resolve itself in any case.
- Ignore all url errors for Savable PPS.  Worst case scenario is
we failed to report ready anyways (for whatever reason) and the
source PPS VM will soon be discarded.
> sources/azure: handle network unreachable errors for savable PPS

- cloudinit/config/cc_ntp.py
- templates/chrony.conf.centos.tmpl
- tools/.github-cla-signers
This patch fixes the service names of Chrony and NTP on Centos Stream and also
adds a template for chrony by re-using the one of RHEL.
LP: #1885952
Signed-off-by: Sven Haardiek <sven.haardiek@uni-muenster.de>
> Fix Chrony usage on Centos Stream

- cloudinit/net/netplan.py
```
Workaround net_setup_link race with udev
LP: #1983516
```
https://bugs.launchpad.net/cloud-init/+bug/1983516
> Workaround net_setup_link race with udev

- tests/unittests/reporting/test_webhook_handler.py
```
Prevent concurrency issue in test_webhook_hander.py
There were very occassionally failures seen in
test_multiple_failures_no_flush, likely due to the background thread not
having enough CPU time. Reduce background thread load and add short
sleep in main loop to fix issue.
```
I haven't been able to intentionally reproduce this bug, but I have seen it a few times in the past couple of months.
One such error:
```
@responses.activate
def test_multiple_failures_no_flush(self, caplog):
"""Test we don't cancel posting if flush hasn't been requested.
Since processing happens in the background, wait in a loop
for all messages to be posted
"""
responses.add(responses.POST, "http://localhost", status=404)
for _ in range(20):
report_start_event("name", "description")
start_time = time.time() …
```
> Prevent concurrency issue in test_webhook_hander.py

- tests/integration_tests/modules/test_ansible.py
- tests/integration_tests/util.py
```
tests: ansible test fixes
Fixed:
1. git update-server-info needs to be called from .git
2. the service needs to be up and running before ansible-pull runs
3. Ansible prints warnings that we should ignore
Add a service that blocks cloud-final until the repo can be cloned.
```
> tests: ansible test fixes

- tests/integration_tests/bugs/test_lp1835584.py
- tests/integration_tests/conftest.py
```
integration tests: Ensure one image for all tests
In bccf9a5, integration test setup was inadvertently changed to force
image setup for every test. Revert that behavior back.
```
Haven't fully tested things yet, but wanted to get it available sooner rather than later.
> integration tests: Ensure one image for all tests

- .github/workflows/check_format.yml
```
ci: Bump format tests runner to focal
https://github.com/actions/runner-images/issues/6002
```
you may have noticed the following deprecation warning in CI:
```
Lint Tests: .github#L1
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
```
see https://github.com/actions/runner-images/issues/6002
> Github is deprecating the 18.04 runner starting 12.1

- cloudinit/cmd/main.py
- cloudinit/sources/__init__.py
- cloudinit/stages.py
- tests/unittests/sources/test_init.py
- tests/unittests/test_upgrade.py
Related to PR https://github.com/canonical/cloud-init/pull/1667. We really want to persist this obj.pkl when get_data runs and we are persisting instance-data.json files. No sense in keeping those syncs to disk separate.
```
sources: obj.pkl cache should be written when get_data is run
When metadata update events trigger a new datasource.get_data run
ensure we are syncing the cached obj.pkl to disk so subsequent
boot stages can leverage the updated metadata.
Add write_cache param to persist_instance_data to avoid
persisting instance data when init.ds_restored from cache.
This avoids a race on clouds where network config is updated
per boot in init-local timeframe but init-network uses stale network
metadata from cache because updated metadata was not
persisted.
Migate _pkl_load and …
```
> sources: obj.pkl cache should be written when get_data is run

- packages/redhat/cloud-init.spec.in
- packages/suse/cloud-init.spec.in
COPR build failures because cloud-init packages a new /etc/cloud/clean.d directory but didn't list in the spec.
```
RPM build errors:
Installed (but unpackaged) file(s) found:
/etc/cloud/clean.d/README
```
[Failed COPR build logs](https://download.copr.fedorainfracloud.org/results/@cloud-init/el-testing/epel-8-x86_64/04750679-cloud-init/builder-live.log.gz)
```
rpm/copr: ensure RPM represents new clean.d dir artifacts
```
> rpm/copr: ensure RPM represents new clean.d dir artifacts

- debian/changelog
Any release to a stable Ubuntu series should not have upsream LP bug references because we file an SRU exception bug to handle all validation of such bugs through CI, jenkins tests and manual verification. Our uss-tableflip/scripts/new-upstream-snapshot should have redacted this for us on these branches automatically. So something is amiss on these PRs.
Here's a manual fix of debian/changelog. And we can sort whatever tooling needed to change separately.
```
changelog: redact LP bug numbers on stable release
```
> changelog: redact LP bug numbers on stable release

- cloudinit/sources/DataSourceVMware.py
- tests/unittests/sources/test_vmware.py
```
DataSourceVMware: fix var use before init
This patch fixes an issue in the DataSourceVMware code where the
variable ipv6_ready was used in a logging statement before it was
initialized. Now the variable is initialized, avoiding the panic.
LP: #1987005
```
I reproduced the bug by:
* applying the following patch to move the logging statement into a position where it would always be executed:
```diff
diff --git a/cloudinit/sources/DataSourceVMware.py b/cloudinit/sources/DataSourceVMware.py
index 80a01e89..b2a54d0b 100644
--- a/cloudinit/sources/DataSourceVMware.py
+++ b/cloudinit/sources/DataSourceVMware.py
@@ -822,6 +822,14 @@ def wait_on_network(metadata):
if not ipv6_ready:
host_info = None
+        LOG.debug(
+            "waiting on network: wait4=%s, ready4=%s, wait6=%s, …
```
> DataSourceVMware: fix var use before init

- cloudinit/net/network_manager.py
- tests/unittests/test_net.py
```
This problem is found after below bug fix, ipv6 is not workable after launching a new instance.
[Bug 2056964](https://bugzilla.redhat.com/show_bug.cgi?id=2056964) - [RHEL-9]Rebase cloud-init from Fedora so it can configure networking using NM keyfiles
we can see log "Not bringing up newly configured network interfaces" in /var/log/cloud-init.log
2022-06-17 02:15:22,191 - __init__.py[DEBUG]: Selected renderer 'network-manager' from priority list: ['netplan', 'network-manager', 'networkd', 'sysconfig', 'eni']
2022-06-17 02:15:22,192 - util.py[DEBUG]: Writing to /etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection - wb: [600] 376 bytes
2022-06-17 02:15:22,193 - util.py[DEBUG]: Restoring selinux mode for /etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection …
```
> network-manager: ipv6 connection does not work on Azure and Openstack

- cloudinit/cmd/devel/net_convert.py
- cloudinit/distros/__init__.py
- cloudinit/distros/arch.py
- cloudinit/distros/debian.py
- cloudinit/net/bsd.py
- cloudinit/net/eni.py
- cloudinit/net/netplan.py
- cloudinit/net/network_manager.py
- cloudinit/net/network_state.py
- cloudinit/net/networkd.py
- cloudinit/net/renderer.py
- cloudinit/net/sysconfig.py
- tests/unittests/cmd/devel/test_net_convert.py
- tests/unittests/distros/test_netconfig.py
- tests/unittests/net/test_network_state.py
```
net: Passthough v2 raw net_conf in netplan systems
Adhere to Netplan Passthrough documented behavior,
not limiting v2 netplan configs to the subset of
props that cloud-init supports.
LP: #1978543
```
SC-1120
https://bugs.launchpad.net/cloud-init/+bug/1978543
[Netplan Passthrough](https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#netplan-passthrough)
```bash
cat > /tmp/lp1978543.yaml <<EOF
network:
version: 2
ethernets:
enp0s3:
dhcp4: false
addresses: [10.0.4.10/24]
nameservers:
addresses: [10.0.4.1]
routes:
- to: default
via: 10.0.4.1
metric: 100
EOF
lxc init ubuntu-daily:jammy lp1978543
lxc file push /tmp/lp1978543.yaml lp1978543/etc/cloud/cloud.cfg.d/custom-networking.cfg
lxc file push /tmp/lp1978543.yaml lp1978543/root/
lxc start lp1978543
lxc exec …
```
> net: Passthough v2 netconfigs in netplan systems

- Makefile
```
make: drop broken targets
```
These targets appear to be unneeded:
```bash
isa~/cloud-init-c(holmanb/drop-broken-make-targets|…) rg pip-requirements
isa~/cloud-init-c(holmanb/drop-broken-make-targets|…) rg pip-test-requirements
isa~/cloud-init-c(holmanb/drop-broken-make-targets|…) grep PIP_INSTALL Makefile    
isa~/cloud-init-c(holmanb/drop-broken-make-targets|…)  
```
These targets were broken when they were originally added in https://github.com/canonical/cloud-init/commit/b2ebae64a7b9738db6c6408cee4adc2bf2f17:
```bash
isa~/cloud-init-c(holmanb/drop-broken-make-targets|…) git checkout b2ebae64a7b9738db6c6408cee4adc2bf2f17 
Note: switching to 'b2ebae64a7b9738db6c6408cee4adc2bf2f17'.
<snip>
isa~/cloud-init-c(:b2ebae64|…) make pip-test-requirements
Installing cloud-init test …
```
> make: drop broken targets

- cloudinit/net/networkd.py
- tests/unittests/net/test_networkd.py
- tests/unittests/test_net.py
- tools/.github-cla-signers
Networkd multi-address support/fix
```
Given a cloud-init network config with multiple addresses for an interface the networkd backend outputs an invalid networkd service config. According to the `man` page of `systemd-networkd` only one `Address=` field per `[Address]` section is allowed.
```
[Ref: https://www.freedesktop.org/software/systemd/man/systemd.network.html#Address=1](https://www.freedesktop.org/software/systemd/man/systemd.network.html#Address=1)
[Ref: https://man.archlinux.org/man/systemd.network.5#%5BADDRESS%5D_SECTION_OPTIONS](https://man.archlinux.org/man/systemd.network.5#%5BADDRESS%5D_SECTION_OPTIONS)
Older versions of `cloud-init` (e.g 19.4) output a valid config.
File location: `/etc/systemd/network/`
The invalid config leads to only one of the IPs being configured for …
> Networkd multi-address support/fix

- tests/integration_tests/modules/test_ansible.py
```
test: make ansible test compatible with old versions
- python http.server: drop --directory arg
- systemd: use absolute paths with ExecStart=
Additionally make git repo setup more robust and improve output
during error condition.
```
Bionic Output
=============
`man systemd.service`:
```bash
<snip>
For each of the specified commands, the first argument must be an absolute path to an executable. Optionally, this filename may be prefixed with a number of
special characters:
<snip>
```
`http.server` has no directory arg (added in 3.7):
```
~# python3 -m http.server --help
usage: server.py [-h] [--cgi] [--bind ADDRESS] [port]
positional arguments:
port                  Specify alternate port [default: 8000]
optional arguments:
-h, --help            show this help message and exit
--cgi …
```
> test: make ansible test work across older versions

- tests/integration_tests/modules/test_combined.py
```
test: reduce number of required http endpoints in flaky test
This should help with Github rate limiting.
```
This test has always been flaky for reasons outside of our control. Maybe long term it doesn't deserve ci coverage? Current theory is we are getting rate limited by Github (local testing git hit by rate limiting pretty quickly).
```
E           assert ['(\'ssh-import-id\', ProcessExecutionError("Unexpected error while running '\n "command.\\nCommand: ['sudo', '--preserve-env=https_proxy', '-Hu', 'ubuntu', "\n "'ssh-import-id', 'gh:powersj', 'lp:smoser']\\nExit code: 1\\nReason: "\n '-\\nStdout: -\\nStderr: -"))'] == []
E             Left contains one more item: '(\'ssh-import-id\', ProcessExecutionError("Unexpected error while running command.\\nCommand: [\'sudo\', …
```
> test: reduce number of network dependencies in flaky test

- doc/rtd/topics/faq.rst
```
doc: add reporting suggestion to docs
```
External scripts waiting on cloud-init leads to bug reports that relate to cloud-init only symptomatically. Lets document how users can make better reports in the faq.
(open to suggestions if we want to list more commands to report on)
> doc: add reporting suggestion to docs (SC-1236)

- tests/integration_tests/modules/test_combined.py
```
testing: Fix test regression in test_combined
```
After https://github.com/canonical/cloud-init/pull/1702 -> https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-azure/89/ fails.
> testing: Fix test regression in test_combined

- tools/read-version
```
When creating a release branch with uss-tableflip/upstream-release
the branch name created is upstream/XX.YY.
If the current branch name is of that format, we should trust the
version defined in version.py as valid and avoid strict checks.
This branch adapts our branch name check for two cases:
1. We recently migrated CI format tests from Travis to github actions.
Use GITHUB_REF environment variable instead of TRAVIS_PULL_REQUEST_BRANCH
2. local branches on developer machines will be named upstream/XX.YY.
Use git branch --show-current to check if we are on such a branch
```
WIP branch proposed faking upstream/22.4 release https://github.com/canonical/cloud-init/pull/1678 which tests these tooling changes to ensure github actions pass on version checks
```
$ ./tools/read-version
22.3
$ …
```
> tools: read-version check GITHUB_REF and git branch --show-current

- cloudinit/cmd/cloud_id.py
- cloudinit/cmd/devel/logs.py
- cloudinit/cmd/devel/render.py
- cloudinit/cmd/main.py
- cloudinit/cmd/query.py
- cloudinit/handlers/jinja_template.py
- cloudinit/helpers.py
- cloudinit/sources/__init__.py
- tests/unittests/cmd/devel/test_logs.py
- tests/unittests/cmd/devel/test_render.py
- tests/unittests/cmd/test_query.py
- tests/unittests/sources/test_init.py
```
Refactor instance json files to use Paths
We have multiple areas of the codebase where we fetch the rundir path
and join it with the filename for instance-data.json or
instance-data-sensitive.json. This commit refactors those calls to use a
'Paths' lookup instead.
```
In a separate task I was adding a call to instance-data-sensitive.json and decided to refactor this first.
> Refactor instance json files to use Paths (SC-1238)

- cloudinit/apport.py
- cloudinit/sources/DataSourceEc2.py
- cloudinit/sources/helpers/ec2.py
- doc/rtd/topics/availability.rst
- tests/unittests/sources/helpers/test_ec2.py
- tests/unittests/sources/test_ec2.py
- tests/unittests/test_ds_identify.py
- tools/.github-cla-signers
- tools/ds-identify
Hello 👋,
This PR is to add the DataSource of 3DS Outscale. To help you review this PR here what we have done. 
The datasource is based EC2 datasource but with one big difference : the retrieval of ` tags`. Indeed, in the meta-data server, in the tags section, we (3DS Outscale) accept all characters and this can lead to cloud-init crash during the retrieval of meta-data. AWS does not have this problem because if the tags are in the meta-data server, only a set of [characters is available ](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions).
Instead of duplicating the code and fix the behavior for our need, we think it would be better to handle this directly in the ec2 helpers. Therefore we have added the ability to skip some element in the meta-data …
> Add 3DS Outscale Datasource

- tests/unittests/config/test_cc_puppet.py
- tests/unittests/net/test_dhcp.py
- tests/unittests/sources/test_azure.py
- tests/unittests/test_temp_utils.py
```
testing: fully mock noexec calls
Mock calls to `utils.has_mount_opt` and `Distro.get_tmp_exe_dir`.
```
After merging https://github.com/canonical/cloud-init/pull/1690, our daily builds show that we are not fully mocking everything while unit-testing:
- https://code.launchpad.net/~cloud-init-dev/+archive/ubuntu/daily/+build/24334448
- https://code.launchpad.net/~cloud-init-dev/+archive/ubuntu/daily/+build/24334437
- https://code.launchpad.net/~cloud-init-dev/+archive/ubuntu/daily/+build/24334441
- https://code.launchpad.net/~cloud-init-dev/+archive/ubuntu/daily/+build/24334444
> testing: fully mock noexec calls

- .readthedocs.yaml
- .travis.yml
```
doc: Fix rtd builds
tools/read-version uses `git branch --show-current`,
--show-current was intruduced in git-2.22.0 and the default
rtd build runners seem to be on bionic, which contains git-2.17.1.
Define build.os as jammy in rtd and align python version in travis.
```
* https://warthogs.atlassian.net/browse/SC-1247
* Failed build: https://readthedocs.org/projects/cloudinit/builds/17973660/
* `tools/read-version` change: https://github.com/canonical/cloud-init/pull/1677
* [rtd - reproducible-builds](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#don-t-rely-on-implicit-dependencies)
* [Git versions across all Ubuntu series](https://packages.ubuntu.com/search?keywords=git&searchon=names&suite=all&section=all)
```bash
SERIES=bionic
NAME=docs
lxc delete -f $NAME > …
```
> doc: Fix rtd builds

- cloudinit/sources/DataSourceLXD.py
- tests/unittests/sources/test_lxd.py
```
lxd: fetch 1.0/devices content
cloud-init awareness of 1.0/devices content will allow
DataSourceLXD to properly limit opt-in hotplug event-handling to
specific udev events based on device instead of just network type.
As devices content is not used atm, a param was added to
read_metadata to control its fetching (defaulting to False).
Note: read_metadata was refactored to try to reduce cyclotomatic
complexity.
```
SC-608
> lxd: fetch 1.0/devices content

- cloudinit/config/cc_ubuntu_advantage.py
- tests/unittests/config/test_cc_ubuntu_advantage.py
```
Ubuntu Advantage: Improved idempotency
Ubuntu Advantage module is now capable of detecting already
activated subscriptions or/and enabled services. Furthermore,
when "enable" parameter is set, no "default" services
will be enabled anymore.
```
If `instance-id` changes due to updated user or meta-data, cloud-init
will run again and UA causes an error when a machine has an already
attached subscription and/or service.
Ubuntu Advantage is now capable of ignoring the following messages:
```
Stderr: This machine is already attached to 'X'
To use a different subscription first run: sudo ua detach.
Stdout: One moment, checking your subscription first
<Service> is already enabled.
See: sudo ua status
```
The module won't set cloud-init status to error when 
detecting those messages. …
> Improve Ubuntu Advantage module's idempotency

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
Currently, get_instance_id() assumes that the instance ID is in the metadata.  If not found, it falls back to a hardcoded string "iid-datasource".
Override this behavior to query the instance id as needed.
> sources/azure: ensure instance id is always correct

- cloudinit/cmd/devel/render.py
- cloudinit/config/cc_phone_home.py
- cloudinit/handlers/jinja_template.py
- cloudinit/stages.py
- cloudinit/util.py
- tests/integration_tests/modules/test_jinja_templating.py
- tests/unittests/cmd/devel/test_render.py
- tests/unittests/test_builtin_handlers.py
- tests/unittests/test_data.py
- tests/unittests/test_util.py
```
Allow jinja templating in /etc/cloud
There have been multiple requests to allow jinja templating in
/etc/cloud configs the same way we allow jinja templating in vendordata
and userdata. This commit allows for templating both
/etc/cloud/cloud.cfg and any file in /etc/cloud/cloud.cfg.d. The same
instance data used for substitution in vendordata and userdata will be
used here.
Note that these configs get loaded multiple times during the lifetime
of cloud-init, and during cloud-init's earlier loads, instance data
is not yet available.
LP: #1913461
```
There's little documentation about how our configuration gets loaded and overlaid, so there's really any documentation to be updated. We have a separate ticket for clarifying docs around /etc/cloud, and I think the changes here can be …
> Allow jinja templating in /etc/cloud (SC-1170)

- tests/unittests/helpers.py
```
tests: Simplify does_not_raise
With this the backtraces during an exception within a does_not_raise
context are more simple and easy to read.
```
Apply the following diff:
```diff
diff --git a/tests/unittests/test__init__.py b/tests/unittests/test__init__.py
index 44a06b2cd..78b4563a0 100644
--- a/tests/unittests/test__init__.py
+++ b/tests/unittests/test__init__.py
@@ -9,7 +9,12 @@ import pytest
from cloudinit import handlers, helpers, settings, url_helper, util
from cloudinit.cmd import main
-from tests.unittests.helpers import ExitStack, TestCase, mock
+from tests.unittests.helpers import ExitStack, TestCase, does_not_raise, mock
+
+
+def test_division():
+    with does_not_raise():
+        assert (1 / 0) is not None
class FakeModule(handlers.Handler):
```
and run `pytest -vv …
> tests: Simplify does_not_raise

- cloudinit/cmd/cloud_id.py
- cloudinit/cmd/status.py
- doc/rtd/topics/boot.rst
- doc/rtd/topics/cli.rst
- tests/unittests/cmd/test_cloud_id.py
- tests/unittests/cmd/test_status.py
```
cli: status machine-readable output --format yaml/json
Provide --format option for cloud-init status and cloud-id to
surface machine-readable output and detailed boot_status_codes.
Add a `_schema_version` key to the JSON status output to represent
whether a schema version has been incremented due to incompatibility.
Preserve a static `schemas`:`1` key which contains a copy of status
version 1 output which will be preserved even if the default
`_schema_version` is incremented.
Provide new boot_code_code values in json/yaml output
which will surface unique codes for the current disabled
status reasons which gives visibility to whether cloud-init
may become active on next boot or later in the current boot.
The boot-status-code can be:
- 'unknown': systemd generators and ds-identify …
```
> cli: status machine-readable output --format yaml/json

- cloudinit/net/dhcp.py
- tests/unittests/net/test_dhcp.py
```
net: set dhclient lease and pid files
This commit drops the sandboxing requirement by
invoking dhclient using pid and lease files that
apparmor already allows[1].
This is desirable as relocating the dhclient binary
has led to some bug fixes[2].
[1] dhclient's apparmor profile allow writing to:
/{,var/}run/dhclient*.pid lrw,
/{,var/}run/dhclient*.lease* lrw,
[2] fix hashes:
db86753f81af
919e22dc1d77
```
<details>
<summary>I have been testing locally in LXD on jammy by forcing a call to dhclient during init-local (patch and logs in the dropdown).
</summary>
<br>
```
diff --git a/cloudinit/sources/DataSourceLXD.py b/cloudinit/sources/DataSourceLXD.py
index 34e4e00eb..a76c4cda0 100644
--- a/cloudinit/sources/DataSourceLXD.py
+++ b/cloudinit/sources/DataSourceLXD.py
@@ -24,6 +24,7 @@ from …
```
> net: set dhclient lease and pid files

- doc/rtd/topics/datasources/nocloud.rst
```
NoCloud docs: make sure echo properly evaluates the string
Not all `echo`s evaluate "strings" by default
but adding `-e` usually helps.
```
I tried to get the example working and it didn't, with my shell.
> NoCloud docs: make sure echo properly evaluates the string

- cloudinit/config/cc_ubuntu_advantage.py
- tests/unittests/config/test_cc_ubuntu_advantage.py
```
cc_ubuntu_advantage: Redact token
```
https://github.com/canonical/cloud-init/pull/1583#issuecomment-1245294551
> cc_ubuntu_advantage: Redact token

- tests/integration_tests/datasources/test_lxd_discovery.py
```
testing: focal lxd datasource discovery
Stop identifying focal as NoCloud.
```
Missed one...
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-lxd_container/103/testReport/tests.integration_tests.datasources/test_lxd_discovery/test_lxd_datasource_discovery/
> testing: focal lxd datasource discovery (SC-1256)

- cloudinit/sources/DataSourceOracle.py
- tests/unittests/sources/test_oracle.py
```
Fix Oracle DS not setting subnet when using IMDS
Previous to 6270b50, if iSCSI config was not available, we used the
ephemeral DHCP4 address as the primary address on Oracle. After
6270b50, we instead used the IMDS address configuration. However, the
parsing of IMDS ignored the "subnetCidrBlock" field, causing the
resulting network config to have the wrong subnet.
LP: #1989686
```
Unfortunately, I have no good way of integration testing this as I don't know how to launch an instance with iSCSI disabled (I asked on the bug if the submitter could provide their launch details).
As a workaround, I applied the following patch:
```diff
diff --git a/cloudinit/sources/DataSourceOracle.py b/cloudinit/sources/DataSourceOracle.py
index 6a684e353..fa10cc6c3 100644
--- …
```
> Fix Oracle DS not setting subnet when using IMDS

- cloudinit/config/cc_ubuntu_advantage.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- pyproject.toml
- tests/integration_tests/clouds.py
- tests/integration_tests/modules/test_ubuntu_advantage.py
- tests/unittests/config/test_cc_ubuntu_advantage.py
```
cc_ubuntu_advantage: Implement custom auto-attach behaviors
Previously, ua auto-attach was performed in Ubuntu Pro images
transparently for cloud-init. Offering no configurability options
for cloud-init users.
Extend the `ubuntu_advantage` cloud-cfg section to include
`features.disable_auto_attach` and `enable_beta`.
Integrate new UA apis to detect pro instances and perform 
auto-attach if ua config is given.
The client can configure what non-beta and beta services will be enabled.
This config can be provided via:
- user-data allowing customers to configure auto-attach.
- A conf file under /etc/cloud/cloud.cfg.d allowing resellers to create 
ua-preconfigured golden images.
In the case that the ubuntu-advantage-client version is older than
the one containing the required apis, …
```
> cc_ubuntu_advantage: Implement custom auto-attach behaviors

- conftest.py
- pyproject.toml
- test-requirements.txt
- tests/unittests/config/test_cc_chef.py
- tests/unittests/config/test_cc_puppet.py
- tests/unittests/helpers.py
- tests/unittests/net/test_dhcp.py
- tests/unittests/net/test_init.py
- tests/unittests/sources/helpers/test_ec2.py
- tests/unittests/sources/test_aliyun.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_bigstep.py
- tests/unittests/sources/test_ec2.py
- tests/unittests/sources/test_exoscale.py
- tests/unittests/sources/test_gce.py
- tests/unittests/sources/test_openstack.py
- tests/unittests/sources/test_oracle.py
- tests/unittests/sources/test_scaleway.py
- tests/unittests/test_data.py
- tests/unittests/test_url_helper.py
- tox.ini
```
tests: Drop httpretty in favor of responses
```
[SC-937](https://warthogs.atlassian.net/browse/SC-937)
After this PR, we could drop `python3-httpretty` from `debian/control` in `ubuntu/<series>` branches.
`tox`
> tests: Drop httpretty in favor of responses

- cloudinit/net/networkd.py
- doc/rtd/topics/network-config-format-v2.rst
- tests/unittests/net/test_networkd.py
- tools/.github-cla-signers
```
support dhcp{4,6}-overrides in networkd renderer
```
Create the metadata file for the VM `metadata.yaml`:
```
instance-id: cloud-vm
local-hostname: cloud-vm
network:
version: 2
ethernets:
nics:
match:
name: ens*
dhcp4: true
dhcp4-overrides:
use-dns: false
nameservers:
addresses: [8.8.8.8, 8.8.4.4]
```
Create the userdata file `userdata.yaml`:
```
#cloud-config
users:
- default
- name: ${YOUR_USER}
primary_group: ${YOUR GROUP}
sudo: ALL=(ALL) NOPASSWD:ALL
groups: sudo, wheel
lock_passwd: true
ssh_authorized_keys:
- ${YOUR_SSH_PUB_KEY}
```
Create a powered-off Photon VM in vSphere:
```
govc import.ova photon-3-kube.ova
govc vm.markastemplate photon-3-kube
govc vm.clone -on=false -vm /dc0/vm/photon-3-kube cloud-vm
```
Set the guestinfo on the VM while it is powered off:
```
export …
```
> support dhcp{4,6}-overrides in networkd renderer

- cloudinit/net/networkd.py
- tests/unittests/net/test_networkd.py
```
networkd: Add test and improve typing.
Add test covering when the original v1 conf contains multiple
subnets associated with a single device.
The issue was already fixed by #1685.
LP: #1973724
```
During the investigation of [lp1973724](https://bugs.launchpad.net/cloud-init/+bug/1973724),
I found out the issue was already fixed in https://github.com/canonical/cloud-init/pull/1685.
Nevertheless, I added a unit test covering the case and some type annotations.
I keep the LP reference in the commit msg to let our tooling close the ticket once released.
https://www.freedesktop.org/software/systemd/man/systemd.network.html
https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html
> networkd: Add test and improve typing.

- cloudinit/config/cc_ubuntu_advantage.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_ubuntu_advantage.py
```
cc_ubuntu_advantage: add ua_config in auto-attach
- Fix and document how to unset ua_config props.
- Redact ua_config values as they could contain sensitive auth info.
- Increase unit test coverage.
```
https://warthogs.atlassian.net/browse/SC-1257
https://github.com/canonical/cloud-init/pull/1583#pullrequestreview-1110047636
> cc_ubuntu_advantage: add ua_config in auto-attach

- tests/integration_tests/instances.py
```
tests: Fix ip log during instance destruction
```
I noticed the following message during integration tests execution:
```text
integration_testing:instances.py:213 Keeping Instance, public ip: <bound method IntegrationInstance.ip of <tests.integration_tests.instances.IntegrationInstance object at 0x7fb1fcbf6518>>
```
> tests: Fix ip log during instance destruction

- cloudinit/sources/DataSourceOracle.py
- tests/unittests/sources/test_oracle.py
```
Fix Oracle DS primary interface when using IMDS
If /run/net* files aren't available, we use IMDS for configuring the
default interface. Rather than attempt a static configuration, grab
the IP and let DHCP do the rest (as it does when /run/net*
is available).
LP: #1989686
```
https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1989686
On my instance, `curl --header "Authorization: Bearer Oracle" http://169.254.169.254/opc/v2/vnics` gives:
```
[
{
"macAddr": "02:00:17:08:BB:E1",
"privateIp": "10.0.2.60",
"subnetCidrBlock": "10.0.2.0/24",
"virtualRouterIp": "10.0.2.1",
"vlanTag": 1320,
"vnicId": "ocid1.vnic.oc1.phx.abyhqljrmna323fjjscndxh2xfa3rkhhrgdwelqhdl6jumhqr3arm44rhuyq"
}
]
```
Generated deb and installed on Oracle. Moved `/run/net-ens3.conf` to `/run/net-ens3.conf.bak`. Ran …
> Fix Oracle DS not setting default route when using IMDS

- cloudinit/cmd/main.py
- doc/rtd/index.rst
- doc/rtd/topics/cli.rst
- doc/rtd/topics/configuration.rst
- doc/rtd/topics/instancedata.rst
- doc/rtd/topics/vendordata.rst
Tbh, when I started this document, I thought I'd have more content for it. My goals are:
1. Document our base configuration, how it's generated, and how the pieces get layered on. We had documentation for user data and vendor data independently, but not the config as a whole
2. Help in understanding the difference between /etc/cloud/cloud.cfg and #cloud-config user data
3. Answer some common questions we get around configuration...in particular how do I modify my network or user config
I'm open to updates or suggestions for additional information.
Also, I'm trying to fit new documents into a diataxis category, even if they stick out like a sore thumb. This does indeed stick out like a sore thumb, but I think it's better to start that way and migrate other documents accordingly rather than …
> doc: Add configuration explanation (SC-1169)

- cloudinit/config/cc_ubuntu_advantage.py
- tests/integration_tests/modules/test_ubuntu_advantage.py
- tests/unittests/config/test_cc_ubuntu_advantage.py
```
cc_ubuntu_advantage: Handle already attached on Pro
On Pro instances, UA could raise an exception signalizing already
attached instances. Catch it and warn if some service is given in
the cloud-config to be configured.
Improve integration test:
- mask ua services on first boot to upgrade UA on Pro
instances and let the second boot be clean
- assert the correct services were enabled
- detect instances where cloud-init does yet support custom
auto-attach and fail the test.
```
```sh
CLOUD_INIT_PLATFORM=<gce|azure|ec2>  tox -e integration-tests -- tests/integration_tests/modules/test_ubuntu_advantage.py::TestUbuntuAdvantagePro
```
> cc_ubuntu_advantage: Handle already attached on Pro

- ChangeLog
- cloudinit/sources/DataSourceOracle.py
- cloudinit/version.py
- debian/changelog
- tests/unittests/sources/test_oracle.py
Steps:
```
git checkout ubuntu/22.3.3-0ubuntu1_22.04.1 -B ubuntu/jammy-22.3-hotfix
git push -u upstream ubuntu/jammy-22.3-hotfix
new-upstream-snapshot 22.3.4
build-package
sbuild --resolve-alternatives --dist=jammy --arch=amd64 ../out/cloud-init_22.3.4-0ubuntu1.dsc
```
Note: We need to avoid tag collisions with other series. Continuing the trend from kinetic of following the changelog version number will result in collisions with each series having the same tag (`ubuntu/22.3.4-0ubuntu1`). I propose following the old scheme: `ubuntu/22.3.4-0ubuntu1_22.04.1`
> Ubuntu/jammy 22.3 hotfix

- tests/integration_tests/util.py
Having recently noticed that LOG.critical() is used in cloudinit, update integration tests to check for CRITICAL.
> testing: check logs for critical errors

- cloudinit/distros/__init__.py
- cloudinit/distros/freebsd.py
- cloudinit/distros/openbsd.py
- tests/unittests/distros/test_manage_service.py
```
Distro manage service: Improve BSD support
OpenBSD has wrapper called `rcctl` that does the same thing as 'service'.
FreeBSD's 'service' knows about 'enable', so we specialize that, too.
Add support and tests.
NetBSD's service does about as much as the base-case, so no need to do anything there.
To mark the occasion, we also add all other BSD `distros` to `OSFAMILIES`.
LP: #1990070
```
- update cloud-init on *BSD
- test:
```python
>>> from cloudinit.distros.freebsd import Distro
>>> f = Distro('FreeBSD', cfg={}, paths={})
>>> f.manage_service('enable', 'ntpd')
SubpResult(stdout='ntpd enabled in /etc/rc.conf\n', stderr='')
>>> f.manage_service('restart', 'ntpd')
SubpResult(stdout='Starting ntpd.\n', stderr='ntpd not running? (check …
```
> Distro manage service: Improve BSD support

- packages/README.md
```
docs: use opensuse for distro name
```
SUSE is a company, opensuse is a community distro.
> docs: use opensuse for distro name

- cloudinit/analyze/show.py
When using the Azure data source, frames are not guaranteed to be unique to each boot.  Instead of splitting boot records when any event is seen more than once, do so whenever the start of `init-local` stage is found (and records have already been processed).
> analyze: use init-local as start of boot record

- tests/integration_tests/datasources/test_lxd_discovery.py
- tests/integration_tests/modules/test_combined.py
- tests/integration_tests/util.py
```
tests: Use LXD metadata to determine NoCloud status
Rather than hardcoding a series name, use the LXD metadata to determine
if the current instance should use NoCloud rather than LXD datasource.
```
> tests: Use LXD metadata to determine NoCloud status

- cloudinit/distros/freebsd.py
- cloudinit/distros/openbsd.py
```
OpenBSD: remove pkg_cmd_environ function
This environment variable is being set to the main mirror, which is
heavily under load. It also sets it to a deprecated and highly insecure
protocol.
OpenBSD's default behaviour is to read a list of mirrors from
installurl(5): https://man.openbsd.org/installurl.5
We can restore this behaviour by removing the contents of this function.
Note that the Equivalent NetBSD function makes vastly more sense.
LP: 1991567
```
Try install a package thru a REPL.
If this code ever did anything, it should now be faster.
> OpenBSD: remove pkg_cmd_environ function

- cloudinit/config/cc_ansible.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- cloudinit/distros/__init__.py
- cloudinit/distros/alpine.py
- tests/integration_tests/modules/test_ansible.py
- tests/unittests/config/test_cc_ansible.py
```
modules: add ansible-galaxy support to ansible
This is intended to allow users to install roles
and collections directly with the user-data
cloud-config for use in ansible playbooks during boot.
```
This allows community reuse of roles and collections, which users
may use in their own ansible playbooks.
There is [more work](https://docs.google.com/document/d/1hHEijcgxZNbWZvbVlL5YkDCDBv52Sb49nEJ7FDU5LcI/edit#) to do with this module, but since this is usable with ansible-pull as well, I'm submitting it as is to keep reviews smaller.
https://galaxy.ansible.com/
https://docs.ansible.com/ansible/latest/cli/ansible-galaxy.html
integration test included to install from galaxy
> cc_ansible: add support for galaxy install

- Makefile
```
make Makefile make agnostic
remove ifeq assignment, and replace with ?= which should do the same thing
this makes our Makefile make agnostic
```
this should remove gnu make as our dependency for building, or rather, testing, this in FreeBSD's and OpenBSD's port system
```
meena@76ix ~/s/c/cloud-init (patch-1)> make distro=fedora srpm
python3 ./packages/brpm --srpm --distro=fedora
usage: brpm [-h] [-d DISTRO] [--srpm] [-b TYPE] [-v] [-s RELEASE] [-p PATCHES]
brpm: error: argument -d/--distro: invalid choice: 'fedora' (choose from 'redhat', 'suse')
make: *** [Makefile:102: srpm] Error 2
meena@76ix ~/s/c/cloud-init (patch-1) [2]> bmake distro=fedora srpm
python3 ./packages/brpm --srpm --distro=fedora
usage: brpm [-h] [-d DISTRO] [--srpm] [-b TYPE] [-v] [-s RELEASE] [-p PATCHES]
brpm: …
```
> make Makefile make agnostic

- cloudinit/config/cc_ubuntu_advantage.py
- tests/integration_tests/modules/test_ubuntu_advantage.py
- tests/unittests/config/test_cc_ubuntu_advantage.py
```
cc_ua: consume ua json api for enable commands
Remove safeguard uaclient imports as uaclient has already been released.
```
https://warthogs.atlassian.net/browse/SC-1253
https://github.com/canonical/cloud-init/pull/1673#discussion_r965352866
Example the UA json api for enable:
```bash
$ sudo ua enable --assume-yes --format json asdf livepatch esm-apps esm-apps | jq
{
"_schema_version": "0.1",
"errors": [
{
"message": "Cannot install Livepatch on a container.",
"message_code": "livepatch-error-install-on-container",
"service": "livepatch",
"type": "service"
},
{
"message": "UA Apps: ESM is already enabled.\nSee: sudo ua status",
"message_code": "service-already-enabled",
"service": "esm-apps",
"type": "service"
},
{
"message": "UA Apps: ESM is already enabled.\nSee: sudo ua status", …
```
> cc_ua: consume ua json api for enable commands

- tests/integration_tests/modules/test_combined.py
```
Fix LXD/nocloud detection on lxd vm tests
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-lxd_vm/130/testReport/junit/tests.integration_tests.modules.test_combined/TestCombined/test_instance_json_lxd_vm/
> Fix LXD/nocloud detection on lxd vm tests

- cloudinit/apport.py
- cloudinit/cmd/devel/logs.py
- tests/integration_tests/test_paths.py
- tests/unittests/cmd/devel/test_logs.py
- tests/unittests/test_apport.py
```
cli/apport: collect-logs include subiquity logs config when present
Add support for both cloud-init collect-logs and apport to
include subiquity live installer artifacts if present to aid in
bug triage.
Apport integration to attach subiquity, curtin and
ubuntu-desktop-installer report keys when logs or
config files are present.
ubuntu-bug cloud-init will also automatically tag the
bug as curtin, subiquity or ubuntu-desktop-installer if
related logs are present in the bug report.
Additional collect-logs support to collect
/var/lib/cloud/data in the event that cloud-init is disabled
by systemd generator with /run/cloud-init/disabled flag.
In these situations we want to collect /var/lib/cloud/data
dir for more context on prior cloud-init behavior.
```
[LP: …
> collect logs apport subiquity support (SC-1279)

- cloudinit/config/cc_lxd.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/integration_tests/modules/test_lxd.py
- tests/unittests/config/test_cc_lxd.py
```
User-data now supports opaque lxd.preseed YAML
which can be provided directly to the command:
lxd init --preseed
Complex LXD host, network, profile and storage setup
and configuration can be provided via this config entry.
For details on available configuration options and examples
https://linuxcontainers.org/lxd/docs/master/preseed/
- or -
lxd init --dump
```
```bash
make deb
CLOUD_INIT_KEEP_INSTANCE=true CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_OS_IMAGE=jammy CLOUD_INIT_SOURCE=./cloud-init_all.deb  tox -e integration-tests tests/integration_tests/test_lxd.py::test_storage_preseed_btrfs
make doc
xdg-open doc/rtd_html/topics/modules.html
```
> lxd: add support for lxd preseed config (SC-1025)

- tools/read-version
`git branch --show-current` option flag is only available in focal+. Use `git rev-parse --abbrev-ref HEAD` instead.
```
read-version: Make it compatible with bionic
`git branch --show-current` option flag is only available in focal+. Use `git rev-parse --abbrev-ref HEAD` instead.
```
https://github.com/canonical/cloud-init/pull/1718
```
$ tox --recreate -e integration-tests -- --collect-only tests/integration_tests/
GLOB sdist-make: /home/ubuntu/cloud-init/setup.py
ERROR: invocation failed (exit code 1), logfile: /home/ubuntu/cloud-init/.tox/log/tox-0.log
ERROR: actionid: tox
msg: packaging
cmdargs: ['/usr/bin/python3', local('/home/ubuntu/cloud-init/setup.py'), 'sdist', '--formats=zip', '--dist-dir', local('/home/ubuntu/cloud-init/.tox/dist')]
env: None …
```
> read-version: Make it compatible with bionic

- cloudinit/apport.py
- cloudinit/cmd/devel/logs.py
- tools/.github-cla-signers
```
apport: fix some data collection failures due to symlinks
Apport screens out symlinks, so we should send realpath() normalized
paths instead.
```
In the LP: #[1993011](http://pad.lv/1993011) test bug, some failures related to symlinks can be seen.  Fix that.
Run `ubuntu-bug` in a Subiquity live-server ephemeral environment with the affected version of cloud-init installed.
> Realpath logfiles

- cloudinit/distros/alpine.py
- tests/unittests/config/test_cc_ntp.py
- tests/unittests/distros/test_manage_service.py
alpine.py: Add Alpine-specific manage_service function and update tests
```
Alpine uses OpenRC rather than Systemd. Add a
distro-specific manage_service in alpine.py and
update some affected testcases appropriately.
```
> alpine.py: Add Alpine-specific manage_service function and update tests

- doc/examples/cloud-config-user-groups.txt
```
Fix inconsistency between comment and statement
Line 3 was stating that the "ubuntu" group is created while the yml indicates "sysadmin"
```
N/A
-  My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html) (N/A)
-  I have updated or added any unit tests accordingly (N/A)
> Fix inconsistency between comment and statement

- tests/integration_tests/modules/test_lxd.py
```
tests: Restrict lxd tests to applicable series
Some lxd init --preseed features are only available in specific 
lxd versions.
The use of projects within the preseed is lxd >= 4.12
and `features.storage.buckets` is lxd >= 5.5 
Adapt the tests to perform the assertions only in series that
contain the applicable lxd versions.
```
https://github.com/canonical/cloud-init/pull/1789
```bash
#!/bin/bash -eux
function run_test {
local SERIES=$1
local PLATFORM=$2
LOG_FN="test_preseed_${PLATFORM}_${SERIES}.log"
CLOUD_INIT_SOURCE=IN_PLACE CLOUD_INIT_PLATFORM=$PLATFORM CLOUD_INIT_OS_IMAGE=$SERIES tox -e integration-tests -- -vv tests/integration_tests/modules/test_lxd.py | tee $LOG_FN
}
for PLATFORM in lxd_container lxd_vm
do
for SERIES in bionic focal jammy kinetic
do
run_test $SERIES $PLATFORM …
```
> tests: Ignore unsupported lxd project keys

- .github/workflows/check_format.yml
- cloudinit/config/schemas/schema-cloud-config-v1.json
- cloudinit/config/schemas/versions.schema.cloud-config.json
- tools/check_json_format.sh
- tox.ini
```
Add schema auto-format to tox and a CI test
```
Our schema format is currently inconsistent. Use json.tool to auto-format.
I didn't include `tox -e check_format` integration for this tool, but it would be possible if desired to use the current CI workflow instead of what I did.
> Auto-format schema

- cloudinit/config/cc_grub_dpkg.py
```
cc_grub: reword docs for clarity
```
This change may seem excessively pedantic, however I did misunderstand this sentence myself while reading the docs and it does seem contradictory to me. I'm open to other suggestions to improve these docs. This change makes it clearer for me.
Drop this sentence for clarity:
> This module should work correctly by default without any user configuration.
User configuration is in fact required for this module to run (`grub_dpkg: {enabled: true}`), which leaves this statement in conflict[1] with the sentence it precedes:
> It can be enabled/disabled using the ``enabled`` config key in the ``grub_dpkg`` config dict.
I think the intention behind this statement is covered in this sentance:
> If no installation device is specified this module will execute …
> grub: clarify docs

- cloudinit/cmd/devel/logs.py
```
apport: address new curtin log and config locations
Retain legacy curtin log and config paths for Bionic, Focal, Jammy.
```
> apport: address new curtin log and config locations

- cloudinit/sources/DataSourceLXD.py
- tests/integration_tests/datasources/test_lxd_hotplug.py
- tests/unittests/sources/test_lxd.py
```
Stop using devices endpoint for LXD network config
When using the LXD datasource, we switched to using the "devices"
endpoint to configure network config. On LXD VMs, this endpoint can
contain incorrect device names, so instead switch to setting up the
fallback NIC until the devices endpoint can surface MAC addresses.
```
The lxd integration tests (`test_lxd.py` `test_lxd_hotplug.py` `test_lxd_discovery.py`) should cover all cases.
> Stop using devices endpoint for LXD network config

- .github/workflows/check_format.yml
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tools/check_json_format.sh
```
ci: run json format test on 22.04
```
Note that [tests here passed](https://github.com/canonical/cloud-init/actions/runs/3440237672/jobs/5738474966) despite running on a version of Ubuntu that didn't support the --indent flag on python's json.tool. This change fixes the ci setup and also prevents silent failure.
> ci: run json tool on 22.04 rather than 20.04

- cloudinit/config/cc_ansible.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- doc/examples/cloud-config-ansible-controller.txt
- doc/examples/cloud-config-ansible-pull.txt
- tests/integration_tests/modules/test_ansible.py
- tests/unittests/config/test_cc_ansible.py
```
ansible: standardize schema keys
The cloud-config schema definition standardizes on underscores
instead of hyphenated key names. This makes for standard config keys
and reduces the burden of supporting aliases for either hyphenated or
underscore-delimited keys.
```
Note:
-----
The `.replace("_", "-")` is because there was previously almost[1] a 1:1 mapping between schema keys and ansible arguments.
[1] "almost" because boolean values are indicated be the absence or presence of a `--$FLAGNAME`
> ansible: s/-/_/g

- tests/unittests/config/test_cc_ansible.py
```
tests: replace ansible install-method with underscore
Also support test runs in environments without pip
```
> tests: replace missed ansible install-method with underscore

- tests/integration_tests/modules/test_lxd.py
```
tests: test_lxd assert features.storage.buckets when present
LXD v 5.5 introduces a features.storage.buckets default.
Assert features.storage.buckets  when host provides this key.
Cope with versions that do not surface this config.
```
Failed jenkins jobs on kinetic indicate this problem
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-kinetic-azure/121/testReport/junit/tests.integration_tests.modules/test_lxd/test_storage_preseed_btrfs/
```
make deb
CLOUD_INIT_PLATFORM=azure CLOUD_INIT_OS_IMAGE=kinetic CLOUD_INIT_CLOUD_INIT_SOURCE=./cloud-init_22.3-107-g661b852c-1~bddeb_all.deb tox -e integration-tests tests/integration_tests/modules/test_lxd.py::test_storage_preseed_btrfs
```
> tests: test_lxd assert features.storage.buckets when present

- tests/integration_tests/modules/test_lxd.py
```
tests: text_lxd basic_preseed verify_clean_log
Catch warnings or traces in the cloud-init.log before
hitting assert failures in parsing invalid lxc cmd output.
```
> tests: text_lxd basic_preseed verify_clean_log

- cloudinit/config/cc_disk_setup.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_disk_setup.py
```
summary: fix cc_disk_setup.py to pass options in correct order to utils
When testing cc_disk_setup it failed with the following error:
Unexpected error while running command.
Command: ['/sbin/mkfs.ext4', '/dev/sdc1', '-L', 'disk3-fs2']
Exit code: 1
Reason: -
Stdout:
stderr: mke2fs 1.46.5 (30-Dec-2021)
mkfs.ext4: invalid blocks '-L' on device '/dev/sdc1'
The manpages for mkfs.ext4, mkfs.xfs, and mkswap all indicate that
options should be passed *before* the device name but cc_disk_setup
passed them after the device name - in the case of mkfx.ext4 a
"fs-size" can be passed after the device and that is what the
"-L disk3-fs2" option is being misintepreted as.
This PR ensures that the device name is passed last. The underlying
issue appears to be due to a different in behaviour between …
```
> fix cc_disk_setup.py to pass options in correct order to utils

- cloudinit/config/cc_ubuntu_advantage.py
- tests/integration_tests/modules/test_ubuntu_advantage.py
- tests/unittests/config/test_cc_ubuntu_advantage.py
Ensure Pro instances are detached before the test run and that the test only runs on LTS releases.
```
test: fix pro integration test
Ensure Pro instances are detached before the test run and that
the test only runs on LTS releases.
As ua.UserFacingError is not properly converted to str,
manually pick its msg to provide the user a more informative
logging msg.
```
- https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-ec2/139/testReport/tests.integration_tests.modules.test_ubuntu_advantage/TestUbuntuAdvantagePro/test_custom_services/
- https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-kinetic-ec2/lastCompletedBuild/testReport/tests.integration_tests.modules.test_ubuntu_advantage/TestUbuntuAdvantagePro/test_custom_serv …
> test: fix pro integration test

- ChangeLog
will fix daily build recipes as well. Remove trailing whitespace due to copy-pasta error into main.
```
ChangeLog: whitespace cleanup
```
To confirm daily builds work:
git checkout <this_branch>
git merge upstream/ubuntu/bionic  # or focal/jammy/kinetic Expect no merge conflicts
> ChangeLog: whitespace cleanup

- cloudinit/net/netplan.py
- cloudinit/net/network_state.py
- doc/rtd/topics/network-config-format-v2.rst
- tests/unittests/distros/test_netconfig.py
- tests/unittests/net/test_net_rendering.py
- tests/unittests/net/test_network_state.py
- tests/unittests/test_net.py
```
network: Deprecate gateway{4,6} keys in network config v2
- Do not render gateway{4,6} when transforming from network config v1 to v2.
- Issue a warning if gateway{4,6} is present in network config v2.
This warning is not issued if a passthrough to netplan is performed.
LP: #1992512
```
https://netplan.io/reference#default-routes
> Netplan deprecated keys (SC-1050)

- cloudinit/sources/DataSourceOpenStack.py
- tools/.github-cla-signers
Add Support for IPv6 metadata to `DataSourceOpenStack`
```
Add Support for IPv6 metadata to `DataSourceOpenStack`
- Add openstack IPv6 metadata url `fe80::a9fe:a9fe`
- Enable requesting multiple metadata sources in parallel
This PR is very similar to #1160, reusing the provided `url_heper` logic.
LP: #1906849 
```
```
cloud-init clean --logs
cloud-init init --local
```
Will successfully request metadata over IPv6 from the openstack provider, given
it is reachable over IPv6. If not, or if IPv4 is faster it will be used instead.
> Srv6d openstack dualstack

- doc/rtd/topics/module_creation.rst
```
doc: improve module creation explanation
Explain that the new module name must be included in
jsonschema.$defs.all_modules to be validated within
the base config.
```
https://github.com/canonical/cloud-init/pull/1770
https://github.com/canonical/cloud-init/pull/1756#pullrequestreview-1181928024
> doc: improve module creation explanation

- tests/unittests/test_ds_identify.py
Some build environments will not have open-vm-tools and consequently vmware-rpctool installed. Since we are mocking behavior of tests we fake the presence of this utility to ensure VMware is properly detected.
```
tests: ds-id mocks for vmware-rpctool as utility may not exist in env
Some build environments will not have open-vm-tools and consequently
vmware-rpctool installed. Since we are mocking behavior of tests
we fake the presence of this utility to ensure VMware is properly
detected.
```
launchpad daily build failures point to environments with no open-vm-tools installed
https://launchpadlibrarian.net/634162856/buildlog_ubuntu-lunar-amd64.cloud-init_22.4.daily-202211171631-33eb9b13~ubuntu23.04.1_BUILDING.txt.gz
```
lxc launch ubuntu-daily:bionic dev-b
lxc exec dev-b bash
git clone …
```
> tests: ds-id mocks for vmware-rpctool as utility may not exist in env

- CONTRIBUTING.rst
- doc-requirements.txt
- doc/rtd/index.rst
- doc/rtd/topics/code_review.rst
- doc/rtd/topics/module_creation.rst
- doc/rtd/topics/modules.rst
- doc/rtd/topics/network-config-format-v2.rst
- doc/rtd/topics/tutorial.rst
```
docs: changed all internal links to be relative
In preparation for migrating the docs to RTD.com, identified all 
links that point to the RTD.org links and changed them to be 
relative so that it doesn't matter where they are rendered. 
Also fixed the sphinx-design extension - although it's not used
yet, I will be using it to create the Diataxis home page sections.
```
> Docs: adding relative links

- .travis.yml
```
Make 3.12 failures not fail the build
Since 3.12 is the development release, failures of it
shouldn't fail the overall build.
```
https://app.travis-ci.com/github/canonical/cloud-init/jobs/588960329
and
https://docs.python.org/3.12/whatsnew/3.12.html
> Make 3.12 failures not fail the build

- cloudinit/cmd/status.py
- tests/unittests/cmd/test_cloud_id.py
- tests/unittests/cmd/test_status.py
```
status: handle ds not defined in status.json
Handles any situation where `status.json` does not yet contain
datasource information, by gracefully fulfilling a 
`datasource=None` in `StatusDetails`.
LP: #1997559
```
https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1997559
Execute:
```sh
lxc launch --ephemeral ubuntu-daily:lunar test
lxc exec test -- cloud-init status --wait
```
I noticed the error does not arise 100% of times, therefore there is some kind of race condition or non-deterministic behavior happening when using the ephemeral option on LXD.
This PR handles any situation where `status.json` does contain `{"v1": {"datasource": null}}`, in general, by gracefully fulfilling a `datasource=None` in `StatusDetails`.
> status: handle ds not defined in status.json

- tests/integration_tests/modules/test_lxd.py
```
test: fix lxd preseed managed network config
Remove managed key in network config on LXD preseed configs
as it is not a valid key in LXD > v4.
```
After the inclusion of the fix of https://github.com/lxc/lxd/issues/11106, we are hitting LXD errors when we pass unknown preseed config keys to `lxd init --preseed` in our integration tests.
More concretely, in https://github.com/canonical/cloud-init/blob/893df0d61179a6722c44267f57c57284543c2f12/tests/integration_tests/modules/test_lxd.py#L49 we hand over a network config with the root key `managed`, which is only compatible in LXD v3.x.y (bionic), and not in v4 nor v5 (newer Ubuntu versions).
[From my understanding](https://linuxcontainers.org/lxd/docs/latest/explanation/networks/), `managed` is implicitly discovered by LXD depending on …
> test: fix lxd preseed

- doc/rtd/topics/analyze.rst
```
docs: uprate analyze to performance page
As previously discussed, the Analyze page contains the content we want
to present under the "Performance" topic and should be uprated. 
I have changed the title of the "Analyze" page to "Performance" so that
it shows correctly in the LHS menu. The anchors are the same, and I have 
not changed the file name so as to avoid having to update any links.
I took the opportunity to make some minor tidying edits to the text.
Hopefully these will add clarity and not change the intended meaning. 
```
> docs: uprate analyze to performance page

- cloudinit/sources/DataSourceAliYun.py
- cloudinit/sources/DataSourceEc2.py
- tests/unittests/sources/test_aliyun.py
- tests/unittests/sources/test_ec2.py
- tools/.github-cla-signers
```
feat: add support Aliyun metadata security hardening mode
currently, Alibaba cloud provides a security hardening mode for its metadata server, which is alike IMDSv2, and we should support it.
Detailed information be found here: https://www.alibabacloud.com/help/en/elastic-compute-service/latest/view-instance-metadata#concept-dwj-y1x-wgb
```
> feat: add support for aliyun metadata security harden mode

- sysvinit/freebsd/cloudconfig
- sysvinit/freebsd/cloudfinal
- sysvinit/freebsd/cloudinit
- sysvinit/freebsd/cloudinitlocal
```
FreeBSD init: use cloudinit_enable as only rcvar
all components of cloudinit need to run, and in a specific order.
If cloudinit is to be enabled, it should only rely on one variable.
This change better encodes that, than #161 
```
Currently, when cloud-init isn't enabled, some of its components issue rc warnings.
Previously, in https://github.com/canonical/cloud-init/pull/161 we went overboard, by giving each its own variable
install this patch, reboot, see no more warnings.
> FreeBSD init: use cloudinit_enable as only rcvar

- config/cloud.cfg.tmpl
```
summary: Append derivatives to is_rhel list in cloud.cfg.tmpl
This commit adds Rocky Linux, AlmaLinux, CloudLinux, EuroLinux, Miracle
Linux, and Virtuozzo to the is_rhel list. Recent downstream patch from
Red Hat causes issues with RHEL derivatives with the cloud.cfg template,
which leads to derivatives having to make small changes to bring back
expected functionality.
```
In RHEL 8.7 and 9.1, and thus Rocky Linux 8.7 and 9.1, cloud-init was rebased to 22.1. In this update, Red Hat backported #1431. In CentOS Stream 8 and 9, they also backported #1639. Unfortunately, this caused some issues with our cloud images as the cloud configuration is now missing some pieces that were once there that would work the same RHEL or CentOS Stream. We had to create a downstream patch in our own …
> Append derivatives to is_rhel list in cloud.cfg.tmpl

- cloudinit/config/cc_ansible.py
- cloudinit/config/schema.py
- cloudinit/net/activators.py
- cloudinit/net/ephemeral.py
- cloudinit/net/network_state.py
- cloudinit/stages.py
- cloudinit/url_helper.py
- pyproject.toml
- tests/integration_tests/modules/test_combined.py
- tests/unittests/config/test_cc_ansible.py
```
lint: fix tip-flake8 and tip-mypy
Improve also test doc.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-style-tip/239/console
https://github.com/PyCQA/pyflakes/pull/684
`tox -e tip-flake8,tip-mypy`
> lint: fix tip-flake8 and tip-mypy

- doc/rtd/index.rst
- doc/rtd/topics/modules.rst
- doc/rtd/topics/tutorials/lxd.rst
- doc/rtd/topics/tutorials/qemu-debugging.rst
- doc/rtd/topics/tutorials/qemu-script.sh
- doc/rtd/topics/tutorials/qemu.rst
```
doc: add qemu tutorial
```
The [NoCloud docs](https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html) for more information about the datasource in use in this tutorial.
When more tutorials come into existance, a landing page/tutorial index for selecting which datasource to use may become desirable, but at only 2 total tutorials as of this PR, I don't know how much sense that would make. Thoughts?
> doc: add qemu tutorial

- cloudinit/net/networkd.py
- tests/unittests/net/test_networkd.py
```
networkd: Add support for multiple [Route] sections to support device routes
Networkd supports multiple [Route] sections within the same file.  Currently all [Route] section tags are squashed
into one and if there is a default gateway it means defining a device route is not possible as the target is set to the
default gateway.
This patch adds support for multiple [Route] sections allowing us to support device routes. This is done by
tracking each route in the route list individually and ensuring the key-value pairs are maintained within their 
respective [Route] section. This both maintains backwards compatibility with previous behavior and allows
the specification of routes with no destination IP, causing the destination to be added with a device target.
```
So the problem is with a …
> Add support for multiple [Route] sections so device routes work

- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/test_azure_helper.py
If utf-8 characters are used in the report, it will fail to encode:
```
azure.py[ERROR]: exception while reporting ready: 'latin-1' codec can't
encode characters in position 392-397:
Body ('乱写一些单词') is not valid Latin-1.
Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```
Explicitly encode document as utf-8.
> sources/azure: encode health report as utf-8

- doc/rtd/topics/faq.rst
- doc/rtd/topics/modules.rst
```
autoinstall: clarify docs for users
```
Add autoinstall pointer to subiquity docs to FAQ.
Remove cc_ubuntu_autoinstall from docs module definitions, since it doesn't give users actionable information.
Leave the module definition intact in the code, since it does add context that may be valuable for developers.
The net affect of this is PR that future searches of the website for "autoinstall" will lead users to the FAQ (and then to subiquity docs), which makes sense because we don't have autoinstall-specific documentation in the cloud-init docs.
> Autoinstall clarification

- cloudinit/net/netplan.py
- tests/integration_tests/datasources/test_lxd_hotplug.py
- tests/integration_tests/modules/test_combined.py
- tests/unittests/distros/test_netconfig.py
```
Restrict read access of /etc/netplan/50-cloud-init.yaml.
On netplan systems, network v2 is passed directly though and written
to /etc/netplan/50-cloud-init.yaml without validation. Current netplan
configuration provides the ability to configure sensitive information
such as `wifi:access-points:password`.
Limit permissions for /etc/network/50-cloud-init.yaml as read-only
for root. Since configuration or modification or netplan config
needs to be performed by an admin user this permission restriction
aligns with netplan tooling.
Set root read-only only always and not just 'if' sensitive material
exists within custom config because it will add confusion to have
two expected modes for this file based on external conditions.
```
feature tracking improved netplan config security & …
> net: netplan config root read-only as wifi config  can contain creds

- cloudinit/stages.py
```
net: clarify network function name and docstring
```
It doesn't seem intuitive to me to describe a function as "removing" a key, when it returns the value in the dict referenced by that key, since I would typically remove a key from a dict using `pop()`, which modifies the dict. 
I propose as alternative `dereference`, `find`, or simply `get`. Thoughts?
```python
pop(...)
D.pop(k[,d]) -> v, remove specified key and return the corresponding value.
If the key is not found, return the default if given; otherwise,
raise a KeyError.
```
> Networking Clarification

- integration-requirements.txt
This fixes integration test failures seen on Jenkins workers which do not have an 'az' command installed.
```
azure: fix support for systems without az command installed
```
failures: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-azure/lastSuccessfulBuild/consoleFull
fix: https://github.com/canonical/pycloudlib/pull/226
> Pycloudlib bump

- cloudinit/features.py
- cloudinit/net/netplan.py
- tests/integration_tests/datasources/test_lxd_hotplug.py
- tests/integration_tests/modules/test_combined.py
- tests/integration_tests/util.py
- tests/unittests/distros/test_netconfig.py
```
netplan: define features.NETPLAN_CONFIG_ROOT_READ_ONLY flag
To make retaining original behavior in stable releases, provide a feature flag NETPLAN_CONFIG_ROOT_READ_ONLY so we can retain world-readable /etc/netplan/50-cloud-init.yaml in downstreams.
Set this flag False to ensure world-readable 50-cloud-init.yaml.
```
> netplan: define features.NETPLAN_CONFIG_ROOT_READ_ONLY flag

- systemd/cloud-init.service.tmpl
```
Ensure network ready before cloud-init service runs on RHEL
LP: #1998655
```
See https://bugs.launchpad.net/cloud-init/+bug/1998655
> Ensure network ready before cloud-init service runs on RHEL

- tests/unittests/net/test_dhcp.py
```
test: mock file deletion in dhcp codepath
Tests attempt to delete /run/dhclient.pid and
/run/dhclient.leases from the host. This leads
to host-dependent test failure. Fix it.
```
```python
def dhcp_discovery(dhclient_cmd_path, interface, dhcp_log_func=None):
"""Run dhclient on the interface without scripts or filesystem artifacts.
@param dhclient_cmd_path: Full path to the dhclient used.
@param interface: Name of the network interface on which to dhclient.
@param dhcp_log_func: A callable accepting the dhclient output and error
streams.
@return: A list of dicts of representing the dhcp leases parsed from the
dhclient.lease file or empty list.
"""
LOG.debug("Performing a dhcp discovery on %s", interface)
pid_file = "/run/dhclient.pid"
lease_file = "/run/dhclient.lease"
with …
```
> test: mock file deletion in dhcp codepath

- cloudinit/config/schemas/schema-cloud-config-v1.json
- cloudinit/util.py
- tests/unittests/test_util.py
```
mounts: document weird prefix in schema
Add test and support for parsing IEC prefix format.
```
Top search engine link for me:
https://inst.eecs.berkeley.edu/~cs61c/su14/labs/02/iec.pdf
Feel free to suggest better wording/placement. I do think that a warning somewhere is probably warranted, since we're doing something explicitly incorrect without telling the user.
Note: There was a time when these prefixes were less well-defined, but I think that point in time has since passed.
> Document Incorrect Prefix For cc_mounts

- tools/read-version
```
read-version: When insufficient tags, use cloudinit.version.get_version
```
```
git clone --no-single-branch --depth 50 https://github.com/canonical/cloud-init.git
cd cloud-init
git fetch origin --force --tags --prune --prune-tags --depth 50 pull/1879/head:external-1879
git checkout --force ac0795a9ff76c48ca74ae23b5766543ef6785387
git apply <this patch>
./tools/read-version
```
> read-version: When insufficient tags, use cloudinit.version.get_version

- cloudinit/dmi.py
- cloudinit/features.py
- cloudinit/sources/DataSourceNoCloud.py
- cloudinit/util.py
- doc/examples/cloud-config-datasources.txt
- doc/rtd/topics/datasources/nocloud.rst
- tests/unittests/test_dmi.py
- tests/unittests/test_util.py
- tools/read-version
```
nocloud: add support for dmi variable expansion for seedfrom URL
NoCloud meta-data seedfrom (or kernel commandline seedfrom) URL can
now provide variable expansion for system-specific DMI values as seen
in /sys/class/dmi/id on Linux or kenv on FreeBSD platforms.
Variable names of the format __dmi.SOME_VAR__ will be replaced when
determining the URL from which NoCloud datasource GETs its user-data
and meta-data.
This allows for a common templated seedfrom URL which can be reused
for mass deployments, but can allow for unique URLs based on classes
of DMI system characteristics such as chassis serial, product name,
UUID etc.
LP: #1994980
```
> nocloud: add support for dmi variable expansion for seedfrom URL

- cloudinit/distros/parsers/ifconfig.py
- tests/data/netinfo/freebsd-duplicate-macs-ifconfig-output
- tests/data/netinfo/freebsd-ifconfig-output
- tests/unittests/distros/test_ifconfig.py
```
BSD: fix duplicate macs in Ifconfig parser
Some cloud providers can have more than one device with the same MAC
address. This PR allows parsing and storing and retrieving such
configurations.
We now use `defaultdict` to retrieve `ifs_by_mac`, before converting it
all to a `dict`. We also store the two in separate variables.
Add test case from Azure to verify, and test data in a new file, since
our old cloudinit.net functions can't handle it.
```
> BSD: fix duplicate macs in Ifconfig parser

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
The ordering of NICs provided by IMDS may not match the order enumerated by kernel.  As such, we do not have any guarantee that the nic we're checking the driver for is the nic we think it is.
Instead of making any assumptions about how the nics are named, check all interfaces by mac address.  If there is an interface using "hv_netvsc", match against that.  If there is only one interface driver that is not blacklisted, use that (in case it is not "hv_netvsc"), but log a debug event.  If there are multiple hits, don't match against any of the names and report a warning.
> sources/azure: fix device driver matching for net config

- doc/examples/cloud-config-ansible-controller.txt
- doc/examples/cloud-config-ansible-pull.txt
- tests/integration_tests/modules/test_ansible.py
```
Fix typo with package_update/package_upgrade
There's a typo in the docs that can lead to confusion.
packages_update > package_update
packages_upgrade > package_upgrade
```
https://cloudinit.readthedocs.io/en/latest/topics/modules.html#package-update-upgrade-install
> Fix typo with package_update/package_upgrade

- cloudinit/config/cc_disk_setup.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- doc/examples/cloud-config-disk-setup.txt
- tests/unittests/config/test_cc_disk_setup.py
```
cc_disk_setup.py: fix MBR single partition creation
Fixes the creation of single partitions on MBR devices. Currently this fails with the following debug output:
cc_disk_setup.py[DEBUG]: Calculating partition layout
cc_disk_setup.py[DEBUG]:    Layout is: 0,
cc_disk_setup.py[DEBUG]: Creating partition table on /dev/sdb
subp.py[DEBUG]: Running command ['/sbin/sfdisk', '--Linux', '--unit=S',
'--force', '/dev/sdb'] with allowed return codes [0] (shell=False,
capture=True)
util.py[DEBUG]: Creating partition on /dev/sdb took 0.237 seconds
util.py[WARNING]: Failed partitioning operation
Failed to partition device /dev/sdb
Unexpected error while running command.
Command: ['/sbin/sfdisk/', '--Linux', '--unit=S', '--force', '/dev/sdb']
Exit code: 1
Reason: -
Stdout: Checking that no-one is …
```
> cc_disk_setup.py: fix MBR single partition creation

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_azure_helper.py
The same default description is used for all error cases.
Remove this parameter in favor of assuming the default in all cases.  Future work will allow for error reporting with a customizable description using a different interface.
> sources/azure: drop description for report_failure_to_fabric()

- cloudinit/config/cc_resizefs.py
- tests/unittests/config/test_cc_resizefs.py
enqueue the btrfs resize operation when supported
```
Use btrfs enquque when available
btrfs has operations that are blocking and when we try to resize a btrfs filesystem we may be in a race condition with blocking operations. Use the enqueue feature introduced in btrfs 5.10 to queue our resize request until resize if possible to avoid the race condition.
```
This is a race condition and as such difficult to reproduce. Introduce the need for btrfs to do a resize blocking operation, such as rebalancing. Then trigger the resize request, it will fail. With a sufficiently new version of btrfs and this new code the resize will succeed.
- [x ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
- [ x] I have updated or …
> Use btrfs enquque when available

- tests/integration_tests/modules/test_lxd.py
LXD v 5.9 introduces a features.networks.zones default. Assert features.networks.zones when host provides this key. Cope with versions that do not surface this config.
```
tests: test_lxd assert features.networks.zones when present
LXD v 5.9 introduces a features.networks.zones default.
Assert features.networks.zones when host provides this key.
Cope with versions that do not surface this config.
```
failures on lunar:
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-lunar-ec2/5/#showFailuresLink
```
CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_OS_IMAGE=lunar tox -e integration-tests tests/integration_tests/modules/test_lxd.py
```
> tests: test_lxd assert features.networks.zones when present

- cloudinit/net/netplan.py
- tests/unittests/test_net.py
- tools/.github-cla-signers
```
network/netplan: add gateways as on-link when necessary
When the gateway isn't part of the subnet's network, the "on-link" flag is required for the route to work.
LP: #2000596
```
This is a fix for https://bugs.launchpad.net/cloud-init/+bug/2000596
I don't know if I should also do this for additional `routes`, please let me know.
I have added a unit test which adds an on-link IPv4 and IPv6 gateways.
> network/netplan: add gateways as on-link when necessary

- cloudinit/config/cc_wireguard.py
```
When starting `wg-quick` service of an already configured system due to meta-data changed, 
changes in Wireguard config won't be loaded as the service already runs during cloud-init config 
section. Restart `wg-quick` systemd service to fix this behavior and improve idempotency.
```
no new test steps required
> Improve Wireguard module idempotency

- cloudinit/config/cc_set_passwords.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_set_passwords.py
```
cc_set_passwords: Move ssh status checking later
If the service starts between checking status and writing config, then
the new config will no longer be applied. Move the status checking later
so the config is already written before we check if restart needed.
LP: #1998526
```
I'm not sure this is the best way to handle this. Previously, if the service response indicates ssh won't run at all, we wouldn't write the sshd config at all. With this new way, we write the config regardless, but then don't attempt restart it'll fail. We could instead check early, then check again late, but that seemed like needless additional status checking. Writing out the config shouldn't hurt anything and will take less time than shelling out to systemctl.
Tests still need to be updated. More looking to …
> cc_set_passwords: Move ssh status checking later (SC-1368)

- cloudinit/sources/DataSourceVultr.py
- cloudinit/sources/helpers/vultr.py
- tests/unittests/sources/test_vultr.py
```
Fix a bug related to the region being reassigned and breaking init-local when cache is used. 
```
* Deploy vultr instance
* Reboot
> Fix issue regarding cache and region codes

- debian/changelog
- debian/patches/retain-netplan-world-readable.patch
- debian/patches/series
Stable releases need to keep 50-cloud-init.yaml world-readable to avoid change in behavior.
This change was introduced in Lunar, so Bionic, Focal, Jammy and Kinetic need to set this feature False.
```
* update changelog 
* Add patch retain-netplan-world-readable.patch
Keep /etc/netplan/50-cloud-init.yaml a world-readable.
Backport of 9e6f7ed6e.
```
This branch was built
> Add patch retain-netplan-world-readable.patch

- cloudinit/sources/DataSourceLXD.py
- tests/unittests/sources/test_lxd.py
LXD 4.0 will not get a backport of the  devices route on LXD socket API. This prevented launching Jammy from hosts with LXD 4.0.
Allow cloud-init to support LXD backplanes without the "devices" route and use fallback network config when absent.
LP: #2001737
```
lxd: handle 404 from missing devices route for LXD 4.0
LXD 4.0 will not get a backport of the  devices route on LXD socket
API. This prevented launching Jammy from hosts with LXD 4.0.
Allow cloud-init to support LXD backplanes without the "devices"
route and use fallback network config when absent.
LP: #2001737
```
> lxd: handle 404 from missing devices route for LXD 4.0

- .github/workflows/check_format.yml
- .travis.yml
```
test: move doc test from travis to actions
Changes:
- drop unnecessary setuptools pin
- use current RTD Python version 3.10.8
```
Makes doc failures visible sooner via gh actions, plus reduce CI bill. This is mostly just copy / paste from existing gh actions tests and the current travis test - low impact / low effort.
FYI @s-makin I mentioned this would be possible today while we were wrapping up #1933.
> ci: doc to gh actions

- config/cloud.cfg.tmpl
```
Add mount_default_fields for PhotonOS.
Otherwise, this is results in some weird contention with systemd default service and cloud-init.service doesn't start at random intervals on Photon OS.
```
> Add mount_default_fields for PhotonOS.

- .github/workflows/check_format.yml
- .github/workflows/unit.yml
- .travis.yml
```
ci: switch unittests to gh actions
```
Followup to https://github.com/canonical/cloud-init/pull/1951, which introduced Python version installs in gh actions. Same reasons as before: makes failures visible sooner, reduce CI bill.
> switch unittests to gh actions

- cloudinit/config/cc_set_passwords.py
- tests/integration_tests/modules/test_set_password.py
- tests/unittests/config/test_cc_set_passwords.py
Well this one is embarrassing. Added an integration test to check the logs.
```
Fix wrong subp syntax in cc_set_passwords.py
In #1909, I added a subp call with incorrect syntax. Fixing that here.
```
> Fix wrong subp syntax in cc_set_passwords.py

- doc/rtd/reference/datasources/cloudsigma.rst
```
doc: fix link
```
@CalvoM noted a broken link in https://github.com/canonical/cloud-init/pull/1958 (thanks!). A grep for "topics" in the docs showed another issue like it. This one is currently not "broken" due to the redirects, but assuming we don't want to maintain those forever lets fix this one as well.
> link is working because of the redirects, but fix it anyways

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
Early attempts to fetch metadata on Azure may fail with connection errors.  While this class of errors is not ideal to retry on, the impact is minimal given that:
1. retries are fairly limited (10)
2. Persistent connection errors would indicate that cloud-init is using a non-primary NIC which is a rare case of failure that will be addressed in the future.
> sources/azure: retry on connection error when fetching metdata

- cloudinit/distros/rhel.py
- tools/.github-cla-signers
Debugging a related issue, I found that the determination of the "previous-hostname" was wrong an RHEL-based distributions.
In `distros/__init__.py`: update_hostname() has this code:
```
prev_hostname = self._read_hostname(prev_hostname_fn)
...
(sys_fn, sys_hostname) = self._read_system_hostname()
...
if sys_hostname and prev_hostname and sys_hostname != prev_hostname:
LOG.info(
"%s differs from %s, assuming user maintained hostname.",
prev_hostname_fn,
sys_fn,
)
return
```
sys_hostname was found to contain a trailing newline, while prev_hostname did not. `sys_hostname != prev_hostname` is therefore always true. The check effectively reduces to:
```
if sys_hostname and prev_hostname:
```
Evidence can be found in the log file, as "assuming user maintained hostname", even when this is not …
> distros/rhel.py: _read_hostname() missing strip on "hostname"

- cloudinit/config/cc_set_hostname.py
- tests/unittests/config/test_cc_set_hostname.py
If the file exists but is empty, do nothing.
Otherwise cloud-init will crash because it does not handle the empty file.
RHBZ: 2140893
Signed-off-by: Emanuele Giuseppe Esposito <eesposit@redhat.com>
```
Start an instance running RHEL-9.1 on aws t4g.large system, after reboot system via sysrq 'b', the system is not accessible via ssh and cloudinit service failed to start.
$ cat cloud-init.service.log
× cloud-init.service - Initial cloud-init job (metadata service crawler)
Loaded: loaded (/usr/lib/systemd/system/cloud-init.service; enabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Tue 2022-11-08 02:33:59 UTC; 19min ago
Process: 703 ExecStart=/usr/bin/cloud-init init (code=exited, status=1/FAILURE)
Main PID: 703 (code=exited, status=1/FAILURE)
CPU: 424ms
Nov 08 …
```
> cc_set_hostname: ignore /var/lib/cloud/data/set-hostname if it's empty

- cloudinit/net/network_state.py
- tests/unittests/test_net.py
```
Fix default route rendering on v2 ipv6
::/0 would get rendered as ::/64 rather than ::/0 across all renderers
using ipv6 in a v2 config.
LP: #2003562
```
> Fix default route rendering on v2 ipv6

- cloudinit/config/cc_ssh.py
- tests/unittests/config/test_cc_ssh.py
- tools/.github-cla-signers
private keys should have 0600: https://www.tenable.com/audits/items/CIS_Google_Container_Optimized_OS_v1.0.0_L1_Server.audit:6225b8224fbd4f360ebdc72c56f3eae9
public keys should have 0644: https://www.tenable.com/audits/items/CIS_Google_Container_Optimized_OS_v1.0.0_L1_Server.audit:7f016cd406100a1ee2ad94834111f005
```
fix: permissions for SSH host keys
If the host-keys are automatically generated the private key has 0640 which should be 0600 so no group or other can see the private key. The public key is correctly set to 0644.
If the host-keys are provided the script generated the private key with 0600 which is indeed correct. But the public key is also 0600 which should be instead 0644.
With this change the private key is always 0600 and the public key is always 0644.
```
During the …
> Fix permission of SSH host keys

- .github/workflows/integration.yml
- .travis.yml
```
ci: migrate integration-test to gh actions
changes:
- drop caching machinery for LXD images and chroots
- divide the workflow in two steps, one for building packages
and other for running the tests so that the second one can
be retried in case of error
```
I have not ported the caching machinery for LXD images and chroots, as in my opinion it is not worth the complexity vs the gains, but I am open to other opinions.
> CI: migrate integration-test to GH actions

- systemd/cloud-init.service.tmpl
Newer SUSE distributions are switching to NetworkManager from wicked. For those distributions we need to wait for NetworkManager before starting the cloud-init service.
- [x ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
> Wait for NetworkManager

- cloudinit/config/cc_set_passwords.py
- tests/integration_tests/modules/test_set_password.py
```
Prevent traceback when restarting ssh
On Bionic in GCE, when restarting ssh, it's not uncommon to see a
traceback with `ssh.service is not active, cannot reload.`. Instead log
a warning.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-gce/171/testReport/junit/tests.integration_tests.modules.test_set_password/TestPasswordListString/test_check_ssh_service/
> cc_set_passwords: Prevent traceback when restarting ssh

- cloudinit/config/cc_resolv_conf.py
- doc/rtd/reference/network-config.rst
```
docs: Clarify networking docs
- Add stronger warnings for resolv_conf module.
- Add link to lxd network config docs.
```
I really don't like the current [networking docs](https://cloudinit.readthedocs.io/en/latest/reference/network-config.html), which has just a list of links to datasources and which formats they support. I think we could do a lot to improve user discovery of information for "how to use the format", however I don't want so do that in this PR so I'm just adding the LXD external link and kicking the "refactor network docs" can down the road.
Additionally I think stronger wording around the resolv_conf module is warranted, and some outdated statements removed.
[LP: #2004131](https://bugs.launchpad.net/cloud-init/+bug/2004131)
> improve resolvconf and network docs

- cloudinit/config/cc_puppet.py
- tests/integration_tests/modules/test_puppet.py
- tests/unittests/config/test_cc_puppet.py
```
cc_puppet: Update puppet service name
From Lunar, we see that the default puppet version is 7.20 which replaces `puppet.service` 
with `puppet-agent.service`. Thus, we need to have a way of calling the appropriate service 
depending with the ubuntu release.
LP: #2002969 
```
Run the tests at `tests/integration_tests/modules/test_puppet.py` on `Lunar`
> cc_puppet: Update puppet service name

- cloudinit/sources/DataSourceVultr.py
- cloudinit/sources/helpers/vultr.py
- tests/unittests/sources/test_vultr.py
```
cloud_interfaces is intended to be a netcfg. Change the helper function to reflect this.
```
> Fix Vultr cloud_interfaces usage

- cloudinit/stages.py
- tests/unittests/test_stages.py
```
Warn on empty "network" key.
It is possible to create an empty network key that fails
over to fallback network config without warning. Fix it.
```
Found by copying a config from Launchpad. I think Launchpad may have caused the weird whitespace.
> Warn on empty network key

- tests/integration_tests/modules/test_set_password.py
```
tests: Remove restart check from test
If no SSH restart happens, we get no log. Since this is perfectly
normal, we shouldn't be checking for a log.
```
> tests: Remove restart check from test

- cloudinit/sources/__init__.py
- tests/integration_tests/modules/test_combined.py
- tests/unittests/sources/test_init.py
```
cloud-id: better handling when diff in ds
Stop deleting cloud-id in Azure whenever we have change in the contents 
of the cloud-id. 
LP: #1998998
```
> cloud-id: better handling of change in datasource files

- cloudinit/net/netplan.py
- tests/unittests/distros/test_netconfig.py
```
netplan: keep original permissions when 50-cloud-init.yaml exists
To avoid limiting permissions of netplan config across package
upgrade, pass preserve_mode=True when writing 50-cloud-init.yaml.
Ensure any custom permissions are retained across package upgrade
even when netplan config is rewritten across system reboot
```
https://warthogs.atlassian.net/browse/SC-1375
> netplan: keep original permissions when 50-cloud-init.yaml exists

- doc/rtd/conf.py
```
docs: fix 404 CSS render use default notfound_urls_prefix in RTD conf
404 styling was off due to invalid config
notfound_urls_prefix = "/"
Drop custom config. The default "/en/latest"
value properly renders the 404 page with style.
```
Current poor 404 rendering:
https://cloudinit.readthedocs.io/en/asdf
Test rendering built using this branch
https://cloudinit.readthedocs.io/en/rtd-build/asdf
> docs: fix 404 CSS render use default notfound_urls_prefix in RTD conf

- debian/patches/retain-netplan-world-readable.patch
Daily build recipes are broken on unittests because the feature NETPLAN_ROOT_READONLY is False on older releases. 
Add mocks to the downstream quilt patch to setup expectation of a True value.
BUILD - failure on unittests: https://launchpadlibrarian.net/650230318/buildlog_ubuntu-jammy-amd64.cloud-init_22.4.daily-202302071231-ce78c1bf~ubuntu22.04.1_BUILDING.txt.gz
```
git checkout upstream/main -B main
quilt push -a # assert quilt patches apply without fuzz/errors
tox -e py3 # assert unittests pass
quilt pop -a # assert quilt patches are cleanly removed
```
> d/patches: daily build recipe mock netplan root-readonly feature true

- .github/workflows/check_format.yml
- CONTRIBUTING.rst
- tools/.github-cla-signers
- tools/check-cla-signers
```
ci: sort and add checks for cla signers file
This sorts the CLA signers file and adds a convenience script for users
to check and sort the file.
A workflow job - which uses the script - makes sure that the file does
not get merged in an unsorted state.
```
Feel free to let me know if this is overkill. :)
> ci: sort and add checks for cla signers file

- cloudinit/config/schema.py
- cloudinit/safeyaml.py
- cloudinit/user_data.py
- tests/unittests/config/test_schema.py
- tests/unittests/test_safeyaml.py
Fix a bug in nested mapping annotations:
The following now can be annotated without keyerrors
users:
- default
-   lock-passwd: false
name: root
```
cli: schema validate vendor-data fix nested annotations
Fix a bug in nested mapping annotations:
The following now can be annotated without keyerrors
users:
- default
-   lock-passwd: false
name: root
```
> cli: schema also validate vendor-data fix nested annotations

- cloudinit/config/cc_disk_setup.py
- tests/unittests/config/test_cc_disk_setup.py
```
disk_setup: use byte string when purging the partition table
This writes a byte string to the device instead of a string when
purging the partition table.
Essentially, this will prevent the error "a bytes-like object is
required, not 'str'" from happening.
```
This will prevent the error "a bytes-like object is required, not 'str'" from happening.
Using the following disk setup in the user-data:
```yaml
device_aliases:
my_disk: /dev/vdb
disk_setup:
my_disk:
layout: remove
overwrite: true
```
Results in an error/warning in the cloud-init log:
```
2023-02-08 20:48:55,158 - util.py[WARNING]: Failed partitioning operation
a bytes-like object is required, not 'str'
```
> disk_setup: use byte string when purging the partition table

- cloudinit/config/cc_ca_certs.py
- doc/examples/cloud-config-ca-certs.txt
- tests/integration_tests/modules/test_ca_certs.py
- tests/unittests/config/test_cc_ca_certs.py
```
summary: overhaul cc_ca_certs functionality
Change "ca-certs" references to "ca_certs".
New certificates are written to individual files, with an incrementing
number as part of their filename, rather than all being placed in a
single file. This resolves issues caused when certificate files
containing more than a single certificate are placed in /etc/ssl/certs
(by utilities such as "update-ca-certificates" run by ca_certs).
Alpine / Debian / Ubuntu:
The current behaviour, whilst it works, is incorrect with regard to
the design of the underlying OS utilities for managing certificates.
For "remove_defaults" the system-installed certificate files should
not be actually deleted (otherwise it becomes problematic
if someone wishes to later re-enable one or more of them), rather
they should …
```
> overhaul cc_ca_certs functionality

- cloudinit/config/schema.py
- tests/integration_tests/modules/test_cli.py
- tests/unittests/config/test_schema.py
~~Changing to WIP as I just noticed https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-azure/192/testReport/junit/tests.integration_tests.modules/test_cli/test_valid_userdata/ , and this can probably also be rolled in here.~~
```
Fix minor schema validation regression and fixup typing
When annotating a schema, we should print "Valid cloud-config" along
with the filename if a file has been used rather than just the config
type.
```
Fixes https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-azure/192/testReport/junit/tests.integration_tests.cmd.test_schema/TestSchemaDeprecations/test_schema_deprecations/
Also, pyright was complaining because `config_files` could not be set, so I changed the `elif` to and `else` …
> Fix minor schema validation regression and fixup typing

- cloudinit/config/cc_ssh.py
- cloudinit/ssh_util.py
- tests/integration_tests/modules/test_ssh_keys_provided.py
- tests/unittests/config/test_cc_ssh.py
- tests/unittests/test_ssh_util.py
```
cc_ssh: support multiple hostcertificates
LP: #1999164
```
https://bugs.launchpad.net/cloud-init/+bug/1999164
```sh
CLOUD_INIT_KEEP_INSTANCE=true tox -e integration-tests -- tests/integration_tests/modules/test_ssh_keys_provided.py::TestSshKeysProvided
$ systemctl status ssh
$ sshd -T | grep -i hostcertificate
hostcertificate /etc/ssh/ssh_host_ed25519_key-cert.pub
hostcertificate /etc/ssh/ssh_host_rsa_key-cert.pub
```
> cc_ssh: support multiple hostcertificates (SC-1425)

- cloudinit/distros/freebsd.py
- tests/unittests/distros/test__init__.py
```
add function is_virtual to distro/FreeBSD
- is_virtual property dentifies identify if the thing we're running
is any kind of virtualization
- virtual() identifies what kind of virtualisation we're dealing with
- is_container() tells us if we're running in a container, or in FreeBSD's
case, in a jail.
- the helper functions are @lru_cached, since this is very unlikely to
change
Co-authored-by: Brett Holman <brett.holman@canonical.com>
```
see discussions in #1923 
We can consider merging this after that PR.
> add function is_virtual to distro/FreeBSD

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/imds.py
- tests/unittests/sources/azure/test_imds.py
- tests/unittests/sources/test_azure.py
Create new azure package for better organization and move IMDS logic for fetching into it.
Functional changes include comprehensive retry logic:
- Re-use metadata retry codes for reprovision data, even if these codes are unused.  There shouldn't be any regressive behavior as these codes currently would result in a retry after re-performing DHCP by the caller.
- Use 10 retries for reprovision data instead of infinite and custom exception callback.
Future work will clean up the test_azure.py tests a little further thanks to these changes, but wanted to minimize churn here to make changes fairly visible.
> sources/azure: refactor imds handler into own module

- cloudinit/sources/DataSourceLXD.py
- tests/unittests/sources/test_lxd.py
```
lxd: Retry if the server isn't ready
```
```
File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 946, in find_source
if s.update_metadata_if_supported(
File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 828, in update_metadata_if_supported
result = self.get_data()
File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 373, in get_data
return_value = self._get_data()
File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceLXD.py", line 193, in _get_data
self._crawled_metadata = util.log_time(
File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2680, in log_time
ret = func(*args, **kwargs)
File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceLXD.py", line …
```
> lxd: Retry if the server isn't ready

- cloudinit/config/cc_write_files.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- cloudinit/util.py
- tests/integration_tests/modules/test_write_files.py
- tests/unittests/test_util.py
- tools/.github-cla-signers
```
summary: Set ownership for new folders in Write Files Module
The parent directory would be created automatically if it does not exist. But the ownership of newly-created parent directory would always be root.
With this change, it would be set the same as `owner`.
LP: #1990513
```
```yaml
write_files:
- path: /home/ubuntu/.help/file-in.txt
content: |
hi in
owner: 'ubuntu:ubuntu'
permissions: '0644'
defer: true
```
With this change, the owner of `/home/ubuntu/.help`  would be `ubuntu`.
Without this change, the owner of `/home/ubuntu/.help`  would be `root`.
> Set ownership for new folders

- cloudinit/config/cc_zypper_add_repo.py
- cloudinit/distros/opensuse.py
- tests/unittests/distros/test_opensuse.py
openSUSE/SUSE has distros that use read only root and btrfs. To update a running system in such a setup the transactional-update command needs to be used. This change implements support for use of the transactional-update commend when appropriate.
```
Support transactional-updates for SUSE based distros
```
- [ x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
- [x ] I have updated or added any unit tests accordingly
> Support transactional-updates for SUSE based distros

- cloudinit/config/cc_ca_certs.py
- tests/unittests/config/test_cc_ca_certs.py
- Enable SUSE based distros to be supported for CA handling
- Do not let the test bleed through to the underlying system where the test is run
```
summary: Enable SUSE based distros to be supported for CA handling
CA handling in he configuration module was previously not supported for SUSE based distros. Enable this functionality
by creating the necessary configuration settings.
Secondly update the test such thta it does not bleed through to the test system
```
- [ x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
- [x ] I have updated or added any unit tests accordingly
> Enable SUSE distros for ca handling

- cloudinit/cmd/main.py
- cloudinit/config/cc_apt_configure.py
- cloudinit/config/cc_ca_certs.py
- cloudinit/config/cc_growpart.py
- cloudinit/config/cc_rsyslog.py
- cloudinit/config/cc_set_passwords.py
- cloudinit/config/cc_update_etc_hosts.py
- cloudinit/config/schema.py
- cloudinit/distros/__init__.py
- cloudinit/distros/ug_util.py
- cloudinit/log.py
- cloudinit/net/network_state.py
- cloudinit/netinfo.py
- cloudinit/stages.py
- cloudinit/util.py
- doc/rtd/reference/faq.rst
- tests/integration_tests/modules/test_combined.py
- tests/unittests/config/test_cc_ca_certs.py
- tests/unittests/config/test_schema.py
- tests/unittests/distros/test_create_users.py
- tests/unittests/net/test_network_state.py
- tests/unittests/test_log.py
- tests/unittests/test_net.py
```
log: Add standardized deprecation tooling
- Add deprecation log level
- Add deprecation utilities for structured format and messaging
- Update existing deprecation log sites, add deprecated versions
```
Barring any objections to the approach, dedup and integration tests will follow.
This change allows us to consistently make clear deprecation expectations with specific versions in all cases. This messaging is required to ensure community members have sufficient time to react to impending change - to either update their configs or make a case for the necessity of the deprecated feature.
> log: Add standardized deprecation tooling (SC-1312)

- cloudinit/net/dhcp.py
- cloudinit/net/ephemeral.py
- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/DataSourceEc2.py
- cloudinit/sources/DataSourceGCE.py
- cloudinit/sources/DataSourceHetzner.py
- cloudinit/sources/DataSourceOpenStack.py
- cloudinit/sources/DataSourceOracle.py
- cloudinit/sources/DataSourceScaleway.py
- cloudinit/sources/DataSourceUpCloud.py
- cloudinit/sources/helpers/vultr.py
- tests/unittests/net/test_ephemeral.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_ec2.py
- tests/unittests/sources/test_hetzner.py
- tests/unittests/sources/test_openstack.py
- tests/unittests/sources/test_oracle.py
- tests/unittests/sources/test_upcloud.py
```
dhcp: Cleanup unused kwarg.
Usage was dropped in de7851b93c5a2d4658.
```
Pick up a couple of bits missed in https://github.com/canonical/cloud-init/pull/1715
> drop unused kwarg

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/imds.py
- tests/unittests/sources/azure/test_imds.py
- tests/unittests/sources/test_azure.py
sources/azure: fix regressions in IMDS behavior
There are effectively two regressions in the recent IMDS refactor:
1. The metadata check len(imds_md["interface"]) in
_check_if_nic_is_primary() is no longer correct as the refactor
switched URLs and did not update this call to account for the
fact that this metadata now lives under "network".
2. Network metadata was fetched with infinite=True and is now limited
to ten retries.  This callback had the twist of only allowing up to
ten connection errors but otherwise would retry indefinetely.
For check_if_nic_is_primary():
- Drop the interface count check for _check_if_nic_is_primary(),
we don't need it anyways.
- Fix/update the unit tests mocks that allowed the tests to pass,
adding another test to verify max retries for http and connection …
> sources/azure: fix regressions in IMDS behavior

- cloudinit/distros/__init__.py
- cloudinit/distros/freebsd.py
- cloudinit/sources/DataSourceOpenStack.py
- cloudinit/sources/__init__.py
- doc/examples/cloud-config-datasources.txt
- tests/unittests/distros/test__init__.py
- tests/unittests/sources/test_openstack.py
- tests/unittests/test_ds_identify.py
- tests/unittests/util.py
- tools/ds-identify
```
source: Force OpenStack when it is only option
Running on OpenStack Ironic was broken in 1efa8a0a0,
which prevented a system configured to run on only
Openstack from actually running this ds. This change
also prevents the kernel commandline override from
working. This change was required to prevent
unnecessarily probing OpenStack on Ec2, and is
therefore still required. 
This commit reverts an earlier attempt[1][2] to
automatically detect OpenStack, due to regression
it caused. Additionally, this change allows a
system that defines a datasource list containing
only [OpenStack] or [OpenStack, None] to attempt
running on OpenStack, overriding ds_detect(). A
datasource list that defines [OpenStack, None]
still falls back to DataSourceNone if OpenStack
fails to reach the IMDS.
This change …
```
> Force OpenStack When It Is Only Datasource in datasource_list

- cloudinit/sources/DataSourceOracle.py
- tests/integration_tests/datasources/test_oci_networking.py
- tests/unittests/sources/test_oracle.py
```
oracle-ds: prefer system_cfg over ds network config source
Bump system_cfg over ds network_config_source for Oracle DS,
so that if network config is defined under /etc/cloud,
it will be honored.
In a previous change, we moved the initramfs and system_cfg
bellow ds to favor ds, but this implied system-wide configs
were always not honored.
LP: #1956788
```
https://bugs.launchpad.net/cloud-init/+bug/1956788
https://warthogs.atlassian.net/browse/SC-1414
https://warthogs.atlassian.net/browse/CPC-1975
```sh
CLOUD_INIT_PLATFORM="oci" CLOUD_INIT_CLOUD_INIT_SOURCE=$(ls cloud*.deb) tox -e integration-tests -- -vv tests/integration_tests/datasources/test_oci_networking.py::test_oci_networking_system_cfg
```
> oracle-ds: prefer system_cfg over ds network config source (SC-1414)

- tests/integration_tests/modules/test_combined.py
```
tests: write to /var/spool/rsyslog to adhere to apparmor profile
AppArmor is active on 23.04. It prevents writing to /var/tmp.
Integration tests now write to /var/spool/rsyslog/cloudinit.log to
assert working config.
```
- 23.04 enabled rsyslog apparmor profile. This profile doesn't allow for file writes to /var/tmp/
https://git.launchpad.net/ubuntu/+source/rsyslog/commit/?id=449cc82460d0b3209751c8a96450f02a5a3b85b3
- Fix Lunar jenkins failed runs like https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-lunar-azure/lastSuccessfulBuild/testReport/tests.integration_tests.modules.test_combined/TestCombined/test_rsyslog/
`CLOUD_INIT_PLATFORM=lxd_container CLOUD_INIT_OS_IMAGE=lunar tox -e integration-tests …
> tests: write to /var/spool/rsyslog to adhere to apparmor profile

- doc/rtd/conf.py
- doc/rtd/static/css/custom.css
Docs: cosmetic improvements and styling
```
A series of cosmetic docs changes that will make them look more like the
documentation produced on Ubuntu.com. It's not *exactly* the same, but
close enough to make it look recognisable as Canonical docs.
Although I tried to test this on a variety of screen sizes, if you spot
anything that doesn't render right or looks weird, please let me know. The
default font sizes were problematic from an accessibility pov so I made
them larger. They are still variable so they should render right on smaller
screens but it's possible I missed some.
Code literals are now the same size as regular font for the same reason,
but made slightly bolded to help pick them out from text (which should
help e.g. when commands are included as inline text and not a code …
```
> docs: cosmetic improvements

- cloudinit/config/cc_grub_dpkg.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_grub_dpkg.py
```
config: Update grub-dpkg docs
```
We should always describe config key metadata in the appropriate schema field rather than in the module description.
> update grub-dpkg docs

- cloudinit/util.py
- tests/unittests/config/test_apt_configure_sources_list_v1.py
- tests/unittests/config/test_apt_source_v3.py
- tests/unittests/test_util.py
```
util: Skip dns resolution check for ip addresses
```
A slight optimization in the default case.
> do not attempt dns resolution on ip addresses

- cloudinit/config/cc_ca_certs.py
- tests/unittests/config/test_cc_ca_certs.py
```
summary: handle non existent ca-cert-config situation
Currently if a cert file doesn't exist, cc_ca_certs module crashes
This fix makes it possible to handle it gracefully.
Also, out_lines variable may not be available if os.stat returns 0.
This issue is also taken care of.
Added tests for the same.
```
> Ca certs fix

- debian/changelog
- debian/cloud-init.postinst
```
d/postinst: prefer yaml.safe_load. yaml.load requires Loader param
It's been deprecated for a while, Ubuntu 23.04 sync'd 6.0.1 which
dropped support for an optional Loader parameter making it required.
This broke dpkg-reconfigured cloud-init on MAAS Ubuntu 23.04 system
deployments which now exit non-zero due to changed yaml.load
call-signature.
LP: #2009746
```
```
lxc launch ubuntu-daily:lunar dev-l
lxc exec dev-l -- cloud-init status --wait --long
cat > debconf.settings <<EOF
cloud-init cloud-init/maas-metadata-url string SOMETEXT
EOF
lxc file push debconf.settings dev-l/
lxc exec dev-l -- dpkg-reconfigure -cloud-init
echo $?
build-package
sbuild --dist=lunar --arch=amd64  --arch-all ../out/cloud-init_*.dsc
lxc file push cloud-init*deb dev-l
lxc exec dev-l -- 'dpkg -i …
```
> d/postinst: prefer yaml.safe_load. yaml.load requires Loader param

- cloudinit/apport.py
- tests/unittests/test_apport.py
Do not prompt for CloudName when instance-data.json exists.
When instance-data.json exists, general-hooks/cloud_init.py will add the following fields to bug reports:
CloudName, CloudID, CloudPlatform and CloudSubplatform.
```
Do not prompt for CloudName when instance-data.json exists.
When instance-data.json exists, general-hooks/cloud_init.py will add the
following fields to bug reports:
CloudName, CloudID, CloudPlatform and CloudSubplatform.
```
> apport: only prompt for cloud_name when instance-data.json is absent

- debian/apport-general-hook.py
- debian/changelog
- debian/rules
- tools/.github-cla-signers
```
Add Apport general hook
Apport 2.25.0-0ubuntu1 removed the buggy `add_cloud_info` from the
ubuntu general hook. Add an Apport general hook that reads
`/run/cloud-init/instance-data.json` if present.
LP: #1724623
Thanks for the initial version: John Chittum
```
> Add Apport general hook

- debian/apport-general-hook.py
- debian/changelog
- debian/rules
- tools/.github-cla-signers
Reflecting @bdrung's #2020 to all `ubuntu/*` downstream branches we support 
```
Add Apport general hook
Apport 2.25.0-0ubuntu1 removed the buggy `add_cloud_info` from the
ubuntu general hook. Add an Apport general hook that reads
`/run/cloud-init/instance-data.json` if present.
LP: #1724623
Thanks for the initial version: John Chittum
```
> apport general-hook

- debian/apport-general-hook.py
- debian/changelog
- debian/rules
- tools/.github-cla-signers
Reflecting @bdrung's #2020 to all `ubuntu/*` downstream branches we support 
```
Add Apport general hook
Apport 2.25.0-0ubuntu1 removed the buggy `add_cloud_info` from the
ubuntu general hook. Add an Apport general hook that reads
`/run/cloud-init/instance-data.json` if present.
LP: #1724623
Thanks for the initial version: John Chittum
```
created with:
```
git cherry-pick  b2481a883c5b5b86c5b6488bf73c5cf9f25c4ecf
git cherry-pick 50c1ca1c6d80f3d120e1ec99e50ecffe2a57c857
```
> jammy: apport general-hook

- debian/apport-general-hook.py
- debian/changelog
- debian/rules
- tools/.github-cla-signers
Reflecting @bdrung's #2020 to all `ubuntu/*` downstream branches we support 
```
Add Apport general hook
Apport 2.25.0-0ubuntu1 removed the buggy `add_cloud_info` from the
ubuntu general hook. Add an Apport general hook that reads
`/run/cloud-init/instance-data.json` if present.
LP: #1724623
Thanks for the initial version: John Chittum
```
> apport general-hook apport 

- cloudinit/config/cc_ansible.py
- tools/.github-cla-signers
The code examples provided for cloud-init with the cc-ansible.py module are not accurate. The "package_name" parameter is mandatory and must be included in the example code. To improve the usability of these examples, they should be updated to include all necessary parameters and reflect the current best practices for using cc-ansible with cloud-init.
> Ansible complete the examples and doc

- cloudinit/net/__init__.py
- cloudinit/net/dhcp.py
- tests/unittests/net/test_dhcp.py
- tools/.github-cla-signers
Sending dhclient command failed for InfiniBand ports because dhcp-client-identifier is not specified.
So, providing this patch to allow send dhcp-client-identifier hardware with the dhclient command for InfiniBand ports.
```
```
> send dhcp-client-identifier with dhclient command for InfiniBand ports

- cloudinit/config/cc_ca_certs.py
```
summary: Fedora: Enable CA handling
Fedora wasn't previously supported for CA handling. Enabling this 
allows the testsuite to pass when ran on a Fedora system. The conf
override is the same as for rhel.
```
> Fedora: Enable CA handling

- cloudinit/net/__init__.py
- tests/unittests/test_net.py
- tools/.github-cla-signers
```
macs: ignore duplicate MAC for devs with driver driver qmi_wwan
Another physical modem which has duplicate MAC addresses.
Cloud-init needs to ignore the subordinate devices which are
associated with the qmi_wwan driver.
Fixes network rendering for the following modems:
Quectel EG25
Quectel RM510Q-GLHA
Sierra Wireless MC7455
LP: #2008888
```
> macs: ignore duplicate MAC for devs with driver driver qmi_wwan

- tests/unittests/sources/conftest.py
Recent changes to override_ds_detect() triggers a call to get_cmdline(), which invokes subp.subp() for various container checks.  This causes tests to fail when running a specific test module instead of the full set.  This is because test_smartos.py on module load will trigger these calls and the lru_cache() will retain the results.  So if the module does not load, the tests will fail.
Patch util.get_cmdline() for all data source tests to avoid this behavior.
> tests/sources: patch util.get_cmdline() for datasource tests

- cloudinit/net/eni.py
- cloudinit/net/sysconfig.py
- tests/unittests/distros/test_netconfig.py
```
Don't change permissions of netrules target
Set permissions if file doesn't exist. Leave them if it does.
LP: #2011783
```
https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2011783
> Don't change permissions of netrules target

- tests/unittests/sources/test_vmware.py
Patch is_vmware_platform to return False to avoid failure:
```
def test_no_data_access_method(self):
ds = get_ds(self.tmp)
ds.vmware_rpctool = None
>       ret = ds._get_data()
tests/unittests/sources/test_vmware.py:104:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cloudinit/sources/DataSourceVMware.py:193: in _get_data
if require_vmware_platform and not is_vmware_platform():
cloudinit/sources/DataSourceVMware.py:401: in is_vmware_platform
system_type = dmi.read_dmi_data("system-product-name")
cloudinit/dmi.py:180: in read_dmi_data
return _call_dmidecode(key, dmidecode_path)
cloudinit/dmi.py:130: in _call_dmidecode
(result, _err) = subp.subp(cmd)
E       RuntimeError: called subp. set …
```
> tests/vmware: fix test_no_data_access_method failure

- tests/unittests/net/test_dhcp.py
- tests/unittests/test_util.py
Oof. We had a number of unit tests not actually checking anything.
Still having problems with `test_url_helper.py` (it's 3.12 specific), but figured I'd at least get this much up.
```
Fix Python 3.12 unit test failures
```
> Fix Python 3.12 unit test failures

- cloudinit/sources/azure/imds.py
- tests/unittests/sources/azure/test_imds.py
- tests/unittests/sources/test_azure.py
When fetching metadata in _check_if_nic_is_primary() the retry count is 300, but fails out after 10 connection errors.  In some cases, fetching from IMDS may fail with read timeout for more than 10 attempts, far sooner than the desired 300.
Keeping the existing max_connection_errors = 10 is fine so long as it is truly a connection error.  These generally shouldn't occur when using the primary NIC.
Always retry on timeout errors (up until desired limit) and count only connections errors against max_connection_errors.
> sources/azure/imds: don't count timeout errors as connection errors

- cloudinit/config/schema.py
- tests/unittests/config/test_schema.py
- tests/unittests/helpers.py
```
schema: do not manipulate draft4 metaschema for jsonschema 2.6.0
Only set additionalProperties = False in unittest
draft4 schema definition because cloud-init globally
registers its draft4 extensions as the primary validator
for any draft4 schemas in the python process.
This affects solutions such as subiquity and
ubuntu-desktop-installer which invoke jsonschema.validate
in the same process at runtime just after calling
cloudinit.schema.get_jsonschema_validator.
The resulting Tracebacks are seen as something like:
jsonschema.exceptions.SchemaError:
{'$ref': '#/definitions/ref_id'} is not valid under any of the
given schema
Background:
cloud-init needs to extend draft4 schema to better
validate and warn 'deprecated' properties in draft4-based
cloud-init schema definitions. Our …
```
> schema: do not manipulate draft4 metaschema on jsonschema 2.6.0

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
Pull out remaining PPS handling bits from _poll_imds() and add two explicit methods for the overloaded path:
- _wait_for_pps_running_reuse() for running PPS logic.
- _wait_for_pps_unknown_reuse() for unknown and recovery PPS logic.
For consistency:
- Rename _wait_for_all_nics_ready() -> _wait_for_pps_savable_reuse().
- Move reporting ready logic into _wait_for_pps_os_disk_shutdown().
Drop several impacted tests as coverage already exists in TestProvisioning, and update the rest to handle the +/- 1 DHCP attempt due to varying assumptions around PPS state and DHCP.
> sources/azure: move pps handling out of _poll_imds()

- cloudinit/net/dhcp.py
- tests/unittests/net/test_dhcp.py
Some variants of dhclient will exit with non-zero codes on lease failure. For example, on RHEL 8.7:
```
[cpatterson@test-rhel87 ~]$ sudo /usr/sbin/dhclient -1 -v -lf /tmp/my.lease -pf /tmp/my.pid bridge2nowhere -sf /bin/true
Internet Systems Consortium DHCP Client 4.3.6
Copyright 2004-2017 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Listening on LPF/bridge2nowhere/42:ef:d5:38:1d:19
Sending on   LPF/bridge2nowhere/42:ef:d5:38:1d:19
Sending on   Socket/fallback
Created duid "\000\004E<\225X\232\304J\337\243\026T\324\243O\270\177".
DHCPDISCOVER on bridge2nowhere to 255.255.255.255 port 67 interval 4 (xid=0x777bc142)
DHCPDISCOVER on bridge2nowhere to 255.255.255.255 port 67 interval 7 (xid=0x777bc142)
DHCPDISCOVER on …
```
> net/dhcp: catch dhclient failures and raise NoDHCPLeaseError

- cloudinit/config/cc_resizefs.py
- tests/unittests/config/test_cc_resizefs.py
Anh pointed out that the daily PPA builds were crashing due to refactor: stop passing log instances to cc_* handlers (#2016).
When dropping the logger argument, the tuple became a list which then gets expanded in the call to do_resize() and crashes.
```
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 257, in _run_modules
    run_name, mod.handle, func_args, freq=freq
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 67, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 172, in run
    results = functor(**args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_resizefs.py", line 309, in handle
    …
```
> config/cc_resizefs: fix do_resize arguments

- cloudinit/config/cc_ssh.py
- cloudinit/ssh_util.py
- tests/unittests/config/test_cc_ssh.py
```
With this change the private key is 0600
LP: #2011291
```
> Fix permission of the private key when openssh is not earlier than 9.0

- cloudinit/net/ephemeral.py
- tests/unittests/net/test_init.py
I analyze the code and find that the following function is normally used to perform the cleanup operation:
https://github.com/canonical/cloud-init/blob/main/cloudinit/net/ephemeral.py#L332
```pycon 
def __exit__(self, excp_type, excp_value, excp_traceback):
"""Teardown sandboxed dhcp context."""
self.clean_network()
def clean_network(self):
"""Exit _ephipv4 context to teardown of ip configuration performed."""
if self.lease:
self.lease = None
if not self._ephipv4:
return
self._ephipv4.__exit__(None, None, None)
```
Therefore, if the following log exists:
subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'add', 'x.x.x.x/18', 'broadcast', 'x.x.x.x', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
the following logs should exist:
subp.py[DEBUG]: …
> ensure do clean network

- tools/.github-cla-signers
I signed the Canonical CLA on behalf of Akamai; this change adds myself and two ICs from Akamai who are associated with my organization to the github-cli-signers file to allow them to contribute on the organization's behalf.
> Adding contributors for DataSourceAkamai

- cloudinit/sources/DataSourceScaleway.py
- tests/unittests/sources/test_scaleway.py
```
summary: Adapt DataSourceScaleway to upcoming IPv6 support
Add support for IPv4 and/or IPv6 provided metadata. Upcoming
features will allow for Instances to be started with only IPv6
connectivity. The datasource must be able to fetch its metadata from
the following endpoints : 
* IPv4 on http://169.264.42.42/conf
* IPv6 on http://[fd00:42::42]/conf
This URL may eventually be overridden in the future by a DNS
resolvable URL defined in /etc/cloud/config.d/scaleway.conf
Add support for the configuration of one or many IP addresses when
provided by the `public_ips` metadata key.  In such configurations,
instances no longer have a `private_ip`. The previous configuration
method is kept for backward compatibility.
This commit also fixes a bug in the definition of ssh keys from tags.
``` …
> Adapt DataSourceScaleway to IPv6

- tests/integration_tests/test_kernel_commandline_match.py
- tools/ds-identify
```
Fix NoCloud kernel commandline semi-colon args.
This was broken in 612b4de892d on systemd systems.
Add an integration test for this codepath.
```
This codepath was already tested without ds-identify, ensure that this works with ds-identify too. 
Successful test run:
```
tests/integration_tests/test_kernel_commandline_match.py::test_lxd_datasource_kernel_override[ds=nocloud;s=http://my-url/-DataSourceNoCloud] 
---------------------------------------------- live log setup ----------------------------------------------
2023-04-07 21:17:44 INFO      integration_testing:clouds.py:70 Settings:
CLOUD_INIT_SOURCE=./cloud-init_all.deb
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=True
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OS_IMAGE=focal …
```
> Fix NoCloud Delimited Args

- cloudinit/sources/DataSourceNoCloud.py
- tests/integration_tests/test_kernel_commandline_match.py
```
NoCloud: Use seedfrom protocol to determine mode
Historically ds=nocloud-net was a required argument
for the user to pass in to tell cloud-init which mode
to use. This argument, however, is redundant when a
seedfrom argument is passed. Allow the mode to be
automatically determined, so that the user need not
pass a mode configuration to achieve desired behavior.
```
[context](https://github.com/canonical/cloud-init/pull/2093#issuecomment-1490989378)
> NoCloud: Use seedfrom protocol to determine mode

- systemd/cloud-init-hotplugd.service
- systemd/cloud-init-hotplugd.socket
- sysvinit/debian/cloud-config
- sysvinit/debian/cloud-final
- sysvinit/debian/cloud-init
- sysvinit/debian/cloud-init-local
- sysvinit/freebsd/cloudconfig
- sysvinit/freebsd/cloudfinal
- sysvinit/freebsd/cloudinit
- sysvinit/freebsd/cloudinitlocal
- sysvinit/gentoo/cloud-config
- sysvinit/gentoo/cloud-final
- sysvinit/gentoo/cloud-init
- sysvinit/gentoo/cloud-init-local
- sysvinit/netbsd/cloudconfig
- sysvinit/netbsd/cloudfinal
- sysvinit/netbsd/cloudinit
- sysvinit/netbsd/cloudinitlocal
```
Standardize disabling cloud-init on non-systemd
Some distros support disabling cloud-init using the 
kernel argument cloud-init=disabled. Standardize it
across non-systemd distros. Skip NetBSD, which
doesn't appear to support passing external
arguments to the kernel.
Add support for disabling cloud-init using
/etc/cloud/cloud-init.disabled to non-systemd
distros.
```
Support disabling cloud-init via kernel commandline using `cloud-init=disabled`
Note: suse and rhel shouldn't need these changes per #2115 and #2114
Docs to follow in another PR.
> Standardize kernel commandline disable

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/identity.py
- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/azure/test_identity.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_azure_helper.py
- Add query_system_uuid() for getting system uuid from dmi in normalized (lower-cased) form.
- Add byte_swap_system_uuid() to convert a system uuid for gen1 instances to the compute.vmId as presented by IMDS.
- Move ChassisAssetTag from Azure helpers into identity.
- Update DataSourceAzure._iid() to use this module.
> azure: introduce identity module

- debian/changelog
- debian/cloud-init.preinst
```bash
tar -cvaf ../cloud-init_23.1.1.orig.tar.xz .
build-package # or: debuild -d -S -nc 
sbuild --dist focal ../out/cloud-init_23.1.1-0ubuntu0~20.04.1.dsc
CLOUD_INIT_PLATFORM=gce CLOUD_INIT_CLOUD_INIT_SOURCE=$(ls cloud-init_*.deb) CLOUD_INIT_OS_IMAGE=focal tox -e integration-tests -- tests/integration_tests/modules/test_combined.py
```
SC-1440
https://github.com/canonical/cloud-init/pull/2117#issuecomment-1508151851
> ubuntu/focal: Gcp drop disable network activation focal (SC-1440)

- debian/changelog
- debian/cloud-init.preinst
```bash
tar -cvaf ../cloud-init_23.1.1.orig.tar.xz .
build-package # or: debuild -d -S -nc 
sbuild --dist jammy ../out/cloud-init_23.1.1-0ubuntu0~22.04.1.dsc
CLOUD_INIT_PLATFORM=gce CLOUD_INIT_CLOUD_INIT_SOURCE=$(ls cloud-init_*.deb) CLOUD_INIT_OS_IMAGE=jammy tox -e integration-tests -- tests/integration_tests/modules/test_combined.py
```
> ubuntu/jammy: Gcp drop disable network activation jammy  (SC-1440)

- ChangeLog
- debian/changelog
- debian/cloud-init.preinst
```bash
build-package
sbuild
CLOUD_INIT_PLATFORM=gce CLOUD_INIT_CLOUD_INIT_SOURCE=$(ls cloud-init_*.deb) tox -e integration-tests -- tests/integration_tests/modules/test_combined.py
```
> ubuntu/kinetic: gce drop disable network activation kinetic (SC-1440)

- cloudinit/config/cc_users_groups.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_users_groups.py
- tests/unittests/distros/test_user_data_normalize.py
```
users: schema permit empty list to indicate create no users
When defining json schema in a63f45f7, we were a bit too strict by
setting `minItems: 1` on the `users:` list.
This schema definition regressed the ability to prevent default_user
creation with user-data.  Remove that schema constraint because the
code already supports this case.
```
This hits desktop and subiquity autoinstall deployment needs.
> users: schema permit empty list to indicate create no users

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/errors.py
- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/azure/test_errors.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_azure_helper.py
When provisioning failures occur an Azure, a generic description is used in the report and ultimately returned to the user.  To improve the user experience, report details of the failure in a manner that is parsable, readable and succinct.  The current approach is to use csv with a custom delimiter ("|") and quote character ("'").  This format may change in the future.
Gracefully handle reportable errors thrown while crawling metadata and treat other exceptions as ReportableErrorUnhandledException.  Future work will introduce more reportable errors to handle the expected failure cases.
> azure/errors: introduce reportable errors

- cloudinit/sources/azure/errors.py
- tests/unittests/sources/azure/test_errors.py
Save a few characters by decoding it as utf-8 string rather than using the bytes representation.
> azure/errors: treat traceback_base64 as string

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/imds.py
- tests/unittests/sources/azure/test_imds.py
- tests/unittests/sources/test_azure.py
Instead of a fixed number of retries, allow up to 5 minutes to fetch metadata from IMDS.  The current approach allows for up to 11 attempts depending on the path.  Given the timeout setting, this can vary from ~11 seconds up to ~32 seconds depending on whether or not read/connection timeouts are encountered.
Delaying boot on the rare occasion that IMDS is delayed is better than ignoring the metadata as it ensures the VM is configured as expected.
This is a very conservative timeout and may be reduced in the future.
> azure/imds: retry fetching metadata up to 300 seconds

- cloudinit/net/ephemeral.py
- tests/unittests/net/test_init.py
```
net: Document use of `ip route append` to add routes
```
**Update**
I am changing this PR to document the reason that the current code is needed for better context.
> net: Document use of `ip route append` to add routes

- cloudinit/reporting/handlers.py
- cloudinit/sources/DataSourceAzure.py
- tests/unittests/reporting/test_reporting_hyperv.py
- tests/unittests/sources/test_azure.py
Azure can report provisioning failures via the Wireserver health endpoint.  However, in the event of networking failures or Wireserver issues, this report cannot be made and the VM will result in an OS provisioning timeout and a generic error is presented to the user.
Report the failure via KVP using the "PROVISIONING_REPORT" key so that the host can relay the provisioning error report to the user when the VM fails to provision.
The format used is subject to change and/or removal.
> sources/azure: report failures to host via kvp

- doc/rtd/development/datasource_creation.rst
- doc/rtd/development/index.rst
- doc/rtd/explanation/boot.rst
- doc/rtd/explanation/format.rst
- doc/rtd/explanation/index.rst
- doc/rtd/explanation/kernel-cmdline.rst
- doc/rtd/howto/disable_cloud_init.rst
- doc/rtd/howto/index.rst
- doc/rtd/reference/base_config_reference.rst
- doc/rtd/reference/datasource_dsname_map.rst
- doc/rtd/reference/datasources.rst
- doc/rtd/reference/datasources/nocloud.rst
- doc/rtd/reference/datasources/openstack.rst
- doc/rtd/reference/index.rst
```
Update kernel commandline docs
- describe kernel commandline override
- add OpenStack Ironic selection instructions
- describe datasource selection
- move datasource creation doc to dev section
- remove generator stage from boot stages
- document how to disable cloud-init in howtos
- fix missing kernel-cmdline.rst link
- update outdated security advice
Document the following commits:
34e8c914df666c937e48f5d1c3add0bd47e4e7eb
f146fe71733e72b94fad525b8cc9988b1405e760
250280ada67995a8449b64027b879d01939d2729
612b4de892d19333c33276d541fed99fd16d3998
a60c0845806baff72c74603286d048efbafab664
d1ffbea556a06105d1ade88b4143ad43f53692c4
02202954c65a7a1cdb9b28703bd0af01edd0e091
```
This documentation serves to document recent work in the following commits: …
> Update kernel commandline docs (SC-1457)

- cloudinit/sources/DataSourceLXD.py
- cloudinit/sources/DataSourceVultr.py
- cloudinit/sources/__init__.py
- cloudinit/stages.py
- tests/unittests/sources/test_init.py
- tests/unittests/test_stages.py
```
Make user/vendor data sensitive and remove log permissions
Because user data and vendor data may contain sensitive information,
this commit ensures that any user data or vendor data written to
instance-data.json gets redacted and is only available to root user.
Also, modify the permissions of cloud-init.log to be 640, so that
sensitive data leaked to the log isn't world readable.
Additionally, remove the logging of user data and vendor data to
cloud-init.log from the Vultr datasource.
LP: #2013967
CVE: CVE-2023-1786
```
> Make user/vendor data sensitive and remove log permissions

- cloudinit/net/netplan.py
- cloudinit/net/renderer.py
- cloudinit/sources/DataSourceGCE.py
- cloudinit/util.py
- tests/integration_tests/modules/test_user_events.py
- tests/integration_tests/test_networking.py
- tests/unittests/net/test_netplan.py
- tests/unittests/test_net.py
- tests/unittests/test_util.py
```
gce: activate network discovery on every boot
Google wants to allow users make changes on nics while the instance
is stopped. Activate network discovery on every boot.
Additionally, skip the call to `netplan generate` if the rendered
config is the same on subsequent boots.
```
- https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceAzure.py#L329
- [Google wants users to be able to reconfigure the NIC after instance creation](https://cloud.google.com/compute/docs/instances/migrating-interfaces-between-networks)
- More context on architectural relationship between cloud-init and netplan: https://bugs.launchpad.net/cloud-init/+bug/1737630
1. Create an instance
2. Stop the instance
3. Move the instance to another VPC
4. Start the instance
5. Verify the instance is …
> gce: activate network discovery on every boot (cpc-2351)

- cloudinit/config/schema.py
- tests/unittests/config/test_schema.py
```
cli: schema validation of jinja template user-data
The CLI cloud-init schema now asserts that the leading header comment in user-data files is a valid user-data type. Raise an informative error otherwise about valid user-data types.
For user-data files declared with '## template: jinja', render those files firts sourcing jinja varibles from /run/cloud-init/instance-data.json or a new --instance-data parameter.
Once the jinja template is rendered, validate schema of the resulting #cloud-config user-data.
This branch also ensures any errors and deprecation warnings are unique.
LP: #1881925
```
> cli: schema validation of jinja template user-data (SC-1385)

- cloudinit/distros/bsd.py
```
Fix linux-specific call on BSDs.
util.get_mount_info() which is called from the
distro base class is linux-specific
```
```
File "/usr/local/lib/python3.9/site-packages/cloudinit/sources/__init__.py", line 946, in find_source
if s.update_metadata_if_supported(
File "/usr/local/lib/python3.9/site-packages/cloudinit/sources/__init__.py", line 828, in update_metadata_if_supported
result = self.get_data()
File "/usr/local/lib/python3.9/site-packages/cloudinit/sources/__init__.py", line 373, in get_data
return_value = self._get_data()
File "/usr/local/lib/python3.9/site-packages/cloudinit/sources/DataSourceOpenStack.py", line 161, in _get_data
tmp_dir=self.distro.get_tmp_exec_path(),
File "/usr/local/lib/python3.9/site-packages/cloudinit/distros/__init__.p …
```
> Fix linux-specific call on BSD.

- cloudinit/sources/helpers/openstack.py
- tests/unittests/sources/helpers/test_openstack.py
The `network_data.json` allows the definition of the DNS through the `services` list at the network level.
See:
- https://opendev.org/openstack/nova/src/commit/700db274c613d6f8f30e5cdc3462beaeb0fda456/nova/tests/unit/network/test_network_info.py#L979-L980
- https://opendev.org/openstack/metalsmith/src/commit/f98dfa61c1d7475b81c20dabbf2c74198c38c793/metalsmith/test/test_network_metadata.py#L52-L90
- https://opendev.org/openstack/nova/commit/4b333b989dfc778a8b61db4a1b8552e988a10471
> openstack/static: honor the DNS servers associated with a network

- setup.py
- tools/.github-cla-signers
Distributions other than RHEL also use /usr/lib/udev for the rules path. Instead of hardcoding the udev rules path for RedHat, check pkg-config for the proper location.
```
setup.py: use pkg-config for udev/rules path
Distributions other than RHEL also use /usr/lib/udev for the rules
path. Instead of hardcoding the udev rules path for RedHat, check
pkg-config for the proper location.
```
> setup.py: use pkg-config for udev/rules path

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/errors.py
- cloudinit/sources/azure/kvp.py
- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/azure/test_errors.py
- tests/unittests/sources/azure/test_kvp.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_azure_helper.py
Add success reporting to the host via KVP.
- Move _report_failure_to_host() into kvp module.
- Tweak error description to use result=error instead of PROVISIONING_ERROR: ...
- Use result=success for the successful ("ready") reports.
The format used is subject to change and/or removal.
> sources/azure: report success to host and introduce kvp module

- .github/labeler.yml
- .github/workflows/doc-autolabel.yml
```
Add documentation label automatically
```
All bugs with this label assigned can be viewed at the following url: https://github.com/canonical/cloud-init/labels/Documentation
See test [here](https://github.com/holmanb/cloud-init/pull/49).
> Add documentation label automatically

- cloudinit/config/cc_ssh.py
- cloudinit/util.py
- tests/unittests/config/test_cc_ssh.py
- tests/unittests/test_util.py
DSA and ED25519 key types are not supported when FIPS is enabled in crypto. Check if FIPS has been enabled on the system and if so, do not generate those key types. Presently the check is only available on Linux systems.
Test Steps:
Steps to Reproduce:
Manual:
1. Boot into an RHEL-9.1 system with fips enabled
2. Try to clean and init cloud-init again
$sudo cloud-init clean
$sudo cloud-init init
LP: 2017761
RHBZ: 2187164
> Do not generate dsa and ed25519 key types when crypto FIPS mode is enabled

- cloudinit/cmd/main.py
- cloudinit/net/cmdline.py
- cloudinit/netinfo.py
- cloudinit/warnings.py
```
Fix logger calls
Use Logger instance rather than module function.
Add missing logger names.
```
> Fix logger, use instance rather than module function

- cloudinit/sources/DataSourceAzure.py
- cloudinit/util.py
- tests/unittests/sources/test_azure.py
- tests/unittests/test_util.py
Provide an option to suppress error logging from _mount_cb_ as some errors can be expected error and handled appropriately by DataSources. For example: failure to mount NTFS volumes on VMs that do not have NTFS drivers.
> Remove mount NTFS error message

- cloudinit/distros/parsers/resolv_conf.py
- tests/unittests/distros/test_resolv.py
- tools/.github-cla-signers
Systems running systemd-resolved or dnsmasq can utlize more than three namervers. Older systems will just use the first three and ignore the rest.
```
resolv_conf: Allow > 3 nameservers
Systems running systemd-resolved or dnsmasq can utlize more than three
namervers. Older systems will just use the first three and ignore the
rest.
Signed-off-by: Major Hayden <major@redhat.com>
```
[Red Hat Bugzilla #2068529](https://bugzilla.redhat.com/show_bug.cgi?id=2068529)
Launch a cloud instance when > 3 nameservers are configured. All of the provided nameservers should be configured on the systems. Older systems without systemd-resolved/NetworkManager/dnsmasq will just use the first three provided while newer systems will use all the servers provided.
> resolv_conf: Allow > 3 nameservers

- cloudinit/net/__init__.py
Much of the filtering logic used in get_interfaces() is duplicated in find_candidate_nics_on_linux().  Consolidate the two interfaces by updating find_candidate_nics_on_linux() to use get_interfaces() and provide boolean toggles to maintain existing behavior.
The following parameters have been added to get_interfaces():
- log_filtered_reasons: bool = False
- filter_openvswitch_internal: bool = True
- filter_vlan: bool = True
- filter_without_own_mac: bool = True
- filter_zero_mac: bool = True
It may be that these deltas are unwanted or harmless, but the toggles could be removed independently with more deliberate consideration. Similarly, logging could be extended if desired for log_filtered_reasons.
> net: refactor find_candidate_nics_on_linux() to use get_interfaces()

- tests/unittests/cmd/test_clean.py
```
tests: avoid leaks to underlying file-system for /etc/cloud/clean.d
```
```
mkdir -p /etc/cloud/clean.d
cat > /etc/cloud/clean.d/1.sh <<EOF
#!/bin/bash
exit 1
EOF
chmod 755 /etc/cloud/clean.d/1.sh
tox -e py3 tests/unittests/cmd/test_clean.py
```
> tests: avoid leaks to underlying file-system for /etc/cloud/clean.d

- cloudinit/net/__init__.py
Azure is introducing a new VF ("MANA") that will initially behave
similarly to mlx4/5 but cannot be denylisted in the same manner.
This is because the synthetic interface (hv_netvsc) will no longer
be required to function in the future which means we must
intelligently filter the VFs out instead of relying solely on the
driver name.
- Isolate filtering logic for Hyper-V's SR-IOV/VFs when used
with synthetic hv_netvsc interfaces.
- Move the filter up to get_interfaces() from
get_interfaces_by_mac_on_linux() to increase coverage of the
filter. With this in place, we should be able to purge the
"blacklist_drivers" across the codebase as it will no longer be
necessary unless there are other paths to be considered.
> net: refactor hyper-v VF filtering and apply to get_interfaces()

- cloudinit/distros/networking.py
- cloudinit/net/__init__.py
- cloudinit/net/network_state.py
- cloudinit/sources/DataSourceAzure.py
- tests/unittests/net/test_init.py
- tests/unittests/sources/test_azure.py
- tests/unittests/test_net.py
- tests/unittests/test_upgrade.py
It was only used by Hyper-V which now has a filtering
mechanism that does not require the use of a denylist.
This exposed some issues with tests misspelling "hv_netvsc"
and using unmatched mac addresses. This fixes those to work
with the current filter that does not rely on the driver name.
> net: purge blacklist_drivers across net and azure

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/errors.py
- tests/unittests/sources/azure/test_errors.py
- tests/unittests/sources/test_azure.py
- Add host_only flag to _report_failure() to allow caller to only report the failure to host.  This is for cases where we don't want _report_failure() to attempt DHCP or we expect that we may recover from the reported error (there is no issue reporting multiple times to host, whereas fabric reports will immediately fail the VM provisioning).
- Add ReportableErrorDhcpLease() to report lease failures.
- Add ReportableErrorDhcpInterfaceNotFound() to report errors where the DHCP interface hasn't been found yet.
- Add TestReportFailure class with new test coverage.  Will migrate other _report_failure() tests in the future as they currently depend on TestAzureDataSource/CiTestCase.
Future work will add the interface name to supporting data, but as that information is not available with …
> azure/errors: add host reporting for dhcp errors

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/errors.py
- tests/unittests/sources/azure/test_errors.py
- tests/unittests/sources/test_azure.py
Always report failure to host, but report failure to fabric only outside of _check_if_nic_is_primary() which is expected to fail if nic is not primary.
Add two types of reportable errors for IMDS metadata:
- add ReportableErrorImdsUrlError() for url errors.
- add ReportableErrorImdsMetadataParsingException() for parsing errors.
Tweak ReportableError repr to be a bit friendlier.
> azure/errors: introduce reportable errors for imds

- cloudinit/cmd/devel/__init__.py
- cloudinit/config/schema.py
- tests/integration_tests/modules/test_cli.py
- tests/unittests/cmd/devel/test_init.py
- tests/unittests/config/test_schema.py
```
Fix cloud-init schema --system being unable to find merged
userdata stored at /var/lib/cloud/instance/cloud_config.txt.
commit e9d1d3a regressed cloud-init schema --system by dropping
a call to fetch existing cached datasource information before
calling Init.paths.get_ipath.
Init.paths.get_ipath only has visibility to merged cloud config in
/var/lib/cloud/<instance_id>/cloud-config.txt after fetching the
existing cached datasource which provides instance-id from metadata
in order to determine the unique instance-id which represents
the full path to the cloud-config.txt.
To support reuse of read_cfg_paths helper function, add an optional
parameter fetch_existing_datasource which indicates whether reading
the existing datasource is necessary for this helper function.
cloud-init schema …
```
> schema: read_cfg_paths call init.fetch to lookup /v/l/c/instance

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- SECURITY.md
- WIP-ONGOING-REFACTORIZATION.rst
- cloudinit/warnings.py
- doc/rtd/development/debugging.rst
- doc/rtd/explanation/events.rst
- doc/rtd/howto/bugs.rst
- doc/rtd/index.rst
- doc/rtd/reference/network-config-format-eni.rst
- doc/rtd/reference/network-config.rst
```
Replace Launchpad references with GitHub Issues
```
This should be ready for review
> Replace Launchpad references with GitHub Issues

- cloudinit/config/cc_growpart.py
- cloudinit/distros/freebsd.py
- tests/unittests/config/test_cc_growpart.py
```
FreeBSD: add ResizeGrowFS class to cc_growpart
this FreeBSD specific resizer resizes the root partition and grows the Filesystem all in one.
All we have to do is call ``service growfs onestart``
Document behaviour: especially that growfs will insert a swap partition
if none is present, unless instructed otherwise.
```
This service has existed for a long time in FreeBSD, I think it's time we use it instead of reinventing the wheel.
caveat: This only works for the root device.
I think this should probably be rebased on #2168 .
> FreeBSD: add ResizeGrowFS class to cc_growpart

- cloudinit/distros/freebsd.py
```
FreeBSD: Fix user account locking
On Linux, we only disable login via Password authentication.
On FreeBSD, we were right out locking the account.
This was reported back when #93 was merged,
but back then I didn't understand that.
Newly created FreeBSD users can now login with with SSH keys.
LP: #1854594 (For real this time)
Fixes: #3507
```
#93
> FreeBSD: Fix user account locking

- cloudinit/config/cc_ntp.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- templates/chrony.conf.alpine.tmpl
- templates/chrony.conf.centos.tmpl
- templates/chrony.conf.cos.tmpl
- templates/chrony.conf.debian.tmpl
- templates/chrony.conf.fedora.tmpl
- templates/chrony.conf.freebsd.tmpl
- templates/chrony.conf.opensuse-leap.tmpl
- templates/chrony.conf.opensuse-microos.tmpl
- templates/chrony.conf.opensuse-tumbleweed.tmpl
- templates/chrony.conf.opensuse.tmpl
- templates/chrony.conf.photon.tmpl
- templates/chrony.conf.rhel.tmpl
- templates/chrony.conf.sle-micro.tmpl
- templates/chrony.conf.sle_hpc.tmpl
- templates/chrony.conf.sles.tmpl
- templates/chrony.conf.ubuntu.tmpl
- templates/ntp.conf.alpine.tmpl
- templates/ntp.conf.debian.tmpl
- templates/ntp.conf.fedora.tmpl
- templates/ntp.conf.freebsd.tmpl
- templates/ntp.conf.opensuse.tmpl
- templates/ntp.conf.photon.tmpl
- templates/ntp.conf.rhel.tmpl
- templates/ntp.conf.sles.tmpl
- templates/ntp.conf.ubuntu.tmpl
- templates/ntpd.conf.openbsd.tmpl
- tests/unittests/config/test_cc_ntp.py
- tools/.github-cla-signers
```
Adds the 'peer' and 'allow' directives to the NTP template.  This also adds additional debug logging for these settings.
```
When deploying NTP servers and peers in a complex system, these additional settings enable the hostnames and IP ranges to be dynamically set in the config file.
Set a `peers` or `allow` directive in the template and run the NTP module.
> Add 'peers' and 'allow' directives in cc_ntp

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/enhancement.md
- README.md
- doc/rtd/index.rst
```
Add templates for GitHub Issues
```
I tried it on a private repo first, and he's what the `New Issue` page looks like:
The Security Policy page takes the user to our [SECURITY.md](https://github.com/canonical/cloud-init/blob/main/SECURITY.md)
GitHub does allow for [full web forms for issues](https://docs.github.com/assets/cb-80507/mw-1440/images/help/repository/sample-issue-form.webp) these days, but I think that might be overkill for our project.
> Add templates for GitHub Issues

- cloudinit/net/network_manager.py
The sysconfig renderer sets the following in the ifcfg file for IPV6 stateful DHCP configuration:
BOOTPROTO = "dhcp"
DHCPV6C = True
IPV6INIT = True
IPV6_AUTOCONF = False
This should result in
[ipv6]
method=dhcp
in the network manager generated keyfile since DHCPV6C is set and IPV6_AUTOCONF is not set. Unfortunately the network manager renderer deviates from this and generates:
[ipv6]
method=auto
keyfile setting. This change fixes this deviation and sets the IPV6 dhcp stateful configuration in alignment with sysconfig renderer.
RHBZ: 2207716
> network-manager: generate ipv6 stateful dhcp config at par with sysconfig

- cloudinit/net/network_manager.py
The static IP configuration for IPv6 in the method_map is missing for network manager renderer. This is causing cloud-init to generate a keyfile with IPv6 method as "auto" instead of "manual". This fixes this issue.
fixes: https://github.com/canonical/cloud-init/issues/4126
RHBZ: 2196284
> network_manager: add a method for ipv6 static IP configuration

- debian/changelog
- debian/patches/netplan99-cannot-use-default.patch
- debian/patches/series
> ubuntu/focal:cherry pick netplan99-cannot-use-default.patch

- cloudinit/net/sysconfig.py
Some distributions like RHEL does not have ifup and ifdown scripts that traditionally handled ifcfg-eth* files. Instead RHEL uses network manager with ifcfg-rh plugin to handle ifcfg scripts. Therefore, the sysconfig should check for the existence of ifcfg-rh plugin in addition to checking for the existence of ifup and ifdown scripts in order to determine if it can handle ifcfg files. If either the plugin or ifup/ifdown scripts are present, sysconfig renderer can be enabled.
fixes: https://github.com/canonical/cloud-init/issues/4131
RHBZ: 2194050
> net/sysconfig: enable sysconfig renderer if network manager has ifcfg-rh plugin

- doc/rtd/conf.py
- doc/rtd/static/css/github_issue_links.css
- doc/rtd/static/js/github_issue_links.js
```
docs: Add feedback button to docs
Adds a "Give feedback" button to the docs that links to creating a new
documentation issue when clicked
```
Docs page should now look like this: ![image](https://github.com/canonical/cloud-init/assets/153674/d063c617-1965-4785-aefd-ab26139239c2)
When clicked, we get a link to [create a new issue](https://github.com/canonical/cloud-init/issues/new?assignees=&labels=documentation%2C+new&projects=&template=documentation.md&title=%5Bdocs%5D%3A+&body=#%20Documentation%0A%0A%0A%0A%0A---%0A*Reported+from%3A+file:///home/james/cloud-init/doc/rtd_html/index.html)
The css and js code was boldly taken from the Ubuntu Pro documentation.
> docs: Add feedback button to docs

- templates/ntp.conf.freebsd.tmpl
```
cc_ntp: Sync up with current FreeBSD ntp.conf
ref: https://reviews.freebsd.org/D39954
```
> cc_ntp: Sync up with current FreeBSD ntp.conf

- debian/changelog
- debian/control
It is no longer used and no longer exists in mantic.
> ubuntu/devel: Remove pep8 dependency

- cloudinit/distros/alpine.py
```
alpine.py: change the locale file used
Rather than modifying the standard Alpine-managed locale file instead
create a new cloud-init specific locale file in the same directory.
This file will be read/processed by Alpine in sequence and take effect
after the OS-packaged locale file - this avoids modifying that locale file.
```
- [ x ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
- [ x ] I have updated or added any unit tests accordingly
- [ x ] I have updated or added any documentation accordingly
> alpine.py: change the locale file used

- cloudinit/net/network_manager.py
- tests/unittests/cmd/devel/test_net_convert.py
- tests/unittests/net/artifacts/no_matching_mac/etc/NetworkManager/system-connections/cloud-init-encc000.2653.nmconnection
- tests/unittests/net/artifacts/no_matching_mac/etc/NetworkManager/system-connections/cloud-init-encc000.nmconnection
- tests/unittests/net/artifacts/no_matching_mac/etc/NetworkManager/system-connections/cloud-init-zz-all-en.nmconnection
- tests/unittests/net/artifacts/no_matching_mac/etc/NetworkManager/system-connections/cloud-init-zz-all-eth.nmconnection
- tests/unittests/test_net.py
cloud init generated keyfiles by network manager renderer for network
interfaces can sometimes conflict with existing keyfiles that are left as an
artifact of an upgrade process or are old user generated keyfiles. When two
such keyfiles are present, the existing keyfile can take precedence over the
cloud init generated keyfile making the later ineffective. Removing the old
keyfile blindly by cloud init would also not be correct since there would be
no way to enforce a different interface configuration if one needs it.
This change adds an autoconnect-priority value for cloud init generated keyfile
so that the cloud init configuration takes precedence over the existing old
keyfile configuration in the default case. The priority values range from 0
to 999. We set a value of 120 so that it …
> network-manager: Set higher autoconnect priority for nm keyfiles

- cloudinit/config/cc_growpart.py
- cloudinit/util.py
- tests/unittests/config/test_cc_growpart.py
- tests/unittests/distros/test_dragonflybsd.py
```
BSD: simplify finding MBR partitions
by removing duplicate code.
Co-authored-by: Alberto Contreras <aciba90@gmail.com>
Fixes: #2168 
```
Fixes: #2168
> BSD: simplify finding MBR partitions

- .gitignore
```
.gitignore: extend coverage pattern
apply more ignorance.
```
This now ignore stuff like
```
meena@76ix ~/s/c/cloud-init (freebsd/cc_rsyslogd)> git status
On branch freebsd/cc_rsyslogd
Your branch is up to date with 'meena/freebsd/cc_rsyslogd'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
.coverage.76ix.155619.066231
.coverage.76ix.155619.278789
.coverage.76ix.155651.132853
.coverage.76ix.155651.886957
.coverage.76ix.155774.532336
.coverage.76ix.155774.848850
.coverage.76ix.155775.241306
.coverage.76ix.155775.885948
.coverage.76ix.155776.720099
.coverage.76ix.155776.820759
nothing added to commit but untracked files present (use "git add" to track)
meena@76ix ~/s/c/cloud-init (freebsd/cc_rsyslogd)> 
```
> .gitignore: extend coverage pattern

- doc/rtd/reference/datasources/nocloud.rst
```
doc: add missing semi-colon to nocloud cmdline docs
Co-authored-by: s-makin <sally.makin@canonical.com>
```
tox -e doc
xdg-open doc/rtd_html/reference/datasources/nocloud.html
> doc: add missing semi-colon to nocloud cmdline docs

- tests/integration_tests/modules/test_apt.py
```
```
[Failing Jenkins job showcasing the error](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-mantic-lxd_container/lastSuccessfulBuild/testReport/junit/tests.integration_tests.modules.test_apt/TestApt/test_ppa_source/)
```
for RELEASE in kinetic mantic; do
CLOUD_INIT_OS_IMAGE=$RELEASE tox -e …
```
> tests: apt support for deb822 format .sources files on mantic

- cloudinit/config/cc_rsyslog.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- cloudinit/distros/__init__.py
- cloudinit/distros/bsd.py
- cloudinit/distros/freebsd.py
- config/cloud.cfg.tmpl
- tests/unittests/config/test_cc_rsyslog.py
- tests/unittests/util.py
```
cc_rsyslog: Refactor for better multi-platform support
- remove Hash key redirection
- copy basic multi-distro config from cc_ntp
- add optional installation
- enable and start services
- on BSD: disable Base system syslog
Co-Authored-by: Chad Smith <chad.smith@canonical.com>
Co-Authored-by: James Falcon <james.falcon@canonical.com>
Fixes: #3250, #4118
LP: #1798055
```
Fixes: #3250, #4118
LP: #1798055
> cc_rsyslog: Refactor for better multi-platform support

- cloudinit/net/bsd.py
- cloudinit/net/freebsd.py
- cloudinit/net/openbsd.py
- tools/.github-cla-signers
OpenBSD: Added support for static routes
FreeBSD: Fixed creation of static routes
- Corrected syntax in usage of route(8)
- Added the needed space separated list of route names in the /etc/rc.conf-variable "static_routes"
> Added / fixed support for static routes on OpenBSD and FreeBSD

- cloudinit/distros/__init__.py
- cloudinit/distros/bsd.py
- cloudinit/distros/freebsd.py
- cloudinit/net/dhcp.py
- cloudinit/net/ephemeral.py
- cloudinit/net/netops/__init__.py
- cloudinit/net/netops/bsd_netops.py
- cloudinit/net/netops/iproute2.py
- cloudinit/sources/DataSourceScaleway.py
- tests/unittests/net/test_dhcp.py
- tests/unittests/net/test_ephemeral.py
- tests/unittests/net/test_init.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_ec2.py
- tests/unittests/sources/test_upcloud.py
```
Support ephemeral network for BSDs
Currently ephemeral.py uses hardcoded iproute2
calls to setup ephemeral networking, which is
incompatible with BSDs. Refactor to support
pluggable network interface operations.
```
Blocked by https://github.com/canonical/cloud-init/pull/2130 ~~and https://github.com/canonical/cloud-init/pull/2122 ([context](https://github.com/canonical/cloud-init/pull/2122#pullrequestreview-1389048745))~~.
> Support Ephemeral Networking for BSD

- doc/rtd/explanation/kernel-cmdline.rst
on a document i have not touched
```
fix doc lint: spellchecker tripped up
why wasn't this failing before?
```
> fix doc lint: spellchecker tripped up

- tools/read-version
```
tools: fix run-container builds for rockylinux/8 git hash mismatch
When building untagged commits from tip of main, brpm uses git describe to create a versioned subdirectory.
For untagged commite, limit git describe hash to 8 characters to align with the expected hash length of 8 that rpmbuild expects.
This avoids missing file errors during %prep stage resulting in the following type or build error:
+ cd cloud-init-23.2-15-g95364bbf7 /var/tmp/rpm-tmp.S7mQ7Y: line 40: cd: cloud-init-23.2-15-g95364bbf7 : No such file or directory
```
See failure on tip of main:
```
./tools/run-container --source-package --unittest --package --artifacts=./srpm/ rockylinux/8
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['rpmbuild', '-ba', …
```
> tools: fix run-container builds for rockylinux/8 git hash mismatch

- cloudinit/config/cc_salt_minion.py
- tests/unittests/config/test_salt_minion.py
- tests/unittests/util.py
- tools/.github-cla-signers
Launching salt-minion in masterless mode
```
If the minion is launched in masterless mode, then it should not be launched as a daemon.
```
For more - https://docs.saltproject.io/en/latest/topics/tutorials/quickstart.html
For testing and reproduce, you can run cloud-init with the following config:
```
#cloud-config
salt_minion:
conf:
file_client: local
fileserver_backend:
- gitfs
gitfs_remotes:
- https://github.com/foo/bar
```
Without a fix, salt-minion will not run correctly in this case.
This fix allows you to run salt-minion both in daemon mode and in masterless mode.
> launching salt-minion in masterless mode

- config/cloud.cfg.tmpl
```
BSD: remove datasource_list from cloud.cfg template
This limited list was put into place, because in the past, something
wasn't working right. Whatever it was, seems to be resolved. Removing it
means BSDs have the same chance on all clouds like other distros do.
People can always create images that customize the selection, but the
out of box experience should be that cloud-init works as advertised on
all supported distros and all available clouds.
```
Found while testing my last change on Hetzner.
ds-identify identifies Hetzner, but cloud-init did not.
Because it wasn't in the list of options.
> BSD: remove datasource_list from cloud.cfg template

- tests/integration_tests/bugs/test_gh626.py
```
tests: can't match MAC for LXD container veth due to netplan 0.106
netplan 0.106 introduced PermanentMACAddress matching for networkd
configuration. LXD containers us veth interfaces which cannot
be matched by PermanentMACAddress.
Fix test_wakeonlan to prefer match by macadddress in network-config
for lxd_vm platform and prefer match by name on lxd_container.
Leave both test types in place to validate netplan plumbing for
both cases.
```
Jenkins failure (lunar and mantic both affected)
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-lunar-lxd_container/lastSuccessfulBuild/testReport/junit/tests.integration_tests.bugs/test_gh626/test_wakeonlan/
> tests: can't match MAC for LXD container veth due to netplan 0.106

- cloudinit/util.py
- tests/unittests/test_util.py
```
FreeBSD fix parsing of mount and mount options
The regular expressions used to parse BSD mount(8) are both
overly complicated and limited.
- Combine the two regular expressions into one
- clarify regular expressions with named groups
- add parsing of mount options
- Attempt to extract mount-parent sub-path finding code from  parse_mount_info()
- Failing that, duplicate it in parse_mount()
This leaves parse_mtab() as only mount info provider without options parsing, for now.
```
a hopefully better fix for #2143
> FreeBSD fix parsing of mount and mount options

- config/cloud.cfg.tmpl
Currently, network manager is disabled on c9s and therefore sysconfig is used as the primary renderer for network configuration. We do not want to change this for c9s even when network-manager renderer is re-enabled as it would mean a big behaviour change for cloud-init in the centos 9 stream.
This change bumps up the priority for sysconfig renderer so that it is used as the primary renderer on c9s and other downstream distributions derived from it. In the next major centos stream release, we may use network manager as the default renderer and make changes accordingly.
RHBZ:2209349
> Set default renderer as sysconfig for centos/rhel

- doc/rtd/reference/datasources/nocloud.rst
```
Clarify directory syntax for nocloud local filesystem.
Fixes GH-3355
```
fixes https://github.com/canonical/cloud-init/issues/3355
> fixes 3355

- integration-requirements.txt
- test-requirements.txt
pytest 7.3.2 changed treatment of `testpaths` config which forced test/unittest/conftest.py module load in our integration-tests toxenv. Upstream bug is tracking their planned revert/fix for this regression. Pin 7.3.1 in the meantime.
Fixes #4183
```
```
Jenkins job failures: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-i …
> integration-tests: pin pytest 7.3.1 to avoid adverse testpaths behavior

- cloudinit/net/__init__.py
- cloudinit/sources/DataSourceGCE.py
- tests/unittests/sources/test_gce.py
```
gce: improve ephemeral fallback NIC selection (CPC-2578)
While setting up the ephemeral network config for fetching the IMD at init-local timeframe on multi-NIC instances, fulfilling:
- All NICs without carrier flag or more than one NIC with carrier flag
- systemd's predictable interface names is enabled
net.find_fallback_nic could select a NIC that is not the primary NIC, leaving the instance without access to the network, as on GCE, only the primary NIC can talk to the IMDS.
At this point in time, there is yet not access to
{instance,vendor,user}-data. Thus, it is tricky to dynamically inject a breadcrum pointing to the primary NIC.
Two actions have been taken to fix this situation:
1. Substitute eth0 with ens4 as the default primary NIC candidate on Linux systems.
2. Try through …
```
> gce: improve ephemeral fallback NIC selection (CPC-2578)

- cloudinit/sources/__init__.py
- tests/data/kernel_cmdline_match/meta-data
- tests/data/kernel_cmdline_match/user-data
- tests/data/kernel_cmdline_match/vendor-data
- tests/integration_tests/cmd/test_status.py
- tests/integration_tests/conftest.py
- tests/integration_tests/test_kernel_commandline_match.py
- tests/integration_tests/util.py
- tests/unittests/sources/test___init__.py
```
nocloud: parse_cmdline no longer detects nocloud-net datasource
Commit 612b4de89 introduced parse_cmdline function which did not take into account hyphenated datasource names.
This negatively impacted the detection of hyphenated nocloud-net.
Fix parse_cmdline regex to align with ds-identify logic which matches all characters until either a semi-colon or whitespace.
Extend integration tests to consume github flat files as the seed_from URL.
setup and consume user-data, meta-data
from using github raw files as the seed
Fixes: 4203
```
```
sed -i 's/canonical\/cloud-init\/main/blackboxsw\/cloud-init\/fix-nocloud-net-detect-from-cmdline/' tests/integration_tests/test_kernel_commandline_match.py
CLOUD_INIT_KEEP_INSTANCE=1 CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_OS_IMAGE=mantic …
```
> nocloud: parse_cmdline no longer detects nocloud-net datasource

- tests/integration_tests/test_multi_part_user_data_handling.py
```
tests: reboot client to assert x-shellscript-per-boot is triggered
Improve assertions across reboot to prove per-always is run and
per-once per-instance are not run across typical reboot.
```
Additional assertions to prove that cloud-init runs x-shellscript-per-always every reboot to assert that https://github.com/canonical/cloud-init/issues/4197 is not a cloud-init prob.
```
CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily CLOUD_INIT_PLATFORM=lxd_container CLOUD_INIT_OS_IMAGE=kinetic .tox/integration-tests/bin/pytest tests/integration_tests/test_shell_script_by_frequency.py
```
> tests: reboot client to assert x-shellscript-per-boot is triggered

- doc/examples/cloud-config-boot-cmds.txt
- doc/examples/cloud-config.txt
A user initially found the poor wording of `but possibly with more friendly.`, and I added a few other minor changes to fix up the wording. I don't think we need the extra boothook comparisons or explanation here as boothooks are very rarely used anymore.
> docs: Correct some bootcmd example wording

- setup.py
```
setup: fix generation of init templates
if an init file ends in any of the letters [tmpl] these will be stripped
in addition to the .tmpl extension.
This is documented behaviour of the str.rstrip() method.
This PR fixes it by using os.path.splitext() (rather than
str.removesuffix which is only available in python 3.9+)
Since BSD sysvinit scripts are now rendered as template,
we need to fix an oversight from #4182 and pass the mode.
```
https://github.com/canonical/cloud-init/pull/4182
successfully tested on Hetzner
> setup: fix generation of init templates

- debian/apport-general-hook.py
- debian/changelog
Update cloud-init's apport general hooks for focal to ensure we don't hit type annotations issues.
LP: #2025376
```
d/apport-general-hook: correct type hints on Dict for py3.8
Focal's python3.8 traces on type hints of the format:
dict[str, str].
Instead, from typing import Dict
LP: #2025376
```
> Ubuntu/focal 23.2.x

- doc/rtd/howto/debug_user_data.rst
- doc/rtd/howto/identify_datasource.rst
- doc/rtd/howto/index.rst
- doc/rtd/howto/locate_files.rst
- doc/rtd/reference/faq.rst
```
Migrate content out of FAQ page (SD-1187)
Extracted several short topics out of the FAQ and
created individual "how-to" pages. Now what's left in 
the FAQ is mostly troubleshooting content.
```
> Migrate content out of FAQ page

- pyproject.toml
```
Specify build-system for pep517
Make it clear to various packaging frontends that we're using
setuptools as our backend.
```
I created 3 separate builds:
`python setup.py sdist`
`python -m build` without pyproject.toml changes
`python -m build` with pyproject.toml changes
All three builds contained exactly the same contents
> Specify build-system for pep517 [SC-1492]

- cloudinit/analyze/__main__.py
- cloudinit/analyze/dump.py
- cloudinit/atomic_helper.py
- cloudinit/cmd/query.py
- cloudinit/handlers/jinja_template.py
- cloudinit/helpers.py
- cloudinit/sources/DataSourceExoscale.py
- cloudinit/sources/DataSourceIBMCloud.py
- cloudinit/sources/DataSourceLXD.py
- cloudinit/sources/DataSourceOpenNebula.py
- cloudinit/sources/DataSourceOracle.py
- cloudinit/sources/DataSourceSmartOS.py
- cloudinit/sources/DataSourceVMware.py
- cloudinit/sources/__init__.py
- cloudinit/sources/helpers/vmware/imc/config_passwd.py
- cloudinit/stages.py
- cloudinit/util.py
- tests/integration_tests/modules/test_jinja_templating.py
- tests/unittests/cmd/test_cloud_id.py
- tests/unittests/cmd/test_query.py
- tests/unittests/config/test_cc_seed_random.py
- tests/unittests/conftest.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_init.py
- tests/unittests/sources/test_opennebula.py
- tests/unittests/sources/test_smartos.py
- tests/unittests/test_builtin_handlers.py
- tests/unittests/test_data.py
- tests/unittests/test_ds_identify.py
- tests/unittests/test_util.py
```
instance-data: write /run/cloud-init/merged-cloud-config.json
Persist the merged_cloud_config key as a new file to aid in
discovery or provided configuration settings.
The file /run/cloud-init/merged-cloud-config.json represents the
full configuration presented to cloud-init which layers config
settings in the following priority order:
1. default config: cloudinit.settings.CFG_BUILTIN
2. merged_system_cfg: config from file-system /etc/cloud and
/etc/cloud.cfg.d
3. cloud-specific metadata
4. cloud-specific vendor-data, vendor-data2
5. cloud-specific user-data
Configuration keys present in earlier sources are overridden by
keys in later sources.
```
> Sc 1452 persist run combined cloud config json

- tests/integration_tests/cmd/test_status.py
```
Integration tests fix stray file test
test regression introduced by 0e374f83
```
unhappy jenkins: 
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-lxd_container/lastSuccessfulBuild/testReport/tests.integration_tests.cmd/test_status/test_wait_when_no_datasource/
```
CLOUD_INIT_KEEP_INSTANCE=1 CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily tox -e integration-tests tests/integration_tests/cmd/test_status.py::test_wait_when_no_datasource
```
> Integration tests fix stray file test

- config/cloud.cfg.tmpl
```
cloud.cfg.tmpl: reinstate ca_certs entry
The change from "ca-certs" to "ca_certs" in PR #4128 was accidentally reverted by PR #4119.
This PR reinstates the original change.
```
> cloud.cfg.tmpl: reinstate ca_certs entry

- tests/integration_tests/instances.py
```
tests: proposed should invoke apt-get install -t=<release>-proposed
Specify apt-get install -t=$RELEASE-proposed to ensure installing
proposed package regardless of default apt policy priority
Ubuntu Lunar priority of -proposed pocket is 100 instead of 500
so cloud-init CLOUD_INIT_SOURCE=PROPOSED does not actually install
from lunar-proposed.
```
Lunar apt policy of -proposed shows up at priority 100 instead of 500, resulting in no cloud-init installed from -proposed
```
CLOUD_INIT_KEEP_INSTANCE=1 CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED CLOUD_INIT_OS_IMAGE=lunar tox -e integration-tests tests/integration_tests/test_kernel_commandline_match.py::test_lxd_datasource_kernel_override_nocloud_net
```
> Tests proposed install disregard apt policy

- systemd/cloud-config.service.tmpl
- systemd/cloud-init.service.tmpl
```
systemd: Block login until config stage completes
LP: #2013403
```
Discovered on riscv64, cc_set_passwords runs in cloud config stage, but tty access blocked by cloud init stage. This means that a user may be able to try logging in prior to the user account being configured.
download the ubuntu riscv unmatched image, install riscv qemu dependencies, then: 
```
qemu-system-riscv64 \
-machine virt \
-cpu rv64 \
-m 1G \
-device virtio-blk-device,drive=hd \
-drive file=lunar-preinstalled-server-riscv64+unmatched.img,if=none,id=hd \
-device virtio-net-device,netdev=net \
-netdev user,id=net,hostfwd=tcp::2222-:22 \
-bios /usr/lib/riscv64-linux-gnu/opensbi/generic/fw_jump.elf \
-kernel /usr/lib/u-boot/qemu-riscv64_smode/uboot.elf \
-object rng-random,filename=/dev/urandom,id=rng \
-device …
```
> systemd: Block login until config stage completes

- cloudinit/features.py
- cloudinit/sources/__init__.py
- cloudinit/stages.py
- doc/rtd/explanation/instancedata.rst
- tests/integration_tests/modules/test_combined.py
- tests/unittests/sources/test_init.py
- tests/unittests/test_data.py
- tests/unittests/test_features.py
```
instance-data: add system-info and features to combined-cloud-config
Some snap environments (subiquity live installer) have different
versions of cloudinit within the snap environment than is installed
on the host system. Invoking cloudinit.stages.Init().read_cfg on an
older version of cloudinit potentially breaks when the host environment
has a newer version of cloud-init because the obj.pkl can not be
deserialized on an older version of cloud-init.
To avoid having to invoke cloudinit.stages.Init().read_cfg() to get
system_info and default_user config, provide this config in:
- /run/cloud-init/combined-cloud-config.json and
- /run/cloud-init/instance-data-sensitive.json:merged_system_cfg key
Add a system_info key in combined-cloud-config.json as seen in
/etc/cloud/cloud.cfg*.
Also …
```
> instance-data: add system-info and features to combined-cloud-config

- cloudinit/cmd/status.py
- tests/unittests/cmd/test_status.py
```
Inspect systemd state for cloud-init status
Relying solely on status.json and result.json can result in reporting
error before cloud-init has fully completed. Using systemd state can
give us more correct info.
Fixes GH-3769
```
#3769
> Inspect systemd state for cloud-init status

- cloudinit/sources/DataSourceDigitalOcean.py
- doc/rtd/reference/datasources/digitalocean.rst
- tests/unittests/sources/test_digitalocean.py
- tools/.github-cla-signers
```
Add deprecation log during init of DataSourceDigitalOcean
This PR adds a log warning of deprecation when DataSourceDigitalOcean is initialized. The DigitalOcean data source is not maintained and currently overridden in official DigitalOcean images with DataSourceConfigDrive.
Fixes GH-4172
```
Resolves https://github.com/canonical/cloud-init/issues/4172.
More context: https://github.com/canonical/cloud-init/pull/4130#issuecomment-1573884030
> Add deprecation log during init of DataSourceDigitalOcean

- cloudinit/config/cc_landscape.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_landscape.py
- tests/unittests/config/test_schema.py
```
landscape: use landscape-config to write configuration
Avoid writing directly to /etc/landscape/client.conf as formats
or config file location could change.
Invoke the `landscape-config` utility instead to persist landscape
client config options.
No longer restart landscape-client service because
landcape-config starts landscape-client with updated values.
Add doc examples for installing via PPA using apt: config.
```
SC-1531
> landscape: use landscape-config utility

- .github/workflows/cla.yml
- .github/workflows/integration.yml
- cloudinit/config/cc_lxd.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- cloudinit/sources/DataSourceLXD.py
- doc/rtd/howto/predeploy_testing.rst
- doc/rtd/reference/datasources/lxd.rst
- doc/rtd/reference/network-config.rst
- doc/rtd/tutorial/lxd.rst
- tests/integration_tests/modules/test_lxd.py
- tools/.github-cla-signers
- tools/check-cla-signers
- tools/ds-identify
Update many links to LXD now that is under the Canonical umbrella (https://discourse.ubuntu.com/t/faq-lxd-has-been-moved-to-canonical/36709)
> LXD moved from linuxcontainers.org to Canonical

- cloudinit/sources/helpers/vmware/imc/guestcust_util.py
- tests/unittests/test_ds_identify.py
- tools/ds-identify
DS VMware: add i386 arch dir to deployPkg plugin search path
See details in https://bugs.launchpad.net/cloud-init/+bug/1944946, path of open-vm-tools libdeployPkgPlugin.so is now multi-arch compliant. For Debian12 32-bit, the path is /usr/lib/i386-linux-gnu/open-vm-tools/plugins/vmsvc/libdeployPkgPlugin.so. This change is to add  i386-linux-gnu path to search pathes.
Fixes GH-4253
> DS VMware: add i386 arch dir to deployPkg plugin search path

- cloudinit/distros/__init__.py
- cloudinit/net/dhcp.py
- tests/unittests/net/test_dhcp.py
- tools/.github-cla-signers
```
The currently used dhcp client, dhclient, is coming from the unmaintained package,
`isc-dhcp-client` (refer https://www.isc.org/dhcp/) which ended support in 2022.
This change introduce support for the dhcp client, udhcpc, from the busybox project.
Busybox advantages are that it is available across many distributions and comes with
lightweight executables.
```
Already discussed in #2125
> net/dhcp: add udhcpc support

- tools/read-version
git describe may not return version/tags in the format that the read-version tool expects. Make the tool robust so that it can gracefully handle version strings that are not in the regular format.
> tools/read-version: fix the tool so that it can handle version parsing errors

- doc/rtd/development/testing.rst
- tools/.github-cla-signers
**Summary: Remove duplicate Integration testing button**
Removes the duplicate Integration testing button from the documentation. This simplifies the documentation and improves the hierarchy under Development.
_Fixes GH- #4242_
* The duplicate button was originally created as a way to provide a separate entry point for the integration tests from the Development section of the documentation. However, this is no longer necessary, as the integration tests can now be accessed from the main menu.
* Removing the duplicate button will make the documentation simpler and easier to navigate.
* To verify that the duplicate button has been removed, open the documentation and navigate to the Development section. The Integration testing button should now only appear once.
* My code follows the process …
> Remove Testing dropdown

- doc/rtd/development/datasource_creation.rst
```
doc: improve datasource_creation.rst
Clarify that the new datasource doc page has to be referenced in doc/rtd/reference/datasources.rst to be rendered.
```
https://github.com/canonical/cloud-init/pull/4167#discussion_r1269203689
> doc: improve datasource_creation.rst

- config/cloud.cfg.tmpl
- doc/examples/cloud-config-user-groups.txt
- doc/rtd/reference/base_config_reference.rst
- tools/.github-cla-signers
```
Remove default membership in redundant groups
The cloud-init template for Ubuntu currently includes membership in
numerous groups. Many of these are groups that were removed from the
default list over a decade ago on the desktop, and which are better
served by udev rules today. Specifically: audio, dialout, floppy,
netdev, plugdev, video.
LP: #1923363
```
[LP: #1923363](https://bugs.launchpad.net/ubuntu/mantic/+source/user-setup/+bug/1923363)
> Remove default membership in redundant groups

- cloudinit/stages.py
- cloudinit/util.py
- tests/unittests/test_stages.py
- tests/unittests/test_util.py
By default, the cloud init log file is created with mode 0o644 with
`preserve_mode` parameter of `write_file()` set to False. This means that when
an existing log file is found, its mode will be unconditionally reset to the
mode 0o644. It is possible that this might cause the change of the mode of the
log file from the current more stricter mode to a less strict mode
(when the new mode 0o644 is less strict than the existing mode of the file).
In order to mitigate the above issue, check the current mode of the log file
and if the current mode is stricter than the default new mode 0o644, then
preserve the current mode of the file.
Fixes GH-4243
> logging: keep current file mode of log file if its stricter than the new mode

- cloudinit/distros/netbsd.py
- cloudinit/sources/DataSourceAzure.py
- doc/examples/cloud-config.txt
- integration-requirements.txt
- requirements.txt
- tests/integration_tests/bugs/test_gh671.py
- tests/integration_tests/instances.py
- tests/unittests/sources/test_azure.py
- tox.ini
crypt is deprecated in Python 3.11 and will be removed in 3.13. This uses the passlib module to replace it. passlib is a pure-Python package.
See: https://passlib.readthedocs.io
> Remove the crypt dependency

- conftest.py
- tests/unittests/distros/test_create_users.py
- tests/unittests/early_patches.py
- tests/unittests/test_builtin_handlers.py
- tests/unittests/test_cli.py
- tests/unittests/test_stages.py
- tox.ini
```
testing: Clear all LRU caches after each test
Some unit tests were missing necessary mocks because a previous test
had mocked the behavior and mock stuck around because of an LRU cache.
This means that if tests got run out of a specific order, they would
fail due to missing mocks. Because of this, a new autouse fixture was
added to automatically clear any lru cache after every test.
Additionally, updated unit tests accordingly so that they have the
necessary mocks, and convert `test_create_users.py` to pytest as
I was getting some transient errors from it.
```
Been hidden forever, but started surfacing in #4237
> testing: Clear all LRU caches after each test

- tests/integration_tests/test_kernel_commandline_match.py
- tools/ds-identify
```
Fix NoCloud kernel commandline key parsing
Currently >2 keys in NoCloud datasource are not
supported. Previously 250280 attempted to correct
no keys being supported, however that fix was only
partial since more than one key breaks datasource
detection.
Additionally add test coverage.
Fixes GH-4271
```
> Kernel Commandline: Fix 4271

- tests/unittests/test_net.py
```
tests: avoid leaks into host system checking of ovs-vsctl cmd
Mock out the `which` checks for presence of ovs-vsctl cmd on system. This prevents test leaks which eventually call subp ovs-vsctl commands.
```
```
sudo apt install openvswitch-switch
tox -e py3 tests/unittests/test_net.py
FAILED tests/unittests/test_net.py::TestGenerateFallbackConfig::test_device_driver - RuntimeError: called subp. set self.allowed_subp=True to allow
FAILED tests/unittests/test_net.py::TestGenerateFallbackConfig::test_hv_netvsc_vf_filter - RuntimeError: called subp. set self.allowed_subp=True to allow
FAILED tests/unittests/test_net.py::TestNetplanNetRendering::test_render[default_generation] - AssertionError: Unexpectedly used subp.subp
============================================= 3 failed, 4777 passed, …
```
> tests: avoid leaks into host system checking of ovs-vsctl cmd

- cloudinit/distros/netbsd.py
- cloudinit/sources/DataSourceAzure.py
- integration-requirements.txt
- requirements.txt
- test-requirements.txt
- tests/unittests/distros/test_netbsd.py
- tests/unittests/sources/test_azure.py
- tox.ini
```
Don't require passlib dependency
Thee crypt module suffices on old versions of Python.
Use it when available. 
```
TODO: tests
> Don't require passlib dependency

- cloudinit/features.py
- tests/unittests/test_data.py
- tests/unittests/test_features.py
```
Ensure get_features() grabs all features
It was previously ignoring keys with numbers in them.
Additionally, update tests so that they don't have to be patched
downstream any time we add a new feature flag. Since the whole point
of the feature flags is to create overrides, that seems like a lot
of needless churn.
```
Will replace https://github.com/canonical/cloud-init/pull/4279 if accepted.
I more-or-less duplicated the mocking code and comment. If we find we need it in more places, it should probably be refactored into a common fixture then, but for now I'm ok with 2.
> Ensure get_features() grabs all features

- tools/.github-cla-signers
- tox.ini
replaced spaces with commas for setting passenv in tox.ini
```
Replaced spaces with commas for setting passenv in tox.ini  
A recent update of tox-ini made a breaking change in the `tox.ini` file
when using whitespace to set multiple values to the `passenv` variable.
This change was believed to have occurred on the following commit
in the tox repository:
https://github.com/tox-dev/tox/commit/f4840a03
```
> replaced spaces with commas for setting passenv

- cloudinit/config/cc_ssh.py
- cloudinit/config/schema.py
- doc/rtd/reference/modules.rst
- doc/rtd/static/css/custom.css
- tests/unittests/config/test_schema.py
- tests/unittests/test_cli.py
```
Module reference page was previously long lists of descriptions that were hard to consume.
- Add tabs to split up sections within module reference
- Tab syncing is an option, but may not be helpful here so left it off by default
- Subheadings can't be used within tabs, so changed headers in cc_ssh module description
```
> Overhaul module reference page

- debian/changelog
- debian/cloud-init.maintscript
- debian/control
```
Remove unused NetworkManager hook
Silence warnings on old installs during upgrade.
This file was removed in 23.2.1-0ubuntu0 and the
upgrade path issue discovered in 23.2.1-0ubuntu0.
LP: #2027861
```
> Ubuntu/devel: Remove unused NetworkManager hook

- cloudinit/sources/DataSourceAkamai.py
- cloudinit/sources/helpers/akamai.py
- doc/rtd/reference/availability.rst
- doc/rtd/reference/datasource_dsname_map.rst
- doc/rtd/reference/datasources.rst
- doc/rtd/reference/datasources/akamai.rst
- tests/unittests/sources/helpers/test_akamai.py
- tests/unittests/sources/test_akamai.py
- tests/unittests/test_ds_identify.py
- tools/.github-cla-signers
- tools/ds-identify
```
Added support for Akamai Connected Cloud (formerly Linode)
Added a DataSource for the Akamai cloud platform, enabling metadata
and user data retrieval and instance provisioning via cloud-init.
```
Our metadata service is not yet publicly available, and as such this is being opened as a draft.  We have tested this in
our lab environment, and will work with you to get you access to the service when it becomes available in beta in the
near future.
> Added support for Akamai Connected Cloud (formerly Linode)

- cloudinit/distros/__init__.py
- tests/integration_tests/modules/test_users_groups.py
- tests/unittests/distros/test__init__.py
```
full re-runs will no longer write duplicate rules to sudoers file
Rerunning cloud-init would always append sudoer rules to the
sudoers file without checking if the rules already existed first.
This is no longer the case - only unique rules not already found
in the sudoers file will be added to it.
Fixes GH-4048 
LP: #1998539
```
This change maintains the current functionality of only adding rules to the sudoers file without checking for old rules that
should be removed.   
Adding functionality for doing so should probably be addressed in a future ticket. 
See issue #4048 for more context on the bug this ticket is addressing.
- Launch an LXD container using any cloud-init source that isnt this branch with the following cloud-config:
```
#cloud-config for SC-1589
groups:
- admingroup: …
```
> sudoers not idempotent (SC-1589) 

- cloudinit/config/cc_ssh_import_id.py
- tests/unittests/config/test_cc_ssh_import_id.py
```
cc_ssh_import_id: add Alpine support and add doas support
Add Alpine to distros supported by this module.
If sudo is not available then try and use doas as an alternative if
it is available.
```
> cc_ssh_import_id: add Alpine support and add doas support

- debian/changelog
- debian/cloud-init.maintscript
DO NOT SQUASH
When publishing packaging changes to `ubuntu/devel`, I got sponsor feedback that our `rm_conffile` should target the version being prepared rather than any previous version (see the man page quoted in the commit message). Additionally, we should include the LP number for the change.
If this get's a +1, I'll push the same changes for focal and bionic.
> Ubuntu/lunar: Fix removing the unused network manager hook

- tests/unittests/config/test_cc_mounts.py
```
cc_mounts: xfs is a Linux only FS
reflect this in the test, by mocking the kernel_version every time.
```
run unittests on FreeBSD
apply this patch
see one less (if only slightly different) failure
(baby steps.
> cc_mounts: xfs is a Linux only FS

- tests/unittests/test_ds_identify.py
- tools/.github-cla-signers
- tools/ds-identify
```
summary: ds-identify/CloudStack: return $DS_MAYBE if vm is running on vmware/xen
```
Currently, ds-identify determines if CloudStack is supported by checking dmi product name. It works fine on KVM, as the VM has the following system information
```
System Information
Manufacturer: Apache Software Foundation
Product Name: CloudStack KVM Hypervisor
```
However, it does not work on VMware or XenServer/XCP-ng. For example, on VMware, the system information is
```
System Information
Manufacturer: VMware, Inc.
Product Name: VMware Virtual Platform
Version: None
```
Therefore, return $DS_MAYBE instead of $DS_NOT_FOUND if vm is running on vmware/xen.
> ds-identify/CloudStack: return $DS_MAYBE if vm is running on vmware/xen

- cloudinit/config/cc_mounts.py
- tests/unittests/config/test_cc_mounts.py
- tools/.github-cla-signers
```
cc_mounts: Fix swapfile not works on btrfs
To make a swapfile works on btrfs
We need to create an empty file, add "no copy-on-write" attribute
before turn it into swapfile
Fixes GH-3713
LP: #1884127
```
https://btrfs.readthedocs.io/en/latest/Swapfile.html
tox  -- tests/unittests/config/test_cc_mounts.py::TestSwapFileCreation::test_swap_creation_method_btrfs
tests/unittests/config/test_cc_mounts.py::TestSwapFileCreation::test_swap_creation_method_btrfs PASSED [100%]
> cc_mounts: Fix swapfile not works on btrfs

- cloudinit/net/eni.py
- cloudinit/net/network_state.py
- cloudinit/sources/helpers/netlink.py
```
summary: flake8 fixes
Address complaints by newer versions of flake8, these are not picked up by ruff
```
- [ x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
> Flake8 fixes

- tools/test_tools.py
- tox.ini
```
Fix test_tools.py collection
When required setuptools functions are not available, we skip running
the module. Doing this requires specifying `allow_module_level=True`,
which we were not doing before.
```
> Fix test_tools.py collection

- tests/unittests/cmd/devel/test_init.py
Fix the following breakage in `tests/unittests/cmd/devel/test_init.py ::TestReadCfgPaths::test_read_cfg_paths_fetches_cached_datasource`:
`PermissionError: [Errno 13] Permission denied: '/run/cloud-init/cloud.cfg'`
```
def load_file(fname, read_cb=None, quiet=False, decode=True):
LOG.debug("Reading from %s (quiet=%s)", fname, quiet)
ofh = io.BytesIO()
try:
>           with open(fname, "rb") as ifh:
E           PermissionError: [Errno 13] Permission denied: '/run/cloud-init/cloud.cfg'
decode     = True
fname      = '/run/cloud-init/cloud.cfg'
ofh        = <_io.BytesIO object at 0xffff9683bf10>
quiet      = False
read_cb    = None
cloudinit/util.py:1564: PermissionError
```
> unittests: fix breakage in test_read_cfg_paths_fetches_cached_datasource

- cloudinit/util.py
- tests/unittests/test_util.py
```
util.get_proc*: Fix tests on non-Linux systems
`/proc/$pid/environ` and `/proc/$pid/stat` don't exist on BSD.
procfs on BSDs is highly limited, and its use very discouraged.
While FreeBSD has procstat(1), which could reasonably read a process
environment, that use-case in the code is Linux specific and doesn't map
on FreeBSD.
Guard get_proc_env() tests with is_Linux().
The code already mostly uses this as a fallback, when all else fails.
implement get_proc_ppid() with `ps(1)`.
This should work on most platforms that have `ps(1)`.
Fixes: GH-4332
```
> util.get_proc*: Fix tests on non-Linux systems

- tests/unittests/cmd/test_clean.py
```
cmd/clean: fix tests on non-Linux platforms
change clean_script to use `#!/bin/sh` which is guaranteed to exist on
pretty much any Unix (like) system, unlike `/bin/bash`, which could be
anywhere in the PATH.
```
> cmd/clean: fix tests on non-Linux platforms

- tests/unittests/test_subp.py
```
subp: Fix spurious test failure on FreeBSD
Fix a test failure that only seemed to occur when running the full test
suite. Probably due to something not being cleaned up properly.
This adds an env={"LANG": "C"} to simplify the test execution, and makes
the failure go away.
Fixes: GH-4354
```
> subp: Fix spurious test failure on FreeBSD

- cloudinit/analyze/dump.py
- tests/unittests/analyze/test_dump.py
```
analyze: fix (unexpected) timestamp parsing
In case of very unexpected timestamps, we pass them on to date.
Unfortunately, only GNU date is able to perform this level of deduction
(guess work).
Rework the code and tests to look for GNU date on non-Linux platforms.
Only fail, and loudly! if GNU date cannot be found.
This patch (partially)
fixes GH-4333
```
> analyze: fix (unexpected) timestamp parsing

- config/cloud.cfg.tmpl
- tests/unittests/test_render_cloudcfg.py
- tools/render-cloudcfg
```
cloud.cfg.tmpl: reorganise, minimise/reduce duplication
Simplify the cloud.cfg.tmpl file. There is a lot of duplication (e.g.
the same sudo rule specified multiple times).
This also addresses #4267 and aligns Debian-specific template
configuration with Debian's own packaged cloud.cfg, located here:
https://salsa.debian.org/cloud-team/cloud-init/-/blob/master/debian/cloud.cfg
Fixes GH-4267
```
> cloud.cfg.tmpl: reorganise, minimise/reduce duplication

- integration-requirements.txt
- tests/integration_tests/clouds.py
- tests/integration_tests/cmd/test_status.py
- tests/integration_tests/modules/test_power_state_change.py
- tests/integration_tests/test_kernel_commandline_match.py
```
Bump pycloudlib to 1!5.1.0
1!5.0.0 removed 'wait' on launch along with a cloud 'clean' method, so
update our integration testing code appropriately.
```
Required by #4324
> Bump pycloudlib to 1!5.1.0

- cloudinit/config/cc_apt_configure.py
- tests/integration_tests/bugs/test_lp1813396.py
- tests/unittests/config/test_apt_configure_sources_list_v1.py
- tests/unittests/config/test_apt_configure_sources_list_v3.py
- tests/unittests/config/test_apt_source_v1.py
```
apt: fix cloud-init status --wait blocking on systemd v 253
When user-data defines apt: config to setup repos with GPG keyids,
GPG spawns a two background daemons gpg-agent and dirmngr for the
root user.
In systemd 253 and later, systemd will report the systemd
unit as SubState=running instead of SubState=exited. This results in
cloud-init status --wait blocking indefinitely despite the fact that
the cloud-config.service StatusErrno=0 and Result=success.
While the SubState=running doesn't block systemd proceeding to any
units/services declared `After=cloud-config.service` it does block
cloud-init status --wait which will affect external tools/utilities
which may be waiting for cloud-init to complete initial system
configuration.
Rather than altering cloud-init status --wait to observe …
```
> apt: fix cloud-init status --wait blocking on systemd v 253

- doc-requirements.txt
- tools/read-version
```
read-version: fallback to get_version when git describe fails
Annotated git tags are not present in shallow git clones. In shallow
clones, git describe may fail with exit 128 with one of the following
errors:
- No tags can describe <hash>
- No names found, cannot describe anything
If either message is present, fallback to
cloudinit.version.version_string.
This fixes readthedocs CI builds which may use git clone --depth 1 in
Annotated git tags are not present in shallow git clones. In shallow
clones, git describe may fail with exit 128 with one of the following
errors:
- No tags can describe <hash>
- No names found, cannot describe anything
If either message is present, fallback to
cloudinit.version.version_string.
Also pin sphinx=7.1.2 as the release 7.2.0 on  August 17 dropped the …
```
> read-version: fallback to get_version when git describe fails

- cloudinit/apport.py
- cloudinit/settings.py
- tests/unittests/sources/test_common.py
```
fix(akamai): add akamai ds to settings.py and apport.py
Fixes GH-4362
```
Adding some missing things from https://github.com/canonical/cloud-init/pull/4167
> feat(akamai): add akamai to settings.py and apport.py

- doc/examples/seed/README
- doc/rtd/reference/datasources/nocloud.rst
- doc/rtd/tutorial/qemu-script.sh
- doc/rtd/tutorial/qemu.rst
```
Undocument nocloud-net
In f146fe cloud-init developed capability to
automatically determine nocloud mode. Remove
documentation related to nocloud-net since this
is no longer a necessary argument and may
confuse users during debugging.
```
Should probably deprecate use of this key too, to allow eventual code cleanup, but that can be a separate PR.
> Undocument nocloud-net

- cloudinit/config/cc_mounts.py
- tests/unittests/config/test_cc_mounts.py
```
cc_mounts: Use fallocate to create swapfile on btrfs
Swapfile works fine with fallocate on btrfs.
Btrfs official document also use fallocate instead of dd.
See https://btrfs.readthedocs.io/en/latest/Swapfile.html
```
https://btrfs.readthedocs.io/en/latest/Swapfile.html
```
tox -- tests/unittests/config/test_cc_mounts.py::TestSwapFileCreation::test_swap_creation_method_btrfs
tests/unittests/config/test_cc_mounts.py::TestSwapFileCreation::test_swap_creation_method_btrfs PASSED [100%]
```
> cc_mounts: Use fallocate to create swapfile on btrfs

- cloudinit/cmd/devel/logs.py
- tests/unittests/cmd/devel/test_logs.py
```
collect-logs now streams certain outputs to avoid large memory usage
_stream_command_output_to_file() was added to mimic functionality of 
_write_command_output_to_file() except instead of reading the output 
of subprocess calls into memory, it streams the outputs directly to 
the target file. this new function is used when the output of a 
subprocess call does not need to be saved into a variable.
As far as usage goes, the main difference between the two functions
is that the stream function does not return result of the subprocess
call, while the write function does.
Fixes GH-3994
LP: #1980150 
```
See GitHub issue #3994 for more context on the issue this PR seeks to address.
See [comment below](https://github.com/canonical/cloud-init/pull/4289#issuecomment-1664636829) for testing …
> collect-logs fix memory usage (SC-1590)

- cloudinit/sources/azure/imds.py
- tests/unittests/sources/azure/test_imds.py
- tests/unittests/sources/test_azure.py
When fetching metadata or reprovisiondata, allow up to 30 seconds for a read timeout.  For cases where a read request is delayed, this would eliminate extra follow-up request(s).
> azure/imds: increase read-timeout to 30s

- cloudinit/cmd/status.py
- tests/integration_tests/modules/test_puppet.py
- tests/unittests/cmd/test_status.py
b## Proposed Commit Message
```
status: treat SubState=running and MainPID=0 as service exited
Avoid cloud-init status --wait blocking indefinitely on systemd
status SubState=running and MainPID=0 condition for cloud-init
systemd services.
When daemons are spawned by a systemd unit
in the unified heirarchy, long-lived processes or daemons launched by
the systemd unit will be tracked in the CGroup/slice.
As long as spawned daemons of processes live, the systemd tooling will
report the parent systemd unit as SubState=running instead of
SubState=exited.
This affected Ubuntu across the 23.04 -> 23.10 release boundary
because a long-term patch to ignore cgroup status was dropped at
systemd 252.5 which last existed in Ubuntu 23.04 (Lunar).
Cloud-init status --wait checks MainPID == 0 when …
```
> status: treat SubState=running and MainPID=0 as service exited

- cloudinit/config/cc_ansible.py
```
Fix pip-managed ansible
PEP 668 disallows installing packages via pip outside of virtual
environments, to avoid breaking due to conflicting system packages.
Ansible is unlikely to be installed in the base system, and if it is and
the user still chooses to use `install_method: pip`, that would be an
invalid configuration.
This flag exists to allow users to bootstrap ansible to run as a
controller. The alternative solution would be to require virtual
environments, however this is often packaged as a separate dependency,
which further complicates bootstrap. Allow installing ansible outside of
virtual environments via pip's --break-system-packages.
Fixes GH-4244
```
fixes https://github.com/canonical/cloud-init/issues/4244
```
tox -re integration-tests -- …
```
> Fix pip-managed ansible

- cloudinit/sources/helpers/ec2.py
- tests/unittests/sources/helpers/test_ec2.py
https://github.com/canonical/cloud-init/pull/4276 uncovered an issue with the initialization of the return value for get_instance_userdata().  The return value was initialized with
`user_data = ""`
which is a str class.  It then calls `url_helper.read_file_or_url()`, which attempts to retrieve user-data content from IMDS. `read_file_or_url()` returns its results as a bytes object, which is then passed directly up to the caller.  In the event that `read_file_or_url()` does not successfully retrieve content (e.g. because it was given a `file://` path to a nonexistent file or an `http://` path that generates a 404 code), an exception is raised and `get_instance_userdata()` returns the string object initially stored in user_data.
Rather than make the caller cope with return data potentially …
> ec2: initialize get_instance_userdata return value to bytes

- ChangeLog
- cloudinit/version.py
```
Release 23.3
Bump the version in cloudinit/version.py to 23.3 and update ChangeLog.
```
Followed project docs at https://github.com/orgs/canonical/projects/29?pane=issue&itemId=21361535
Because tip of main had 23.2.2 patch version, used https://github.com/canonical/uss-tableflip/pull/112 to generate proper VERSION = "MAJOR.MINOR" in version.py
> Release 23.3

- cloudinit/distros/parsers/sys_conf.py
- tests/unittests/distros/test_sysconfig.py
```
pep-594: drop deprecated pipes module import
python3.11 will deprecated pipes module 3.13 will drop it from main.
cloud-init only used the undocumented pipes.quote function, which is actually only wrapper around shlex.quote[1].
Use shlex.quote instead.
[1] https://github.com/python/cpython/blob/3.11/Lib/pipes.py#L64-L66
```
> pep-594: drop deprecated pipes module import

- tests/integration_tests/clouds.py
```
integration tests: don't clean when KEEP_* flags true
When bumping to pycloudlib version 1!5.0.0, we gained the ability to
clean anything created by the Cloud instance, not just the Instance
instance. This commit ensures we don't do this when KEEP_ settings
are true.
```
> integration tests: don't clean when KEEP_* flags true

- cloudinit/cmd/main.py
```
Log PPID for easier debugging
It is unusual on Linux for cloud-init to be started
by any process besides PID 1. To ease debugging, log
parent process PID and executable.
Note: current implementation only supports Linux 
```
This would ideally be implemented in the distro base class for cleaner cross-distro support, but the distro object isn't yet instantiated as early as we want for this message, and I'd rather not refactor that right now. 
Sample logs:
```
grep -i pid ./cloud-init.log
2023-08-30 17:38:18,306 - main.py[INFO]: PID [1] started cloud-init using: /usr/lib/systemd/systemd
2023-08-30 17:38:19,086 - main.py[INFO]: PID [1] started cloud-init using: /usr/lib/systemd/systemd
2023-08-30 17:38:27,027 - main.py[INFO]: PID [1] started cloud-init using: /usr/lib/systemd/systemd …
```
> Log PPID for better debugging

- cloudinit/config/schemas/schema-cloud-config-v1.json
- tools/.github-cla-signers
```
summary: Update template parameter descriptions in docs #4166 
Enhanced the clarity and detail of template parameter descriptions in cloud-init documentation. 
Specifically, parameters related to the `ntp_client` configuration have been revisited.
Fixes GH-4166
```
> update ntp custom config documentation #4166

- tests/integration_tests/bugs/test_lp1813396.py
```
integration tests: Fix cgroup parsing
It's possible to still have cgroup output for cloud-config.service
even if there are no spawned processes. Instead, use systemd-cgls
to list the cgroup and ensure there are isn't more than 1 line of
output.
```
Fixes https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-ec2/291/testReport/tests.integration_tests.bugs/test_lp1813396/test_gpg_no_tty/
where `systemctl status` output looks like:
```
● cloud-config.service - Apply the settings specified in cloud-config
Loaded: loaded (/lib/systemd/system/cloud-config.service; enabled; vendor preset: enabled)
Active: active (exited) since Fri 2023-09-01 01:06:13 UTC; 3s ago
Process: 802 ExecStart=/usr/bin/cloud-init modules --mode=config (code=exited, …
```
> integration tests: Fix cgroup parsing

- tools/run-lint
- tox.ini
```
Bring back flake8 for python 3.6
Ruff is incompatible with python 3.6. Since we still support 3.6,
bring back the option to run flake8 from the Makefile.
Also bump ruff version to bring flake8 parity.
Fixes GH-4339
```
Note, that this doesn't bring flake8 back to github actions or tox. It is simply for compatibility reasons.
> Bring back flake8 for python 3.6

- doc/rtd/howto/disable_cloud_init.rst
There was a typo in the instruction on disabling cloud-init from the kernel command line. The actual command is:
#echo 'GRUB_CMDLINE_LINUX="cloud-init=disabled"' >> /etc/default/grub
Instead of
#echo 'GRUB_CMDLINE_LINUX=cloud-init.disabled' >> /etc/default/grub
Fix it.
> doc: fix instructions on how to disable cloud-init from kernel commadline

- tests/integration_tests/modules/test_disk_setup.py
```
integration tests: fix mount indentation
Commit cda82fe changed the indentation level in cloud.cfg causing
the sed to replace improperly.
```
Fixes https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-lxd_vm/303/testReport/junit/tests.integration_tests.modules.test_disk_setup/TestPartProbeAvailability/test_disk_setup_when_mounted/
> integration tests: fix mount indentation

- cloudinit/config/cc_apt_configure.py
- tests/integration_tests/bugs/test_lp1813396.py
- tests/unittests/config/test_apt_configure_sources_list_v1.py
- tests/unittests/config/test_apt_configure_sources_list_v3.py
- tests/unittests/config/test_apt_source_v1.py
```
Upstream commit 842d0452 introduced a dependency on gpgconf
utility without a strict Depends: clause in debian/control.
While gnupg is in Recommends for cloud-init, some images
like Ubuntu minimal will not install the package Recommends
to keep images smaller.
To avoid adding a hard Requires dependency on gpgconf, use os.kill
directly to stop any dirmngr and gpg-agent when spawned by
cloud-config's root ppid due to apt-related user-data.
NOOP If no gpg-agent or dirmngr processes are spawned by PPID 1.
LP: #2034273
```
As this represents a regression in behavior for Ubuntu minimal images and possibly Debian images without gpgconf, this is going to require a hotfix release of 23.3.1
```
./tools/run-container --package ubuntu/mantic …
```
> apt: kill dirmngr/gpg-agent without gpgconf dependency

- ChangeLog
- cloudinit/config/cc_apt_configure.py
- cloudinit/version.py
- debian/changelog
- tests/integration_tests/bugs/test_lp1813396.py
- tests/unittests/config/test_apt_configure_sources_list_v1.py
- tests/unittests/config/test_apt_configure_sources_list_v3.py
- tests/unittests/config/test_apt_source_v1.py
Ran `new_upstream_snapshot.py -b 2033310 -c 23.3.1`, then manually updated version number and removed old snapshot message in log.
> Ubuntu/lunar 23.3.x new_upstream_snapshot

- cloudinit/net/network_manager.py
- cloudinit/net/sysconfig.py
- tests/unittests/test_net.py
When network type is ipv6_dhcpv6-stateful/stateless/slaac, cloud-init seems to
enable dhcp for both ipv4 and ipv6. Network manager prefers dhcp over ipv4 and
hence dhcp6 is not used to obtain the IP address. This is incorrect.
For only ipv6_dhcpv6-stateful/stateless/slaac networks, we should set:
`ipv4.method = disabled // disables all ipv4 dhcp`
For ifcfg files (sysconfig renderer), the corresponding changes should be:
`BOOTPROTO = none // instead of dhcp so that dhcp4 is disabled.`
Additionally, for only ipv6_dhcpv6_stateful, we should set:
`ipv6.may-fail = no // dhcp6 must succeed.`
which translates to the following ifcfg setting:
`IPV6_FAILURE_FATAL = yes // so that dhcp6 should succeed.`
This patch fixes this for rhel. The patch has been tested by Red Hat QE.
RHBZ: 2046491
fixes: …
> net: fix ipv6_dhcpv6_stateful/stateless/slaac configuration for rhel

- cloudinit/config/cc_ca_certs.py
- cloudinit/config/cc_grub_dpkg.py
- cloudinit/config/cc_lxd.py
- cloudinit/distros/__init__.py
- cloudinit/subp.py
- tests/unittests/config/test_cc_ca_certs.py
```
Fix typing issues in subp module
Add the 'SubpResult' return type from subp and fix some associated
typing issues
Additionally convert to using f-strings, use if expressions rather
than if blocks where applicable, and enforce subp kwargs
```
Adding `-> SubpResult` to subp's type signature wound up exposing other typing issues from mypy.
> Fix typing issues in subp module

- tests/integration_tests/instances.py
Use commit message.
[Some integration tests](https://github.com/canonical/cloud-init/blob/fd214a1243011275c5dffb92b481c235e4c7a1bf/tests/integration_tests/test_kernel_commandline_match.py#L75) expect the instance to never receive a network connection, such as with lxc which may use a console connection in these cases. This causes errors on traceback when attempting to print the ip, which is only done for convenience. In these cases just don't print the ip address.
Error during teardown:
```
================================================================================== short test summary info ===================================================================================
ERROR tests/integration_tests/test_kernel_commandline_match.py::test_lxd_disable_cloud_init_env - …
```
> Work around no instance ip

- cloudinit/distros/gentoo.py
```
Upstream gentoo patch
https://launchpadlibrarian.net/394553826/0001-Fix-Gentoo-package-installation-command.patch
Fixes GH-3260
```
I thought this was already fixed, but apparently not. Fixes #3260.
> upstream gentoo patch

- cloudinit/config/cc_apt_configure.py
- tests/unittests/config/test_apt_configure_sources_list_v1.py
- tests/unittests/config/test_apt_configure_sources_list_v3.py
- tests/unittests/config/test_apt_source_v3.py
```
tests: convert multiple cc_apt_configure tests to pytest
Adapt test_apt_configure_sources_list_v1.py,
test_apt_configure_sources_list_v3.py and test_apt_source_v3.py
to pytest
One functional change made for test support in cc_apt_configure.
- add_apt_sources function only prepends target test_apt_source_v3.py path to filename
if filename does not already start with target.
No production logic invokes add_apt_sources with target= param set.
For pytest conversion, the following procedure was followed:
- Make use of fake_filesystem fixture and avoid subclassing from FilesystemMockingTestCase
- Rector common EXAMPLE_TMPL, reusing it as a base test content/layout representation in
YAML_TEXT_CUSTOM_SL.
- use a common setup fixture in a class for typical mocks are needed for tests
- use …
```
> Pytestify apt config test modules

- cloudinit/sources/__init__.py
Users with datasource_list = [Azure, None] started failing to boot
properly outside of Azure with the changes to override datasource detection.
If the fallback "None" is included in the datasource_list, do not treat
the system as configured with a single datasource.
If users want to force a single datasource regardless of detection,
they can do so by removing None from the list.
> sources: do not override datasource detection if None is in list

- cloudinit/config/cc_ubuntu_advantage.py
- tests/integration_tests/modules/test_ubuntu_advantage.py
- tests/integration_tests/releases.py
- tests/integration_tests/util.py
- tests/unittests/config/test_cc_ubuntu_advantage.py
- tools/.github-cla-signers
```
cc_ubuntu_advantage: do not rely on uaclient.messages module
Importing a uaclient module that is not under "uaclient.api" is not
supported and likely to break in the future.
The expected message_codes are defined as part of the API of `pro enable
--format=json` and won't change, so we don't lose anything by hardcoding
the value.
```
No functional change. The ubuntu_advantage `enable` and `enable_beta` options should still work.
> cc_ubuntu_advantage: do not rely on uaclient.messages module

- cloudinit/config/cc_apt_configure.py
- tests/unittests/config/test_apt_configure_sources_list_v1.py
- tests/unittests/config/test_apt_configure_sources_list_v3.py
- tests/unittests/config/test_apt_source_v1.py
- tests/unittests/config/test_apt_source_v3.py
Note that this still hasn't been broken in the latest mantic images, so I can't actually confirm that the fix works other than manually uninstalling packages and re-running cloud-init.
```
Install gnupg if gpg not found
Ubuntu recommends gnupg in its packaging but does not require it, and
minimal images will no longer contain gnupg. Given that gpg is only
used for apt key handling, rather than having a hard requirement,
this commit installs gnupg if no gpg binary is found.
Fixes GH-4410
```
https://github.com/canonical/cloud-init/issues/4410
> Install gnupg if gpg not found

- cloudinit/config/cc_ansible.py
- tests/unittests/util.py
```
Fix pip-managed ansible on pip < 23.0.1
Commit b417b218 broke pip-managed ansible with
pip < 23.0.1 and fixed pip-managed ansible with
pip >= 23.0.1. Gate change by pip version to
correctly operate on both versions.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-lxd_vm/303/testReport/junit/tests.integration_tests.modules/test_ansible/test_ansible_controller/
> Fix pip-managed ansible on pip < 23.0.1

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
When reporting failure the _negotiated flag is not set to True. This may result in reporting success when we do the final check for _negotiated to report ready at the end of the process.
Azure ignores the additional report so there weren't unexpected "successful" deployments but the report is unnecessary and conflicting with the prior log.
- Set or reset _negotiated flag in various _report_ready*() methods.
- Add a test case to verify this scenario.
> sources/Azure: fix for conflicting reports to platform

- tests/integration_tests/modules/test_ubuntu_advantage.py
```
integration test: allow pro service warnings
Even if pro is giving us warnings, that is showing that cloud-init
enabled things correctly.
```
An integration test is failing due to livepatch warning that a kernel is not supported. While this may be a problem, it should be caught elseware and is not a problem in cloud-init.
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-ec2/306/testReport/tests.integration_tests.modules.test_ubuntu_advantage/TestUbuntuAdvantagePro/test_custom_services/
> integration test: allow pro service warnings

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
```
In VM SKUs with large ephemeral disk, the NTFS-formatted resource disk
might have the SVI (System Volume Information) folder present. This 
causes cloud-init to skip formatting the resource disk for these SKUs 
during VM stop/start. This PR adds the SVI folder to the list of files 
cloud-init should ignore when it attempts to check if there is any user 
data on the resource disk.
```
> sources/Azure: Ignore system volume information folder while scanning for files in the ntfs resource disk

- cloudinit/config/cc_apt_configure.py
- tests/integration_tests/modules/test_apt.py
- tests/unittests/config/test_apt_configure_sources_list_v1.py
- tests/unittests/config/test_apt_configure_sources_list_v3.py
- tests/unittests/config/test_apt_source_v1.py
- tests/unittests/config/test_apt_source_v3.py
```
apt: install software-properties-common when absent but needed
When optional user-data contains APT sources configuration that warrants source repo setup, cloud-init calls add-apt-repository which is packaged in software-properties common.
The software-properties-common package is defined as a Recommends: in debian/control, and some minimal images do not install recommended packages.
When minimal images do not have software-properties-common installed, cloud-init will install this package on first boot only when required by optional apt sources user-data.
The gnupg package is another optional/recommended package that willl be installed is specific apt user-data config requires gpg interaction.
Refactor _ensure_gpg to _ensure_dependencies to only attempt to install missing dependencies …
```
> apt: install software-properties-common when absent but needed

- doc/rtd/index.rst
- doc/rtd/introduction.rst
```
One thing cloud-init has been lacking is a high-level overview of what it is,
what it does, and how it works. Once we are happy with the general structure
and content of this introduction, I will also add links to the various pages
around the docs that a newcomer might want to visit for more information on
each of the topics.
```
> Add cloud-init overview/introduction

- cloudinit/sources/DataSourceOVF.py
- cloudinit/sources/DataSourceVMware.py
- doc/rtd/reference/datasources/ovf.rst
- doc/rtd/reference/datasources/vmware.rst
- tests/unittests/sources/test_ovf.py
- tests/unittests/sources/test_vmware.py
- tests/unittests/test_ds_identify.py
- tools/ds-identify
Addresses #4436
```
vmware: Fallback to vmtoolsd if rpctool errs
This patch udpates the ds-identify script and the
VMware datasource to fall back to using the
vmtoolsd program if vmware-rpctool errors.
Fixes GH-4436
```
I validated the output and exit code for both commands:
```shell
$ vmtoolsd --cmd "info-get guestinfo.userdata.encoding"; echo $?
gzip+base64
0
```
```shell
$ vmware-rpctool "info-get guestinfo.userdata.encoding"; echo $?
gzip+base64
0
```
```shell
$ vmtoolsd --cmd "info-get guestinfo.userdata.enc"; echo $?
No value found
1
```
```shell
$ vmware-rpctool "info-get guestinfo.userdata.enc"; echo $?
No value found
1
```
* Locally I verified the OVF datasource with:
```shell
make clean_pyc && PYTHONPATH="$(pwd)" python3 -m pytest -v --log-level=DEBUG …
```
> vmware: Fall back to vmtoolsd if vmware-rpctool errs

- doc/rtd/reference/faq.rst
```
Don't recommend using cloud-init as a library
```
Whoever put that in the docs didn't know what they were talking about.
> Don't recommend using cloud-init as a library

- cloudinit/net/sysconfig.py
- doc/rtd/reference/network-config.rst
- tests/unittests/cmd/devel/test_net_convert.py
- tests/unittests/test_net.py
cloud-init does not necessarily generate its configuration files upon instance boot. If cloud-init service is disabled or if cloud-init network configuration is disabled either using Linux kernel command line `network-config=disabled` or by cloud-init configuration
```
network:
config: disabled
```
, cloud-init will not generate those config files. Hence, using the word "on instance boot" on the config file header could be misleading on those circumstances and confuse users. Remove it.
> net: remove the word "on instance boot" from cloud-init generated config

- cloudinit/apport.py
- tests/unittests/test_apport.py
```
feat(apport): collect ubuntu-pro logs if keys present in cloud-config
```
https://warthogs.atlassian.net/browse/SC-1439
> feat(apport): collect ubuntu-pro logs if keys present in cloud-config (SC-1439)

- cloudinit/cmd/devel/__init__.py
- cloudinit/config/schema.py
- cloudinit/safeyaml.py
- tests/unittests/test_safeyaml.py
Fix schema annotation handling and schema marks for nested sequences and maps.
```
schema: handle nested dicts and lists in schema marks and annotation
YAML schema processing of sequences will process the root node and
then leaf-first processing of children. This adds complexity for nested
maps and sequences that may live under intermediate parents below the
root because those parents have not yet been processed.
Refactor safeyaml schemamark handling to cope with depth-first
processing of nested mappings and sequences.
Make SchemaPathMarks a class instead of namedtuple to allow for
operator overloading of equality and contains operators.
Add helper private functions to correct the parentage of
schema marks during construct_sequence and construct_mapping calls
when the newly schema mark …
```
> Schema annotate nested sequence and dict

- cloudinit/config/cc_ansible.py
- cloudinit/config/cc_apt_configure.py
- cloudinit/config/cc_chef.py
- cloudinit/config/cc_landscape.py
- cloudinit/config/cc_mcollective.py
- cloudinit/config/cc_puppet.py
- cloudinit/config/cc_salt_minion.py
- cloudinit/distros/__init__.py
- cloudinit/distros/alpine.py
- cloudinit/distros/arch.py
- cloudinit/distros/bsd.py
- cloudinit/distros/gentoo.py
- cloudinit/distros/opensuse.py
- cloudinit/distros/photon.py
- cloudinit/distros/rhel.py
- tests/integration_tests/modules/test_package_update_upgrade_install.py
- tests/unittests/config/test_cc_ansible.py
- tests/unittests/config/test_cc_landscape.py
- tests/unittests/config/test_cc_mcollective.py
- tests/unittests/config/test_cc_package_update_upgrade_install.py
- tests/unittests/config/test_cc_puppet.py
- tests/unittests/distros/test_init.py
```
Fix regression in package installation
This commit addresses 3 issues introduced by commit 226ba25.
1. We regressed the ability to provide specific
versions in generic package installs with the `packages:`
directive in #cloud-config YAML.
2. Package installation failure changed to logging error rather than
raising Exception.
3. Package lists being passed to package installation became constrained
to `packages` schema when it was originally more open.
To fix 1, added _validate_entry function to ensure packages specified
at both the top level and under a package manager are parsed the same.
To fix 2, raise Exception rather than log error if package installation
fails. Also, change any intermediary package install failures to INFO
rather than ERROR.
To fix 3, apply typing to the pkglist …
```
> Fix regression in package installation

- integration-requirements.txt
- tests/integration_tests/modules/test_ubuntu_advantage.py
```
Revert allowing pro service warnings in tests
This reverts commit 67bb6aa3. Since pycloudlib has been updated to
no longer allow a failure of this type, we can be more stringent
in what we allow.
Additionally, bump pycloudlib version accordingly.
```
https://github.com/canonical/pycloudlib/pull/320/files
> Revert allowing pro service warnings

- .github/workflows/linkcheck.yml
- doc/rtd/conf.py
- tools/.github-cla-signers
workflow for linkcheck in CI 
Workflow subject to changes by maintainers.
Fixes GH- #4460
> [enhancement]: Automatically linkcheck in CI

- cloudinit/config/cc_apt_configure.py
- tests/integration_tests/modules/test_apt_functionality.py
```
*     tests: apt re.search to match alternative ordering of installed pkgs
Given that different versions of python may order set items
differrently, update log matching for logs containing either:
install gnupg software-properties-common
- or -
install software-properties-common gnupg
*     apt: doc apt_pkg performance improvement over subp apt-config dump
```
1. Fixes failing jenkins tests due to different sort order of packages installed https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-ec2/lastSuccessfulBuild/testReport/
2. Documents the reason we have an apt_pkg ImportError fallback to a less performant subp(apt-config dump) in response to review comments on https://github.com/canonical/cloud-init/pull/4472
> Apt tests and docs

- cloudinit/net/__init__.py
- tests/unittests/net/test_init.py
- tests/unittests/test_net.py
This will make sure on Azure we can use both dhcp4 and dhcp6 when IMDS is not used. This is useful in situations where only ipv6 network is available and there is no dhcp4 running.
Fixes GH-4439
> net: allow dhcp6 configuration from generate_fallback_configuration()

- cloudinit/config/cc_ubuntu_advantage.py
- tests/unittests/config/test_cc_ubuntu_advantage.py
1. fix ua enable to avoid passing `--` to the command line  (this wasn't caught in integration tests as the tests were inadvertently skipped in jenkins.
2. Shift cloud-init from invoking `ua` on the command line to using the preferred `pro` name for the command to align with branding.
Fixes# 
```
*     ua: shift CLI command from ua to pro for all interactions
Because the Ubuntu advantage is branded pro, the command-line utility
is also named 'pro' for which an alias of 'ua' exists. Eventually,
ua will likely be deprecated, so shift away from calling ua in favor of
pro.
*   pro: avoid double-dash when enabling inviddual services on CLI
When ubuntu_advantage: enable: [] lists individual services,
cloud-init invokes the pro CLI incorrectly by providing a
double-dash '--' which the …
```
> Pro enable fix and shift to using pro command instead of ua

- cloudinit/config/cc_timezone.py
- tests/integration_tests/modules/test_combined.py
```
test: use a mantic-compatible tz in t/i/m/test_combined.py
```
In Debian testing and Ubuntu Mantic+, some legacy timezones under `/usr/share/timezone` have been moved from `tzdata` to `tzdata-legacy`.
Per [cc_timezone](https://cloudinit.readthedocs.io/en/latest/reference/modules.html#timezone) and https://github.com/canonical/cloud-init/issues/3761#issuecomment-1545387654, non-present timezones are historically treated as config errors. So, update the integration test to include a timezone compatible across the board.
Fixes: 
- https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-mantic-lxd_vm/lastCompletedBuild/testReport/tests.integration_tests.modules.test_combined/TestCombined/test_timezone/
- …
> test: use a mantic-compatible tz in t/i/m/test_combined.py

- tests/integration_tests/modules/test_apt_functionality.py
```
integration test fix for deb822 URI format
```
Jenkins failures exhibiting this test failure
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-azure/320/testReport/tests.integration_tests.modules.test_apt_functionality/TestDefaults/test_security/
> integration test fix for deb822 format on azure platform

- .github/workflows/linkcheck.yml
```
ci(linkcheck): fix invalid ternary operator
```
I am not sure why `github.event_name == 'workflow_dispatch' && github.event.inputs.failOnError` is needed at all, but the JS-sh ternary operator (x ? y : z) it not a valid [action expression](https://docs.github.com/en/actions/learn-github-actions/expressions), as shown in https://github.com/canonical/cloud-init/actions/runs/6429056328.
> ci(linkcheck): fix invalid ternary operator

- cloudinit/distros/rhel.py
- tools/.github-cla-signers
Fix override of systemd_locale_conf in RHEL distro
> Systemd_locale_conf filename parameter gets overridden

- sysvinit/freebsd/dsidentify.tmpl
```
ds-identify: Allow disable service and override environment
This PR allows disabling the ds-identify service on FreeBSD, without
having to delete the service file.
It also overrides two environment variables when running the service
to ensure that on FreeBSD, paths are where they are to be expected.
Fixes GH-4481
Co-authored-by: Dave Cottlehuber <dch@skunkwerks.at>
```
> ds-identify: FreeBSD fixes

- cloudinit/sources/azure/imds.py
- tests/unittests/sources/azure/test_imds.py
Allow retries for 429 when fetching reprovisiondata. 429 is used when exceeding rate-limits and is currently retried for fetching instance metadata.
A tight retry-loop was observed on older versions of cloud-init where we had a series of short (2 second) read timeouts.  We expect this had triggered the rate-limiting due to max concurrent connections (from IMDS' perspective). Then _poll_imds() then entered a tight retry loop, spamming the logs until connections were allowed to resume.
The standard sleep between readurl() retries should be an adequate backoff if 429 is observed.
> azure/imds: retry on 429 errors for reprovisiondata

- Makefile
- cloudinit/cmd/status.py
- doc/rtd/howto/disable_cloud_init.rst
- systemd/cloud-config.service.tmpl
- systemd/cloud-final.service.tmpl
- systemd/cloud-init-generator.tmpl
- systemd/cloud-init-local.service.tmpl
- systemd/cloud-init.service.tmpl
- systemd/cloud-init.target
- tests/integration_tests/test_kernel_commandline_match.py
- tests/unittests/cmd/test_status.py
- tests/unittests/test_ds_identify.py
- tools/ds-identify
- tools/render-cloudcfg
The commits in this PR are written separately with the intent of being added to the git tree individually. 
<details>
<summary>Old squashed commit message</summary>
```
Move disable checks out of systemd generator
- Add environment variable check to unit conditionals
- Change unit conditionals from rhel-only to all distros
- Add unit conditionals to cloud-init target
- Makefile: Benchmark generator script
- generator: Remove redundant code
- generator: Eliminate variables, branches and functions
- docs: Describe environment variable disablement method
- cloud-init status: Fix bug in containers where
disabling cloud-init with KERNEL_CMDLINE causes
cloud-init status --wait to loop indefinitely
- Add integration test coverage for disablement
- KERNEL_CMDLINE environment variable is now …
```
> Move disable checks out of systemd generator

- .github/workflows/unit.yml
```
Make Python 3.12 CI test non-experimental
Python 3.12 is released upstream. Require it.
```
> Python 3.12 has been released. Require CI tests to pass.

- cloudinit/cmd/main.py
```
Remove logging of PPID path
Attempting to read /proc/1/exe is now causing permission denied errors.
Since we're only accessing the path to log it, and the ppid gives us
enough information, just stop logging it.
```
Traceback in logs when starting cloud-init:
```
2023-10-10 15:05:42,002 - util.py[DEBUG]: Cloud-init v. 23.3.1 running 'init-local' at Tue, 10 Oct 2023 15:05:41 +0000. Up 1.77 seconds.
2023-10-10 15:05:42,003 - util.py[WARNING]: failed stage init-local
2023-10-10 15:05:42,003 - util.py[DEBUG]: failed stage init-local
File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 776, in status_wrapper
ret = functor(name, args)
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 354, in main_init …
```
> Remove logging of PPID path

- tests/unittests/conftest.py
- tests/unittests/test_cli.py
```
tests: Add logging fix
Prior to 6bbbfbbb03, cloud-init's logger was initialized during module
load in cloudinit/log.py and cloudinit/cmd/main.py. Running individual
unittests exposes that many tests assume logging to be configured
automatically as it was before. Configure automatically in conftest.py.
```
Without this fix running various individual test files, such as test_schema.py, causes failures due to unconfigured logging:
```
FAILED tests/unittests/config/test_schema.py::TestValidateCloudConfigSchema::test_validateconfig_schema_emits_warning_on_missing_jsonschema - AssertionError: assert 'Ignoring schema validation. jsonschema is not present' in ''
FAILED tests/unittests/config/test_schema.py::TestValidateCloudConfigSchema::test_validateconfig_logs_deprecations[schema0-config0-De …
```
> Add logging setup fixture

- doc/rtd/reference/datasources/nocloud.rst
Fix the missing mcopy argument
```
Mcopy's last argument is the destination, which was missing in the example.
Run the command from the original file, check the vfat and see that it didn't work. Run the new command and see it works.
> Fix the missing mcopy argument

- cloudinit/distros/debian.py
- tests/unittests/distros/test_debian.py
```
Set Debian's default locale to be C.UTF-8
When no locale is found in /etc/default/locale, cloud-init was
defaulting to generating en_US.UTF-8. This can be an expensive operation
and isn't necessary. Instead, change the default to C.UTF-8 which
generally shouldn't require generation.
Also add some logging to make it more obvious where cloud-init is
getting the locale information from.
LP: #2038945
```
> Set Debian's default locale to be C.UTF-8

- cloudinit/net/sysconfig.py
It is not necessary for NetworkManager renderer to keep NM out of the loop from handling DNS. This is unlike sysconfig renderer where we explicitly add `dns=none` in `/etc/NetworkManager/conf.d/99-cloud-init.conf` NetworkManager configuration file in order to prevent NetworkManager from handling DNS and writing `/etc/resolv.conf`. This is because NetworkManager renderer writes DNS information in the interface keyfile and does not manipulate `/etc/resolv.conf` directly. NetworkManager reads this information from the keyfile and handles DNS, including managing `/etc/resolv.conf`. Sysconfig renderer on the other hand directly writes `/etc/resolv.conf` directly and hence we need to make sure NetworkManager is not overwriting the DNS data in `/etc/resolv.conf`.
Add a comment explaining the …
> add comment explaining difference between sysconfig and NetworkManager renderer

- cloudinit/config/cc_apt_configure.py
- tests/unittests/config/test_cc_apt_configure.py
```
If no apt-sources config is given, then no apt dependencies are required to be installed.
This avoids unneeded calls to apt-update and apt-install.
The problem was introduced in 015543d304.
```
https://github.com/canonical/cloud-init/pull/4441
```
lxc launch ubuntu-daily:devel mm
lxc shell mm
$ grep -E 'apt-update|apt-install' /var/log/cloud-init.log
2023-10-17 14:50:41,775 - util.py[DEBUG]: apt-update [eatmydata apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet update] took 8.957 seconds
2023-10-17 14:50:42,142 - util.py[DEBUG]: apt-install [eatmydata apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet install] took 0.366 seconds
```
> fix(cc_apt_configure): avoid unneeded call to apt-install

- .github/PULL_REQUEST_TEMPLATE.md
```
chore: fix PR template rendering
GH seems to not respect proper Markdown rendering rules, splitting lines
where it shouldn't. Revert to single lines to avoid the issue.
```
[the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
[unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html)
accordingly
[documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html)
accordingly
> chore: fix PR template rendering

- cloudinit/sources/azure/imds.py
max_connection_errors is treated more like "retry_connection_errors" where it will retry up to specified number of errors rather than aborting when max_connection_errors is hit.
Update the max_connection_errors to abort once that number is seen.
Bump the max_connection_errors default by 1 so no behavior is changed.
> azure/imds: refactor max_connection_errors definition

- cloudinit/subp.py
Sometimes a script may itself have executable permission but the underlying
file system on which the script is located may have been mounted with 'noexec'
mount option. On those cases is_exe() would return false and the file would
be silently skipped. Add a warning log when a file is being skipped so that
it can be noticed and provides useful information while debugging issues.
> subp: add a log when skipping a file for execution for lack of exe permission

- debian/changelog
- debian/patches/do-not-block-user-login.patch
- debian/patches/series
> Ubuntu/lunar: Revert behavior, allow user login after cloud-init stage

- debian/changelog
- debian/patches/do-not-block-user-login.patch
- debian/patches/series
> Ubuntu/devel: Revert behavior, allow user login after cloud-init stage

- debian/changelog
- debian/patches/do-not-block-user-login.patch
- debian/patches/series
> Ubuntu/mantic: Revert behavior, allow user login after cloud-init stage

- debian/changelog
- debian/patches/do-not-block-user-login.patch
- debian/patches/series
> Ubuntu/jammy: Revert behavior, allow user login after cloud-init stage

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
For Savable PPS we rely on a connectivity check to IMDS to determine if the NIC is primary.  However, in some cases, connectivity may be delayed and we incorrectly assume the NIC is not primary.
Instead of relying on connectivity, check the DHCP-provided route configuration for the presence of Wireserver and/or IMDS IPs.
- Return bool from _setup_ephemeral_networking() indicating primary NIC or not.
- Remove _check_if_nic_is_primary() used in Savable PPS.
- Add a relevant diagnostic to assist debugging failures when a secondary NIC is chosen.
- Remove some tests that are redundant.
> azure: check for primary interface when performing DHCP

- ChangeLog
- cloudinit/config/cc_ansible.py
- cloudinit/version.py
- debian/changelog
`new_upstream_snapshot.py -c 23.3.3 -b 2040291`
I popped off the quilt refresh as it isn't necessary and adds noise to the hotfix
> Ubuntu/mantic 23.3.x

- ChangeLog
- cloudinit/config/cc_ansible.py
- cloudinit/version.py
- debian/changelog
new_upstream_snapshot.py -c 23.3.3 -b 2040291
I popped off the quilt refresh as it isn't necessary and adds noise to the hotfix
> Ubuntu/jammy 23.3.x

- ChangeLog
- cloudinit/config/cc_ansible.py
- cloudinit/version.py
- debian/changelog
new_upstream_snapshot.py -c 23.3.3 -b 2040291
I popped off the quilt refresh as it isn't necessary and adds noise to the hotfix
> Ubuntu/lunar 23.3.x

- ChangeLog
- cloudinit/config/cc_ansible.py
- cloudinit/version.py
- debian/changelog
new_upstream_snapshot.py -c 23.3.3 -b 2040291
I popped off the quilt refresh as it isn't necessary and adds noise to the hotfix
> Ubuntu/focal 23.3.x

- cloudinit/config/schema.py
- cloudinit/config/schemas/schema-network-config-v1.json
- cloudinit/helpers.py
- cloudinit/stages.py
- doc/rtd/reference/cli.rst
- doc/rtd/reference/network-config.rst
- tests/integration_tests/modules/test_combined.py
- tests/unittests/config/test_cc_apt_pipelining.py
- tests/unittests/config/test_cc_bootcmd.py
- tests/unittests/config/test_cc_ca_certs.py
- tests/unittests/config/test_cc_growpart.py
- tests/unittests/config/test_cc_mounts.py
- tests/unittests/config/test_cc_update_etc_hosts.py
- tests/unittests/config/test_cc_users_groups.py
- tests/unittests/config/test_schema.py
- tests/unittests/reporting/test_reporting.py
- tests/unittests/test_stages.py
Wire network warnings to schema logs
Write /run/cloud-init/network-config.json reflecting cloud-init's source network-config
Add the following to the cloud-init schema sub command:
- cloud-init schema --system now validates network-config
- new cloud-init schema --config-type param accepts "network-config" when testing config files for development
```
*     schema: network-config optional network key. Use route def uses oneOf
network-config schema now permits optional top-level network key.
We should generally be using oneOf declarations in JSON schema.
Fix anyOf_type_route schema definition.
Update route definition to oneOf from anyOf requiring either
'network' or 'destrination' key, combined with a 'gateway' key.
* schema: add cloud_init_deepest_matches for best_match error message
Plug …
```
> schema: emit network schema warnings in logs schema --system validates network

- integration-requirements.txt
- test-requirements.txt
- tools/read-dependencies
```
test: unpin pytest
After https://github.com/pytest-dev/pytest/pull/11125 being
included in pytest==7.4, pytest can be unpinned.
```
https://github.com/canonical/cloud-init/pull/4184
https://github.com/pytest-dev/pytest/issues/11104
https://github.com/pytest-dev/pytest/pull/11125#issuecomment-1600235619
```sh
tox -re integration-tests -- --collect-only tests/integration_tests/
```
With pytest==7.3.2 the following traceback appeared:
```
ImportError while loading conftest '/home/aciba/canonical/cloud-init/tests/unittests/conftest.py'.                                                                                                                 
tests/unittests/conftest.py:11: in <module> …
```
> test: unpin pytest
