canonical/cloud-init

doc/rtd/topics/datasources/configdrive.rst

docs: Update the configdrive datasource links

---

cloudinit/config/cc_set_hostname.py

Correct jumbled documentation for cc_set_hostname module

---

tools/migrate-lp-user-to-github

To test:
./tools/migrate-lp-user-to-github <your_launchpad_user> <your_github_user>

tools: migrate-lp-user-to-github cleans up repo_dir on error

---

cloudinit/util.py

that should make for a slightly prettier and less confusing log

dmidecode: log result *after* stripping \n

---

cloudinit/tests/test_url_helper.py

This is to fix an issue with the linting.

Patch url helper

---

tools/.lp-to-git-user

lp-to-git-users: adding fred-lefebvre

---

doc/rtd/topics/format.rst

doc: add kernel command line option to user data

---

tools/.lp-to-git-user

lp-to-git-users: adding ad-m

---

tools/migrate-lp-user-to-github

Reduce incosistency and allow use virtualenv for launchpad packages.
```
$ grep '^#!.*env python' ./tools/ -E -r
./tools/read-version:#!/usr/bin/env python
./tools/render-cloudcfg:#!/usr/bin/env python3
./tools/read-dependencies:#!/usr/bin/env python
./tools/cloudconfig-schema:#!/usr/bin/env python3
./tools/validate-yaml.py:#!/usr/bin/env python
```

tools: Detect python to use via env in migrate-lp-user-to-github

---

HACKING.rst
doc/rtd/topics/modules.rst

doc: specify _ over - in cloud config modules

---

cloudinit/apport.py
cloudinit/settings.py
cloudinit/sources/DataSourceRbxCloud.py
doc/rtd/topics/datasources.rst
doc/rtd/topics/datasources/rbxcloud.rst
tests/unittests/test_datasource/test_common.py

I have a number of small changes. Please review commit-by-commit, since the appropriate separation has been preserved.
If combined commits is a problem - it will create several separate PRs.

Add tests for dsname in datasource

---

ChangeLog
cloudinit/version.py

Bump the version in cloudinit/version.py to be 19.4 and update ChangeLog.
LP: #1851428

Release 19.4

---

cloudinit/config/cc_ssh.py

doc: update cc_ssh clarify host and auth keys

---

tools/.lp-to-git-user

lp-to-git-users: adding goneri

---

tools/migrate-lp-user-to-github

And a couple of other minor cleanups.

migrate-lp-user-to-github: ensure Launchpad repo exists

---

tools/.lp-to-git-user

Mapped from andreipoltavchenko

lp-to-git-users: adding pa-yourserveradmin-com

---

tools/.lp-to-git-user

lp-to-git-users: adding karibou

---

doc/rtd/topics/modules.rst

LP: #1852456
To test:
LP:1852456
```
make doc
```

doc: add modules page toc with links

---

tools/.lp-to-git-user

lp-to-git-users: adding ask0n

---

tools/.lp-to-git-user

lp-to-git-users: adding madhuri-rai07

---

tools/.lp-to-git-user

lp-to-git-users: adding andreaf74

---

tools/.lp-to-git-user

lp-to-git-users: adding rjschwei

---

tools/.lp-to-git-user

lp-to-git-users: adding OddBloke

---

README.md

Just add Rootbox & HyperOne to list of supported public cloud providers via RbxCloud ds.

Add Rootbox & HyperOne to list of cloud in README

---

cloudinit/helpers.py

See #175 for details and justification for merging in ```stable-19.4``` only.

Fix PermissionError undefined in helpers.py - fix LP-1831146 

---

cloudinit/config/cc_set_passwords.py

Increasing the bits of security from 52 to 115.
LP: #1860795

cc_set_password: increase random pwlength from 9 to 20

---

cloudinit/config/cc_ssh_authkey_fingerprints.py

Print ssh key fingerprints using sha256 hash
LP: #1860789

upgrade from md5 to sha256

---

cloudinit/config/tests/test_set_passwords.py
cloudinit/net/tests/test_init.py
cloudinit/net/tests/test_network_state.py
cloudinit/sources/tests/test_oracle.py
cloudinit/tests/helpers.py
cloudinit/tests/test_dhclient_hook.py
cloudinit/tests/test_gpg.py
cloudinit/tests/test_version.py
test-requirements.txt
tests/unittests/test_datasource/test_aliyun.py
tests/unittests/test_datasource/test_ec2.py
tests/unittests/test_datasource/test_gce.py
tests/unittests/test_datasource/test_maas.py
tests/unittests/test_distros/test_user_data_normalize.py
tests/unittests/test_handler/test_handler_locale.py
tests/unittests/test_reporting.py
tests/unittests/test_reporting_hyperv.py
tests/unittests/test_sshutil.py

And drop our test dependency on mock.

Replace mock library with unittest.mock

---

ChangeLog
cloudinit/version.py

Bump the version in cloudinit/version.py to 20.1 and
LP: #1863954

Release 20.1

---

doc/rtd/topics/format.rst

Typo: dta → data

---

cloudinit/config/cc_disk_setup.py

Addresses "Runtime Error: dictionary keys changed during iteration".
LP: #1868327

cc_disk_setup: fix RuntimeError

---

cloudinit/config/cc_set_passwords.py
cloudinit/config/tests/test_set_passwords.py
cloudinit/tests/test_util.py
cloudinit/util.py

Avoid chpasswd on all the BSD variants.

set_passwords: avoid chpasswd on BSD

---

tools/.lp-to-git-user

Map lp user kgarloff to github user garloff

Add lp-to-git mapping for kgarloff

---

tools/.lp-to-git-user

lp-to-git-users: adding killermoehre

---

README.md
doc/rtd/topics/availability.rst

Add OpenBSD in the list of supported Operating System.

readme: OpenBSD is now supported

---

cloudinit/sources/DataSourceNoCloud.py
cloudinit/sources/DataSourceOVF.py
doc/rtd/topics/datasources/nocloud.rst

I don't believe this has ever been supported, looking at the git
history, but it certainly isn't at the moment.
LP: #1875470

DataSourceNoCloud/OVF: drop claim to support FTP

---

tools/.github-cla-signers

Add "TheRealFalcon" as contributor

Add "TheRealFalcon" as contributor

---

tools/.lp-to-git-user

Mapped from chcheng
Adding chengcheng-chcheng

lp-to-git-users: adding chengcheng-chcheng

---

tools/.github-cla-signers

Add bipinbachhao as contributor

Add bipinbachhao as contributor

---

doc/rtd/topics/datasources/maas.rst

Fix link to the MAAS documentation

---

tools/.github-cla-signers

Add dermotbradley as contributor.

Add dermotbradley as contributor

---

tools/.github-cla-signers

- Added myself as contributor to the project
- Sorted the file alphabetically

Added BirknerAlex as contributor

---

tools/.lp-to-git-user

lp-to-git-users: adding anhvoms

---

tools/.github-cla-signers

Added "tsanghan" to .github-cla-singers

Add "tsanghan" as contributor

---

tests/unittests/test_util.py

Parametrize devlist tests

---

tools/.github-cla-signers

Hi,
My Ubuntu One username is alexbaranowski (no capital letters ;(().
Launchpad profile https://launchpad.net/~alexbaranowski
Best,
Alex

Add AlexBaranowski as contributor

---

doc/rtd/topics/datasources/ovf.rst

Plus a minor formatting improvement.

doc/rtd/topics/datasources/ovf.rst: fix doc8 errors

---

ChangeLog
cloudinit/version.py

Bump the version in cloudinit/version.py to 20.3 and
LP: #1892878

Release 20.3

---

tools/.github-cla-signers

Add jqueuniet as contributor

---

cloudinit/user_data.py

This was added in d00126c167fc06d913d99cfc184bf3402cb8cf53, but not
removed in ef041fd822a2cf3a4022525e942ce988b1f95180 which removed the
one usage of it from the original commit.

user_data: remove unused constant

---

.github/PULL_REQUEST_TEMPLATE.md

> PULL_REQUEST_TEMPLATE.md: empty checkboxes need a space
- [] look this one isn't right
- [] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
- [] I have updated or added any unit tests accordingly
- [] I have updated or added any documentation accordingly

PULL_REQUEST_TEMPLATE.md: empty checkboxes need a space

---

debian/changelog
debian/control

cc_apt_configure requires it to be installed for some operations.

d/control: add gnupg to Recommends

---

tests/integration_tests/integration_settings.py
tests/integration_tests/platforms.py

Add Azure to integration tests
n/a

Add Azure to integration tests

---

tools/.lp-to-git-user

lp-to-git-users: adding asciiprod

---

doc/rtd/topics/instancedata.rst

> docs: add example cloud-init query commands to debug jinja tmpl
Just a doc change related to a passing question in IRC
- [N/A] I have updated or added any unit tests accordingly

docs: add example cloud-init query commands to debug jinja tmpl

---

.github/PULL_REQUEST_TEMPLATE.md

Remove Ubuntu restriction from PR template
n/a

Remove Ubuntu restriction from PR template

---

.github/PULL_REQUEST_TEMPLATE.md

> PULL_REQUEST_TEMPLATE.md: expand commit message section
>
> Make it a little easier for people to understand what we're looking for
> in a commit message.
N/A.

PULL_REQUEST_TEMPLATE.md: expand commit message section

---

debian/patches/ds-identify-behavior-xenial.patch

> d/patches/ds-identify-behavior-xenial.patch: refresh against master
>
> cf6c36a18de233190996f7c2dde1e04908bad50a caused this distro patch to
> stop applying cleanly. This refreshes the patch, to fix daily builds.
The failure to build can be seen here: https://code.launchpad.net/~cloud-init-dev/+archive/ubuntu/daily/+recipebuild/2673624
I manually replicated the tree the recipe produces (merge `ubuntu/xenial` into `master`, then merge this PR branch into that) and confirmed that `quilt push -a` succeeds.

d/patches/ds-identify-behavior-xenial.patch: refresh against master

---

doc/rtd/topics/faq.rst

> faq.rst: add warning to answer that suggests running `clean`
Someone on IRC followed these steps on a system they shouldn't have.
`tox -e doc` produces:

faq.rst: add warning to answer that suggests running `clean`

---

cloudinit/sources/helpers/azure.py
tests/unittests/test_reporting_hyperv.py

DataSourceAzure: push dmesg log to KVP
Pushing dmesg log to KVP to help troubleshoot VM boot issues

DataSourceAzure: push dmesg log to KVP

---

tests/integration_tests/bugs/test_lp1897099.py
tests/integration_tests/conftest.py
tox.ini

Integration test for fallocate falling back to dd
See canonical#585
LP: #1897099
n/a
pytest -s tests/integration_tests/bugs/test_lp1897099.py

Integration test for fallocate falling back to dd

---

ChangeLog
cloudinit/version.py

Release 20.4
Bump the version in cloudinit/version.py to 20.4 and
LP: #1905440

Release 20.4

---

cloudinit/config/cc_apt_configure.py

cc_apt_configure: add riscv64 as a ports arch

cc_apt_configure: add riscv64 as a ports arch

---

tests/unittests/test_handler/test_handler_ca_certs.py

CA Cert tests will fail on systems that don't have the, installed and
configured.
Signed-off-by: Daniel Watkins <oddbloke@ubuntu.com>
Issue found when running `tox` on my own laptop. 
Uninstall or run `tox` on `cloud-init` source tree on a system that does not have CA Certs installed.

Sandbox CA Cert tests so they don't fail where they're not installed

---

integration-requirements.txt

```
integration-requirements.txt: bump pycloudlib commit
This bump is required to be able to launch groovy and hirsute LXD VMs,
as it includes
https://github.com/canonical/pycloudlib/commit/ffd86ad7fe12f5aaa6e03b568f8958a69f698bf4
```
Launch any test with `PLATFORM="lxd_vm"` and `OS_IMAGE="groovy"` or `"hirsute"`; if it successfully launches an instance, this is fixed.

integration-requirements.txt: bump pycloudlib commit

---

.github/workflows/stale.yml

> stale: disable check for holiday break
>
> We're unlikely to see any activity on many PRs over the next couple of
> weeks, so don't close out inactive PRs for the duration.

stale: disable check for holiday break

---

.travis.yml

No longer allow integration test failures on travis
n/a
n/a

No longer allow integration test failures on travis

---

doc/man/cloud-init.1
tools/.github-cla-signers

```
1.fix a typo in man page cloud-init.1
2.add xiachen-rh as contributor
```

fix a typo in man page cloud-init.1

---

tests/integration_tests/test_upgrade.py

```
test_upgrade: add some missing commas
```

test_upgrade: add some missing commas

---

tools/.github-cla-signers

Adding self to cla signers

---

cloud-tests-requirements.txt

```
cloud-tests: update cryptography requirement
```
I ran a few cloud tests like:
`tox -e citest -- run --os-name focal -t modules/bootcmd`
And ensured the test passed and the correct version, 3.2, of cryptography was pulled in.

cloud-tests: update cryptography requirement

---

tools/.github-cla-signers

Add Rick Harding (mitechie) to the CLA signers.

Add Rick Harding (mitechie) to CLA signers.

---

ChangeLog
cloudinit/ssh_util.py
cloudinit/version.py
tests/unittests/test_sshutil.py

```
Merge upstream/20.4.1 into master
upstream/20.4.1 was used to release the 20.4.1 hotfix. Merging it into
master reconciles that fork in history, and integrates both the 20.4.1
changelog and tag into our main history.
```
This needs to be landed as a _merge commit_, not as a squash. This PR is in draft until we've (temporarily) modified the cloud-init repo's branch protection policy to allow this.
Manually perform this merge locally and confirm that (a) the Changelog entry is included, and (b) `git describe` starts with 20.4.1:
```
$ grep 20.4.1 ChangeLog
20.4.1
$ git describe
20.4.1-79-gfb40b505
```
(The exact `git describe` output will be different, as the git hash of the merge commit will be different: GitHub will create the one, canonical merge commit when we merge this PR.)

Merge upstream/20.4.1 into master

---

doc/examples/part-handler.txt

Remove the vi comment from the part-handler example

---

tests/integration_tests/test_upgrade.py

```
test_upgrade: modify test_upgrade_package to run for more sources
This allows us to use it when validating packages from -proposed (and
PPAs etc.).
```
CI will run the most-modified test, I used this code locally for SRU verification.

test_upgrade: modify test_upgrade_package to run for more sources

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/test_datasource/test_azure.py

Azure: adding support for consuming userdata from IMDS

Azure: adding support for consuming userdata from IMDS

---

tools/.github-cla-signers

Add Vultaire as contributor

---

debian/changelog
debian/po/templates.pot

```
* d/po/templates.pot: refresh with debconf-updatepo
```
`sbuild` succeeds locally, I won't upload until a LXD container integration test run succeeds.

* d/po/templates.pot: refresh with debconf-updatepo

---

tools/.github-cla-signers

Add "esposem" as contributor

---

doc/rtd/topics/datasources/nocloud.rst

```
doc: Update NoCloud docs stating required files
LP: #1931577
```
https://bugs.launchpad.net/cloud-init/+bug/1931577
n/a

doc: Update NoCloud docs stating required files

---

tools/.github-cla-signers

Add myself to the contributor list

---

cloudinit/net/__init__.py

Logging the detected network devices before renaming them.
```
Logging the detected network devices before renaming them.
```

Logging the detected interfaces

---

ChangeLog
cloudinit/version.py

Bump the version in cloudinit/version.py to 21.3 and update ChangeLog.
LP: #1940839

Release 21.3

---

cloudinit/net/networkd.py
tests/unittests/test_net.py
tests/unittests/test_net_activators.py

Add support to accept-ra in networkd renderer

Add support to accept-ra in networkd renderer

---

doc/man/cloud-id.1

fix(date): Let's make copyright this year

---

tools/.github-cla-signers

I've signed the CLA
per https://cloudinit.readthedocs.io/en/latest/topics/hacking.html#submitting-your-first-pull-request

Add me to tools/.github-cla-signers

---

cloudinit/sources/DataSourceOVF.py
tests/unittests/test_datasource/test_ovf.py

```
summary: Fix a typo introduced at PR#947 and add a new test to verify it
```

Fix a typo introduced at PR#947 and add a new test to verify it

---

HACKING.rst

No, I'm not pretending to be manager, but I'm assuming David doesn't need to be bothered with CLA issues.

HACKING.rst: change contact info to James Falcon

---

tools/.github-cla-signers

Add andgein as contributor in the project

Add andgein as contributor

---

tools/.lp-to-git-user

lp-to-git-users: adding vholer

---

integration-requirements.txt

```
integration-requirements: bump the pycloudlib commit
```
Needed to include: https://github.com/canonical/pycloudlib/pull/162
Set the `GOOGLE_CLOUD_PROJECT` env var, run a GCE integration test and check that the specified project is actually being used.

integration-requirements: bump the pycloudlib commit

---

README.md

```
Fix dead link to "contributing" page in README
```

update dead link

---

tools/build-on-netbsd

netbsd: install new dep packages

---

cloudinit/net/openbsd.py

OpenBSD 7.0 comes with a new service called dhcpleased to manage the DHCP
requests.

openbsd: properly restart the network on 7.0

---

cloudinit/sources/DataSourceVMware.py
cloudinit/url_helper.py
setup.py
tests/integration_tests/integration_settings.py

distutils is getting deprecated soon. Let's replace it with alternatives as suggested in:
https://www.python.org/dev/peps/pep-0632/
```
Remove distutils usage
distutils is getting deprecated soon. Let's replace it with alternatives as suggested in:
https://www.python.org/dev/peps/pep-0632/
```

Remove distutils usage

---

cloudinit/config/cc_rsyslog.py

```
cc_rsyslog: fix typo in docstring
```
Hi,
Please let me know if I need to add myself to `tools/.github-cla-signers`. It didn't seem worth it for such a small contribution. I did sign the contributor license agreement.

cc_rsyslog: fix typo in docstring

---

cloudinit/config/cc_phone_home.py

```
Include POST format in cc_phone_home docs
LP: #1959149
```

Include POST format in cc_phone_home docs (SC-764)

---

.github/workflows/stale.yml

@mitechie , would you mind reviewing this one? :wink:

Remove mitechie from stale PR github action (SC-765)

---

cloudinit/config/cc_ssh.py
tools/.github-cla-signers

ref https://github.com/canonical/cloud-init/pull/1202

update log messages to show ssh private key gens pub and simplify code 

---

cloudinit/sources/helpers/vultr.py

Fix missing continue
```
A continue was missing to allow interface seeking.
```
Deploy an image with a private network on Vultr

Fix missing continue

---

integration-requirements.txt

```
Bump pycloudlib to use fixed azure dependency
```

bump pycloudlib version

---

tools/.github-cla-signers

Add eslerm as contributor to project.

add "eslerm" as contributor

---

ChangeLog
cloudinit/version.py

```
Bump the version in cloudinit/version.py to 22.1 and
LP: #1960939
```

Release 22.1

---

tests/integration_tests/modules/test_apt.py

```
Fix apt test on azure
```
Tested via pycloudlib on azure and locally.

fix apt source match

---

tools/.lp-to-git-user

lp-to-git-users: adding sparkiegeek

---

Makefile
cloudinit/distros/__init__.py
cloudinit/sources/DataSourceAzure.py
cloudinit/url_helper.py
cloudinit/util.py
debian/changelog
doc/man/cloud-init.1
tests/integration_tests/clouds.py
tests/integration_tests/modules/test_apt.py
tests/integration_tests/modules/test_combined.py
tests/integration_tests/modules/test_users_groups.py
tests/unittests/sources/test_azure.py
tests/unittests/test_util.py
tools/.github-cla-signers

New upstream snapshot: Jammy

---

Makefile
cloudinit/distros/__init__.py
cloudinit/sources/DataSourceAzure.py
cloudinit/url_helper.py
cloudinit/util.py
debian/changelog
debian/patches/retain-apt-partner-pocket.patch
doc/man/cloud-init.1
tests/integration_tests/clouds.py
tests/integration_tests/modules/test_apt.py
tests/integration_tests/modules/test_combined.py
tests/integration_tests/modules/test_users_groups.py
tests/unittests/sources/test_azure.py
tests/unittests/test_util.py
tools/.github-cla-signers

New Upstream Snapshot: Impish

---

Makefile
cloudinit/distros/__init__.py
cloudinit/sources/DataSourceAzure.py
cloudinit/url_helper.py
cloudinit/util.py
debian/changelog
doc/man/cloud-init.1
tests/integration_tests/clouds.py
tests/integration_tests/modules/test_apt.py
tests/integration_tests/modules/test_combined.py
tests/integration_tests/modules/test_users_groups.py
tests/unittests/sources/test_azure.py
tests/unittests/test_util.py
tools/.github-cla-signers

New Upstream Snapshot: Focal

---

Makefile
cloudinit/distros/__init__.py
cloudinit/sources/DataSourceAzure.py
cloudinit/url_helper.py
cloudinit/util.py
debian/changelog
debian/patches/retain-apt-partner-pocket.patch
doc/man/cloud-init.1
tests/integration_tests/clouds.py
tests/integration_tests/modules/test_apt.py
tests/integration_tests/modules/test_combined.py
tests/integration_tests/modules/test_users_groups.py
tests/unittests/sources/test_azure.py
tests/unittests/test_util.py
tools/.github-cla-signers

New Upstream Snapshot: Bionic

---

doc/examples/part-handler-v2.txt
doc/examples/part-handler.txt
doc/status.txt

python2 is dead

---

tox.ini

tox: set verbose flags for integration tests

---

templates/hosts.arch.tmpl

```
Add Arch Linux hosts template
```
Reported [here](https://bugs.archlinux.org/task/74359?project=5&string=cloud-init)
TODO

Add arch template

---

debian/changelog
debian/patches/cpick-30ccd51a-ds-identify-also-discover-LXD-by-presence-from-DMI
debian/patches/cpick-be9389c6-Work-around-bug-in-LXD-VM-detection-1325
debian/patches/cpick-e3307e4d-ds-identify-detect-LXD-for-VMs-launched-from-host-with
debian/patches/series

Ubuntu/devel 22.1 hotfix

---

doc/rtd/index.rst
doc/rtd/topics/tutorial.rst

```
docs: Add first tutorial
Added a tutorial using a very simple cloud-config on LXD.
Also tightened up some wording on the landing page
and added tutorial link to landing page.
```
My goal here was to make a tutorial to launch a cloud-config on LXD for somebody that has no familiarity with cloud-init. Even though LXD isn't as well known as other clouds/containers/VMs, I went with LXD because it is the easiest to setup and it's what upstream committers use to test changes.

docs: Add first tutorial (SC-900)

---

doc/rtd/topics/faq.rst
tools/.github-cla-signers

```
Fix doc typo
- Fix typo in documentation in the `FAQ` page.
- Add aciba90 as contributor.
```

Fix doc typo

---

cloudinit/config/cc_set_hostname.py
tools/.github-cla-signers

Small typo (perserve vs preserve)

---

debian/changelog
debian/control

```
d/control: add python3-responses for unittests
```
ref: https://github.com/canonical/cloud-init/compare/ubuntu/bionic...holmanb:ubuntu/bionic?expand=1
```
git checkout upstream/ubuntu/bionic
build-package
sbuild --resolve-alternatives --dist=bionic --arch=amd64 ../out/cloud-init*dsc
```

Bionic: d/control: add python3-responses for unittests

---

debian/changelog
debian/control

```
d/control: add python3-responses for unittests
```
ref: https://github.com/canonical/cloud-init/compare/ubuntu/bionic...holmanb:ubuntu/bionic?expand=1
```
git checkout upstream/ubuntu/focal
build-package
sbuild --resolve-alternatives --dist=focal --arch=amd64 ../out/cloud-init*dsc
```

Focal: d/control: add python3-responses for unittests

---

doc/rtd/topics/integration_tests.rst

```
Fix typo in integration_test.rst
```

Fix typo in integration_test.rst

---

debian/changelog
debian/control

Suggests: openssh-server added in https://github.com/canonical/cloud-init/pull/1422
(do not squash)

Ubuntu/bionic: add Suggests: openssh-server

---

debian/changelog
debian/control

Suggests: openssh-server added in https://github.com/canonical/cloud-init/pull/1422
(do not squash)

Ubuntu/focal: add Suggests: openssh-server

---

debian/changelog
debian/control

Suggests: openssh-server added in https://github.com/canonical/cloud-init/pull/1422
(do not squash)

Ubuntu/devel: add Suggests: openssh-server

---

debian/changelog
debian/control

Suggests: openssh-server added in https://github.com/canonical/cloud-init/pull/1422
(do not squash)

Ubuntu/jammy: add Suggests: openssh-server

---

ChangeLog
cloudinit/version.py

Bump the version in cloudinit/version.py to 22.2 and
LP: #1960939
```
```

Release 22.2

---

integration-requirements.txt

tests: bump pycloudlib

---

tools/.github-cla-signers

Add "rongz609" as contributor

---

tests/unittests/config/test_schema.py

```
test_schema: no relative $ref URLs, replace $ref with local path
```
Daily builds started breaking on older python3-jsonschema because of invalid unittest replacement of non-local $refs
https://launchpadlibrarian.net/603670335/buildlog_ubuntu-kinetic-amd64.cloud-init_22.2-3259-ga918e9e2-0ubuntu1+1968~trunk~ubuntu22.10.1_BUILDING.txt.gz

test_schema: no relative $ref URLs, replace $ref with local path

---

tools/.github-cla-signers

Add linitio as contributor in the project

---

doc/rtd/topics/datasources/ec2.rst
doc/rtd/topics/datasources/gce.rst
doc/rtd/topics/datasources/vmware.rst
doc/rtd/topics/module_creation.rst
doc/rtd/topics/network-config.rst
tox.ini

The linkchecker currently works as-is, but running it shows broken links I'd like to fix as well in this PR.
```
tox: add link checker environment, fix some links
```

tox: add link checker environment, fix some links (SC-1087)

---

cloudinit/net/__init__.py
cloudinit/sources/DataSourceRbxCloud.py
cloudinit/sources/DataSourceVMware.py
cloudinit/util.py

```
datasources: replace networking functions with stdlib and cloudinit.net code
util: remove unused function
sources/vmw: reuse cloudinit.net code
sources/rbx: replace homegrown IP address code with stdlib
```
These changes should be functionally equivalent with better code re-use.

Reuse library code, remove dead code

---

cloudinit/sources/DataSourceEc2.py
tests/integration_tests/datasources/test_ec2_ipv6.py

```
Remove extra space from ec2 dual stack crawl message
Also update integration test to accommodate possible extra text
```

testing: update ec2 dual_stack test for new text (SC-1113)

---

tests/unittests/sources/test_azure.py

- Rename construct_valid_ovf_env() -> construct_ovf_env()
- Explicitly pass all parameters rather than taking dictionaries.
- Add defaults for username and hostname, removing usage from callers
that are unneeded/unverified.
- Add support for DisableSshPasswordAuthentication, though currently
lacks test coverage.
- Use existing dictionary format for public keys.

tests/azure: refactor ovf creation

---

tools/.github-cla-signers

Just signed the cla, so adding myself.
```
summary: Add dcaro to the cla signers
```

Add dcaro to the cla signers

---

tests/unittests/sources/test_azure.py

tests/azure: add test coverage for DisableSshPasswordAuthentication

---

.travis.yml

```
Pin setuptools for Travis
Pinned to the latest version that works across versions.
See https://github.com/pypa/setuptools/issues/3118
```

Pin setuptools for Travis (SC-1136)

---

CONTRIBUTING.rst

```
doc: clarify cla instructions
```
https://github.com/canonical/cloud-init/pull/1545
https://github.com/canonical/cloud-init/pull/1527#issuecomment-1158901533

doc: it isn't obvious which id to use on cla, fix it

---

cloudinit/config/cc_ubuntu_advantage.py
cloudinit/config/schemas/schema-cloud-config-v1.json
tests/unittests/config/test_cc_ubuntu_advantage.py
tools/.github-cla-signers
tox.ini

Ubuntu Advantage config: http_proxy, https_proxy
```
Implemented the usage of
- http_proxy
- https_proxy
parameters for Ubuntu Advantage. Parameter will be set before an attachment takes place.
```
I did my best in writing unit tests and would be delighted if you add more as I am not very familiar with that.
Following scenarios are tested:
- UA config with weird params
- UA config with an invalid url
- UA config with non string values for keys
- [ x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
- [ x] I have updated or added any unit tests accordingly
- [ x] I have updated or added any documentation accordingly

Ubuntu Advantage config: http_proxy, https_proxy

---

tests/unittests/config/test_cc_ubuntu_advantage.py

```
testing: port cc_ubuntu_advantage test to pytest
```
No functional modifications
This will ease [SC-1145](https://warthogs.atlassian.net/browse/SC-1145).

testing: port cc_ubuntu_advantage test to pytest

---

debian/changelog
debian/cloud-init.lintian-overrides
debian/cloud-init.postinst
debian/control
debian/source/lintian-overrides

do not squash
https://warthogs.atlassian.net/browse/SC-1154

ubuntu/devel: fix lintian warnings

---

tests/unittests/config/test_apt_source_v1.py
tests/unittests/config/test_apt_source_v3.py
tests/unittests/test_util.py

No functional changes
```
testing: remove appereances of FakeCloud
```

testing: remove appereances of FakeCloud

---

.travis.yml
debian/changelog
debian/cloud-init.lintian-overrides
debian/cloud-init.postinst
debian/source/lintian-overrides

do not squash
[SC-1154](https://warthogs.atlassian.net/browse/SC-1154)

ubuntu/jammy: fix lintian

---

.travis.yml
debian/changelog
debian/cloud-init.postinst
debian/source/lintian-overrides

do not squash
[SC-1154](https://warthogs.atlassian.net/browse/SC-1154)

Ubuntu/impish: fix lintian

---

.travis.yml
debian/changelog
debian/cloud-init.postinst
debian/source/lintian-overrides

do not squash
[SC-1154](https://warthogs.atlassian.net/browse/SC-1154)

Ubuntu/bionic: fix lintian

---

cloudinit/sources/helpers/azure.py

Somehow we managed to get passed CI and merged a black invalid
format in commit 6f369c09b1
Fix this in main so other new PRs are not affected
```
black: fix missed formatting issue which landed in main
Somehow we managed to get passed CI and merged a black invalid
format in commit 6f369c09b1
Fix this in main so other new PRs are not affected
```

black: fix missed formatting issue which landed in main

---

tests/integration_tests/cmd/test_status.py
tests/integration_tests/datasources/test_lxd_discovery.py
tests/integration_tests/modules/test_combined.py
tests/unittests/sources/test_ec2.py

SC-1195
```
testing: drop impish support
```

testing: drop impish support

---

tools/.github-cla-signers

Add "netcho" as contributor

---

cloudinit/config/cc_lxd.py
cloudinit/config/schemas/schema-cloud-config-v1.json
doc/examples/cloud-config-lxd.txt
tests/integration_tests/modules/test_lxd_bridge.py
tests/unittests/config/test_cc_lxd.py
tests/unittests/util.py

```
cc_lxd: Add btrfs and lvm lxd storage options
Also add mocked_distro flag to get_cloud() test function
```

Add btrfs and lvm support to lxd storage options (SC-1026)

---

cloudinit/config/schemas/schema-cloud-config-v1.json

```
docs: clarify user password purposes
Also undeprecate "user" key as we currently have no userdata replacement
```

docs: clarify user password purposes

---

cloudinit/config/cc_grub_dpkg.py
cloudinit/config/schemas/schema-cloud-config-v1.json
tests/unittests/config/test_cc_grub_dpkg.py

```
schema: activate grub-dpkg deprecations
```
SC-1173

schema: activate grub-dpkg deprecations

---

cloudinit/config/cc_salt_minion.py
cloudinit/config/cc_scripts_per_boot.py
cloudinit/config/cc_scripts_per_instance.py
cloudinit/config/cc_scripts_per_once.py
cloudinit/config/cc_scripts_user.py
cloudinit/config/cc_scripts_vendor.py
cloudinit/config/cc_seed_random.py
cloudinit/config/cc_set_hostname.py
cloudinit/config/cc_set_passwords.py
cloudinit/config/cc_spacewalk.py
cloudinit/config/cc_ssh.py
cloudinit/config/cc_ssh_authkey_fingerprints.py
cloudinit/config/cc_ssh_import_id.py

```
config: Def activate_by_schema_keys for s mods
```
SC-1133
Merge #1609

config: Def activate_by_schema_keys for s mods

---

cloudinit/config/cc_package_update_upgrade_install.py
cloudinit/config/cc_phone_home.py
cloudinit/config/cc_power_state_change.py
cloudinit/config/cc_puppet.py
cloudinit/config/cc_refresh_rmc_and_interface.py
cloudinit/config/cc_reset_rmc.py
cloudinit/config/cc_resizefs.py
cloudinit/config/cc_resolv_conf.py
cloudinit/config/cc_rh_subscription.py
cloudinit/config/cc_rightscale_userdata.py
cloudinit/config/cc_rsyslog.py
cloudinit/config/cc_runcmd.py

```
config: Def activate_by_schema_keys for p-r mods
```
SC-1133
SC-1205
Merge #1609

config: Def activate_by_schema_keys for p-r mods

---

cloudinit/config/modules.py
cloudinit/importer.py

```
Modernise importer.py and type ModuleDetails
```
Minor refactoring extracted from https://github.com/canonical/cloud-init/pull/1597

Modernise importer.py and type ModuleDetails

---

cloudinit/config/cc_set_passwords.py
tests/unittests/config/test_cc_set_passwords.py

```
testing: migrate test_cc_set_passwords to pytest
```

testing: migrate test_cc_set_passwords to pytest

---

tests/unittests/test_ssh_util.py

```
testing: migrate test_sshutil to pytest
```

testing: migrate test_sshutil to pytest

---

cloudinit/config/schemas/schema-cloud-config-v1.json
tests/unittests/config/test_cc_scripts_vendor.py

```
schema: Enable deprecations in cc_scripts_vendor
```
SC-1173

schema: Enable deprecations in cc_scripts_vendor

---

cloudinit/config/cc_users_groups.py
cloudinit/config/schema.py
cloudinit/config/schemas/schema-cloud-config-v1.json
cloudinit/distros/__init__.py
tests/integration_tests/modules/test_users_groups.py
tests/unittests/config/test_cc_users_groups.py
tests/unittests/config/test_schema.py
tests/unittests/distros/test_create_users.py

```
schema: Enable deprecations in cc_users_groups
Extend doc of schemas with multiple sub-schemas including.
```
SC-1173
SC-1175

schema: Enable deprecations in cc_users_groups

---

cloudinit/config/schemas/schema-cloud-config-v1.json
tests/unittests/config/test_cc_growpart.py

```
schema: Enable deprecations in cc_growpart
```
SC-1173

schema: Enable deprecations in cc_growpart

---

cloudinit/util.py

```
util: Include Idle process state in ppid parser
```
Cleanup related to https://github.com/canonical/cloud-init/commit/668a68fe577368555ea7f71577fc352494a98c25

Support Idle process state in get_proc_ppid()

---

cloudinit/config/cc_update_etc_hosts.py
cloudinit/config/schemas/schema-cloud-config-v1.json
tests/unittests/config/test_cc_update_etc_hosts.py

```
schema: Enable deprecations in cc_update_etc_hosts
```
SC-1173

schema: Enable deprecations in cc_update_etc_hosts

---

tests/integration_tests/cmd/test_schema.py

```
testing: fix references to `DEPRECATED.`
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-lxd_container/78/testReport/junit/tests.integration_tests.cmd.test_schema/TestSchemaDeprecations/test_clean_log/

testing: fix references to `DEPRECATED.`

---

tests/integration_tests/modules/test_lxd.py

```
test: Drop forced package install hack in lxd integration test
```
The original purpose of this package uninstall was to force the module to install the packages whether or not they are in the base image. This ended up failing in an lvm2 postinst script (a packaging issue that has some open launchpad tickets and stackoverflow Q/A as well). We worked around by adding the umask command. Unsurprisingly this isn't robust enough to pass everywhere.
Integration [test failure](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-gce/65/console) shows:
```
09:30:06   "Command: ['eatmydata', 'apt-get', "
09:30:06   "'--option=Dpkg::Options::=--force-confold', "
09:30:06   "'--option=Dpkg::options::=--force-unsafe-io', '--assume-yes', '--quiet', "
09:30:06 …
```

drop hack that forces package re-install

---

integration-requirements.txt
tox.ini

```
test: Collect integration test time by default
```

Measure Integration Tests

---

tests/integration_tests/modules/test_wireguard.py

```
Wireguard tests currently pass locally on LXD, however these tests fail
on any platform that requires ssh to connect to the instance. This
occurs since the process of setting up wireguard involves adding
interfaces, routes, and firewall rules, which results in an instance
that cannot be connected with as expected by pycloudlib.
This change "fixes" the test by stopping the wireguard service in
runcmd, which un-does the network changes that make the instance
inaccessible.
```

test: fix wireguard integration tests

---

integration-requirements.txt

```
pycloudlib: bump to quiet azure HTTP info logs
```

pycloudlib: bump to quiet azure HTTP info logs

---

cloudinit/config/schemas/versions.schema.cloud-config.json

```
schema: drop release number from version file
```

add new release versions to schema version file

---

ChangeLog
cloudinit/version.py

Bump the version in cloudinit/version.py to 22.3 and
LP: #1986703
```
```

Release 22.3

---

tests/unittests/config/test_cc_yum_add_repo.py

```
test: avoid centos leaked check of /etc/yum.repos.d/epel-testing.repo
```
```bash
./tools/run-container --package --source-package --unittest rockylinux/8 -k
```

test: avoid centos leaked check of /etc/yum.repos.d/epel-testing.repo

---

cloudinit/config/cc_wireguard.py
tox.ini

```
Fix check_format_tip
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-style-tip/132
tox -e check_format_tip

Fix check_format_tip

---

cloudinit/net/ephemeral.py
tests/unittests/net/test_ephemeral.py

```
net: Fix EphemeraIPNetwork
Execute ipv4 and ipv6 setup in the correct order.
```

net: Fix EphemeraIPNetwork

---

cloudinit/config/cc_ubuntu_autoinstall.py
doc/rtd/topics/modules.rst

```
docs: publish cc_ubuntu_autoinstall docs to rtd
```
```
tox -e doc
xdg-open doc/rtd_html/topics/modules.html
```

docs: publish cc_ubuntu_autoinstall docs to rtd

---

cloudinit/config/cc_chef.py
tests/unittests/config/test_cc_chef.py

```
Fix cc_chef typing issue
The function 'subp_blob_in_tempfile' had an if branch that is currently
unused, but attempts to invalidly append a list to a tuple.
```

Fix cc_chef typing issue (SC-1244)

---

cloudinit/config/cc_ansible.py
tests/unittests/config/test_cc_ansible.py

```
config: enable bootstrapping pip in ansible
```

config: enable bootstrapping pip in ansible

---

tests/unittests/analyze/test_boot.py
tests/unittests/analyze/test_dump.py

```
testing: Port unittests/analyze to pytest
```

testing: Port unittests/analyze to pytest

---

doc/rtd/topics/module_creation.rst

```
Update docs according to commit ad8f406a
```
https://github.com/canonical/cloud-init/pull/1700

Update docs according to commit ad8f406a

---

integration-requirements.txt

```
test: bump pycloudlib
to 25cca01b24d111e00e91a86eb1021b88592e069e
```
https://github.com/canonical/pycloudlib/pull/213

test: bump pycloudlib

---

tests/integration_tests/modules/test_combined.py

```
testing: LXD datasource now supported on Focal
```

testing: LXD datasource now supported on Focal

---

doc/examples/include.txt

```
Update #include example with real URLs
LP: #1307667
```
Launch and LXD container with the include example and verify files written in both cloud-configs are written to their respective locations.

Update #include example with real URLs

---

integration-requirements.txt

```
pycloudlib: bump commit for gce cpu architecture support
commit d76228e24
```
Avoid jenkins failures like https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-gce/102/ due to GCE requiring architecture filters. x86_64 vs arm64 etc.
```

pycloudlib: bump commit for gce cpu architecture support

---

cloudinit/analyze/__main__.py
cloudinit/cmd/devel/make_mime.py
cloudinit/cmd/devel/parser.py
cloudinit/cmd/devel/render.py
cloudinit/distros/__init__.py
cloudinit/distros/bsd.py
cloudinit/distros/freebsd.py
cloudinit/net/bsd.py
cloudinit/net/cmdline.py
cloudinit/net/eni.py
cloudinit/net/netplan.py
cloudinit/net/network_manager.py
cloudinit/net/networkd.py
cloudinit/net/renderers.py
cloudinit/net/sysconfig.py
cloudinit/reporting/events.py
cloudinit/sources/helpers/vmware/imc/config.py
cloudinit/sources/helpers/vmware/imc/config_file.py
cloudinit/sources/helpers/vmware/imc/config_namespace.py
cloudinit/sources/helpers/vmware/imc/guestcust_util.py
cloudinit/sources/helpers/vmware/imc/nic.py
tests/unittests/distros/test_arch.py
tests/unittests/distros/test_gentoo.py
tests/unittests/distros/test_opensuse.py
tests/unittests/distros/test_photon.py
tests/unittests/distros/test_sles.py
tests/unittests/sources/test_azure_helper.py

```
Style: use relative imports
prefer absolute imports over relative imports.
```
@TheRealFalcon's review on #1758 
no function changes, tests still pass.

Style: use relative imports

---

ChangeLog
cloudinit/sources/DataSourceOracle.py
cloudinit/version.py
tests/unittests/sources/test_oracle.py

Release 22.3.4

---

ChangeLog
cloudinit/sources/DataSourceOracle.py
cloudinit/version.py
debian/changelog
tests/unittests/sources/test_oracle.py

Ubuntu/bionic 22.3 hotfix

---

ChangeLog
cloudinit/sources/DataSourceOracle.py
cloudinit/version.py
debian/changelog
tests/unittests/sources/test_oracle.py

Steps:
```
git checkout ubuntu/22.3.3-0ubuntu1_20.04.1 -B ubuntu/focal-22.3-hotfix
git push -u upstream ubuntu/focal-22.3-hotfix
new-upstream-snapshot 22.3.4
build-package
sbuild --resolve-alternatives --dist=jammy --arch=amd64 ../out/cloud-init_22.3.4-0ubuntu1.dsc
```

Ubuntu/focal 22.3 hotfix release

---

packages/README.md

Add pointers to downstream packaging resources.
```
doc: clarify packages as dev only
Add pointers to downstream packaging resources.
```
[SC-1227](https://warthogs.atlassian.net/browse/SC-1227)

doc: clarify packages as dev only

---

doc/rtd/topics/faq.rst
tools/.github-cla-signers

Corrected typo in the docs FAQ section
```
Corrected typo ("cloud-init" instead of "clous-init") in the docs FAQ section. Additionally added "mxwebdev" as contributor to the .github-cla-signers file. 
```
Not relevant for docs update.

Corrected typo in the docs FAQ section

---

cloudinit/config/schemas/schema-cloud-config-v1.json
config/cloud.cfg.tmpl
doc/examples/cloud-config.txt
doc/rtd/index.rst
doc/rtd/topics/base_config_reference.rst
doc/rtd/topics/datasources/exoscale.rst
doc/rtd/topics/datasources/smartos.rst
doc/rtd/topics/faq.rst
doc/rtd/topics/instancedata.rst
doc/rtd/topics/logging.rst
doc/rtd/topics/module_creation.rst
doc/rtd/topics/network-config-format-v1.rst
doc/rtd/topics/network-config-format-v2.rst
doc/rtd/topics/network-config.rst
tests/unittests/config/test_schema.py

```
Create reference documentation for base config
Also add schema entries for the base config modules lists that can be
overridden with user data.
```

Create reference documentation for base config (SC-1171)

---

tests/unittests/config/test_cc_ansible.py

```
Temporarily remove broken test
Daily builds are failing on a test[1] that is currently being refactored
in another PR[2], so just remove it for now to fix daily builds.
[1]: https://launchpadlibrarian.net/627753049/buildlog_ubuntu-jammy-amd64.cloud-init_22.3-3470-gcd2cca35-0ubuntu1+1988~trunk~ubuntu22.04.1_BUILDING.txt.gz
[2]: https://github.com/canonical/cloud-init/pull/1778/files#diff-35a90421249cbd95c2eb06a6cdb38e9a1c062c9720cdb01efde5e833c87e7c74
```

Temporarily remove broken test

---

cloudinit/config/cc_final_message.py

```
Add clarity to cc_final_message docs
```

Add clarity to cc_final_message docs

---

cloudinit/cmd/devel/hotplug_hook.py
cloudinit/sources/DataSourceLXD.py
cloudinit/sources/__init__.py
doc/rtd/topics/datasources/lxd.rst
tests/integration_tests/datasources/test_lxd_discovery.py
tests/integration_tests/datasources/test_lxd_hotplug.py
tests/unittests/cmd/devel/test_hotplug_hook.py
tests/unittests/sources/test_lxd.py

```
Enable hotplug for LXD datasource
When a NIC appears, check for a cloud-init.network-config and apply it.
```

Enable hotplug for LXD datasource (SC-1107)

---

tools/.github-cla-signers

Adding myself as CLA signer

---

.travis.yml

```
test: add 3.12-dev to Travis CI
```

test: add 3.12-dev to Travis CI

---

tools/.github-cla-signers

```
summary: adding itjamie to cla
Adding myself per https://cloudinit.readthedocs.io/en/latest/topics/contributing.html#submitting-your-first-pull-request
```

adding myself for cla

---

tests/integration_tests/modules/test_lxd.py

```
testing: Fix preseed test
The wrong method of determining the current Ubuntu release was used,
causing tests to fail.
```

testing: Fix preseed test

---

tests/integration_tests/modules/test_ansible.py

Test ansible missed underscore

---

tests/integration_tests/modules/test_ubuntu_advantage.py

```
tests: activate Ubuntu Pro tests (only on Jenkins)
```
https://warthogs.atlassian.net/browse/SC-1275

tests: activate Ubuntu Pro tests (only on Jenkins)

---

ChangeLog

```
changelog: capture 22.3.1-4 releases
Manually capture in changelog published releases and security fixes.
```

Changelog capture 22.3.1-4

---

debian/changelog

```
changelog: update fixed bugs in d/changelog
```
obtain the list of fixed bugs since last public release with: 
```
git log ubuntu/22.3-13-g70ce6442-0ubuntu1_22.10.1..HEAD | log2dch | grep LP
- Fix last reported event possibly not being sent (#1796) (LP: #1993836)
- cc_ntp: add support for BSDs (#1759) [Mina Galić] (LP: #1990041)
[Mina Galić] (LP: #1991024)
[Mina Galić] (LP: 1991567)
[Mina Galić] (LP: #1990070)
- Fix Oracle DS primary interface when using IMDS (#1757) (LP: #1989686)
- commit ffcb29bc8315d1e1d6244eeb1cbd8095958f7bad (LP: #1307667)
- Fix Oracle DS not setting subnet when using IMDS (#1735) (LP: #1989686)
(LP: #1883122)
- Allow jinja templating in /etc/cloud (SC-1170) (#1722) (LP: #1913461)
[Alberto Contreras] (LP: #1962343)
```

changelog: update fixed bugs in d/changelog

---

doc/rtd/index.rst

```
doc: rtd home page links added
- Moved all URLs to the end of the file (under "links") for ease of reference and updating
- Standardised text slightly between this version and GitHub README.md
- Added links that are in GitHub README.md but missing here
- Standardised links so the same are shown in both files```

doc: home page links added

---

tools/.github-cla-signers

Add "nkukard" as contributor

---

.travis.yml

```
travis: promote 3.11-dev to 3.11
```

travis: promote 3.11-dev to 3.11

---

ChangeLog
cloudinit/version.py

```
Release 22.4.2
Bump the version in cloudinit/version.py to 22.4.2 and update ChangeLog.
```
Sync ChangeLog from upstream/22.4.x branch into upstream/main

Release 22.4.2

---

ChangeLog
cloudinit/cmd/status.py
cloudinit/net/__init__.py
cloudinit/version.py
debian/changelog
tests/unittests/cmd/test_cloud_id.py
tests/unittests/cmd/test_status.py
tests/unittests/test_net.py

Bug template has not been updated yet, so do not request review from SRU vanguard yet.

Ubuntu/kinetic 22.4.x

---

doc/rtd/topics/network-config-format-v2.rst

```
Add back gateway4/6 deprecation to docs
It was accidentally removed in f1a9e44e.
```

Add back gateway4/6 deprecation to docs

---

integration-requirements.txt

Bump commit to c9db5bfc
```
pycloudlib: bump commit dropping azure api smoke test
Avoid breakage on newer Azure SDK versions
Bump commit to c9db5bfc
```

pycloudlib: bump commit dropping azure api smoke test

---

cloudinit/distros/__init__.py
cloudinit/distros/openEuler.py

fix https://bugs.launchpad.net/cloud-init/+bug/1999042

Fix the distro.osfamily output problem in the openEuler system.

---

doc-requirements.txt
doc/rtd/conf.py
doc/rtd/topics/analyze.rst
doc/rtd/topics/bugs.rst
doc/rtd/topics/cli.rst
doc/rtd/topics/configuration.rst
doc/rtd/topics/datasources/aliyun.rst
doc/rtd/topics/datasources/altcloud.rst
doc/rtd/topics/datasources/azure.rst
doc/rtd/topics/datasources/cloudstack.rst
doc/rtd/topics/datasources/ec2.rst
doc/rtd/topics/datasources/exoscale.rst
doc/rtd/topics/datasources/gce.rst
doc/rtd/topics/datasources/lxd.rst
doc/rtd/topics/datasources/nocloud.rst
doc/rtd/topics/datasources/openstack.rst
doc/rtd/topics/datasources/oracle.rst
doc/rtd/topics/datasources/smartos.rst
doc/rtd/topics/debugging.rst
doc/rtd/topics/faq.rst
doc/rtd/topics/format.rst
doc/rtd/topics/network-config-format-v2.rst
doc/rtd/topics/network-config.rst
doc/rtd/topics/tutorials/lxd.rst

```
Docs: Adding "copy-code" functionality
- Uses the sphinx-copybutton extension
- I have reviewed existing code blocks to separate out
input and output lines for user convenience (so they 
don't end up copying output as well). Didn't work in 
every case.
```

Docs copy button

---

tests/unittests/test_atomic_helper.py
tests/unittests/test_util.py

As shown in the title, I added a test case.

add some test case

---

cloudinit/config/cc_write_files.py

```
doc: improve cc_write_files doc
```

doc: improve cc_write_files doc

---

tools/read-version

```
tools: read-version drop extra call to git describe --long
```
This duplicate call should have been redacted in the previous commit 6bdd88a7f1d69dc4aac9fa51d663c4b11e3b5217

tools: read-version drop extra call to git describe --long

---

integration-requirements.txt

Bump to fe7facd3
```
pycloudlib: add lunar support for integration tests
Bump to fe7facd3
```

pycloudlib: add lunar support for integration tests

---

debian/changelog
debian/patches/expire-on-hashed-users.patch

DO NOT SQUASH MERGE.
If this PR gets approved, I'll do the other series without a PR unless there's an objection.

Ubuntu/jammy: Refresh d/p/expire-on-hashed-users.patch

---

cloudinit/sources/DataSourceAzure.py

- Initialize md and cfg to the fallback used when no OVF is found and IMDS is required.
- Rename metadata_source -> ovf_source and drop usage of "IMDS" as a valid value.
- Set `self.seed` to "IMDS" when ovf_source is unset.
- Remove late check for metadata source.  This is already done by the earlier check where we'll fail with "No OVF or IMDS available".
- Move "Found provisioning metadata" diagnostic up to where we read OVF.  Suggesting it was "IMDS" prior to querying IMDS is misleading.
- Add warning when falling back to IMDS-only provisioning.

sources/azure: minor refactor for metadata source detection logic

---

.github/PULL_REQUEST_TEMPLATE.md

```
docs: update the link to the readthedocs
Changing the link url to the correct url.
```

docs: update the link to readthedocs

---

packages/bddeb
packages/pkg-deps.json

```
build: support newer releases
make the package build possible on newer releases after focal.
```
Start a jammy lxd container and run the make command.
```
make ci-deps-ubuntu
```

build: support newer releases

---

pyproject.toml

remove httpretty

---

cloudinit/config/cc_disk_setup.py

```
cc_disk_setup: code cleanup
```
Not best practice; lets not do this.

code cleanup

---

doc/rtd/conf.py
doc/rtd/googleaf254801a5285c31.html

```
Added google verification file to ensure that the 
Google bots can find and index the site. Should
speed up the listing of our docs in Google's 
search results. 
```

docs: add google search verification

---

packages/README.md

```
docs: update downstream package list
```

add links to downstream packages

---

README.md
packages/README.md

```
readme: add reference to packages dir
```
[LP: #2006065](https://bugs.launchpad.net/cloud-init/+bug/2006065)

readme: add reference to packages dir

---

tools/.github-cla-signers

Add "ederst" as contributor

---

doc/rtd/reference/faq.rst

```
doc: Reword user data debug section
```
clarify the value and purpose of the two tools, add mention of debug logs

reword user data debug section

---

tests/integration_tests/cmd/test_schema.py

```
test: Fix deprecation message integration test
```
```
$ tox -e integration-tests -- tests/integration_tests/cmd/test_schema.py
...
====================================== 2 passed, 4 warnings in 77.03s (0:01:17) ======================================
______________________________________________________ summary _______________________________________________________
integration-tests: commands succeeded
congratulations :)
```

fix deprecation integration tests

---

integration-requirements.txt

```
test: switch pycloudlib source to pypi
```
This PR tests this change with CI.

test: switch pycloudlib source to pypi

---

ChangeLog
cloudinit/version.py

Release 23.1

---

cloudinit/sources/helpers/vmware/imc/guestcust_util.py

```
summary: sources/vmware/imc: fix-missing-catch-few-negtive-scenarios
1. When metadata is invalid, should catch exception and report imc failure event.
2. When pre/post customization script is invalid, should catch exception and report imc failure event.
```
- [] I have updated or added any unit tests accordingly

sources/vmware/imc: fix-missing-catch-few-negtive-scenarios

---

tests/integration_tests/cmd/test_schema.py

```
tests: fix test_schema
```
https://github.com/canonical/cloud-init/pull/2026
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-lxd_container/197/testReport/junit/tests.integration_tests.cmd.test_schema/TestSchemaDeprecations/test_clean_log/
```
tox -e integration-tests -- tests/integration_tests/cmd/test_schema.py
```

tests: fix test_schema

---

cloudinit/config/cc_ubuntu_advantage.py
tests/unittests/config/test_cc_ubuntu_advantage.py

```
cc_ubuntu_advantage: improve UA logs discovery
- Use log_time context manager to wrap log UA-API calls
- Add a log msg pointing to UA logs
```
```sh
tox -e integration-tests -- tests/integration_tests/modules/test_ubuntu_advantage.py::TestUbuntuAdvantagePro
```

cc_ubuntu_advantage: improve UA logs discovery (SC-1269)

---

ChangeLog
cloudinit/version.py

Merge 23.1.x at 23.1.1 into main.

Release 23.1.1

---

cloudinit/util.py

```
util: Pass deprecation schedule in deprecate_call()
```

pass through deprecation schedule

---

doc/rtd/explanation/instancedata.rst
tools/.github-cla-signers

Fix metadata IP in instancedata.rst
For some reason it was 168 instead of 169.

Fix metadata IP in instancedata.rst

---

cloudinit/cmd/devel/hotplug_hook.py
cloudinit/config/cc_disk_setup.py
cloudinit/config/cc_lxd.py
cloudinit/config/cc_reset_rmc.py
cloudinit/net/__init__.py
cloudinit/net/networkd.py
cloudinit/sources/DataSourceDigitalOcean.py
cloudinit/sources/DataSourceHetzner.py
cloudinit/sources/DataSourceNWCS.py
cloudinit/sources/DataSourceUpCloud.py
cloudinit/sources/helpers/vmware/imc/config_nic.py
cloudinit/templater.py
cloudinit/user_data.py
tests/integration_tests/clouds.py
tests/integration_tests/conftest.py
tests/integration_tests/instances.py
tests/unittests/config/test_cc_disk_setup.py
tests/unittests/config/test_cc_growpart.py
tests/unittests/config/test_cc_power_state_change.py
tests/unittests/config/test_cc_set_hostname.py
tests/unittests/helpers.py
tests/unittests/sources/test_init.py
tests/unittests/test_cli.py
tests/unittests/test_features.py
tests/unittests/test_netinfo.py
tests/unittests/test_util.py

```
chore: fix style tip
- remove too broad exceptions
- ignore dynamic base types in templater
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-style-tip/
```
tox -e tip-pylint,tip-flake8,tip-mypy
```

chore: fix style tip

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/sources/test_azure.py

There is a networking check in _poll_imds() which will attempt DHCP again if networking is not up for source PPS.  With the previous change to wait at least 20 minutes during provisioning for DHCP, this additional round is not necessary.
Report failure if networking is not up for any mode of source PPS. In practice, this is very unlikely as provisioning will typically timeout within the 20 minute window the VM is attempting DHCP and the source PPS VM will be deleted.
This fixes an (unobserved) issue where Savable PPS does not have networking prior to _wait_for_all_nics_ready().

sources/azure: add networking check for all source PPS

---

tools/.github-cla-signers

```
This contributor was added on a downstream ubuntu/devel branch #2020 and should be reflected in main too
```

contributor: add bdrung

---

tools/.github-cla-signers

For https://github.com/canonical/cloud-init/pull/2086

Add "frantisekz" as contributor

---

doc/rtd/explanation/instancedata.rst

missing ending quote

---

tools/.github-cla-signers

-------
Add "licebmi as a contributor"

Add "licebmi" as contributor

---

tests/unittests/helpers.py

```
test: Backport assert_call_count for old requests
Fixes test broken by e02c460 on Focal.
```
https://github.com/canonical/cloud-init/commit/e02c4607923af64311c70ae9a06d6794355e9a61 broke unittests on Focal caused by using an attribute that did not yet exist on the version of responses on Focal.
Fixes https://launchpadlibrarian.net/659934575/buildlog_ubuntu-focal-amd64.cloud-init_23.1.daily-202304060033-e02c4607~ubuntu20.04.1_BUILDING.txt.gz
On focal:
```
python3 -m pytest tests/unitests/sources/test_scaleway.py
```

backport assert_call_count for old requests

---

tests/unittests/net/test_dhcp.py

```
dhcp: Add missing mocks
```

fix unittests

---

doc/rtd/reference/network-config.rst

```
docs: update the network configuration docs path links
Updating the links to the paths in the codebase for the various 
network configuration examples
```

docs: update network configuration path links

---

cloudinit/distros/bsd.py

```
Revert "fix linux-specific code on bsd (#2143)"
This reverts commit a9cec5daa52aa9fb0a1f17dfc939e3ff61a476b9.
```
Prefer PR #2146

Revert "fix linux-specific code on bsd (#2143)"

---

README.md

```
README: Point to Github Actions build status
```

Fix the build badges

---

README.md
doc/rtd/reference/datasources.rst
doc/rtd/reference/distros.rst
doc/rtd/reference/index.rst

```
Clean up README, add supported distros page to docs.
```
The markdown table is ugly, make the README less so.

Clean up README, add supported distros page to docs.

---

.github/workflows/scheduled.yml
tests/unittests/conftest.py
tox.ini

```
ci: add hypothesis scheduled GH check
```

ci: add hypothesis scheduled GH check (SC-1167)

---

debian/changelog
debian/patches/netplan99-cannot-use-default.patch
debian/patches/series

ubuntu/focal-23.1.x:cherry pick netplan99-cannot-use-default.patch

---

ChangeLog
cloudinit/version.py

Bump the version in cloudinit/version.py to 23.2 and update ChangeLog.
```
Release 23.2
Bump the version in cloudinit/version.py to 23.2 and
```
https://github.com/orgs/canonical/projects/29/views/1?pane=issue&itemId=21361535

Release 23.2

---

.github/PULL_REQUEST_TEMPLATE.md

```
Modify PR template so autoclose works
```

Modify PR template so autoclose works

---

tests/integration_tests/reporting/test_webhook_reporting.py

```
tests: update test_webhook_reporting
Since the config-refresh_rmc_and_interface module was removed in #2148,
we also need to update the reporting test.
```

tests: update test_webhook_reporting

---

tools/.github-cla-signers

signed .github-cla-signers

---

tests/integration_tests/bugs/test_lp1835584.py

```
tests: fix test_lp1835584
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-bionic-azure/263/testReport/tests.integration_tests.bugs/test_lp1835584/test_azure_kernel_upgrade_case_insensitive_uuid/
```
CLOUD_INIT_CLOUD_INIT_SOURCE=UPGRADE CLOUD_INIT_PLATFORM="azure" CLOUD_INIT_OS_IMAGE="bionic" tox -e integration-tests -- tests/integration_tests/bugs/test_lp1835584.py::test_azure_kernel_upgrade_case_insensitive_uuid
```

tests: fix test_lp1835584

---

tools/.github-cla-signers

Add "kaiwalyakoparkar" as a contributor

Add "kaiwalyakoparkar" as a contributor

---

tests/integration_tests/bugs/test_gh626.py

test: add tracking bug id

---

tests/integration_tests/modules/test_ca_certs.py

```
tests: Update test_clean_log for oci
```
There's a '99-' file in /etc/cloud/cloud.cfg.d/ that activates this module.

tests: Update test_clean_log for oci

---

cloudinit/util.py

I've tried grokking this one too many times...

Add docstring and typing to mergemanydict

---

ChangeLog
cloudinit/version.py

```
Relesae 23.2.1
Bump the version in cloudinit/version.py to 23.2.1 and update ChangeLog.
LP: #2025180
```
git cherry-pick 23.2.1 # to sync Changelog into main

Release 23.2.1

---

ChangeLog

```
ChangeLog: Describe the issue fixed, not the former behavior
```

fix changelog

---

tests/integration_tests/modules/test_combined.py

… match
```
tests: daily devel PPA is now version 99.daily update tests to match
```
unhappy jenkins:
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-mantic-lxd_container/lastSuccessfulBuild/testReport/junit/tests.integration_tests.modules.test_combined/TestCombined/test_final_message/

tests: daily devel PPA is now version 99.daily update tests to match

---

cloudinit/config/cc_lxd.py

```
LXD documentation has moved and broken this link as a result.
I believe this is the correct one to redirect to, but please
advise if not.
```

Update LXD URL

---

doc/examples/cloud-config-add-apt-repos.txt

```
doc: fix typo on apt.primary.arches
```
N/A
N/A

doc: fix typo on apt.primary.arches

---

cloudinit/sources/DataSourceVMware.py

Multiple ip addresses are common scenario for modern Linux, so set debug log level for such cases.
And update copyright.

DS VMware: modify a few log level

---

cloudinit/importer.py
tests/unittests/test_importer.py

```
Fix reference before assignment
Fixes GH-4288 
```

fixes 4288

---

ChangeLog
cloudinit/importer.py
cloudinit/version.py
tests/integration_tests/test_kernel_commandline_match.py
tests/unittests/test_importer.py
tools/ds-identify

23.2.x: Release 23.2.2

---

ChangeLog
cloudinit/version.py

```
Release 23.2.2
Bump the version in cloudinit/version.py to 23.2.2 and
```

Cherry-pick 23.2.2 version/changelog

---

ChangeLog
cloudinit/importer.py
cloudinit/version.py
debian/changelog
tests/integration_tests/test_kernel_commandline_match.py
tests/unittests/test_importer.py
tools/ds-identify

```sh
new_upstream_snapshot.py -c 23.2.2
dch -r -D lunar ''
git commit -m 'releasing cloud-init version 23.2.2-0ubuntu0~23.04.1' debian/changelog
git tag ubuntu/23.2.2-0ubuntu0_23.04.1
```

Lunar 23.2.x

---

cloudinit/config/cc_ntp.py
cloudinit/config/cc_resolv_conf.py
cloudinit/config/cc_rh_subscription.py
cloudinit/config/cc_spacewalk.py
cloudinit/config/cc_yum_add_repo.py
cloudinit/distros/__init__.py
cloudinit/distros/openeuler.py
cloudinit/net/sysconfig.py
config/cloud.cfg.tmpl
doc/rtd/reference/network-config.rst
systemd/cloud-init-generator.tmpl
systemd/cloud-init.service.tmpl
tests/unittests/test_cli.py
tools/render-cloudcfg

change openEuler to openeuler and fix some bugs in openEuler
Reference:
https://gitee.com/src-openeuler/cloud-init/issues/I3SQF9?from=project-issue
https://gitee.com/src-openeuler/cloud-init/issues/I4KMYA?from=project-issue
sync:
https://gitee.com/src-openeuler/cloud-init/blob/e49820529009e4ff9e8190bd56c89621759ae6ec/Fix-the-error-level-logs-displayed-for-the-cloud-init-local-service.patch
https://gitee.com/src-openeuler/cloud-init/blob/e49820529009e4ff9e8190bd56c89621759ae6ec/bugfix-cloud-init-add-os-support.patch

change openEuler to openeuler and fix some bugs in openEuler

---

cloudinit/config/cc_keyboard.py
cloudinit/config/schemas/schema-cloud-config-v1.json
cloudinit/distros/alpine.py
tests/unittests/config/test_cc_keyboard.py

```
cc_keyboard: add Alpine support
Add support for Alpine Linux to cc_keyboard.
```

cc_keyboard: add Alpine support

---

tests/unittests/config/test_cc_wireguard.py

```
cc_wireguard: make tests pass on FreeBSD
These tests relied on the SUT to provide sensible return values for
util.kernel_version(). On FreeBSD, those values are 14.0-CURRENT for my
development machine, which doesn't work well with when split at '.' and
compared against a pair of integers (14, '0-CURRENT') < (5, 4) doesn't
make much sense.
This patch adds `@mock`s for util.kernel_version wherever it is used.
That way, test_cc_wireguard.py tests passes on a FreeBSD system.
```

cc_wireguard: make tests pass on FreeBSD

---

tests/unittests/config/test_cc_growpart.py

```
cc_growpart: fix tests to run on FreeBSD
because /etc/rc.d/growfs exists on FreeBSD, we need to be selective
about when to allow tests access to it, so that they will pass.
```

cc_growpart: fix tests to run on FreeBSD

---

tests/integration_tests/clouds.py

```
integration tests: Pass username to pycloudlib
This enables running cloud-init integration tests from distros other
than Ubuntu.
```

integration tests: Pass username to pycloudlib

---

integration-requirements.txt

```
Bump pycloudlib to 1!5.1.0 for ec2 mantic daily image support
```

Bump pycloudlib to 1!5.1.0 for ec2 mantic daily image support

---

ChangeLog
cloudinit/version.py

Sync hotflix 23.3.x ChangeLog and version.py
```
Release 23.3.1
Bump the version in cloudinit/version.py to 23.3.1 and update ChangeLog.
```

Release 23.3.1

---

tests/unittests/config/test_apt_source_v1.py

use msg from commit
Follow up #4424

Refactor test_apt_source_v1.py to use pytest

---

tools/.github-cla-signers

Add "phsm" as contributor

---

doc/rtd/howto/debug_user_data.rst

```
docs: link the cloud-config validation service
```
https://warthogs.atlassian.net/browse/SC-1485?focusedCommentId=312348

docs: link the cloud-config validation service (SC-1573)

---

cloudinit/cmd/devel/__init__.py
cloudinit/cmd/devel/hotplug_hook.py
cloudinit/cmd/devel/net_convert.py
cloudinit/cmd/main.py
cloudinit/config/cc_package_update_upgrade_install.py
cloudinit/config/cc_rsyslog.py
cloudinit/log.py
cloudinit/sources/DataSourceVMware.py
cloudinit/stages.py
tests/unittests/config/test_cc_ca_certs.py
tests/unittests/config/test_schema.py
tests/unittests/net/test_network_state.py
tests/unittests/test_log.py
tests/unittests/test_net.py
tools/ccfg-merge-debug

```
style: Update log functions to snake case
```
As [suggested by @TheRealFalcon](https://github.com/canonical/cloud-init/pull/4435#pullrequestreview-1634190397).

Make logging snakecase

---

debian/changelog
debian/patches/cpick-015543d3-apt-install-software-properties-common-when-absent-but
debian/patches/cpick-0d9f149a-Pytestify-apt-config-test-modules-4424
debian/patches/cpick-5023e9f9-Refactor-test_apt_source_v1.py-to-use-pytest-4427
debian/patches/cpick-e9cdd7e3-Install-gnupg-if-gpg-not-found-4431
debian/patches/series

Ubuntu/mantic 23.3.x

---

cloudinit/cmd/main.py
cloudinit/log.py
tests/integration_tests/cmd/test_status.py
tests/unittests/test_cli.py

```
Export warning logs to status.json
```
Work continued from https://github.com/canonical/cloud-init/pull/2164

Export warning logs to status.json

---

cloudinit/sources/DataSourceNWCS.py

I realized when I created this data source I had forgotten to add a contact email for it. Updating src to include email.

Add contact email for NWCS.sh

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/cla.yml
README.md
doc/rtd/development/contribute_code.rst
doc/rtd/reference/datasources/cloudstack.rst

Fix links after https://github.com/canonical/cloud-init/pull/4469/

Doc contrib links

---

debian/changelog
debian/patches/do-not-block-user-login.patch
debian/patches/series

If/once approved and merged, these changes will be reflected to jammy, lunar, and mantic.

Ubuntu/focal 23.3.x

---

debian/changelog
debian/patches/do-not-block-user-login.patch
debian/patches/series

```
```
[the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
[unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html)
accordingly
[documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html)
accordingly

Ubuntu/jammy 23.3.x

---

debian/changelog
debian/patches/do-not-block-user-login.patch
debian/patches/series

```
```
[the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
[unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html)
accordingly
[documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html)
accordingly

Ubuntu/lunar 23.3.x

---

doc/rtd/explanation/analyze.rst

```
doc: Fix incorrect statement about `cloud-init analyze`
```

Docs Correction

---

Makefile
cloudinit/templater.py
setup.py
tests/unittests/test_render_template.py
tools/render-template

```
tools/render-template: Allow disabling yaml loading
Fixes GH-4487
```
Fixes #4487

tools/render-template: Allow disabling yaml loading

---

.github/PULL_REQUEST_TEMPLATE.md

```
github: allow pull request to specify desired rebase and merge
```

github: allow pull request to specify desired rebase and merge

---

tests/integration_tests/releases.py

```
integration_tests: Support running on non-Ubuntu distros
Commit 2562f93383 broke cross-platform support. Fix it.
Also remove an unused function.
```

integration_tests: Support running on non-Ubuntu distros

---

cloudinit/url_helper.py
cloudinit/util.py
packages/bddeb
packages/brpm
tests/unittests/helpers.py
tests/unittests/test_url_helper.py

Remove dead code

---

.github/workflows/check_format.yml
.github/workflows/integration.yml
.github/workflows/unit.yml
README.md

```
test: add gh workflows on push to main, update status badges
Update workflows: check_format, unit and integration to run tests each time a branch lands in main.
Update our status badges in README.md to represent the project-level status of this CI instead of per pull request.
```

test: add gh workflows on push to main, update status badges

---

.github/PULL_REQUEST_TEMPLATE.md
cloudinit/config/schema.py
cloudinit/sources/DataSourceAzure.py
cloudinit/sources/azure/errors.py
cloudinit/util.py
debian/changelog
tests/integration_tests/cmd/test_schema.py
tests/integration_tests/modules/test_cli.py
tests/integration_tests/releases.py
tests/unittests/sources/azure/test_errors.py
tests/unittests/sources/test_azure.py
tests/unittests/test_util.py

Changes in the AzureDataSource.py in upstream rendered an inability for git to resolve merge conflicts.
This broke daily build recipes https://launchpadlibrarian.net/695986874/buildlog.txt.gz for Mantic series only specifically related to 
```
Auto-merging cloudinit/sources/DataSourceAzure.py`
CONFLICT (content): Merge conflict in cloudinit/sources/DataSourceAzure.py
```
```
git checkout upstream/main -B main
git merge upstream/ubuntu/devel # see merge conflict
```
```
git checkout upstream/ubuntu/devel -B ubuntu/devel
new_upstream_snapshot.py
```
The fix needed here is the resolve those merge conflicts in daily package builds is performing a new_upstream_snapshot,py into `upstream/ubuntu/devel` leaving the branch in UNRELEASED state.
```
git fetch …
```

Ubuntu/devel fix daily recipe with new_upstream_snapshot.py

---

cloudinit/sources/DataSourceAzure.py

This is normal behavior, don't warn.

azure: update diagnostic from warning level to debug

---

tests/integration_tests/test_upgrade.py

Use message of commit
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-gce/348/testReport/junit/tests.integration_tests/test_upgrade/test_clean_boot_of_upgraded_package/

Undo dhcp6 integration test changes

---

tests/integration_tests/modules/test_package_update_upgrade_install.py

test: Add default hello package version

---

cloudinit/distros/__init__.py
cloudinit/distros/suse.py

Proposed commit message:
```
distros: Add suse
```
Fixes https://github.com/canonical/cloud-init/issues/4525

Add suse distro

---

tests/integration_tests/bugs/test_lp1898997.py
tests/integration_tests/modules/test_ansible.py

test: Skip failing tests

---

cloudinit/config/schema.py
tests/unittests/config/test_schema.py

```
When non-root user calls cloud-init schema to validate cfg files, they will get a permissions error on /var/lib/cloud/instance dir trying to source the cached datasource. Fallback to default read_cfg_paths in this case and log debug level msg about this case.
Since cloud-init schema CLI is used in the context of validating config files and not really searching for cfg path overrides, using default paths to find instance-data.json isn't critical or even a warning condition.
Additionally avoid print() and use LOG.warning when no datasource currently detected as this should indicate that scripts or user may be trying to read instance-data.json which does not exist yet.
Fixes GH-4620
```
```
lxc launch ubuntu-daily:mantic test-m
lxc exec test-m -- cloud-iniit status --wait
lxc exec …
```

schema: non-root fallback to default cfg paths on perm errors

---

cloudinit/net/network_state.py

```
refactor: Remove metaclass from network_state.py
It's magic that makes it hard to follow call hierachies without saving
much code.
```
Existing unit test coverage should suffice. If this broke anything it should be pretty apparent.

refactor: Remove metaclass from network_state.py

---

cloudinit/config/schemas/schema-cloud-config-v1.json
tests/unittests/test_merging.py

```
fix: Add schema for merge types
Fixes GH-4647
```
https://github.com/canonical/cloud-init/issues/4647
Added unit tests

fix: Add schema for merge types

---

tests/integration_tests/datasources/test_none.py

```
tests: datasourcenone rely on client.restart to block until done (#)`
Earlier iterations of this test exposed failure cases where DataSourceNone and cloud-init status --wait would block indefinitely in some failure modes. The primary failure mode was DataSourceNone config on LXD containers due to invalid network config on virtual NICs due to LP:#2022947 and newer netplan resulting in tracebacks preventing init local and network boot stages from persisting completion status to /run/cloud-init/status.json.
This is resolved already within the test by copying working network config prior to DataSourceNone detection on lxd_containers.
The test can now rely on client.restart default blocking and retries to avoid expiring all retries on platforms with slower reboots.
```
90 retries not …

tests: datasourcenone rely on client.restart to block until done

---

ChangeLog
cloudinit/version.py

Release 23.4

---

cloudinit/config/schemas/schema-cloud-config-v1.json

```
config: Module documentation updates
- improve security wording
- standardize default value formatting
```

config: Module documentation updates

---

cloudinit/analyze/show.py
cloudinit/config/cc_apt_pipelining.py
cloudinit/config/cc_ntp.py
cloudinit/distros/networking.py
cloudinit/mergers/m_list.py
cloudinit/net/dhcp.py
cloudinit/net/sysconfig.py
cloudinit/sources/DataSourceConfigDrive.py
cloudinit/sources/helpers/vmware/imc/guestcust_util.py
cloudinit/ssh_util.py
cloudinit/url_helper.py
cloudinit/util.py
tests/unittests/filters/test_launch_index.py
tests/unittests/helpers.py
tests/unittests/sources/test_smartos.py
tests/unittests/test_merging.py

```
chore(ruff): fix tip target
```
tox -e tip-ruff

style(ruff): fix tip target

---

cloudinit/util.py

```
fix(util): Fix boottime to work on OpenBSD
OpenBSD doesn't have sysctlbyname()
But all BSDs have `sysctl()`.
Luckily, all BSDs' have the same values in sysctl.h for
`CTL_KERN`. Unfortunately, `KERN_BOOTTIME` is not so consistent, so we
need to add a small compat hack for NetBSD.
```

fix(util): Fix boottime to work on OpenBSD

---

cloudinit/sources/DataSourceCloudStack.py
tests/unittests/sources/test_cloudstack.py

```
Implement DataSourceCloudStack.get_hostname() to return FQDN
CloudStack provides instance name as hostname.
Instance name can have dashes in its name, but not dots.
Thus, setting FQDN as instance name is impossible in Cloudstack.
The virtual network where the instance is connected, however,
has a "Network domain" property which is propagated as "search"
parameter into the instance's /etc/resolv.conf.
Current behavior:
For instance with name "instance-a" in the network with domain
"example.com": 
- its /etc/hostname would contain
instance-a
- its /etc/hosts would contain
127.0.1.1 instance-a instance-a
Behavior with this patch applied:
- its /etc/hostname would contain
instance-a
- its /etc/hosts would contain:
127.0.1.1 instance-a.example.com instance-a
```
Please point me out if I …

Implement DataSourceCloudStack.get_hostname() to return FQDN

---

.github/workflows/linkcheck.yml
doc/rtd/development/datasource_creation.rst
doc/rtd/howto/status.rst
doc/rtd/spelling_word_list.txt

Blocked by https://github.com/canonical/cloud-init/pull/4578, separate PR because that one is already too big.

Datasource docs update, include boot status

---

ChangeLog
cloudinit/cmd/status.py
cloudinit/version.py
tests/unittests/cmd/test_status.py

23.4.x: Release 23.4.1

---

ChangeLog
cloudinit/version.py

Depends on the review and merge/push of https://github.com/canonical/cloud-init/pull/4694

sync release 23.4.1

---

cloudinit/templater.py

```
chore: remove commented code
```

chore: remove commented code

---

cloudinit/net/dhcp.py
cloudinit/sources/DataSourceCloudStack.py
tests/unittests/net/test_dhcp.py

A couple of minor fixes in fail over code paths. Add a typing and docstring.

Minor dhcp fixes

---

doc/rtd/explanation/format.rst
doc/rtd/reference/merging.rst

What value is this content to a user today?

doc: Document how cloud-init is, not how it was

---

debian/changelog
debian/patches/series
debian/patches/status-retain-recoverable-error-exit-code.patch

Ubuntu/lunar 23.4.x

---

debian/changelog
debian/patches/series
debian/patches/status-retain-recoverable-error-exit-code.patch

Ubuntu/jammy 23.4.x

---

debian/changelog
debian/patches/series
debian/patches/status-retain-recoverable-error-exit-code.patch

Ubuntu/focal 23.4.x

---

cloudinit/net/network_manager.py
cloudinit/net/network_state.py
tests/unittests/test_net.py

```
feat: Add v2 route mtu rendering to NetworkManager
```

feat: Add v2 route mtu rendering to NetworkManager

---

tests/unittests/test_ds_identify.py
tools/.github-cla-signers
tools/ds-identify

```
feat: datasource check for WSL
Adds `dscheck_WSL` function in ds-identify to allow detecting WSL.
Fixes: UDENG-1993
```
This PR opens up the work for implementing a datasource for WSL.
Subsequent PR's will bring the datasource, its documentation and
the final step should be enabling it in the required datasources lists.

feat: datasource check for WSL

---

requirements.txt
test-requirements.txt

```
tests: Pin jsonschema version
Release 4.21.0 broke tests
```
4.21.0 was released [four hours ago](https://github.com/python-jsonschema/jsonschema/releases/tag/v4.21.0)
CI does this for us :-)

tests: Pin jsonschema since release 4.21.0 broke ci

---

debian/changelog
debian/cloud-init.maintscript

```
Fixes GH-4760
```
Solves #4760 

fix(debian): Remove/Delete README in /etc/cloud/clean.d/

---

debian/changelog
debian/cloud-init.maintscript

```
Fixes GH-4760
```
Solves #4760 

fix(debian): Remove/Delete README in /etc/cloud/clean.d/ (mantic)

---

debian/changelog
debian/cloud-init.maintscript

```
Fixes GH-4760
```
Solves #4760 

fix(debian): Remove/Delete README in /etc/cloud/clean.d/ (lunar)

---

debian/changelog
debian/cloud-init.maintscript

```
Fixes GH-4760
```
Solves #4760 

fix(debian): Remove/Delete README in /etc/cloud/clean.d/ (jammy)

---

debian/changelog
debian/cloud-init.maintscript

```
Fixes GH-4760
```
Solves #4760 

fix(debian): Remove/Delete README in /etc/cloud/clean.d/ (focal)

---

doc/rtd/reference/datasources.rst
doc/rtd/reference/datasources/scaleway.rst

Add the missing Scaleway datasource documentation to the list of datasources of the reference section.
```
(docs): Add DatasourceScaleway documentation
Add the missing Scaleway datasource documentation to the list of
datasources of the reference section.
```
N/A
N/A
- [X ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ X] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

doc : Add DatasourceScaleway documentation

---

ChangeLog
cloudinit/version.py

sync release 23.4.2

---

ChangeLog
cloudinit/version.py
debian/changelog
debian/patches/status-retain-recoverable-error-exit-code.patch
requirements.txt
test-requirements.txt
tests/unittests/test_ds_identify.py
tools/ds-identify

Ubuntu/mantic 23.4.x

---

integration-requirements.txt
test-requirements.txt

```
ci: Pin pytest<8.0.0.
The latest pytest release broke some tests in non-obvious ways. Pin
the version for now so that CI passes.
```
Logs here -> [test.txt](https://github.com/canonical/cloud-init/files/14088258/test.txt)

ci: Pin pytest<8.0.0.

---

tests/integration_tests/test_networking.py

```
tests(net-config): add awareness of netplan on stable Ubuntu
Update test to account for skipping schema validation due to absence of python3-netplan prior to Ubuntu Mantic.
Also limit the test to IS_UBUNTU since it has specific depedencies on netplan availability and use the setup_image fixture to ensure CLOUD_INIT_SOURCE is honored prior to instance launch.
Without the setup_image fixutre, this test was launching instance without first installing cloud-init from daily PPA or IN_PLACE etc.
```
Failing jenkins jobs
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-lxd_container/382/testReport/tests.integration_tests/test_networking/test_invalid_network_v2_netplan/
```
CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE CLOUD_INIT_OS_IMAGE=(jammy|focal|mantic) …
```

tests(net-config): add awareness of netplan on stable Ubuntu

---

ChangeLog
cloudinit/version.py

Cherry-pick release 23.4.3

---

tests/integration_tests/datasources/test_azure.py

```
tests: Remove invalid keyword from method call
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-azure/386/testReport/junit/tests.integration_tests.datasources/test_azure/test_azure_eject/
Untested (I currently don't have azure credentials set up on new machine)

tests: Remove invalid keyword from method call

---

tests/integration_tests/net/test_dhcp.py

```
tests(dhcp): Add udhcpc client to the integration test matrix
Udhcpc support is incomplete, however it does function.
Add it to the test matrix for improved test coverage.
```

tests(dhcp): Add udhcpc client to test matrix

---

cloudinit/config/cc_lxd.py
cloudinit/distros/parsers/ifconfig.py
cloudinit/util.py

These involve operations on possibly null variables or impossible logic.
```
fix: Address TIOBE abstract interpretation issues
These involve operations on possibly null variables or impossible logic.
```
Current top 3 at https://canonical.tiobe.com/tiobeweb/TICS/ViolationsDashboard.html#axes=Project(cloud-init)&sort=T(4,worst)&x=Ap(type),Ap(rule),Ap(level),Ap(impactAtProject),Ap(impactAtScope),Ap(message)

fix: Address TIOBE abstract interpretation issues

---

tests/integration_tests/datasources/test_ec2_ipv6.py

```
test: fix test_ec2_ipv6
The test removes dhcp clients to force imds recrawling, but didn't
remove the dhcpcd one, after 21b2b6e4423b0fec325b32042c05ef4274cdd301
the dhcpcd one is used and the test preconditoin is not met.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-mantic-ec2/139
```sh
export CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily
export CLOUD_INIT_OS_IMAGE=mantic
tox -e integration-tests -- --pdb tests/integration_tests/datasources/test_ec2_ipv6.py::test_dual_stack
```

test: fix test_ec2_ipv6

---

debian/apport-general-hook.py
debian/changelog

Requires https://github.com/canonical/cloud-init/pull/4873 and updates to the other branches {focal,jammy,mantic}

apport: Don't collect logs if cloud-init is disabled

---

tests/integration_tests/modules/test_combined.py

```
test: fix test_combined_cloud_config_json
Features are series dependent, make the test aware of that.
The test now distiguishes between devel and in_place cloud-init pakages
which would carry quilt patches modifying features.
Co-authored-by: James Falcon <james.falcon@canonical.com>
```
```
export CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED
export CLOUD_INIT_PLATFORM=lxd_container
tox -e integration-tests -- --pdb tests/integration_tests/modules/test_combined.py::TestCombined::test_combined_cloud_config_json
```

test: fix test_combined_cloud_config_json

---

doc/rtd/explanation/events.rst
setup.py
sysvinit/gentoo/cloud-init-hotplug
tools/cloud-init-hotplugd
tools/hook-hotplug

```
Change hoot-hotplug from being Bash-specific to POSIX shell.
Add OpenRC init script for starting hotplug "daemon".
Add hotplug "daemon" that corresponds to cloud-init's
cloud-init-hotplugd.service/cloud-init-hotplugd.socket functionality.
```

Modify hook-hotplug to be POSIX shell, add OpenRC init script

---

doc/rtd/reference/datasources/ec2.rst

```
doc(ec2): fix metadata urls
Add dot in last url and switch to literal urls to fix square braket rendering.
Fixes: GH-4870
```

doc(ec2): fix metadata urls

---

debian/changelog
debian/cloud-init.postinst
debian/patches/retain-ec2-default-net-update-events.patch
debian/patches/series

This PR adds 3 commits on top of https://github.com/canonical/cloud-init/pull/4884 to deal with hotplug changes for the next release.
https://warthogs.atlassian.net/browse/SC-1718

Mantic hotplug

---

debian/changelog
debian/cloud-init.postinst
debian/patches/retain-ec2-default-net-update-events.patch
debian/patches/series

Hotplug changes for the next release.
https://warthogs.atlassian.net/browse/SC-1718

Jammy hotplug

---

debian/changelog
debian/control

Ubuntu/devel: Drop isc-dhcp-client

---

cloudinit/config/cc_growpart.py
tests/unittests/config/test_cc_growpart.py

```
feat(Alpine) cc_growpart.py: fix handling of /dev/mapper devices for Alpine
Unlike the majority of other Linux distros /dev/mapper entries in
Alpine Linux are NOT symlinks to /dev/dm-X block devices but rather are
actual block devices themselves. This is a side-effect of Alpine's use
of mdev, rather than udev, in its initramfs.
Therefore this change works out the corresponding /dev/dm-X for any
/dev/mapper/XYZ device on Alpine.
```

cc_growpart.py: fix handling of /dev/mapper devices for Alpine

---

tests/unittests/config/test_cc_ubuntu_pro.py

```
test: fix jsonschema version checking in pro test
```
https://launchpadlibrarian.net/715151681/buildlog_ubuntu-focal-amd64.cloud-init_23.4.daily-202402191902-4779679e~ubuntu20.04.1_BUILDING.txt.gz
https://launchpadlibrarian.net/715105971/buildlog_ubuntu-jammy-amd64.cloud-init_23.4.daily-202402191436-4779679e~ubuntu22.04.1_BUILDING.txt.gz

test: fix jsonschema version checking in pro test

---

debian/changelog
debian/cloud-init.postinst
debian/patches/retain-ec2-default-net-update-events.patch
debian/patches/series

Hotplug changes for the next release.
https://warthogs.atlassian.net/browse/SC-1718

Focal hotplug

---

sysvinit/openrc/cloud-config
sysvinit/openrc/cloud-final
sysvinit/openrc/cloud-init
sysvinit/openrc/cloud-init-ds-identify
sysvinit/openrc/cloud-init-local

```
refactor(openrc):  Improve the OpenRC files
As suggested by @blackboxsw in #4772 I have made some improvements to the OpenRC files.
```

Improve OpenRC files

---

tests/integration_tests/net/test_dhcp.py

```
test: xfail udhcpc on azure
```
see https://github.com/canonical/cloud-init/issues/4765

test: xfail udhcpc on azure

---

doc/rtd/reference/network-config-format-v2.rst

```
docs: Remove statement about device path matching
Fixes GH-4929
```
https://github.com/canonical/cloud-init/issues/4929

docs: Remove statement about device path matching

---

cloudinit/config/cc_apt_configure.py
tests/unittests/config/test_apt_configure_sources_list_v1.py
tests/unittests/config/test_apt_configure_sources_list_v3.py
tests/unittests/config/test_apt_source_v1.py

WIP: apt: kill spawned keyboxd after gpg cmd interaction

---

tests/integration_tests/bugs/test_lp1813396.py

```
test: Make integration test output more useful
```
Without this, all you see is:
```
assert 2 < 2
```

test: Make integration test output more useful

---

ChangeLog
cloudinit/config/cc_apt_configure.py
cloudinit/net/dhcp.py
cloudinit/subp.py
cloudinit/version.py
debian/changelog
doc/rtd/reference/network-config-format-v2.rst
tests/integration_tests/test_upgrade.py
tests/unittests/config/test_apt_configure_sources_list_v1.py
tests/unittests/config/test_apt_configure_sources_list_v3.py
tests/unittests/config/test_apt_source_v1.py
tests/unittests/net/test_dhcp.py

Release 24.1 to Noble

---

tests/integration_tests/modules/test_hotplug.py

```
test(aws): local network connectivity on multi-nics
```
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2055397

test(aws): local network connectivity on multi-nics

---

tools/run-container

```
feat: Make lxc binary configurable
```
Helpful for non-ubuntu images

feat: make lxc binary configurable

---

ChangeLog
cloudinit/version.py

```
release: sync changelog and version
```
The release should have been to main originally, but it's too late to put the tagged commit on main, so just sync the changelog.

release: sync changelog and version

---

tools/ds-identify

```
fix: use correct disabled path in ds-identify
```

fix: use correct disabled path in ds-identify

---

tests/unittests/conftest.py

```
test: Allow fake_filesystem to work with TemporaryDirectory
```

test: Allow fake_filesystem to work with TemporaryDirectory

---

ChangeLog
cloudinit/version.py

Release 24.1.1

---

ChangeLog
cloudinit/version.py

Sync 24.1.1 changelog and version

---

ChangeLog
cloudinit/config/cc_apt_configure.py
cloudinit/config/modules.py
cloudinit/config/schemas/schema-network-config-v1.json
cloudinit/net/dhcp.py
cloudinit/sources/DataSourceOracle.py
cloudinit/sources/DataSourceScaleway.py
cloudinit/sources/DataSourceVMware.py
cloudinit/sources/DataSourceWSL.py
cloudinit/url_helper.py
cloudinit/util.py
cloudinit/version.py
debian/changelog
doc/rtd/reference/datasources/oracle.rst
doc/rtd/reference/datasources/wsl.rst
doc/rtd/reference/network-config-format-v1.rst
tests/integration_tests/modules/test_ubuntu_pro.py
tests/integration_tests/util.py
tests/unittests/net/test_dhcp.py
tests/unittests/sources/test_common.py
tests/unittests/sources/test_oracle.py
tests/unittests/sources/test_scaleway.py
tests/unittests/sources/test_wsl.py
tests/unittests/test_ds_identify.py
tests/unittests/test_upgrade.py
tests/unittests/test_url_helper.py
tools/ds-identify

Noble 24.1.1 release

---

.gitignore

```
chore: ignore all cloud-init_*.tar.gz in .gitignore
We were ignoring orig.tar.gz, but sbuild creates a .tar.gz
```
We were ignoring orig.tar.gz, but sbuild creates a .tar.gz.

chore: ignore all cloud-init_*.tar.gz in .gitignore

---

doc-requirements.txt

```
doc: Install required dependencies
```
Otherwise on Noble I see:
```
$ tox -re doc
doc: remove tox env folder /home/holmanb/cloud-init/.tox/doc
.pkg: remove tox env folder /home/holmanb/cloud-init/.tox/.pkg
doc: install_deps> python -I -m pip install -r /home/holmanb/cloud-init/doc-requirements.txt
.pkg: install_requires> python -I -m pip install setuptools
.pkg: _optional_hooks> python /usr/lib/python3/dist-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /usr/lib/python3/dist-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_wheel> python /usr/lib/python3/dist-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: install_requires_for_build_wheel> python -I -m pip install …
```

doc: Install required dependencies

---

cloudinit/gpg.py
tests/unittests/conftest.py

```
gpg: Handle temp directory containing files
```

gpg: Handle temp directory with files

---

cloudinit/config/schemas/schema-cloud-config-v1.json
tools/.github-cla-signers

We pass the parameters straight through to `ansible-pull`, which supports this flag since https://github.com/ansible/ansible/pull/11219.

Add verify_commit and inventory to ansible.pull schema

---

cloudinit/config/cc_ansible.py
cloudinit/config/cc_ubuntu_autoinstall.py
tests/unittests/config/test_cc_ansible.py
tests/unittests/config/test_cc_ubuntu_autoinstall.py
tests/unittests/conftest.py
tests/unittests/net/test_init.py

test: mocking updates

---

ChangeLog
cloudinit/version.py

Cherry pick of hotfix Changelog/24.1.2 version bump
```
Release 24.1.2
Bump the version in cloudinit/version.py to 24.1.2 and update ChangeLog.
```

Sync Release 24.1.2 from hotfix branch

---

tests/unittests/test_ds_identify.py
tests/unittests/test_gpg.py

```
fix(tests): Leaked subp.which mock
Fixes GH-5094
```
Fixes #5094

fix(tests): Leaked subp.which mock

---

ChangeLog
cloudinit/version.py

Cherry-pick top commit of 24.1.x

Release 24.1.3

---

.github/workflows/linkcheck.yml
.github/workflows/scheduled.yml

```
ci: Make linkcheck a scheduled job
```

Make linkcheck a scheduled test

---

.github/workflows/linkcheck.yml

https://github.com/canonical/cloud-init/actions/runs/8502422349
```
Invalid workflow file: .github/workflows/linkcheck.yml#L3
You have an error in your yaml syntax on line 3
```

ci: fix linkcheck.yml invalid yaml

---

tests/unittests/sources/test_ec2.py

```
test: pytest-ify t/u/sources/test_ec2.py
```
- [] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly
- [] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

test: pytest-ify t/u/sources/test_ec2.py

---

tests/integration_tests/assets/enable_profile.py
tests/integration_tests/conftest.py
tests/integration_tests/instances.py
tests/integration_tests/integration_settings.py

```
test: Enable profiling in integration tests
```
Based on 4940351013f5
set `INCLUDE_PROFILE = True`
run an integration test
follow the logged instructions:
```
===================================== 1 passed, 3 warnings in 57.68s =====================================
Profile reports generated, run the following to view:
python3 -m snakeviz /tmp/cloud_init_test_logs/last/tests/integration_tests/*/*/*/profile/local.stats
python3 -m snakeviz /tmp/cloud_init_test_logs/last/tests/integration_tests/*/*/*/profile/network.stats
python3 -m snakeviz /tmp/cloud_init_test_logs/last/tests/integration_tests/*/*/*/profile/config.stats
python3 -m snakeviz /tmp/cloud_init_test_logs/last/tests/integration_tests/*/*/*/profile/final.stats
```

test: Enable profiling in integration tests

---

cloudinit/config/cc_growpart.py
cloudinit/distros/__init__.py
cloudinit/distros/alpine.py
cloudinit/distros/bsd.py
tests/unittests/config/test_cc_growpart.py

Refactor growpart code into distro definitions.
I wrote this a while ago but forgot to submit it.

Growpart refactor distro specific code

---

doc/rtd/reference/breaking_changes.rst
doc/rtd/reference/index.rst

```
docs: Add breaking changes section to reference
```
In order to have snapd seeding changes to reference from the noble release docs

docs: Add breaking changes section to reference docs

---

tests/integration_tests/util.py

```
The old check didn't catch all cases.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-lxd_vm/88/testReport/junit/tests.integration_tests.datasources.test_nocloud/TestFTP/test_nocloud_ftp_unencrypted_server_succeeds/

test: universally ignore netplan apply dbus issue

---

tests/integration_tests/modules/test_package_update_upgrade_install.py

```
test: Update version of hello package installed on noble
```

test: Update version of hello package installed on noble

---

integration-requirements.txt

```
test: bump pycloudlib to use latest version
This is to ensure we can get the latest Azure noble images.
```
I ran the CI subset of tests against Azure on Noble using this version and they passed.

test: bump pycloudlib to use latest version

---

doc/rtd/reference/datasources/nocloud.rst

```
doc(nocloud): Describe ftp and ftp over tls implementation
Standardize and improve nocloud documentation.
```

doc: Describe ftp

---

templates/sources.list.ubuntu.deb822.tmpl

```
chore(templates): update ubuntu universe wording
Fixes: GH-5197
```

chore(templates): update ubuntu universe wording

---

tests/unittests/test_ds_identify.py
tools/ds-identify

Originally proposed by @smoser, then [reverted](https://github.com/canonical/cloud-init/pull/4327) due to [a reported bug](https://github.com/canonical/cloud-init/issues/4794) that it introduced. This brings back the original proposal by Scott plus the fixes required to resolve the issues it introduced. Also makes some minor shellcheck and test changes.

Bring back ds-identify fix

---

doc/rtd/conf.py
doc/rtd/reference/datasources/wsl.rst
doc/rtd/reference/modules.rst
doc/rtd/tutorial/index.rst
doc/rtd/tutorial/lxd.rst
doc/rtd/tutorial/wsl.rst

```
docs: Add WSL tutorial
```
Note that this tutorial references the Preview version of Ubuntu and will need to be updated soon.

docs: Add WSL tutorial

---

doc-requirements.txt
doc/rtd/tutorial/wsl.rst

```
docs: Remove preview from WSL tutorial
```

docs: Remove preview from WSL tutorial

---

doc/rtd/explanation/configuration.rst

```
docs: Add base config reference from explanation
```

docs: Add base config reference from explanation

---

cloudinit/config/schemas/schema-network-config-v2.json
tests/unittests/config/test_schema.py

During validation process, the network schema is extracted without the network key.  As such, the schema validation should work either with or without the top level network key.  This change updates the schema and adds a unit test to validate.
```
fix(schema): allow networkv2 schema without top-level key
During validation process, the network schema is extracted without
the network key.  As such, the schema validation should work
either with or without the top level network key.  This change
updates the schema and adds a unit test to validate.
```
This was causing failing integrations tests due to false negative schema validation errors.

fix(schema): allow networkv2 schema without top-level key

---

tox.ini

```
ci: Print isort diff
When it passes locally, it would be good to know why ci fails.
```

ci: Print isort diff

---

cloudinit/config/cc_landscape.py
cloudinit/distros/ubuntu.py
debian/changelog
tests/unittests/config/test_cc_landscape.py
tests/unittests/distros/test_ubuntu.py

Sync main into oracular. Contains the real fix for [LP: #2064132](https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2064132)

upstream snapshot release Ubuntu/devel

---

tests/unittests/test_atomic_helper.py
tests/unittests/test_builtin_handlers.py
tests/unittests/test_conftest.py

```
test: Remove some CiTestCase tests
Includes:
- test_atomic_helper.py
- test_builtin_handlers.py
- test_conftest.py (partial)
```

test: Remove some CiTestCase tests

---

tests/integration_tests/test_upgrade.py

This reverts the temporary changed introduced by PR #4855 that manually dropped the "dhcp6" key from the post_network yaml in the integration test "test_clean_boot_of_upgraded_package"
```
fix: stop manually dropping dhcp6 key in integration test
This reverts the temporary changed introduced by PR #4855 that
manually dropped the "dhcp6" key from the post_network yaml
in the integration test "test_clean_boot_of_upgraded_package"
```
See PR #4855 to see the temp change being reverted by this commit.
N/A

fix: stop manually dropping dhcp6 key in integration test

---

cloudinit/config/cc_apt_pipelining.py

cc_apt_pipelining docstring typo fix

---

cloudinit/config/cc_mcollective.py
cloudinit/config/cc_snap.py
cloudinit/config/cc_users_groups.py
cloudinit/config/cc_yum_add_repo.py
cloudinit/gpg.py
cloudinit/handlers/jinja_template.py
cloudinit/net/__init__.py
cloudinit/sources/DataSourceHetzner.py
cloudinit/sources/DataSourceIBMCloud.py
cloudinit/sources/DataSourceMAAS.py
cloudinit/sources/DataSourceSmartOS.py
cloudinit/sources/DataSourceWSL.py
cloudinit/sources/helpers/azure.py
cloudinit/util.py
pyproject.toml
tests/integration_tests/bugs/test_lp1835584.py
tests/integration_tests/bugs/test_lp1897099.py
tests/unittests/config/test_apt_configure_sources_list_v1.py
tests/unittests/config/test_apt_configure_sources_list_v3.py
tests/unittests/config/test_apt_source_v1.py
tests/unittests/config/test_cc_apk_configure.py
tests/unittests/config/test_cc_apt_configure.py
tests/unittests/config/test_schema.py
tests/unittests/net/test_dhcp.py
tests/unittests/sources/helpers/test_netlink.py
tests/unittests/sources/test_ec2.py
tests/unittests/test_ds_identify.py
tests/unittests/test_log.py
tests/unittests/test_stages.py
tox.ini

https://github.com/canonical/cloud-init/pull/5262#issuecomment-2102281282

Update ruff & fix some docstrings

---

cloudinit/sources/helpers/azure.py
tests/unittests/reporting/test_reporting_hyperv.py
tests/unittests/sources/azure/test_imds.py

```
test: Avoid circular import in Azure tests
```
Run `pytest tests/unittests/reporting/test_reporting_hyperv.py` or `pytest tests/unittests/sources/azure/test_imds.py` individually.

test: Avoid circular import in Azure tests

---

doc/rtd/reference/network-config.rst

```
docs: Renderers/Activators have downstream overrides
```

docs: Renderers/Activators have downstream overrides

---

packages/debian/cloud-init.logrotate

```
fix(logrotate): typo correction of delaycompress
Fixes: GH-5316
```

fix(logrotate): typo correction of delaycompress

---

tests/unittests/sources/test_ec2.py

#5321 missed one test update. Fix it.
```
test: Fix failing test_ec2.py test
#5321 missed one test update. Fix it.
```

test: Fix failing test_ec2.py test

---

debian/changelog
debian/patches/cpick-417ee551-fix-ec2-Ensure-metadata-exists-before-configuring-PBR
debian/patches/cpick-74dc7cce-test-Fix-failing-test_ec2.py-test-5324
debian/patches/cpick-d6776632-fix-Check-renderer-for-netplan-specific-code-5321
debian/patches/series

DO NOT SQUASH
Process:
- `cherry-pick` 3 commits
- Squash changelog commits
- Manually update changelog accordingly

Ubuntu/noble 24.1.x

---

.github/workflows/alpine-unittests.yml

tests(alpine): github trust lxc mounted source dir cloud-init-ro
Avoid CI noise about directory ownership for a mount that we exposed via lxd

tests(alpine): github trust lxc mounted source dir cloud-init-ro

---

tox.ini

```
ci(mypy): add type-jinja2 stubs
```
`tox -re mypy`

ci(mypy): add type-jinja2 stubs

---

tests/unittests/test_builtin_handlers.py

```
fix(tests): use regex to avoid focal whitespace in jinja debug test
```
Daily focal builds were failing on unmatched whitespace indents in jinja debug tests
https://code.launchpad.net/~cloud-init-dev/+archive/ubuntu/daily/+build/28465099
Here's a build success run using this changeset:
https://code.launchpad.net/~cloud-init-dev/+archive/ubuntu/daily/+recipebuild/3732927
The daily recipe build for focal  will take care of building this properly
https://code.launchpad.net/~cloud-init-dev/+recipe/cloud-init-daily-focal

fix(tests): use regex to avoid focal whitespace in jinja debug test

---

doc/rtd/conf.py
tox.ini

```
chore: fix lint failure
This file isn't included in the CI linting
```

chore: fix lint failure

---

cloudinit/config/cc_disk_setup.py

```
cleanup: Don't execute code on import
```
Just one module.

cleanup: Don't execute code on import

---

tests/integration_tests/modules/test_package_update_upgrade_install.py

```
tests: add oracular's hello package for pkg upgrade test
```
failing jenkins job: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-oracular-lxd_vm/7/testReport/junit/tests.integration_tests.modules/test_package_update_upgrade_install/test_versioned_packages_are_installed/
```
CLOUD_INIT_OS_IMAGE=oracular tox -e integration-tests -- tests/integration_tests/modules/test_package_update_upgrade_install.py::test_versioned_packages_are_installed
```

tests: add oracular's hello package for pkg upgrade test

---

systemd/cloud-init-hotplugd.service
systemd/cloud-init-hotplugd.socket
tests/integration_tests/cmd/test_status.py
tests/integration_tests/modules/test_ansible.py
tests/integration_tests/modules/test_hotplug.py
tests/integration_tests/util.py
tools/hook-hotplug

See individual commits.
https://warthogs.atlassian.net/browse/SC-1716
```sh
#!/bin/bash
set -eux -o pipefail
make deb
export CLOUD_INIT_CLOUD_INIT_SOURCE=cloud-init_all.deb
tox -e integration-tests -- tests/integration_tests/modules/test_hotplug.py::test_nics_before_config_trigger_hotplug
```

 feat(hotlug): trigger hotplug after cloud-init.service

---

tests/unittests/distros/package_management/test_apt.py
tests/unittests/helpers.py

```
fix(test): Remove temporary directory side effect
```
https://github.com/canonical/cloud-init/pull/5230#issuecomment-2177761257

fix(test): Remove temporary directory side effect

---

cloudinit/config/cc_package_update_upgrade_install.py
cloudinit/distros/package_management/apt.py

```
fix: Use monotonic time
Prevent time change races.
```

fix: Use monotonic time

---

tests/integration_tests/modules/test_cli.py

```
test: Update validation error in test_cli.py test
Message changed in 9c3258f4
```
Shoulda just lumped this into the last PR. Whoops.

test: Update validation error in test_cli.py test

---

.github/PULL_REQUEST_TEMPLATE.md

```
ci: Add PR checklist
Put action items directly in the checklist to make it easier for contributors.
```

Add PR checklist

---

tests/integration_tests/test_networking.py

```
test: update validate error message in test_networking
Message changed in 9c3258f4
```
```
CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_OS_IMAGE=oracular CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE tox -e integration-tests -- tests/integration_tests/test_networking.py
```

test: update validate error message in test_networking

---

.github/PULL_REQUEST_TEMPLATE.md

ci: PR update checklist GH- anchors to align w/ later template

---

cloudinit/net/cmdline.py

chore(cmdline): Update comments

---

cloudinit/cmd/query.py

Do not raise an error when userdata files are missing during cloud-init query operations
Fixes #5396
```
Gracefully handle missing files
Do not raise an error when userdata files are missing
Fixes: GH-5396
```

Gracefully handle missing userdata files during cloud-init query operations

---

cloudinit/config/schema.py
cloudinit/util.py
tests/unittests/distros/test_create_users.py

```
test: Fix deprecation test failures
8906e17e is causing some test failures on older releases.
Fix them
```

test: Fix deprecation test failures

---

tests/integration_tests/modules/test_ubuntu_pro.py

```
The ubuntu_advantage key is deprecated in 24.1 in favor of ubuntu_pro.
Any version less than 24.1 will have only an info level log resulting in no DEPRECATED keys from cloud-init status --format=yaml.
Parse log level messages in /var/log/cloud-init.log instead.
```
```
CLOUD_INIT_UA_TOKEN=<YOUR_TOKEN_HERE_FROM_UBUNTU_COM_PRO> CLOUD_INIT_OS_IMAGE=focal CLOUD_INIT_PLATFORM=lxd_container CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily  .tox/integration-tests/bin/pytest -- tests/integration_tests/modules/test_ubuntu_pro.py::TestUbuntuAdvantage::test_valid_token
```

tests: update ubuntu_pro test to account for info-level deprecations

---

tests/unittests/config/test_cc_ubuntu_pro.py

jsonschema is still a soft dependency, so don't fail it not present.
```
test: Add jsonschema guard in test_cc_ubuntu_pro.py
jsonschema is still a soft dependency, so don't fail it not present.
```
Ran tests with jsonschema both installed and uninstalled.

test: Add jsonschema guard in test_cc_ubuntu_pro.py

---

cloudinit/sources/helpers/vmware/imc/config_nic.py
tests/unittests/sources/vmware/test_vmware_config_file.py

```
fix(vmware): Explicitly set IPv6 to dhcp when there is no IPv6 addr given
When there is no IPv6 addr given in the customization configuration,
we shall set IPv6 type to dhcp6, then customized Linux network will be
set to dhcp IPv6 explicitly.
```

fix(vmware): Explicitly set IPv6 to dhcp when there is no IPv6 addr given

---

tests/integration_tests/datasources/test_nocloud.py

```
test: Ensure mkcert executable in ftp tests
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-lxd_vm/460/testReport/junit/tests.integration_tests.datasources.test_nocloud/TestFTP/test_nocloud_ftps_encrypted_server_succeeds/

test: Ensure mkcert executable in ftp tests

---

tests/integration_tests/cmd/test_status.py

```
test: Add missing assert to test_status.py
```
This doesn't fix anything. I just noticed we were missing an assert.

test: Add missing assert to test_status.py

---

cloudinit/util.py
pyproject.toml
tests/unittests/test_util.py

GH-5445
```
typing: fix check_untyped_defs in cloudinit.util
GH-5445
```

typing: fix check_untyped_defs in cloudinit.util

---

cloudinit/cmd/devel/logs.py
cloudinit/log.py
tests/unittests/cmd/devel/test_logs.py
tests/unittests/test_log.py

```
```
I have functional changes coming, but since the non-functional stuff grew a bit bigger than I was expecting, I decided to separate it as its own PR for easier review.
I'm also open to squashing a few of these if that makes more sense, though the tracing should probably remain separate.

Add trace logging and refactor logs.py

---

cloudinit/sources/DataSourceNoCloud.py
cloudinit/sources/__init__.py
doc/examples/cloud-config-datasources.txt
tests/unittests/sources/test_nocloud.py
tests/unittests/test_ds_identify.py
tools/ds-identify

See individual commits, relates to https://github.com/canonical/cloud-init/issues/5389

Improve nocloud detection / improve logging

---

cloudinit/distros/azurelinux.py

```
<bug>(azurelinux): Change default usr_lib_exec path 
Change default usr_lib_exec from /usr/libexec/ to /usr/lib. 
As azurelinux install cloud-init tool binaries under /usr/lib/cloud-int instead of /usr/libexec/cloud-init
```

modify azurelinux default libexec path

---

.github/labeler.yml
cloudinit/config/schemas/schema-cloud-config-v1.json

```
fix: doc auto label to consider schema json changes as doc PRs
```
```
`feat(schema): add chef_license schema enum
Fixes GH-5513
```

feat(schema): add chef_license schema enum

---

doc/rtd/reference/modules.rst

Fixes GH-5467
```
doc(modules): add section to wrap modules' doc
Fixes GH-5467
```

doc(modules): add section to wrap modules' doc

---

doc/rtd/conf.py
tox.ini

See individual commits:
fix(doc-spelling): config spelling_word_list_filename
chore: remove unneeded doc-lint tox env config
tox -e doc-spelling

doc-spelling fixes

---

cloudinit/url_helper.py

```
chore: Fix log message in url_helper.py
```
Original log is based on a misreading of https://github.com/canonical/cloud-init/pull/4994#discussion_r1514623431

chore: Fix log message in url_helper.py

---

cloudinit/sources/DataSourceAzure.py
cloudinit/sources/DataSourceIBMCloud.py
cloudinit/sources/DataSourceLXD.py
cloudinit/sources/__init__.py
cloudinit/sources/azure/errors.py
cloudinit/url_helper.py
debian/changelog
debian/patches/no-nocloud-network.patch
debian/patches/no-single-process.patch
doc/rtd/development/integration_tests.rst
pyproject.toml
tests/integration_tests/datasources/test_nocloud.py
tests/integration_tests/test_kernel_command_line_match.py
tests/unittests/sources/test_azure.py
tests/unittests/sources/test_ibmcloud.py

Merge main failed to rebase merge in previous upstream snapshot.
```
$ PAGER= git diff upstream/main --name-only
debian/README.source
debian/apport-general-hook.py
debian/apport-launcher.py
debian/changelog
debian/cherry-pick
debian/clean
debian/cloud-init.config
debian/cloud-init.lintian-overrides
debian/cloud-init.logrotate
debian/cloud-init.maintscript
debian/cloud-init.manpages
debian/cloud-init.postinst
debian/cloud-init.postrm
debian/cloud-init.preinst
debian/cloud-init.prerm
debian/cloud-init.templates
debian/control
debian/copyright
debian/gbp.conf
debian/gbp_format_changelog
debian/patches/deprecation-version-boundary.patch
debian/patches/no-nocloud-network.patch
debian/patches/no-single-process.patch
debian/patches/series
debian/po/POTFILES.in
debian/po/templates.pot …
```

Fix dailies: Ubuntu/noble

---

debian/changelog
debian/patches/no-nocloud-network.patch
debian/patches/no-single-process.patch
debian/patches/series

See https://github.com/canonical/cloud-init/pull/5581

[ubuntu/focal] Revert single process

---

requirements.txt

```
chore: explain other use of oauth
```

chore: explain other use of oauth

---

doc/rtd/development/contribute_code.rst
doc/rtd/development/feature_flags.rst

In alignment with our [upstream python support policy](https://docs.cloud-init.io/en/latest/development/contribute_code.html#python-support).

Document dropping Python 3.6 and 3.7

---

tests/integration_tests/test_paths.py

```
test: fix test_honor_cloud_dir int test
Align integration test with c28092fa615961c7ae2f56738a19ea28331b84a7.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-lxd_container/488/testReport/junit/tests.integration_tests.test_paths/TestHonorCloudDir/test_honor_cloud_dir/

test: fix test_honor_cloud_dir int test

---

tests/integration_tests/cmd/test_schema.py

```
test: fix cmd/test_schema int test
Adapt to new annotation formating from
a2193da3eaec4df8945cf3657f94f7c66ff2417d.
```
* a2193da3eaec4df8945cf3657f94f7c66ff2417d
* https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-oracular-lxd_vm/51/testReport/junit/tests.integration_tests.cmd.test_schema/TestSchemaDeprecations/test_schema_deprecations/

test: fix cmd/test_schema int test

---

.github/workflows/packaging-tests.yml

`feat: add automation for ubuntu/* branches asserting quilt patches apply`
[Sample run success](https://github.com/blackboxsw/cloud-init/actions/runs/10398640974/job/28796270466?pr=24)

feat: add automation for ubuntu/* branches asserting quilt patches apply

---

ChangeLog
cloudinit/version.py

```
Release 24.3
Bump the version in cloudinit/version.py to 24.3 and
```
[Procedure followed](https://github.com/orgs/canonical/projects/29/views/1?pane=issue&itemId=21361535) and [public docs](https://github.com/canonical/uss-tableflip/blob/main/doc/upstream_release_process.md)
Verified health of jenkins integration runs on all supported releases focal++  and test platforms (lxd_vm/container, azure, ec2, gce)
upstream-snapshot 24.3 24.2

Release 24.3

---

config/cloud.cfg.tmpl

```
<bug>(azurelinux): update azurelinux cloud-init config 
- Update upstream cloud-init config template for azurelinux distro
- remove modules that not currently supported azurelinux
```

update azurelinux cloud-init config

---

debian/changelog
debian/cloud-init.lintian-overrides

See individual commits for context.
`build-package`

Oracular lintian fixes

---

ChangeLog
cloudinit/version.py

```
Release 24.3.1 (#5375)
Bump the version in cloudinit/version.py to 24.3.1 and update ChangeLog.
```
Sync ChangeLog and version.py from 24.3.x hotfix branch per hotfix process project docs https://github.com/orgs/canonical/projects/29?pane=issue&itemId=23587201

Release 24.3.1 (#5375)

---

cloudinit/sources/DataSourceSmartOS.py
cloudinit/sources/helpers/cloudsigma.py
requirements-all.txt
requirements.txt
tox.ini

https://warthogs.atlassian.net/browse/SC-1853
US120

Optional serial

---

.github/workflows/packaging-tests.yml

```
ci: fix packaging test when no patches
```

ci: fix packaging test when no patches

---

.github/labeler.yml
debian/changelog
debian/patches/no-single-process.patch
systemd/cloud-config.service.tmpl
systemd/cloud-final.service.tmpl
systemd/cloud-init-local.service.tmpl
systemd/cloud-init-network.service.tmpl
tests/integration_tests/util.py
tox.ini

Fix daily build recipe: Ubuntu/focal refresh patches

---

cloudinit/lifecycle.py

```
docs: fix typo in docstring
```

docs: fix typo in docstring

---

tests/integration_tests/modules/test_hotplug.py

```
test(hotplug): reenable vpc test in focal
After the fix for LP: 2055397 is released, we can re-enable this test. 
Add additional assertions to verify that every route has metrics
configured.
```
This change is blocked until https://launchpad.net/ubuntu/+source/systemd/245.4-4ubuntu3.24 leaves proposed.
```sh
#!/bin/bash
tox -e integration-tests -- --pdb tests/integration_tests/modules/test_hotplug.py::test_multi_nic_hotplug_vpc
```

test(hotplug): reenable vpc test in focal

---

cloudinit/config/schemas/schema-cloud-config-v1.json
doc/module-docs/cc_locale/data.yaml
doc/module-docs/cc_locale/example3.yaml
tests/unittests/config/test_cc_locale.py

```
fix(schema): Allow for locale: false in schema add tests
Also refactor and pytestify tests dropping use of
FilesystemMockingTestCase.
```

fix(schema): Allow for locale: false in schema add tests

---

.github/workflows/integration.yml

```
ci: fix integration test positional argument
```
DO NOT MERGE

Fix CI integration tests

---

tests/integration_tests/modules/test_version_change.py

```
test: Fix test_log_message_on_missing_version_file
This test has some questionable history that has been removed. The
main purpose of the test is to ensure that we get a log that the
python-version file is written if there's no pre-existing
python-version file but there is pre-existing pickle cache.
The invalid pickle at the beginning of the test complicated this test.
A normal boot will write a valid cache, so we should get no pickle
errors on reboot.
```

test: Fix test_log_message_on_missing_version_file

---

.github/ISSUE_TEMPLATE/config.yml
.github/workflows/cla.yml
CONTRIBUTING.md
README.md
cloudinit/analyze/__init__.py
cloudinit/cmd/main.py
cloudinit/net/network_state.py
doc/man/cloud-id.1
doc/man/cloud-init-per.1
doc/rtd/development/datasource_creation.rst
doc/rtd/links.txt
doc/summit/2023_summit_shared_notes.md
integration-requirements.txt
systemd/cloud-config.service.tmpl
systemd/cloud-final.service.tmpl
systemd/cloud-init-local.service.tmpl
systemd/cloud-init-network.service.tmpl
tests/unittests/analyze/test_boot.py

```
chore: update docs URLs to cloud-init.io
LP: #2032128
```
https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2032128

chore: update docs URLs to cloud-init.io

---

tests/integration_tests/util.py

```
test: make verify_clean_boot respect return code by environment
GH checks should now pass when run out of a pr event (as the post merge
event) while still work on prs and Jenkins.
```
https://github.com/canonical/cloud-init/commit/a9c6b1407714b70c11b72b1c32489dacf4bc4000
https://github.com/canonical/cloud-init/actions/runs/11073687167/job/30770781093
```sh
export CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE
export CLOUD_INIT_PLATFORM=lxd_container
tox -e integration-tests -- -vvv \
tests/integration_tests/modules/test_combined.py::TestCombined::test_deprecated_message \
tests/integration_tests/modules/test_users_groups.py::TestUsersGroups::test_user_root_in_secret \
tests/integration_tests/modules/test_users_groups.py::TestUsersGroups::test_nopassword_unlock_w …
```

test: make verify_clean_boot respect return code by environment

---

doc/rtd/tutorial/wsl.rst

```
docs: fix WSL tutorial
Install and start are no longer separate operations,
so update accordingly.
Fixes GH-5746
```

docs: fix WSL tutorial

---

tests/unittests/test_url_helper.py

```
test: bump timeout in test_order
```
I've seen this fail a few times now. Let's see if we can "fix" it by messing with timeouts
https://launchpadlibrarian.net/752095666/buildlog_ubuntu-noble-amd64.cloud-init_99.daily-202409301943-5133c838b~ubuntu24.04.1_BUILDING.txt.gz

test: bump timeout in test_order

---

tests/integration_tests/util.py
tox.ini

```
test: make verify_clean_boot really respect return code
```
* https://github.com/canonical/cloud-init/pull/5754
* Successful [build](https://github.com/aciba90/cloud-init/actions/runs/11122356882/job/30903458967) on my remote.

test: make verify_clean_boot really respect return code

---

config/cloud.cfg.tmpl

```
chore: Remove resize_root_tmp from cloud.cfg.tmpl
It was removed in ed8f1b1 .
Fixes GH-5786
```

chore: Remove resize_root_tmp from cloud.cfg.tmpl

---

tests/integration_tests/cmd/test_schema.py
tests/integration_tests/modules/test_apt_functionality.py
tests/integration_tests/modules/test_combined.py
tests/integration_tests/test_networking.py
tests/integration_tests/test_upgrade.py

```
test: Update integration tests from netplan backport
```
https://launchpad.net/ubuntu/+source/netplan.io/0.107.1-3ubuntu0.22.04.1

test: Update integration tests from netplan backport

---

.github/workflows/scheduled.yml
.github/workflows/unit.yml

```
chore: add 3.13 to PR CI runs, 3.14 to scheduled
```
3.13 released [last week](https://docs.python.org/3/whatsnew/3.13.html) ->

chore: add 3.13 to PR CI runs, 3.14 to scheduled

---

tools/build-on-freebsd

See: https://www.freshports.org/devel/py-pyyaml/

freebsd: adjust to match the new pyyaml package name

---

debian/changelog
debian/patches/grub-dpkg-support.patch
debian/patches/series

Will apply same patch to other downstreams if approved.

Ubuntu/oracular: revert disable grub-dpkg

---

.github/workflows/packaging-tests.yml

```
ci: fix packaging tests
Start with branch head and then merge main rather than vice versa.
Trying to merge the branch head was resulting in the commit not being
found.
Additionally, the check for the series file needed to be negated.
```

ci: fix packaging tests

---

tox.ini

```
ci: fix broken daily dependencies
```
https://github.com/canonical/cloud-init/actions/runs/11798968697/job/32866381927
tip-pylint and hypothesis_slow jobs fail to run due to missing dependencies

ci: fix broken daily dependencies

---

tests/integration_tests/reporting/test_webhook_reporting.py

```
test: Decrement expected webhook events
grub_dpkg was removed so that's one less event we should see
```

test: Decrement expected webhook events

---

tests/integration_tests/datasources/test_nocloud.py

```
test: Ensure unit ordering in ftp tests includes downstream units
```

test: Ensure unit ordering in ftp tests includes downstream units

---

cloudinit/sources/helpers/azure.py

```
fix: bump azure key size to 3072
For post 2030 FIPS 140-3 compliance for key size transition as per NIST SP 800-131A Rev. 2
and NIST SP 800-57 Part 1 Rev. 5. 
Per @xnox.
```
SRU Everywhere please :)
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf
https://nvlpubs.nist.gov/nistpubs/specialpublications/nist.sp.800-57pt1r5.pdf
Per @xnox

fix: bump azure key size to 3072

---

tools/.github-cla-signers

[X] I have signed the CLA: https://ubuntu.com/legal/contributors
Work on Gentoo + systemd support is upcoming...

Add myself to CLA signers file

---

packages/debian/control.in
tests/integration_tests/instances.py

```
ci: Add proper 'Breaks:' to integration testing simple deb
Also improve logging in deb install failure.
```

ci: Add proper 'Breaks:' to integration testing simple deb

---

cloudinit/distros/gentoo.py
tests/unittests/distros/test_gentoo.py

feat(gentoo): Add compatibility for Gentoo with systemd
Rebase please

feat(gentoo): Add compatibility for Gentoo with systemd

---

cloudinit/cmd/main.py
cloudinit/features.py
tests/integration_tests/datasources/test_nocloud.py
tests/integration_tests/modules/test_boothook.py
tests/unittests/cmd/test_main.py
tests/unittests/test_data.py
tests/unittests/test_features.py

```
chore: Add feature flag for manual network waiting
Controls the behavior added in e30549e for easier downstream patching
```

chore: Add feature flag for manual network waiting

---

test-requirements.txt
tests/integration_tests/conftest.py
tox.ini

Multiple logical commits. please rebase.
run the following and ensure a coverage report is spit out at the end:
```
tox -e py3-fast
```
run the following and ensure that multiple workers are collected (you can kill it early lol no need to let run. but if you do, observe how it only takes an hour or so instead of several hours!):
```
tox -e integration-tests-fast
```

Pytest fast improvements

---

cloudinit/config/cc_chef.py
cloudinit/config/schemas/schema-cloud-config-v1.json
tests/unittests/config/test_cc_chef.py
tools/.github-cla-signers

Related to [5090](https://github.com/canonical/cloud-init/issues/5090)
```
Corrected the path for chef Cache in cc_chef, schema-cloud-config-v1& test_cc_chef
```

Fix: corrects the path for Chef's cache

---

debian/changelog
debian/patches/no-single-process.patch

https://github.com/canonical/cloud-init/issues/6001

Ubuntu/jammy: wait for mounts

---

debian/changelog
debian/patches/no-single-process.patch

https://github.com/canonical/cloud-init/issues/6001

Ubuntu/noble: wait for mounts

---

.github/workflows/check_format.yml
.github/workflows/cla.yml
.github/workflows/packaging-tests.yml
.github/workflows/packaging-upstream.yml

https://github.com/canonical/cloud-init/pull/5964#issuecomment-2588334872

ci: do not merge in packaging test

---

tests/integration_tests/assets/dropins/cc_custom_module_24_1.py
tests/integration_tests/dropins/test_custom_modules.py

```
test: Ensure pre-24.2 custom modules work
```

test: Ensure pre-24.2 custom modules work

---

doc/rtd/reference/breaking_changes.rst

```
docs: document /usr merge breaking change
```

docs: document /usr merge breaking change

---

ChangeLog
cloudinit/version.py

Bump the version in cloudinit/version.py to 25.1 and update ChangeLog.

Release 25.1

---

debian/changelog
debian/control

~~I plan to upload this immediately if approved.~~
See https://github.com/canonical/cloud-init/pull/6053 for the hotfix

Ubuntu/devel: Add Azure metapackage

---

cloudinit/config/modules.py

```
fix: track more removed modules
```
I noticed warnings for these modules in a jammy log when debugging a separate issue. Jammy won't return 0 for these warnings, but noble (and other downstreams) can.

fix: track more removed modules

---

tests/integration_tests/modules/test_users_groups.py

```
test: make users/groups warning test release aware
Also, make the duplicated check a separate test.
```

test: make users/groups warning test release aware

---

tests/integration_tests/cmd/test_clean.py

```
test: check for correct logrotate config
```

test: check for correct logrotate config

---

cloudinit/sources/DataSourceAliYun.py

```
fix: Fix DataSourceAliYun exception_cb signature
Fixes GH-6066
```
Curious why mypy didn't catch this one. Pylance does.

fix: Fix DataSourceAliYun exception_cb signature

---

tests/integration_tests/datasources/test_nocloud.py

```
test: ensure NoCloud networking works on plucky
The NoCloud/LXD datasource we use for testing NoCloud uses an
invalid fallback network config. This results in
systemd-networkd-wait-online timeout. This wastes time everywhere, but
it also results in cloud-init returning error on plucky+ due to
cloud-init invoking wait-online manually.
This commit provides a more reasonable network config via NoCloud.
```

test: ensure NoCloud networking works on plucky

---

tests/integration_tests/test_signal_handler.py

```
test: remove script death check from test_signal_handler.py
Cloud-init gets killed but the runcmd script does not.
```

test: remove script death check from test_signal_handler.py

---

tests/integration_tests/modules/test_apt_functionality.py

```
test: ensure software-properties-common properly removed
```

test: ensure software-properties-common properly removed

---

tests/integration_tests/datasources/test_caching.py

```
test: fix errors in custom datasource networking
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-plucky-lxd_container-minimal/40/testReport/junit/tests.integration_tests.datasources/test_caching/test_no_cache_network_only/

test: fix errors in custom datasource networking

---

tests/integration_tests/modules/test_users_groups.py

```
test: warning on users/groups test is version specific
```

test: warning on users/groups test is version specific

---

tests/integration_tests/instances.py

The Oracle Cloud Agent holds the apt lock and causes the installation of the custom cloud-init source to fail. This adds a retry when the apt failure is due to a lock issue. This retry will retry for a total of 5 minutes before failing.
```
ci(oracle): fix issue installing cloud-init on custom image creation
The Oracle Cloud Agent holds the apt lock and causes the installation
of the custom cloud-init source to fail. This adds a retry when the 
apt failure is due to a lock issue. This retry will retry for a total
of 5 minutes before failing.
```

ci(oracle): fix issue installing cloud-init on custom image creation

---

tests/integration_tests/test_networking.py

```
test: move to has_netplanlib() in test_networking.py
```

test: move to has_netplanlib() in test_networking.py

---

tests/integration_tests/modules/test_keys_to_console.py

```
test: update keys_to_console timeout
```
It fails intermittently

test: update keys_to_console timeout

---

tests/integration_tests/test_networking.py

another one
```
test: replace version check with has_netplanlib()
```

test: replace version check with has_netplanlib()

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/sources/test_azure.py

```
fix(Azure): don't reraise FileNotFoundError during ephemeral setup
```

fix(Azure): don't reraise FileNotFoundError during ephemeral setup

---

.github/PULL_REQUEST_TEMPLATE.md
doc/rtd/development/contribute_code.rst
doc/rtd/development/contribute_docs.rst
doc/rtd/development/index.rst

```
chore: remove remaining references to .github-cla-signers
```

chore: remove remaining references to .github-cla-signers

---

ChangeLog
cloudinit/version.py

cherry-pick of the 25.1.1 release commit

Release 25.1.1

---

debian/changelog
debian/control

Ubuntu/oracular 24.4.x

---

systemd/cloud-init-local.service.tmpl

In cases where small images are being built and auditd is enabled it is possible that auditd complains before cloud-init has a chance to resize the disk. Make auditd wait until we are done.
```
72 characters.
```

Make auditd wait

---

cloudinit/sources/azure/errors.py
tests/unittests/sources/azure/test_errors.py

```
fix(azure): update ReportableErrorUnhandledException error
Since traceback_base64 is often truncated in Azure, this PR reverses the lines
before encoding it to base64 to get the most important parts.
```

fix(azure): update ReportableErrorUnhandledException error

---

doc/rtd/reference/network-config-format-v2.rst

```
docs: clarify examples for network addresses/gateway
While skimming the docs, I missed the example for addresses / gateway
because most of the examples use a code block, and these ones were
inline.
```

docs: clarify examples for network addresses/gateway

---

ChangeLog
cloudinit/url_helper.py
cloudinit/version.py
tests/unittests/sources/test_maas.py

cherry pick MAAS datasource fix, update changelog, and bump version number.

Release 25.1.2

---

cloudinit/sources/DataSourceNoCloud.py
doc/examples/cloud-config-datasources.txt

```
Revert "chore: Deprecate partially supported system config (#5515)"
This reverts commit 16a31981259fca3c34c15ad71666f6e9c4077ef9.
A common raspberry pi use case is to keep the NoCloud metadata at
the root of the boot partition, so using a 'cidata' labeled filesystem
isn't a viable option.
LP: #2100232
```

Revert "chore: Deprecate partially supported system config (#5515)"

---

cloudinit/cmd/main.py
tests/unittests/cmd/test_main.py

A user can generate a traceback by using to level options without specifying a subcommand, for example cloud-init --debug generates such a traceback. Catch the exception that generates the traceback and provide the user with a descriptive error message.
```
72 characters.
```

No traceback on command line error

---

doc/rtd/reference/examples.rst

```
docs: remove monospace formatting from SSH instance keys section heading
The section heading for "Configure instance's SSH keys" is inexplicably set to monospace.  This change makes it match the normal formatting of the other sections.
```

remove monospace formatting from section heading

---

cloudinit/config/cc_ansible.py
tests/integration_tests/modules/test_ansible.py
tests/unittests/config/test_cc_ansible.py

```
Older ansible-pull CLI < 2.12 has a bug where multiple playbooks
are not run by the command line client although the CLI allows
specifying multiple playbooks.
To avoid this on older versions of ansible-pull, make individual
ansible-pull calls with each playbook if multiple are provided in
loud-config.
Update integration tests
```
CLOUD_INIT_OS=plucky tox -e integration-tests --  tests/integration_tests/modules/test_ansible.py::test_ansible_pull_distro
CLOUD_INIT_OS=oracular tox -e integration-tests --  tests/integration_tests/modules/test_ansible.py::test_ansible_pull_distro
```

fix: ansible-pull multiple playbooks on older ansible ver < 2.12

---

tests/unittests/test_dmi.py

```
test: remove FilesystemMockingTestCase from test_dmi.py
```

test: remove FilesystemMockingTestCase from test_dmi.py

---

tests/unittests/test_util.py

```
test: remove FilesystemMockingTestCase from test_util.py
```

test: remove FilesystemMockingTestCase from test_util.py

---

tests/unittests/config/test_cc_apk_configure.py

```
test: remove FilesystemMockingTestCase from test_cc_apk_configure.py
```

test: remove FilesystemMockingTestCase from test_cc_apk_configure.py

---

tests/integration_tests/reaper.py

```
test: pre-fetch instance id when logging from reaper
After deletion the instance id is no longer available.
```

test: pre-fetch instance id when logging from reaper

---

conftest.py
tests/unittests/conftest.py
tests/unittests/distros/package_management/test_apt.py
tests/unittests/sources/test_maas.py
tests/unittests/test_helpers.py

```
test: Consolidate use of paths fixture
Move it to tests/unittests/conftets.py and substitute MockPaths with it.
```

test: Consolidate use of paths fixture

---

tests/unittests/config/test_cc_disk_setup.py
tests/unittests/config/test_cc_keyboard.py
tests/unittests/config/test_cc_mcollective.py
tests/unittests/config/test_cc_resizefs.py
tests/unittests/config/test_cc_resolv_conf.py
tests/unittests/config/test_cc_runcmd.py
tests/unittests/config/test_cc_update_etc_hosts.py
tests/unittests/config/test_cc_write_files.py
tests/unittests/config/test_cc_write_files_deferred.py
tests/unittests/config/test_cc_yum_add_repo.py
tests/unittests/config/test_cc_zypper_add_repo.py
tests/unittests/conftest.py

```
test: drop FilesystemMockingTestCase from cc tests
```

test: drop FilesystemMockingTestCase from cc tests

---

doc/rtd/explanation/hardening.rst
doc/rtd/explanation/index.rst

```
doc(ssdlc): Add hardening page
```

doc(ssdlc): Add hardening page

---

doc/rtd/explanation/format.rst

```
docs: clarify what #include can include
The description includes `both base config and meta config`, but those
terms aren't defined in the page, and can be thought to refer to
the base config and meta-data configuration formats rather than
user-data. Since the description already says "any kind of
user-data format", just remove the clarification.
```

docs: clarify what #include can include

---

tests/unittests/conftest.py
tests/unittests/distros/test__init__.py
tests/unittests/distros/test_bsd_utils.py
tests/unittests/helpers.py
tests/unittests/runs/test_merge_run.py
tests/unittests/runs/test_simple_run.py
tests/unittests/sources/test_azure.py
tests/unittests/sources/test_azure_helper.py
tests/unittests/sources/test_configdrive.py
tests/unittests/sources/test_ibmcloud.py
tests/unittests/test__init__.py

```
test: drop some FilesystemMockingTestCases
#5760
```
#5760

test: drop some FilesystemMockingTestCases

---

tests/unittests/sources/test_smartos.py

GH-5760
```
test: drop FilesystemMockingTestCase in smartos
GH-5760
```

test: drop FilesystemMockingTestCase in smartos

---

doc/rtd/reference/breaking_changes.rst
doc/rtd/spelling_word_list.txt

```doc: detailed examples of openstack config alternatives for non-x86 images```

doc: detailed examples of openstack config alternatives for non-x86 images

---

tests/unittests/analyze/test_boot.py

```
test: drop citestcase from analyze tests
```

test: drop citestcase from analyze tests

---

integration-requirements.txt
tests/integration_tests/clouds.py
tests/integration_tests/conftest.py
tests/integration_tests/instances.py
tests/integration_tests/reaper.py
tests/integration_tests/test_reaper.py

There's multiple commits here that can be reviewed separately. Let me know if you'd prefer separate PRs (jj makes that a lot easier)
- [] Squash merge using "Proposed Commit Message"

Allow running integration tests in parallel

---

.github/workflows/packaging-upstream.yml

```
ci: update patch checking to use current supported releases
```
https://github.com/canonical/cloud-init/actions/runs/16329313756

ci: update patch checking to use current supported releases

---

tests/unittests/config/test_cc_rh_subscription.py
tests/unittests/config/test_cc_snap.py
tests/unittests/config/test_cc_users_groups.py
tests/unittests/config/test_cc_wireguard.py
tests/unittests/config/test_cc_write_files.py
tests/unittests/config/test_schema.py
tests/unittests/helpers.py

```
test: drop citestcase from rest of config tests
```

test: drop citestcase from rest of config tests

---

cloudinit/analyze/__init__.py
pyproject.toml

```
fix: fixed defs types in cloudinit analyze
```

fixed defs types in cloudinit analyze

---

cloudinit/sources/DataSourceAzure.py
tests/unittests/sources/test_azure.py

```
feat(azure): Implement the clean callback for DataSourceAzure
When the user runs 'cloud-init clean -c datasource' or 'cloudinit clean -c all' command for Azure DataSouce,
it would remove the azure resource disk line in /etc/fstab. 
```
It is based on PR #6100
Fixes  https://issues.redhat.com/browse/RHEL-82988
Issue description
If use 'cloud-init clean --config all' to deprovision VM and prepare it as a generalized image, then use it to create a VM in a size without resource disk, the mount will fail, which impacts some other services that use mount as dependency, e.g. nfs-server.
1. Create a VM on Azure DS1_v2 size.(has resource disk)
2. Run 'cloud-init clean --config all' to deprovision the VM.
3. grep 'azure' /etc/fstab
4. Got the expected result: No …

feat(azure): Implement the clean callback for DataSourceAzure

---

cloudinit/net/activators.py
cloudinit/net/eni.py
cloudinit/net/netplan.py
cloudinit/net/network_manager.py
cloudinit/net/networkd.py
cloudinit/net/renderers.py
pyproject.toml
tests/unittests/test_net_activators.py

```
chore: add typing to cloudinit.net.eni
GH-5445
Signed-off-by: Alberto Contreras <alberto.contreras@canonical.com>
```
GH-5445

chore: add typing to cloudinit.net.eni

---

cloudinit/analyze/dump.py
pyproject.toml

```
fix: fixed defs types in cloudinit analyze dump
```

fix: fixed defs types in cloudinit analyze dump

---

tests/unittests/sources/test_cloudsigma.py
tests/unittests/sources/test_configdrive.py
tests/unittests/sources/test_digitalocean.py

```
test: drop citestcase from c and d sources
```

test: drop citestcase from c and d sources

---

tests/unittests/sources/test_gce.py
tests/unittests/sources/test_hetzner.py

```
test: drop citestcase from g and h sources
```

test: drop citestcase from g and h sources

---

tests/integration_tests/modules/test_ssh_keysfile.py

```
test: relax checks on authorized keys
Check that the expected keys exist rather than enforcing a specific
number of keys. Additional authorized keys that have not been specified
in user data may be added to the default and root accounts. This 
includes keys specified at launch and may vary in number.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-gce-generic/287/#showFailuresLink

test: relax checks on authorized keys

---

ChangeLog
cloudinit/version.py

```
Release 25.2
Bump the version in cloudinit/version.py to 25.2 and
```

Release 25.2

---

tests/unittests/sources/test_nwcs.py
tests/unittests/sources/test_opennebula.py
tests/unittests/sources/test_openstack.py
tests/unittests/sources/test_ovf.py

```
test: drop citestcase from n and o sources
```

test: drop citestcase from n and o sources

---

tests/unittests/sources/test_vultr.py
tests/unittests/sources/vmware/test_custom_script.py
tests/unittests/sources/vmware/test_guestcust_util.py
tests/unittests/sources/vmware/test_vmware_config_file.py

```
test: drop citestcase from v sources
```

test: drop citestcase from v sources

---

cloudinit/sources/DataSourceScaleway.py
tests/unittests/sources/test_rbx.py
tests/unittests/sources/test_scaleway.py
tests/unittests/sources/test_upcloud.py

```
test: drop citestcase from r, s and u sources
```

test: drop citestcase from r, s and u sources

---

tests/unittests/test_simpletable.py
tests/unittests/test_subp.py

```
test: drop citestcase from s* tests
```

test: drop citestcase from s* tests

---

tests/unittests/test_util.py

```
test: drop citestcase from test_util.py
```

test: drop citestcase from test_util.py

---

tests/unittests/test_net_freebsd.py

```
test: drop citestcase net_freebsd
```

test: drop citestcase net_freebsd

---

tests/unittests/cmd/test_clean.py

```
fix: add missing test mock
When files exist in /etc/cloud/clean.d, unittests fail due to a missing mock.
```
Blocks https://github.com/canonical/cloud-init/pull/6326

fix: add missing test mock

---

tests/unittests/test_temp_utils.py
tests/unittests/test_templating.py

```
test: drop citestcase from t* tests
```

test: drop citestcase from t* tests

---

cloudinit/analyze/dump.py
cloudinit/cmd/main.py
cloudinit/config/cc_disk_setup.py
cloudinit/config/cc_mounts.py
cloudinit/log/loggers.py
cloudinit/net/netplan.py
cloudinit/net/networkd.py
cloudinit/net/sysconfig.py
cloudinit/sources/DataSourceAliYun.py
cloudinit/sources/DataSourceAzure.py
cloudinit/sources/DataSourceCloudStack.py
cloudinit/sources/DataSourceOracle.py
cloudinit/url_helper.py
tools/test_tools.py
tox.ini

```
chore(ci): fix cloud-init test failures from new pylint
```
~~Blocked by https://github.com/canonical/cloud-init/pull/6406~~
After this change, `tox -e tip-pylint - cloudinit/ tools/` passes cleanly. This doesn't bump pylint CI version because files under `tests/` still have pylint warnings.

chore(ci): fix cloud-init test failures from new pylint

---

tests/unittests/net/test_dhcp.py

```
test: drop citestcase from net/test_dhcp.py
```

test: drop citestcase from net/test_dhcp.py

---

CONTRIBUTING.md
README.md
SECURITY.md
doc/rtd/development/code_review.rst
doc/rtd/development/contribute_docs.rst
doc/rtd/development/find_issues.rst
doc/rtd/development/first_PR.rst
doc/rtd/development/index.rst
doc/rtd/howto/ubuntu_test_prerelease.rst
doc/rtd/index.rst
doc/rtd/links.txt
doc/rtd/reference/faq.rst
doc/rtd/reference/ubuntu_stable_release_updates.rst

```
see individual commits
```

Migrate to new communication platforms

---

tests/unittests/test_version.py

```
test: drop citestcase from test_version.py
```

test: drop citestcase from test_version.py

---

cloudinit/cmd/devel/make_mime.py

```
fix: fixed defs types in cloud-init cmd devel make_mime
```

fixed defs types in cloud-init cmd devel make_mime

---

cloudinit/config/schemas/schema-cloud-config-v1.json
doc/module-docs/cc_phone_home/data.yaml

I'm working on terraform provider for cloud-init, thus reading cloud-init documentation a lot. Noticed this typos in modules:
- [phone-home](https://cloudinit.readthedocs.io/en/latest/reference/modules.html#phone-home)
- [update-etc-hosts](https://cloudinit.readthedocs.io/en/latest/reference/modules.html#update-etc-hosts)
```
fix(docs): Fix typo in `fDQn`
72 characters.
```

fix(docs): Fix typo in `fDQn`

---

cloudinit/config/cc_raspberry_pi.py
cloudinit/config/schemas/schema-cloud-config-v1.json

```
feat(cc_raspberry_pi): Remove remote_gpio interface
Removes the remote_gpio interface option from the
cc_raspberry_pi configuration module.
```
@tdewey-rpi, @lurch

feat(cc_raspberry_pi): remove remote_gpio interface

---

.github/workflows/stale.yml
doc/rtd/development/first_PR.rst

```
chore: hand off responsibilities
The faults of incompetent abilities will be consigned to oblivion
```

chore: hand off responsibilities

---

systemd/cloud-init-local.service.tmpl

```
fix(systemd): revert auditd.service dependency
RHBZ: 2390898
```
https://github.com/canonical/cloud-init/pull/6423

fix(systemd): revert auditd.service dependency

---

cloudinit/config/schema.py
tests/unittests/config/test_schema.py

```
feat(schema): add support for the not keyword
Refs GH-6468
```
Pushed a commit with just the tests so that it fails the CI then will push another commit with the code fix

feat(schema): add support for the not keyword

---

cloudinit/config/cc_rh_subscription.py
cloudinit/config/schemas/schema-cloud-config-v1.json
doc/module-docs/cc_rh_subscription/data.yaml
doc/module-docs/cc_rh_subscription/example2.yaml
doc/module-docs/cc_rh_subscription/example3.yaml
tests/unittests/config/test_cc_rh_subscription.py

```
chore(cc_rh_subscription): deprecate hyphenated fields, remove self.log
Refs GH-6370
```

chore(cc_rh_subscription): deprecate hyphenated fields, remove self.log
