- cloudinit/sources/DataSourceMAAS.py
- tests/unittests/sources/test_common.py
- tests/unittests/sources/test_maas.py
```
Make MAAS a local data source
The existing datasource works for ephemeral deployments
(booting over the network). When adapted to run during 
local timeframe, the initramfs brings up the initial
networking.
However, when the system boots from disk initramfs doesn’t bring
up the networking, which means that cloud-init will try to get
the metadata before network is actually up.
The motivation for this change is to support network configuration
for non-Ubuntu operating systems.
```
https://warthogs.atlassian.net/browse/MAASENG-2140
> Maas disregard initramfs

- Makefile
- doc/summit/2023_summit_shared_notes.md
Store our cloud-init summit notes somewhere accessible without a google account
```
Provide an unauthenticated view of meeting notes for those without google accounts.  Original meeting notes live in a shared google drive document. To provide a point of reference for those in the community without google accounts we have refactored the notes to markdown and will host them in the cloud-init repository so that both discourse trip reports and mailinglist threads can reference these notes without have to bloat the email or discourse post with details.
```
> summit-notes: add 2023 notes for reference in mailinglist/discourse

- cloudinit/handlers/boot_hook.py
- tests/integration_tests/modules/test_boothook.py
- tests/integration_tests/test_multi_part_user_data_handling.py
- tests/unittests/test_builtin_handlers.py
```
boothook: allow stdout/stderr to emit to cloud-init-output.log
Fixes GH-3016
```
```
./tools/run-container --package ubuntu/mantic
CLOUD_INIT_CLOUD_INIT_SOURCE=cloud-init.*bddeb_all.deb CLOUD_INIT_OS_IMAGE=mantic tox -e integration-tests tests/integration_tests/test_multi_part_user_data_handling.py::test_cloud_config_archive_boot_hook_logging
```
> boothook: allow stdout/stderr to emit to cloud-init-output.log

- doc/rtd/explanation/boot.rst
- doc/rtd/reference/datasources/configdrive.rst
```
Clarify boothook docs
```
See commit messages for explanations
> Clarify boothook docs

- cloudinit/sources/azure/imds.py
- tests/unittests/sources/azure/test_imds.py
When retrying to fetch metadata from IMDS there is a backoff for logging to avoid flooding the logs.  In the current implementation we have to wait until the next backoff log to see the transition.
Always log when the current error does not match the previous one.
> azure/imds: ensure new errors are logged immediately when retrying

- cloudinit/cmd/main.py
- cloudinit/cmd/status.py
- doc/man/cloud-init.1
- tests/integration_tests/cmd/test_status.py
- tests/unittests/cmd/test_cloud_id.py
- tests/unittests/cmd/test_status.py
(Rebase merge)
See individual commit messages for details.
[Design spec](https://discourse.ubuntu.com/t/spec-improve-error-and-warning-visibility/39765)
- Docs to come in a followup PR, based on the commit message of https://github.com/canonical/cloud-init/pull/4500/commits/bbf644dda50452195c0ba8c6c9c6ec4db0bc2759.
> Add cloud-init degraded state and machine readable degraded errors to cloud-init status

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/errors.py
- tests/unittests/sources/test_azure.py
Azure requires the use of the primary interface to query IMDS and report ready to wireserver.  If we determine that the interface is not the primary interface, report the failure to the host.
The exception is when iterating over hotplugged NICs in the Savable PPS scenario.  In this case the secondary may be enumerated first and we would expect a failure.
> azure: report failure to host if ephemeral DHCP was on a secondary NIC

- cloudinit/config/schema.py
- tests/integration_tests/cmd/test_schema.py
- tests/integration_tests/modules/test_cli.py
```
*  tests: fix schema test expected cli output Valid schema <type>
*   fix(schema cli): check raw userdata when processed cloud-config empty
The processed userdata file /var/lib/cloud/instance/cloud-config.txt
will be empty when invalid user-data headers are declared.
When cloud-init schema --system finds an empty
/var/lib/cloud/instance/cloud-config.txt prefer to validate a
non-empty unprocessed raw userdata file at
/var/lib/cloud/instance/user-data.txt.
This allows the CLI to provide actionable error messages about
unsupported header declarations in raw userdata.
```
Fix [Jenkins job]( integration test failures:
-  commit 1: one behavioral regression in `cloud-init schema --system` not reporting invalid user-data header types …
> fix schema integration test regressions: invalid header and expected output from schema --system CLI

- debian/patches/do-not-block-user-login.patch
```
Commit f17b889d unintentionally redacted the second part of the changeset moving Before=systemd-user-sessions.service from cloud-config.service back into cloud-init.service.
Replace the dropped patchset.
```
test that daily recipe builds will build effetively:
```
git merge blackboxsw/ubuntu/devel
quilt push -a; git diff; quilt pop -a
build-package
sbuild --dist=mantic --arch=amd64 --arch-all ../out/cloud-init_23*dsc
```
Additional branches for:
* [focal](https://github.com/canonical/cloud-init/compare/ubuntu/focal...blackboxsw:cloud-init:ubuntu/focal)
* [jammy](https://github.com/canonical/cloud-init/compare/ubuntu/jammy...blackboxsw:cloud-init:ubuntu/jammy)
* [lunar](https://github.com/canonical/cloud-init/compare/ubuntu/lunar...blackboxsw:cloud-init:ubuntu/lunar)
> fix d/p/do-not-block-user-login.patch

- tests/integration_tests/modules/test_cli.py
```
tests: fix integration test expectations of exit 2 on schema warning
Commit 70acb7f2a introduced exit code 2 for schema warnings.
Update cli integration tests to expect return_code == 2 on invalid
schema.
```
Failed jenkins job: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-mantic-lxd_container/102/
```
CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily CLOUD_INIT_OS_IMAGE=jammy tox -e integration-tests  tests/integration_tests/modules/test_cli.py
```
> Test fix warning error codes

- cloudinit/sources/azure/errors.py
- tests/unittests/sources/azure/test_errors.py
Include the failing code in the reason to make it more prominent.
> azure/errors: include http code in reason for IMDS failure

- cloudinit/util.py
- tests/unittests/test_util.py
Follow up of https://github.com/canonical/cloud-init/pull/4477
The chances of ds-idenfy being affected by this issue are very small, as it searches for the presence of `cc:` and `datasource_list` and if so parses the array following `datasource_list`. See, https://github.com/canonical/cloud-init/blob/14b76c4448e817570699421b27e234d60cf40bbb/tools/ds-identify#L591
I think this change is sufficient as cloud-configs contained in kernel cmdline are expected to be fairly simple, and even if a `cc:` would be needed within a `cc: end_cc`, then that `cc:` could be url-encoded bypassing this problem.
> fix(cmdline): fix cmdline parsing with MAC containing cc:

- cloudinit/config/cc_apt_pipelining.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_apt_pipelining.py
Deprecate extra option values, correct docs.
f2f530e59
> cc_pipeline_apt fix invalid claim

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
There are Azure Stack implementations which do not support IMDS.  The only way to detect this is by checking for the presence of the static route to IMDS.  If we don't see the route to IMDS, limit the failure report to the host via KVP.
There will be future work to detect that we are running on Azure Stack and have explicit configuration passed along via ovf-env.xml to toggle IMDS support as the environment dictates.
- refactor _check_if_primary() to track configured routes
- use this to toggle reporting behavior
- add duration check to TestGetMetadataFromImds tests in case we want to toggle duration in the future.
Example diagnostic on Azure public cloud:
```
2023-10-27 12:37:04,634 - azure.py[DEBUG]: Obtained DHCP lease on interface 'eth0' (primary=True driver='hv_netvsc' …
```
> azure: workaround to disable reporting IMDS failures on Azure Stack

- .github/workflows/check_format.yml
- tools/ds-identify
Add shellcheck to CI
Fixes GH- #4453  
@TheRealFalcon 
After finding bug in the systemd-generator script, I have added shellcheck for ds-identify script and system-generator script can be integrated later on in the CI. 
Please review my PR. Any changes suggested by the maintainers are welcome!
> [enhancement]: Add shellcheck to CI

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/imds.py
- tests/unittests/sources/azure/test_imds.py
- tests/unittests/sources/test_azure.py
Drop the limit for connection errors if a route to IMDS is detected. Since we know we've brought up the primary NIC and connectivity should work, continue to retry until retry_deadline is up.
If there is no route to IMDS detected, such as Azure Stack, keep the current limit of 11.
Fetching reprovision data behavior is unchanged.
> azure/imds: remove limit for connection errors if route present

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/errors.py
- tests/unittests/sources/azure/test_errors.py
- tests/unittests/sources/test_azure.py
```
azure: Check for stale pps data from IMDS
After reprovisioning, IMDS should return None value for PPS data
type.
Introduce a check to verify it IMDS is returning stale-PPS
data. In case of stale data, report the error to the host and allow
the VM to continue with provisioning. This is part of a larger effort
to improve error handling and error reporting during VM provisioning.
```
After reprovisioning, IMDS should return None value for PPS data type. This PR introduces a check to verify if IMDS is returning stale PPS data. In case of stale data, error will be reported to the host and VM will continue with provisioning.
This is a part of a large larg
> azure: Check for stale pps data from IMDS

- cloudinit/config/schema.py
> Actually validate or tell user we cannot

- cloudinit/net/sysconfig.py
- tests/unittests/test_net.py
```
net: Fix DHCPv4 not enabled on SUSE in some cases
```
Fix follow issue:
```
#cloud-config
datasource_list: [NoCloud]
network:
version: 1
config:
- type: physical
name: eth0
mac_address: 56:00:04:a2:c5:f0
subnets:
- type: dhcp
- type: ipv6_dhcpv6-stateful
```
cloud-init devel net-convert -p test.cfg -k yaml -d out -O sysconfig -D opensuse
cat out/etc/sysconfig/network/ifcfg-eth0
```
#
BOOTPROTO=dhcp6         # this shuold be dhcp
DHCLIENT6_MODE=managed
LLADDR=56:00:04:a2:c5:f0
STARTMODE=auto
```
> net: Fix DHCPv4 not enabled on SUSE in some cases

- cloudinit/cmd/main.py
- cloudinit/log.py
- cloudinit/util.py
```
main: Don't call logging too early
A deprecate log was called before logging was set up. Fix it.
```
> Fix deprecated log

- cloudinit/stages.py
- cloudinit/util.py
- tests/unittests/test_stages.py
- tests/unittests/test_util.py
Since cloud-init still redacts sensitive information from `/var/log/cloud-init.log`, there is no way to expose a secure system (no CVE). However, https://github.com/canonical/cloud-init/pull/4250 weakens our mitigation of restricting logs by allowing more permissive log permissions. Revert that commit and implement the behavior it was trying to introduce.
> Fix permissions issue

- cloudinit/net/ephemeral.py
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-ec2/348/testReport/junit/tests.integration_tests.datasources/test_ec2_ipv6/test_dual_stack/
[cloud-init-test.log](https://github.com/canonical/cloud-init/files/13503657/cloud-init-test.log)
> fix(test): Fix expected log for ipv6-only ephemeral network

- tools/.github-cla-signers
- tools/build-on-openbsd
fix: Update build-on-openbsd dependencies
* script would fail will needing to do work with python netifaces
module.
* linting: SC2806 -  Double quote to prevent globbing and word
splitting.
> Update build-on-openbsd dependencies

- cloudinit/stages.py
- tests/integration_tests/datasources/test_none.py
- tests/integration_tests/util.py
- tests/unittests/helpers.py
- tests/unittests/runs/test_simple_run.py
- tests/unittests/test_stages.py
```
bug(schema): write network-config if instance dir present (#4635)
Only write /var/lib/cloud/instance/network-config.json once
datasource is detected. The /var/lib/clound/instance symlink is
created by Init.instancify after datasource detection is complete.
Move creation of /var/lib/cloud/instance/network-config.json into
it's own method _write_network_config_json. It will be called by
any call to apply_network_config.
apply_network_config is called in both Local and Network stages.
In Local stage, apply_network_config is used to either:
- render the final network config of datasource detected in Local
- in absence of Local datasource, render basic fallback DHCP on
primary NIC to allow network to come up before detecting a
Network datasource
For Network datasources, they will not have …
```
> bug(schema): do not write network-config when instance dir absent

- cloudinit/sources/helpers/azure.py
I recently noticed some images do not include `eject` and this failure is lost in the debug messages.  Raising it to error to improve visibility of the error.
Given that the media may contain the plain-text admin password, we strongly prefer to eject it as soon as possible from within the VM.  If the media is not ejected by the client, the host will do so with some delay when cloud-init reports ready/failure to WireServer.
> azure: report failure to eject as error instead of debug

- cloudinit/sources/DataSourceAliYun.py
- tests/unittests/sources/test_aliyun.py
- tests/unittests/sources/test_common.py
- tools/.github-cla-signers
```
feat: Allow aliyun ds to fetch data in init-local
In Alibaba Cloud environment, cloud-init supports fetching data before the network services start.
```
> feat: Allow aliyun ds to fetch data in init-local

- tests/integration_tests/datasources/test_none.py
```
tests: increase number of retries across reboot to 90
```
Failure seen in jenkins after 30 retries
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-gce/lastSuccessfulBuild/testReport/tests.integration_tests.datasources/test_none/test_datasource_none_discovery/
> tests: increase number of retries across reboot to 90

- cloudinit/config/cc_keys_to_console.py
- cloudinit/config/cc_phone_home.py
- cloudinit/config/cc_ssh.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- cloudinit/ssh_util.py
- doc/examples/cloud-config-ssh-keys.txt
- doc/examples/cloud-config.txt
- tests/data/merge_sources/expected9.yaml
- tests/data/merge_sources/source9-1.yaml
- tests/integration_tests/modules/test_keys_to_console.py
- tests/integration_tests/modules/test_ssh_auth_key_fingerprints.py
- tests/integration_tests/modules/test_ssh_generate.py
- tests/integration_tests/modules/test_ssh_keys_provided.py
- tests/unittests/config/test_cc_phone_home.py
- tests/unittests/config/test_cc_ssh.py
- tests/unittests/test_ssh_util.py
- tools/mock-meta.py
OpenSSH 7.0 and greater similarly disable the ssh-dss (DSA) public key algorithm. It too is weak and we recommend against its use. 
refer:https://www.openssh.com/legacy.html
However, cloud-init still generates the DSA key.  It is recommended that cloud-init disable dsa
> delete DSA support

- bash_completion/cloud-init
- cloudinit/cmd/main.py
- doc/man/cloud-init.1
- doc/rtd/reference/cli.rst
- tests/unittests/cmd/test_main.py
We are currently not parsing the subcommands correctly. 
This causes the high-level arguments to make parsing of subcommand be erroneous.
Fixes
LP: #2040325
The steps listed in [this LP bug](https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2040325) are sufficient and well explained.
> fix(cli): fix parsing of argparse subcommands

- cloudinit/config/cc_ansible.py
- cloudinit/config/cc_apt_configure.py
- cloudinit/config/cc_bootcmd.py
- cloudinit/config/cc_growpart.py
- cloudinit/config/cc_seed_random.py
- cloudinit/config/cc_snap.py
- cloudinit/config/cc_ssh.py
- cloudinit/distros/bsd.py
- cloudinit/distros/freebsd.py
- cloudinit/distros/netbsd.py
- cloudinit/distros/openbsd.py
- cloudinit/distros/package_management/apt.py
- cloudinit/handlers/boot_hook.py
- cloudinit/subp.py
- cloudinit/util.py
- tests/unittests/config/test_apt_configure_sources_list_v1.py
- tests/unittests/config/test_apt_configure_sources_list_v3.py
- tests/unittests/config/test_apt_source_v1.py
- tests/unittests/config/test_apt_source_v3.py
- tests/unittests/config/test_cc_ansible.py
- tests/unittests/config/test_cc_growpart.py
- tests/unittests/config/test_cc_seed_random.py
- tests/unittests/config/test_cc_snap.py
- tests/unittests/distros/package_management/test_apt.py
- tests/unittests/test_subp.py
Improve code quality and reduce maintenance burden by removing boilerplate, old unused copy-pasted code, and redundant features. Update code to use current Python3 features. Add typing information to subp args. This PR reduces code complexity, improves static analysis via typing, and eliminates the need to test internal features that we didn't even use.
> subp cleanup and typing

- packages/brpm
- packages/redhat/cloud-init.spec.in
```
fix(copr): Multiple fixes to allow COPR builds
Correct syntax error and typo in packages/brpm and remove unneeded
TODO.rst reference from packages/redhat/cloud-init.spec.in.
```
Successful build with these additional two commits: https://copr.fedorainfracloud.org/coprs/g/cloud-init/el-testing/build/6726068/
`bash -x ./tools/run-container --source-package --unittest --artifacts=./srpm/ rockylinux/8`
> fix(packages/brpm): correct syntax error and typo

- packages/bddeb
- packages/brpm
- pyproject.toml
- tox.ini
A followup to d798bb5e09a4e8caf2c3900042ee9ab51409140b.
```
style(brpm/bddeb): add black and ruff for packages build scripts (#4666)
Add packages/brpm and bddeb to both black and ruff tox targets.
Apply style/formatting changes do_format changes to packags/brpm and
packages/bddeb.
```
> style(brpm/bddeb): add black and ruff for packages build scripts

- cloudinit/sources/DataSourceAzure.py
Use the commit message
Without this change, CI unittests [failed on Python 3.13](https://github.com/canonical/cloud-init/actions/runs/7103603744/job/19336679815). With this change, [tests succeed](https://github.com/canonical/cloud-init/actions/runs/7106053767/job/19344642252?pr=4567).
> Fix cloud-init for Python 3.13

- cloudinit/net/__init__.py
- cloudinit/net/network_manager.py
- tests/unittests/net/test_init.py
- tests/unittests/test_net.py
Please see discussions in https://github.com/canonical/cloud-init/pull/4474 .
The second patch unreverts the revert https://github.com/TheRealFalcon/cloud-init/commit/21e6dfb8298835e93e5a11e6185574e611a1f44b .
The first change tries to the fix the issue due to which the above reversal was made. 
```
If "may-fail" is set to False in the Network Manager keyfile for both ipv4
and ipv6, it essentially means both ipv4 and ipv6 network initialization must
succeed for the overall network configuration to succeed. This means, for
environments where only ipv4 or ipv6 is available but not both and we need to
configure both ipv4 and ipv6 options, the overall network configuration will
fail. This is not what we want. When both ipv4 and ipv6 are configured,
it is enough for the overall configuration …
```
> net/network_manager: do not set "may-fail" to False for both ipv4 and ipv6

- cloudinit/net/activators.py
- setup.py
- sysvinit/openbsd/cloudconfig.tmpl
- sysvinit/openbsd/cloudfinal.tmpl
- sysvinit/openbsd/cloudinit.tmpl
- sysvinit/openbsd/cloudinitlocal.tmpl
- tools/build-on-openbsd
```
fix(openbsd): services & build tool
* Added net/activator for `ifconfig` that is used with OpenBSD
* Added sysvinit scripts for OpenBSD
* Updated build-on-openbsd tool with additional dependencies and
better logic
```
> fix(openbsd): services & build tool

- cloudinit/stages.py
- tests/unittests/test_stages.py
Rebase
It's easier to increase test coverage by removing unused code than it is to add more tests :wink: 
- [] Squash merge using "Proposed Commit Message"
> Small stages.py refactors

- cloudinit/dmi.py
- tests/unittests/test_dmi.py
- tests/unittests/test_ds_identify.py
- tools/ds-identify
```
fix: add support for OpenBSD's native dmi reading
OpenBSD's sysctl provides the most important DMI data in
its `hw` hierarchy. Switch ds-identify and cloudinit.dmi to using it.
This means we can get rid of the dmidecode dependency, which
requires setting `kern.allowkmem=1` and a reboot before usage.
```
> dmi: support OpenBSD native reading 

- cloudinit/cmd/status.py
- tests/unittests/cmd/test_status.py
```
fix: Handle systemctl commands when dbus not ready
During `cloud-init status`, we check systemctl to ensure the status
we're reporting is accurate. However, we can get an error from systemctl
if dbus isn't ready yet. This commit will either ignore the error if we
can assume that cloud-init is still running, or retry until we get a
proper response from systemctl.
Fixes GH-4676
```
https://github.com/canonical/cloud-init/issues/4676
> fix: Handle systemctl commands when dbus not ready

- tests/unittests/cmd/devel/test_logs.py
```
fix(tests): make cmd/devel/tests work on non-GNU
The tests were tied to the exact output of GNU ls.
Tests were failing on *BSD.
Fix them by using a different platform independent command.
POSIX sh should work everywhere.
```
> fix(tests): make cmd/devel/tests work on non-GNU

- cloudinit/log.py
Using a logger name of `__name__` is useful to identify the source of a log.... Except when that source is named `__init__.py` because we have a few of those that contain lots of code. Use the module's directory name in that case.
> Make logger name more useful

- conftest.py
- tests/unittests/analyze/test_boot.py
- tests/unittests/sources/azure/test_errors.py
- tests/unittests/sources/azure/test_kvp.py
- tests/unittests/test_conftest.py
```
test: Fix silent swallowing of unexpected subp error
We throw an error when supb isn't mocked in a test. However, there
are many broad exception handlers that wind up swallowing the error.
This commit changes it from an AssertionError to a new error that
inherits from BaseException so that it doesn't get silently swallowed.
Also fix any tests that are impacted.
```
> test: Fix silent swallowing of unexpected subp error

- cloudinit/cmd/devel/render.py
- cloudinit/cmd/query.py
- cloudinit/config/cc_final_message.py
- cloudinit/config/schema.py
- cloudinit/handlers/__init__.py
- cloudinit/handlers/jinja_template.py
- cloudinit/templater.py
- cloudinit/util.py
- tests/unittests/cmd/devel/test_render.py
- tests/unittests/cmd/test_query.py
- tests/unittests/config/test_schema.py
- tests/unittests/test_cli.py
- tests/unittests/test_templating.py
- tests/unittests/test_util.py
```
feat(jinja): better jinja feedback and error catching
When an error is encountered while trying to parse a jinja template, the traceback is automatically parsed to get the specific error and the line number that caused this error, and then this information is turned into a user-friendly single-line error message. 
The cloud-init runtime will log these error messages when jinja syntax errors are encountered in the cloud-config file. For the query, render, and schema commands, the nasty traceback is caught and a single line error message is given to the user instead.
Fixes GH-4360
```
> SC-1603-jinja-enhancements

- setup.py
- tools/build-on-openbsd
```
fix(setup): Relocate libexec on OpenBSD
our setup.py didn't relocate our USR_LIB_EXEC path on OpenBSD.
Thus, leaving tools installed in /usr/lib/cloud-init on that platform.
OpenBSD ports install things in /usr/local, so follow suit.
```
> fix(setup): Relocate libexec on OpenBSD

- cloudinit/sources/azure/imds.py
- tests/unittests/sources/azure/test_imds.py
This is a more appropriate categorization for these logs and
this log level will ensure they are logged to the console.
> azure/imds: log http failures as warnings instead of info

- cloudinit/distros/alpine.py
- cloudinit/distros/arch.py
- cloudinit/distros/debian.py
- cloudinit/distros/gentoo.py
- cloudinit/distros/opensuse.py
- cloudinit/distros/photon.py
- cloudinit/distros/rhel.py
Setting create_hostname_file to False while trying to set the hostname via userdata can result in the hostname not being correctly set (it is overwritten by the cloud provider's DHCP service).  This change adds a log line every time a hostname file is not created due to create_hostname_file being False for easier debugging of that situation.
```
chore: Add log message when create_hostname_file key is false
Setting create_hostname_file to False while trying to set the
hostname via userdata can result in the hostname not being
correctly set (it is overwritten by the cloud provider's DHCP
service).  This change adds a log line every time a hostname file
is not created due to create_hostname_file being False for easier
debugging of that situation.
```
Added logging related to this PR: …
> logging: Add log message when create_hostname_file key is false

- doc/rtd/development/contribute_docs.rst
On the page for contributing to the docs, there is no direct link to the docs source code.  This change adds a link to the top of that page.
```
docs: Add link to contributing to docs
On the page for contributing to the docs, there is no direct link
to the docs source code.  This change adds a link to the top of
that page.
```
> docs: Add link to contributing to docs

- ChangeLog
- cloudinit/cmd/status.py
- cloudinit/version.py
- debian/changelog
- debian/patches/do-not-block-user-login.patch
- debian/patches/retain-apt-pre-deb822.patch
- debian/patches/status-do-not-remove-duplicated-data.patch
- tests/unittests/cmd/test_status.py
```bash
new_upstream_snapshot.py -c 23.4.1 -b 2045582
dch -r -D mantic ''
git commit -m 'releasing cloud-init version 23.4.1-0ubuntu0~23.10.1' debian/changelog
git tag ubuntu/23.4.1-0ubuntu1_23.10.1
```
> Ubuntu/mantic 23.4.x

- ChangeLog
- cloudinit/cmd/status.py
- cloudinit/version.py
- debian/changelog
- debian/patches/retain-apt-pre-deb822.patch
- debian/patches/status-do-not-remove-duplicated-data.patch
- tests/unittests/cmd/test_status.py
```bash
new_upstream_snapshot.py -c 23.4.1 -b 2045582
dch -r -D lunar ''
git commit -m 'releasing cloud-init version 23.4.1-0ubuntu1~23.04.1' debian/changelog
git tag ubuntu/23.4.1-0ubuntu1_23.04.1
```
> Ubuntu/lunar 23.4.x

- ChangeLog
- cloudinit/cmd/status.py
- cloudinit/version.py
- debian/changelog
- debian/patches/retain-apt-pre-deb822.patch
- debian/patches/status-do-not-remove-duplicated-data.patch
- tests/unittests/cmd/test_status.py
```bash
new_upstream_snapshot.py -c 23.4.1 -b 2045582
dch -r -D lunar ''
git commit -m 'releasing cloud-init version 23.4.1-0ubuntu1~22.04.1' debian/changelog
git tag ubuntu/23.4.1-0ubuntu1_22.04.1
```
> Ubuntu/jammy 23.4.x

- ChangeLog
- cloudinit/cmd/status.py
- cloudinit/version.py
- debian/changelog
- debian/patches/retain-apt-pre-deb822.patch
- debian/patches/status-do-not-remove-duplicated-data.patch
- tests/unittests/cmd/test_status.py
```bash
new_upstream_snapshot.py -c 23.4.1 -b 2045582
dch -r -D focal ''
git commit -m 'releasing cloud-init version 23.4.1-0ubuntu1~20.04.1' debian/changelog
git tag ubuntu/23.4.1-0ubuntu1_20.04.1
```
> Ubuntu/focal 23.4.x

- cloudinit/config/cc_apt_configure.py
- tests/integration_tests/modules/test_apt_functionality.py
- tests/integration_tests/util.py
- tests/unittests/config/test_cc_apt_configure.py
```
fix(apt_configure): disable sources.list if rendering deb822
If deb822 sources format is used and a preexistent
/etc/apt/sources.list exists, then disable the old sources file.
This prevents user-facing warnings while operating with apt or
apt-get and other possible conflicts.
This is safe to do as cloud-init owns the base APT configuration which
tipically/historically involved overwriting /etc/apt/sources.list
Fixes GH-4691
LP: #2045086
```
I think it is safe to disable `/etc/apt/source.list`, because previously cloud-init override it, before https://github.com/canonical/cloud-init/pull/4437, or now if features.APT_DEB822_SOURCE_LIST_FILE is false or if the provided sources config has the classic style.
https://github.com/canonical/cloud-init/issues/4691
> fix(apt_configure): disable source.list if rendering deb822

- tools/ds-identify
```
fix(ds-identify): Return code 2 is a valid result, use cached value
Commit de5fc365f1 added a new return code (2) for indicating disabled status.
Without this change, ds-identify will re-run when it shouldn't, and users will
see a bogus log message:
previous run returned unexpected '$ret'. Re-running.
Fix it.
```
> fix(ds-identify): Return code 2 is a valid result, use cached value

- tests/integration_tests/reporting/test_webhook_reporting.py
```
test: Update webhook test due to removed cc_migrator module
Removed cc_migrator module means 2 less events, one from start, one
from end.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-lxd_container/376/testReport/junit/tests.integration_tests.reporting/test_webhook_reporting/test_webhook_reporting/
I don't love the arbitrary number that changes when the number of modules changes, but I also haven't found a simple way of representing the total number of modules that will run and send events.
> test: Update webhook test due to removed cc_migrator module

- .github/workflows/linkcheck.yml
- doc/rtd/conf.py
```
sphinx linkcheck cannot process link anchors in generated github
markdown or rst formatted pages. Ignore those expect failing links.
Also reduce expected github action linkcheck expected broken link count.
```
Should resolve linkcheck GH action failures seen in #4726
```
tox -e linkcheck | grep broken   
```
> test(linkcheck): ignore github md and rst link headers

- tests/integration_tests/cmd/test_clean.py
- tests/integration_tests/modules/test_cli.py
```
Commit d662ffc5 introduced a warning from cloud-init when disabling an image build artifact /etc/apt/sources.lists in favor of writing deb822 format sources file at /etc/apt/sources.list.d/ubuntu.sources.
As such, integration tests cannot check execute(cloud-init status).ok, they have to instead expect to see non-zero exit 2 due to the warning.
We want to make this strict expectation of exit 2 on noble so we can track in jenkins when Ubuntu Noble image builds correctly remove this undesired build artifact /etc/apt/sources.list.
```
Failing jenkins noble jobs https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-ec2/20/
```
CLOUD_INIT_OS_IMAGE=noble CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily .tox/integration-tests/bin/pytest …
```
> tests: add expected exit 2 on noble from cloud-init status

- config/cloud.cfg.tmpl
- sysvinit/freebsd/cloudinitlocal.tmpl
- sysvinit/netbsd/cloudconfig.tmpl
- sysvinit/netbsd/cloudfinal.tmpl
- sysvinit/netbsd/cloudinit.tmpl
- sysvinit/netbsd/cloudinitlocal.tmpl
- sysvinit/netbsd/dsidentify.tmpl
- tests/unittests/test_ds_identify.py
- tools/ds-identify
```
fix(runpath): On *BSD, /run is not ephemeral
On *BSD, `/run` is not ephemeral, but the way cloud-init behaves, it
expects it to be. To fix this, we ds-identify's RUN_* initialization after
figuring out which OS we run on.
For the Python we set the config to the expected directories.
Add and fix tests to ensure this behavior is correct and consistent.
Fixes GH-4180
Fixes GH-4231
```
> fix(runpath): On *BSD, create /run is not ephemeral

- cloudinit/config/cc_apt_configure.py
- tests/integration_tests/util.py
- tests/unittests/config/test_cc_apt_configure.py
```
feat(apt): remove /etc/apt/sources.list when deb22 preferred (#....)
Some images may contain /etc/apt/sources.list which cloud-init historically would silently overwrite on first boot. Remove this file rather than preserve a vestigial disabled file as /etc/apt/sources.list.disabled because the disabled file may just confuse users as to the why the file exists and whether they should consider re-enabling it.
If a customer reenables a previously disabled
/etc/apt/sources.list.disabled file and the same APT sources are defined in both /etc/apt/sources.list and deb822 formatted /etc/apt/sources.list.d/ubuntu.sources, apt update and cache commands will emit warnings about duplicate sources being detected which could break tooling which attempts to parse apt command output.
Let's avoid …
```
> feat(apt): remove /etc/apt/sources.list when deb22 preferred

- cloudinit/net/network_manager.py
- tests/unittests/net/test_net_rendering.py
- tests/unittests/test_net.py
- tools/.github-cla-signers
This basically applies the logic of d29eeccd to network-manager as well.
```
net/nm: Apply global DNS settings to interfaces
Sometimes DNS settings in cloud configs are specified globally and
not per interface / subnet. This results in a configuration without
proper nameservers. This was fixed for netplan in d29eeccd and is
now also applied to the network-manager renderer.
```
> Apply global DNS settings to individual interfaces in network-manager renderer

- cloudinit/config/cc_growpart.py
- tests/unittests/config/test_cc_growpart.py
Fixes https://github.com/canonical/cloud-init/issues/4613
See bug
> Fix growpart race

- doc/rtd/explanation/boot.rst
- doc/rtd/howto/debugging.rst
- doc/rtd/reference/base_config_reference.rst
- doc/rtd/reference/datasources/lxd.rst
```
doc(ds-identify): Describe ds-identify irrespective of distro
- add links to the detect stage where appropriate
- add note about datasource_list requiring a subset of YAML
- rename "Generator" stage to "Detect"
```
This stage may have originally been specific to systemd-generator, but today it is used by various other init systems for the same purpose. Update the docs to use generic vocabulary, include some links to this section where appropriate, and update language to be direct. Also include the importance of the `datasource_list` key being a subset of YAML.
> Describe ds-identify irrespective of distro

- debian/changelog
- debian/patches/series
- debian/patches/status-retain-recoverable-error-exit-code.patch
> Ubuntu/mantic 23.4.x: Retain exit code in cloud-init status for recoverable errors

- tests/integration_tests/modules/test_cli.py
```
tests: stable ubuntu releases will not exit 2 on warnings
```
Branches such as https://github.com/canonical/cloud-init/pull/4755 just landed in stable release branches ubuntu/focal, jammy, lunar and mantic to retain exit 0 behavior when encountering warnings. As such, integation tests which source ppa:cloud-init-dev/daily should assert that exit 0 is seen on invalid_userdata warnings.
```
CLOUD_INIT_OS_IMAGE=lunar CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily .tox/integration-tests/bin/pytest  tests/integration_tests/modules/test_cli.py
```
> tests: warning status zero on stable release

- tests/integration_tests/modules/test_set_hostname.py
- tests/integration_tests/releases.py
See individual commits.
This is due to the new `create_hostname_file` key being necessary on GCE. The layout is a bit verbose, but due to the way we inject userdata with marks, I'm not sure there's a better way to do it.
> Hostname tests

- cloudinit/distros/__init__.py
- cloudinit/distros/amazon.py
- cloudinit/distros/debian.py
- cloudinit/distros/freebsd.py
- cloudinit/distros/rhel.py
- cloudinit/net/dhcp.py
- cloudinit/sources/DataSourceCloudStack.py
- tests/unittests/net/test_dhcp.py
- tests/unittests/sources/test_cloudstack.py
```
refactor(IscDhclient): discover DHCP leases at distro-provided location
Use leases directory and lease file provided by Distro object
instead of cycling through all possible locations.
```
IscDhclient class seems to be only used by CloudStack datasource.
> refactor(IscDhclient): discover DHCP leases at distro-provided location

- cloudinit/distros/alpine.py
- tests/unittests/net/test_dhcp.py
```
Alpine: fix location of dhclient leases file
PR #4683 changes missed Alpine. This PR addresses this.
```
> Alpine: fix location of dhclient leases file

- doc/rtd/reference/cli.rst
- integration-requirements.txt
- tests/helpers.py
- tests/integration_tests/assets/enable_coverage.py
- tests/integration_tests/bugs/test_lp1835584.py
- tests/integration_tests/conftest.py
- tests/integration_tests/instances.py
- tests/integration_tests/integration_settings.py
- tests/integration_tests/test_kernel_commandline_match.py
- tests/integration_tests/test_upgrade.py
- tests/integration_tests/util.py
- tests/unittests/config/test_cc_chef.py
- tests/unittests/config/test_cc_resolv_conf.py
- tests/unittests/config/test_modules.py
- tests/unittests/config/test_schema.py
- tests/unittests/helpers.py
- tests/unittests/sources/vmware/test_vmware_config_file.py
- tests/unittests/test_ds_identify.py
- tests/unittests/test_helpers.py
- tests/unittests/test_render_template.py
- tests/unittests/test_subp.py
- tox.ini
> Enable coverage in integration tests

- cloudinit/config/schemas/schema-network-config-v1.json
- tests/integration_tests/test_networking.py
- tests/unittests/config/test_schema.py
```
feat: network schema v1 strict on nic name length 15
Add schema validation for physical nic name length of 15.
Add integration tests to assert this schema validation behavior.
Fixes: GH-4743
```
```
CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE CLOUD_INIT_OS_IMAGE=noble CLOUD_INIT_PLATFORM=lxd_vm .tox/integration-tests/bin/pytest tests/integration_tests/test_networking.py::test_netplan_rendering
```
> Net v1 name length

- packages/debian/cloud-init.logrotate
- tests/integration_tests/cmd/test_clean.py
Update  logrotate config for ubuntu to adhere to best practices across other products.
Fix config to specify `su root root` to avoid errors from logrotate about insecure permissions
```
error: skipping "/var/log/cloud-init-output.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
```
Update the integration test to actually invoke the packaged logrotate.d file which lives at
/etc/logrotate.d/cloud-init once packaged.
```
CLOUD_INIT_KEEP_INSTANCE=1 CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily CLOUD_INIT_OS_IMAGE=lunar CLOUD_INIT_PLATFORM=lxd_container tox -e integration-tests -- …
```
> Fix logrotate config and integration test

- sysvinit/gentoo/cloud-init-ds-identify
- tools/ds-identify
```
feat(Alpine): Modify ds-identify for Alpine support and add OpenRC init.d script
Add OpenRC init.d script for ds-identify.
Add support to ds-identify for "virt-what" as an alternative to
"systemd-detect-virt" for non-systemd Linux distros.
Change ds-identify to use short option for "modprobe" for Busybox
compatibility.
Change ds-identify to use short options for "grep" as POSIX does not
define long options, they are a GNU-ism.
```
> Modify ds-identify for Alpine support and add OpenRC init.d script

- tests/integration_tests/test_networking.py
Netplan tests are failing on KeyError: 'match' for expected; this change initializes the key.
```
(fix: netplan rendering integrations tests)
Netplan tests are failing on KeyError: 'match' for expected; this change initializes the key.
```
Jenkins integrations tests are failing due to test added in PR#4774; I think this should fix it.
> fix: netplan rendering integrations tests

- cloudinit/config/cc_ca_certs.py
- tests/unittests/config/test_cc_ca_certs.py
- tools/.github-cla-signers
feat(cacerts) : Enable support for VMware Photon
```
This feature enables cacerts functionality for VMware Photon.  It 
allows for adding 3rd party certificates as well as for cloud-init
to use them in modules like phone_home.
1. Add a certificate in the cloud-init configuration cacerts
2. Execute cloud-init
3. Verify that the certificate has been added to /etc/ssl/certs/ directory
4. Verify that the phone_home module can access a website built from the applied root certifcate
- [X ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
> Update cacerts to support VMware Photon

- doc/rtd/conf.py
```
Commit ce07818f9 introduced new doc links for Scaleway datasource.
Ignore anchors which sphinx link check cannot parse.
Fixes CI linkcheck failures.
```
> fix: linkcheck for ci to ignore scaleway anchor URL

- tests/integration_tests/cmd/test_clean.py
```
tests: add exit 2 on noble from cloud-init status
Supplemental integration test missed in commit 720665263.
This will all be reverted with Noble cloud-image builds with
/etc/cloud/build.info serial that is greater than 20240110.
```
One other integration test missed expecting exit 2 on noble due to deb822 duplicated source warnings.
Both this PR and 72066526310cb58f6c6d657c49466d76f0be2910 will likely need to be revoked within a week when cloudimage builds are unblocked for noble.
- failure seen in [jenkins results](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-lxd_container/393/testReport/tests.integration_tests.cmd.test_clean/TestCleanCommand/test_clean_rotated_logs/)
```
CLOUD_INIT_KEEP_INSTANCE=1 …
```
> tests: add exit 2 on noble from cloud-init status

- tests/unittests/test_ds_identify.py
- tools/ds-identify
Reported in https://github.com/canonical/cloud-init/issues/4794, when an invalid configuration includes an invalid (empty) `datasource_list`, ds-identify will identify the wrong datasource.
While the datasource_list is invalid, it does represent a regression because previous ds-identify behavior was to silently ignore the invalid configuration and now it needlessly prevents cloud-init from running rather than identifying the correct datasource like it used to.
This issue was introduced in https://github.com/canonical/cloud-init/pull/4327.
```
$ tox -e py3 tests/unittests/test_ds_identify.py
```
> Revert ds identify optimization

- ChangeLog
- cloudinit/version.py
- requirements.txt
- test-requirements.txt
- tests/unittests/test_ds_identify.py
- tools/ds-identify
Fix https://github.com/canonical/cloud-init/issues/4794, which was introduced in release 23.4.
```
tox -e py3 tests/unittests/test_ds_identify.py
```
> Fix Release 23.4.x

- tests/integration_tests/modules/test_ubuntu_advantage.py
Focal and Jammy integration tests on jenkins foor GCE, AWS, and Azure were failing on checking for clean log finding an error about missing a necessary token.  The issue was in the test which did not take a proper snapshot.
```
fix(tests): failing integration tests due to missing ua token
Focal and Jammy integration tests on GCE, AWS, and Azure were
failing on checking for clean log finding an error about missing
a necessary token.  The issue was in the test which did not take
a proper snapshot.
```
Validated the change locally for GCE with:
```
$ CLOUD_INIT_OS_IMAGE=focal …
```
> fix(tests): failing integration tests due to missing ua token

- tests/unittests/test_ds_identify.py
A stray docstring closing anchor actually "commented" out this specific test which we expect to xfail.
```
72 characters.
```
> tests: enable ds-idenitfy xfail test LXD-kvm-not-MAAS-1

- tests/integration_tests/cmd/test_clean.py
```
tests: use client fixture instead of class_client avoiding timeout
Tests invoking cloud-init clean end up removing all logs on the test
instance. Therefore, we cannot use the class_client fixture because
subsequent tests which call cloud-init status --wait will block
forever because the instance state has been removed by the prior
logrotate test.
Integration tests defined using the class_client fixture will
run using the same launched instance which should be reserved for
testcases where there is no cross-test interaction or artifact that
may invalidate the subsequent tests.
A cleaned system with no cloud-init.log will sit at
cloud-init status --wait indefinitely. This results in integration
test timeouts which cause our Jenkins runners to eventually fail.
```
Failed jenkins …
> tests: separate integration tests which invoke cloud-init clean

- tests/integration_tests/cmd/test_clean.py
New noble download images are building again so they should not return 2 on cloud-init status --wait.  This change reverts the temporary fix to allow our tests to pass during the out of sync period.
```
tests: revert #4792 as noble images no longer return 2
New noble download images are building again so they should not
return 2 on cloud-init status --wait.  This change reverts the
temporary fix to allow our tests to pass during the out of sync
period.
```
Not a clean `git revert` because there have been intervening commits that touched the same files.
> tests: revert #4792 as noble images no longer return 2

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/errors.py
- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/azure/test_errors.py
- tests/unittests/sources/azure/test_kvp.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_azure_helper.py
These errors would be reported as unhandled exceptions.  Replace them with reportable errors to clean things up:
- ReportableErrorOvfInvalidMetadata(ReportableError)
- ReportableErrorOvfParsingException(ReportableError)
- ReportableErrorOsDiskPpsFailure(ReportableError)
> azure: replace BrokenAzureDataSource with reportable errors

- tests/integration_tests/test_networking.py
From jenkins integrations tests failures 2024-01-26.
Related to: #4795
```
fix(tests): fixing KeyError on integrations tests
From jenkins integrations tests failures 2024-01-26.
Related to: #4795
```
Tested integrations test locally: `$ CLOUD_INIT_OS_IMAGE=focal CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily CLOUD_INIT_PLATFORM=gce  tox -e integration-tests  -- tests/integration_tests/modules/test_ubuntu_advantage.py::TestUbuntuAdvantagePro`
> fix(tests): fixing KeyError on integrations tests

- cloudinit/util.py
- tests/unittests/test_util.py
```
refactor(cloudinit.util): Modernize error handling, add better warnings
Special-casing exception handling on error codes isn't required since Python
3.3. Use built-in exceptions and improve warning messages.
```
> refactor(cloudinit.util): Modernize error handling, add better warnings

- tests/unittests/config/test_cc_ca_certs.py
- tests/unittests/config/test_cc_disk_setup.py
- tests/unittests/helpers.py
- tests/unittests/net/test_network_state.py
- tests/unittests/sources/test_opennebula.py
- tests/unittests/sources/test_smartos.py
- tests/unittests/sources/test_vmware.py
- tests/unittests/test_cli.py
- tests/unittests/test_log.py
- tests/unittests/test_net.py
```
test: Cleanup unwanted logger setup calls
This was causing duplicate logs in test output.   
Also use modern class self() calls (less error-prone, easier to audit).
```
While digging through test failures I noted that extra logging handlers were getting added in test code causing duplicate logs. Since the logging cleanup recently, a single root logger is used in unittests. Avoid polluting the logger with unwanted handlers - manual logger setup shouldn't be required in tests anymore. Also the CiTestCase class was overwriting the log level incorrectly.
> test: Cleanup unwanted logger setup calls

- cloudinit/config/cc_package_update_upgrade_install.py
- tests/unittests/config/test_cc_package_update_upgrade_install.py
On SUSE distributions the reboot marker file is written as /run/reboot-needed. Recognize this as an additional indicator that a reboot is needed on package update/upgrade.
feat(SUSE): On SUSE distributions the reboot marker file is written as /run/reboot-needed. Recognize this as an additional indicator that a reboot is needed on package update/upgrade.
- [x ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
> Support reboot on SUSE distros on package install/update/upgrade

- cloudinit/config/schema.py
- tests/integration_tests/cmd/test_schema.py
- tests/unittests/config/test_schema.py
```
fix(net-schema): no warn when skipping schema check on non-netplan
Avoid warning when network-config schema is version 2 and we
are on non-netplan systems because cloud-init doesn't yet
have static JSON network-config schema defined yet for
version 2.
Also fixes integration test to expect python3 netplan API
on Ubuntu Mantic and newer.
Fixes GH-4814
```
Also failed our Jenkins test runners
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-mantic-lxd_container/139/testReport/junit/tests.integration_tests.cmd.test_schema/TestSchemaDeprecations/test_network_config_schema_validation/
Validation performed with this PR on a system with no netplan python imports available
Notice: 
1. happy cloud-init status without warnings
2. skipping netplan schema …
> fix(net-schema): no warn when skipping schema check on non-netplan

- tests/integration_tests/instances.py
- tests/integration_tests/modules/test_set_password.py
```
test: Update tests for passlib requirements
- Add one xfail for a test that assumes that 'crypt' will exist on the host.
- Don't manually install python3-passlib. This is unecessary unless the Python version is > 3.12, and it could mask future problems in cloud-init packaging requirements.
```
> test: Update tests for passlib requirements

- cloudinit/sources/DataSourceAliYun.py
- cloudinit/sources/__init__.py
- integration-requirements.txt
- test-requirements.txt
- tests/unittests/config/test_cc_growpart.py
- tests/unittests/config/test_cc_seed_random.py
- tests/unittests/sources/test_altcloud.py
- tests/unittests/sources/test_azure.py
- tests/unittests/test_stages.py
Fix tests after pytest 8.0.0 release. Changes in tests collection ordering are surfacing mocking issues.
https://docs.pytest.org/en/stable/changelog.html#collection-changes
`pytest test/unittest` on pytest==8.0.0
> test: fix pytest 8.0.0

- cloudinit/distros/__init__.py
- cloudinit/distros/bsd.py
- cloudinit/net/dhcp.py
- cloudinit/net/ephemeral.py
- cloudinit/sources/DataSourceCloudStack.py
- cloudinit/sources/DataSourceEc2.py
- cloudinit/sources/DataSourceGCE.py
- cloudinit/sources/DataSourceOpenStack.py
- cloudinit/sources/DataSourceScaleway.py
- cloudinit/sources/__init__.py
- cloudinit/subp.py
- cloudinit/util.py
- config/cloud.cfg.tmpl
- tests/integration_tests/net/test_dhcp.py
- tests/unittests/conftest.py
- tests/unittests/distros/test__init__.py
- tests/unittests/net/test_dhcp.py
- tests/unittests/sources/test_aliyun.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_cloudstack.py
- tests/unittests/sources/test_ec2.py
- tests/unittests/sources/test_gce.py
- tests/unittests/sources/test_init.py
- tests/unittests/sources/test_openstack.py
- tests/unittests/sources/test_scaleway.py
- tests/unittests/sources/test_upcloud.py
- tests/unittests/test_util.py
- tests/unittests/util.py
```
feat(dhcp): Add support for dhcpcd in ephemeral network timeframe
- dhcp: rework client api
- dhcp/isc-dhclient: consolidate duplicate code paths
- distro: make dhcp_client a distro property [1]
- distro: make fallback_interface a distro property [1]
- cloudstack: simplify "domain-name" and "dhcp-server-identifier" codepaths
- scaleway: eliminate unnecessary fallback interface detection
- ec2: eliminate old unnecessary pickle attribute check for "fallback_nic"[2]
- tests/unittest: new dhcpcd tests
- tests/integration: new dhcpcd tests for azure, ec2, gce, and openstack
[1] required because datasource objects can access the Distro attributes but
not the other way around. Also this is a very distro-specific codepath
and much simplification to the code will be possible as a result of …
```
> dhcpcd support

- tests/unittests/config/test_schema.py
```
test: Simplify log parsing in schema test
On focal, when using caplog, additional whitespace is getting added
on a newline. Simplify the schema test that is failing of focal so this
is no longer encountered.
```
On focal, this is what caplog is capturing:
```
2024-01-31 14:28:16 DEBUG     cloudinit.util:util.py:2282 Writing to /tmp/pytest-of-root/pytest-6/test_network_config_schema_val1/mkdtmp/etc/netplan/network-config.yaml - wb: [600] 32 bytes
2024-01-31 14:28:16 WARNING   cloudinit.config.schema:schema.py:676 Invalid network-config provided:
format-l1.c12: Invalid netplan schema. incorrect YAML value: yes for dhcp value
```
the additional whitespace after the newline was causing failure.
> Fix focal dailies

- tests/integration_tests/test_kernel_commandline_match.py
```
test: Add kernel commandline test
Verify that ds-identify doesn't identify bonding.max_bonds=0
as a datasource definition "ds=0".
```
https://github.com/canonical/cloud-init/pull/4825
> tests: Add kernel commandline test

- packages/bddeb
```
fix(packages/bddeb): restrict debhelper-compat to 12 in focal
debhelper-compat (= 13) is not available in focal.
```
```sh
release=focal
./packages/bddeb -S -d --release $release
DEB_BUILD_OPTIONS=nocheck sbuild --nolog --no-run-lintian --no-run-autopkgtest --verbose --dist=$release cloud-init_*.dsc
```
Without this patch, sbuild fails with:
```
...
Install main build dependencies (apt-based resolver)                                                                                                                                          
----------------------------------------------------                                                                                                                                          
Installing build dependencies …
```
> fix(packages/bddeb): restrict debhelper-compat to 12 in focal

- cloudinit/distros/__init__.py
- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/helpers/azure.py
- tests/integration_tests/datasources/test_azure.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_azure_helper.py
Azure currently relies on eject for some use cases.  In noble minimal images eject is not installed by default.  This change prefers a udev command that performs the same action before trying eject.
A integration test has been created but is not functional.  Code changes have not been tested.
[1] https://github.com/canonical/cloud-init/issues/4732
```
feat: fall back to cdrom_id eject if eject is not available
Azure currently relies on eject for some use cases.  In ubuntu noble
minimal images eject is not installed by default.  This change adds a
fallback of systemd udev's cdrom -e if eject is not found on the distro.
Fixes GH-4732
```
Completely untested at this time.  @TheRealFalcon offered to work on an integration test for this.
> feat: prefer udev's cdrom_id -e to eject

- cloudinit/sources/__init__.py
- tests/unittests/sources/test___init__.py
- tools/.github-cla-signers
```
fix(source): fix argument boundaries when parsing cmdline
When the command-line includes an argument that contains `ds=`, the rest
of the argument is always interpreted as a datasource, regardless of
wether the argument is `ds` or just the suffix of another argument.
While this doesn't cause issues in a majority of cases, it starts
conflicting with other arguments that also include `ds=` but do not
refer to a cloud-init datasource. For instance, setting
`bonding.max_bonds=0` in the command-line (which is a real-world
use-case) conflicts with the current implementation.
To fix this issue, this commit ensures that `ds`, `ci.ds` and
`ci.datasource` arguments are either at the very beginning of the
command-line, or just before a whitespace, so that we don't match
another argument.
```
Add …
> fix(source): fix argument boundaries when parsing cmdline

- tests/integration_tests/reporting/test_webhook_reporting.py
```
tests: reduce expected reports due to dropped rightscale module
Commit 1a248b592 dropped cc_rightscale_user_data module.
When a module is dropped or added we need to account for the
two related start and finish events related to that module.
```
Failed jenkins job
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-lxd_container/382/testReport/junit/tests.integration_tests.reporting/test_webhook_reporting/test_webhook_reporting/
```
CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE CLOUD_INIT_OS_IMAGE=noble  CLOUD_INIT_PLATFORM=lxd_container  tox -e integration-tests  -- tests/integration_tests/reporting/test_webhook_reporting.py::test_webhook_reporting
```
> tests: reduce expected reports due to dropped rightscale module

- cloudinit/config/schema.py
- tests/unittests/config/test_schema.py
```
fix(schema cli): avoid netplan validation on net-config version 1
Commit e168b4a1 moved network-config version 2 checking out of netplan_validate_network_schema and up into the callsite in netplan_validate_network_schema.
An oversight didn't apply the same version 2 check to the second callsite in validate_cloudconfig_file.
Add unittest coverage to supplement the integration test which already caught this failure in tests.integration_tests.cmd.test_schema.
```
Failed jenkins job https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-ec2/lastSuccessfulBuild/testReport/junit/tests.integration_tests.cmd.test_schema/TestSchemaDeprecations/test_network_config_schema_validation/
```
CLOUD_INIT_OS_IMAGE=noble CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE …
```
> fix(schema cli): avoid netplan validation on net-config version 1

- cloudinit/cmd/status.py
- tests/unittests/cmd/test_status.py
```
fix: Handle systemctl when dbus not ready
See commit d29b744, but this commit generalizes the solution for all
calls in status.py
```
#4681 #4676 LP: #2046483
> fix: Handle systemctl when dbus not ready

- doc/rtd/reference/datasources/vmware.rst
```
docs(vmware): fix indentation on example userdata yaml
The given user data yaml was improperly indented, 
leading to both the code block rendering the yaml incorrectly,
as well as the user data causing cloud-init to fail. 
Fixes GH-4828
```
Fixes issue #4828
Ran `tox -e doc` locally and then verified that the `/reference/datasources/vmware` page was fixed.
> docs(vmware): fix indentation on example userdata yaml (GH-4828)

- cloudinit/config/schemas/schema-network-config-v1.json
- doc/rtd/reference/network-config-format-v1.rst
- tests/unittests/config/test_schema.py
```
fix: Add types to network v1 schema
Even though it has conflicted with our documentation, we have allowed
nameserver address to a be a string, mtu to be empty, and nameserver
search to be missing. Since we have allowed these, expand our schema
and documentation accordingly.
Fixes GH-4710
```
> fix: Add types to network v1 schema

- cloudinit/config/cc_set_hostname.py
- cloudinit/config/cc_update_hostname.py
- doc/rtd/reference/datasources/nocloud.rst
- doc/rtd/reference/datasources/vmware.rst
- doc/rtd/tutorial/qemu-script.sh
- doc/rtd/tutorial/qemu.rst
If a cloud or user sets create_hostname_file to false (as GCP does) the examples in our docs for setting the hostname will not work. This change updates those examples to also set create_hostname_file to true.
```
docs: add create_hostname_file to all hostname user-data examples
If a cloud or user sets create_hostname_file to false (as GCP does)
the examples in our docs for setting the hostname will not work.
This change updates those examples to also set create_hostname_file
to true.
```
See https://github.com/canonical/cloud-init/pull/4330 for details on `create_hostname_file` key.
This is left as a WIP because I want to go through and follow each of the changed examples to ensure they still work with the new key included.
> docs: add create_hostname_file to all hostname user-data examples

- tests/integration_tests/cmd/test_status.py
- tests/integration_tests/decorators.py
```
tests: add status --wait blocking test from early boot
In bugs such as LP: #2046483, cloud-init status --wait produces a traceback early when dbus or other resources are not yet available resulting in an early unblock from status --wait.
Add an integration test inserting a systemd unit before cloud-init-local.service that will block until cloud-init is done.
Assert that the timestamp of marker file created when this test unit unblocks, occurs after cloud-init.target was reached.
```
Supplemental test coverage to make sure future changes to cloud-init boot stages don't break cloud-init --wait expected behavior.
```
CLOUD_INIT_KEEP_INSTANCE=1 CLOUD_INIT_OS_IMAGE=noble CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE tox -e integration-tests -- …
```
> tests: add status --wait blocking test from early boot

- tests/integration_tests/test_upgrade.py
```
test: Add expected dhcp6 key
```
@TheRealFalcon think it is safe to ignore this one? Also this one strikes me as one to maybe run as part of ci, but not sure we should really add more to ci runtime.
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-gce/384/testReport/junit/tests.integration_tests/test_upgrade/test_clean_boot_of_upgraded_package/
Not yet tested
> add expected dhcp6 key

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/test_azure.py
Add ProvisionGuestProxyAgent Boolean configuration setting into the OvfEnv class.
This PR is only logging the value of ProvisionGuestProxyAgent.
> azure: Add ProvisionGuestProxyAgent Boolean setting

- cloudinit/net/dhcp.py
- tests/unittests/net/test_dhcp.py
- tests/unittests/util.py
Adds InifiniBand support to dhcpcd, updates udhcpc support to use the same client-id as dhcpcd and isc-dhclient.
InfinBand has its own software stack, but also uses a shim layer, IPoIB, to assign an IP address and provide compatibility with traditional transports (TCP / UDP) over its own transport. Its own transport uses RDMA to transfer data and typical users use a userspace library called libibverbs, on top of which various transports are built.
DHCP             -> https://www.rfc-editor.org/rfc/rfc2855
DHCP InfinBand   -> https://www.rfc-editor.org/rfc/rfc4390.html
DHCP hwaddr      -> https://www.iana.org/assignments/arp-parameters/arp-parameters.txt
Some relevant excerpts from RFC4390:
> A DHCP client, when working over an IPoIB interface, MUST follow the
>   following rules:
>
> …
> dhcpcd InfiniBand support

- cloudinit/analyze/show.py
- tests/unittests/analyze/test_show.py
- tools/.github-cla-signers
```
feat: handle error when log file is empty
Fixes GH-4686
```
> handle error when log file is empty

- cloudinit/cloud.py
- cloudinit/config/cc_lxd.py
- cloudinit/config/cc_snap.py
- cloudinit/config/cc_ubuntu_autoinstall.py
- cloudinit/util.py
- systemd/cloud-config.service.tmpl
- tests/integration_tests/modules/test_frequency_override.py
- tests/unittests/config/test_cc_lxd.py
- tests/unittests/config/test_cc_snap.py
- tests/unittests/config/test_cc_ubuntu_autoinstall.py
- tests/unittests/util.py
```
feat(bootspeed): cloud-config.service drop After=snapd.seeded (#4687)
Historically cloud-config.service was declared the boot stage blocked
on After=snapd.seeded.service to allow for any config module to
potentially leverage snap utilities if present.
In practice, only the config modules cc_snap, cc_lxd,
cc_ubuntu_autoinstall and cc_runcmd are the modules that may strictly
rely on snaps being seeded during initial boot. So the systemd
ordering is not necessary in the majority of deployment cases.
Avoid a hard systemd ordering `After=snapd-seeded.service` in
cloud-config.service. Instead, directly call
`snap system wait seed.loaded` if user-data requires that snaps
are present and seeded.
Add a semaphore runner set limited to frequency PER_ONCE
which calls snap wait system seed.loaded …
```
> cloud-config: after systemd ordering After=snapd.seeded.service

- cloudinit/apport.py
- cloudinit/cmd/status.py
Use individual commit messages
Also relocate apport functionality to main branch for better testing and less code duplication.
Fixes https://github.com/canonical/cloud-init/issues/4875, which is [this bug](https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2025376) which was never fixed in `ubuntu/focal` so it came back again in 23.3.
If we had included the apport code in the main branch rather than in packaging branches, our unit tests would have caught the invalid typing.
> Don't warn if cloud-init is disabled

- tests/integration_tests/net/test_dhcp.py
```
test: harden test_dhcp.py::test_noble_and_newer_force_client
Update apt sources and ensure target dhcp client is correctly installed.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-ec2/51/testReport/junit/tests.integration_tests.net.test_dhcp/TestDHCP/test_noble_and_newer_force_client_udhcpc_udhcpc_/
From there, we can see that udhcpc wasn't properly installed:
`'2024-02-12 21:22:06,618 - distros[DEBUG]: DHCP client not found: udhcpc\n'`
Execute modified test on lxd_vm and noble.
> test: harden test_dhcp.py::test_noble_and_newer_force_client

- cloudinit/config/cc_install_hotplug.py
- cloudinit/sources/DataSourceEc2.py
- cloudinit/sources/__init__.py
- doc/rtd/reference/datasources/ec2.rst
- systemd/cloud-init-hotplugd.service
- systemd/cloud-init-hotplugd.socket
- tests/integration_tests/clouds.py
- tests/integration_tests/modules/test_hotplug.py
- tests/integration_tests/test_networking.py
- tests/integration_tests/util.py
- tests/unittests/config/test_cc_install_hotplug.py
- tests/unittests/sources/test_aliyun.py
- tests/unittests/sources/test_ec2.py
Read individual commits for more context.
https://warthogs.atlassian.net/browse/SC-1662
https://bootstack.canonical.com/cases/00336928
https://bootstack.canonical.com/cases/00377150
Run the added integration tests on EC2.
> feat(ec2): support multi NIC/IP setups

- cloudinit/distros/freebsd.py
```
distro: add eject FreeBSD code path
OpenBSD, and NetBSD both have an eject(1), so they should be covered in
the default code path.
FreeBSD and Dragonfly however, do not have eject in base. Here, eject is
an (unmaintained) port. In base, we do however, have camcontrol(8) and
cdcontrol(1), both of which have an eject subcommand.
Let's use camcontrol(8) here.
```
> distro: add FreeBSD code path for eject

- requirements.txt
- test-requirements.txt
- tests/unittests/config/test_cc_apk_configure.py
- tests/unittests/config/test_cc_apt_configure.py
- tests/unittests/config/test_cc_bootcmd.py
- tests/unittests/config/test_cc_ca_certs.py
- tests/unittests/config/test_cc_chef.py
- tests/unittests/config/test_cc_lxd.py
- tests/unittests/config/test_cc_mounts.py
- tests/unittests/config/test_cc_package_update_upgrade_install.py
- tests/unittests/config/test_cc_runcmd.py
- tests/unittests/config/test_cc_set_passwords.py
- tests/unittests/config/test_cc_snap.py
- tests/unittests/config/test_cc_write_files.py
- tests/unittests/config/test_cc_yum_add_repo.py
- tests/unittests/helpers.py
- tests/unittests/test_merging.py
```
fix: unpin jsonschema and update tests
In 034a5cd , we pinned jsonschema version due to failing tests. Test
failures were due to jsonschema library changing error messages.
This commit unpins the version and updates tests accordingly.
Fixes GH-4783
Co-authored-by: dermotbradley <dermot_bradley@yahoo.com>
```
https://github.com/canonical/cloud-init/issues/4783
> fix: unpin jsonschema and update tests

- tests/integration_tests/modules/test_ubuntu_advantage.py
```
test(ubuntu-pro): change livepatch to esm-infra
Livepatch is reported as warning by ubuntu-pro-client when 
enabled on some unsupported kernels.
The test is only concern with the fact that only custom services
defined in user-data are enabled by cloud-init / ubuntu-pro-client.
Change livepatch to esm-infra, as enabling this service should be
much more stable.
Consider future warnings as ok, for what this test is concerned.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-ec2/393/testReport/tests.integration_tests.modules.test_ubuntu_advantage/TestUbuntuAdvantagePro/test_custom_services/
```
CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily CLOUD_INIT_PLATFORM=ec2 …
```
> test(ubuntu-pro): change livepatch to esm-infra

- cloudinit/config/cc_apt_configure.py
- templates/sources.list.ubuntu.deb822.tmpl
- tests/integration_tests/util.py
- tests/unittests/config/test_cc_apt_configure.py
Updated per changes that just merged into Ubuntu Noble per https://code.launchpad.net/~juliank/livecd-rootfs/+git/livecd-rootfs/+merge/458366. The changset indicates that livecd-rootfs will leave around an "empty" breadcrumb `/etc/apt/sources.list` which will contain comments about the intent of Ubuntu to use deb822 format but no active APT configuration. cloud-init will now leave this breadcrumb in place and not warn in this case by checking md5sum of the file. If it is unaltered, leave it in place.
```
--- feat(apt): skip known md5sums /etc/apt/sources.list
Some image creation software will place known stub files in
/etc/apt/sources.list to inform users in comments of desired
deb822 format.
When deb822 is preferred and /etc/apt/sources.list exists, do
not remove that file if it is has a …
```
> feat(apt): deb822 sources update ubuntu.sources template and replace invalid /etc/apt/sources.list with Ubuntu default

- debian/cloud-init.postinst
An oversight in postinst to pre-flight check of hotplug file exists before trying to rename it to avoid errors in postinst when hotplug file doesn't exist
> postinst: pre-flight check hotplug file exists before forcibly moving it

- tests/integration_tests/modules/test_hotplug.py
- tools/hook-hotplug
```
fix(hotplug): remove literal quotes in args
Remove literal double quotes which cause
/usr/bin/cloud-init devel hotplug-hook: error: argument -s/--subsystem: invalid choice: '"net"' (choose from 'net') in cloud-init-hotplugd.service when a NIC is added/removed.
Literal quoutes provoke errors, an eval or something in those lines would bypass the error, but that would be equivalent to no quotes at all.
This quouting was introuced in e70cd47846120b83035daa87e089fa045355f03a.
Fixes: GH-4886
```
> fix(hotplug): remove literal quotes in args

- tests/integration_tests/util.py
On newer netplan, logging format now includes logging scope in warning messages. Generalize the expected warning log to match old and new warning messages.
```
tests: generalize warning Open vSwitch warning from netplan apply
On newer netplan, logging format now includes logging scope in
warning messages. Generalize the expected warning log to match old
and new warning messages.
```
Failure seen from integraiton test run against daily PPA:
```
E       AssertionError: Unexpected warning count != 0. Found: ["WARNING]: Running ['netplan', 'apply'] resulted in stderr output: Cannot call Open vSwitch: ovsdb-server.service is not running."]
```
```
CLOUD_INIT_OS_IMAGE=noble CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily  CLOUD_INIT_PLATFORM=ec2 tox -e integration-tests -- …
```
> tests: generalize warning Open vSwitch warning from netplan apply

- tests/integration_tests/modules/test_hotplug.py
- tests/integration_tests/releases.py
```
test: limit test_no_hotplug_triggered_by_docker to stable releases
docker repo does not contain pkgs for devel ubuntu series.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-ec2/53/testReport/junit/tests.integration_tests.modules/test_hotplug/test_no_hotplug_triggered_by_docker/
```
CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily CLOUD_INIT_PLATFORM=ec2 CLOUD_INIT_OS_IMAGE=noble tox -e integration-tests -- tests/integration_tests/modules/test_hotplug.py::test_no_hotplug_triggered_by_docker
```
> test: limit test_no_hotplug_triggered_by_docker to stable releases

- cloudinit/config/cc_apt_configure.py
- debian/changelog
- debian/patches/retain-ec2-default-net-update-events.patch
- doc/rtd/reference/datasources/ec2.rst
- templates/sources.list.ubuntu.deb822.tmpl
- tests/integration_tests/modules/test_hotplug.py
- tests/integration_tests/modules/test_ubuntu_advantage.py
- tests/integration_tests/releases.py
- tests/integration_tests/util.py
- tests/unittests/config/test_cc_apt_configure.py
- tools/hook-hotplug
Perform new_upstream_snapshot to fix merge conflicts against tip of main for manitc
integration test changes in tip of main introduced inability to merge cleanly in daily recipes:
https://launchpadlibrarian.net/714590141/buildlog.txt.gz
```
git checkout upstream/ubuntu/mantic -B ubuntu/mantic
new_upstream_snapshot.py -c a4140119 # resolve merge conflicts
git add ...
git merge --continue
new_upstream_snapshot  -p merge
```
```
git merge ubuntu/mantic # this branch
```
> Ubuntu/mantic: snapshot to fix daily builds

- tests/integration_tests/util.py
```
test: fix verify_clean_log
verify_clean_log assumed shadowed warning messages to be contained
in a single line entry with a `[WARNING]`, but warnings can be
multiline as:
'''
2024-02-16 15:01:49,354 - activators.py[WARNING]: Running ['netplan', 'apply'] resulted in stderr output: Cannot call Open vSwitch: ovsdb-server.service is not running.
Failed to connect system bus: No such file or directory
Falling back to a hard restart of systemd-networkd.service
'''
wrongly asserting the number of expected_warnings.
Make this check more reliable by asserting that the number of
lines containing `WARNINGS` is less or equal than the number of
appearances of the shadowed warning messages.
```
Fixes: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-lxd_vm/4 …
> test: fix verify_clean_log

- cloudinit/config/cc_apt_configure.py
- debian/changelog
- debian/patches/retain-ec2-default-net-update-events.patch
- doc/rtd/reference/datasources/ec2.rst
- templates/sources.list.ubuntu.deb822.tmpl
- tests/integration_tests/modules/test_hotplug.py
- tests/integration_tests/modules/test_ubuntu_advantage.py
- tests/integration_tests/releases.py
- tests/integration_tests/util.py
- tests/unittests/config/test_cc_apt_configure.py
- tools/hook-hotplug
Perform new_upstream_snapshot to fix merge conflicts against tip of main for jammy
integration test changes in tip of main introduced inability to merge cleanly in daily recipes:
https://launchpadlibrarian.net/714590145/buildlog.txt.gz
````
git checkout upstream/ubuntu/jammy -B ubuntu/jammy
new_upstream_snapshot.py -c a4140119 # resolve merge conflicts
git add ...
git merge --continue
new_upstream_snapshot  -p merge
```
```
git merge ubuntu/mantic # this branch
```
> Ubuntu/jammy: new_upstream snapshot to fix build failures 

- cloudinit/config/cc_apt_configure.py
- debian/changelog
- doc/rtd/reference/datasources/ec2.rst
- templates/sources.list.ubuntu.deb822.tmpl
- tests/integration_tests/modules/test_hotplug.py
- tests/integration_tests/modules/test_ubuntu_advantage.py
- tests/integration_tests/releases.py
- tests/integration_tests/util.py
- tests/unittests/config/test_cc_apt_configure.py
- tools/hook-hotplug
Perform new_upstream_snapshot to fix merge conflicts against tip of main for focal
integration test changes in tip of main introduced inability to merge cleanly in daily recipes:
https://launchpadlibrarian.net/714590161/buildlog.txt.gz
```
git checkout upstream/ubuntu/focal -B ubuntu/focal
new_upstream_snapshot.py -c a4140119 # resolve merge conflicts
git add ...
git merge --continue
new_upstream_snapshot  -p merge
```
```
git merge ubuntu/mantic # this branch
```
> Ubuntu/focal: new_upstream_snapshot to fix daily build recipe (merge conflicts)

- tests/integration_tests/test_kernel_commandline_match.py
On focal we detect NoCloud rather than LXD, so ensure the test reflects this.
```
test: fix kernel override test
On focal we detect NoCloud rather than LXD, so ensure the test reflects
this.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-lxd_vm/398/testReport/junit/tests.integration_tests/test_kernel_commandline_match/test_lxd_datasource_kernel_override_bonding_max_bonds_0_DataSourceLXD_False_/
Slightly concerning that this has been failing for weeks and nobody caught it
> test: fix kernel override test

- cloudinit/net/dhcp.py
- config/cloud.cfg.tmpl
- tests/unittests/distros/test__init__.py
- tests/unittests/net/test_dhcp.py
- tests/unittests/sources/test_cloudstack.py
```
feat(dhcp): Make dhcpcd the default dhcp client
isc-dhcp-client is no longer supported by upstream
BREAKING_CHANGE: Distros that want the old behavior may
set their own custom client list in cloud.cfg.
```
Will be followed up by patches into Ubuntu non-noble downstreams.
> feat(dhcp): Make dhcpcd the default dhcp client

- tests/unittests/config/test_cc_apk_configure.py
```
test: fix tmpdir in test_cc_apk_configure
cc_apk_configure uses temp_utils.py, which has special logic to return
if the user is root that can't be retargeted using our current fixtures.
Fix it by setting that tmpdir in the test setup.
```
Running tests in `tests/unittests/config/test_cc_apk_configure.py` as root will demonstrate the failure
> test: fix tmpdir in test_cc_apk_configure

- tests/integration_tests/modules/test_ca_certs.py
same as commit summary
Failed jenkins test runner. Looks like a missed case of ubuntu_advantage in an unrelated integration test.
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-ec2/lastSuccessfulBuild/testReport/junit/tests.integration_tests.modules.test_ca_certs/TestCaCerts/test_clean_log/
```
>       assert (
not diff
), f"Expected inactive modules do not match, diff: {diff}"
E       AssertionError: Expected inactive modules do not match, diff: {'ubuntu_pro', 'ubuntu_advantage'}
E       assert not {'ubuntu_advantage', 'ubuntu_pro'}
```
```
CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily tox -e integration-tests -- tests/integration_tests/modules/test_ca_certs.py::TestCaCerts
```
> tests: inactive module rename ubuntu_advantage to ubuntu_pro

- tests/integration_tests/instances.py
```
tests: use apt instead of dpkg -i to install pkg deps
On Ubuntu Noble dhcpcd-base is a hard package Depends and
also not included by default in ubuntu-minimal images until
cloud-init the new cloud-init images contain latest cloud-init.
When provided with a DEB_PATH source, use apt instead of dpkg -i
to any missing install package dependencies.
Fixes: GH-4908
```
Failed jenkins job
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-azure/51/console
There is a separate bug with Ubuntu Minimal  images (missing sgdisk https://github.com/canonical/cloud-init/issues/4907) which leaves a WARNING in logs that will not be addressed by this particular PR.
> tests: use apt install instead of dpkg -i to install pkg deps

- cloudinit/apport.py
- cloudinit/cmd/clean.py
- cloudinit/settings.py
- cloudinit/sources/DataSourceWSL.py
- doc/rtd/reference/datasources.rst
- doc/rtd/reference/datasources/wsl.rst
- tests/unittests/sources/test_common.py
- tests/unittests/sources/test_wsl.py
- tests/unittests/test_ds_identify.py
- tools/ds-identify
```
feat: Implements the WSL datasource
A new datasource is implemented for the WSL platform.
It relies on being able to access the Windows filesystem and execute cmd.exe
to determine where the user data configuration files are.
Reference documentation for that datasource is also added, explaining where
the user should place the config files, the requirements for the datasource to work
and some details that are expected to work differently or not at all.
I'm not sure that list is exhaustive, so we should expect revisions to it in the short future.
For now at least the implementation is focused on locating and ingesting user-data,
without being too smart.
Closes UDENG-1989
```
Following #4730 , this brings in the Python module with its unit tests implementing the WSL datasource.
Enabling …
> feat: WSL datasource implementation

- cloudinit/cmd/devel/hotplug_hook.py
- cloudinit/config/cc_install_hotplug.py
- cloudinit/settings.py
- cloudinit/stages.py
- cloudinit/util.py
- doc/rtd/reference/cli.rst
- tests/integration_tests/modules/test_hotplug.py
- tests/unittests/cmd/devel/test_hotplug_hook.py
- tests/unittests/test_stages.py
- tests/unittests/test_util.py
```
feat(hotplug): add cmd to enable hotplug
Add command to enable network config updates on hotplug events on
already booted instances:
cloud-init devel hotplug-hook -s net enable
The command creates a sentinel file in
/var/lib/cloud/hotplug.enabled containing the subsystems for 
which is enabled, which will override the allowed events, and
install the appropriate udev rules.
```
https://warthogs.atlassian.net/browse/SC-1664
This PR is going to have conflicts with https://github.com/canonical/cloud-init/pull/4799
```
CLOUD_INIT_PLATFORM=lxd_vm tox -e integration-tests -- tests/integration_tests/modules/test_hotplug.py::test_hotplug_enable_cmd
CLOUD_INIT_PLATFORM=ec2 tox -e integration-tests -- tests/integration_tests/modules/test_hotplug.py::test_hotplug_enable_cmd_ec2
```
> feat(hotplug): add cmd to enable hotplug

- tests/integration_tests/modules/test_ubuntu_pro.py
Until ubuntu-advantage-tools version 32 is SRU'd to stable series Pro images will continue to auto-attach by default unless an ubuntu_advantage key is provided in user-data.
Allow our integration test to provide ubuntu_advantage and ubuntu_pro keys knowing that any ubuntu_pro config overrides ubuntu_advantage in latest cloud-init.
This will emit a warning message about preference of ubuntu_pro over ubuntu_advantage and deprecation warnings, but the integration test doesn't validate deprecation warnings.
We can drop ubuntu_advantage from our user-data in May when Pro 32 releases.
```
72 …
```
> tests: pro integration tests supply ubuntu_advantage until pro v32

- tests/integration_tests/cmd/test_status.py
```
tests: lxd_vm early boot status test ordered After=systemd-remount-fs
Fix errors seen on lxd_vm where test service
before-cloud-init-local.service gets run before the filesytem is mounted read-write.
Test failures exhibit the following failure:
systemctl status before-cloud-init-local.service:
/waitoncloudinit.sh: 7: cannot create /before-local: Read-only file system
```
Failing Jenkins tests show no test artifact files emitted by the example before-cloud-init-local.service which is setup by the test.
The issue is that the service is executing on the system while the filesystem is still read-only and before systemd-remount-fs.service has run. This leaves the early boot test service with the following types of script permission errors as seen from systemctl status
```
Warning: The unit …
```
> tests: lxd_vm early boot status test ordered After=systemd-remount-fs

- tests/integration_tests/test_upgrade.py
```
test: limit temp dhcp6 changes to < NOBLE
#4474 landed in Noble, so this block isn't needed.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-gce/49/testReport/junit/tests.integration_tests/test_upgrade/test_clean_boot_of_upgraded_package/
> test: limit temp dhcp6 changes to < NOBLE

- tests/integration_tests/test_networking.py
```
test: Use correct lxd network-config keys
Focal uses user.network-config while others use
cloud-init.network-config. Ensure we handle all cases approparitely in
test_networking.py
There are also some minor refactors
```
Last 3 failures here: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-lxd_vm/408/#showFailuresLink
> test: Use correct lxd network-config keys

- cloudinit/cmd/cloud_id.py
- cloudinit/cmd/status.py
- doc/rtd/howto/status.rst
- tests/integration_tests/util.py
- tests/unittests/cmd/test_cloud_id.py
- tests/unittests/cmd/test_status.py
```
refactor: Refactor status.py
The one major functional change in this commit is around how we detect
running vs error states. Status reporting has a fundamental problem in
that we can't accurately tell if cloud-init is done because cloud-init
is actually several processes. There isn't always a way to tell whether
a service isn't running because it simply hasn't started yet vs the
service being blocked/crashed and will never start/finish.
In the past, if any of the cloud-init services reported an error, we
would assume that cloud-init as a whole has crashed and report that
cloud-init is "done", but with error. This commit flips that logic to
assume that cloud-init is always running unless we see indication that
cloud-init has completely finished. This means that
`cloud-init status …
```
> Refactor status.py

- cloudinit/sources/DataSourceNoCloud.py
- cloudinit/sources/__init__.py
- tests/integration_tests/datasources/test_nocloud.py
```
fix(nocloud): NoCloud serial datasource definition is broken
Fix it.
Deprecate the "nocloud-net" name.
```
https://github.com/canonical/cloud-init/issues/4945
https://github.com/canonical/cloud-init/issues/4948
> fix serial datasource definition for nocloud

- tests/unittests/cmd/test_status.py
```
test: fix test_get_status_systemd_failure
"uses_systemd" wasn't mocked. Also, `m_is_running` needed
to be specified in the mock list.
```
https://launchpadlibrarian.net/716284641/buildlog_ubuntu-mantic-amd64.cloud-init_99.daily-202402270455-1447bfe4~ubuntu23.10.1_BUILDING.txt.gz
In a container, moved the `/run/systemd/system` dir and test fails on main like it does currently, but passes on this branch.
> test: fix test_get_status_systemd_failure

- tests/integration_tests/modules/test_apt_functionality.py
```
tests: avoid console prompts when removing gpg on Noble
On Ubuntu Noble, removal of gpg deb results in some postfix
console config prompts which block cloud-init status --wait.
Use DEBIAN_FRONTEND=noninteractive when trying to remove deb
packages in user-data bootcmd to avoid getting blocked on input.
```
```
CLOUD_INIT_OS_IMAGE=noble CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily tox -e integration-tests -- tests/integration_tests/modules/test_apt_functionality.py::test_apt_proxy
```
> tests: avoid console prompts when removing gpg on Noble

- tests/integration_tests/net/test_dhcp.py
```
test: Fix xfail to check the dhcp client name
Rather than the instance client object
```
[Failing test](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-azure/lastCompletedBuild/testReport/tests.integration_tests.net.test_dhcp/TestDHCP/test_noble_and_newer_force_client_udhcpc_udhcpc_/)
> test: Fix udhcpc xfail

- cloudinit/subp.py
- tests/unittests/test_subp.py
```
feat(subp): Make invalid command warning more user-friendly
```
from https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-azure/lastCompletedBuild/testReport/tests.integration_tests.datasources/test_azure/test_azure_eject/
current tracebacks look like this:
```
'Traceback (most recent call last):\n'
'  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_disk_setup.py", '
'line 491, in check_partition_gpt_layout\n'
'    out, _err = subp.subp(prt_cmd, update_env=LANG_C_ENV)\n'
'                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
'  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 244, in '
'subp\n'
'    bytes_args = [\n'
'                 ^\n'
'  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 245, in ' …
```
> feat(subp): Make identifying invalid commands easier

- cloudinit/config/cc_resizefs.py
- cloudinit/util.py
- tests/unittests/config/test_cc_resizefs.py
- tests/unittests/test_util.py
```
fix(cc_resize): Don't warn if zpool command not found
Not resizing the rootfs should not cause warnings in containers.
This is expected, and how cloud-init currently behaves. Similarly,
if the image doesn't include the tools to resize the rootfs in a
container, cloud-init should similarly not raise warnings.
Other changes:
- relocate single-use helper function from cc_resize to util.py
- add warning on non-containers when no device is found.
LP: #2055219
```
many container test failures, [including this one](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-lxd_container/lastCompletedBuild/testReport/)
To hit this codepath, I believe you need zfs-backed lxd storage, which I do not have. Should be reproducible via:
```
tox -e integration-tests …
```
> fix(cc_resize): Don't warn if zpool command not found

- tests/integration_tests/datasources/test_azure.py
Minimal images have errors/warnings in the log due to the absence of sgdisk, causing an unrelated test failure in the Azure eject test.
> fix(tests): don't check for clean log on minimal image

- doc/rtd/reference/network-config-format-v2.rst
```
doc(network-v2): fix section nesting levels
Place `set-name` and `wakeonlan` out of `match`, see [0]. Move the elements under the previous part one level up.
References:
[0] https://netplan.readthedocs.io/en/latest/netplan-yaml/#properties-for-physical-device-types
```
> doc(network-v2): fix section nesting levels

- cloudinit/net/dhcp.py
- tests/unittests/net/test_dhcp.py
If there are no NICs available when attempting to perform DHCP, dhcp_discovery() will pass along interface=None.  Here is an example failing backtrace:
```
File "/usr/lib/python3/dist-packages/cloudinit/net/ephemeral.py", line 288, in obtain_lease
self.lease = maybe_perform_dhcp_discovery(
File "/usr/lib/python3/dist-packages/cloudinit/net/dhcp.py", line 98, in maybe_perform_dhcp_discovery
return distro.dhcp_client.dhcp_discovery(interface, dhcp_log_func, distro)
File "/usr/lib/python3/dist-packages/cloudinit/net/dhcp.py", line 324, in dhcp_discovery
distro.net_ops.link_up(interface)
File "/usr/lib/python3/dist-packages/cloudinit/net/netops/iproute2.py", line 10, in link_up
subp.subp(
File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 244, in subp
bytes_args = [
File …
```
> net/dhcp: fix maybe_perform_dhcp_discovery check for interface=None

- tests/integration_tests/test_upgrade.py
```
tests: upgrade tests should only validate current boot log
In upgrade tests, we should only validate clean log on the latest
boot to avoid false positives for warnings/errors which were removed
by upgrade.
```
Failed jenkins job showing warning from boot prior to pkg upgrade
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-lxd_container/395/testReport/tests.integration_tests/test_upgrade/test_subsequent_boot_of_upgraded_package/
```
tests.integration_tests.test_upgrade.test_subsequent_boot_of_upgraded_package (from pytest)
...
def test_subsequent_boot_of_upgraded_package(session_cloud: IntegrationCloud):
source = get_validated_source(session_cloud)
if not source.installs_new_version():
if os.environ.get("GITHUB_ACTIONS"): …
```
> tests: upgrade tests should only validate current boot log

- cloudinit/subp.py
```
fix: Don't warn on vendor directory
Fixes GH-4919
```
fixes https://github.com/canonical/cloud-init/issues/4919
> fix: Don't warn on vendor directory

- ChangeLog
- cloudinit/version.py
```
Release 24.1
Bump the version in cloudinit/version.py to 24.1 and update ChangeLog.
```
Steps:
1. pushed new branch 24.1.x which matches upstream main
2. `upstream-release 24.1 23.4.4`
3. redact minor release changelog entries
> Release 24.1

- doc/rtd/conf.py
When someone receives a 404, the splash page should no longer point to https://canonical-cloud-init.readthedocs-hosted.com as Canonical now has a CNAME docs.cloud-init.io available.
Add a documentation bug link for broken references which allow users to quickly report a bug with a failed link if necessary.
The new https://docs.cloud-init.io primary site is up and functional. All redirects should be in place, we will ask the community before we switch 
```
tox -e doc
xdg-open doc/rtd_html/404.html
```
> docs: update 404 page for new doc site and bug link

- cloudinit/sources/DataSourceVMware.py
- pyproject.toml
- requirements.txt
- tests/unittests/sources/test_vmware.py
- tools/build-on-netbsd
- tools/build-on-openbsd
- tox.ini
netifaces is no longer being maintained and is only used by the VMWare data source.  As such this commit replaces the calls to netifaces with cloudinit's native netinfo.
```
refactor: remove dependency on netifaces
netifaces is no longer being maintained and is only used by the VMWare data source.  As such this commit replaces the calls to netifaces with cloudinit's native netinfo.
```
This is related to https://github.com/canonical/cloud-init/pull/953.  I have tagged is as WIP at this time because I would like to do more testing on VMWare directly to ensure the updated code works in an environment without mocks.
> refactor: remove dependency on netifaces

- cloudinit/net/ephemeral.py
```
chore(ephemeral): add debug log when bringing up ephemeral network
A debug message is logged whenever an instance is able to connect 
to the IMDS but when it can't, and an ephemeral network needs 
brought up, nothing is logged. Adding a log message here will help 
improve readability of logs and help troubleshoot failure paths 
when an instance is having issues with networking. 
```
> chore(ephemeral): add debug log when bringing up ephemeral network

- tests/unittests/test_ds_identify.py
- tools/ds-identify
```
feat(ds-identify): Don't run unnecessary systemd-detect-virt
Running systemd-detect-virt is expensive and, on systemd >=251,
it is unnecessary.
The environment variable SYSTEMD_VIRTUALIZATION contains the
virtualization type that we currently manually get from
systemd-detect-virt.
https://www.freedesktop.org/software/systemd/man/latest/systemd.generator.html#Environment
```
```bash
$ /bin/sh -c 'VALUE="container:lxc";echo ${VALUE#*:}'
lxc
```
```console
[up 0.50s] ds-identify 
policy loaded: mode=search report=false found=all maybe=all notfound=disabled
/etc/cloud/cloud.cfg.d/90_dpkg.cfg set datasource_list: [ NoCloud, ConfigDrive, OpenNebula, DigitalOcean, Azure, AltCloud, OVF, MAAS, GCE, OpenStack, CloudSigma, SmartOS, Bigstep, Scaleway, AliYun, Ec2, CloudStack, Hetzner, IBMCloud, …
```
> feat(ds-identify): Don't run unnecessary systemd-detect-virt

- cloudinit/sources/DataSourceWSL.py
- doc/rtd/reference/datasources/wsl.rst
- tests/unittests/sources/test_wsl.py
- tests/unittests/test_ds_identify.py
- tools/ds-identify
```
tests: Fix wsl test
Force ds-identify to use the correct file mocks
Set defaults for optional os-release fields [1]
VERSION_ID and ID might not be set; set defaults.
[1] man 5 os-release
Fixes GH-5002
```
Fixes GH-5002
Comment out `VERSION_ID` in the host system's os-release file, run 
```bash
tox -e py3 -- tests/unittests/test_ds_identify.py::TestWSL
```
> tests: Fix wsl test file mocks, set defaults for optional os-release fields

- tools/run-container
```
feat(run-container): Run from arbitrary commitish
```
Assuming HEAD is a reasonable default. If one wants to run using [an alternate lxc binary](https://github.com/canonical/cloud-init/commit/d15779535b16f0f379c0feee2af6dfef0e8a1d5c) from a commit-ish that did not yet support doing that, for example, this would be useful. 
```
./tools/run-container --commitish 24.1 --source-package --unittest --artifacts=./srpm/ rockylinux/8
```
> Run container from commitish

- cloudinit/url_helper.py
- tests/unittests/sources/test_ec2.py
- tests/unittests/sources/test_openstack.py
- tests/unittests/test_url_helper.py
When processing multiple urls in wait_for_url and a timeout error occurs, the local variable url is None yet url_exc.url is set.
Fallback to url_exc.url with url is unet to provide sensible warning messages:
Calling '<full_failed_url>' failed [3/120s]: request error
instead of:
Calling 'None' failed [3/120s]
LP: #2055077
* two more commits to fix other unit tests (reduce test time for test_ec2, fix openstack test to also mock requests against IPv6 route
Confusing logs generated from Ec2 datasource detection on any system where cloud-init is disabled where 
Failure to wait_for_urls finds no resolvable URLs.
```
2024-02-26 19:29:49,617 WARNING cloudinit.sources.DataSourceEc2:583 Calling 'None' failed [119/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries …
```
> bug(wait_for_url): when exceptions occur url is unset, use url_exc

- tests/unittests/conftest.py
- tests/unittests/net/test_dhcp.py
- tests/unittests/net/test_init.py
- tests/unittests/sources/helpers/test_openstack.py
- tox.ini
Create pytest fixture `disable_sysfs_net` to mock cloudinit.net.get_sys_class_path and 
avoid reading /sys/class/net on the host system. This fixture is only applied sparingly to modules that interact with `cloudinit.net.get_sys_class_path` because the cost globally setting  `autouse=True` on this fixture adds about 10 seconds to the test runtime. In modules where we expect most tests to be consuming `get_sys_class_path` we autouse at the module level, otherwise leverage the `disable_sysfs_net` fixture in individual test methods where needed.
This is an answer to GH #4973 where unitests are being run in non-production environments which exhibit duplicate MAC addresses causing many tests to fail.
The plan is it squash merge these separate commits after review.
```
bug(tests): mock reads of …
```
> bug(tests): mock reads of host's /sys/class/net via get_sys_class_path

- cloudinit/cmd/main.py
- tests/integration_tests/modules/test_cli.py
```
fix(cmd-modules): exit code when --mode init
```
Supersedes https://github.com/canonical/cloud-init/pull/4939
Execute `cloud-init modules --mode init` on any instance.
> fix(cmd-modules): exit code when --mode init

- cloudinit/sources/DataSourceOracle.py
- cloudinit/util.py
- doc/rtd/reference/datasources/oracle.rst
- tests/unittests/sources/test_common.py
- tests/unittests/sources/test_oracle.py
```
fix: Make DataSourceOracle more resilient to early network issues
If DataSourceOracle fails to retrieve IMDS info in init-local, try
again during network timeframe. Additionally, ensure max_wait,
timeout, and retries are respected.
LP: #2056194
```
Launch on noble instance (with an added timeout hack): https://paste.ubuntu.com/p/NNrrC3G3FY/
Launch on noble instance with these changes: https://paste.ubuntu.com/p/NMthRQrJS2/
Note that the weirdness in retries/timeouts is fixed with https://github.com/canonical/cloud-init/pull/5024
> fix: Make DataSourceOracle more resilient to early network issues

- cloudinit/url_helper.py
- tests/unittests/sources/test_scaleway.py
- tests/unittests/test_url_helper.py
```
See individual commits. Reasoning for the Scaleway changes are in a commit message.
```
> Fix wait for url

- cloudinit/net/dhcp.py
- tests/unittests/net/test_dhcp.py
I'm not sure 10 seconds is enough of a timeout.  Azure will retry DHCP failures, but I expect the reduction from 300s/60s -> 10s will result in unexpected failures for other clouds where there is no retry.
I see that dhcpcd offers a --timeout option which might be better than relying on subprocess timeout?  Something to consider.
In the meantime:
- catch the TimeoutExpired exception and raise NoDhcpLeaseError to address below traceback
- update the "dhclient" logs to "dhcpcd"
```
File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceAzure.py", line 851, in _get_data
crawled_data = util.log_time(
^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2825, in log_time
ret = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File …
```
> net/dhcp: handle timeouts for dhcpcd

- cloudinit/config/modules.py
- tests/integration_tests/modules/test_ubuntu_pro.py
Add RENAMED_MODULES to allow support for custom /etc/cloud/cloud.cfg.d/* which may still contain the old ubuntu_advantage module name instead of ubuntu_pro.
While the typical package upgrade path would replace ubuntu_avantage with ubuntu_pro in /etc/cloud/cloud.cfg. It's possible a customer has a customized /etc/cloud/cloud.cfg that they do not wish to update with the version delivered by the cloud-init upstream package.
In cases where ubuntu_advantage is listed in system config, allow cloud-init to WARN about the rename, but still load and run ubuntu_pro.
Fixes GH-5019
```
72 characters.
If …
```
> pro: honor but warn on custom ubuntu_advantage in /etc/cloud/cloud.cfg

- cloudinit/config/schemas/schema-network-config-v1.json
- doc/rtd/reference/network-config-format-v1.rst
```
fix: Add "broadcast" to network v1 schema
Both the klibc initramfs code and the eni code will write a network v1
configuration including the broadcast address if it is provided. It
gets rendered if using the eni renderer.
LP: #2056460
```
https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2056460
> fix: Add "broadcast" to network v1 schema

- cloudinit/atomic_helper.py
- tests/unittests/test_atomic_helper.py
```
fix(atomic_helper.py): ensure presence of parent directories
```
```
Steps to reproduce:
$ cloud-init clean -ls
$ cloud-init -d modules -m init
2024-02-22 18:59:46,522 - handlers.py[DEBUG]: start: modules-init: running modules for init
2024-02-22 18:59:46,522 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
....
[('set_hostname', FileNotFoundError(2, 'No such file or directory'))]
```
> atomic_helper.py: ensure presence of parent directories

- cloudinit/config/cc_apt_configure.py
- tests/integration_tests/util.py
```
fix(apt): Don't warn on 822 source format
```
spurious warnings, probably shouldn't do that to users
> fix(apt): Don't warn on 822 source format

- tests/unittests/test_upgrade.py
```
fix: Include DataSourceCloudStack attribute in unpickle test
Ensure  is ignored in the _unpickle test for
DataSourceCloudStack. It has existed for many years.
```
Tested that it also works on the 24.1.x branch
> fix: Include DataSourceCloudStack attribute in unpickle test

- cloudinit/config/cc_apt_configure.py
- cloudinit/config/modules.py
- cloudinit/config/schemas/schema-network-config-v1.json
- cloudinit/net/dhcp.py
- cloudinit/sources/DataSourceOracle.py
- cloudinit/sources/DataSourceScaleway.py
- cloudinit/sources/DataSourceVMware.py
- cloudinit/sources/DataSourceWSL.py
- cloudinit/url_helper.py
- cloudinit/util.py
- doc/rtd/reference/datasources/oracle.rst
- doc/rtd/reference/datasources/wsl.rst
- doc/rtd/reference/network-config-format-v1.rst
- tests/integration_tests/modules/test_ubuntu_pro.py
- tests/integration_tests/util.py
- tests/unittests/net/test_dhcp.py
- tests/unittests/sources/test_common.py
- tests/unittests/sources/test_oracle.py
- tests/unittests/sources/test_scaleway.py
- tests/unittests/sources/test_wsl.py
- tests/unittests/test_ds_identify.py
- tests/unittests/test_upgrade.py
- tests/unittests/test_url_helper.py
- tools/ds-identify
Include the bugfixes planned for 24.1.1 (and dependent commits to avoid cherry-pick conflicts and failing tests), waiting on #5021 and #5028 to land and then will include them in this PR.
2516aed4408f140fad8de888e2decaddc39e2c8f (HEAD -> 24.1.x, origin/24.1.x) fix: Add "broadcast" to network v1 schema (#5034)
db8272a439a30c129e517cbaf51966debe899593 pro: honor but warn on custom ubuntu_advantage in /etc/cloud/cloud.cfg (#5030)
95d6a658824c84971def7be118cb5afc869633be net/dhcp: handle timeouts for dhcpcd (#5022)
1c4b7d57241076785717a0a804a3c00b93aa07a4 fix: Make wait_for_url respect explicit arguments
888507d4cab4124931a0675333cce7eb21425069 bug(wait_for_url): when exceptions occur url is unset, use url_exc
74481d2deea3ee3a640c568b6eca742ca41665de test: Fix scaleway retry assumptions …
> Updates for 24.1.1

- tests/integration_tests/instances.py
```
tests: Don't wait for GCE instance teardown
Fixes GH-4987
```
It feels like an abstraction would be better here for cloud-specific instance behavior customizations, but I think that would be a bigger refactor.
Fixes https://github.com/canonical/cloud-init/issues/4987
> tests: Don't wait for GCE instance teardown

- packages/debian/control.in
With support for new clients, remove hard dependency on dhclient.
> packages/debian: remove dependency on isc-dhcp-client

- cloudinit/sources/DataSourceVMware.py
- tests/unittests/sources/test_vmware.py
```
DS VMware: Fix ipv6 addr converter from netinfo to netifaces
Found an issue when verifying PR 4634 on vSphere platform, 
which is failing to convert ipv6 addr from netinfo format to
netifaces format due to 'bcast' is not existing in ipv6.
This PR is fixing this by updating ipv4 converter function and
adding a new ipv6 converter function,  also adding unit tests.
```
> DS VMware: Fix ipv6 addr converter from netinfo to netifaces

- cloudinit/config/cc_ntp.py
- cloudinit/config/cc_resolv_conf.py
- cloudinit/config/cc_yum_add_repo.py
- cloudinit/distros/__init__.py
- cloudinit/distros/azurelinux.py
- cloudinit/util.py
- config/cloud.cfg.tmpl
- doc/rtd/reference/network-config.rst
- templates/hosts.azurelinux.tmpl
- tests/unittests/distros/test_azurelinux.py
- tests/unittests/distros/test_netconfig.py
- tests/unittests/test_cli.py
- tests/unittests/test_render_template.py
- tests/unittests/test_util.py
- tools/.github-cla-signers
- tools/render-template
```
This adds support for the new (renamed) distro 'Azure Linux'.                                                                                                                                 
Azure Linux is the renamed next version of the existing 'Mariner'                                                                                                                             
distro. It is similar to the 'Mariner' distro but changes the base                                                                                                                            
inherited Distro() class.                                                                                                                                                                     
```
> feat(azurelinux): Add new distro 'azurelinux' for Microsoft Azure Linux.

- tests/unittests/test_url_helper.py
```
fix: Don't assume ordering of ThreadPoolExecutor submissions
This test breaks in Python 3.13 and was never guaranteed to
succeed in earlier versions of Python but apparently did due
to the way that cPython was implementated previously.
```
We've had some flaky test failures for a bit now: [[example]()]
This test was never guaranteed to succeed, it just apparently did because of cPython ThreadpoolExecutor implementation. Python 3.13 brings lots of threading changes - it is unsurprising that this test now fails occasionally.
```
self = <tests.unittests.test_url_helper.TestDualStack object at 0x7f07de5e12e0>
def test_dual_stack_staggered(self):
"""Assert expected call intervals occur"""
stagger = 0.1
with mock.patch(M_PATH + "_run_func_with_delay") as delay_func:
dual_stack(
lambda x, …
```
> fix: Don't assume ordering of ThreadPoolExecutor submissions

- cloudinit/net/networkd.py
- tests/unittests/net/test_networkd.py
- tools/.github-cla-signers
Support the explicit rejection of router advertisements in cases where
the network may be configured to send them, but they are not desireable,
for example, in a case where static IPv4 addressing is used.
Before this change, IPv6AcceptRA is only included in the rendered
networkd files if DHCP is used.
Now, if a boolean value for accept-ra is present, it will be included in
the rendered output, regardless of the configured addressing.
Fixes: #4927
> networkd: Always respect accept-ra if set

- cloudinit/distros/freebsd.py
- tests/unittests/config/test_cc_users_groups.py
```
distro(freebsd): add_user: respect homedir
reportedly, passing `homedir` to a user struct doesn't actually change
the homedir to the desired value. This is because we hard-code the path.
Respect the value we are passed, and only make up a default when we
don't get a `homedir`.
Simplify style to remove cerimonious verbosity around strings, and amend
tests to verify what we did.
```
> distro(freebsd): add_user: respect homedir

- cloudinit/sources/DataSourceMAAS.py
- tests/unittests/sources/test_common.py
```
bug(maas): register the correct DatasourceMAASLocal in init-local
Incorrectly registering DataSourceMAAS for init-local DEP_FILESYSTEM
inadvertently short-circuits the _get_data checks performed by
DataSourceMAASLocal for presence of network config from initramfs.
This results in a 2 minute timeout on physical system
reboots because the network stage DataSourceMAAS expects all system
networking is already configured and the IMDS to be accessible.
Correct this registration to do the proper initramfs checks and avoid
trying to perform GETs against the IMDS in init-local timeframe when
we know network is not yet available.
Fixes GH-5064
LP: #2057763
```
> bug(maas): register the correct DatasourceMAASLocal in init-local

- cloudinit/config/schemas/schema-network-config-v1.json
- doc/rtd/reference/network-config-format-v1.rst
```
fix: document and add 'accept-ra' to network schema
It has been available in v1 config since 62bbc26
```
https://github.com/canonical/cloud-init/pull/51
https://github.com/canonical/cloud-init/blob/main/tests/unittests/net/network_configs.py#L802
> fix: document and add 'accept-ra' to network schema

- cloudinit/sources/DataSourceEc2.py
- tests/unittests/sources/test_ec2.py
See individual commits.
https://warthogs.atlassian.net/browse/SC-1717
> refactor(ec2): simplify convert_ec2_metadata_network_config

- cloudinit/config/schemas/schema-network-config-v1.json
It is passed through to our v1 schema from OpenStack network_data.json
```
fix: Undeprecate 'network' in schema route definition
It is passed through to our v1 schema from OpenStack network_data.json
Fixes GH-5051
```
https://github.com/canonical/cloud-init/issues/5051
> fix: Undeprecate 'network' in schema route definition

- cloudinit/config/cc_package_update_upgrade_install.py
- cloudinit/distros/__init__.py
- cloudinit/distros/package_management/apt.py
- cloudinit/distros/package_management/package_manager.py
- cloudinit/distros/package_management/snap.py
- tests/unittests/config/test_cc_package_update_upgrade_install.py
- tests/unittests/distros/package_management/test_apt.py
- tests/unittests/distros/test_init.py
```
fix: Fix breaking changes in package install
Ensure:
* Apt can still install packages that contain `-`, `/`, or `=`
* If a specified package manager fails we don't retry as a generic
package
* We do not attempt to invoke a package manager that doesn't exist
* Packages that are unable to be installed are tracked and
reported appropriately
Fixes GH-5066
```
https://github.com/canonical/cloud-init/issues/5066
Added additional unit tests
> fix: Fix breaking changes in package install

- cloudinit/cmd/main.py
- cloudinit/sources/helpers/openstack.py
- tests/unittests/cmd/devel/test_net_convert.py
- tests/unittests/cmd/test_main.py
- tests/unittests/config/test_cc_apt_configure.py
- tests/unittests/config/test_cc_ca_certs.py
- tests/unittests/config/test_cc_set_passwords.py
- tests/unittests/config/test_cc_ssh.py
- tests/unittests/conftest.py
- tests/unittests/distros/test_netconfig.py
- tests/unittests/helpers.py
- tests/unittests/runs/test_simple_run.py
- tests/unittests/sources/test_lxd.py
- tests/unittests/sources/test_vultr.py
- tests/unittests/test_cli.py
```
```
Issues were found using a combination of
https://pypi.org/project/pytest-randomly/
and
https://pypi.org/project/pytest-bisect-tests/
> Cleanup test side effects

- ChangeLog
- cloudinit/config/cc_package_update_upgrade_install.py
- cloudinit/config/schemas/schema-network-config-v1.json
- cloudinit/distros/__init__.py
- cloudinit/distros/package_management/apt.py
- cloudinit/distros/package_management/package_manager.py
- cloudinit/distros/package_management/snap.py
- cloudinit/sources/DataSourceEc2.py
- cloudinit/sources/DataSourceMAAS.py
- cloudinit/version.py
- debian/changelog
- doc/rtd/reference/network-config-format-v1.rst
- tests/unittests/config/test_cc_package_update_upgrade_install.py
- tests/unittests/conftest.py
- tests/unittests/distros/package_management/test_apt.py
- tests/unittests/distros/test_init.py
- tests/unittests/net/test_dhcp.py
- tests/unittests/net/test_init.py
- tests/unittests/sources/helpers/test_openstack.py
- tests/unittests/sources/test_common.py
- tests/unittests/sources/test_ec2.py
- tests/unittests/test_url_helper.py
- tox.ini
We are specifically avoiding merging this to ubuntu/devel as Ubuntu is in feature freeze at the moment and we only want to upload bugfix releases to ubuntu/noble-24.1.x.
- Updated hotfix process card https://github.com/orgs/canonical/projects/29/views/1?pane=issue&itemId=23587201
```
git fetch upstream --tags
git checkout upstream/ubuntu/noble-24.1.x -B ubuntu/noble-24.1.x
new_upstream_snapshot -c 24.1.2  # expect merge failures on Changelog && cloudinit/version.py
vi Changelog cloudinit/version.py # Accept new 24.1.2 content
git add ChangeLog cloudinit/version.py
git merge --continue
new_upstream_release.py -c 24.1.2 -p merge # proceed with refreshing debian/changelog entry creation post merge
vi debian/changelog
git commit -am 'update changelog'
git rebase -u HEAD~2
dch -r -D noble
git …
```
> Release 24.1.2 to noble

- cloudinit/net/__init__.py
- cloudinit/net/netplan.py
- cloudinit/net/networkd.py
- tests/unittests/net/test_init.py
- tests/unittests/net/test_networkd.py
```
fix(net/networkd): add GatewayOnLink flag when necessary
When the gateway isn't part of the subnet's network, the "GatewayOnLink" flag is required for the route to work.
Fixes GH-4995
```
> fix(net/networkd): add GatewayOnLink flag when necessary

- doc/examples/cloud-config-user-groups.txt
- tools/.github-cla-signers
```
examples: set the home directory using homedir, not home
According to the JSON schema, the "homedir" directive should be used to
set a user's home directory. However, we use "home" in a documented
example. Supplying the example cloud-config to cloud-init schema fails
with:
Additional properties are not allowed ('home' was unexpected),
Fixed by replacing "home" with "homedir" in the example.
LP: #2047796
```
Place the following content in a filed called e.g., test.yaml
```yaml
#cloud-config
users:
- name: ubuntu
plain_text_passwd: ubuntu,
home: /home/ubuntu
shell: /bin/bash
lock_passwd: false
gecos: Ubuntu all-oem-init
groups:
- adm
- cdrom
- dip
- lxd
- sudo
```
```bash
cloud-init schema --config-file test.yaml
```
> examples: set the home directory using homedir, not home

- cloudinit/sources/DataSourceOracle.py
```
fix: Ensure network config in DataSourceOracle can be unpickled
`_network_config` is only explicitly set on the instance if
`_is_iscsi_root()` is True. This means that when `_is_iscsi_root()` is
False, we're modifying the class variable directly. When the instance
gets pickled, the class variable is not included so such changes do
not get persisted. This commit fixes this.
```
> fix: Ensure network config in DataSourceOracle can be unpickled

- tests/unittests/config/test_apt_key.py
Fix test on non Debian based systems. Add mock to prevent bleed through to system tests are running on.
- [x ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
> Add missing mock, to prevent bleed through to test system

- cloudinit/distros/package_management/apt.py
- tests/unittests/distros/package_management/test_apt.py
```
fix: Allow caret at the end of apt package
```
https://github.com/canonical/cloud-init/pull/5069#issuecomment-2013974883
> fix: Allow caret at the end of apt package

- tests/unittests/test_ds_identify.py
- tools/ds-identify
```
fix: Always use single datasource if specified
ds-identify would automatically append "None" to the datasource_list
if a single entry was provided in /etc/cloud/cloud.cfg[.d].
This wasn't a problem in the past as the python code would detect
a single datasource along with None as an indication to automatically
use that datasource. Since the python code no longer does that,
we should ensure that one specified datasource results in one specified
datasource after ds-identify has run.
Fixes GH-5091
```
Prior to this commit, in `/etc/cloud/cloud.cfg[.d]`, an entry of `datasource_list: [OpenStack]` results in `/run/cloud-init/cloud.cfg` containing `datasource_list: [ OpenStack, None ]` (OpenStack is just an example here...it's true for any datasource).
> fix: Always use single datasource if specified

- cloudinit/cmd/devel/logs.py
- cloudinit/config/cc_power_state_change.py
- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/DataSourceOVF.py
- cloudinit/sources/azure/errors.py
- cloudinit/sources/helpers/azure.py
- setup.py
- setup_utils.py
```
chore: Handle all level 1 TiCS security violations
Ignore these bandit violations as we're not dealing with untrusted
input. Violations ignored in this commit are:
B314: xml_bad_ElementTree
B318: xml_bad_mindom
B405: import_xml_etree
B406: import_xml_sax
B408: import_xml_minidom
B603: subprocess_without_shell_equals_true
```
This PR addresses all of the level 1 warnings at: https://canonical.tiobe.com/tiobeweb/TICS/ViolationsDashboard.html#axes=Project(cloud-init)&sort=T(4,worst)&x=Ap(type),Ap(rule),Ap(level),Ap(impactAtProject),Ap(impactAtScope),Ap(message)
(Link is Canonical only)
I attempted to add a bandit config to ignore certain warnings, but TiCS won't pick it up. We have to go line by line. 
As of right now, we're only concerned with Level 1 warnings. Running locally, I got …
> chore: Handle all level 1 TiCS security violations

- cloudinit/net/__init__.py
- cloudinit/net/ephemeral.py
```
fix(dhcpcd): Interface rename
```
I think that the issue that causes #5113 is that the rename code assumes that an interface will be down prior to attempting to rename. This was default behavior with isc-dhcp-client, but dhcpcd does IP assignment and link manipulation. This change works by bringing down the link and address, which will put the link into the same state that cloud-init's rename code expects.
> Fix rename dhcpcd

- cloudinit/sources/DataSourceEc2.py
- tests/unittests/sources/test_ec2.py
```
fix(ec2): Do not enable dhcp6 on EC2
When cloud-init finds any ipv6 information in the instance metadata, it
automatically enables dhcp6 for the network interface. However, this
brings up the instance with a broken IPv6 configuration because SLAAC
should be used for almost all situations on EC2.
Red Hat BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2092459
Fedora Pagure: https://pagure.io/cloud-sig/issue/382
Upstream: https://bugs.launchpad.net/cloud-init/+bug/1976526
Fixes: canonical/cloud-init#3980
Signed-off-by: Major Hayden <major@redhat.com>
```
* Red Hat BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2092459
* Fedora Pagure: https://pagure.io/cloud-sig/issue/382
1. Deploy an instance on AWS with a VPC attached that has IPv6 subnets
2. The instance should come online with an …
> fix(ec2): Do not enable dhcp6 on EC2

- cloudinit/net/dhcp.py
On most distros, including Ubuntu, the default timeout for dhclient is 300s. There is no cloud-init controlled duration for the dhclient process as it doesn't fork and there is no timeout value passed to subp().
I have seen some distros configure dhclient with a timeout of 60s, but is far less common.
Given that a cloud VM is not very useful with DHCP, err on the generous side and allow up to 300 seconds for dhcpcd to get an address.
Note that there is still an issue with dhcpcd retries which will be addressed later in a separate PR.
> net/dhcp: bump dhcpcd timeout to 300s

- cloudinit/net/dhcp.py
- tests/unittests/net/test_dhcp.py
Seeing a fairly large number of lease parsing failures on Azure similar to:
```
File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceAzure.py", line 851, in _get_data
crawled_data = util.log_time(
^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2828, in log_time
ret = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/cloudinit/sources/helpers/azure.py", line 45, in impl
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceAzure.py", line 660, in crawl_metadata
self._wait_for_pps_savable_reuse()
File "/usr/lib/python3/dist-packages/cloudinit/sources/helpers/azure.py", line 45, in impl
return func(*args, **kwargs) …
```
> net/dhcp: raise InvalidDHCPLeaseFileError on error parsing dhcpcd lease

- tests/integration_tests/test_upgrade.py
```
After [0, 1], dhcp6 is going to be always false after upgrading cloud-init. Correct this in the integration test.
Refs:
[0] https://github.com/canonical/cloud-init/issues/3980
[1] https://bugs.launchpad.net/cloud-init/+bug/1976526
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-ec2/411/testReport/junit/tests.integration_tests/test_upgrade/test_clean_boot_of_upgraded_package/
```
export CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily
tox -e integration-tests -- -vvv tests/integration_tests/test_upgrade.py::test_clean_boot_of_upgraded_package
```
> test: fix upgrade dhcp6 on ec2

- cloudinit/net/dhcp.py
- tests/unittests/net/test_dhcp.py
```
fix(dhcpcd): Make lease parsing more robust
```
Followup to https://github.com/canonical/cloud-init/pull/5128 (rebase before merge)
> fix(dhcpcd): Make lease parsing more robust

- debian/changelog
- debian/patches/cpick-144782a8-test-Remove-side-effects-from-tests-5074
- debian/patches/cpick-372e80f8-net-dhcp-bump-dhcpcd-timeout-to-300s-5127
- debian/patches/cpick-77771023-net-dhcp-raise-InvalidDHCPLeaseFileError-on-error
- debian/patches/cpick-8f806e20-net-Warn-when-interface-rename-fails
- debian/patches/cpick-accdfe6a-refactor-Import-log-module-rather-than-functions-5074
- debian/patches/cpick-f6ac6ee8-fix-dhcpcd-Make-lease-parsing-more-robust-5129
- debian/patches/cpick-f74b61ea-ephemeral-dhcpcd-Set-dhcpcd-interface-down
- debian/patches/series
Sync applicable bug fixes from 24.1.4 to ubuntu/noble-24.1.x for release.
We are in beta freeze for Ubuntu noble, and we want to limit changes published to noble to Ubuntu bug-fixes only.
So this PR is a cherry-picked set of changes from 24.1.4 with the exclusion of the commit a6e09d9bfd3ef0770bc4d9452d978ba93dbe1245 which is  run_dir support for BSD and not applicable to Ubuntu images.
```
git checkout upstream/ubuntu/noble-24.1.x -B ubuntu/noble-24.1.x
for hash in accdfe6a8b2ffff82731c8bae2d672ff7c3f0974 144782a838123099334fe44c07566b07503fd67b f74b61eae24706dd313efc06792198a718f06672 8f806e20bda1bdf0e00ff180183990470e241837 372e80f8e6e01441e69d277782e2367678994abb 77771023ab5bda43a25cdc3dd4eb69a79169b3cb f6ac6ee8a4321ba959ae8f3ae9f1b9ac3b9fafd0; do cherry-pick $hash; …
```
> Release bug-fix only cherry-picks from 24.1.4 upstream release

- cloudinit/subp.py
```
fix: Don't log sensitive data
Since /var/log/cloud-init.log is a priviledged file, this
does not expose a secure system (no CVE). However, we don't
want to log this information so that users can file reports
without having to manually redact logs.
Standardize log messages so that redacted and non-redacted logs match.
```
> fix: Logging sensitive data

- cloudinit/sources/DataSourceEc2.py
- tests/unittests/sources/test_ec2.py
```
Revert "ec2: Do not enable dhcp6 on EC2 (#5104)"
This reverts commit f0fb841883b80c71618582e43e1b3cd87a0dcb58.
It appears that this bug was fixed already via another patch sometime
between the time I found the issue and submitted the PR #5104. This
patch isn't needed any longer and I want to avoid causing additional
problems. 😉
```
See #5104 for more details, but it looks like this problem was fixed in between the time I found the bug and I submitted my PR. My PR likely makes things more complicated.
N/A
> Revert "ec2: Do not enable dhcp6 on EC2 (#5104)"

- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/test_azure.py
Parse ProvisionGuestProxyAgent  property as bool instead of string.
> azure: parse ProvisionGuestProxyAgent as bool

- debian/changelog
- debian/patches/cpick-516fad6d-fix-url_helper-fix-TCP-connection-leak-on-readurl
- debian/patches/series
This fixes an occasionally seen issue on long-booting instances that take many retries - it has been seen since mantic was released and appears to be due to a change in Python or requests.
```
python3 -c "from cloudinit.url_helper import readurl; readurl('http://191.235.228.36/fail', infinite=True)" & sleep 30 && sudo lsof -n  | grep 191.235.228.36 | wc -l
```
This shows higher numbers on reproducible systems and 0 or 1 on non-reproducing systems. 
Note: the kernel doesn't immediately close sockets when the process that opens the socket is killed or exits. This makes testing for this behavior difficult.
> Another fix for noble

- cloudinit/util.py
- tests/unittests/distros/test_freebsd.py
- tools/.github-cla-signers
```
feat(freebsd): support freebsd find part by gptid and ufsid
freebsd obtained device partition name by the function find_freebsd_part, the params of function is the device name mounted,  usually is first  field of /etc/fstab ,  like /dev/gpt/rootfs,  but freebsd fstab also support gptid or ufsid for a unique id to identify  
partitions, like /dev/gptid/xxx, /dev/ufsid/xxx,  update function to  support
```
Regarding the FreeBSD fstab configuration supporting  gptid  and ufsid , can refer to these two links
[ufsid](https://forums.freebsd.org/threads/how-to-use-drive-unique-id-in-fstab.19690/)
[gptid](https://forums.freebsd.org/threads/how-to-use-uuid-to-identify-partitions-on-freebsd.89163/)
> feat(freebsd): support freebsd find part by gptid and ufsid

- cloudinit/distros/networking.py
- cloudinit/net/__init__.py
- cloudinit/net/activators.py
- cloudinit/net/netops/__init__.py
- cloudinit/net/netops/bsd_netops.py
- cloudinit/net/netops/iproute2.py
- cloudinit/sources/DataSourceDigitalOcean.py
- cloudinit/sources/helpers/digitalocean.py
- tests/unittests/distros/test_networking.py
- tests/unittests/test_net.py
- tests/unittests/test_net_activators.py
This is a small step towards making cloud-init use reusable networking interfaces for better cross-distro abstractions and easier maintenance.
> Netops refactor

- cloudinit/cmd/devel/net_convert.py
- cloudinit/cmd/main.py
- cloudinit/config/cc_lxd.py
- cloudinit/config/schema.py
- cloudinit/safeyaml.py
- cloudinit/sources/DataSourceOVF.py
- cloudinit/sources/helpers/vmware/imc/guestcust_util.py
- cloudinit/util.py
- tests/integration_tests/datasources/test_lxd_hotplug.py
- tests/unittests/cmd/devel/test_net_convert.py
- tests/unittests/config/test_schema.py
- tests/unittests/distros/test_netconfig.py
- tests/unittests/distros/test_networking.py
- tests/unittests/net/test_dns.py
- tests/unittests/net/test_net_rendering.py
- tests/unittests/net/test_network_state.py
- tests/unittests/net/test_networkd.py
- tests/unittests/test_ds_identify.py
- tests/unittests/test_net.py
- tests/unittests/test_net_activators.py
- tests/unittests/test_net_freebsd.py
```
chore(safeyaml): Remove legacy Python 2 unicode helper
PyYAML has built-in unicode support in Python3+.
The original code[1] was added as a helper to add
support for unicode to `yaml.safe_load()`. We
don't need this anymore, and can jettison it and
prefer `yaml.safe_load()`.
[1] a7a9de1a079
```
Note that the unittests that were added with this helper back in the python2 days still pass.
Rational: custom code that offers nothing over library code is an unnecessary complexity, remove it.
> chore(safeyaml): Remove legacy Python 2 unicode helper

- cloudinit/util.py
- tests/unittests/test_util.py
Many failures are being treated as warnings instead of errors due to usage of logexc() to emit the failure.
Add log_level parameter to allow increasing the log level without requiring an additional log.
Add tests but I'm unsure why its not logging the backtrace when the failure occurs within the test method.
> util: add log_level kwarg for logexc()

- cloudinit/analyze/dump.py
- cloudinit/sources/DataSourceOpenNebula.py
- tests/unittests/analyze/test_dump.py
- tests/unittests/sources/test_opennebula.py
- tests/unittests/test_conftest.py
- tests/unittests/test_subp.py
This change removes cloud-init's dependency on `bash` in both runtime code and in unittests. 
There are two runtime changes in this PR:
1) It standardizes the failure path and tests for systems that don't include GNU date. This fallback path to GNU date isn't used in 99.99% of cases. It is only exercised when a user has set a custom datetime format in their logs which Python code doesn't understand. GNU date offers a parsing capability which is used only in these cases.
2) The main change in this PR is adding support for posix shell in the OpenNebula datasource. It is of course possible for the OpenNebula cloud (or the end user) to pass non-posix shell data to cloud-init, but with this change at least cloud-init codepaths exist for posix shell. 
cc @dermotbradley @igalic 
```
incus create …
```
> Remove dependency on bash

- cloudinit/sources/DataSourceNoCloud.py
- cloudinit/url_helper.py
- cloudinit/util.py
- integration-requirements.txt
- tests/integration_tests/datasources/test_nocloud.py
- tests/integration_tests/test_kernel_commandline_match.py
- tests/integration_tests/util.py
- tests/unittests/sources/test_maas.py
- tests/unittests/test__init__.py
- tests/unittests/test_util.py
```
feat: Add support for FTP and FTP over TLS
Use Python's ftplib to connect to and read instance configurations from a
remove server. Like the current http support, nocloud's configuration URI
is defined via kernel command line or dmi product serial.
Notes on FTP and FTP over TLS
=============================
FTP is insecure, use at your own risk.
The FTP over TLS implementation follows library best practices[1][2].
From the ssl documentation regarding create_default_context():
> It will load the system’s trusted CA certificates, enable certificate
> validation and hostname checking, and try to choose reasonably secure
> protocol and cipher settings.
Test Changes
============
tests/i/util.py
---------------
- new helper function verify_clean_boot() to verify cloud-init state
- acquire …
```
> Add ftp support to NoCloud

- cloudinit/util.py
```
chore: Remove obsolete nose workaround
```
The comments allude to a nose bug that resulted in tracebacks when `exc_info=True` and no traceback occurred. I checked the lowest supported unittests and spot-checked a couple of other python versions in unit tests - none had these tracebacks and we no longer use nose, so I think that this is obsolete.
> chore: Remove obsolete nose workaround

- tests/integration_tests/instances.py
```
test: install software-properties-common if absent during PPA setup
In minimal images, add-apt-repository command will be absent because
software-properties-common is not installed.
This breaks integration tests which use ImageType.MINIMAL and attempt
to install cloud-init from a PPA.
Before calling add-apt-repository, check presence of the command.
When absent, apt install software-properties-common.
```
https://github.com/canonical/pycloudlib/pull/361 updates the correct image stream source for Azure minimal noble daily images.
The following integration test will fall over due to inability to call add-apt-repository in minimal azure images because software-properties-common deb isn't installed by default :
```
CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/dailyCLOUD_INIT_OS_IMAGE=n …
```
> test: install software-properties-common if absent during PPA setup

- cloudinit/net/ephemeral.py
- cloudinit/netinfo.py
- tests/unittests/conftest.py
- tests/unittests/helpers.py
- tests/unittests/net/test_dhcp.py
- tests/unittests/net/test_init.py
- tests/unittests/sources/test_aliyun.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_ec2.py
- tests/unittests/sources/test_openstack.py
- tests/unittests/sources/test_upcloud.py
```
fix(dhcp): Enable interactively running cloud-init init --local (#5166)
Check network interface state before and after receiving dhcp lease. Return
link and address to pre-existing state prior to running dhcp client.
While this isn't a supported cloud-init use case, it does make some
testing easier.
- add function typing and a docstring to a netinfo function
- remove unnecessary connectivity url check from EphemeralIPv4Network
```
Build a deb from this branch
On both noble and mantic, do the following:
- `cloud-init clean --logs`
- `cloud-init init --local`
- still connected? cool
My logs: [interactive-init-local-support.tar.gz](https://github.com/canonical/cloud-init/files/14952135/interactive-init-local-support.tar.gz)
> Enable interactively running cloud-init local --local

- tests/integration_tests/util.py
```
test: Skip test if console log is None
In the recent pycloudlib bump, Azure's console_log call went from
raising NotImplementedError to returning None if the boot diagnostic
log hasn't been initialized.
```
Ran the failures from https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-mantic-azure/188/ locally with these changes and they're skipped instead (as they were before).
> test: Skip test if console log is None

- doc/rtd/reference/datasources.rst
- doc/rtd/reference/datasources/nocloud.rst
- doc/rtd/reference/datasources/none.rst
```
docs: Add DataSourceNone documentation
```
> docs: Add DataSourceNone documentation

- cloudinit/config/schemas/schema-cloud-config-v1.json
- doc/examples/cloud-config-apt.txt
- doc/examples/cloud-config-user-groups.txt
- tests/data/user_data.1.txt
- tests/unittests/runs/test_merge_run.py
- tests/unittests/sources/test_vultr.py
```
docs: Add deprecated system_info to schema
In some cases, `system_info` can be passed via user data or vendor data
to override the system_info in /etc/cloud/cloud.cfg . While this
technically can work, this is a use case we no longer support and should
indicate that it is deprecated.
Also remove/update examples.
```
> docs: Add deprecated system_info to schema

- cloudinit/config/schemas/schema-network-config-v1.json
```
fix: Add subnet ipv4/ipv6  to network schema
These are used by our openstack network_data.json parsing code and
get used by the sysconfig renderer.
Fixes GH-4911
```
https://github.com/canonical/cloud-init/issues/4911
and
https://github.com/canonical/cloud-init/blob/70581bb0833f0ce77a2ca0ae1ee203ecc2a7bf62/cloudinit/net/sysconfig.py#L623-L636
> fix: Add subnet ipv4/ipv6  to network schema

- doc/rtd/reference/breaking_changes.rst
- doc/rtd/spelling_word_list.txt
```
docs: Add breaking datasource identification changes
```
> docs: Add breaking datasource identification changes

- cloudinit/net/netplan.py
- tests/integration_tests/modules/test_combined.py
- tests/integration_tests/test_networking.py
- tests/unittests/net/test_netplan.py
- tests/unittests/test_net.py
```
feat(net): provide network config to netplan.State for render (#4981)
Rely on netplan API where present to write network config to
50-cloud-init.yaml. (SC-1402)
Allow cloud-init to be decoupled from security policies of netplan
libraries when rendering potentially senstive network configuratiion.
Newer netplan versions may filter sensitive network configuration parts
into separate files or subdirectories. Allow cloud-init to rely on
netplan's treatment of sensitive keys by using netplan.state.State to
write_yaml_file with cloud-init's requested base filename:
50-cloud-init.yaml.
If netplan security policy changes in the future, those changes will
be adopted under the hood of netplan.State.
```
Some concerns with this approach: 
1.   Given that netplan API doesn't yet surface a public …
> feat(net): provide network config to netplan.State for render

- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_users_groups.py
- tools/.github-cla-signers
The previous cloud-config still works without any issues, but it doesn't pass validation - not even as deprecated.
Example from https://lima-vm.io default
Currently it does not validate, therefore.
commit b27f713ae5b4c5b38eda63758dbaeab92be13b9d
```
fix: deprecate ssh-authorized-keys in schema
Deprecate the users ssh-authorized-keys property
```
> Deprecate the users ssh-authorized-keys property

- tests/integration_tests/test_networking.py
- tests/integration_tests/test_upgrade.py
```
tests: validate netplan API YAML instead of strict content
Netplan API is used on Mantic and later which prevents cloud-init
from writing a header comment in /etc/netplan/50-cloud-init.yaml.
So, the former header comments cloud-init wrote when it
created /etc/netplan/50-cloud-init.yaml instead of netplan API will
disappear when using netplan's API to write 50-cloud-init.yaml.
Only compare the loaded YAML dict of networking config instead of
the full content of the file before and after upgrade to assert
the equality of network config.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-azure/110/testReport/junit/tests.integration_tests/test_upgrade/test_clean_boot_of_upgraded_package/
> tests: validate netplan API YAML instead of strict content

- .github/workflows/alpine-unittests.yml
```
test: Add alpine to ci
Cloud-init has Alpine Linux support, yet does not regularly test it.
Alpine is an attractive addition to the test matrix since it is easily
available to run in lxc, and it has several alternative components to test
against:
- busybox: non-GNU posix-compliant tools
- musl: libc alternative to glibc
- openrc: init system alternative to systemd
```
~~Blocked by https://github.com/canonical/cloud-init/pull/5119 and https://github.com/canonical/cloud-init/pull/5120. Once those land, unittests will pass on Alpine.~~
Both have landed, ready for review.
> Add alpine unittests to ci

- .github/workflows/alpine-unittests.yml
```
ci: Add timezone for alpine unit tests
```
now that https://github.com/canonical/cloud-init/issues/5158 is fixed, we can add a timezone to the alpine instance to check for regressions
> ci: Add timezone for alpine unit tests

- tests/unittests/test_upgrade.py
```
test: mock internet access in test_upgrade
Fixes: #5211
```
> test: mock internet access in test_upgrade

- integration-requirements.txt
- tests/integration_tests/clouds.py
- tests/integration_tests/modules/test_hotplug.py
- tests/integration_tests/test_networking.py
Adopt changes from https://github.com/canonical/pycloudlib/pull/355. See individual commits.
https://warthogs.atlassian.net/browse/SC-1754
```
CLOUD_INIT_PLATFORM=ec2 tox -e integration-tests -- \
tests/integration_tests/modules/test_hotplug.py::test_multi_nic_hotplug_vpc \
tests/integration_tests/modules/test_hotplug.py::test_multi_nic_hotplug \
tests/integration_tests/test_networking.py::test_ec2_multi_nic_reboot
```
- [] Squash merge using "Proposed Commit Message"
> test(ec2): refactor multinic tests and add ipv6 coverage

- test-requirements.txt
- tools/read-dependencies
- tox.ini
```
ci: Skip package build on tox runs
Building a wheel/sdist generally adds 5+ seconds to every tox run.
This is unnecessary because a built package isn't needed to run any
of the CI tasks.
Also remove the `recreate` line as it wasn't doing anything. To work
correctly, it should be defined under `[testenv]`,
not `[tox]`.
```
`tox -e ruff` is near instant on Python 3.8+
`recreate` lives under https://tox.wiki/en/latest/config.html#tox-environment
> ci: Skip package build on tox runs

- cloudinit/distros/__init__.py
- tests/unittests/distros/test_init.py
When package_update or package_upgrade: true are provided in cloud-config do not call snap refresh on systems that do not have the snap command.
This was intended as fixed in cbe5f3a119 but the fix only avoided snap refresh during package install, not the generic package update operation.
Fixes: GH-5143
Testable with either of the following procedures:
```
$ cat > pkg_update.yaml <<EOF
#cloud-config
package_update: true
EOF
lxc launch ubuntu-daily/jammy no-snap -c cloud-init.user-data="$(pkg_update.yaml)"
sleep 3
lxc exec no-snap -- apt remove --purge snapd
lxc exec no-snap -- cloud-init clean --logs --reboot 
sleep 3
lxc exec no-snap -- cloud-init status --wait --format=yaml
... ## expect errors
incus launch images:ubuntu/22.04/cloud  no-snap -c cloud-init.user-data="$(pkg_update.yaml)" …
```
> bug(package_update): avoid snap refresh in images without snap command

- ChangeLog
- cloudinit/version.py
> sync ChangeLog and version.py from 24.1.x

- debian/changelog
- debian/patches/cpick-a6f7577d-bug-package_update-avoid-snap-refresh-in-images-without
- debian/patches/series
Cherry pick a6f7577d to fix  SRU regression https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2064132
```
git checkout upstream/ubuntu/noble-24.1.x -B ubuntu/noble-24.1.x
cherry-pick a6f7577d
git commit -am 'update changelog'
sed -i '`s/UNRELEASED/noble/'` debian/changelog
git commit -am 'releasing cloud-init version 24.1.3-0ubuntu4'
```
> Ubuntu/noble 24.1.x

- debian/changelog
- debian/patches/cpick-a6f7577d-bug-package_update-avoid-snap-refresh-in-images-without
- debian/patches/series
Sync SRU regression fix with cherry-pick to a6f7577d582aa51d51ca129fcff65313e210d47b.
Keeping version ordering given single the cherry-pick to also ensure we sort below noble which is at `24.1.3-0ubuntu3.1`
```
git checkout upstream/ubuntu/focal-24.1.x -B ubuntu/focal-24.1.x 
cherry-pick a6f7577d582aa51d51ca129fcff65313e210d47b  # adds a d/patches/cpick file 
sed -i '1s/UNRELEASED/focal/' debian/changelog
git commit -am 'releasing cloud-init version 24.1.3-0ubuntu1~20.04.2'
```
> Ubuntu/focal 24.1.x: sru regression for for ubuntu images without snapd

- debian/changelog
- debian/patches/cpick-a6f7577d-bug-package_update-avoid-snap-refresh-in-images-without
- debian/patches/series
Sync SRU regression fix with cherry-pick to a6f7577d582aa51d51ca129fcff65313e210d47b.
Keeping version ordering given single the cherry-pick to also ensure we sort below noble which is at `24.1.3-0ubuntu3.1`
```
git checkout upstream/ubuntu/jammy-24.1.x -B ubuntu/jammy-24.1.x 
cherry-pick a6f7577d582aa51d51ca129fcff65313e210d47b  # adds a d/patches/cpick file 
sed -i '1s/UNRELEASED/jammy/' debian/changelog
git commit -am 'releasing cloud-init version 24.1.3-0ubuntu1~22.04.2'
```
> jammy sru regression fix images without snapd per v. 24.1.5

- debian/changelog
- debian/patches/cpick-a6f7577d-bug-package_update-avoid-snap-refresh-in-images-without
- debian/patches/series
Sync SRU regression fix with cherry-pick to a6f7577d582aa51d51ca129fcff65313e210d47b.
Keeping version ordering given single the cherry-pick to also ensure we sort below noble which is at `24.1.3-0ubuntu3.1`
```
git checkout upstream/ubuntu/mantic-24.1.x -B ubuntu/mantic-24.1.x 
cherry-pick a6f7577d582aa51d51ca129fcff65313e210d47b  # adds a d/patches/cpick file 
sed -i '1s/UNRELEASED/mantic/' debian/changelog
git commit -am 'releasing cloud-init version 24.1.3-0ubuntu1~23.10.3'
```
> SRU regression for non-snap Ubuntu/Debian images on Mantic

- cloudinit/sources/DataSourceWSL.py
- doc/rtd/reference/datasources/wsl.rst
- tests/unittests/sources/test_wsl.py
- tests/unittests/test_ds_identify.py
- tools/.github-cla-signers
- tools/ds-identify
```
feat(WSL): Add support for Ubuntu Pro configs
Currently, WSL only supports manual cloud-init configurations provided
in the host Windows filesystem. This adds support for Landscape/Ubuntu
Pro for WSL to provide cloud-init configurations and have them merged 
with or override manual user configurations. This adds support for 
organizations to better provision WSL instances using cloud-init.
```
Currently, the WSL datasource can only work with user-provided configurations manually created in the host Windows filesystem. This change allows organizations to provide configurations via Landscape/Ubuntu Pro and have them loaded into WSL instances. These new configurations will be created under `%USERPROFILE%/.ubuntupro/.cloud-init`. This change will require …
> feat(WSL): Add support for Ubuntu Pro configs

- cloudinit/sources/DataSourceMAAS.py
```
chore: Fix broken maas code
```
Better late than never, eh?
> chore: Remove broken maas code

- .github/workflows/alpine-unittests.yml
```
test: Run Alpine tests without network
None of the unit tests should be reaching out to the network.
Since Alpine tests run under LXD, we can still easily run tests there
without network.
Also, include the tzdata package that was missed in 725f5fb and
remove unneeded network debug lines.
```
See https://github.com/canonical/cloud-init/pull/5212#pullrequestreview-2023557564
> test: Run Alpine tests without network

- cloudinit/cmd/clean.py
- cloudinit/distros/__init__.py
- tests/unittests/cmd/test_clean.py
- tests/unittests/test_traceback.py
```
fix(cmd): Do not hardcode reboot command
Attempting a `cloud-init clean --reboot` fails on alpine because this
command is hard-coded. This code already has an Init object available,
which has a Distro attribute. Stamp out the duplicate hard-coded
implementation and re-use distro reboot code to acquire cross-distro
compatiblity.
Error:
Could not reboot this system using "['shutdown', '-r', 'now']": Unexpected error while running comma  nd.
Command: ['shutdown', '-r', 'now']
Exit code: -
Reason: [Errno 2] No such file or directory: b'shutdown'
Stdout: -
Stderr: -
```
This change is mostly test updates - the code change is trivial: just reuse the existing reboot code which already has multi-distro support.
> Do not hardcode reboot command

- cloudinit/sources/DataSourceEc2.py
- tests/unittests/sources/test_ec2.py
- tests/unittests/test_ds_identify.py
- tools/ds-identify
```
fix(ec2): Fix broken uuid match with other-endianness
EC2 documents that the system-uuid may be reported in different endianness[1].
A user has reported a case where cloud-init is broken due to inability to
detect the system platform. Fix it.
Behavior change:
Cloud-init was previously making the assumption that uuid and serial would match
on ec2. This assumption was:
1) not documented as a valid way to identify ec2[1]
2) proven invalid on ec2 by the DMI_PRODUCT_SERIAL and DMI_PRODUCT_UUID reported in #5105
3) used in the logic which warns about not running on the "real" ec2
Preserving this warning logic exactly as it was presents several challenges:
a) Risk of regression outside of our control: Since this logic relied upon undocumented
behavior, AWS could change this at any point, …
```
> fix(ec2): Fix broken uuid match with other-endianness

- debian/changelog
- debian/patches/cli-retain-file-argument-as-main-cmd-arg.patch
- debian/patches/series
```
fix(cli): retain support for --files argument before subcommand
Upstream dropped support for a generic positional --file argument ordered
on the command line before the cloud-init subcommand because the
--files argument is only applicable to the specific subcommands init,
modules and single.
Add functionality to retain support for --file or -f argument both
before and after the subcommand to avoid regressions in stable releases due
to a change in behavior.
LP: #2064300
```
When approved, this same quilt patch will be applied to `upstream/ubuntu/(jammy|mantic)-24.1.x` branches and uploaded to unapproved queue for focal, jammy and mantic. This quilt patch and related debian/changelog entries will also by sync'd to the unreleased `upstream/ubuntu/(focal|jammy|mantic)` branches to ensure …
> Ubuntu/focal 24 1.x:fix(cli): retain support for --files argument before subcommand

- integration-requirements.txt
```
test: Fix integration test dependencies
Commit acc68de0 introduced a change which no longer builds a wheel, however integration tests now fail when dependencies are not available.
Include the base requirements in test-requirements.txt.
Fixes GH-5210
```
without this change I see this locally:
```
================================================ FAILURES ================================================
____________________________________ TestCombined.test_run_frequency _____________________________________
self = <test_combined.TestCombined object at 0x7ae41489a900>
class_client = <tests.integration_tests.instances.IntegrationInstance object at 0x7ae414cb1e80>
def test_run_frequency(self, class_client: IntegrationInstance):
log = class_client.read_from_file("/var/log/cloud-init.log") …
```
> test: Fix integration test dependencies

- tests/integration_tests/instances.py
```
tests: force version of cloud-init from PPA regardless of version
The PPA provided to CLOUD_INIT_CLOUD_INIT_SOURCE can contain a lower
version of cloud-init than what is currently released for a given
series. In those cases install an apt preferences file to pin
the cloud-init installed to the given PPA regardless of the published
version.
```
```
CLOUD_INIT_KEEP_INSTANCE=1 CLOUD_INIT_OS_IMAGE=jammy CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily tox -e integration-tests -- tests/integration_tests/test_networking.py::test_invalid_network_v2_netplan
lxc exec cloudinit....... -- apt policy cloud-init  # ensure that the cloud-init version installed is 23.4.daily based instead of 24.1.3.
```
> tests: force version of cloud-init from PPA regardless of version

- cloudinit/config/cc_ntp.py
- templates/chrony.conf.almalinux.tmpl
- templates/chrony.conf.cloudlinux.tmpl
- templates/ntp.conf.almalinux.tmpl
- templates/ntp.conf.cloudlinux.tmpl
- tools/.github-cla-signers
```
fix(ntp): Fix AlmaLinux OS and CloudLinux OS support
- Add missing templates for chrony and ntp configuration files.
- AlmaLinux OS is binary compatible with RHEL
and CloudLinux OS based on AlmaLinux OS.
So, let's use distro-specific configurations from rhel.
```
This bugfix is part of a [patch](https://git.almalinux.org/rpms/cloud-init/src/branch/a9/SOURCES/0031-Improvements-for-AlmaLinux-OS-and-CloudLinux-OS.patch) which is used in cloud-init packages of AlmaLinux OS 8 and 9.
User data:
```yaml
#cloud-config
ntp:
servers:
- time.cloudflare.com
- time.google.com
```
> fix(ntp): Fix AlmaLinux OS and CloudLinux OS support

- cloudinit/config/cc_mounts.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- config/cloud.cfg.tmpl
```
fix(mount): When cloud-init is disabled, don't run cloud-init.service
cc_mounts configures a `Requires=cloud-init.service` in the configured mount unit via `x-systemd.requires=cloud-init.service`. This creates a requirement dependency on cloud-init.service, even if cloud-init is disabled.
Fix this by changing the mount unit dependency to
`x-systemd.after=cloud-init.service`.
Fixes GH-2815
```
Fixes #2815
> fix(mount): When cloud-init is disabled, don't run cloud-init.service

- cloudinit/config/schema.py
- tests/integration_tests/cmd/test_schema.py
- tests/integration_tests/test_networking.py
- tests/unittests/config/test_schema.py
```
fix(schema): no network validation on netplan systems without API
Do not validation network config against cloud-init's network v2 schema on netplan systems because netplan schema supports keys not present in cloud-init's v2 schema which can result in schema warnings from cloud-init which are perfectly acceptable netplan config keys.
Given that cloud-init performs a clean passthrough of network version 2 directly to netplan without trying to process the network configuration, there is little value in providing such schema warnings unless cloud-init's network v2 schema is aligned with the specific netplan schema supported for each release.
On mantic and later, cloud-init will call netplan's python API to validate schema with netplan itself, but prior to Ubuntu Mantic no python API …
```
> fix(schema): no network validation on netplan systems without API

- cloudinit/analyze/show.py
- cloudinit/cmd/main.py
- cloudinit/config/cc_power_state_change.py
- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/DataSourceCloudStack.py
- cloudinit/sources/DataSourceEc2.py
- cloudinit/sources/DataSourceMAAS.py
- cloudinit/sources/DataSourceOpenStack.py
- cloudinit/sources/DataSourceOracle.py
- cloudinit/sources/DataSourceScaleway.py
- cloudinit/subp.py
- cloudinit/url_helper.py
- cloudinit/util.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_oracle.py
- tests/unittests/test_url_helper.py
This PR contains two commits related to system time.
The first fixes container to be more accurate with `cloud-init analyze` commands.
The second hardens cloud-init against clock changes, which are possible (and likely)
during early boot.
Fixes #2423
Fixes #3149
See commit messages for test steps.
> Multiple fixes related to system time

- systemd/cloud-config.service.tmpl
- systemd/cloud-final.service.tmpl
- systemd/cloud-init-hotplugd.service
- systemd/cloud-init-local.service.tmpl
- systemd/cloud-init.service.tmpl
```
chore: Update systemd description
The current descriptions do not follow systemd guidance and are misleading since some services have multiple roles.
systemd.unit(5) on Description:
A short human readable title of the unit. This may be used by systemd
(and other UIs) as a user-visible label for the unit, so this string
should identify the unit rather than describe it, despite the name.
Yet these service files attempt to describe the unit rather than identify it.
Before:
May 01 09:49:49.238629 tiny systemd[1]: Starting cloud-config.service - Apply the settings specified in cloud-config...
After:
May 01 09:49:49.238629 tiny systemd[1]: Starting cloud-config.service - Cloud-init: Config Stage...
```
There's also the fact that the service files allude to the hotplug command being a daemon …
> chore: Update systemd description

- cloudinit/cmd/main.py
- cloudinit/util.py
- tests/unittests/cmd/test_main.py
```
fix(pdb): Enable running cloud-init under pdb
Cloud-init closes stdin on startup, which breaks interactively running cloud-init under pdb.
Leave stdin open if it is connected to a tty, which fixes pdb use.
File "/usr/lib/python3.12/bdb.py", line 90, in trace_dispatch
return self.dispatch_line(frame)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/bdb.py", line 115, in dispatch_line
if self.quitting: raise BdbQuit
^^^^^^^^^^^^^
bdb.BdbQuit
------------------------------------------------------------
The program exited via sys.exit(). Exit status: 1
```
> fix(pdb): Enable running cloud-init under pdb

- cloudinit/distros/ubuntu.py
- tests/unittests/distros/test_ubuntu.py
```
fix(snapd): ubuntu do not snap refresh when snap absent
No longer call snap refresh when cloud-config user-data specifies upgade_packages:true and custom Ubuntu images do not have snapd package installed
LP: #2064300
```
My commit a6f7577d582aa51d51ca129fcff65313e210d47b attempted to fix this issue, but the validation of the fix only looked at
`update_packages: true` config not `upgrade_packages: true`
During SRU validation we discovered that this former patch was not successful in closing the upgrade patches case.
https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2064132
```
#!/bin/bash
set -ex
SERIES=$1
cat > pkg-upgrade.yaml <<EOF
#cloud-config
package_upgrade: true
EOF
#for SERIES in "focal" "jammy" "mantic"; do
for SERIES in "focal"; do
echo "---------- SRU verification: …
```
> fix(snapd): ubuntu do not snap refresh when snap absent

- debian/changelog
- debian/patches/cpick-51c6569f-fix-snapd-ubuntu-do-not-snap-refresh-when-snap-absent
- debian/patches/series
Bug fix release to pull in fix for `package_upgrade: true` discovered during SRU verification testing of https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2064132. The real fix is 51c6569f96bee4f91aad5db58765c7abab7ffcdf which prevents the upgrade path (not update)
Note as well the bug reference in the upstream commit shouldn't have been LP: #2064300 but LP: #2064132. Manually correct that in the d/changelog.
Will reflect the same quilt patch to jammy and mantic once approved.
```
git checkout upstream/ubuntu/focal-24.1.x -B ubuntu/focal-24.1.x
cherry-pick 51c6569f96bee4f91aad5db58765c7abab7ffcdf
vi debian/changelog # correct package version suffix to  `~20.04.4` and correct LP bug number
git commit -am 'changelog' 
sed -i '1s/UNRELEASED/focal/' debian/changelog …
```
> Ubuntu/focal 24.1.x

- cloudinit/cmd/main.py
- cloudinit/signal_handler.py
- tests/integration_tests/util.py
- tests/unittests/test_cli.py
```
fix: Warn when a signal is handled
Cloud-init is expected to run to completion. It does not expect to be
stopped or restarted. Therefore, cloud-init should loudly warn when this
happens so that the user is aware that the unexpected has happened. 
Problems:
- When systemd stops cloud-init, no warning is logged.
- When systemd restarts cloud-init, status info and return code from the
current stage is lost.
The net effect of these problems is that when cloud-init is restarted
no warning is logged, and cloud-init status indicates no problem.
Communicate unexpected state by:
- Increase signal handling log level to ERROR, add log to stderr.
- Write status.json before exiting when sys.exit() is called.
- Warn when status.json contains existing data when the stage
starts[1].
- Append existing …
```
> fix: Warn when signal is handled

- tests/integration_tests/datasources/test_nocloud.py
There seems to be a jenkins proxy issue with the test software.sslmate.com had an issue with the jenkins proxy
```
CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_OS_IMAGE=jammy CLOUD_INIT_KEEP_INSTANCE=True tox -e integration-tests -- tests/integration_tests/datasources/test_nocloud.py::TestFTP::test_nocloud_ftps_encrypted_server_succeeds
```
```
CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_OS_IMAGE=jammy CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily tox -e integration-tests -- tests/integration_tests/datasources/test_nocloud.py::TestFTP::test_nocloud_ftp_encrypted_server_fails
```
> fix(tests): Fix TestFTP integration test SC-1779

- cloudinit/config/cc_ca_certs.py
```
feat(ca_certs): Add AlmaLinux OS and CloudLinux OS support
AlmaLinux OS is binary compatible with RHEL
and CloudLinux OS based on AlmaLinux OS.
So, let's use distro-specific configurations from rhel.
```
This bugfix is part of a [patch](https://git.almalinux.org/rpms/cloud-init/src/commit/a04da1edff8f67fc2f63218691e2978731b4396d/SOURCES/0031-Improvements-for-AlmaLinux-OS-and-CloudLinux-OS.patch) which is used in cloud-init packages of AlmaLinux OS 8 and 9.
User data:
```yaml
#cloud-config
ca_certs:
remove_defaults: true
trusted:
- single_line_cert
- |
-----BEGIN CERTIFICATE-----
YOUR-ORGS-TRUSTED-CA-CERT-HERE
-----END CERTIFICATE-----
```
> feat(ca_certs): Add AlmaLinux OS and CloudLinux OS support

- systemd/cloud-final.service.tmpl
- systemd/cloud-init-local.service.tmpl
- systemd/cloud-init.service.tmpl
```
feat(systemd): Improve AlmaLinux OS and CloudLinux OS support
AlmaLinux OS is binary compatible with RHEL
and CloudLinux OS based on AlmaLinux OS.
Use the same options with rhel on these systemd services:
- Cloud-init: Local Stage (pre-network): cloud-init-local.service
- Cloud-init: Network Stage: cloud-init.service
- Cloud-init: Final Stage: cloud-final.service
```
This improvement is part of a [patch](https://git.almalinux.org/rpms/cloud-init/src/branch/a9/SOURCES/0031-Improvements-for-AlmaLinux-OS-and-CloudLinux-OS.patch) which is used in cloud-init packages of AlmaLinux OS 8 and 9.
Check if template files correctly rendered to the systemd services:
```
systemctl cat cloud-init-local.service
systemctl cat cloud-init.service
systemctl cat cloud-final.service
```
> feat(systemd): Improve AlmaLinux OS and CloudLinux OS support

- tests/integration_tests/modules/test_cli.py
```
test: Fix test_failing_userdata_modules_exit_codes
In f24ecef8b, we persist error state across mode invocations during
the same boot. Fix the integration testing accordingly.
```
> test: Fix test_failing_userdata_modules_exit_codes

- cloudinit/config/cc_ssh.py
- tests/unittests/config/test_cc_ssh.py
Fedora core 38 and above, centos 10 stream and all distributions derived from
them do not have the group 'ssh_keys'. Please see the fedora rawhide change
https://src.fedoraproject.org/rpms/openssh/c/7a21555354a2c5e724aa4c287b640c24bf108780?branch=rawhide
In those distributions, openssh versions are 9 and above. The private
key permissions are set as 0o600 and the public key permissions are set as
0o644 from sshd-keygen utility. The 'root' group owns the keys.
Please see
https://src.fedoraproject.org/rpms/openssh/c/b615362fd0b4da657d624571441cb74983de6e3f?branch=rawhide
In older releases where 'ssh_keys' group is present, the private key
permissions are set as 0o640. Public key permissions are 0o644. These
releases have openssh version less than 9.
Since cloud-init generates the keys and …
> Fix ssh key permissions for redhat where 'ssh_keys' group is absent

- cloudinit/sources/DataSourceLXD.py
- tests/integration_tests/modules/test_combined.py
- tests/unittests/sources/test_lxd.py
```
fix(lxd): Properly handle unicode from LXD socket
Fixes GH-5300
```
See #5300
> fix(lxd): Properly handle unicode from LXD socket

- cloudinit/sources/DataSourceEc2.py
- tests/unittests/sources/test_ec2.py
Draft as currently untested.
```
fix(ec2): Ensure metadata exists before configuring PBR
Fixes GH-5283
```
https://github.com/canonical/cloud-init/issues/5283
I reproduced the issue on a multi-nic IPv6 only system, then created an AMI with this fix and launched using only the AMI as the difference and no longer see the exception and cannot connect as expected.
> fix(ec2): Ensure metadata exists before configuring PBR

- doc/rtd/reference/breaking_changes.rst
```
docs: Removal of top-level --file breaking change
```
> docs: Removal of top-level --file breaking change

- cloudinit/distros/__init__.py
- cloudinit/sources/DataSourceEc2.py
- tests/unittests/sources/test_ec2.py
Draft PR as this has not been tested in a real environment yet.
```
fix: Check renderer for netplan-specific code
DataSourceEc2 has netplan-specific code that was gated by the
selected activator. However, in practice, the activators are rarely
used. Somebody may have selected a non-netplan renderer without
selecting the proper activator with it. Since this involves rendering
configuration, we should gate on the renderer instead.
Fixes GH-5318
```
> fix: Check renderer for netplan-specific code

- cloudinit/util.py
chore: Add docstrings and types to Version class
> chore: Add docstrings and types to Version class

- cloudinit/config/cc_mounts.py
- cloudinit/distros/bsd.py
- cloudinit/distros/netbsd.py
- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/DataSourceEc2.py
- cloudinit/sources/DataSourceLXD.py
- cloudinit/sources/DataSourceWSL.py
- cloudinit/util.py
- tests/integration_tests/conftest.py
- tests/integration_tests/util.py
- tests/unittests/config/test_cc_ntp.py
- tests/unittests/sources/test_gce.py
- tests/unittests/test_util.py
- tox.ini
Fedora 39 and above comes with python version 3.12. When running `tox -e pylint` on cloud-init, we may experience issue such as the one reported here: https://github.com/pylint-dev/pylint/issues/8782
Minimum version of pylint required in order to support python 3.12 is 3.0.2. Please see https://github.com/pylint-dev/astroid/issues/2201 . Upon further experimentation, it is seen that we need minimum pylint version 3.2.0 for cloud-init. Update tox.ini in order to use this pylint version.
> Update pylint version in order to support python 3.12

- cloudinit/sources/DataSourceAzure.py
- tests/integration_tests/datasources/test_azure.py
- tests/unittests/sources/test_azure.py
```
fix(azure): disable use-dns for secondary nics
DNS resolution through secondary NICs is not supported on Azure. Disable
it.
Without this, we see seconds of delay resolving urls in cloud-init logs
from Jammy+, see SF ticket.
Per cjp256's comment, the first NIC under metadata.imds.network is ensured
to be the primary one. We use this to determine primary NICs instead of
relying on fragile driver and/or NIC names.
Fixes: SF #00380708
Co-authored-by: Calvin Mwadime <calvin.mwadime@canonical.com>
```
Supersedes https://github.com/canonical/cloud-init/pull/5180, see comments for more context.
Closes:
- https://warthogs.atlassian.net/browse/CPC-4224
- https://warthogs.atlassian.net/browse/CPC-3999
- https://bootstack.canonical.com/cases/00380708
```bash
make deb
export …
```
> fix(azure): disable use-dns for secondary nics

- cloudinit/net/netplan.py
- tests/unittests/test_net.py
```
fix(netplan): Fix predictable interface rename issue
When predictable naming is disabled, the following command may exit with
a non-zero exit code.
udevadm test-builtin net_setup_link
This code only ran to check for udev rename races, which cannot happen
when systemd renaming is disabled. Skip when disabled.
Fixes GH-3950
```
https://github.com/canonical/cloud-init/issues/3950
> fix(netplan): Fix predictable interface rename issue

- cloudinit/distros/__init__.py
- tests/unittests/distros/test__init__.py
When sudo is compiled with the `secure-path` option and the configuration file exists in `/usr/etc` and not in `/etc` take the configuration in `/usr/etc` into account. If the desired include directive exists in the system (`/usr/etc` ) configuration there is nothing to do if there is no file in `etc`.
- [x ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ x] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
> Support sudoers in the "usr merge" location

- cloudinit/config/cc_disk_setup.py
Fixes https://github.com/canonical/cloud-init/issues/5246
Also downgrade a warning log
> Add nvme support

- .github/workflows/check_format.yml
- .github/workflows/scheduled.yml
- .github/workflows/unit.yml
```
ci: Move lint tip and py3-dev jobs to daily
These jobs give us useful signal, but we don't want them blocking
PR merges, so run them daily instead of per-PR.
```
A previous push of this PR had the daily jobs run per-PR so that I could test that they run appropriately. The results for them can be found here:
https://github.com/canonical/cloud-init/actions/runs/9305890839?pr=5347
> ci: Move lint tip and py3-dev jobs to daily

- cloudinit/distros/__init__.py
- cloudinit/distros/alpine.py
- tests/unittests/distros/test_alpine.py
```
feat(alpine): add support for Busybox adduser/addgroup
By default Alpine Linux provides Busybox utilities such as adduser
and addgroup for managing users and groups. Optionally the Alpine
"shadow" package provides the traditional useradd/groupadd utilities.
Add fallback support for the Busybox user/group management utilities
for Alpine Linux.
```
> feat(alpine): add support for Busybox adduser/addgroup

- cloudinit/config/cc_growpart.py
- cloudinit/distros/bsd.py
- tests/unittests/config/test_cc_growpart.py
```
growpart: Fix behaviour for ZFS datasets
on FreeBSD, ZFS datasets aren't exposed directly as disks devices, so
stats will fail. Currently, this means that growpart will be skipped for
FreeBSD ZFS volumes, even tho we are perfectly capable of  resizing ZFS.
- Return fs from devent2dev(), which is now inappropriately named
- Add get_zfs_size() helper, and extend get_size() to accept an `fs`
parameter.
- Add _call_resizer() helper, to avoid an indent on `if fs == zfs`
Sponsored by:	The FreeBSD Foundation
```
> growpart: Fix behaviour for ZFS datasets

- cloudinit/config/modules.py
- tests/integration_tests/modules/test_ubuntu_pro.py
```
tests: fix integration tests for ubuntu pro 32.3 release
Now that pro 32.3 is published, drop duplicated ubuntu_advantage
alias keys from test user-data because pro 32.3 can now react to
ubuntu_pro keys.
Also, pro v. 32.3 changed how it logs some messages for various
systemd services. To obtain ua-auto-attach.service logs we now
invoke systemctl status ua-auto-attach.service instead of looking
at /var/log/ubuntu-advantage.log.
Additionally fix bug in clipped log message which didn't log the
full name of the renamed module:
Module has been renamed from cc_old_name to c.
```
Failed jenkins jobs representing this failure to discover Skip logs in /var/log/ubuntu-advantage.log
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-azure/451/testReport/tes …
> tests: fix integration tests for ubuntu pro 32.3 release

- cloudinit/cmd/devel/logs.py
- cloudinit/cmd/main.py
- tests/unittests/cmd/devel/test_logs.py
- tests/unittests/conftest.py
- tests/unittests/test_cli.py
```
```
`tests/unittests/cmd/devel/test_logs.py` would fail if you ran the file on its own due to subp happening on import.
The 2nd commit is just some extra cleanup.
> Ensure subp doesn't run during logs.py import

- tests/integration_tests/modules/test_growpart.py
```
tests: fix expect logging from growpart on devent with partition
Commit e520c944e changed resize logging by altering providing the
device path which includes the partition number instead of a tuple
when both device and partiiton number of set.
Fix expected log message.
```
CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_OS_IMAGE=oracular CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE tox -e integration-tests -- tests/integration_tests/modules/test_growpart.py::TestGrowPart::test_grow_part
```
Jenkins test failure showing inability to match expected log
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-oracular-lxd_vm/8/testReport/junit/tests.integration_tests.modules.test_growpart/TestGrowPart/test_grow_part/
```
> tests: fix expect logging from growpart on devent with partition

- cloudinit/sources/DataSourceEc2.py
- tests/unittests/sources/test_ec2.py
```
fix(ec2): Correctly identify netplan renderer
```
Found with tests/integration_tests/modules/test_hotplug.py::test_multi_nic_hotplug
> fix(ec2): Correctly identify netplan renderer

- doc/rtd/static/css/custom.css
```
docs: Adjust CSS to increase font weight across the docs.
A common problem users encounter is that the font weight in the
documentation is too thin/hard to read. 
Fixes GH-4146
```
> Increase docs font weight

- tests/integration_tests/modules/test_hotplug.py
```
test(hotplug): fix race getting ipv6
Add retry logic for _get_ip_addr to properly get the ipv6 address.
The  output of `ip --brief addr` can show
ens6 UP 192.168.13.34/20 metric 200 fe80::8fd:afff:fea3:f4ad/64 instead of
ens6 UP 192.168.13.34/20 metric 200 2a05:d012:ea0:c500:1373:45f4:aa83:517c/128 fe80::8fd:afff:fea3:f4ad/64 if executed so early that the kernel didn't expose the wanted ipv6 address.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-ec2/lastCompletedBuild/testReport/tests.integration_tests.modules/test_hotplug/test_multi_nic_hotplug_vpc/
```
...
assert "routing-policy" in new_nic_cfg
>           assert [
{"from": secondary_priv_ip4, "table": 101},
{"from": secondary_priv_ip6, "table": 101},
] == …
```
> test(hotplug): fix race getting ipv6

- cloudinit/config/cc_final_message.py
- cloudinit/config/cc_growpart.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- cloudinit/sources/DataSourceNone.py
- cloudinit/sources/__init__.py
- doc/rtd/explanation/configuration.rst
- doc/rtd/explanation/format.rst
- tests/unittests/config/test_cc_final_message.py
- tests/unittests/config/test_cc_growpart.py
*   fix(final_message): do not warn on datasourcenone when single ds
Avoid warning level log "Used fallback datasource" when base
configuration defines `datasource_list: [ None ]`.
Using DataSourceNone in this case is desired behavior.
Also drop unused is_disconnected property from DataSource
which was only used by DataSourceNone in cc_final_message.
Instead compare based on dsname property.
Fixes: GH-5192
* fix(growpart): correct growpart log message to include value of mode
Affects snapd UC24 which sets `datasource_list: [ None ]' in some configs
> Fix snapd growpart and final message warnings

- cloudinit/config/cc_growpart.py
- tests/unittests/config/test_cc_growpart.py
```
fix: Stop attempting to resize ZFS in cc_growpart on Linux
In e520c944, growing ZFS was added to cc_growpart to support BSD
systems. However, this left Linux in a state where it will fail to
resize and log a warning anytime it encounters ZFS. This commit
ensures that the cc_growpart resize is only attempted on BSD (or any
other system that uses `growfs`). This leaves cc_resizefs to grow the
filesystem on Linux.
This is admittedly a hack solution and long term, we should ensure
that ZFS gets grown in one module, and find a better long-term
abstraction for volume managers.
```
> fix: Stop attempting to resize ZFS in cc_growpart on Linux

- doc/rtd/reference/network-config-format-v2.rst
docs: network-config v2 ethernets are of type object
The schema (cloudinit/config/schemas/schema-network-config-v2.json) and most other examples show that the `ethernets` field should contain an object with a map of type:
configuration id -> definition
> docs: network-config v2 ethernets are of type object

- cloudinit/config/cc_apt_configure.py
- cloudinit/distros/__init__.py
- cloudinit/distros/alpine.py
- cloudinit/distros/amazon.py
- cloudinit/distros/arch.py
- cloudinit/distros/freebsd.py
- cloudinit/distros/gentoo.py
- cloudinit/distros/netbsd.py
- cloudinit/distros/opensuse.py
- cloudinit/distros/package_management/apt.py
- cloudinit/distros/package_management/package_manager.py
- cloudinit/distros/package_management/snap.py
- cloudinit/distros/photon.py
- cloudinit/distros/rhel.py
- tests/unittests/config/test_apt_source_v1.py
- tests/unittests/config/test_apt_source_v3.py
- tests/unittests/distros/package_management/test_apt.py
- tests/unittests/helpers.py
- tests/unittests/util.py
```
fix(apt): Enable calling apt update multiple times
This is required to configure apt when dependency is not installed.
Fixes GH-5223
```
**note for reviewers**: does this kwarg name make it obvious what it is supposed to do? 
Calling this multiple times isn't ideal, but we support installing gpg as needed for apt-configure, and without calling apt-update after the gpg install we won't be able to actually install packages whose repositories are configured in apt_configure, so our hands are tied if we want to continue to support this for minimal images.
Fixes https://github.com/canonical/cloud-init/issues/5223
> fix(apt): Allow opt-in for calling apt update multiple times

- cloudinit/config/schemas/schema-cloud-config-v1.json
- doc/examples/cloud-config-user-groups.txt
For creating users and groups, it is possible to pass a `sudo` option to the
config file that accepts a sudo rule. The option can be a sudo rule string,
a list of sudo rule strings or `False` to explicitly deny sudo usage. Update
examples to show how a list of strings can be used with `sudo` option.
> doc: update examples to reflect alternative ways to provide `sudo` option

- cloudinit/config/schema.py
- pyproject.toml
- tests/unittests/sources/test_akamai.py
```
typing: add no_implicit_optional lint
Explicit optional types are preferred and the default in mypy >= 0.980[1].
Add the config to check for this and fix any instance of the lint error.
References:
[1] https://mypy.readthedocs.io/en/stable/config_file.html#confval-implicit_optional
```
> typing: add no_implicit_optional lint

- cloudinit/config/schema.py
- tests/unittests/config/test_schema.py
During initialization, schema validator may throw warning messages if it finds
the provided configuration does not agree with the schema definition:
schema.py[WARNING]: Invalid cloud-config provided
In reality, even if the configuration does not agree with the schema, it may
sometimes still work. Improve the error message to make it more factual instead
of broadly claiming that the config is broken.
fixes: GH-5399
> Improve schema validator warning messages on initialization

- config/cloud.cfg.tmpl
- systemd/cloud-config.service.tmpl
- systemd/cloud-init.service.tmpl
```
perf(set_passwords): Run module in Network stage
Cloud-init blocks login until Config stage completes[1] to prevent users
from connecting to the instance via ssh prior to user configuration[2].
To enable faster ssh, cloud-init can simply move the set_passwords
module sooner in boot. This follows precedent of previous races of this
kind[3], and it effectively reverts b3c9b6a79c85e and while moving the set_passwords
module into Network stage.
The snap and grub_dpkg modules take a significant amount of time due to
runtime of external commands. This should improve time to ssh for all
users of those modules.
This will make both chpasswd and passwd run earlier in boot than before.
This should be safe, since chpasswd and passwd both use PAM, which to my
knowledge just requires r/w access to …
```
> perf(set_passwords): Run module in Network stage

- cloudinit/net/netplan.py
- tests/unittests/test_net.py
```
feat(netplan): Improve network v1 -> network v2 performance
When converting network v1 to network v2, cloud-init might need to
know whether the backend network system supports ipv6 mtu. Previously
cloud-init was always calling `netplan info` when converting from v1
to v2 to know whether this feature is supported. With this change,
cloud-init only calls `netplan info` if it is required to render the
configuration (i.e. if MTU needs to be configured for ipv6).
This code change works by changing a property which always gets
referenced into a function which only gets referenced when it is
needed.
This removes ~0.2s from network render time on all Ubuntu platforms
that require converting from network v1 to network v2.
On a local LXD VM running Ubuntu Noble (24.04), this removes 0.2 seconds …
```
> perf(netplan): Improve network v1 -> network v2 performance

- doc/rtd/reference/network-config-format-v1.rst
```
docs: Remove mention of resolv.conf
Use of resolv.conf is renderer-specific.
Not every renderer uses it.
```
> docs: Remove mention of resolv.conf

- tests/unittests/config/test_cc_disk_setup.py
- tests/unittests/config/test_cc_seed_random.py
```
fix(pytest): Fix broken pytest gdb flag
When pyest is called with --pdb, some tests fail. The test failure
appears to be due to unittest mocking subp prior to pytest fixtures
being created, which causes autospec to fail on subp, since subp is
already mocked. Fix it by converting these tests to use pytest.
```
The following:
```
.tox/py3/bin/python -m pytest -vvvv --showlocals --pdb
```
now passes
> fix(pytest): Fix broken pytest gdb flag

- cloudinit/sources/azure/imds.py
- tests/unittests/sources/azure/test_imds.py
Transient failures in fetching metadata from IMDS would not retry. get_metadata_from_imds() is now using time.monotonic() for measuring time instead of time.time() causing the deadline check to fail on first check (monotonic() values will always be less than time()).
Update azure.imds.ReadUrlRetryHandler to use time.monotonic() instead of time.time().
> fix(azure): fix discrepancy for monotonic() vs time()

- tests/integration_tests/cmd/test_status.py
```
test: Update schema validation error in integration test
Message changed in 9c3258f4
```
https://github.com/canonical/cloud-init/pull/5404
> test: Update schema validation error in integration test

- debian/changelog
- debian/patches/backport-ubuntu-pro-rename.patch
- debian/patches/series
```
feat(pro): deprecate ubuntu_advantage key for ubuntu_pro
Backport deprecatation of ubuntu_advantage_key in favor of ubuntu_pro
to standardize product branding for Ubuntu Pro.
This allows for common behavior, documentation and tooling on all
supported and maintained releases including those Ubuntu releases
under active Expanded Security Maintenance(ESM).
LP: #2067660
```
Rebase merge:uise separate commits
http://pad.lv/2067660
```
build-package
sbuild --dist=bionic --arch=amd64 --arch-all ../out/cloud-init_23.1.2-0ubuntu0~18.04.2.dsc
lxc launch ubuntu-daily:bionic test-pro-b
lxc file push cloud-init_23.1.2-0ubuntu0~18.04.2_all.deb test-pro-b/
lxc exec test-pro-b -- apt update
lxc exec test-pro-b -- apt upgrade  --yes
lxc exec test-pro-b -- apt install ubuntu-advantage-tools --yes
lxc …
```
> Ubuntu/bionic 23.1.x: backport ubuntu_pro config keys, deprecate ubuntu_advantage

- cloudinit/sources/DataSourceOpenStack.py
- tests/unittests/sources/test_openstack.py
- tools/.github-cla-signers
```
OpenStack: Append interface for IPv6 link-local metadata address
Link-Local IPv6 addresses (fe80::/10) without a scope_id or interface are invalid,
see [1]. This made urllib3 reject an URL of `http://[fe80::a9fe:a9fe]` as invalid
argument.
This change now appends an interface in the proper URL-encoded format ([2]).
[1] https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/netinet_in.h.html
[2] https://datatracker.ietf.org/doc/html/rfc6874
Fixes GH-5422
```
* see https://github.com/canonical/cloud-init/pull/1805#issuecomment-2177441491
* Fixes GH-5422
Start VM on OpenStack with only IPv6.
https://github.com/canonical/cloud-init/pull/1805#issuecomment-2177441491
> fix (openstack): Append interface / scope_id for IPv6 link-local metadata address

- tests/integration_tests/modules/test_apt_functionality.py
```
tests: hard-code curtin-dev ppa instead of canonical-kernel-team
Avoid integration test dependencies on PPAs that we don't own.
The canonical-kernel-team PPA will trail publication of packages
to the devel series sometimes by many weeks. Also, their process
may change in the future and the daily canonical-kernel-team PPA
may not be used at some point in the future.
Some of our apt-related integration tests are only asserting that
different formats of user-data can setup and assert valid PPA
signing keys to 3 separate PPAs on a single instance launch to avoid
the costs of launching three separate instances to test different
user-data formats.
For these tests, we can hard-code a known series and PPA without
degrading the value of the simple test.
Shift our canonical-kernel-team PPA …
```
> tests: hard-code curtin-dev ppa instead of canonical-kernel-team

- cloudinit/config/cc_yum_add_repo.py
- doc/examples/cloud-config-yum-repo.txt
- tests/unittests/config/test_cc_yum_add_repo.py
'metalink' config can be specified instead or along with 'baseurl' in the yum repository config. Add support for specifying metalink instead of 'baseurl'.
Fixes GH-5359
> Support metalink in yum repository config

- cloudinit/net/cmdline.py
- tests/unittests/test_net.py
- tools/.github-cla-signers
klibc's ipconfig format [1] states that PROTO values 'none', 'off', 'static' and blank all mean no autoconfiguration, but cloud-init parser is too strict and accepts only the first.
LP: #2065787
[1] https://git.kernel.org/pub/scm/libs/klibc/klibc.git/plain/usr/kinit/ipconfig/README.ipconfig
> fix(net): klibc ipconfig PROTO compatibility

- cloudinit/sources/DataSourceLXD.py
- tools/.github-cla-signers
Fix for requests 2.32.2+:
Add get_connection_with_tls_context() for requests 2.32.2 as suggests:  https://github.com/psf/requests/pull/6710
> fix for python3-requests 2.32.2

- tests/integration_tests/test_ds_identify.py
```
test: Add ds-identify integration test coverage
LXD instances don't have a defined datasource_list and therefore
implicitly exercise ds-identify. Add coverage for all other platforms.
```
Currently LXD integration tests exercise ds-identify, but I don't know of any others that do - just some [unit tests](https://github.com/canonical/cloud-init/blob/main/tests/unittests/test_ds_identify.py).
> test: Add ds-identify integration test coverage

- cloudinit/cmd/main.py
- cloudinit/config/schema.py
- cloudinit/features.py
- cloudinit/util.py
- tests/unittests/config/test_schema.py
- tests/unittests/test_data.py
- tests/unittests/test_features.py
- tests/unittests/test_log.py
Add deprecation version knob for stable release distros. This allows distros to set an "initial release" version for the cloud-init release on a stable distro, and any newly added deprecation in future releases should log at an INFO level. 
with the following cloud-config:
```yaml
#cloud-config
grub-dpkg:
enabled:
false
users:
- name: osadmin
lock-passwd: false
sudo: ["ALL=(ALL) NOPASSWD:ALL"]
ssh-authorized-keys:
- ssh-rsa "AAAAB3NzaC1yc2EAAAADAQABAAABAQCc/K1T62elOkJKc94sWovn06RE7D274Fxx5n+eT/oClAwk7632awMtWjO+lIRpzOlEcYCR6wexlmL9mZNEFJoROMMRyCxRilNAiDKOq0X5j1HXY2ky9KjtLxo2b8yXFRBcYKK4W8aHU94NkNek81jdi9lC+L6jUrZ25d7xylqnEbd4TgrBphiowdh5B3RY+j6ePthLWWhHopRcVDgq91yYacelCCIfSDaGBya9iXPZSwoKtPin4n5PdSGmSOA3fIkvV5JjLS1QbuY5tzhXKuH9MdAqrvutF1bprs/GDf0IY8DO7DDoo8rXjhhgGtCdg1i5UitZIAM3hn/Vk5F//5e …
```
> deprecation version boundary

- cloudinit/sources/helpers/openstack.py
Fixes #5364 
```
fix: Do not add the vlan_mac_address field into the VLAN object
Fixes GH-5364
```
> Do not add the vlan_mac_address field into the VLAN object

- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_grub_dpkg.py
- tests/unittests/config/test_cc_package_update_upgrade_install.py
- tests/unittests/config/test_cc_users_groups.py
- tests/unittests/config/test_schema.py
```
fix(schema): permit deprecated hyphenated keys under users key
Both hyphenated and underscore delimited key names are permitted
by cloudinit/distros/ug_util.py#L114 due to magic replacement
of key names.
Since this is still valid json schema, add the necessary hyphenated
aliases for all users/groups keys. Because the goal in the future is
to only support one config key for a given configuraion option, add
deprecated keys to thos schema definitions.
Also drop the description key from the deprecates lock-passwd schema
key.
Any deprecated schema key which provides a suggested replacement should
not provide duplicated key descriptions as the preferred replacement
will provided the necessary context.
Fixes GH-5454
```
Expect a supplemental PR which allows downstream stable images which …
> Schema support deprecated users groups hyphenated keys

- cloudinit/sources/helpers/openstack.py
- tests/unittests/sources/helpers/test_openstack.py
Ensure that properties for bonded interfaces are translated properly from the OpenStack network_config.json format.
Fixes #5366
```
fix: Ensure properties for bonded interfaces are properly translated
There is a discrepancy between the properties key name formatting in
the OpenStack network_data.json and cloudinit network-config.json
specifications. Ensure `bond_` is translated to `bond-` when the
OpenStack configuration is parsed by cloudinit.
Fixes GH-5366
```
> Translate key names for OpenStack bond properties

- cloudinit/config/schema.py
- tests/unittests/config/test_schema.py
```
fix(schema): Don't report changed keys as deprecated
```
also fixes issue where unittests run with version boundary set
> fix(schema): Don't report changed keys as deprecated

- cloudinit/config/schema.py
- cloudinit/util.py
- tests/unittests/test_log.py
```
fix: dont double-log deprecated INFOs
```
> fix: dont double-log deprecated INFOs

- cloudinit/config/schema.py
- cloudinit/util.py
- tests/integration_tests/cmd/test_schema.py
- tests/integration_tests/cmd/test_status.py
- tests/integration_tests/modules/test_combined.py
- tests/unittests/distros/test_create_users.py
```
tests: integration tests aware of features.DEPRECATION_INFO_BOUNDARY
```
Failed jenkins jobs represented deprecation message errors in integration tests https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-lxd_container/454/ .
```
CLOUD_INIT_OS_IMAGE=jammy CLOUD_INIT_PLATFORM=lxd_container CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily tox -e integration-tests -- tests/integration_tests/cmd/test_schema.py::TestSchemaDeprecations::test_clean_log tests/integration_tests/cmd/test_schema.py::TestSchemaDeprecations::test_schema_deprecations tests/integration_tests/cmd/test_status.py::test_status_json_errors tests/integration_tests/modules/test_combined.py::TestCombined::test_deprecated_message
```
> tests: integration tests aware of features.DEPRECATION_INFO_BOUNDARY

- cloudinit/config/schemas/schema-cloud-config-v1.json
- doc/module-docs/cc_rh_subscription/example2.yaml
- tests/unittests/config/test_cc_rh_subscription.py
- tools/.github-cla-signers
```
fix(rh_subscription): add string type to org
Per [1], org's correct type is string. Added as new type and deprecated
integer.
References:
[1] https://github.com/candlepin/subscription-manager/blob/b6fad11e7783ae414fe88fdecee57d8db5c8e292/man/subscription-manager.8#L589
Fixes GH-5382
Co-authored-by: pneigel-ca <patrick.neigel@gmail.com>
```
> fix(rh_subscription): add string type to org

- tests/integration_tests/datasources/test_nocloud.py
```
tests: update nocloud deprecation test for boundary version (#PR)
```
Failing jenkins test 
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-lxd_vm/469/testReport/junit/tests.integration_tests.datasources.test_nocloud/TestSmbios/test_smbios_seed_network/
```
CLOUD_INIT_OS_IMAGE=jammy CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily tox -e integration-tests -- tests/integration_tests/datasources/test_nocloud.py::TestSmbios::test_smbios_seed_local
```
> tests: update nocloud deprecation test for boundary version

- tests/integration_tests/cmd/test_status.py
- tests/integration_tests/test_ds_identify.py
```
test: Update integration tests to pass on focal
- Update deprecation test to include focal.
- Update test using `cloud-id` appropriately
```
> Focal test updates

- cloudinit/distros/__init__.py
- tests/integration_tests/modules/test_combined.py
- tests/unittests/distros/test_create_users.py
```
tests: reduce deprecation count when below deprecation info boundary
```
Jenkins failure https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-gce/lastSuccessfulBuild/testReport/junit/tests.integration_tests.modules.test_combined/TestCombined/test_deprecated_message/
```
for REL in focal jammy noble mantic oracular; do 
CLOUD_INIT_OS_IMAGE=$REL CLOUD_INIT_PLATFORM=lxd_container CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE tox -e integration-tests -- tests/integration_tests/modules/test_combined.py::TestCombined::test_deprecated_message;
done
```
> tests: reduce deprecation count when below deprecation info boundary

- tests/integration_tests/cmd/test_status.py
```
test: Fix no default user in test_status.py
```
> test: Fix no default user in test_status.py

- ChangeLog
- cloudinit/distros/__init__.py
- cloudinit/version.py
- debian/changelog
- tests/integration_tests/cmd/test_status.py
- tests/integration_tests/modules/test_combined.py
- tests/unittests/config/test_cc_ubuntu_pro.py
- tests/unittests/distros/test_create_users.py
Looking to enqueue a release of 24.2 for noble
```
new_upstream_snapshot.py -c 24.2
quilt push -a
tox -e py3
quilt pop -a
mkdir ../dl
cd ../dl/
wget https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/cloud-init/24.2-0ubuntu1/cloud-init_24.2.orig.tar.gz
cd ../cloud-init
build-package
sbuild --dist=noble --arch=amd64 --arch-all ../out/cloud-init_24.2-0ubuntu1~24.04.1.dsc
```
> Ubuntu/noble: new_upstream_snapshot.py -c 24.2 for release

- cloudinit/net/openbsd.py
- tools/.github-cla-signers
```
fix(openbsd): fix mtu on newline in hostname files
The /etc/hostname.* files should have the mtu on
a separate line otherwise it gives error:
ifconfig: mtu: bad value
The lines are executed in order by ifconfig and
mtu should be on it's own line.
Fixes: GH-5413
```
use cloud-init with a config drive instead of dhcp
> fix(openbsd): fix mtu on newline in hostname files

- tests/unittests/config/test_cc_mounts.py
```
test: pytestify and cleanup test_cc_mounts.py
Remove `unittest` constructs and remove base classes
```
I did a bit more refactoring on the first test to make it feel more pytest-native, but functionally all tests should still be the same.
> test: pytestify and cleanup test_cc_mounts.py

- cloudinit/net/network_manager.py
- tests/unittests/net/network_configs.py
If an MTU has been provided for the bond interface, ensure it is properly configured. Support for jumbo frames requires that the underlying physical interfaces and the parent bond interface all have the larger MTU configured, not just the physical interfaces. 
```
fix: Set MTU for bond parent interface
If an MTU has been provided for the bond interface, ensure it is
properly configured. Support for jumbo frames requires that the
underlying physical interfaces and the parent bond interface all
have the larger MTU configured, not just the physical interfaces.
```
> Set MTU for bond parent interface

- cloudinit/config/schemas/schema-cloud-config-v1.json
At least one of (or both) 'baseurl' or 'metalink' should be provided for yum repository specification. Add schema changes to enforce it. Without this, with just 'metalink' property set, one would get the schema validator error
\---
Error: Cloud config schema errors: yum_repos.epel-release: 'baseurl' is a required property \---
> schema: add schema rules for 'baseurl' and 'metalink' in yum repo config

- cloudinit/cmd/main.py
- cloudinit/distros/__init__.py
- cloudinit/distros/bsd.py
- cloudinit/util.py
- doc/rtd/reference/cli.rst
- tests/integration_tests/datasources/test_ec2_ipv6.py
- tests/integration_tests/datasources/test_nocloud.py
- tests/integration_tests/test_upgrade.py
- tests/integration_tests/util.py
```
feat: Warn user of unexpected run mode
On systemd, services are started by PID 1. When this doesn't happen, cloud-init
is in an unknown run state and should warn the user.
- Reorder pid log to be able to reuse Distro information.
- Add docstring deprecating util.is_Linux().
```
> feat: Warn user of unexpected run mode

- tests/integration_tests/instances.py
```
fix(test): Fix ip printer for non-lxd
```
https://github.com/canonical/cloud-init/commit/343d2c72f32db8fbe47eb8afa98c15987e9ffba6 gave us a  log with the IP address of an instance, if `KEEP_INSTANCE = True`, which allows on to ssh into an instance immediately after a test finishes, useful for debugging and developing tests.
https://github.com/canonical/cloud-init/commit/937e84c4def1e8c88e27d7e270529403b9a63dcc worked around [a pycloudlib bug](https://github.com/canonical/pycloudlib/issues/316) in this logic which caused some lxd instances to hang/fail, but broke the IP printer logic for all non-lxd platforms.
This brings back the IP printer logic. I tested this on ec2 and lxd.
Run integration test with `KEEP_INSTANCE=True`, check for `Keeping Instance, public ip: x.x.x.x` in the "live …
> fix(test): Fix ip printer for non-lxd

- tests/integration_tests/datasources/test_ec2_ipv6.py
```
tests: revert expectation of exit 2 from cloud-init init --local
Commit 604d80eb introduced assertions expecting exit 2 from the
CLI when calling cloud-init init --local. Revert this test assertion
as only cloud-init status command exits (2) on deprecations/warnings.
Invoking cloud-init's boot stages on the commmand line will only exit
1 if critical errors are encountered to avoid degrading overall
systemd health as seen from cloud-init systemd units. When cloud-init
boot stages encounter recoverable_errors of any type, there is no
need to exit non-zero as those deprecation logs are not-critical to
the health of the system as a whole.
```
Expected integration test failure on ec2 with daily PPA tomorrow because cloud-init init --local (or any direct call to cloud-init stage  doesn't …
> tests: ec2 check status exit code instead of cloud-init init --local

- tests/integration_tests/modules/test_hotplug.py
```
test: Unconditionally skip test_multi_nic_hotplug_vpc
It is pretty consistently failing due to #5373 with no fix in
sight.
```
https://github.com/canonical/cloud-init/issues/5373
> test: Unconditionally skip test_multi_nic_hotplug_vpc

- cloudinit/sources/helpers/openstack.py
- tests/unittests/sources/helpers/test_openstack.py
Ensure DNS server addresses are parsed from the proper location of network_data.json
Fixes #5386 
```
fix: Ensure proper configuration of DNS servers via OpenStack json network config
Ensure DNS server addresses are parsed from the proper location
of network_data.json and that the services entry is not propogated
```
> Fix configuration of DNS servers via OpenStack

- doc/rtd/reference/datasources/ovf.rst
```
doc(OFV): Document how to configure cloud-init
```
https://github.com/canonical/cloud-init/issues/5517
> doc(OFV): Document how to configure cloud-init

- cloudinit/config/cc_yum_add_repo.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- doc/examples/cloud-config-yum-repo.txt
- tests/unittests/config/test_cc_yum_add_repo.py
'mirrorlist' config can be specified instead or along with 'baseurl' in the yum repository config. Add support for specifying mirrorlist instead of 'baseurl'.
Fixes GH-5520
Signed-off-by: Ani Sinha <anisinha@redhat.com>
> Support setting mirrorlist in yum repository config

- tests/integration_tests/datasources/test_caching.py
Fix squashmerged test changes that required extra formatting in commit 550c685c98551f65c30832b186fe091721b48477
Issue introduced by applying minor changes to existing tests in review and merging it before CI finished running the formatting validation job.
> chore(formatting): fix squashed commit test formatting

- cloudinit/sources/DataSourceWSL.py
- doc/rtd/reference/datasources/wsl.rst
- tests/unittests/sources/test_wsl.py
```
fix(wsl): Special handling Landscape client config tags
UP4W business logic is so that its data overrides user at a key (module) 
level.
That means the entire Landscape config is overriden if both agent data
and user data contains config for that module.
Yet, for better usability, computer tags must be assignable per instance.
That's not possible with agent.yaml, because it's meant to be global.
Its config data affects all Ubuntu WSL instances.
Thus this aims to make a special case for landscape.client.tags,
if present in user provided data (either Landscape or local user -
whatever is picked up before merging with agent.yaml)
its value overwrites any tags set by agent.yaml.
Only landscape.client.tags are treated specially.
The pre-existing merge rules still apply for any other value …
```
> fix(wsl): Special handling Landscape client config tags

- cloudinit/config/cc_write_files.py
- cloudinit/config/cc_write_files_deferred.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- doc/module-docs/cc_runcmd/example1.yaml
- doc/module-docs/cc_write_files/data.yaml
- doc/module-docs/cc_write_files/example6.yaml
- tests/unittests/config/test_cc_write_files.py
- tools/.github-cla-signers
```
feat(write_files): support URI content sources
This change adds an optional `source` key to the `write_files` module,
allowing users to specify a URI from which to load file contents. This
facilitates more flexible multi-part configurations, as file contents
can be managed via external sources such as independent Git
repositories.
Fixes GH-5500
```
Resolves #5500
Unit tests, included, cover:
- `file://` and HTTP URI functionality
- Fallback behavior (i.e. use inline `content` if the provided URI fails to return usable data)
- Updated schema validation
> feat: Support URI sources in `write_files` module

- debian/cloud-init.postinst
```
chore(postinst): Delete unnecessary postinst code
```
1) Delete version gated code
- most recent version gate was 22.1-14-g2e17a0d6-0ubuntu1~22.04.5
- If someone somehow upgraded a Jammy instance to noble without getting the newer Jammy cloud-init package available in jammy-updates, the fix in the postinst would still run since this code exists in all releases of noble.
2) Delete old preseed code. Debian doesn't use our postinst, and we don't use preseed, so just drop it -> we can probably do this with the maas preseed code too but that requires more investigation
> chore(postinst): Delete unnecessary postinst code

- tests/integration_tests/datasources/test_caching.py
- tests/integration_tests/test_kernel_command_line_match.py
```
```
7703634ec048aa00ddf6ef7a5d552004a84c4f04
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-lxd_container/470/
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-lxd_vm/469/
```sh
CLOUD_INIT_PLATFORM=lxd_container tox -e integration-tests -- \
tests/integration_tests/datasources/test_caching.py::test_no_cache_network_only \
tests/integration_tests/datasources/test_caching.py::test_no_cache_with_fallback
CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_OS_IMAGE=focal tox -e integration-tests -- tests/integration_tests/test_kernel_command_line_match.py::test_lxd_datasource_kernel_override
```
> test: fix no ds cache tests

- tools/ds-identify
```
fix(wsl): Put back the "path" argument to wsl_path in ds-identify
Got swallowed by 
https://github.com/canonical/cloud-init/pull/5116/commits/da6b5c437a799bb934c89545c1b077a84d34a51d
The way it is results in wrong invocation of wslpath binary,
thus we never find WSL specific data, disabling cloud-init.
```
1. Have a WSL instance with  `datasources_list=[WSL, NoCloud] # could be something else,as long as there is one more real datasource meant to be not activated`
2. Run cloud-init normally.
3. Look at `/run/ds-identify.log`. It should contain the message "No .cloud-init directories found".
We compute the `.cloud-init` directory correctly but when translating that into a Linux path using `wslpath` then things don't go well.
Unfortunately that's a function built to be mocked, so I don't …
> fix(wsl): Put back the "path" argument to wsl_path in ds-identify

- .github/labeler.yml
- .github/workflows/labeler.yaml
```
fix: auto label doc PRs
Create explicit file to define and pin the actions/labeler's version.
Upgrade breaking changes from action/labeler@v5.
```
The current action should label PRs with changes under `doc/` as `documentation` but it does not, see: https://github.com/canonical/cloud-init/actions/runs/10078086430/job/27862171756?pr=5541.
https://github.com/actions/labeler?tab=readme-ov-file#breaking-changes-in-v5
https://github.com/actions/labeler/releases/tag/v5.0.0
> fix: auto label doc PRs

- doc/rtd/howto/run_cloud_init_locally.rst
- doc/rtd/tutorial/qemu.rst
- tools/.github-cla-signers
- [n/a] I have added unit tests to cover the new behavior under ``tests/unittests/``
- [n/a] I have updated the documentation with the changed behavior.
```
docs: improve qemu command line
The suggested qemu command line in our local execution example
is rather old.
Change the discouraged -hd* options to the new
-device instead.
Further add a chance to use KVM acceleration to speed up the
example.
Finally we had several occasions to be working on x86 only.
We dropped arguments that can not work on cross-arch and
furthermore added a hint at how one could again native
performance on these platforms.
Fixes GH-5050
```
n/a
Use the "How to run cloud-init locally" example
> Improve qemu cmdline

- doc-requirements.txt
- doc/rtd/conf.py
- doc/rtd/explanation/boot.rst
```
doc: add diagram with boot stages
SC-1835
Fixes GH-5334
```
```
tox -e doc && (cd doc/rtd_html/ && python3 -m http.server)
open http://0.0.0.0:8000/explanation/boot.html
```
> doc: add diagram with boot stages

- doc/examples/boothook.txt
- doc/rtd/explanation/format.rst
- doc/rtd/reference/examples.rst
```
doc: Update docs on boothooks
Improve explaination on #cloud-boothook for end-users.
Reorder and improve doc/rtd/explanation/format.rst.
SC-1657
Fixes GH-4542
Co-authored-by: Calvin Mwadime <calvin.mwadime@canonical.com>
```
https://github.com/canonical/cloud-init/pull/5541#pullrequestreview-2196889423
> doc: Update docs on boothooks

- doc/rtd/reference/faq.rst
```
doc(autoinstall): Remove incorrect statements, be more direct
```
Top level keys are no longer ignored, so drop this incorrect statement.
Tailor this section more directly toward subiquity / autoinstall, since
that is where the frequently asked questions come from.
> doc(autoinstall): Remove incorrect statements, be more direct

- doc/examples/cloud-config-datasources.txt
- doc/rtd/reference/datasources/nocloud.rst
```
doc(NoCloud): Categorize the different configuration types
Formally document providing runtime configuration in system configuration.
Introduce names to identify previously unnamed NoCloud concepts.
Add more structure - discrete sections for:
- runtime configuration types
- discovery configuration
- configuration sources
```
Related to https://github.com/canonical/cloud-init/pull/5515
I'm not opposed to changing the new names if better ones are proposed.
I think that it is important to name and group different classes of configuration to create a more structured model for users (and developers) to think about cloud-init.
> Update NoCloud docs

- .github/labeler.yml
```
fix(actions): doc labeler needs all clause instead of default any
Unspecified base match in labeler assumes 'any' for each match
clause. When specifying base-branch and --any-glob-to-any-file either
one of these cases would result in a successful match which would label
all PRs again main as documentation. We need to explicitly specify
'all:' in our labeler match config to ensure BOTH:
- matching file paths related to documentation
-AND-
- targeting a merge against 'main' branch
```
labeler github action appears to have when being triggered by 'old' repo .github/workflow state which results in this PR's documentation label being added. To test this without concern for interaction with prior .github/workflow state, I was able to change the `documentation:` label in .github/labeler.yml …
> fix(actions): doc labeler needs all clause instead of default any

- templates/hosts.aosc.tmpl
```
fix(aosc): add hosts template for AOSC OS
```
Fixed the [issue](https://github.com/AOSC-Dev/aosc-os-abbs/pull/6927) encountered in AOSC OS, which highlighted the missing hosts template for AOSC OS.
This fix has been verified in the latest AOSC package and has been merged into the AOSC OS repository.
> fix(aosc): add hosts template for AOSC OS

- cloudinit/stages.py
- tests/integration_tests/integration_settings.py
- tests/integration_tests/test_instance_id.py
```
feat: Eliminate redundant configuration reads
When instance id hasn't changed and datasource hasn't changed, don't
forcibly reload configuration.
```
On a test system, this avoids reloading the configuration on the second `instancify()`
See the new messages in logs: 
[no-reload.log](https://github.com/user-attachments/files/16351318/no-reload.txt)
> feat: Eliminate redundant configuration reads

- cloudinit/sources/DataSourceNoCloud.py
- cloudinit/sources/DataSourceOVF.py
- cloudinit/util.py
- tests/unittests/test_util.py
```
fix(NoCloudNet): Add network-config support
This enables support for network config v2 and v1 to NoCloud
when used with http / ftp / etc. 
BREAKING_CHANGE: Adds an additional network request to NoCloud.
```
#5561
> fix(NoCloudNet): Add network-config support

- tests/integration_tests/test_instance_id.py
- tests/integration_tests/test_kernel_command_line_match.py
String output changed in 7703634ec0.
Instance-id doesn't change on LXD / Focal.
```
fix: Integration tests
String output changed in 7703634ec0.
Instance-id doesn't change on LXD / Focal.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-lxd_vm/lastCompletedBuild/testReport/
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-lxd_container/lastCompletedBuild/testReport/tests.integration_tests/test_instance_id/test_instance_id_changes/
> fix: Integration tests

- cloudinit/config/cc_mounts.py
- tests/unittests/config/test_cc_mounts.py
```
refactor: update handle function of cc_mounts
The handle function of cc_mounts was hard to grok and had one of the
highest cyclomatic complexity scores in the codebase. Functionally,
the code should be unchanged.
```
> refactor: update handle function of cc_mounts

- cloudinit/sources/DataSourceNoCloud.py
- cloudinit/util.py
```
Commit 5322dca2 introduced an assumption to read_seeded that
network-config must always be present for NoCloud datasource.
Since it is still considered and optional supplemental configuration
allow the read_seeed calls to succeed in the absence of network-config.
Avoids failures seen in tests/integration-tests/datasources/test_nocloud.py::
test_nocloud_seedfrom_vendordata
```
Failing integration test without this changeset
```
CLOUD_INIT_KEEP_INSTANCE=1 CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily CLOUD_INIT_OS_IMAGE=oracular CLOUD_INIT_PLATFORM=lxd_container tox -e integration-tests -- tests/integration_tests/datasources/test_nocloud.py::test_nocloud_seedfrom_vendordata
```
> fix: nocloud no fail when network-config absent

- cloudinit/sources/DataSourceLXD.py
```
fix: Update default LXD meta-data with user meta-data
This was previously unnecessary because:
a. LXD automatically appends the user.meta-data key to default meta-data.
b. In the presence of duplicate keys, PyYAML uses the last key.
This change is part of a series of changes that will enable cloud-init to
avoid depending on undefined behavior. In the future LXD may stop appending
user-defined meta-data to its default meta-data. This change makes
cloud-init forward compatible to LXD for when that change is implemented.
GH-5575
```
Fixes https://github.com/canonical/cloud-init/issues/5575.
Should make cloud-init forward compatible with LXD changes which might be made to address https://github.com/canonical/lxd/issues/13853
> fix: Update default LXD meta-data with user meta-data

- cloudinit/sources/DataSourceIBMCloud.py
- cloudinit/sources/__init__.py
- pyproject.toml
- tests/unittests/sources/test_ibmcloud.py
```
refactor: refactor and fix check_untyped_defs in DataSourceIBMCloud.py
GH-5445
```
> refactor and mypy up ibm datasource

- doc/rtd/development/integration_tests.rst
```
docs: improve integrations testing configuration instructions
```
> doc: improve integrations testing configuration instructions

- cloudinit/url_helper.py
- tests/integration_tests/datasources/test_nocloud.py
- tests/integration_tests/test_kernel_command_line_match.py
tests fixed:
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-lxd_vm/lastCompletedBuild/testReport/tests.integration_tests/test_kernel_command_line_match/test_lxd_datasource_kernel_override_nocloud_net_ds_nocloud_net_s_https___raw_githubusercontent_com_canonical_cloud_init_main_tests_data_kernel_cmdline_match__/
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-lxd_vm/lastCompletedBuild/testReport/tests.integration_tests.datasources.test_nocloud/TestFTP/test_nocloud_ftp_unencrypted_server_succeeds/
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-lxd_vm/lastCompletedBuild/testReport/tests.integration_tests.datasources.test_nocloud/TestFTP/test_nocloud_ftps_encrypted_ …
> fix: Fix integration test failures

- cloudinit/distros/package_management/snap.py
- doc/module-docs/cc_package_update_upgrade_install/data.yaml
- doc/module-docs/cc_package_update_upgrade_install/example2.yaml
- tests/integration_tests/modules/test_package_update_upgrade_install.py
- tests/unittests/config/test_cc_package_update_upgrade_install.py
- tests/unittests/distros/test_ubuntu.py
-- 07102024: updated proposed commit message, reverted behavior to only honor refresh.hold=forever and updated example doc for temporary snap hold.
```
feat(snap): avoid refresh on package_upgrade: true and refresh.hold
When snap refresh.hold is set to forever, an admin is saying they do
not want generic automated refreshes of snaps performed by default.
This should be an indicator to cloud-init to avoid calling snap refresh
on such systems due to a `package_upgrade: true` present in user-data.
For network-limited environments with images which have the snap package
manager but don't want to wait and timeout on snap refresh, the following
user-data can be provided to still allow for package_upgrade: true,
and avoid a 20-30 second wait on snaps being unable to access certain
snap URLs. …
```
> feat(snap): avoid refresh on package_upgrade: true and refresh.hold

- debian/changelog
- debian/patches/no-nocloud-network.patch
- debian/patches/no-single-process.patch
- debian/patches/series
See https://github.com/canonical/cloud-init/pull/5581
> [ubuntu/jammy] revert single process

- cloudinit/util.py
- tests/unittests/test_util.py
```
fix: read_optional_seed to set network-config when present
Commit 5322dca2f added network-config support to nocloud's
read_optional_seed function. It persisted meta-data as
network-config. Add tests and fix to track network-config value.
```
> fix: read_optional_seed to set network-config when present

- cloudinit/net/network_manager.py
The value of `may-fail` in network manager keyfile is a source of confusion as the default value of it is `True` for Network Manager and `False` for network manager renderer implementation. Add a comment to explain why the renderer sets `may-fail` to `False` in its implementation.
> network_manager: add a comment explaining the `may-fail` setting

- debian/patches/no-single-process.patch
```
fix: invalid quilt patch no-single-process.patch
Patch diff was invalid representing a 57 line diff for cloud-init.service
in the diff header. But, the actual diff context was only 56 lines.
This broke the ability to apply all quilt patches with quilt push -a.
Resulting in broken daily build recipe for focal with the following
error message:
patch: **** malformed patch at line 252:
Patch no-single-process.patch does not apply (enforce with -f)
```
Failing daily build https://launchpadlibrarian.net/742766914/buildlog.txt.gz
```
-- Before this PR
quilt push -a  # will fail in the same way as daily recipe
-- After this PR
quilt push -a  # will succeed
tox -e py3 # success
quilt pop -a # succeed
```
> Ubuntu/focal: fix invalid quilt patch for daily recipe builds

- .github/labeler.yml
```
chore(actions): add doc label for any doc related subdir file matches
Recently noticed that doc file changes in nested subdirs were not triggering documentation auto label.
Example of subdir match at
https://github.com/actions/labeler?tab=readme-ov-file#basic-examples
```
documentation PR that didn't auto-label 
https://github.com/canonical/cloud-init/pull/5595
> chore(actions): add doc label for any doc related subdir file matches

- cloudinit/config/cc_resizefs.py
- tests/unittests/config/test_cc_resizefs.py
```
fix(btrfs): Version parsing
Fixes GH-5614
```
#5614
> fix(btrfs): Version parsing

- setup.py
Fixes #5613
```
<fix>(systemd) Correct location of installed drop-in files
As noted in the systemd documentation, /etc is reserved for "System
units created by the administrator" while the lib directory should be
used by "System units installed by the distribution package manager".
Fixes GH-5613
```
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1078180
https://manpages.debian.org/bookworm/systemd/systemd.unit.5.en.html
Validate that cloud-init installations currently include `/etc/systemd/system/sshd-keygen@.service.d/disable-sshd-keygen-if-cloud-init-active.conf`.  After this change, the file is installed as `/usr/lib/systemd/system/sshd-keygen@.service.d/disable-sshd-keygen-if-cloud-init-active.conf`
> fix install location of systemd drop-in configs

- tests/integration_tests/modules/test_ca_certs.py
```
tests: fix test_ca_certs.py for gcp
Avoid exclusive expectations that cloud-init is the only agent
registering certificates in a system to
/etc/ssl/certs/ca-certificates.crt.
On Google Cloud Platform, Google Guest Agent does setup root certs
which makes performing a checksum of ca-certificates.crt incorrect due
to extra certs present in ca-certificates.crt.
Adapt test to assert that cloud-init's cert is contained in
ca-certificates.crt but not exclusive content of the file.
Fixes GH-5609
```
Failing jenkins job
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-gce/145/testReport/tests.integration_tests.modules.test_ca_certs/TestCaCerts/test_cert_installed/
https://github.com/canonical/cloud-init/issues/5609
```
CLOUD_INIT_OS_IMAGE=noble …
```
> tests: fix test_ca_certs.py for gcp

- cloudinit/apport.py
- cloudinit/cmd/devel/logs.py
- cloudinit/stages.py
- cloudinit/util.py
- tests/unittests/cmd/devel/test_logs.py
- tests/unittests/conftest.py
- tests/unittests/test_apport.py
- tests/unittests/test_cli.py
```
feat: collect-logs improvements
* Collect sensitive data by default since we ask for it more often
than not
* Output warning that we're collecting sensitive data
* Glob most of /run/cloud-init, /etc/cloud, and /var/lib/cloud
* Stop creating empty directories in the tarball
* Require running as root given that the logs are root read-only
* Update apport accordingly
```
> Collect logs improvements

- cloudinit/config/schemas/schema-cloud-config-v1.json
- doc/rtd/conf.py
- doc/rtd/templates/module_property.tmpl
- doc/rtd/templates/property_deprecation.tmpl
- tests/unittests/config/test_cc_ca_certs.py
- tests/unittests/config/test_cc_growpart.py
- tests/unittests/config/test_cc_grub_dpkg.py
- tests/unittests/config/test_cc_package_update_upgrade_install.py
- tests/unittests/config/test_cc_ubuntu_pro.py
- tests/unittests/config/test_cc_update_etc_hosts.py
- tests/unittests/config/test_cc_users_groups.py
- tests/unittests/config/test_schema.py
- tox.ini
Fix incorrectly redacted module property documentation for `Users and Groups`  and `Rsyslog` for nested JSON schemas which contain alternative `oneOf` schemas.
The bulk of this work was made easier by adding the ability to debug the rendered RST files to see bogus white-space indentation that sphinx was able to smooth out.
When building docs, a developer/reviewer can now look at individually rendered RST content for any config module with the following environment variable:
```
CLOUD_INIT_DEBUG_MODULE_DOC_FILE=/tmp/doc.cc_rsyslog CLOUD_INIT_DEBUG_MODULE_DOC=cc_rsyslog tox -e doc
``` 
To render all module docs `CLOUD_INIT_DEBUG_MODULE_DOC=all` can be provided instead
--- See individual commits
```
tox -e doc
xdg-open doc/rtd_html/reference/modules.html   # Navigate to rsyslog and "users …
```
> Doc module render fixes

- tests/integration_tests/modules/test_ca_certs.py
Remove additional \n which is not present if only one ca_cert is in the instance.
```
test: fix ca_certs int test
Remove additional \n which is not present if only one ca_cert is in the
instance.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-lxd_container/488/testReport/junit/tests.integration_tests.modules.test_ca_certs/TestCaCerts/test_cert_installed/
> test: fix ca_certs int test

- doc/rtd/development/datasource_creation.rst
- doc/rtd/reference/datasource_dsname_map.rst
Minor updates to docs to tell DS creators they need to add dsname entries to datasource_dsname_map.rst
> Update docs when generating new Datasource

- tests/integration_tests/cmd/test_status.py
```
fix(tests): use instance.clean/restart instead of clean --reboot
Directly calling execute("cloud-init clean --logs --reboot") on
an integration instances also involves awaiting a new boot id upon
next interaction with with instance to ensure a reboot has actually
taken place already on this target machine.
Slow responding test instances/platforms may not completed the shutdown
restart sequence yet when trying to iteract with an immediate blocking
call to execut("cloud-init status --wait") which may exit early if accessing
the prior instance boot before the reboot occurred.
It is preferable to use inspect /proc/sys/kernel/random/boot_id before
issuing a reboot request and block until a delta is seen in boot_id.
This blocking wait on reboot and new boot_id is encapsulated inside …
```
> fix(tests): use instance.clean/restart instead of clean --reboot

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/errors.py
- tests/unittests/sources/test_azure.py
```
feat(azure): add PPS support for azure-proxy-agent
This PR adds PPS support for azure-proxy agent and improves error logging.
```
> azure: add PPS support for azure-proxy-agent

- cloudinit/sources/DataSourceWSL.py
- doc/rtd/reference/datasources/wsl.rst
- tests/unittests/sources/test_wsl.py
```
fix(sources/wsl): no error with empty .cloud-init dir (SC-1862)
Do not treat the emptiness of .cloud-init/ as an error in the logs
if agent.yaml is present.
Fixes GH-5632
```
> fix(sources/wsl): no error with empty .cloud-init dir (SC-1862)

- cloudinit/distros/__init__.py
- cloudinit/distros/alpine.py
- cloudinit/distros/bsd.py
- cloudinit/distros/freebsd.py
- cloudinit/distros/netbsd.py
- cloudinit/distros/networking.py
- cloudinit/distros/openbsd.py
- tests/integration_tests/modules/test_users_groups.py
- tests/unittests/distros/test_create_users.py
- tests/unittests/distros/test_dragonflybsd.py
- tests/unittests/distros/test_freebsd.py
- tests/unittests/distros/test_netbsd.py
- tests/unittests/distros/test_openbsd.py
```
fix: cc_user_groups incorrectly assumes "useradd" never locks password
Currently cc_user_groups assumes that "useradd" never locks the password
field of newly created users. This is an incorrect assumption.
From the useradd manpage:
'-p, --password PASSWORD
The encrypted password, as returned by crypt(3). The default is to
disable the password.'
That is, if cloud-init runs 'useradd' but does not pass it the "-p"
option (with an encrypted password) then the new user's password field
will be locked by "useradd".
cloud-init only passes the "-p" option when calling "useradd" when
user-data specifies the "passwd" option for a new user. For user-data
that specifies either the "hashed_passwd" or "plain_text_passwd"
options instead then cloud-init calls "useradd" without the "-p" option
and …
```
> fix: cc_user_groups incorrectly assumes "useradd" never locks password field

- cloudinit/config/cc_mounts.py
- tests/unittests/config/test_cc_mounts.py
```
fix: properly handle blank lines in fstab
```
> fix: properly handle blank lines in fstab

- doc/rtd/reference/network-config-format-v2.rst
```
docs: Clarify v2 set-name behavior
```
https://github.com/canonical/cloud-init/blob/8bc3e42543d6be2624a439fe0b72b4546928667e/cloudinit/net/__init__.py#L613
> docs: Clarify v2 set-name behavior

- cloudinit/sources/DataSourceScaleway.py
- tests/unittests/sources/test_scaleway.py
- tools/.github-cla-signers
```
fix(scaleway): Don't override IPv6 routes when IPv4 is not primary
If an instance in _routed-ip_ mode uses both IPv4 **and** IPv6, but the IPv6 is listed (attached) first, the default IPv6 route may be absent from the final network configuration for systems that do not accept Router Advertisements.
This changes fixes the problem by making sure that routes are appended, not overwritten.
```
1. Create an instance with `routed-ip-enabled=true` but no IP address
2. Create a `routed_ipv6` Flexible IP and attach it to the instance
3. Create a `routed_ipv4` Flexible IP and attach it to the instance
4. Start the instance
5. Once fully booted, connect to the instance and ensure it has the expected network configuration, and especially a default IPv6 route
> fix(scaleway): Don't override IPv6 routes when IPv4 is not primary

- tests/integration_tests/util.py
```
test: assert that schema is valid by default
```
This should increase our test coverage of `cloud-init schema` by running it by default in `verify_clean_boot()`. This command has had numerous tracebacks over the years (I just [reported another](https://github.com/canonical/cloud-init/issues/5656)), so additional coverage should hopefully help prevent this type of thing from getting hit by users.
My plan is to fix any new test failures caused by this new addition prior to adding `verify_clean_boot()` next to our `verify_clean_log()` calls - which should pave the way for eventually replacing `verify_clean_log()`.
Note: In a followup PR I plan to add new flags (`ignore_deprecations` and `require_deprecations`) to allow skipping deprecation on tests which we intend to continue using …
> test: assert that schema is valid by default

- cloudinit/net/netops/iproute2.py
- tests/unittests/net/netops/test_iproute2.py
- tests/unittests/net/test_init.py
```
fix(netops): Fix ip addr flush command
Fixes GH-5648
```
Fixes #5648
> fix(netops): Fix ip addr flush command

- cloudinit/cmd/main.py
```
chore: drop broken optimization
Setting TZ environment variable was introduced as a performance optimization in 2016[1].
However, this optimization never worked, because it introduced code which only runs when
__name__ is "__main__". This never happens when installed via setuptools - it gets imported
and executed by the "cloud-init" script.
The underlying issue was fixed at some point between Trusty and Bionic, presumably in
cPython or in glibc. The following reproducer of the original issue will print multiple
lines on an affected system.
strace /usr/bin/python3 -c 'import os; from datetime import datetime; print([datetime.now() for i in range(10)])' |& grep -e localt -e zonei
[1] https://code.launchpad.net/~raharper/cloud-init/+git/cloud-init/+merge/307722
```
I also checked a few …
> chore: drop broken optimization

- .github/workflows/check_format.yml
- .github/workflows/integration.yml
- .github/workflows/linkcheck.yml
- .github/workflows/packaging-tests.yml
- .github/workflows/scheduled.yml
- .github/workflows/stale.yml
- .github/workflows/unit.yml
```
chore: bump ci dependency versions
- use canonical/lxd in integration test
- optimize integration test to run faster
```
https://github.com/canonical/cloud-init/pull/5658
> chore: bump ci dependency versions

- debian/patches/no-nocloud-network.patch
On stable release, I don't think we want to attempt to reach out to the nocloud URL to find network-config (and retry 10 times) as this wil introduce unnecessary lag in boot or datasource detection for something that was not supported on the original stable releases.
Adapt the quilt patch to drop the logic which attempts to read a network-config file from any nocloud URL.
quilt push -a
tox -e py3
quilt pop -a
> fix(no-nocloud-network.patch): avoid reading network-config from read_seeded

- cloudinit/sources/DataSourceEc2.py
- doc/examples/cloud-config-datasources.txt
- tools/.github-cla-signers
```
feat(ec2): Bump url_max_timeout to 240s from 120s.
Initialization of IMDS is periodically exceeding the 120s limit on
instance launch. Increase the timeout to allow for this variance.
Update docs to reflect change.
```
This issue was seen during instance launch testing and is inconsistent and difficult to reproduce.
Most of the time, the current timeout is not reached.
``tox -e py3`` was run before and after this change with only hash naming differences.
> feat(ec2): Bump url_max_timeout to 240s from 120s.

- tests/unittests/config/test_cc_ansible.py
```
chore: make ansible test serial
```
Arguably we should modify the test, but for now just mark it as serial to fix the py3-fast tox env.
```
tox -e py3-fast
```
> chore: make ansible test serial

- cloudinit/sources/azure/errors.py
- cloudinit/sources/helpers/azure.py
- tests/unittests/sources/azure/test_errors.py
- tests/unittests/sources/test_azure_helper.py
- tox.ini
```
chore: fix tip-ruff
```
https://github.com/canonical/cloud-init/actions/runs/10739858604/job/29786611496
> chore: fix tip-ruff

- cloudinit/config/cc_phone_home.py
- cloudinit/stages.py
- doc/examples/cloud-config-boot-cmds.txt
- doc/examples/cloud-config.txt
- doc/man/cloud-init-per.1
- doc/module-docs/cc_bootcmd/data.yaml
- doc/module-docs/cc_phone_home/data.yaml
- doc/module-docs/cc_phone_home/example1.yaml
- doc/module-docs/cc_phone_home/example2.yaml
- doc/rtd/explanation/format.rst
- doc/rtd/explanation/instancedata.rst
- doc/rtd/howto/module_run_frequency.rst
- doc/rtd/reference/cli.rst
- doc/userdata.txt
- tests/data/merge_sources/expected9.yaml
- tests/data/merge_sources/source9-1.yaml
- tests/integration_tests/modules/test_boothook.py
- tests/integration_tests/test_multi_part_user_data_handling.py
- tests/unittests/config/test_cc_bootcmd.py
```
chore: Prefer other methods over $INSTANCE_ID
$INSTANCE_ID is an environment variable that contains a reference
to the current instance id. Its use is no longer needed now that
we can use jinja templates with {{ v1.instance_id }}. Furthermore,
`cloud-init-per` is a better replacement for running scripts once
per instance.
In particular, this commit does the following:
- Add jinja templating functionality to boothooks to be consistent
with other core user data types
- Document cloud-id and cloud-init-per as they were previously
undocumented
- Replace all $INSTANCE_ID references in docs to either use
{{ v1.instance_id }} or the `cloud-init-per` script
- Update documentation of $INSTANCE_ID to now be deprecated
- Update tests as necessary
```
> chore: Prefer other methods over $INSTANCE_ID

- doc/rtd/explanation/events.rst
tl;dr: documenting downstream bugs rather than filing them against downstream bug trackers is not the best approach.
It may be better to let users use the features that they want to, and if an issue is uncovered direct bug reports to the proper support channels.
>   Due to its use of ``systemd`` sockets, ``hotplug`` functionality is
>   currently incompatible with SELinux on Linux distributions using systemd.
This isn't true. No incompatibility with SELinux exists. An SELinux rule just needs to be updated on the affected distro to allow this access.
>   This issue is being tracked in GitHub #3890.
This is a downstream issue. Why wasn't it reported downstream for them to fix?
>   Additionally, ``hotplug``
>   support is considered experimental for non-Alpine and non-Debian-based
> …
> doc: remove misleading warning

- debian/changelog
- debian/cloud-init.postinst
- see separate commits
Functional change
```
fix(d/postinst): retain handle_preseed functions for MAAS provision
Commit cf13fd12 removed support for MAAS preseed functions from
debian/cloud-init.postinst which is the only operation which
allows MAAS to send preseed config to cloud-init.
Fixes GH-5685
```
https://github.com/canonical/cloud-init/issues/5685
The other functions in postinst that were removed by commit cf13fd12 were already version gated to be skipped on any recent supported LTS.  So, the other dropped postinst functions in that commit do not need to be reverted. Just active MAAS preseed support utility functions.
> fix: cloud-init.postinst for maas preseed provisioning

- .github/labeler.yml
Minor update to auto-label any packaging branches with the label 'packaging'.
Test run here https://github.com/blackboxsw/cloud-init/pull/31
> chore(actions): add packaging label for any branches modifying debian/*

- .github/labeler.yml
```
ci: fix labeler
```
The failed job shows this output:
```yaml
Run actions/labeler@v5
with:
repo-token: ***
configuration-path: .github/labeler.yml
sync-labels: false
dot: true
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
Error: SyntaxError: Invalid regular expression: /ubuntu/**/: Nothing to repeat
Error: Invalid regular expression: /ubuntu/**/: Nothing to repeat
```
This PR removes the offending line, which was redundant anyways 
So I'm not really sure how to test this, because unlike normal workflows, the base branch runs [the labeler job](https://github.com/actions/labeler/tree/main?tab=readme-ov-file#initial-set-up-of-the-labeler-action). Per the docs:
> When submitting an initial pull request to a repository using the …
> ci: fix labeler

- systemd/cloud-config.service.tmpl
- systemd/cloud-final.service.tmpl
- systemd/cloud-init-local.service.tmpl
- systemd/cloud-init-network.service.tmpl
```
fix: use cross-distro netcat name
```
```bash
$ ls -la /etc/alternatives/netcat /usr/bin/netcat
lrwxrwxrwx 1 root root 15 Nov  1  2023 /etc/alternatives/netcat -> /bin/nc.openbsd
lrwxrwxrwx 1 root root 24 Nov  1  2023 /usr/bin/netcat -> /etc/alternatives/netcat
```
> fix: use cross-distro netcat name

- tests/integration_tests/util.py
- tox.ini
```
test: make verify_clean_boot respect return code by series
Also update stdout / stderr output format.
```
Failing in https://github.com/canonical/cloud-init/actions/runs/10819125394/job/30016291006?pr=5691
> test: make verify_clean_boot respect return code by series

- cloudinit/sources/DataSourceNoCloud.py
- tests/unittests/sources/test_nocloud.py
```
Use individual commits
```
First commit is just pytestifying the tests so I can later use the caplog fixture.
> fix: Invalid "seedfrom" in NoCloud system configuration

- .github/labeler.yml
- debian/changelog
- debian/patches/no-single-process.patch
- systemd/cloud-config.service.tmpl
- systemd/cloud-final.service.tmpl
- systemd/cloud-init-local.service.tmpl
- systemd/cloud-init-network.service.tmpl
- tests/integration_tests/util.py
- tox.ini
Same as https://github.com/canonical/cloud-init/pull/5702 for jammy
> Fix daily build recipe: Ubuntu/jammy refresh patches

- cloudinit/sources/DataSourceScaleway.py
- tests/unittests/sources/test_scaleway.py
On some distributions like focal (See LP: #2073869) systemd fails to add a route which is not in the subnet of the NIC if onlink is not explicitely specified.
Force on-link to true to avoid those situations.
Fixes: GH-5523
Scaleway: Force on-link: true for static networks (#5523)
```
<type>(optional scope): <summary>  Force use of on-link: true not working on Ubuntu Focal
The version of systemd on Ubuntu Focal does not support subnets outside
of the NIC network without addition of on-link. This is not the case with other Ubuntu
distributions.
Fixes GH-5523
LP: #2073869
> Scaleway: Force on-link: true for static networks (#5523)

- cloudinit/config/cc_lxd.py
- tests/unittests/config/test_cc_lxd.py
```
fix: lxd do not check for thinpool kernel module
Rather than checking for kernel module file before running lxd, just
fall back to disabling thinpool and retrying with thinpool disabled
when subp() fails and it is using lvm as backing storage.
On some Ubuntu releases, the kernel module is compressed which causes
this check to fail and this warning to erroneously be logged. Making
this logic only run in the failure path and avoiding file matches on
kernel driver files should be less error prone.
BREAKING_CHANGE: On some Ubuntu series this changes behavior causing
lxd to now use lxd thinpool, which is the current lxd default.
```
Some images ship compressed kernel modules. On Jammy, GCE, we ship: `/lib/modules/6.8.0-1014-gcp/kernel/drivers/md/dm-thin-pool.ko.zst` …
> fix: lxd do not check for thinpool kernel module

- cloudinit/net/activators.py
- systemd/cloud-final.service.tmpl
- tests/unittests/test_net_activators.py
```
fix(NetworkManager): Fix network activator
Reload NetworkManager configuration rather than bringing up interfaces.
This enables NetworkManager to configure interfaces which are not yet available in userspace, and fixes a race that was previously worked around in a service file.
```
https://github.com/canonical/cloud-init/issues/5512
> fix(NetworkManager): Fix network activator

- debian/changelog
- debian/patches/no-nocloud-network.patch
- debian/patches/no-single-process.patch
- debian/patches/revert-551f560d-cloud-config-after-snap-seeding.patch
@holmanb , do you mind reviewing this one? There were two conflicts based on some of your recent changes and I want to make sure I didn't mess them up.
I made an accidental bad push to upstream jammy, so it is currently at tip of main even though it was originally further back.
> Ubuntu/jammy: fix dailies

- tests/integration_tests/conftest.py
```
fix: force sftp cleanup when done with instance
Force inline sftp closure rather than on garbage collection.
Without this, pytest causes tracebacks because it cleans up the logger
before the final sftp connection is closed, which causes tracebacks
after tests exit.
```
https://github.com/pytest-dev/pytest/issues/5282
https://github.com/pytest-dev/pytest/issues/5502
https://github.com/canonical/pycloudlib/issues/415
I tested the `client` and `class_client` fixtures manually by introducing two new classes, with one failing test each, and didn't see any tracebacks nor unexpected failures.
> fix: force sftp cleanup when done with instance

- .github/workflows/packaging-tests.yml
```
ci: fix packaging patch check
Also:
- simplify checkout logic to use local github main branch
- add human-friendly job name and reduce redundant words
```
A recent push to fix running against the devel branch broke running against series with patches.
https://github.com/canonical/cloud-init/actions/runs/10909563606/job/30278043196?pr=5712
The patch check job showed this:
```bash
+ test -f debian/patches/series
+ exit 0
```
> Fix CI patch test

- systemd/cloud-init-hotplugd.socket
```
fix(hotplugd.socket): remove basic.target as dependency
In 62ace19d679 we moved cloud-init-hotplugd.socket earlier in boot,
after cloud-config.target. But we didn't remove the dependencies added
by default and this might conflict with other units producing
non-solvable ordering cycles, see #2081124.
Remove the default dependency on basic.target added by systemd.
LP: #2081124
```
I have manually tested this on and image produced by https://cdimage.ubuntu.com/noble/daily-live/20240920/, modifying the target system prior to first-booting.
> fix(hotplugd.socket): remove basic.target as dependency

- integration-requirements.txt
- tests/integration_tests/modules/test_ubuntu_pro.py
```
tests(pro): bump pycloudlib add noble release to pro tests
Since Noble is an LTS which supports Ubuntu Pro add integration
test coverage for that feature.
Bump pycloudlib dependency to 1!9.2 which allows cloud-init integration
tests to obtain service_account_email configuration from
the .config/pycloudlib.toml:
[gce]
credentials_path = <path>
without the need to also provide `service_account_email` in
pycloudlib.toml.
```
Fixes jenkins failures about service account https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-gce/lastSuccessfulBuild/testReport/junit/tests.integration_tests.modules.test_ubuntu_pro/TestUbuntuAdvantagePro/test_custom_services/
```
CLOUD_INIT_OS_IMAGE=noble CLOUD_INIT_PLATFORM=gce tox -e integration-tests -- …
```
> tests(pro): bump pycloudlib add noble release to pro tests

- tests/unittests/test_cli.py
- tests/unittests/test_ds_identify.py
```
chore: clean up pytest warnings
```
Pytest warns about incorrect usage of mocker and returning from test methods. Clean it up
> chore: clean up pytest warnings

- tests/integration_tests/cmd/test_schema.py
- tests/integration_tests/datasources/test_none.py
Fix a couple of integration test failures due to shift to verify_clean_boot in commit 313390f81f44be0e52d5447b4112209b282ddb87
Failed jenkins jobs resolved by this PR: [tests.integration_tests.cmd.test_schema.TestSchemaDeprecations.test_clean_log](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-gce/513/testReport/junit/tests.integration_tests.cmd.test_schema/TestSchemaDeprecations/test_clean_log/)
[tests.integration_tests.datasources.test_none.test_datasource_none_discovery](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-gce/513/testReport/junit/tests.integration_tests.datasources/test_none/test_datasource_none_discovery/)
> Tests fix clean boot changes

- tests/integration_tests/datasources/test_nocloud.py
- tests/integration_tests/reporting/test_webhook_reporting.py
```
* tests: fix test_nocloud message typo introduced by commit 313390f8
*  tests: webhook require_deprecation msg on 24.3
```
Failed job: 
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-oracular-lxd_vm/lastSuccessfulBuild/testReport/junit/tests.integration_tests.datasources.test_nocloud/TestSmbios/test_smbios_seed_network/
```
CLOUD_INIT_PLATFORM=lxd_vm CLOUD_INIT_KEEP_INSTANCE=1 CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE .tox/integration-tests/bin/pytest tests/integration_tests/datasources/test_nocloud.py::TestSmbios::test_smbios_seed_network  --pdb
```
> tests: fix test_nocloud message typo introduced by commit 313390f8

- debian/changelog
- debian/patches/cpick-hotplugd-systemd-ordering-fix.patch
- debian/patches/series
Sync single cherry-pick from upstream #5722 for release. Lay this cherry-pick down as a single quilt patch. Preferred to use the ubuntu/noble-24.3.x branch because we already have performed a new_upstream_snapshot.py against ubuntu/noble to fix daily recipes.
```
git checkout upstream/ubuntu/noble -B ubuntu/noble-24.3.x
git reset --hard ubuntu/24.3.1-0ubuntu0_24.04.1
git cherry-pick82b4b7e1436f3da2ae8285c7e9ef6815030a6ccd
vi debian/patches/series
git add debian/patches/series
git cherry-pick --continue
dch -i # manually add same d/changelog from oracular/ fix verson 24.04.2
git commit -am 'update changelog'
vi debian/changelog # set UNRELEASED to noble
git commit -am 'releasing cloud-init version 24.3.1-0ubuntu0~24.04.2'
```
Preferred to use the …
> Single cherry-pick fix into noble on top of what's queued in SRU verification.

- cloudinit/cmd/status.py
- tests/unittests/cmd/test_status.py
- tools/.github-cla-signers
Fixes: GH-5863
Cloud-init version: 24.4~3+really24.3.1-0ubuntu1
Operating System Distribution: Ubuntu
Cloud provider, platform or installer type: lxd vm
cloud-init status --wait
> remove newline injected for cloud-init status --wait

- tests/integration_tests/modules/test_apt_functionality.py
```
Correct expected Logging format in apt.test_install_missing_deps
integration tests due to logging changes introduced in 70d4a5c25.
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-gce/lastSuccessfulBuild/testReport/tests.integration_tests.modules/test_apt_functionality/test_install_missing_deps/
CLOUD_INIT_KEEP_INSTANCE=1 CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE CLOUD_INIT_OS_IMAGE=oracular .tox/integration-tests/bin/pytest  tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_de
> test: fix timer logging change expected logs

- tests/integration_tests/test_instance_id.py
```
test: avoid undocumented lxd key
Use the dedicated volatile key instead.
```
The docs for this key [have a typo](https://github.com/canonical/lxd/pull/14168).
```bash
tox -e integration-tests -- tests/integration_tests/test_instance_id.py
```
> test: avoid undocumented lxd key

- doc/rtd/explanation/format.rst
- doc/rtd/explanation/instancedata.rst
- doc/rtd/reference/datasources/lxd.rst
```
doc: do not document user.meta-data key
This key is not documented by lxd and will likely be removed.
Also prefer cloud-init prefixes.
```
https://github.com/canonical/lxd/issues/13853#issuecomment-2374472140
> doc: do not document user.meta-data key

- tests/integration_tests/instances.py
- tests/integration_tests/integration_settings.py
```
feat(integration_test): add CLOUD_INIT_PKG setting
Add CLOUD_INIT_PKG to control what specific cloud-init package to
install when CLOUD_INIT_SOURCE is PROPOSED, UPGRADE or points to a ppa.
SC-1858
```
```sh
export CLOUD_INIT_PLATFORM=lxd_vm
export CLOUD_INIT_OS_IMAGE=oracular
CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:aciba/us-120-cloud-specific-cloud-init-packaging \
CLOUD_INIT_CLOUD_INIT_PKG=cloud-init-smart-os \
tox -e integration-tests -- -vvv --pdb tests/integration_tests/modules/test_set_hostname.py::TestHostname::test_hostname
export CLOUD_INIT_CLOUD_INIT_PKG=cloud-init
CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED \
tox -e integration-tests -- -vvv --pdb tests/integration_tests/modules/test_set_hostname.py::TestHostname::test_hostname
CLOUD_INIT_CLOUD_INIT_SOURCE=UPGRADE \
tox -e …
```
> feat(integration_test): add CLOUD_INIT_PKG setting

- cloudinit/sources/DataSourceEc2.py
- tests/integration_tests/datasources/test_ec2_ipv6.py
Bring back log messages about link-local being used during ephemeral net setup at init-local time to make it testable.
```
test(ec2-dual-stack): fix int-test
Bring back log messages about link-local being used during ephemeral net
setup at init-local time to make it testable.
```
* Logs changed as part of: https://github.com/canonical/cloud-init/pull/5672
* Failing test: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-ec2/496
```
export CLOUD_INIT_CLOUD_INIT_SOURCE=./cloud-init_all.deb
tox -re integration-tests -- -vvv --pdb tests/integration_tests/datasources/test_ec2_ipv6.py::test_dual_stack
```
> test(ec2-dual-stack): fix int-test

- tests/unittests/cmd/test_main.py
```
test: pytestify test_main.py
```
> test: pytestify test_main.py

- tests/integration_tests/modules/test_hotplug.py
See individual commits for more context.
* Example of failing test: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-oracular-ec2/79/testReport/junit/tests.integration_tests.modules/test_hotplug/test_multi_nic_hotplug/
```
export CLOUD_INIT_CLOUD_INIT_SOURCE=./cloud-init_all.deb
tox -re integration-tests -- -vvv --pdb tests/integration_tests/modules/test_hotplug.py::test_multi_nic_hotplug
```
> Improvements test multi nic hotplug

- doc/rtd/development/integration_tests.rst
- integration-requirements.txt
- tests/integration_tests/clouds.py
- tests/integration_tests/conftest.py
- tests/integration_tests/integration_settings.py
```
tests: add OS_IMAGE_TYPE setting to allow for minimal tests
Allow setting CLOUD_INIT_OS_IMAGE_TYPE="mimimal" to support
running the full integration test suite against Ubuntu minimal
images.
Required for SC-1750: Daily jenkins ubuntu minimal test runner for
Ubuntu Focal, Jammy and Noble releases.
```
https://warthogs.atlassian.net/browse/SC-1750
Depends on https://github.com/canonical/pycloudlib/pull/410
After the above this PR and the pyclluldlib PR merge, a serserver-jenkins-jobs matrix will be configured to run LXDContainer jobs against ubuntu-minimal:(focal, jammy, and noble)
```
CLOUD_INIT_OS_IMAGE_TYPE=minimal tox -e integration-tests -- tests/integration-tests/test_paths.py
```
> tests: add OS_IMAGE_TYPE setting to allow for minimal tests

- tox.ini
```
ci: fix tox.ini pytest cmd to use cloudinit dir for coverage reporting
```
Run the following locally to run pytest and ensure that the coverage report table appears at the end of the pytest results:
```
tox -e py3
```
Then, run the following new tox command to re-print the table to console:
```
tox -e coverage-report
```
Then, run the following new tox command to generate the html coverage site.
```
tox -e converage-html
```
Optional: Open automagically with xdg-open:
```
xdg-open htmlcov/index.html
```
> ci: fix tox.ini pytest cmd to use cloudinit dir for coverage reporting

- tox.ini
When the pytest fails, its easier to debug if pytest is run in verbose mode. Enable it.
> Make pytest more verbose for easier debugging

- integration-requirements.txt
- tests/integration_tests/modules/test_combined.py
```
fix(test): convert p.gce.instance.instance_id to str
Sdk changes surface instance_id as integer rather than as str.
Convert it appropiately and adopt pycloudlib's public API, rather than
directly accessing instance_id on the GCE SDK underliying instance
object.
```
* Being fixed here: https://github.com/canonical/pycloudlib/pull/437
* Failing test: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-gce/lastCompletedBuild/testReport/tests.integration_tests.modules.test_combined/TestCombined/test_instance_json_gce/
```
export CLOUD_INIT_CLOUD_INIT_SOURCE=NONE
export CLOUD_INIT_PLATFORM=gce
export CLOUD_INIT_OS_IMAGE=jammy
tox -v -e integration-tests-jenkins -- -vvv --pdb \
tests/integration_tests/modules/test_combined.py::TestCombined::test_instanc …
```
> fix(test): convert p.gce.instance.instance_id to str

- cloudinit/cmd/main.py
- tests/integration_tests/reporting/test_webhook_reporting.py
- tests/unittests/cmd/test_main.py
Includes a git revert of bd6cd1fbee12ac81ff6c46cc5f979cfdf76e5e13.
```
fix: avoid deprecation logs for calling cli stages
Avoid deprecating command line calls to cloud-init boot.
When cloud-init's boot stages are invoked directly on the command line
is typically an attempt to add suppplemental configuration to a
system after initial boot has completed.
Although direct calls to cloud-init boot stages could lead to
misconfiguration if boot stages are called out of sequence
of customized /etc/cloud/cloud.cfg altering which config modules are
run during the boot stage, the support of such uses or custom
environments is out of scope for this feature. It remains a simple
tool to apply additional configuration via user-data onto an existing
system after initial boot.
At some point in the future, …
```
> fix: avoid deprecation logs for calling cli stages

- integration-requirements.txt
```
chore: bump pycloudlib to required version
Commit 99f4ca4f bumped the max version of pycloudlib without bumping
the min version.
```
Canonical only: https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-focal-gce/506/
> chore: bump pycloudlib to required version

- tests/integration_tests/modules/test_keys_to_console.py
- tests/integration_tests/modules/test_ssh_auth_key_fingerprints.py
- tests/integration_tests/modules/test_write_files.py
- tests/integration_tests/util.py
```
test: add get_syslog_or_console for minimal images without syslog #5793
Minimal images do not have rsyslog installed. As a result, no
/var/log/syslog exists. Add helper function get_syslog_or_console
to allow minimal images to use pycloudlib.Instance.get_console
instead of reading /var/log/syslog.
```
Sample jenkins test failures for minimal.
https://jenkins.canonical.com/server-team/job/zzz-chad-jammy-lxd-minimal/lastSuccessfulBuild
```
CLOUD_INIT_OS_IMAGE_TYPE=minimal CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily CLOUD_INIT_PLATFORM=lxd_container tox -e integration-tests -- 
tests/integration_tests/modules/test_keys_to_console.py tests/integration_tests/modules/test_ssh_auth_key_fingerprints.py tests/integration_tests/modules/test_write_files.py
```
> test: add get_syslog_or_console for minimal images without syslog

- .github/workflows/integration.yml
```
WIP: chore: Use devel release and no sbuild in integration CI
```
> chore: Use devel release and no sbuild in integration CI

- cloudinit/config/cc_byobu.py
- cloudinit/distros/debian.py
- tests/integration_tests/modules/test_combined.py
- tests/unittests/config/test_cc_byobu.py
- tests/unittests/config/test_cc_locale.py
- tests/unittests/distros/test_debian.py
Install the necessary package dependencies (byobu or locales) when cloud-config directives provide configuration requesting setup and config of byobu or locales.
Addresses issues with minimal images not containing byobu or locales packages, yet user-data requests that specific setup and configuration.
```
* feat(locale): support locales install on minimal images when cfg requests-
*  feat(byobu): support byobu install on minimal images when cfg requests
```
Failed jenkins job on ubuntu minimal
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-lxd_container-minimal/lastSuccessfulBuild/
```
CLOUD_INIT_KEEP_INSTANCE=1 CLOUD_INIT_OS_IMAGE=noble CLOUD_INIT_CLOUD_INIT_SOURCE=IN_PLACE CLOUD_INIT_OS_IMAGE_TYPE=minimal tox -e integration-tests -- …
```
> feat(byobu/locale): install necessary packages when absent in images and cloud-config user-data wants to setup 

- .github/workflows/integration.yml
- tests/integration_tests/util.py
```
test: verify_clean_boot enhancements
```
> test: verify_clean_boot enhancements

- cloudinit/config/schema.py
- tests/unittests/config/test_schema.py
```
chore: update netplan import semantics and related tests
The way the netplan API was being imported caused test issues.
Imports were moved and tests updated accordingly.
Fixes GH-5804
```
To reproduce in a virtualenv, symlink the netplan API (should be at `/usr/lib/python3/dist-packages/netplan`) into your virtualenv's site-packages.
> chore: update netplan import semantics and related tests

- tests/integration_tests/modules/test_combined.py
- tests/integration_tests/util.py
Rebase as separate commits
```
*  tests(minimal): rsyslog not in minimal images expect warning
Adapt test_no_problems to use verify_clean_boot instead of
verify_clean_log.
Fix verify_clean_boot to retain platform-specific ignored tracebacks
before passing it into _verify_clean_boot.
* tests(lxd): avoid failure on multiple calls to --show-log
Cope with repeated calls to lxc console --show-log which exits 1
with the error "no such file or directory" when the log entries
have already been processed and no new log entries exist.
Preserve lxc_log on the client instance and return former log content
on lxd platforms when "no such file or directory" runtime errors are raised
```
Resolves test_keys_to_console errors seen in https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-i …
> tests(lxd): avoid failure on multiple calls to --show-log

- cloudinit/net/eni.py
- cloudinit/net/network_state.py
- cloudinit/net/sysconfig.py
- tests/unittests/net/network_configs.py
- tests/unittests/test_net.py
```
fix: Render bridges correctly for v2 on sysconfig with set-name
When listing interfaces in v2 format, we should expect to be able to
reference other interfaces using the name in the configuration, not
the name the interface will eventually take. This was broken when
using `set-name`.
To fix this, we now store the configuration id alongside the eventual
name, and reference that instead of the name.
Fixes GH-5574
```
> fix: Render bridges correctly for v2 on sysconfig with set-name

- cloudinit/config/cc_lxd.py
- tests/unittests/config/test_cc_lxd.py
```
fix: do not warn in thinpool fallback
This path is expected on some images.
```
> fix: do not warn in thinpool fallback

- doc/rtd/reference/breaking_changes.rst
```
doc: clarify workarounds required for single process changes
```
> doc: clarify workarounds required for single process changes

- cloudinit/config/cc_set_passwords.py
- tests/unittests/config/test_cc_set_passwords.py
Fix the complexity of random passwords generated by the rand_user_password() method.
The complexity of the random password generated by the rand_user_password() method may not meet the security configuration requirements of the system authentication module. chpasswd will fail.
Fixes GH-5814
> generate random passwords using minclass

- tests/unittests/cmd/test_main.py
```
test: unbreak pytest-xdist
'pytest -n auto' fails with random data in parametrization, so
work around it.
```
> test: unbreak pytest-xdist

- systemd/cloud-init-local.service.tmpl
- systemd/cloud-init-main.service.tmpl
See individual commits. One is a fix for https://github.com/canonical/cloud-init/issues/5755 and the other cleans up redundant dependencies that were introduced in the single process change.
> Fix arch systemd ordering cycle.

- systemd/cloud-config.service
- systemd/cloud-final.service
- systemd/cloud-final.service.tmpl
- systemd/cloud-init-local.service.tmpl
- systemd/cloud-init-main.service.tmpl
- systemd/cloud-init-network.service.tmpl
https://github.com/canonical/cloud-init/issues/5818
> Simplify systemd service files

- tests/unittests/config/test_cc_set_passwords.py
Fix the issue of duplicate judgment conditions in the _get_str_class_num function
The problem introduced by commit https://github.com/canonical/cloud-init/commit/879945f56103d937a7fee84bfe7662dc2a5be708 
Fixes GH-5814
> fix _get_str_class_num

- sysvinit/openbsd/cloudconfig.tmpl
- sysvinit/openbsd/cloudfinal.tmpl
- sysvinit/openbsd/cloudinit.tmpl
- sysvinit/openbsd/cloudinitlocal.tmpl
- tools/build-on-openbsd
```
<type>fix(openbsd)</type>: Enable sysv init scripts in OpenBSD build script
This replaces the use of `/etc/rc.local` in the OpenBSD build script by the sysv init scripts provided with cloud-init.
Fixes GH-4036
LP: #1992853
```
I've fixed a bug in the sysv init scripts by disabling `rc_bg="YES"`, otherwise it would fail to execute correctly with this error at boot:
```
rcctl start cloudconfig 
cloudconfig/etc/rc.d/cloudconfig: kill: 66598: No such process
(ok)
```
Also, `/etc/rc.local` is not needed anymore, `/var/run` is managed by the system and does not have to be cleaned up manually.
My own CI: https://github.com/hcartiaux/openbsd-cloud-image/actions/
* Generate an OpenBSD 7.6 image with cloud-init 24.3.1
* Apply the diff with the post-install script `install.site`
* Generate a …
> Enable the sysv init scripts in OpenBSD build script

- debian/changelog
- debian/patches/deprecation-version-boundary.patch
- debian/patches/no-single-process.patch
- systemd/cloud-config.service
- systemd/cloud-final.service
- systemd/cloud-final.service.tmpl
- systemd/cloud-init-local.service.tmpl
- systemd/cloud-init-main.service.tmpl
- systemd/cloud-init-network.service.tmpl
- sysvinit/openbsd/cloudconfig.tmpl
- sysvinit/openbsd/cloudfinal.tmpl
- sysvinit/openbsd/cloudinit.tmpl
- sysvinit/openbsd/cloudinitlocal.tmpl
- tests/unittests/cmd/test_main.py
- tests/unittests/config/test_cc_set_passwords.py
- tools/build-on-openbsd
> Fix dailies

- cloudinit/config/cc_grub_dpkg.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_grub_dpkg.py
```
fix: disable grub-dpkg by default
```
It is no longer used by grub packaging.
> fix: disable grub-dpkg by default

- cloudinit/config/cc_grub_dpkg.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- debian/changelog
- debian/patches/cli-retain-file-argument-as-main-cmd-arg.patch
- debian/patches/no-single-process.patch
- debian/patches/revert-551f560d-cloud-config-after-snap-seeding.patch
- systemd/cloud-config.service
- systemd/cloud-final.service
- systemd/cloud-init-local.service.tmpl
- systemd/cloud-init-main.service.tmpl
- systemd/cloud-init-network.service.tmpl
- sysvinit/openbsd/cloudconfig.tmpl
- sysvinit/openbsd/cloudfinal.tmpl
- sysvinit/openbsd/cloudinit.tmpl
- sysvinit/openbsd/cloudinitlocal.tmpl
- tests/unittests/cmd/test_main.py
- tests/unittests/config/test_cc_grub_dpkg.py
- tests/unittests/config/test_cc_set_passwords.py
- tools/build-on-freebsd
- tools/build-on-openbsd
Another tricky one. Please review thoroughly.
> fix dailies: Ubuntu/jammy

- cloudinit/sources/DataSourceSmartOS.py
- tests/unittests/sources/test_smartos.py
- tools/.github-cla-signers
```
fix(smartos): Add `addrconf` IPv6 support
SmartOS uses `addrconf` as a special value to indicate that an IPv6
address should be obtained via DHCPv6 or SLAAC. cloud-init does not
know how to handle this.
Added logic to DataSourceSmartOS.py to properly recognise and handle
this value.
```
The vendor's documentation describes how this is supposed to work.
https://docs.smartos.org/setting-up-ipv6-in-a-zone/
This works fine for native and lx-branded zones (where network configuration is handled by other means), but not for KVM or Bhyve zones in which `cloud-init` is expected to perform the appropriate configuration. 
Before this change, `addrconf` would be passed through to `cloud-init` as a static address, causing errors.
```
status: error
extended_status: error
boot_status_code: …
```
> fix(smartos): Add `addrconf` IPv6 support

- cloudinit/config/schemas/schema-network-config-v2.json
- cloudinit/net/network_state.py
- cloudinit/net/networkd.py
- doc/rtd/reference/network-config-format-v2.rst
- tests/unittests/net/test_networkd.py
Implement the "optional" ethernet interface property from NetPlan for the networkd renderer. Marks an interface as not required for the network-online target using the RequiredForOnline=no Link property.
```
feat(networkd): Support RequiredForOnline link option
This allows an administrator to specify that an interface may not be available at
boot time, so we can avoid hanging while we wait for a configuration that might
never happen.
```
Using the networkd renderer, add an optional: true property to an interface. See that networkd no longer blocks the boot waiting for it to be configured.
> Support networkd RequiredForOnline option

- cloudinit/sources/helpers/vultr.py
- tools/.github-cla-signers
```
feat(vultr): add override for network interface detection (#5847)
```
The purpose of this feature is to provide the Vultr team with a way to define custom NIC lists to scan for metadata. This is particularly useful when dealing with niche hardware deployments.
The feature checks for the presence of an `/opt/vultr/find_candidate_nics.sh` shell script on the running guest image. If detected, DataSourceVultr uses that as an optional source of truth before falling back to `net.find_candidate_nics()`.
This feature was tested manually on Vultr's Ubuntu 22.04 and Ubuntu 24.04 images (as of 10/2024).
The added functionality is low risk, as it is both opt-in and limited to the Vultr cloud.
```
cp vultr.py /usr/lib/python3/dist-packages/cloudinit/sources/helpers/vultr.py
cloud-init clean -r
```
> feat(vultr): add override for network interface detection

- cloudinit/util.py
delete recursive=True for ensure_dir
Fixes GH-5807
> delete recursive=True for ensure_dir

- cloudinit/analyze/__init__.py
- cloudinit/analyze/show.py
- cloudinit/config/schema.py
- cloudinit/reporting/handlers.py
- cloudinit/sources/DataSourceGCE.py
- cloudinit/sources/azure/errors.py
- cloudinit/sources/azure/kvp.py
- cloudinit/sources/helpers/azure.py
- tests/integration_tests/clouds.py
- tests/integration_tests/test_paths.py
- tests/unittests/cmd/devel/test_logs.py
- tests/unittests/config/test_cc_ubuntu_pro.py
- tests/unittests/distros/package_management/test_apt.py
- tests/unittests/sources/azure/test_errors.py
- tests/unittests/sources/azure/test_kvp.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_gce.py
- tests/unittests/test_log.py
Fixes GH-5175
https://github.com/canonical/cloud-init/issues/5855 was discovered while working on this issue. I decided to split it as a separate work item, because it requires a broader discussion.
```bash
make deb
export CLOUD_INIT_KEEP_INSTANCE=true
export CLOUD_INIT_CLOUD_INIT_SOURCE=./cloud-init_all.deb
export CLOUD_INIT_PLATFORM=lxd_vm
export CLOUD_INIT_OS_IMAGE=oracular
tox -v -e integration-tests-jenkins -- -vvv --pdb tests/integration_tests/test_paths.py
export CLOUD_INIT_PLATFORM=lxd_vm
tox -v -e integration-tests-jenkins -- -vvv --pdb tests/integration_tests/test_paths.py
export CLOUD_INIT_PLATFORM=gce
tox -v -e integration-tests-jenkins -- -vvv --pdb …
```
> migrate away from deprecation warnings

- doc/rtd/conf.py
- doc/rtd/static/js/mermaid_config.js
- tools/.github-cla-signers
```
docs: Adjust arrow color in Mermaid diagrams for improved visibility
1. Changed the color of arrows in Mermaid diagrams to enhance
visibility in both dark and light mode themes. This change ensures
that the diagrams are readable regardless of the viewing mode. 
2. IMPORTANT: Changed the order in doc/rtd/conf.py file, this was done 
because it was giving import errors on running build commands. 
3. Added "MaheshG11" to "tools/.github-cla-signers".
Fixes GH-5837 
```
Fixes issue #5837 
1. Modified the lineColor property of arrows for all mermaid diagrams in the documentation to a neutral color that stands out in both dark and light modes.
2. Added "MaheshG11" to "tools/.github-cla-signers".
3. IMPORTANT: Changed the order in conf.py file, this was done because it was giving import …
> Docs: improved mermaid diagram for better visibility. Add "MaheshG11" as contributor

- cloudinit/cmd/main.py
- cloudinit/config/cc_growpart.py
- cloudinit/config/cc_grub_dpkg.py
- cloudinit/config/cc_landscape.py
- cloudinit/config/cc_reset_rmc.py
- cloudinit/config/cc_ubuntu_pro.py
- cloudinit/config/cc_yum_add_repo.py
- cloudinit/config/schema.py
- cloudinit/distros/package_management/apt.py
- cloudinit/net/eni.py
- cloudinit/sources/DataSourceScaleway.py
- cloudinit/util.py
- tests/unittests/config/test_cc_landscape.py
- tests/unittests/config/test_schema.py
- tests/unittests/distros/package_management/test_apt.py
- tests/unittests/test_net.py
- tests/unittests/test_util.py
```
chore: remove unused code
```
These were identified using Vulture and manually verified.
> Remove dead code

- cloudinit/net/network_manager.py
- tests/unittests/net/network_configs.py
Most RHEL systems use network manager to bring up manage network connections. 
Network Manager uses route-metric for the default route and route/plen[,gateway,metric] for the additional static routes, please see
https://networkmanager.dev/docs/api/latest/nm-settings-nmcli.html 
https://networkmanager.dev/docs/api/latest/nm-settings-keyfile.html
This changes ensures that cloud-init generates nmconnection files with route metric settings that are compatible with RHEL and network manager.
Fixes: GH-5877
For the config data
```
#cloud-config
network:
version: 1
config:
- type: physical
name: enp1s0
subnets:
- type: static
address: 10.0.2.2/24
gateway: 10.0.2.1
routes:
- destination: 0.0.0.0/0
gateway: 10.0.2.1
metric: 99
- destination: 192.168.122.1/24
gateway: 10.0.2.1
metric: 98
```
After …
> Fix metric setting of nmconnection for rhel

- tests/integration_tests/modules/test_package_update_upgrade_install.py
```
test: allow relative path in apt-get test
Minimal Ubuntu images don't show full path
```
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-lxd_container-minimal/18/testReport/tests.integration_tests.modules.test_package_update_upgrade_install/TestPackageUpdateUpgradeInstall/test_apt_packages_were_updated/
/var/log/apt/history.log (snippet):
```
Start-Date: 2024-11-20  15:11:45
Commandline: apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet install tree sl
Install: libgpm2:amd64 (1.20.7-11, automatic), sl:amd64 (5.02-1), tree:amd64 (2.1.1-2ubuntu3), libncurses6:amd64 (6.4+20240113-1ubuntu2, automatic)
End-Date: 2024-11-20  15:11:46
```
> test: allow relative path in apt-get test

- tests/integration_tests/reporting/test_webhook_reporting.py
```
test: re-decrement expected webhook events
Tried to fix in aedb7f97 , but there are two events (start and stop)
per module
```
> test: re-decrement expected webhook events

- ChangeLog
- cloudinit/version.py
Bump the version in cloudinit/version.py to 24.4 and update ChangeLog.
https://discourse.ubuntu.com/t/2024-cloud-init-release-schedule/41679
> Release 24.4

- tests/integration_tests/modules/test_growpart.py
```
test: Allow unknown size in growpart test
```
The test occasionally fails because it could not properly determine the sizes.
Relevant logs:
```
2024-11-14 20:57:53,534 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2024-11-14 20:57:53,534 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7fa841cbdeb0>)
2024-11-14 20:57:53,535 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2024-11-14 20:57:53,546 - performance.py[DEBUG]: Running ['growpart', '--help'] took 0.011 seconds
2024-11-14 20:57:53,547 - util.py[DEBUG]: Reading from /proc/505/mountinfo (quiet=False)
2024-11-14 20:57:53,547 - util.py[DEBUG]: Reading 3422 …
```
> test: Allow unknown size in growpart test

- cloudinit/config/cc_chef.py
- cloudinit/config/cc_mounts.py
- cloudinit/config/cc_rsyslog.py
- cloudinit/config/cc_ssh.py
- cloudinit/config/schema.py
- cloudinit/distros/__init__.py
- cloudinit/distros/parsers/sys_conf.py
- cloudinit/dmi.py
- cloudinit/handlers/cloud_config.py
- cloudinit/mergers/__init__.py
- cloudinit/net/renderer.py
- cloudinit/net/sysconfig.py
- cloudinit/sources/__init__.py
- cloudinit/templater.py
- cloudinit/util.py
It is not best practice, and it often adds unnecessary overhead.
```
chore: eliminate calls at import time
It is not best practice, and it often adds unnecessary overhead.
Fixes GH-5344
```
The important part of this is regex compile - that can be done when/if the function is called rather than at import time which will save some cycles.
While `namedtuple()` and `tuple()` aren't truly harmful, there are ways to define similar types statically rather than generating them at runtime, so I modified those in a few places too.
Fixes https://github.com/canonical/cloud-init/issues/5344
> chore: eliminate calls at import time

- tests/integration_tests/bugs/test_gh671.py
- tests/integration_tests/bugs/test_lp1835584.py
- tests/integration_tests/bugs/test_lp1901011.py
- tests/integration_tests/bugs/test_lp1910835.py
- tests/integration_tests/clouds.py
- tests/integration_tests/cmd/test_status.py
- tests/integration_tests/conftest.py
- tests/integration_tests/datasources/test_azure.py
- tests/integration_tests/decorators.py
- tests/integration_tests/modules/test_apt_functionality.py
- tests/integration_tests/modules/test_hotplug.py
- tests/integration_tests/modules/test_lxd.py
- tests/integration_tests/test_networking.py
```
test: improve test initialization error path
- eliminated vestigial setup_image() fixture use
- make setup_image() a function not a fixture
- move one-time setup into pytest_sessionstart()
- use a global variable to store the session for cleanup
- any failure in pytest_sessionstart() triggers pytest.exit()
- make failure warnings more descriptive
```
If a session fixture fails in pre-configuring our image, there is no point in reporting many test failures. One failure with a better message would be preferred.
Example output:
```
!!! _pytest.outcomes.Exit: <class 'TimeoutError'> in session fixture setup: !!!!
================ 203 deselected, 1 warning in 130.94s (0:02:10) ================
integration-tests-ci: exit 2 (133.56 seconds) /home/runner/work/cloud-init/cloud-init> …
```
> test: exit on pytest session fixture failure

- cloudinit/config/cc_set_passwords.py
- cloudinit/distros/__init__.py
- tests/unittests/config/test_cc_set_passwords.py
```
fix: don't deadlock when starting network service with systemctl
```
https://github.com/canonical/cloud-init/issues/5930
> fix: don't deadlock when starting network service with systemctl

- doc/rtd/howto/launch_lxd.rst
- tools/.github-cla-signers
```
docs: fix typo in generated file usage for launch_lxd doc 
File was created with name "user-data.yaml".
But later it was used several times with typo in it.
```
> docs: fix typo in generated file usage for launch_lxd doc

- cloudinit/config/cc_chef.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tools/.github-cla-signers
Added `config_path` property to `cc_chef` to enable changing of Chef configuration path. Enables better support of community Chef forks (e.g. [Cinc](https://cinc.sh)).
> feat(cc_chef): Allow change of Chef configuration file

- .github/workflows/alpine-unittests.yml
- .github/workflows/integration.yml
```
ci: bump canonical/setup-lxd to version v0.1.2
Fixes lxd alpine runner.
```
The image server is down, so this test still fails, however it fixes the permission issue on 24.04.
> ci: fix lxd alpine runner

- systemd/cloud-config.service
- systemd/cloud-final.service
- systemd/cloud-init-local.service.tmpl
- systemd/cloud-init-network.service.tmpl
(OpenBSD) netcat installs itself by default only as "nc", *not* as "netcat" (the latter longer name is an ubuntu (or debian?) add-on).
Use the upstream-provided binary name.
fix: use program name of netcat as installed by upstream, "nc" (#5933)
> fix: use program name of netcat as installed by upstream, "nc"

- cloudinit/sources/helpers/openstack.py
- tests/unittests/sources/test_configdrive.py
It is possible that we outrun udev and when we try to enumerate the macs any given mac may not yet be present. If we detect the condition give udev a chance to catch up and check the system macs again before triggering an error.
Fixes #4125
This mostly addresses the issue observed in #4125. There are still corner cases where this change would not totally prevent the problem. 
Customer running into this condition has verified that this change addresses their issue on SLE.
> Wait for udev

- cloudinit/sources/DataSourceEc2.py
- cloudinit/sources/DataSourceScaleway.py
- cloudinit/sources/azure/imds.py
- cloudinit/sources/helpers/ec2.py
- cloudinit/sources/helpers/openstack.py
- cloudinit/url_helper.py
- tests/unittests/sources/helpers/test_ec2.py
- tests/unittests/sources/test_ec2.py
- tests/unittests/test_data.py
- tests/unittests/test_url_helper.py
Follow-up to https://github.com/canonical/cloud-init/pull/5578
```
feat(url_helper): Retry on 503 error
If the server is busy, no need to fail.
Add type hints to adjascent code paths
and necessary refactors.
Fixes GH-5577
```
> Retry on 503

- cloudinit/distros/__init__.py
Introduction of new WARNING level logs could be problematic for stable
downstream distros. Customers using these distros would then see a new and
unexpected behavior change or a new WARNING log that can confuse them. So for
handling user account passwords, use log_with_downgradable_level() helper api
instead so that downstream distros can maintain stability while also making
progressive changes in upstream towards improved user experience.
Downstream distros can convert these logs to DEBUG level by setting
DEPRECATION_INFO_BOUNDARY to a value older than the cloud-init version at which
these logs were first introduced (24.3). Please see the documentation for
log_with_downgradable_level().
> Use log_with_downgradable_level for user password configuration warnings

- setup_utils.py
```
fix: Use /usr/lib/ rather than /lib in packaging code
Support for unmerged /usr was removed from systemd a while ago:
https://lists.freedesktop.org/archives/systemd-devel/2022-September/048352.html
Furthermore, Debian tooling will now throw lintian errors if files
continue to reference /lib. Since it is no longer supported in upstream
systemd, there is no reason for it to be supported in upstream
cloud-init code that uses systemd.
```
> fix: Use /usr/lib/ rather than /lib in packaging code

- cloudinit/sources/DataSourceEc2.py
- cloudinit/sources/DataSourceExoscale.py
- cloudinit/url_helper.py
- tests/unittests/test_url_helper.py
```
fix: Don't log error in wait_for_url
There are use cases where we may want to recover or not treat a failure
of this function as an error. This change lets the caller decide what
to do.
Logging was added to callsites that didn't already have it.
Fixes GH-5971
```
#5971
> fix: Don't log error in wait_for_url

- cloudinit/cmd/main.py
- tests/integration_tests/modules/test_cloud_config_archive.py
- tests/unittests/cmd/test_main.py
```
fix: Ensure _should_wait_via_user_data() handles all user data types
The function "_should_wait_via_user_data()" wasn't properly
handling user data that has a header that starts with
#cloud-config, but isn't cloud-config, like #cloud-config-archive
Fixes GH-5975
```
> fix: Make _should_wait_via_user_data() handle non-dict data

- doc/rtd/development/integration_tests.rst
- tests/integration_tests/clouds.py
N/A
Separate commits, plz rebase :blue_heart: 
This will allow for manually specifying instance types when needing to reproduce certain bugs or test certain instance types (like Baremetal!)
Also, put some duct tape over the metaphorical mouths of urllib3 and botocore for integration tests to lessen log spam.
Run an integration test locally with INSTANCE_TYPE specified:
```
CLOUD_INIT_INSTANCE_TYPE="m6in.32xlarge" tox -e integration-tests -- tests/integration_tests/modules/test_hotplug.py::test_multi_nic_hotplug_vpc
```
> add INSTANCE_TYPE integration settings and lessen integration log spams

- cloudinit/cmd/devel/hotplug_hook.py
- cloudinit/sources/DataSourceEc2.py
- cloudinit/sources/__init__.py
- doc/module-docs/cc_install_hotplug/data.yaml
- tests/integration_tests/modules/test_hotplug.py
- tests/unittests/cmd/devel/test_hotplug_hook.py
- tools/hook-hotplug
```
fix: Retry AWS hotplug for async IMDS
Make tests more robust to temporary network failure.
Document hotplug limitations.
Fixes GH-5373
```
https://github.com/canonical/cloud-init/issues/5373#issuecomment-2265450589
```bash
CLOUD_INIT_PLATFORM="ec2" CLOUD_INIT_INSTANCE_TYPE="m6in.32xlarge" CLOUD_INIT_OS_IMAGE="noble" CLOUD_INIT_CLOUD_INIT_SOURCE="./cloud-init_all.deb" tox -e integration-tests -- tests/integration_tests/modules/test_hotplug.py::test_multi_nic_hotplug_vpc
```
> fix: retry AWS hotplug for async IMDS

- cloudinit/config/cc_ansible.py
- tests/unittests/config/test_cc_ansible.py
- tools/.github-cla-signers
```
fix: Run ansible with run_user instead of root for distro install_method
Added constructor for AnsiblePullDistro that handels which user to run
playbook with
```
Fixes GH-4092
> fix: Run ansible with run_user instead of root for distro install_method

- cloudinit/sources/DataSourceGCE.py
- tests/unittests/sources/test_gce.py
This commit addresses issue #5997 which reported crashes in init-local when cloud-init was examining GCELocal as a potential datasource. When all NICs failed at DHCP discovery cloud-init attempts to log the events by dereferencing a value that was never assigned.
This commit modifies the _get_data function of DataSourceGCE.py by adding an empty dictionary definition for the ret variable at the top level of the function and some debugging logs when a candidate NIC fails to obtain a DHCP lease. At the same time, the commit replaces the direct key access operator on ret with the safe lookup method get(). This commit also adds a unit test that mocks the observed situation
Fixes GH-5997
> Fix: GCE _get_data crashes if DHCP lease fails (#5997)

- debian/changelog
- debian/patches/no-single-process.patch
https://github.com/canonical/cloud-init/issues/6001
> Ubuntu/focal: wait for mounts

- cloudinit/config/cc_ubuntu_autoinstall.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- doc/module-docs/cc_ubuntu_autoinstall/data.yaml
- tests/unittests/config/test_cc_ubuntu_autoinstall.py
> Clarify subiquity docs

- cloudinit/util.py
- tests/unittests/test_util.py
- tools/.github-cla-signers
Fixes #5989 
- Explicitly cast `fqdn` to a string before processing.
> fix: Ensure fqdn is always treated as a string in get_hostname_fqdn

- cloudinit/net/sysconfig.py
- tests/unittests/distros/test_netconfig.py
In some distros, `/etc/sysconfig/network` may have important configurations that are necessary for the instance to come up. For example, centos based distros write `NOZEROCONF=yes` in `/etc/sysconfig/network` for some instances that require zeroconf to be disabled. Removing these customizations would prevent the instance to come up. So leave the customizations in `/etc/sysconfig/network` intact except those that we are interested in.
Fixes GH-5990
Signed-off-by: Ani Sinha <anisinha@redhat.com>
> net/sysconfig: do not remove all existing settings of /etc/sysconfig/network

- tests/integration_tests/clouds.py
- tests/integration_tests/modules/test_ansible.py
- tests/integration_tests/modules/test_apt_functionality.py
- tests/integration_tests/modules/test_combined.py
- tests/integration_tests/modules/test_frequency_override.py
- tests/integration_tests/modules/test_ubuntu_drivers.py
- tests/integration_tests/test_networking.py
- tests/integration_tests/util.py
I should probably squash these once this is done being reviewed and ready to be merged right?
Tested locally using the following script:
```
declare -A tests
tests["focal"]="tests/integration_tests/modules/test_frequency_override.py::test_frequency_override \
tests/integration_tests/modules/test_ansible.py::test_ansible_pull_pip \
tests/integration_tests/modules/test_ubuntu_drivers.py::test_ubuntu_drivers_installed \
tests/integration_tests/modules/test_apt_functionality.py::test_install_missing_deps \
tests/integration_tests/modules/test_boothook.py::TestBoothook::test_boothook_header_runs_part_per_instance \
tests/integration_tests/modules/test_boothook.py::TestBoothook::test_boothook_waits_for_network"
tests["jammy"]="tests/integration_tests/modules/test_frequency_override.py::test_freq …
```
> Fixing oracle integration tests

- .github/workflows/packaging-upstream.yml
```
ci: don't reference PR in post-merged CI
```
https://github.com/canonical/cloud-init/actions/runs/13292819865/job/37117524229
> ci: don't reference PR in post-merged CI

- doc/rtd/reference/datasources/lxd.rst
- tools/.github-cla-signers
All other references to old `user.vendor-data` and `user.user-data` were replaced by their newer counterparts `cloud-init.vendor-data` and `cloud-init.user-data`, but apparentely these ones were lingering still.
> doc: Update references to older keys

- tests/integration_tests/modules/test_disk_setup.py
```
test: Add integration test for /var mounts
```
> test: Add integration test for /var mounts

- cloudinit/sources/DataSourceAliYun.py
- cloudinit/sources/DataSourceEc2.py
- cloudinit/sources/helpers/aliyun.py
- tests/unittests/sources/test_aliyun.py
- tests/unittests/sources/test_ec2.py
```
In the pr: https://github.com/canonical/cloud-init/pull/5838,
we discussed the optimization of improving the startup
speed of cloudinit, which is to provide a path in the IMDS server
to return all instance metadata information at once. This PR
is mainly due to the support of this feature in the aliyun data
source. We separated the data source from EC2, of course, we also
reused some tool functions of EC2. The benefits of the separation
are obvious. Prior to this, some behaviors of EC2 affected Alibaba
Cloud, such as the device number attribute in network configuration.
https://bugs.launchpad.net/cloud-init/+bug/1917875
The update made this time are as follows
1. Separate the Alibaba Cloud data source from ec2 and make it
independent
2. Alibaba Cloud data sources will prioritize …
```
> feat: aliyun datasource support crawl metadata at once

- .github/workflows/packaging-tests.yml
If merged, I'll include a snapshot of upstream in this PR and duplicate it to the other branches: https://github.com/canonical/cloud-init/pull/6035
Then we'll want the same included in new_upstream_snapshot.py
> ci: check for sorted patches

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
```
feat(azure): Fix imds-based ssh_pwauth
To enable/disable password authentication is only possible in the OVF code path.
If OVF is unavailable, we fall back to IMDS and we want to have the same logic.
```
> feat(azure): Fix imds-based ssh_pwauth

- .github/workflows/packaging-upstream.yml
https://github.com/canonical/cloud-init/actions/runs/13439618723/job/37550455311#step:2:857
> ci: fix post-merge packaging CI

- tests/integration_tests/conftest.py
```
fix: when get_session_cloud() fails, _SESSION_CLOUD isn't set
Which causes this secondary failure:
INTERNALERROR> During handling of the above exception, another exception occurred: INTERNALERROR>
<snip>
INTERNALERROR>   File "/home/holmanb/ci/tests/integration_tests/conftest.py", line 490, in pytest_sessionstart
INTERNALERROR>     if _SESSION_CLOUD:
INTERNALERROR>        ^^^^^^^^^^^^^^
INTERNALERROR> NameError: name '_SESSION_CLOUD' is not defined
```
> fix: when get_session_cloud() fails, _SESSION_CLOUD isn't set

- debian/changelog
- debian/control
Since plucky is past feature freeze, let's just fix the bug rather than add a new metapackage now.
See: https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2098988
> Ubuntu/plucky 25.1.x: fix passlib dependency

- cloudinit/sources/azure/errors.py
- tests/unittests/sources/azure/test_errors.py
```
feat(azure): format ReportableErrorImdsInvalidMetadata's value without repr()
repr() is used to capture the value, and value is later formatted with str().  The
conversion with repr() maintains most accurate output, but the quote handling
causes confusion for the typical case.  Drop repr usage and add additional
supporting data indicating type.
Current error example:
\```
Azure datasource failure occurred: result=error|reason=invalid IMDS metadata for
key=extended.compute.ppsType|agent=Cloud-Init/24.4
0ubuntu1~20.04.1|key=extended.compute.ppsType|'value=''Running'''|vm_id=dd9d1a15-9289-4a87-a338
3caf2d8df7e0|timestamp=2025-02-09T10:17:46.481069+00:00|documentation_url=https://aka.ms/linuxprovisioningerror
\```
Proposed output example:
\```
Azure datasource failure occurred: …
> feat(azure): format ReportableErrorImdsInvalidMetadata's value without repr()

- cloudinit/signal_handler.py
- tests/integration_tests/modules/test_power_state_change.py
- tests/integration_tests/test_signal_handler.py
```
test: Add integration test for signal handling warnings/errors
Also, added context above "traceback" in log output.
```
> test: Add integration test for signal handling warnings/errors

- cloudinit/url_helper.py
```
fix: stop warning on dual-stack request failure
Failure from one or more endpoints may be expected, yet logging
warning means we will return 2.
```
> fix: stop warning on dual-stack request failure

- tests/integration_tests/cmd/test_schema.py
- tests/integration_tests/modules/test_combined.py
- tests/integration_tests/util.py
```
test: decouple netplan integrations from libnetplan SRU
The netplan.io SRU on Jammy is in an unresolved publication state for 140 days. Avoid hard-coding cloud-init integration tests to expect a specific series to contain libnetplan and instead check the instance under test to confirm python3-netplan is installed before validating cloud-init behavior.
```
Jammy integration tests should not expect libnetplan yet (until netplan.io version 0.107 gets SRU''d)
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-azure-generic/lastSuccessfulBuild/testReport/junit/tests.integration_tests.modules.test_combined/TestCombined/test_netplan_permissions/
```
CLOUD_INIT_PLATFORM=lxd_container CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily …
```
> test: decouple netplan integrations from libnetplan SRU

- tests/unittests/sources/test_openstack.py
- tests/unittests/util.py
```
test: correctly mock fallback nic in openstack tests
Previously, the mock distro would present a mock fallback interface
resulting in invalid IP addresses that would look something like:
fe80::a9fe:a9fe%25<MagicMock name='mock.fallback_interface' id='138716823174880'>
```
> test: correctly mock fallback nic in openstack tests

- cloudinit/sources/DataSourceVMware.py
- doc/rtd/reference/datasources/vmware.rst
- tests/unittests/sources/test_vmware.py
- tests/unittests/test_upgrade.py
```
feat(vmware): Support network events
This patch updates the DataSource for VMware to support network
reconfiguration when the BOOT, BOOT_NEW_INSTANCE, and HOTPLUG
events are received.
Previously the datasource could only reconfigure the network if
a new instance ID was detected. However, due to features like
backup/restore, migrating VMs, etc., it was determined that it is
valuable to support reconfiguring the network without changing the
instance ID. This is because changing the instance ID also means
running the per-instance configuration modules, such as regenerating
the system's SSH host keys, which could lock out automation.
```
`NA`
```shell
make clean_pyc && PYTHONPATH="$(pwd)" python3 -m pytest -v tests/unittests/sources/test_vmware.py
```
```shell
make clean_pyc && …
```
> feat(vmware): Support network events

- cloudinit/config/cc_chef.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- tests/unittests/config/test_cc_chef.py
TODO: unit tests see individual commits
```
* chef: migrate files in old config directories for backups and cache
*   fix: correct the path for Chef's backups (#5994)
Corrected the path for chef file_backup_path in cc_chef, schema,
and test_cc_chef.
Followup to a0ebb8d3 which fixed cache.
```
> Chef backups cache migration

- cloudinit/sources/helpers/azure.py
```
fix(azure): reduce retry sleep interval for Wireserver
Reduce cloud-init latency on retries by setting retry sleep interval for Wireserver to 1 second.
```
> fix(azure): reduce retry sleep interval for Wireserver

- cloudinit/config/schemas/schema-network-config-v1.json
- cloudinit/sources/helpers/openstack.py
- doc/rtd/reference/network-config-format-v1.rst
- tests/unittests/sources/helpers/test_openstack.py
- tools/.github-cla-signers
This patch fixes regression caused by [0]
when setting mac_address for vlan subinterface is no longer propagated to netplan. The patch [0] changed behaviour of cloud-init between Bionic and Focal which on first glance looked like fixing only warning. But it was affecting netplan configuration.
This patch adds optional mac_address field to vlan subinterface.
[0] https://github.com/canonical/cloud-init/pull/5365
Related: #5364
> Allow to set mac_address for VLAN subinterface

- cloudinit/sources/DataSourceAzure.py
- tests/unittests/sources/test_azure.py
```
fix(azure): handle unexpected exceptions during obtain_lease()
During DHCP we have seen various errors arising due to network interfaces being renamed during discovery.
e.g. cloud-init unhandled exception: FileNotFoundError(2, ''No such file or directory'')'
Add a guard to catch any unexpected exception to avoid unexpected propagation of exception, e.g. FileNotFoundError.
```
> fix(azure): handle unexpected exceptions during obtain_lease()

- cloudinit/cmd/main.py
- tests/unittests/test_cli.py
This change ensures that a subcommand's usage information is provided to the user when an invalid argument is passed to the subcommand.
Fixes #4609 
```
fix: CLI shows incorrect usage when subcommand used erroneously
When a subcommand is provided with an invalid parameter, the CLI
outputs the top-level usage information. This change modifies this
behaviour such that the usage information of the respective
subcommand is displayed instead.
Fixes GH-4609
```
From issue:
Expected:
Providing and invalid optional parameter --invalid to a cloud-init sub-command should generate a usage statement for that sub-command
$ cloud-init clean --invalid
usage: /usr/bin/cloud-init clean [-h] [-l] [--machine-id] [-r] [-s] [-c {all,ssh_config,network} [{all,ssh_config,network} ...]]
/usr/bin/cloud-init …
> fix: cli: incorrect top-level usage output when subcommand provides invalid optional parameter

- cloudinit/sources/DataSourceOracle.py
- tests/unittests/sources/test_oracle.py
```
feat(oracle): downgrade warning log about falling back to IMDS
If an oracle instance does not configure networking in the initramfs and
thus cloud-init does not already have networking, a warning should NOT
be logged since ubuntu oracle images will soon be changed such that
networking will not be configured in initramfs for VMs that do not have
an ISCSI root/boot device.
```
The Canonical Public Cloud team is looking to make a change to the open-iscsi package in the near future that will modify the iscsi initramfs script such that on VMs that do not have iscsi boot or root devices, networking will NOT be configured in the initramfs since:
A) setting up the networking via DHCP is ridiculously slow (~10s) and cloud-init ephemeral network setup is very fast (~2s) 
B) this will allow for …
> feat(oracle): downgrade warning log about falling back to imds

- cloudinit/sources/DataSourceOracle.py
When a VNIC is attached to a private subnet and has a ULA address, the VNIC data given by the IMDS does not contain the "ipv6SubnetCidrBlock" entry and instead has a "subnetCidrBlock" entry set to null. To properly detect if we should configure a VNIC as ipv6 single stack, the key "ipv6VirtualRouterIp" must be present and the key "privateIp" must not be present. Previously, the key "ipv6SubnetCidrBlock" was assumed to be present on all VNICs configured for ipv6 single stack or dual stack, but that is not the case when using a private subnet with ULA addresses.
N/A
Oracle raised an issue a customer had where cloud-init hit a `KeyError` on an ipv6 only instance with ULA addresses. This change addresses this bug.
Tested against various instance configurations that had prefixes for ULA only, …
> fix(oracle): properly detect ipv6 only for private ULA addresses

- cloudinit/ssh_util.py
- tests/unittests/test_ssh_util.py
```
<type>fix: ensure system sshd_config is not overwritten<summary>  # no more than 72 characters
In some systems, Tumbleweed for instance, the system sshd_config is
stored in /usr/etc/ssh/sshd_config which is then set to inherit user
changes from /etc/ssh/sshd_config.d/*.conf to neatly handle updating
of system configuration without overwriting user configuration
However, previously we would check for /etc/ssh/sshd_config and if it
does not exist cloud-init would then write it's changes to
/etc/ssh/sshd_config instead of the 
/etc/ssh/sshd_config.d/50-cloud-init.conf that's used for all other
instances
To handle this if the sshd_config file does not exist, lets also check
for sshd_config.d. If the later then exists we know it's safe to use
write sshd_config.d/50-cloud-init.conf
```
This …
> Handle ssh_config being /usr and inheriting user configuration from sshd_config.d

- tools/run-lint
When using the Makefile the user has influence over the Python Interpreter to be used by setting an environment variable called PYTHON. We need to give the user the same option for running the linter and not force the linter to use a "python3" command which may or may not exist.
```
72 characters.
```
> Make lint interpreter configurable

- debian/changelog
- debian/control
Should be reviewed alongside https://github.com/canonical/cloud-init/pull/6139
```
Fix how cloud-init-base overwrites cloud-init files
Cloud-init is currently broken on `do-release-upgrade` to plucky. In
plucky, cloud-init's packaging has been broken out into multiple binary
packages:
- cloud-init-base contains almost all of what used to be cloud-init
minus some dependencies that aren't needed everywhere
- Additional cloud-specific packages will be made that contain
cloud-init-base + the dependencies needed for that cloud
- cloud-init now depends on cloud-init-base + all extra cloud-specific
dependencies.
This allows the cloud-init package to be essentially identical to what
the cloud-init package contained before with the advantage of being
able to install only `cloud-init-base` on …
```
> Ubuntu/devel 25.1.x

- debian/changelog
- debian/control
Should be reviewed alongside https://github.com/canonical/cloud-init/pull/6137
```
Fix how cloud-init-base overwrites cloud-init files
Cloud-init is currently broken on `do-release-upgrade` to plucky. In
plucky, cloud-init's packaging has been broken out into multiple binary
packages:
- cloud-init-base contains almost all of what used to be cloud-init
minus some dependencies that aren't needed everywhere
- Additional cloud-specific packages will be made that contain
cloud-init-base + the dependencies needed for that cloud
- cloud-init now depends on cloud-init-base + all extra cloud-specific
dependencies.
This allows the cloud-init package to be essentially identical to what
the cloud-init package contained before with the advantage of being
able to install only `cloud-init-base` on …
```
> Ubuntu/oracular 25.1.x

- setup_utils.py
This commit adds the possibility to specify a custom pkg-config binary path in build scripts using the PKG_CONFIG environment variable. Packages managers might use different pkg-config depending on the target platform.
Fixes GH-6099
```
chore: allow custom pkg-config binary path
This commit adds the possibility to specify a custom pkg-config binary path
in build scripts using the PKG_CONFIG environment variable. Packages
managers might use different pkg-config depending on the target platform.
Fixes GH-6099
```
Specific package managers might not define `pkg-config`, but rather `pkg-config-x86` (and so on for various arch) in  multi arch build systems.
> chore: allow custom pkg-config binary path

- cloudinit/net/__init__.py
- tests/unittests/test_net.py
Warn when interfaces are ignored based on `addr_assign_type`. See #6110 and #6111
```
fix: Reorder iface filters & warn on inherited MAC
This filter was originally introduced in bf7723e to prevent bonds and
vlans being included in `get_interfaces`. However, specific filtering
for vlans was implemented in ebc9ecb and the same was added for bonds
in e5f5421.
As of kernel commit cb6cf08, some USB NICs which use passthrough MAC
addresses will also report their MAC address as stolen. MAC
passthrough makes it possible for more than one physical interface to
use the same MAC, so provide a warning to make it clear what
is going on.
```
> fix: Reorder iface filters & warn on inherited MAC

- tests/unittests/test_ds_identify.py
refresh_rmc_and_interface module was dropped in GH-PR #2148 
ddb0721259f406 ("config: drop refresh_rmc_and_interface as RHEL 7 no longer supported")
Remove stale reference to it in `ds_identify` unit test.
> Remove reference to already removed refresh_rmc_and_interface module

- cloudinit/cmd/devel/hotplug_hook.py
- cloudinit/config/cc_install_hotplug.py
- tests/integration_tests/modules/test_hotplug.py
- tests/unittests/cmd/devel/test_hotplug_hook.py
- tests/unittests/config/test_cc_install_hotplug.py
This patch removes the handling of the udev remove action in the hotplug process to prevent the call trace shown below from being generated:
```
2025-03-21 19:38:43,116 - hotplug_hook.py[ERROR]: Received fatal exception handling hotplug!
File "/usr/lib/python3/dist-packages/cloudinit/cmd/devel/hotplug_hook.py", line 334, in handle_args
handle_hotplug(
File "/usr/lib/python3/dist-packages/cloudinit/cmd/devel/hotplug_hook.py", line 224, in handle_hotplug
try_hotplug(subsystem, event_handler, datasource)
File "/usr/lib/python3/dist-packages/cloudinit/cmd/devel/hotplug_hook.py", line 257, in try_hotplug
raise last_exception
File "/usr/lib/python3/dist-packages/cloudinit/cmd/devel/hotplug_hook.py", line 246, in try_hotplug …
```
> fix: drop udev remove action in hotplug

- tests/integration_tests/modules/test_cli.py
- tests/integration_tests/modules/test_combined.py
- tests/integration_tests/util.py
```
tests: fix ibm expected warnings on invalid vendor-data schema
- also test_combined expects IBM datasource NoCloud [seed=/dev/vda]
```
Want to reduce the amount of IBM test failures seen given that we know the vendor-data schema delivered in IBM images uses deprecated schema.
Kick any IBM jenkins job and see 40 repeated test failures, a good portion of which fail due to verify_clean_boot getting a non-zero exit code on `cloud-init schema --system --annotate` because of deprecated vendor-data https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-ibm-generic
> tests: fix ibm expected warnings on invalid vendor-data schema

- tests/integration_tests/modules/test_cli.py
- tests/integration_tests/util.py
Verified testing locally with the correct full `Invalid schema: vendor-data` message 
```
CLOUD_INIT_PLATFORM=ibm CLOUD_INIT_OS_IMAGE=focal  CLOUD_INIT_CLOUD_INIT_SOURCE=NONE tox -e integration-tests -- tests/integration_tests/modules/test_cli.py 
```
>     tests: ibm logged message is Invalid schema: vendor-data

- cloudinit/stages.py
- tests/integration_tests/datasources/test_lxd_discovery.py
```
test: fix integration test on new lxd versions
```
Observed on lxd version 6.3:
```bash
>       assert "#cloud-config\ninstance-id" in ds_cfg["meta-data"]
E       AssertionError: assert '#cloud-config\ninstance-id' in 'instance-id: 31115406-0687-4110-9af1-0f5597e62919\nlocal-hostname: cloudinit-0411-223256hhan8767\npublic-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCqpCozNyoIR4yR5UGrjUg4HzfDs0voCchtGzRcYc1HO83rgPJGHMSFi5WuiLCZtWMtLShnZBxwouXo03mnYPe1dC1QBas2QZIEgJ9Piq+c3kS/YxIf0R2UNg/laYeRNpNtz5zuC+gBQpz5BWLGL39PUHyW6eBtIdpl2CrOASN56pK6Hk285ZphFVWDc+GyxqM1s1E1qH8NmtX2RKl9/LV/LWcPqwkwWMaV9PmdoiwKekJb9xNJiE0HEwdgE55FCSVzMMxJtGZaSHfva8qDamW/IK5JB7RM5u2aC71yWZI8DOXEPHFxKBWBJO4eMQPLQp4ACq8fEWqzci3Ieu9AzmGBa4PCiWA70flPoU09U8daqoYjZei/az1H0CAObaWeDo/pU8bN4CUX8ap3+RU3UzD5JMcZs9jy2VG1nbrM5CYM9E …
```
> Quick LXD integration fix

- config/cloud.cfg.tmpl
```
fix(alpine): do not enable cc_reset_rmc for Alpine Linux
cc_reset_rmc module relies upon binaries from IBM Power Tools which
IBM only provides for Enterprise Linux distros. These binaries are
almost certainly compiled using glibc, whereas Alpine uses musl.
Therefore remove reset_rmc from the list of cloud_final_modules in
the cloud.cfg generated for Alpine from the template.
```
> fix(alpine): do not enable cc_reset_rmc for Alpine Linux

- cloudinit/url_helper.py
- tests/unittests/sources/test_maas.py
```
fix: ensure MAAS datasource retries on failure
All MAAS requests get an `exception_cb` added dynamically via the
`OauthUrlHelper`. Ensure these callbacks adhere to the requirement
added in 1a515532 that an `exception_cb` return True if the exception
is not to be raised from the handler.
LP: #2106671
```
> fix: ensure MAAS datasource retries on failure

- debian/changelog
- debian/cloud-init-base.preinst
```
Some environments will not have an /etc/fstab (LXC). Return early instead of leaking fatal awk messages and catching non-zero exit codes.
Also fix shellcheck: drop unused $oldver from fix_ephemeral0_micro
GH: #6148
```
Found error messages from packaging preinst during testing installs of cloud-init-base when no cloud-init package is present in the image.
```
lxc launch ubuntu-daily:plucky dev-p
lxc exec dev-p -- apt remove cloud-init cloud-init-base --assume-yes
lxc exec dev-p -- apt install cloud-init --assume-yes | grep fstab
```
> fix(d/cloud-init-base.preinst): avoid sed of /etc/fstab when absent

- setup.py
```
fix: setup.py doesn't match CPE releases on RHEL /etc/system-release-cpe
python3.12 setup.py build reports invalid escape sequence '\o'
For years we've had an invalid escape sequence that didn't correctly match CPE images from RHEL.
The correct string match seen in /etc/system-release-cpe format is:
cpe:/o:redhat:enterprise_linux:9:baseos or
cpe:/o:fedoraproject:fedora:17
Reference: https://linux.org/docs/man5/os-release.html
```
> fix: setup.py doesn't match CPE releases on RHEL /etc/system-release-cpe

- cloudinit/sources/DataSourceCloudStack.py
- tests/unittests/sources/test_cloudstack.py
- tests/unittests/sources/test_common.py
This commit adds a new local datasource, CloudStackLocal, which supports ephemeral networking and parallels the structure of other cloud provider datasources. In particular this functionality is enabled by performing DHCP setup contingently on the perform_dhcp_setup parameter. Each detected NIC is presented sequentially as a candidate for networking and performs DHCP discovery. If a lease is not obtained, a subsequent NIC is tried. Otherwise upon success, we try to reach the IMDS. If this were to fail for some reason, we continue to the next NIC. Upon successful data retrieval from the IMDS we return. The communication with the IMDS has been wrapped in a new function: _crawl_metadata for improved modularity.
The motivation for this patch is outlined in GH issue #6143, which highlighted …
> Fix: Add Ephemeral Network for CloudStackLocal DS

- cloudinit/config/cc_ansible.py
- cloudinit/config/cc_bootcmd.py
- cloudinit/config/cc_package_update_upgrade_install.py
- cloudinit/config/cc_power_state_change.py
- cloudinit/signal_handler.py
- cloudinit/subp.py
- tests/unittests/test_signal_handler.py
```
fix: stop reporting error if cloud-init receives signal
It's too hard to predict when exactly cloud-init might receive a
legitimate signal (such as reboot), and even if we correctly predicted
it, the handling of it can still be racy.
Instead, log the current state and exit 0.
Fixes GH-6151
```
> fix: stop reporting error if cloud-init receives signal

- tests/unittests/test_ds_identify.py
- tools/ds-identify
I don’t think that the MAAS datasource specifically requires custom cloud.cfg parsing.
MAAS uses curtin to set debconf selections [1][2]
Curtin uses cloud-init’s postinst to write out MAAS preseed[3], which is what that ds-identify `check_config()` call[4] is checking for.
Before cloud-init’s postinst writes out the MAAS preseed, it writes out `/etc/cloud/cloud.cfg.d/90_dpkg.cfg` with a `datasource_list: [ <values> ]`, which is the generic (non-maas specific) way of setting MAAS as the datasource.
I don’t think we need the custom MAAS config parsing code that currently exists in cloud-init - it is redundant.
Removing this eliminates known false positives: known cloud-init platform miss-identifications.
Related to https://github.com/canonical/cloud-init/issues/4796
[1] …
> Simplify maas check

- cloudinit/net/__init__.py
- tests/unittests/net/test_init.py
udevadm settle may fail due to circumstances outside of cloud-init's control.  We regularly see reports of udevadm settle timeouts due to a deadlock between a udev action waiting on something that happens after cloud-init-local.service.  While it can be considered misconfiguration, cloud-init should treat the outcome as best-effort and move on.
Fixes #6184
> fix(net): ignore udevadm failures when enumerating nics

- doc/examples/cloud-config-ansible-controller.txt
- doc/examples/cloud-config-ansible-managed.txt
- doc/examples/cloud-config-user-groups.txt
- doc/examples/cloud-config.txt
- doc/rtd/reference/datasources/vmware.rst
- doc/rtd/reference/datasources/wsl.rst
- doc/rtd/reference/yaml_examples/ansible_controller.rst
- doc/rtd/reference/yaml_examples/ansible_managed.rst
- doc/rtd/reference/yaml_examples/user_groups.rst
- tests/data/merge_sources/expected7.yaml
- tests/data/merge_sources/source7-1.yaml
- tests/integration_tests/modules/test_ansible.py
- tests/integration_tests/modules/test_cli.py
- tests/integration_tests/modules/test_users_groups.py
- tests/unittests/config/test_schema.py
```
docs: ensure proper 'sudo' representation
Some YAML parsers can choke on the ':' character if it isn't quoted,
so ensure all sudo examples are quoted.
Also, remove any `sudo: false` examples as that configuration is
deprecated.
Fixes GH-6195
```
Running with `sudo: false` results in:
```
2025-05-01 13:39:15,213 - loggers.py[DEPRECATED]: Deprecated cloud-config provided: users.5.sudo:  Changed in version 22.2. The value ``false`` is deprecated for this key, use ``null`` instead.
```
and
```
2025-05-01 13:39:15,612 - lifecycle.py[DEPRECATED]: The value of 'false' in user fizzbuzz's 'sudo' config is deprecated in 22.2 and scheduled to be removed in 27.2. Use 'null' instead.
```
> docs: ensure proper 'sudo' representation

- doc/rtd/howto/launch_lxd.rst
- doc/rtd/howto/launch_qemu.rst
- doc/rtd/howto/shared/download_image.txt
- doc/rtd/tutorial/qemu-script.sh
- doc/rtd/tutorial/qemu.rst
```
docs: Use Noble for examples instead of Jammy
```
The docs refer to "the latest Ubuntu LTS", which is Noble these days, not Jammy.
I tested that `https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img` is indeed a working URL as well.
> docs: Use Noble for examples instead of Jammy

- cloudinit/config/cc_ansible.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- doc/examples/cloud-config-ansible-pull.txt
- doc/module-docs/cc_ansible/data.yaml
- doc/module-docs/cc_ansible/example1.yaml
- doc/module-docs/cc_ansible/example2.yaml
- doc/rtd/conf.py
- doc/rtd/templates/module_property.tmpl
- tests/integration_tests/modules/test_ansible.py
- tests/unittests/config/test_cc_ansible.py
```
feat: Support both list and dict type for ansible pull
Use both dict and list types for using ansible pull module
like setup_controller.
```
Fixes GH-4566
> feat: Change ansible pull module type from dict to list

- cloudinit/socket.py
- tests/unittests/test_cli.py
```
fix: make 'cloud-init --all-stages' work interactively
```
> fix: make 'cloud-init --all-stages' work interactively

- cloudinit/config/schemas/schema-network-config-v1.json
- cloudinit/net/netplan.py
- doc/examples/network-config-v1-subnet-routes.yaml
- doc/rtd/reference/network-config-format-v1.rst
- tests/unittests/config/test_schema.py
- tests/unittests/net/network_configs.py
- tests/unittests/test_net.py
```
feat: Add support of subnet metric for netplan
This patch enhances netplan configuration by adding support for subnet metrics. It implements metric handling for DHCP configurations by adding the subnet metric to DHCP overrides with the "route-metric" key. For static routes, it establishes a priority system where the route's metric takes precedence, followed by the subnet's metric, and finally defaulting to 100 if neither is specified. The patch also adds subnet metric support for default gateway routes. These changes provide more flexible network configuration options, allowing for better control over routing priorities in cloud-init generated netplan configurations from network config v1. 
```
> feat: Add subnet metric support for netplan

- cloudinit/net/dhcp.py
- cloudinit/net/ephemeral.py
- cloudinit/sources/helpers/azure.py
- tests/unittests/net/test_dhcp.py
- Fixup "dhclient" -> "dhcp client" in diagnostic message as client may be dhclient, dhcpcd, or others.
- Expand callback to include interface name which can be used in the diagnostic log.
- Add type definitions for callback function.
- Create VM on Azure.
- Verify DHCP diagnostic logs.
Should see something like this example output:
```
2025-05-27 22:27:38,366 - performance.py[DEBUG]: Running ['dhcpcd', '--ipv4only', '--waitip', '--persistent', '--noarp', '--script=/bin/true', 'eth0'] took 4.287 seconds
2025-05-27 22:27:38,366 - azure.py[DEBUG]: dhcp client stdout for interface=eth0:
2025-05-27 22:27:38,366 - azure.py[DEBUG]: dhcp client stderr for interface=eth0: dhcpcd-10.0.6 starting
DUID 00:01:00:01:2f:c8:f8:d6:60:45:bd:79:d7:b8
eth0: IAID bd:79:d7:b8
eth0: carrier lost
eth0: carrier …
```
> feat(azure): add interface to dhcp_log_func

- doc/rtd/reference/cli.rst
Hey @TheRealFalcon 
docs: include missing --seed datasource flags in cloud-init clean CLI doc. Addresses missing flags in clean.py reference documentation.
> docs: include missing --seed datasource flags in cloud-init clean CLI

- systemd/cloud-init-main.service.tmpl
```
fix: remove unnecessary 'Wants' from cloud-init-main.service
c61e42a unintentionally added an additional 'Wants' to
cloud-init-main.service. While there are no known problems with this,
there is also no known reason to include it.
```
I [called it out](https://github.com/canonical/cloud-init/pull/5827/files#r1878895648) in the PR, and the conversation was marked as resolved, so I mistakenly thought it was fixed.
> fix: remove unnecessary 'Wants' from cloud-init-main.service

- cloudinit/sources/DataSourceAzure.py
- cloudinit/sources/azure/errors.py
- cloudinit/sources/azure/kvp.py
- cloudinit/sources/helpers/azure.py
- tests/unittests/config/test_schema.py
- tests/unittests/sources/azure/test_errors.py
- tests/unittests/sources/azure/test_kvp.py
- tests/unittests/sources/test_azure.py
- tests/unittests/sources/test_azure_helper.py
- Only read system uuid and convert once.  As can be seen in the test mocks, in some cases it will be read multiple times when reporting error. Initialize IDs to None and save them. This required ReportableError to have its VM ID populated when we report failure instead of re-reading it on initialization.
- Report failure to read or convert into a ReportableError. Today, this failure is reported as unhandled exception.  I expect this happens on images that either restrict/limit DMI or otherwise use some access controls that cause breakage.  This doesn't fix it, but cleans up the reported error.
- Report a diagnostic for the detected VM ID.
> feat(azure): improve handling for reading VM ID

- cloudinit/config/cc_ca_certs.py
```txt
feat(ca_certs): Add CentOS support
CentOS is using the same PKI paths as RHEL.
```
In PR #5264 the `ca_certs` support of AlmaLinux and CloudLinux was added, both are configured as a derivation of RHEL.
The new PR adds CentOS as well, in the same manner.
Basically the same as for PR #5264
```yaml
#cloud-config
ca_certs:
remove_defaults: true
trusted:
- single_line_cert
- |
-----BEGIN CERTIFICATE-----
YOUR-ORGS-TRUSTED-CA-CERT-HERE
-----END CERTIFICATE-----
```
[x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
[ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
[ ] I have updated or added any …
> feat(ca_certs): Add CentOS support

- cloudinit/features.py
- cloudinit/net/netplan.py
- tests/unittests/net/test_netplan.py
- tests/unittests/test_data.py
- tests/unittests/test_features.py
```
fix: allow downstreams to strip invalid MTU
mtu: 0 is an invalid value within neptlan configuration, but cloud-init
allowed it in previous releases. This commit adds a flag to allow
cloud-init to strip it from downstreams to keep backwards compatibility.
Fixes GH-6239
```
If merged, we can add Ubuntu quilt patches for Jammy and Noble
> fix: allow downstreams to strip invalid MTU

- cloudinit/analyze/show.py
- tests/integration_tests/cmd/test_analyze.py
- tests/integration_tests/util.py
- tests/unittests/analyze/test_boot.py
```
fix[analyze-boot]: use monotonic clock for containers
Fixes GH-5773
```
Spin an lxd container and run `cloud-init analyze boot` . You will notice that the `Cloud-init activated by systemd at` timestamp is higher (should be lower) than the `Cloud-init start` timestamp
###Verifying the fix
`CLOUD_INIT_PLATFORM='lxd_container' CLOUD_INIT_OS_IMAGE='noble' tox -e integration-tests -- tests/integration_tests/cmd/test_analyze.py` using this source branch (which has the fix and the new integration test)
> fix[analyze-boot]: use monotonic clock for containers

- cloudinit/net/networkd.py
- tests/unittests/cmd/devel/test_net_convert.py
- tests/unittests/net/artifacts/photon_net_config/etc/systemd/network/10-cloud-init-bond.200.netdev
- tests/unittests/net/artifacts/photon_net_config/etc/systemd/network/10-cloud-init-bond.200.network
- tests/unittests/net/artifacts/photon_net_config/etc/systemd/network/10-cloud-init-bond0.netdev
- tests/unittests/net/artifacts/photon_net_config/etc/systemd/network/10-cloud-init-bond0.network
- tests/unittests/net/artifacts/photon_net_config/etc/systemd/network/10-cloud-init-eth0.network
- tests/unittests/net/artifacts/photon_net_config/etc/systemd/network/10-cloud-init-eth1.network
- tests/unittests/net/artifacts/photon_net_config/etc/systemd/network/10-cloud-init-eth2.network
- tests/unittests/net/artifacts/photon_net_config/etc/systemd/network/10-cloud-init-vl101.netdev
- tests/unittests/net/artifacts/photon_net_config/etc/systemd/network/10-cloud-init-vl101.network
- tests/unittests/net/artifacts/photon_net_config/etc/systemd/network/10-cloud-init-vlan100.netdev
- tests/unittests/net/artifacts/photon_net_config/etc/systemd/network/10-cloud-init-vlan100.network
- tests/unittests/net/artifacts/photon_net_config_v2.yaml
- tests/unittests/net/network_configs.py
- tests/unittests/net/test_net_rendering.py
feat(networkd): support vlan and bond rendering
```
Networkd renderer used in Photon OS doesn't support vlan and bond settings specified through network config yaml.
This is an effort towards supporting the same in networkd renderer.
```
> vlan and bond support in networkd

- cloudinit/net/eni.py
- tests/unittests/net/network_configs.py
```
fix(ENI): render keys with hyphens
In ENI spaces within keys can be represented as hyphens or underscores.
Standardize on hyphens.
Fixes GH-5234
Signed-off-by: Alberto Contreras <alberto.contreras@canonical.com>
```
> fix(ENI): render keys with hyphens

- tests/integration_tests/test_upgrade.py
```
test: increase timeout on test_clean_package_install
Creating a snapshot and launching from that can take a long time.
```
I'm aware that random timeouts are often bad. Without this one we can leave the entire job hanging for several hours until it gets killed by jenkins, so we can't get rid of it here.
> test: increase timeout on test_clean_package_install

- tests/unittests/conftest.py
Fix an issue in an environment where TMPDIR is not set to /tmp where 22 tests fail. These tests have codepaths that use TemporaryDirectory(). Create a TMPDIR equivalent under the fake_filesystem.
I'm looking at a different problem (LP: #[2118989](https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/2118989)) and found this when simply trying to unittest main branch.
```
fix(tests): handle TMPDIR != "/tmp"
Fix an issue in an environment where TMPDIR is not set to /tmp where 22
tests fail. These tests have codepaths that use TemporaryDirectory().
Create a TMPDIR equivalent under the fake_filesystem.
```
> fix(tests): handle TMPDIR != "/tmp"

- cloudinit/cmd/clean.py
- cloudinit/config/cc_mounts.py
- cloudinit/sources/DataSourceAzure.py
- doc/rtd/reference/cli.rst
- tests/unittests/cmd/test_clean.py
A new `cloud-init clean -c fstab` option is introduced that would clean all fstab entries that have "comment=cloudconfig" comment. It refactors code already present in DataSourceAzure.clean() method added as a part of the change 08a9dcf34445be572 ("feat(azure): Implement the clean callback for DataSourceAzure (#6321)")
Fixes: GH-6341
> feat(clean): Add a new clean option to clean fstab entries

- tests/integration_tests/modules/test_combined.py
```
test: support systemctl try-reload-or-restart messaging alternatives
systemd 251 changed response message text from reload-or-try-restart to
try-reload-or-restart
```
Jenkins failures seen on Ubuntu noble but not questing due to systemd name changes.
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-lxd_container-minimal/116/testReport/junit/tests.integration_tests.modules.test_combined/TestCombined/test_no_problems/
```
CLOUD_INIT_KEEP_INSTANCE=1 CLOUD_INIT_OS_IMAGE_TYPE=minimal CLOUD_INIT_OS_IMAGE=questing CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily tox -e integration-tests -- tests/integration_tests/modules/test_combined.py::TestCombined::test_no_problems
CLOUD_INIT_KEEP_INSTANCE=1 CLOUD_INIT_OS_IMAGE_TYPE=minimal …
```
> test: support systemctl try-reload-or-restart messaging alternatives

- tools/cloud-init-hotplugd
```
fix: cloud-init-hotplugd: remove use of "exec" and unnecessary exit
"exec" should not have been used to call cloud-init so remove it, also
only call "cloud-init devel hotplug-hook" when there are arguments to
pass to it.
The "exit" at the end of the script is unnecessary, so remove it.
Fixes GH-6351
```
> fix: cloud-init-hotplugd: remove use of "exec" and unnecessary exit

- tests/integration_tests/modules/test_apt_functionality.py
- tests/integration_tests/releases.py
```
test: skip gpg dependency test on questing
The test involves removal of Ubuntu core packages. On Questing,
this results in the gpg package being in a broken state that cannot
be recovered by simply installing gnupg.
```
> test: skip gpg dependency test on questing

- debian/changelog
- debian/control
Without this, one can manually `apt install cloud-init` and receive an updated version of `cloud-init` without the corresponding updated `cloud-init-base`. Since all of the functionality is contained within `cloud-init-base`, this wouldn't be what anybody wants.
> Ubuntu/devel: ensure binary versions match

- tox.ini
```
chore(tox): align check_format's pylint folder targets
Use the same folder targets of tox -e pylint.
Otherwise `tox -e check_format`'s pylint and `tox -e pylint` targets
differ, targeting additional folders as doc/ or .tox/ that are not
covered by CI.
```
> chore(tox): align check_format's pylint folder targets

- cloudinit/net/network_state.py
- cloudinit/net/networkd.py
```
feat(network_state): render vlan, bond, bridge device mac address properly in network state
Currently mac_address given through config yaml is ignored and mac address is not accessible
while iterating through interfaces.
```
> Render vlan, bond, bridge device mac address properly in network state

- conftest.py
- tests/unittests/helpers.py
- tests/unittests/sources/test_init.py
- tests/unittests/test_conftest.py
```
test: remove CiTestCase fully
```
It depends on https://github.com/canonical/cloud-init/pull/6410, https://github.com/canonical/cloud-init/pull/6413 and, https://github.com/canonical/cloud-init/pull/6415.
> test: remove CiTestCase fully

- tests/unittests/early_patches.py
```
test: fix lru_cache test wrapper
The position of the cached func in the decorator and decorated
signatures varies depending on how the decorator is called (with or
without args). Fix the latter case.
Fixes tox -e hypothesis-slow.
Fixes GH-5869
```
https://github.com/canonical/cloud-init/actions/runs/17380029255/job/49335144582
tox -e hypothesis-slow
> test: fix lru_cache test wrapper

- cloudinit/config/cc_rh_subscription.py
- cloudinit/config/schemas/schema-cloud-config-v1.json
- cloudinit/util.py
- doc/module-docs/cc_rh_subscription/example3.yaml
- doc/rtd/spelling_word_list.txt
- tests/unittests/config/test_cc_rh_subscription.py
- tests/unittests/test_util.py
```
feat(rh_subscription): new release_version field
Refs GH-6030
```
- Run a QEMU RHEL-10 VM with the following user-data (See more details in https://github.com/canonical/cloud-init/issues/6292#issuecomment-3144757542 on where to get the image from)
```
#cloud-config
password: 'somepasswordyouset'
chpasswd:
expire: False
rh_subscription:
username: 'yourredhatusername'
password: 'yourredhatpassword'
```
- Manually modify the cloudinit python script in the VM (under `/usr/lib/python3.12/site-packages/cloudinit`) withe file changes of this PR
- `sudo subscription-manager unregister`
- Add `releasever: 10` under rh_subscription in `/var/lib/cloud/instance/cloud-config.txt`
- `sudo cloud-init single --name cc_rh_subscription --frequency always`
> feat(rh_subscription): new release_version field

- tests/unittests/config/test_cc_runcmd.py
- tests/unittests/runs/test_merge_run.py
- tests/unittests/runs/test_simple_run.py
- tests/unittests/sources/test_smartos.py
This doesn't fix all warnings. Other valid ones exist which can be seen running `tox -e py3-fast`. Those will have to be fixed separately. Specifically:
```python3
tests/unittests/analyze/test_dump.py::TestParseCILogLine::test_parse_logline_returns_event_for_amazon_linux_2_line
/home/holmanb/ci-b/tests/unittests/analyze/test_dump.py:201: DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
and fails to parse leap day. The default behavior will change in Python 3.15
to either always raise an exception or to use a different default year (TBD).
To avoid trouble, add a specific year to the input & format.
See https://github.com/python/cpython/issues/70647.
datetime.strptime("Apr 30 19:39:11", "%b %d %H:%M:%S") …
```
> Fix test warnings

- packages/bddeb
```
fix: bddeb tool needs distro debian param for package dependency lookup
Use debian distro package renames and lookups when determining
system package names for test-requirements.txt.
Otherwise, pyserial dependency gets translated to invalid
system package name python3-pyserial.
```
Without this change current `make deb` target results in the following debuild errors:
```
make deb
...
dpkg-checkbuilddeps: error: Unmet build dependencies: python3-pyserial
```
> fix: bddeb tool needs distro debian param for package dependency lookup

- meson.build
- meson_options.txt
To allow for a low-dependency installation of cloud-init, optionalize the bash-completion dependency, defaulted to true. This means behaviorally nothing changes, but that the bash-completion features can be easily turned off if not desired.
```
feat: Optionalize bash completion.
To allow for a low-dependency installation of cloud-init, optionalize the
bash-completion dependency, defaulted to true. This means behaviorally
nothing changes, but that the bash-completion features can be easily
turned off if not desired.
```
n/a
* Testing: with bash-completion not installed, `meson build -Dbash-completion=false ...` runs successfully, `meson build -Dbash-completion=true ...` and with -D option omitted displays error.
> Optionalize bash completion.

- cloudinit/net/netplan.py
- packages/bddeb
See individual commits.
https://github.com/canonical/cloud-init/issues/6141
!! Note: Without this PR, running the tests will write to `/etc/netplan/50-cloud-init.yaml`
Run `pytest test/unittest` with the root user.
> 6141 fix bddeb running with root

- tests/integration_tests/instances.py
CLOUD_INIT_CLOUD_INIT_SOURCE=PROPOSED gets and exit 1 from `apt-get install -qy {pkg} -t=$(lsb_release -sc)-proposed` when local apt cache files on disk do not have a known suite yet for jammy-proposed. This exit 1 results  test teardown  during base image creation and failure to run any integration tests.
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-gce-generic/648/artifact/pytest.log
```
test: fix integration for PROPOSED to run apt update prior to install
```
> test: fix integration for PROPOSED to run apt update prior to install

- tests/unittests/test_registry.py
Refactored tests/unittests/test_registry.py to use pytest instead of unittest.TestCase as part of the pytest migration effort.
- Removed TestCase inheritance and replaced with pytest fixtures
- Converted self.assert* methods to bare assert statements
- Replaced self.assertRaises with pytest.raises context manager
- Added autouse fixture to reset global state
- Maintained all original test functionality
Related: #6427
> test: Convert test_registry.py from unittest to pytest

- cloudinit/net/eni.py
- tests/unittests/net/network_configs.py
- tests/unittests/sources/test_configdrive.py
- tests/unittests/test_net.py
```
feat(eni): support "ip route" if available instead of "route"
When adding post-up/pre-down entries to /etc/network/interfaces to
manage routes use the "ip" binary if available rather than the "route"
binary.
Fixes: GH-6250
```
> feat(eni): support "ip route" if available instead of "route"

- tests/integration_tests/modules/test_combined.py
Failing jenkins tests due to changes in `stat` command output in questing single quotes changed to double quotes.
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-questing-lxd_container-generic/lastSuccessfulBuild/testReport/junit/tests.integration_tests.modules.test_combined/TestCombined/test_cloud_id_file_symlink/
> test: add regex to cope with stat link output double/single quotes

- meson.build
```
fix: install doc files that were previously installed pre-Meson
The Meson-based installation does not install these text files whereas
the pre-Meson installation did, so reinstate them.
```
> fix: install doc files that were previously installed pre-Meson

- cloudinit/config/schemas/schema-cloud-config-v1.json
- doc/module-docs/cc_raspberry_pi/data.yaml
```
docs(cc_raspberry_pi): Better phrasing of config descriptions
```
@tdewey-rpi @lurch
> docs(cc_raspberry_pi): Better phrasing of config descriptions
